export interface HomeopathicRemedyInfo {
  name: string;
  latinName: string;
  germanName?: string;
  category?: 'Polychrest' | 'Pflanzlich' | 'Mineralisch' | 'Tierisch' | 'Nosode' | 'Säure' | 'Sonstige';
  defaultPotencies: string[];
  defaultTagesdosis: string;
  defaultHaeufigkeit: string;
  defaultAnwendungsdauer: string;
  defaultZeitraum: string;
  standardNote?: string;
  keyIndications?: string[];
}

export const COMMON_HOMEO_REMEDIES_DB: HomeopathicRemedyInfo[] = [
  {
    name: 'Aconitum napellus (Blauer Eisenhut)',
    latinName: 'Aconitum napellus',
    germanName: 'Blauer Eisenhut',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200', 'D12', 'D6'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '1 bis 3 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Bei plötzlichem Krankheitsbeginn nach Kälteeinwirkung / Schreck. Bei Besserung sofort pausieren.',
    keyIndications: ['Plötzlicher Beginn', 'Große Unruhe & Angst', 'Trockene Hitze', 'Nach Kaltwind']
  },
  {
    name: 'Allium cepa (Küchenzwiebel)',
    latinName: 'Allium cepa',
    germanName: 'Küchenzwiebel',
    category: 'Pflanzlich',
    defaultPotencies: ['D6', 'D12', 'C30'],
    defaultTagesdosis: '2 bis 3 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '2- bis 3-mal täglich',
    defaultAnwendungsdauer: '3 bis 5 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Fließschnupfen mit scharfem Nasensekret und mildem Tränenfluss.',
    keyIndications: ['Scharfer Fließschnupfen', 'Milder Tränenfluss', 'Besser an frischer Luft']
  },
  {
    name: 'Apis mellifica (Honigbiene)',
    latinName: 'Apis mellifica',
    germanName: 'Honigbiene',
    category: 'Tierisch',
    defaultPotencies: ['C30', 'D12', 'C200'],
    defaultTagesdosis: '2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '2 bis 4 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Brennende, stechende Schmerzen, Ödeme, Verschlimmerung durch Hitze, Besserung durch Kälte.',
    keyIndications: ['Stechende Schmerzen', 'Hellrote Schwellung/Ödem', 'Durstlosigkeit', 'Besser durch Kälte']
  },
  {
    name: 'Arnica montana (Bergwohlverleih)',
    latinName: 'Arnica montana',
    germanName: 'Bergwohlverleih',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200', 'D12', 'D6'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Erstes Mittel bei allen Traumata, Prellungen, Muskelkater und Wundheitsgefühl.',
    keyIndications: ['Trauma & Verletzung', 'Zerschlagenheitsgefühl', 'Bett fühlt sich zu hart an', 'Blutergüsse']
  },
  {
    name: 'Arsenicum album (Weißes Arsenik)',
    latinName: 'Arsenicum album',
    germanName: 'Weißes Arsenik',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Einmalgabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich morgens',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Große Schwäche, brennende Schmerzen gebessert durch Wärme, nächtliche Unruhe zwischen 1-3 Uhr.',
    keyIndications: ['Brennende Schmerzen', 'Große Unruhe', 'Besser durch Hitze', 'Periodizität']
  },
  {
    name: 'Belladonna (Tollkirsche)',
    latinName: 'Atropa belladonna',
    germanName: 'Tollkirsche',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'D12', 'C200'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '2 bis maximal 4 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Plötzlicher Beginn, pochender roter Kopf, weite Pupillen, Schmerzempfindlichkeit.',
    keyIndications: ['Pochende Schmerzen', 'Roter heißer Kopf', 'Licht- & Erschütterungsempfindlich']
  },
  {
    name: 'Bellis perennis (Gänseblümchen)',
    latinName: 'Bellis perennis',
    germanName: 'Gänseblümchen',
    category: 'Pflanzlich',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Tiefe Gewebsverletzungen, Becken- und Bauchraumtrauma, Überanstrengung.',
    keyIndications: ['Tiefe Gewebequetschung', 'Bauch- und Beckentrauma', 'Verstauchung']
  },
  {
    name: 'Bryonia alba (Weiße Zaunrübe)',
    latinName: 'Bryonia alba',
    germanName: 'Weiße Zaunrübe',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'D12', 'C200'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Strikte Verschlechterung bei geringster Bewegung, Besserung durch absolute Ruhe und Druck.',
    keyIndications: ['Schlechter bei Bewegung', 'Besser durch Ruhe & Liegen auf Schmerzseite', 'Großer Durst']
  },
  {
    name: 'Calcium carbonicum (Austernschalenkalk)',
    latinName: 'Calcium carbonicum Hahnemanni',
    germanName: 'Austernschalenkalk',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Einmalgabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich oder wöchentlich',
    defaultAnwendungsdauer: 'Einmalgabe / Intervallbeobachtung',
    defaultZeitraum: 'Konstitutionsbehandlung',
    standardNote: 'Klassisches Konstitutionsmittel bei langsamer Entwicklung, Kälteempfindlichkeit, Kopfschweiß im Schlaf.',
    keyIndications: ['Kopfschweiß im Schlaf', 'Kälteempfindlichkeit', 'Neigung zu Erschöpfung bei Anstrengung']
  },
  {
    name: 'Calcium phosphoricum (Kalziumphosphat)',
    latinName: 'Calcium phosphoricum',
    germanName: 'Kalziumphosphat',
    category: 'Mineralisch',
    defaultPotencies: ['D6', 'D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '5 bis 10 Tage',
    defaultZeitraum: 'Aufbau- und Regenerationsphase',
    standardNote: 'Wachstumsschmerzen, Rekonvaleszenz, Knochenheilung.',
    keyIndications: ['Wachstumsschmerzen', 'Verlangen nach Geräuchertem', 'Erschöpfung nach Krankheit']
  },
  {
    name: 'Calendula officinalis (Ringelblume)',
    latinName: 'Calendula officinalis',
    germanName: 'Ringelblume',
    category: 'Pflanzlich',
    defaultPotencies: ['D6', 'D12', 'C30'],
    defaultTagesdosis: '2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Wundheilungsphase',
    standardNote: 'Fördert Granulation und Wundheilung bei Riss- und Schnittwunden.',
    keyIndications: ['Wundheilung', 'Risswunden', 'Schmerzlinderung postoperativ']
  },
  {
    name: 'Cantharis vesicatoria (Spanische Fliege)',
    latinName: 'Cantharis vesicatoria',
    germanName: 'Spanische Fliege',
    category: 'Tierisch',
    defaultPotencies: ['C30', 'D12'],
    defaultTagesdosis: '2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '2-mal täglich',
    defaultAnwendungsdauer: '2 bis maximal 4 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Heftiges, schneidendes Brennen beim Wasserlassen, ständiger Harndrang.',
    keyIndications: ['Brennender Harndrang', 'Zystitis mit Schneideschmerz', 'Verbrennungen']
  },
  {
    name: 'Carbo vegetabilis (Holzkohle)',
    latinName: 'Carbo vegetabilis',
    germanName: 'Holzkohle',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Große Schwäche, Luftmangel mit Verlangen nach Zirkulation/Fächeln, Blähungsbauch.',
    keyIndications: ['Verlangen nach Luftzug/Fächeln', 'Kollapsneigung', 'Meteorismus']
  },
  {
    name: 'Causticum Hahnemanni',
    latinName: 'Causticum',
    germanName: 'Ätzkalkmischung nach Hahnemann',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'C200'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Initialphase',
    standardNote: 'Ausgeprägtes Mitgefühl mit anderen, Lähmungsneigung, Heiserkeit morgens.',
    keyIndications: ['Ungerechtigkeitsempfinden', 'Heiserkeit', 'Sehnenverkürzungen']
  },
  {
    name: 'Chamomilla (Echte Kamille)',
    latinName: 'Matricaria chamomilla',
    germanName: 'Echte Kamille',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'D12'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '2 bis maximal 4 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Extreme Reizbarkeit, unerträgliche Schmerzen, einseitig rote Backe, Besserung durch Herumtragen.',
    keyIndications: ['Überempfindlich gegen Schmerz', 'Reizbar & zornig', 'Zahnungsbeschwerden']
  },
  {
    name: 'China officinalis (Chinarinde)',
    latinName: 'Cinchona officinalis',
    germanName: 'Chinarinde',
    category: 'Pflanzlich',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Rekonvaleszenzphase',
    standardNote: 'Schwäche und Erschöpfung nach Flüssigkeitsverlust (Blut, Schweiß, Durchfall).',
    keyIndications: ['Flüssigkeitsverlust', 'Blähungen im gesamten Bauch', 'Überempfindliche Sinne']
  },
  {
    name: 'Cocculus indicus (Kockelskörner)',
    latinName: 'Cocculus indicus',
    germanName: 'Kockelskörner',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'D12'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Erschöpfung und Schwindel nach Schlafmangel, Nachtwachen und Sorge um Angehörige.',
    keyIndications: ['Schlafmangel & Nachtwachen', 'Reisekrankheit/Schwindel', 'Schwäche in Knien & Nacken']
  },
  {
    name: 'Coffea cruda (Rohkaffee)',
    latinName: 'Coffea cruda',
    germanName: 'Rohkaffee',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'D12'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich abends',
    defaultAnwendungsdauer: '2 bis maximal 4 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Schlaflosigkeit durch Gedankenandrang und freudige Erregung, erhöhte Sinnesschärfe.',
    keyIndications: ['Gedankenüberflutung', 'Schlaflosigkeit', 'Überempfindlichkeit aller Sinne']
  },
  {
    name: 'Colocynthis (Koloquinte)',
    latinName: 'Citrullus colocynthis',
    germanName: 'Koloquinte',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'D12'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '2 bis maximal 4 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Krampfartige Bauchschmerzen, Besserung durch festen Druck und Sich-Doppelkrümmen.',
    keyIndications: ['Krämpfe nach Ärger/Wut', 'Besser durch starkes Vorbeugen/Druck', 'Ischialgie']
  },
  {
    name: 'Conium maculatum (Gefleckter Schierling)',
    latinName: 'Conium maculatum',
    germanName: 'Gefleckter Schierling',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Initialphase',
    standardNote: 'Drehschwindel beim Umdrehen im Bett, Drüsenverhärtungen, aufsteigende Schwäche.',
    keyIndications: ['Schwindel beim Kopfdrehen/Liegen', 'Drüsenschwellungen', 'Altersbeschwerden']
  },
  {
    name: 'Drosera rotundifolia (Rundblättriger Sonnentau)',
    latinName: 'Drosera rotundifolia',
    germanName: 'Rundblättriger Sonnentau',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'D12'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Krampfartiger, bellender Husten in Anfällen, Verschlimmerung nach Mitternacht im Liegen.',
    keyIndications: ['Krampfhustenanfälle', 'Husten mit Würgen', 'Schlechter nach Mitternacht']
  },
  {
    name: 'Dulcamara (Bittersüß)',
    latinName: 'Solanum dulcamara',
    germanName: 'Bittersüßer Nachtschatten',
    category: 'Pflanzlich',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Beschwerden nach Nässe und Kälte oder Wetterumschwung von warm zu nasskalt.',
    keyIndications: ['Folgen von Nasskälte', 'Gelenkschmerzen bei Wetterwechsel', 'Harnblasenreizung']
  },
  {
    name: 'Eupatorium perfoliatum (Wasserhanf)',
    latinName: 'Eupatorium perfoliatum',
    germanName: 'Durchwachsener Wasserhanf',
    category: 'Pflanzlich',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '2 bis maximal 4 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Grippe mit tief sitzendem Knochenschmerz, als ob die Knochen gebrochen wären.',
    keyIndications: ['Knochenschmerzen bei Grippe', 'Augapfelschmerz', 'Durst auf Kaltes vor dem Frösteln']
  },
  {
    name: 'Ferrum phosphoricum (Eisenphosphat)',
    latinName: 'Ferrum phosphoricum',
    germanName: 'Eisenphosphat',
    category: 'Mineralisch',
    defaultPotencies: ['D6', 'D12', 'C30'],
    defaultTagesdosis: '2 bis 3 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Erstes Entzündungsstadium, mäßiges Fieber, wechselnde Blässe und Rötung der Wangen.',
    keyIndications: ['Beginnende Infekte', 'Mäßiges Fieber', 'Neigung zu Nasenbluten']
  },
  {
    name: 'Gelsemium sempervirens (Gelber Jasmin)',
    latinName: 'Gelsemium sempervirens',
    germanName: 'Gelber Jasmin',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'D12', 'C200'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Große Schwere, Zittrigkeit, Benommenheit, schwere Augenlider, Prüfungsangst.',
    keyIndications: ['Schwere Augenlider & Glieder', 'Prüfungsangst / Lampenfieber', 'Sommergrippe ohne Durst']
  },
  {
    name: 'Glonoinum (Nitroglyzerin)',
    latinName: 'Glonoinum',
    germanName: 'Nitroglyzerin',
    category: 'Mineralisch',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '1 bis 3 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Sonnenstich, heftig pulsierende Kopfschmerzen im Takt des Herzschlags.',
    keyIndications: ['Sonnenstich & Hitzeerschöpfung', 'Klopfende Schläfen', 'Orientierungsverlust']
  },
  {
    name: 'Graphites (Reißblei)',
    latinName: 'Graphites',
    germanName: 'Reißblei / Graphit',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Initialphase',
    standardNote: 'Trockene, rissige Hautstellen mit honigartigem klebrigem Sekret, Neigung zu Verstopfung.',
    keyIndications: ['Honigartiges Sekret', 'Rissige Haut an Gelenkbeugen/Ohr', 'Trägheit']
  },
  {
    name: 'Hepar sulfuris calcareum (Kalkschwefelleber)',
    latinName: 'Hepar sulfuris',
    germanName: 'Kalkschwefelleber',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'D12', 'C200'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Extreme Kälte- und Berührungsempfindlichkeit, splitterartiger Schmerz, Neigung zu Eiterung.',
    keyIndications: ['Splitterartige Schmerzen', 'Extreme Zugluftempfindlichkeit', 'Eiterungsprozesse']
  },
  {
    name: 'Hypericum perforatum (Johanniskraut)',
    latinName: 'Hypericum perforatum',
    germanName: 'Echtes Johanniskraut',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200', 'D12'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Arnika der Nerven: Verletzungen an nervenreichen Körperstellen (Finger, Zehen, Steißbein, Zähne).',
    keyIndications: ['Nervenverletzungen', 'Eingeklemmte Finger/Zehen', 'Steißbeinsturz', 'Aufschießender Schmerz']
  },
  {
    name: 'Ignatia amara (Ignatiusbohne)',
    latinName: 'Strychnos ignatii',
    germanName: 'Ignatiusbohne',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Folgen von akutem Kummer, Trauer, Enttäuschung. Kloßgefühl im Hals, tiefes Seufzen.',
    keyIndications: ['Akuter Kummer & Enttäuschung', 'Globusgefühl im Hals', 'Paradoxe Symptome', 'Tiefes Seufzen']
  },
  {
    name: 'Ipecacuanha (Brechwurzel)',
    latinName: 'Cephaelis ipecacuanha',
    germanName: 'Brechwurzel',
    category: 'Pflanzlich',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '2 bis maximal 4 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Dauerhafte Übelkeit, die durch Erbrechen nicht gebessert wird; saubere Zunge.',
    keyIndications: ['Ständige Übelkeit ohne Erleichterung', 'Saubere Zunge', 'Krampfhusten mit Würgen']
  },
  {
    name: 'Kalium bichromicum (Kaliumdichromat)',
    latinName: 'Kalium bichromicum',
    germanName: 'Kaliumdichromat',
    category: 'Mineralisch',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Zähe, fadenförmige Sekrete, punktförmig lokalisierte Schmerzen, Sinusitis.',
    keyIndications: ['Zähe fadenförmige Sekrete', 'Punktförmige Schmerzpunkte', 'Stirnhöhlenkatarrh']
  },
  {
    name: 'Kalium carbonicum (Kaliumkarbonat)',
    latinName: 'Kalium carbonicum',
    germanName: 'Kaliumkarbonat',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Initialphase',
    standardNote: 'Verschlechterung um 2–4 Uhr morgens, stechende Schmerzen, Schwellung des oberen Augenlids.',
    keyIndications: ['Aufwachen 2-4 Uhr nachts', 'Säckchenförmige Schwellung Oberlid', 'Rückenschmerz']
  },
  {
    name: 'Lachesis muta (Buschmeisterschlange)',
    latinName: 'Lachesis muta',
    germanName: 'Buschmeisterschlange',
    category: 'Tierisch',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich morgens',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Linksseitigkeit, Unverträglichkeit von enger Kleidung am Hals, Verschlechterung nach dem Schlaf.',
    keyIndications: ['Linksseitigkeit', 'Keine Enge am Hals vertragbar', 'Schlechter nach dem Schlaf', 'Redseligkeit']
  },
  {
    name: 'Ledum palustre (Sumpfporst)',
    latinName: 'Ledum palustre',
    germanName: 'Sumpfporst',
    category: 'Pflanzlich',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Stichwunden (Nägel, Insekten, Zecken), betroffene Stelle fühlt sich kalt an, bessert durch Kälte.',
    keyIndications: ['Insekten- & Zeckenstiche', 'Punktionswunden', 'Kältegefühl der Verletzung']
  },
  {
    name: 'Lycopodium clavatum (Keulenbärlapp)',
    latinName: 'Lycopodium clavatum',
    germanName: 'Keulenbärlapp',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Rechtsseitigkeit, Verschlimmerung 16–20 Uhr, starker Blähbauch, Heißhunger auf Süßes.',
    keyIndications: ['Rechtsseitigkeit', 'Verschlimmerung 16-20 Uhr', 'Blähbauch nach wenig Essen', 'Verlangen nach Warmem']
  },
  {
    name: 'Magnesium phosphoricum (Magnesiumphosphat)',
    latinName: 'Magnesium phosphoricum',
    germanName: 'Magnesiumphosphat',
    category: 'Mineralisch',
    defaultPotencies: ['D6', 'D12', 'C30'],
    defaultTagesdosis: '2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '2 bis maximal 4 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Krämpfe, Neuralgien, Menstruationsbeschwerden, deutliche Besserung durch Wärme und Druck.',
    keyIndications: ['Krampfartige Schmerzen', 'Besser durch Wärme & Druck', 'Heißes Wasserglas ("Heiße 7")']
  },
  {
    name: 'Mercurius solubilis (Quecksilber)',
    latinName: 'Mercurius solubilis Hahnemanni',
    germanName: 'Quecksilber nach Hahnemann',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'D12', 'C200'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Vermehrter Speichelfluss mit Mundgeruch, Zahnabdrücke an den Zungenrändern, Nachtschweiß.',
    keyIndications: ['Zahnabdrücke auf der Zunge', 'Speichelfluss & Mundgeruch', 'Schlechter bei Hitze und Kälte']
  },
  {
    name: 'Natrium muriaticum (Kochsalz)',
    latinName: 'Natrium chloratum',
    germanName: 'Kochsalz',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Einmalgabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich morgens',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Konstitutions- und Initialphase',
    standardNote: 'Stiller Kummer, Verschlossenheit, Abneigung gegen Trost, Salzhunger, Lippenherpes.',
    keyIndications: ['Abneigung gegen Trost', 'Verlangen nach Salz', 'Kopfschmerz wie Hämmern', 'Rissige Unterlippe']
  },
  {
    name: 'Nux vomica (Brechnuss)',
    latinName: 'Strychnos nux-vomica',
    germanName: 'Brechnuss',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200', 'D12'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich abends',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Reizbarkeit, Ungeduld, Magenkrämpfe nach Stress/Genussmitteln, Kälteempfindlichkeit.',
    keyIndications: ['Reizbar & ungeduldig', 'Folgen von Stress, Kaffee, Alkohol', 'Magen-Darm-Krämpfe', 'Aufwachen um 3 Uhr']
  },
  {
    name: 'Phosphorus (Gelber Phosphor)',
    latinName: 'Phosphorus',
    germanName: 'Gelber Phosphor',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Offen, mitfühlend, Verlangen nach eiskaltem Wasser, Blutungsneigung, Furcht im Dunkeln/Gewitter.',
    keyIndications: ['Durst auf eiskaltes Wasser', 'Blutungsneigung', 'Furcht vor Gewitter & Dunkelheit', 'Kontaktfreudig']
  },
  {
    name: 'Phytolacca decandra (Kermesbeere)',
    latinName: 'Phytolacca decandra',
    germanName: 'Kermesbeere',
    category: 'Pflanzlich',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Halsschmerzen mit Schmerzausstrahlung zu den Ohren beim Schlucken, Brustdrüsenentzündung.',
    keyIndications: ['Schmerzausstrahlung zu den Ohren', 'Dunkelrote Rachenschleimhaut', 'Mastitis']
  },
  {
    name: 'Pulsatilla pratensis (Wiesen-Küchenschelle)',
    latinName: 'Pulsatilla pratensis',
    germanName: 'Wiesen-Küchenschelle',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Mildes weinerliches Gemüt, Besserung durch Trost und frische Luft, Durstlosigkeit, wechselnde Symptome.',
    keyIndications: ['Besser durch Trost & Frischluft', 'Durstlosigkeit', 'Milde gelbgrüne Sekrete', 'Wechselhafte Beschwerden']
  },
  {
    name: 'Rhus toxicodendron (Giftsumach)',
    latinName: 'Toxicodendron pubescens',
    germanName: 'Giftsumach',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'D12', 'C200'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Anlaufschmerz gebessert durch fortgesetzte Bewegung und Wärme, Verrenkungen, Zerschlagenheit.',
    keyIndications: ['Anlaufschmerz', 'Besser durch fortgesetzte Bewegung', 'Schlechter bei Ruhe & Nässe', 'Ruhelosigkeit']
  },
  {
    name: 'Ruta graveolens (Weinraute)',
    latinName: 'Ruta graveolens',
    germanName: 'Gartenraute / Weinraute',
    category: 'Pflanzlich',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Verletzungen der Knochenhaut, Sehnen und Bänder (Tennisarm, Achillessehne, Überanstrengung der Augen).',
    keyIndications: ['Knochenhaut- & Sehnenverletzungen', 'Tennisarm', 'Augenüberanstrengung']
  },
  {
    name: 'Sepia officinalis (Echter Tintenfisch)',
    latinName: 'Sepia succus',
    germanName: 'Echter Tintenfisch',
    category: 'Tierisch',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Einmalgabe à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Erschöpfung durch familiäre Überlastung, Gleichgültigkeit gegen Angehörige, Besserung durch Sport.',
    keyIndications: ['Überforderung durch Haushalt/Familie', 'Verlangen nach Alleinsein', 'Besser durch Sport', 'Senkungsgefühl']
  },
  {
    name: 'Silicea (Kieselerde)',
    latinName: 'Silicea terra',
    germanName: 'Kieselerde',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Konstitutions- und Aufbauphase',
    standardNote: 'Große Frostigkeit, Mangel an Lebenswärme, schwaches Bindegewebe, treibt Fremdkörper aus.',
    keyIndications: ['Extreme Frostigkeit', 'Fußschweiß', 'Fremdkörperaustreibung', 'Mangelndes Selbstvertrauen']
  },
  {
    name: 'Spongia tosta (Gerösteter Badeschwamm)',
    latinName: 'Euspongia officinalis',
    germanName: 'Gerösteter Badeschwamm',
    category: 'Tierisch',
    defaultPotencies: ['D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '2 bis maximal 4 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Trockener, bellender Pseudokrupp-Husten ("Sägen von Holz"), Besserung durch warmes Trinken.',
    keyIndications: ['Trockener bellender Husten (Krupp)', 'Erstickungsangst', 'Besser durch warme Getränke']
  },
  {
    name: 'Staphisagria (Stephanskraut)',
    latinName: 'Delphinium staphisagria',
    germanName: 'Stephanskraut',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Folgen von Kränkung, Demütigung, unterdrücktem Zorn und Vorwürfen.',
    keyIndications: ['Unterdrückter Zorn & Kränkung', 'Schmerzen nach Streit/Zurechtweisung', 'Schnittwunden']
  },
  {
    name: 'Sulfur (Schwefelblüte)',
    latinName: 'Sulfur',
    germanName: 'Schwefelblüte',
    category: 'Mineralisch',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Einmalgabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich morgens nüchtern',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Akut- und Initialphase',
    standardNote: 'Zentrales antipsorisches Reaktionsmittel; Wärmeintoleranz, brennende Fußsohlen im Bett, Hautaffinität.',
    keyIndications: ['Wärmeintoleranz / streckt Füße aus dem Bett', 'Heißhunger um 11 Uhr', 'Hautjucken']
  },
  {
    name: 'Symphytum officinale (Beinwell)',
    latinName: 'Symphytum officinale',
    germanName: 'Echter Beinwell',
    category: 'Pflanzlich',
    defaultPotencies: ['D6', 'D12', 'C30'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '5 bis 10 Tage',
    defaultZeitraum: 'Frakturheilungsphase',
    standardNote: 'Fördert die Knochen- und Periostheilung nach Frakturen sowie bei Augapfeltrauma.',
    keyIndications: ['Knochenbrüche / Kallusbildung', 'Periostschmerzen', 'Stumpfe Augenverletzungen']
  },
  {
    name: 'Thuja occidentalis (Lebensbaum)',
    latinName: 'Thuja occidentalis',
    germanName: 'Abendländischer Lebensbaum',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'C200', 'LM VI'],
    defaultTagesdosis: '1 Gabe à 3–5 Globuli',
    defaultHaeufigkeit: '1-mal täglich',
    defaultAnwendungsdauer: '3 bis maximal 5 Tage',
    defaultZeitraum: 'Initialphase',
    standardNote: 'Hauptmittel bei Sykose, Warzen, Folgen von Impfungen oder chronischen Schleimhautkatarrhen.',
    keyIndications: ['Warzen & Wucherungen', 'Impffolgen', 'Schlechter bei Kälte & Nässe']
  },
  {
    name: 'Veratrum album (Weißer Nieswurz)',
    latinName: 'Veratrum album',
    germanName: 'Weißer Nieswurz',
    category: 'Pflanzlich',
    defaultPotencies: ['C30', 'D12'],
    defaultTagesdosis: '1 bis 2 Gaben à 3–5 Globuli',
    defaultHaeufigkeit: '1- bis 2-mal täglich',
    defaultAnwendungsdauer: '1 bis 3 Tage',
    defaultZeitraum: 'Akutphase',
    standardNote: 'Kollapszustände mit eiskaltem Schweiß auf der Stirn, Durchfall und Erbrechen.',
    keyIndications: ['Kalter Stirnschweiß', 'Kollapsneigung & Erschöpfung', 'Verlangen nach Eis']
  }
];

export async function searchHomeopathicRemedies(query: string): Promise<HomeopathicRemedyInfo[]> {
  const q = query.trim().toLowerCase();
  if (!q) return COMMON_HOMEO_REMEDIES_DB.slice(0, 15);

  return COMMON_HOMEO_REMEDIES_DB.filter(r => 
    r.name.toLowerCase().includes(q) ||
    r.latinName.toLowerCase().includes(q) ||
    (r.germanName && r.germanName.toLowerCase().includes(q)) ||
    (r.keyIndications && r.keyIndications.some(ind => ind.toLowerCase().includes(q)))
  ).slice(0, 20);
}
