#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Boericke Expansion Batch 3 (remedies C to Z)
"""

BATCH3_REMEDIES = [
    {
        "id": "cheiranthus-cheiri",
        "latin": "Cheiranthus cheiri",
        "cat": "plant",
        "de_name": "Goldlack",
        "en_name": "Wallflower",
        "es_name": "Alhelí amarillo",
        "fr_name": "Giroflée des murailles",
        "it_name": "Violaciocca gialla",
        "el_name": "Χείρανθος",
        "ru_name": "Желтушник левкойный",
        "de_essence": "Boerickes Weisheitszahnmittel: Schmerzen beim Durchbruch von Weisheitszähnen, strahlt in Ohr und Schläfe, Gehörgangsreizung und Taubheit.",
        "en_essence": "Boericke's wisdom tooth remedy: cutting pain during dentition of wisdom teeth radiating to ear and temples, auditory canal irritation, and deafness.",
        "indications_de": ["Weisheitszahn-Dentitionsschmerz", "Ohrenschmerz & Schwerhörigkeit", "Gingivitis bei Zahnung"],
        "indications_en": ["Wisdom teeth impaction / dentition", "Otalgia radiating from jaw", "Deafness from catarrhal swelling"],
        "keynotes_de": ["Heftiges Stechen vom Kieferwinkel ins Ohr", "Schwellung und Rötung des Zahnfleisches um den Weisheitszahn", "Taubheit mit Völlegefühl im Gehörgang"],
        "keynotes_en": ["Stitching neuralgia radiating from angle of jaw to ear", "Gums around erupting molars inflamed and swollen", "Deafness with sensation of fullness in external meatus"],
        "better_de": ["Wärme am Kiefer"],
        "better_en": ["Warmth to jaw"],
        "worse_de": ["Kauen", "Kälte", "Nachts"],
        "worse_en": ["Chewing", "Cold", "Night"],
        "diff": ["Plantago", "Chamomilla", "Magnesia phosphorica"],
        "sphere": ["Kiefer", "Zähne", "Ohren", "Trigeminus"],
        "tier": 2
    },
    {
        "id": "chelone-glabra",
        "latin": "Chelone glabra",
        "cat": "plant",
        "de_name": "Kahle Schlangenkopfpflanze",
        "en_name": "Balmony",
        "es_name": "Cabeza de tortuga",
        "fr_name": "Galane glabre",
        "it_name": "Chelone glabra",
        "el_name": "Χελώνη",
        "ru_name": "Хелоне голая",
        "de_essence": "Boerickes Lebertonikum: Schmerzlose Leberträgheit mit Ikterus, Spulwurmbefall (Ascaris lumbricoides), Appetitlosigkeit und Bittergeschmack.",
        "en_essence": "Boericke's celebrated hepatic tonic: painless liver torpor with jaundice, roundworm infestation, anorexia, and bitter taste.",
        "indications_de": ["Leberatonie & chronischer Ikterus", "Spulwurmbefall (Askariasis)", "Dyspeptische Bitterkeit"],
        "indications_en": ["Hepatic torpor and chronic jaundice", "Roundworm infestation", "Bitter dyspepsia with languor"],
        "keynotes_de": ["Dumpfer Schmerz in der rechten Hypochondriumgegend", "Stuhl hell oder lehmfarben, Urin dunkel gefärbt", "Spezifisch wirksam zur Beseitigung von Spulwürmern"],
        "keynotes_en": ["Dull aching in right lobe of liver extending backward", "Stools pale and clay-colored, urine bile-stained", "Expels roundworms and restores digestive power"],
        "better_de": ["Nach leichtem Essen"],
        "better_en": ["After light nourishment"],
        "worse_de": ["Druck auf die Leber", "Fett"],
        "worse_en": ["Pressure on liver", "Fatty food"],
        "diff": ["Carduus marianus", "Chelidonium", "Taraxacum"],
        "sphere": ["Leber", "Gallenblase", "Darmparasiten"],
        "tier": 2
    },
    {
        "id": "chenopodium-anthelminticum",
        "latin": "Chenopodium anthelminticum",
        "cat": "plant",
        "de_name": "Amerikanischer Wurmsamen",
        "en_name": "Jerusalem Oak / Wormseed",
        "es_name": "Epazote",
        "fr_name": "Chénopode vermifuge",
        "it_name": "Farinello vermifugo",
        "el_name": "Χηνοπόδιον",
        "ru_name": "Марь противоглистная",
        "de_essence": "Boerickes Leitsymptom: Menière-Krankheit mit Drehschwindel und Tinnitus, charakteristischer Schmerz am unteren Winkel der rechten Scapula.",
        "en_essence": "Boericke's hallmark: Meniere's disease with auditory vertigo and buzzing, and characteristic pain at lower angle of right scapula.",
        "indications_de": ["Menière-Syndrom & Schwindel", "Hörverlust für hohe Töne & Tinnitus", "Schulterblattschmerz rechts"],
        "indications_en": ["Meniere's disease and aural vertigo", "Auditory nerve impairment / tinnitus", "Right infrascapular pain"],
        "keynotes_de": ["Drehschwindel verbunden mit lautem Pfeifen und Brausen im Ohr", "Schmerz unter dem rechten Schulterblatt zieht durch die Brust", "Besonders empfindlich für Töne menschlicher Stimmen"],
        "keynotes_en": ["Aural vertigo with sudden roaring and buzzing in ears", "Characteristic fixed ache beneath lower angle of right scapula", "Loss of auditory perception, better for vibrations"],
        "better_de": ["Ruhelage des Kopfes"],
        "better_en": ["Resting head quietly"],
        "worse_de": ["Kopfdrehung", "Aufstehen"],
        "worse_en": ["Turning head", "Rising"],
        "diff": ["Chelidonium", "Chininum sulfuricum", "Conium"],
        "sphere": ["Nervus vestibulocochlearis", "Innenohr", "Scapula"],
        "tier": 1
    },
    {
        "id": "chloralum-hydratum",
        "latin": "Chloralum hydratum",
        "cat": "mineral",
        "de_name": "Chloralhydrat",
        "en_name": "Chloral Hydrate",
        "es_name": "Hidrato de cloral",
        "fr_name": "Chloral hydraté",
        "it_name": "Cloralio idrato",
        "el_name": "Ένυδρη χλωράλη",
        "ru_name": "Хлоралгидрат",
        "de_essence": "Urtikaria nach Alkoholgenuss oder heißem Bad, profunde Schläfrigkeit mit lebhaften Alpträumen, emotionale Labilität.",
        "en_essence": "Urticaria breaking out after alcoholic drinks or hot bathing, deep somnolence with vivid terrifying dreams, emotional instability.",
        "indications_de": ["Alkohol-induzierte Urtikaria", "Nervöse Schlaflosigkeit & Somnolenz", "Asthenopische Cephalgie"],
        "indications_en": ["Alcohol-induced urticaria", "Nervous insomnia with nightmares", "Severe erythema from bathing"],
        "keynotes_de": ["Urtikaria-Ausschlag tritt sofort nach Genuss von Wein oder Bier auf", "Starkes Frösteln am ganzen Körper mit bleierner Schläfrigkeit", "Halluzinationen beim Schließen der Augen"],
        "keynotes_en": ["Wheals break out rapidly following small amounts of alcohol", "Coldness of entire body accompanied by irresistible stupor", "Vivid distressing visual hallucinations upon closing eyes"],
        "better_de": ["Frische kühle Luft"],
        "better_en": ["Fresh cool air"],
        "worse_de": ["Alkohol", "Heißes Wasser", "Nachts"],
        "worse_en": ["Alcohol", "Hot bath", "Night"],
        "diff": ["Agaricus", "Opium", "Apis"],
        "sphere": ["Haut", "Gehirn", "Schlafzentrum"],
        "tier": 2
    },
    {
        "id": "cholesterinum",
        "latin": "Cholesterinum",
        "cat": "nosode",
        "de_name": "Cholesterin",
        "en_name": "Cholesterin",
        "es_name": "Colesterina",
        "fr_name": "Cholestérol",
        "it_name": "Colesterina",
        "el_name": "Χοληστερίνη",
        "ru_name": "Холестерин",
        "de_essence": "Boerickes spezifisches Mittel bei Cholelithiasis, unerträglichem Leberschmerz, Ikterus, Karzinom der Leber und chronischer Cholesterinämie.",
        "en_essence": "Boericke's celebrated specific for gall-stones, intractable hepatic pain, deep jaundice, hepatic carcinoma, and hypercholesterolemia.",
        "indications_de": ["Gallensteinkoliken (Cholelithiasis)", "Hartnäckiger Leber-Dauerschmerz", "Ikterus mit Leberschwellung"],
        "indications_en": ["Gall-stone colic (cholelithiasis)", "Intractable chronic liver ache", "Obstructive jaundice with hepatomegaly"],
        "keynotes_de": ["Brennender, schneidender Schmerz in der Lebergegend, Patient kann Berührung kaum ertragen", "Verhindert die Neubildung von Gallensteinen und löst Gallenkoliken", "Chronische Gelbsucht mit dunklem, galligem Urin"],
        "keynotes_en": ["Persistent acute pain in right hypochondrium; cannot bear touch", "Boericke: 'Frequent attacks of gall-stone colic and jaundice'", "Stops agonizing pain of hepatic neoplasm or stone impaction"],
        "better_de": ["Vornüberbeugen", "Leise Ruhe"],
        "better_en": ["Bending forward", "Quiet rest"],
        "worse_de": ["Berührung", "Rechtsseitenlage", "Erschütterung"],
        "worse_en": ["Touch", "Lying on right side", "Jarring"],
        "diff": ["Berberis", "Chelidonium", "Podophyllum"],
        "sphere": ["Gallenblase", "Gallengänge", "Leberparenchym"],
        "tier": 1
    },
    {
        "id": "cineraria-maritima",
        "latin": "Cineraria maritima",
        "cat": "plant",
        "de_name": "Silber-Greiskraut / Aschenpflanze",
        "en_name": "Dusty Miller",
        "es_name": "Cineraria marítima",
        "fr_name": "Cinéraire maritime",
        "it_name": "Cineraria marittima",
        "el_name": "Κινεράρια",
        "ru_name": "Цинерария приморская",
        "de_essence": "Boerickes berühmtes Augenmittel bei beginnendem Grauem Star (Katarakt), Hornhauttrübung, posttraumatischen Sehstörungen und Schleiersehen.",
        "en_essence": "Boericke's celebrated eye specific: incipient cataract, corneal opacities, post-traumatic visual haze, and resolving lenticular deposits.",
        "indications_de": ["Incipienter Grauer Star (Katarakt)", "Hornhauttrübungen nach Verletzung", "Schleier- und Nebelsehen"],
        "indications_en": ["Incipient cataract", "Corneal opacities from trauma", "Visual cloudiness / misty vision"],
        "keynotes_de": ["Sehen wie durch einen dichten Nebel oder Schleier", "Fördert die Resorption von Ablagerungen in Linse und Hornhaut", "Reizlosigkeit; rein degenerative Eintrübung des dioptrischen Apparates"],
        "keynotes_en": ["Progressive dimness of vision as if looking through steam or gauze", "Absorbs lenticular deposits and restores clarity", "Effective in elderly patients with early lens clouding"],
        "better_de": ["Ausruhen der Augen"],
        "better_en": ["Resting eyes"],
        "worse_de": ["Helles Sonnenlicht", "Augenüberanstrengung"],
        "worse_en": ["Bright sunlight", "Eye strain"],
        "diff": ["Phosphorus", "Silicea", "Calcarea fluorica"],
        "sphere": ["Augenlinse", "Kornea", "Sehorgan"],
        "tier": 1
    },
    {
        "id": "cochlearia-armoracia",
        "latin": "Cochlearia armoracia",
        "cat": "plant",
        "de_name": "Meerrettich",
        "en_name": "Horseradish",
        "es_name": "Rábano picante",
        "fr_name": "Raifort sauvage",
        "it_name": "Rafano rusticano",
        "el_name": "Χράνο",
        "ru_name": "Хрен обыкновенный",
        "de_essence": "Akuter und chronischer Sinuskatarrh, Stirnhöhlenentzündung mit heftigem Tränenfluss, Mundfäule, Skorbut und Ödeme.",
        "en_essence": "Acute and chronic sinus catarrh, frontal sinusitis with stinging lachrymation, scorbutic gums, and dropsical swellings.",
        "indications_de": ["Frontale Sinusitis & Schnupfen", "Scharfer Tränenfluss & Niesen", "Skorbutisches Zahnfleisch"],
        "indications_en": ["Frontal sinusitis", "Acrid lachrymation with sneezing", "Spongy bleeding gums"],
        "keynotes_de": ["Völlegefühl und drückender Schmerz an der Nasenwurzel", "Tränenfluss brennt wie Feuer auf den Wangen", "Gefühl von brennender Schärfe in Rachen und Mundschleimhaut"],
        "keynotes_en": ["Frontal sinus pressure and aching at root of nose", "Profuse acrid lachrymation scalding the cheeks", "Burning pungent sensation in mouth and pharynx"],
        "better_de": ["Im Freien", "Kühle Luft"],
        "better_en": ["Open air", "Cool breeze"],
        "worse_de": ["Warme Stube", "Bücken"],
        "worse_en": ["Warm room", "Stooping"],
        "diff": ["Allium cepa", "Euphrasia", "Kali bichromicum"],
        "sphere": ["Nasennebenhöhlen", "Nasenschleimhaut", "Tränendrüsen"],
        "tier": 2
    },
    {
        "id": "codeinum-purum",
        "latin": "Codeinum purum",
        "cat": "plant",
        "de_name": "Codein",
        "en_name": "Codeine",
        "es_name": "Codeína pura",
        "fr_name": "Codéine pure",
        "it_name": "Codeina pura",
        "el_name": "Κωδεΐνη",
        "ru_name": "Кодеин чистый",
        "de_essence": "Boerickes Husten- und Zuckungsmittel: Quälender, trockener Kitzelhusten nachts, Zucken der Augenlider (Myokymie) und Diabetes mellitus.",
        "en_essence": "Boericke's celebrated cough and twitching remedy: dry, hacking, exhausting nocturnal tickling cough, twitching of eyelids, and glycosuria.",
        "indications_de": ["Trockener, quälender Reizhusten", "Zucken der Augenlider (Blepharospasmus)", "Diabetische Erschöpfung"],
        "indications_en": ["Dry racking nocturnal cough", "Involuntary twitching of eyelids", "Diabetic thirst and polyuria"],
        "keynotes_de": ["Husten bricht aus, sobald der Kopf das Kissen berührt", "Unwillkürliches Zucken der Augenlid- und Gesichtsmuskeln", "Unstillbarer quälender Hustenreiz tief im Kehlkopf"],
        "keynotes_en": ["Cough comes on violently on lying down at night", "Involuntary twitching of muscles of eyelids and brows", "Exhausting tickling in larynx preventing sleep"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting up"],
        "worse_de": ["Nachts", "Flaches Hinlegen", "Kaltes Einatmen"],
        "worse_en": ["Night", "Lying down", "Inhaling cold air"],
        "diff": ["Hyoscyamus", "Rumex", "Agaricus"],
        "sphere": ["Atemzentrum", "Kehlkopf", "Augenlider", "Pankreas"],
        "tier": 1
    },
    {
        "id": "commelina-communis",
        "latin": "Commelina communis",
        "cat": "plant",
        "de_name": "Asiatische Tagblume",
        "en_name": "Dayflower",
        "es_name": "Flor de Santa Lucía",
        "fr_name": "Comméline commune",
        "it_name": "Erba miseria asiatica",
        "el_name": "Κομμελίνα",
        "ru_name": "Коммелина обыкновенная",
        "de_essence": "Akute und chronische Zystitis mit Hämaturie, schmerzhaftes Brennen entlang der Urethra und Dranginkontinenz.",
        "en_essence": "Acute and chronic cystitis with hematuria, painful burning along urethra, and urgency incontinence.",
        "indications_de": ["Hämaturie bei Zystitis", "Schmerzhafte Dysurie", "Urethritis mit Ausfluss"],
        "indications_en": ["Hematuria from cystitis", "Painful dysuria", "Urethral burning and catarrh"],
        "keynotes_de": ["Blutiger Urin mit heftigem Brennschmerz beim Miktionsende", "Ständiges Gefühl eines scharfen Tropfens in der Harnröhre", "Fördert die rasche Klärung von trübem Reizharn"],
        "keynotes_en": ["Blood-tinged urine with cutting pain at close of urination", "Sensation of sharp burning drop lingering in urethra", "Relieves irritable bladder with mucoid urine"],
        "better_de": ["Wärme am Unterbauch"],
        "better_en": ["Warmth to hypogastrium"],
        "worse_de": ["Kälte", "Bewegung"],
        "worse_en": ["Cold", "Motion"],
        "diff": ["Cantharis", "Terebinthina"],
        "sphere": ["Harnblase", "Urethra", "Nieren"],
        "tier": 3
    },
    {
        "id": "damiana",
        "latin": "Damiana (Turnera diffusa)",
        "cat": "plant",
        "de_name": "Damiana",
        "en_name": "Damiana",
        "es_name": "Damiana",
        "fr_name": "Damiana",
        "it_name": "Damiana",
        "el_name": "Νταμιάνα",
        "ru_name": "Дамиана",
        "de_essence": "Boerickes Aphrodisiakum und Nerventonikum: Sexuelle Neurasthenie, Impotenz durch nervöse Erschöpfung, Frigidität, Prostatahypertrophie und Blasenatonie.",
        "en_essence": "Boericke's celebrated aphrodisiac and nerve tonic: sexual neurasthenia, nervous impotence from exhaustion, frigidity, and atonic bladder.",
        "indications_de": ["Sexuelle Neurasthenie & Impotenz", "Männliche & weibliche Frigidität", "Prostataüberlastung & Blasenatonie"],
        "indications_en": ["Sexual neurasthenia / impotence", "Frigidity from nerve exhaustion", "Prostatic enlargement and bladder atony"],
        "keynotes_de": ["Völliger Verlust der sexuellen Vitalität bei geistiger und körperlicher Erschöpfung", "Tröpfelnder Harnabgang bei älteren Männern mit Prostatitis", "Hebt die Gemütsstimmung und tonisiert das Beckennervensystem"],
        "keynotes_en": ["Profound sexual weakness from mental overwork and nervous strain", "Slow dribbling micturition in elderly men with large prostate", "Acts as an uplifting general tonic to pelvic reflex centers"],
        "better_de": ["Ausreichender Schlaf", "Kräftigung"],
        "better_en": ["Sound sleep", "Nourishment"],
        "worse_de": ["Geistige Überarbeitung", "Exzesse"],
        "worse_en": ["Mental exhaustion", "Excesses"],
        "diff": ["Agnus castus", "Selenium", "Caladium"],
        "sphere": ["Sexualorgane", "Beckenplexus", "Nervensystem"],
        "tier": 1
    },
    {
        "id": "dictamnus-albus",
        "latin": "Dictamnus albus",
        "cat": "plant",
        "de_name": "Weißer Diptam / Brennender Busch",
        "en_name": "White Dittany",
        "es_name": "Díctamo blanco",
        "fr_name": "Dictame blanc",
        "it_name": "Frassinella",
        "el_name": "Δίκταμνος ο λευκός",
        "ru_name": "Ясенец белый",
        "de_essence": "Krampfartige Uterusbeschwerden, schmerzhafter Fluor albus, Blähungskoliken und profuse Menses.",
        "en_essence": "Spasmodic uterine colic, acrid leucorrhea, flatulent distention, and profuse premature menses.",
        "indications_de": ["Uteruskoliken & Krämpfe", "Ätzender Fluor albus", "Blähungsbeschwerden"],
        "indications_en": ["Uterine cramps and colic", "Acrid leucorrhea", "Flatulent abdominal spasms"],
        "keynotes_de": ["Krämpfe ziehen vom Becken in den Rücken", "Ausfluss scharf, brennend mit Juckreiz", "Darmblähungen mit schmerzhaften kolikartigen Stichen"],
        "keynotes_en": ["Bearing-down and cramps extending into back", "Leucorrhea excoriating and tenacious", "Painful flatulent griping relieved by flatus"],
        "better_de": ["Zusammenkrümmen", "Wärme"],
        "better_en": ["Bending double", "Warmth"],
        "worse_de": ["Vor und während Menses"],
        "worse_en": ["Before and during menses"],
        "diff": ["Pulsatilla", "Viburnum"],
        "sphere": ["Uterus", "Weibliche Genitalien", "Darm"],
        "tier": 3
    },
    {
        "id": "dirca-palustris",
        "latin": "Dirca palustris",
        "cat": "plant",
        "de_name": "Lederholz",
        "en_name": "Leatherwood",
        "es_name": "Cuero de pantano",
        "fr_name": "Bois de cuir",
        "it_name": "Legno di cuoio",
        "el_name": "Δίρκα",
        "ru_name": "Дирка болотная",
        "de_essence": "Neuralgischer Kopfschmerz mit Schwindel, Wehtun im Darmtrakt mit schleimiger Diarrhoe, Heiserkeit und Zungenbrennen.",
        "en_essence": "Neuralgic headache with vertigo, gastrointestinal catarrh with mucous diarrhea, hoarseness, and tongue burning.",
        "indications_de": ["Kongestive Cephalgie & Schwindel", "Schleimige Darmkatarrhe", "Laryngitis mit Kitzeln"],
        "indications_en": ["Congestive cephalalgia with vertigo", "Mucous diarrhea with tenesmus", "Laryngitis with tickle"],
        "keynotes_de": ["Schwindelgefühl beim schnellen Bücken oder Kopfdrehen", "Bauchschmerzen mit unvollständiger Stuhlentleerung", "Kehlkopf trocken und wund mit Heiserkeit"],
        "keynotes_en": ["Dizziness on sudden stooping or turning", "Griping abdominal pain with mucoid evacuations", "Throat dry, hoarse, with constant scraping"],
        "better_de": ["Frische Luft", "Ruhe"],
        "better_en": ["Open air", "Rest"],
        "worse_de": ["Bücken", "Kopfbewegung"],
        "worse_en": ["Stooping", "Head motion"],
        "diff": ["Gelsemium", "Bryonia"],
        "sphere": ["Kopf", "Darm", "Kehlkopf"],
        "tier": 3
    },
    {
        "id": "duboisia-myoporoides",
        "latin": "Duboisia myoporoides",
        "cat": "plant",
        "de_name": "Korkholzbaum",
        "en_name": "Corkwood",
        "es_name": "Duboisia",
        "fr_name": "Duboisia",
        "it_name": "Duboisia",
        "el_name": "Ντουμπουαζία",
        "ru_name": "Дубоизия миртовидная",
        "de_essence": "Boerickes Atropin-Verwandter: Extreme Pupillenerweiterung (Mydriasis), Trockenheit im Rachen, ataktischer Gang und Scharlachfieber-Symptome.",
        "en_essence": "Boericke's atropinic nervous remedy: wide pupillary dilatation (mydriasis), dry parched pharynx, locomotor ataxia, and scarlatinal rash.",
        "indications_de": ["Extremer Mydriasis & Photophobie", "Trockenheit von Rachen und Schleimhäuten", "Ataktische Gangunsicherheit"],
        "indications_en": ["Extreme mydriasis and glare", "Dry parched throat and voice loss", "Locomotor ataxia and trembling"],
        "keynotes_de": ["Pupillen maximal erweitert und lichtstarr; Scharlachrote Konjunktiven", "Rachen extrem trocken, brennend heiß, Schlucken fast unmöglich", "Schwanken beim Gehen mit geschlossenen Augen"],
        "keynotes_en": ["Pupils dilated to maximum; paralysis of accommodation", "Intense dryness and redness of throat; voice reduced to whisper", "Unsteady staggering gait when eyes are shut"],
        "better_de": ["Dunkler Raum", "Kühle"],
        "better_en": ["Darkened room", "Coolness"],
        "worse_de": ["Licht", "Schlucken", "Bewegung"],
        "worse_en": ["Light", "Swallowing", "Motion"],
        "diff": ["Belladonna", "Gelsemium", "Stramonium"],
        "sphere": ["Auge", "Pupillarmuskulatur", "Rachen", "Motorik"],
        "tier": 2
    },
    {
        "id": "echinacea-purpurea",
        "latin": "Echinacea purpurea",
        "cat": "plant",
        "de_name": "Roter Sonnenhut",
        "en_name": "Purple Coneflower",
        "es_name": "Equinácea púrpura",
        "fr_name": "Échinacée pourpre",
        "it_name": "Echinacea purpurea",
        "el_name": "Εχινάκεια η πορφυρή",
        "ru_name": "Эхинацея пурпурная",
        "de_essence": "Boerickes großes Blutreinigungsmittel: Septische Zustände, Furunkel, Karbunkel, Insektenstiche, Schlangenbisse, eitrige Wundinfektionen und Abwehrschwäche.",
        "en_essence": "Boericke's premier blood-purifier: septic conditions, boils, carbuncles, insect stings, venomous bites, purulent lymphangitis, and lowered resistance.",
        "indications_de": ["Septische Allgemeininfektionen", "Furunkulose & bösartige Karbunkel", "Phlegmonen & Wundvergiftung"],
        "indications_en": ["Septicemia and pyemia", "Recurrent boils and carbuncles", "Bites and purulent infections"],
        "keynotes_de": ["Müdigkeit, Zerschlagenheit und Faulgeruch des Atems bei Sepsis", "Furunkel sind bläulich-rot, brennend schmerzhaft und heilen extrem langsam", "Stimuliert die körpereigene Leukozytenabwehr und reinigt das Blut"],
        "keynotes_en": ["Aching exhaustion, foul breath, and dusky skin in systemic toxemia", "Boils purplish, extremely painful, slow to mature with gangrenous tendency", "Corrects blood dyscrasia and restores immune resistance"],
        "better_de": ["Ruhe", "Warme Umschläge"],
        "better_en": ["Rest", "Warm compresses"],
        "worse_de": ["Körperliche Anstrengung", "Kälte"],
        "worse_en": ["Physical effort", "Cold"],
        "diff": ["Echinacea angustifolia", "Baptisia", "Arsenicum album"],
        "sphere": ["Blut", "Immunsystem", "Haut", "Lymphbahnen"],
        "tier": 1
    },
    {
        "id": "epiphegus-virginiana",
        "latin": "Epiphegus virginiana",
        "cat": "plant",
        "de_name": "Buchenspargel",
        "en_name": "Beechdrops",
        "es_name": "Epifego",
        "fr_name": "Épiphègue de Virginie",
        "it_name": "Epifego",
        "el_name": "Επίφηγος",
        "ru_name": "Эпифегус виргинский",
        "de_essence": "Boerickes 'Einkaufs-Kopfschmerz': Nervöse Erschöpfungskopfschmerzen nach Einkaufstouren, Festen oder Überanstrengung; Schläfenschmerz mit Übelkeit.",
        "en_essence": "Boericke's celebrated neurasthenic headache specific: pressing headache brought on by shopping, excitement, fatigue, or social visits.",
        "indications_de": ["Ermüdungskopfschmerz (Shopping-Headache)", "Nervöse Schläfenmigräne", "Speichelfluss mit Übelkeit"],
        "indications_en": ["Headache from shopping or excitement", "Nervous temporal migraine", "Salivation with nausea"],
        "keynotes_de": ["Kopfschmerz beginnt in einer Schläfe nach anstrengendem Stadtbummel", "Ständiges Verlangen, schleimigen Speichel auszuspucken", "Bessert zuverlässig nach kurzem Schlaf"],
        "keynotes_en": ["Pressing pain in temples provoked by shopping or bustling crowd", "Viscid saliva compelling constant spitting", "Relieved after a short refreshing nap"],
        "better_de": ["Schlafen", "Ruhe in dunklem Zimmer"],
        "better_en": ["Sleeping", "Rest in dark quiet room"],
        "worse_de": ["Einkaufen", "Menschenmengen", "Ermüdung"],
        "worse_en": ["Shopping", "Crowds", "Fatigue"],
        "diff": ["Gelsemium", "Iris versicolor", "Onosmodium"],
        "sphere": ["Schläfen", "Gehirn", "Speicheldrüsen"],
        "tier": 2
    },
    {
        "id": "erodios-cicutarium",
        "latin": "Erodios cicutarium (Erodium)",
        "cat": "plant",
        "de_name": "Gewöhnlicher Reiherschnabel",
        "en_name": "Storksbill",
        "es_name": "Agujas de cigüeña",
        "fr_name": "Bec-de-grue commun",
        "it_name": "Becco di gru comune",
        "el_name": "Ερώδιον",
        "ru_name": "Аистник обыкновенный",
        "de_essence": "Boerickes Hämostatikum bei massiven Uterusblutungen: Metrorrhagie, schwere Menorrhagie im Klimakterium und Blutungen bei Myomen.",
        "en_essence": "Boericke's reliable hemostatic for uterine flooding: active and passive metrorrhagia, climacteric hemorrhages, and fibroid bleeding.",
        "indications_de": ["Uterusblutungen (Metrorrhagie)", "Klimakterische Dauerblutung", "Blutungen durch Uterusmyome"],
        "indications_en": ["Severe uterine hemorrhages", "Climacteric persistent bleeding", "Fibroid menorrhagia"],
        "keynotes_de": ["Reichliches, dunkles Blut fließt unaufhörlich aus dem Uterus", "Gefühl von Schwäche und Leere im Kreuzbein", "Wirksames pflanzliches Hämostyptikum"],
        "keynotes_en": ["Continuous flooding of dark blood from relaxed uterus", "Exhausting sacral ache accompanying hemorrhage", "Acts promptly as a natural uterine styptic"],
        "better_de": ["Flache Bettruhe"],
        "better_en": ["Lying flat in bed"],
        "worse_de": ["Aufstehen", "Gehen"],
        "worse_en": ["Rising", "Walking"],
        "diff": ["Trillium", "Thlaspi bursa pastoris", "Sabina"],
        "sphere": ["Uterus", "Endometrium", "Venöses Beckengeflecht"],
        "tier": 2
    },
    {
        "id": "eschscholtzia-californica",
        "latin": "Eschscholtzia californica",
        "cat": "plant",
        "de_name": "Kalifornischer Mohn / Goldmohn",
        "en_name": "California Poppy",
        "es_name": "Amapola de California",
        "fr_name": "Pavot de Californie",
        "it_name": "Papavero della California",
        "el_name": "Παπαρούνα της Καλιφόρνιας",
        "ru_name": "Эшшольция калифорнийская",
        "de_essence": "Boerickes unschädliches Schlafmittel: Beruhigendes Sedativum bei nervöser Schlaflosigkeit, Angst, neuralgischen Schmerzen und Zahnungsunruhe von Kindern.",
        "en_essence": "Boericke's harmless natural soporific: quiets nervous excitability, insomnia, neuralgic aches, and childhood dentition restlessness without narcosis.",
        "indications_de": ["Nervöse Schlaflosigkeit & Agitiertheit", "Zahnungsunruhe bei Kleinkindern", "Krampfartige Schmerzzustände"],
        "indications_en": ["Nervous insomnia and excitability", "Childhood dentition distress", "Mild neuralgic cramps"],
        "keynotes_de": ["Bringt friedlichen, tiefen Schlaf ohne betäubende Nachwirkungen", "Beruhigt das überreizte Nervensystem bei erschöpften Patienten", "Mildert Zahnschmerzen und nächtliches Weinen bei Kindern"],
        "keynotes_en": ["Produces calm, natural, refreshing sleep without stupor", "Soothes irritable nerves exhausted from stress", "Eases toothache and night crying in teething infants"],
        "better_de": ["Stille", "Dunkelheit"],
        "better_en": ["Quiet", "Darkness"],
        "worse_de": ["Lärm", "Emotionale Aufregung"],
        "worse_en": ["Noise", "Emotional excitement"],
        "diff": ["Passiflora", "Chamomilla", "Coffea cruda"],
        "sphere": ["Zentralnervensystem", "Schlafregulation", "Sensible Nerven"],
        "tier": 1
    },
    {
        "id": "eugenia-jambosa",
        "latin": "Eugenia jambosa",
        "cat": "plant",
        "de_name": "Rosenapfel",
        "en_name": "Rose-Apple",
        "es_name": "Pomarrosa",
        "fr_name": "Jambrosade",
        "it_name": "Mela rosa",
        "el_name": "Ευγενία",
        "ru_name": "Сизигиум ямбоз",
        "de_essence": "Boerickes Akne- und Hustenmittel: Akne rosacea, verhärtete Papeln im Gesicht, Kitzelhusten im Kehlkopf und plötzliches Kältegefühl nach Miktion.",
        "en_essence": "Boericke's acne and cough remedy: acne rosacea with indurated comedones, tickling throat cough, and sudden chilliness after urinating.",
        "indications_de": ["Akne rosacea & Knotenbildung", "Kehlkopfkitzel & Reizhusten", "Schüttelfrost nach Urinieren"],
        "indications_en": ["Acne rosacea and indurated pimples", "Dry tickling cough from pit of throat", "Shuddering chill after micturition"],
        "keynotes_de": ["Gesicht bedeckt mit schmerzhaften, entzündeten, derben Pusteln", "Kitzelhusten nachts, Patient muss sich aufsetzen", "Auffallendes Schütteln und Kältezittern unmittelbar nach dem Wasserlassen"],
        "keynotes_en": ["Face disfigured with hard painful indurated pimples", "Throat feels dry; tickling in pit of throat provoking cough", "Sudden chilliness and shaking immediately following urination"],
        "better_de": ["Kühle Anwendungen im Gesicht"],
        "better_en": ["Cool face washes"],
        "worse_de": ["Wärme", "Berührung", "Nachts"],
        "worse_en": ["Warmth", "Touch", "Night"],
        "diff": ["Eugenia caryophyllata", "Sulphur iodatum", "Rumex"],
        "sphere": ["Gesichtshaut", "Kehlkopf", "Harnblase"],
        "tier": 2
    },
    {
        "id": "galega-officinalis",
        "latin": "Galega officinalis",
        "cat": "plant",
        "de_name": "Echte Geißraute",
        "en_name": "Goat's Rue",
        "es_name": "Ruda cabruna",
        "fr_name": "Galéga officinal",
        "it_name": "Capraggine",
        "el_name": "Γαλέγα",
        "ru_name": "Козлятник лекарственный",
        "de_essence": "Boerickes laktationsförderndes Mittel: Ausgeprägte Galaktagoge-Wirkung bei Milchmangel (Agalaktie) stillender Mütter, Diabetes und Ödeme.",
        "en_essence": "Boericke's celebrated galactagogue: stimulates deficient breast milk secretion in nursing mothers, regulates appetite, and relieves edema in diabetes.",
        "indications_de": ["Milchmangel bei Stillenden (Agalaktie)", "Diabetische Polyurie", "Wassersucht"],
        "indications_en": ["Agalactia in nursing mothers", "Diabetic polyuria", "Dropsical effusions"],
        "keynotes_de": ["Fördert rasch und zuverlässig den Milchfluss bei stillenden Frauen", "Verbessert die Milchqualität und stärkt die Mutter", "Vermindert die Zuckerausscheidung bei milder Glykosurie"],
        "keynotes_en": ["Acts reliably as a potent stimulant of mammary lactation", "Improves quantity and nutrient quality of maternal milk", "Mild glycemic control and diuretic properties in dropsy"],
        "better_de": ["Ausreichende Flüssigkeitszufuhr"],
        "better_en": ["Adequate fluids"],
        "worse_de": ["Stillstress", "Erschöpfung"],
        "worse_en": ["Nursing strain", "Fatigue"],
        "diff": ["Ricinus communis", "Agnus castus", "Urtica urens"],
        "sphere": ["Mammae (Milchdrüsen)", "Stoffwechsel", "Laktation"],
        "tier": 1
    },
    {
        "id": "gentiana-quinqueflora",
        "latin": "Gentiana quinqueflora",
        "cat": "plant",
        "de_name": "Fünfblütiger Enzian",
        "en_name": "Five-Flowered Gentian",
        "es_name": "Genciana quinqueflora",
        "fr_name": "Gentiane à cinq fleurs",
        "it_name": "Genziana quinqueflora",
        "el_name": "Γεντιανή",
        "ru_name": "Горечавка пятицветковая",
        "de_essence": "Boerickes spezifisches Malariamittel: Chronische Wechselfieber, intermittierender Schüttelfrost, Appetitlosigkeit und Schwindel.",
        "en_essence": "Boericke's valued anti-periodic: chronic intermittent fevers, malarial chills, stubborn anorexia, and biliary headache.",
        "indications_de": ["Chronische Wechselfieber (Malaria)", "Hartnäckige Inappetenz", "Gallenkopfschmerz"],
        "indications_en": ["Chronic intermittent fevers", "Obstinate anorexia", "Bilious headache"],
        "keynotes_de": ["Schüttelfrost kehrt pünktlich jeden zweiten Tag wieder", "Komplette Appetitlosigkeit mit Bittergeschmack", "Mächtiges pflanzliches Bittertonikum"],
        "keynotes_en": ["Regular recurring chill and fever paroxysms", "Total loss of appetite with clean or coated tongue", "Powerful tonic in post-malarial cachexia"],
        "better_de": ["Warme Einhüllung"],
        "better_en": ["Warm wrapping"],
        "worse_de": ["Kälte", "Periodizität"],
        "worse_en": ["Cold", "Periodicity"],
        "diff": ["China", "Eupatorium perfoliatum", "Arsenicum"],
        "sphere": ["Thermoregulation", "Magen", "Leber"],
        "tier": 2
    }
]
