#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Boericke Expansion Batch 2 (remedies B to M)
"""

BATCH2_REMEDIES = [
    {
        "id": "beta-vulgaris",
        "latin": "Beta vulgaris",
        "cat": "plant",
        "de_name": "Rote Bete",
        "en_name": "Beetroot",
        "es_name": "Remolacha",
        "fr_name": "Betterave",
        "it_name": "Barbabietola",
        "el_name": "Παντζάρι",
        "ru_name": "Свекла обыкновенная",
        "de_essence": "Boerickes Mittel bei chronischem Katarrh der Atemwege und Rekonvaleszenz nach schweren Infekten; beeinflusst den Zellstoffwechsel positiv.",
        "en_essence": "Boericke's remedy for chronic catarrhal conditions of respiratory tract and debility after severe acute infections; stimulates cellular vitality.",
        "indications_de": ["Chronischer Bronchialkatarrh", "Postinfektiöse Rekonvaleszenz", "Verdauungsatonie"],
        "indications_en": ["Chronic bronchial catarrh", "Post-infectious convalescence", "Digestive atony"],
        "keynotes_de": ["Hartnäckiger Husten nach Influenza mit zähem Auswurf", "Allgemeine Schwäche mit Anämiegefühl", "Neigung zu Erkältungen bei Kälteeinbruch"],
        "keynotes_en": ["Protracted post-influenzal cough with tenacious mucus", "General weakness with pallor", "Susceptibility to chills and catarrhs"],
        "better_de": ["Wärme", "Ruhe"],
        "better_en": ["Warmth", "Rest"],
        "worse_de": ["Kälte", "Zugluft"],
        "worse_en": ["Cold", "Drafts"],
        "diff": ["Alfalfa", "China", "Avena sativa"],
        "sphere": ["Atmungstrakt", "Blutbildung", "Stoffwechsel"],
        "tier": 3
    },
    {
        "id": "betonica-aquatica",
        "latin": "Betonica aquatica",
        "cat": "plant",
        "de_name": "Wasser-Betonie",
        "en_name": "Water Betony",
        "es_name": "Betónica acuática",
        "fr_name": "Bétoine aquatique",
        "it_name": "Betonica acquatica",
        "el_name": "Βετονίκη",
        "ru_name": "Буквица водяная",
        "de_essence": "Skrofulöse Drüsenschwellungen am Hals, chronischer Kopfschmerz und Schläfenklopfen.",
        "en_essence": "Scrofulous induration of cervical glands, chronic congested headache, and throbbing in temples.",
        "indications_de": ["Zervikale Lymphadenitis", "Kongestiver Kopfschmerz", "Skrofulöse Diathese"],
        "indications_en": ["Cervical lymphadenitis", "Congestive headache", "Scrofulous diathesis"],
        "keynotes_de": ["Verhärtete Drüsenketten am Hals", "Klopfen und Völlegefühl in den Schläfen", "Verschlimmerung durch geistige Anstrengung"],
        "keynotes_en": ["Hard enlarged glands along neck", "Throbbing sensation with temporal fullness", "Worse from mental application"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting upright"],
        "worse_de": ["Bücken", "Geistige Arbeit"],
        "worse_en": ["Stooping", "Mental exertion"],
        "diff": ["Scrophularia", "Cistus canadensis"],
        "sphere": ["Lymphdrüsen", "Kopf", "Blutgefäße"],
        "tier": 3
    },
    {
        "id": "boldo",
        "latin": "Boldo (Peumus boldus)",
        "cat": "plant",
        "de_name": "Boldostrauch",
        "en_name": "Boldo",
        "es_name": "Boldo",
        "fr_name": "Boldo",
        "it_name": "Boldo",
        "el_name": "Μπόλντο",
        "ru_name": "Болдо",
        "de_essence": "Boerickes Leber- und Gallensteinmittel: Gallenstauung, Cholelithiasis, schmerzhaftes Brennen im rechten Hypochondrium und bitterer Geschmack.",
        "en_essence": "Boericke's celebrated liver remedy: gall-stones, hepatic torpor, burning in right hypochondrium, bitter taste, and heavy bilious malaise.",
        "indications_de": ["Cholelithiasis & Gallenstau", "Schmerzhafte Hepatomegalie", "Bitteres Aufstoßen"],
        "indications_en": ["Cholelithiasis and biliary stasis", "Tender hepatomegaly", "Bitter bilious eructations"],
        "keynotes_de": ["Brennender Schmerz in der Lebergegend strahlt zum Magen", "Dunkler, lehmfarbener Stuhl mit Bittergeschmack im Mund", "Starke Schwere und Müdigkeit nach fetten Mahlzeiten"],
        "keynotes_en": ["Burning heavy ache in liver region radiating to epigastrium", "Clay-colored stool with persistent bitter taste", "Extreme drowsiness and heaviness after rich food"],
        "better_de": ["Rechtsseitenlage mit Kissen"],
        "better_en": ["Lying on right side supported"],
        "worse_de": ["Druck", "Fettes Essen", "Bewegung"],
        "worse_en": ["Pressure", "Fatty food", "Motion"],
        "diff": ["Chelidonium", "Carduus marianus", "Chionanthus"],
        "sphere": ["Leber", "Gallenblase", "Gallengänge"],
        "tier": 1
    },
    {
        "id": "borago-officinalis",
        "latin": "Borago officinalis",
        "cat": "plant",
        "de_name": "Borretsch",
        "en_name": "Borage",
        "es_name": "Borraja",
        "fr_name": "Bourrache",
        "it_name": "Borragine",
        "el_name": "Μποράντζα",
        "ru_name": "Бурачник лекарственный",
        "de_essence": "Pleuritischer Schmerz, melancholische Verstimmung mit Herzklopfen und verminderte Harnausscheidung.",
        "en_essence": "Pleuritic stitching, melancholic sadness with palpitation, and sluggish urinary excretion.",
        "indications_de": ["Pleuritis & Bruststechen", "Herzklopfen bei Melancholie", "Verminderte Diurese"],
        "indications_en": ["Pleuritic stitches", "Melancholy with palpitation", "Oliguria"],
        "keynotes_de": ["Stechen in der seitlichen Brustwand beim tiefen Einatmen", "Traurigkeit ohne ersichtlichen Grund mit Herzpochen", "Bessert nach reichlichem Wasserlassen"],
        "keynotes_en": ["Stitching in lateral thorax on deep inspiration", "Unexplained gloominess accompanied by palpitations", "General relief after free diuresis"],
        "better_de": ["Ruhelage auf schmerzhafter Seite"],
        "better_en": ["Lying on affected side"],
        "worse_de": ["Tiefe Inspiration", "Kälte"],
        "worse_en": ["Deep breathing", "Cold"],
        "diff": ["Bryonia", "Asclepias tuberosa"],
        "sphere": ["Pleura", "Herz", "Gemüt", "Nieren"],
        "tier": 3
    },
    {
        "id": "botulinum",
        "latin": "Botulinum",
        "cat": "nosode",
        "de_name": "Botulinum-Toxin",
        "en_name": "Botulinum Nosode",
        "es_name": "Botulinum",
        "fr_name": "Botulinum",
        "it_name": "Botulinum",
        "el_name": "Βοτουλίνο",
        "ru_name": "Ботулинум",
        "de_essence": "Boerickes Bild bei Fleischvergiftung (Botulismus): Ptosis, Doppelbilder, Schlucklähmung, extreme Muskelschwäche und trockener Mund.",
        "en_essence": "Boericke's toxemic picture: ptosis, diplopia, pharyngeal paralysis, muscular prostration, and dry mucous membranes from food poisoning.",
        "indications_de": ["Ptosis & Augenmuskellähmung", "Schluckunfähigkeit & Dysphagie", "Extreme Muskelschwäche"],
        "indications_en": ["Ptosis and ocular motor paralysis", "Dysphagia from throat paresis", "Sudden profound motor exhaustion"],
        "keynotes_de": ["Herabhängen der oberen Augenlider mit Doppeltsehen", "Feste Nahrung kann nicht geschluckt werden; verschluckt sich leicht", "Völlige Lähmigkeit der Extremitäten bei wachem Verstand"],
        "keynotes_en": ["Drooping eyelids (ptosis) with double vision", "Inability to swallow solids; choking easily", "Profound muscular flaccidity with retained consciousness"],
        "better_de": ["Flaches Liegen in Ruhe"],
        "better_en": ["Lying flat quietly"],
        "worse_de": ["Schluckversuch", "Körperliche Bewegung"],
        "worse_en": ["Attempting to swallow", "Exertion"],
        "diff": ["Gelsemium", "Causticum", "Conium"],
        "sphere": ["Hirnnerven", "Augenmuskeln", "Schlingzentrum"],
        "tier": 2
    },
    {
        "id": "buxus-sempervirens",
        "latin": "Buxus sempervirens",
        "cat": "plant",
        "de_name": "Gewöhnlicher Buchsbaum",
        "en_name": "Boxwood",
        "es_name": "Boj",
        "fr_name": "Buis commun",
        "it_name": "Bosso",
        "el_name": "Πύξος",
        "ru_name": "Самшит вечнозеленый",
        "de_essence": "Rheumatische Gicht mit Gelenksteifigkeit, juckendes Kopfekzem mit dicken Krusten und krampfartige Darmkoliken.",
        "en_essence": "Rheumatic gout with joint stiffness, itchy scalp eczema with thick crusts, and spasmodic abdominal cramps.",
        "indications_de": ["Chronischer Gelenkrheumatismus", "Krustiges Kopfekzem", "Krampfkoliken"],
        "indications_en": ["Chronic articular rheumatism", "Crusted scalp eczema", "Spasmodic colic"],
        "keynotes_de": ["Steife, schmerzende Gelenke, die bei Wetterwechsel anschwellen", "Kopfhaut juckt brennend unter schorfigen Belägen", "Krämpfe bessern durch warme Umschläge"],
        "keynotes_en": ["Stiff painful joints aggravated before changes in weather", "Scalp intensely itchy beneath thick crusty scabs", "Cramps ameliorated by hot applications"],
        "better_de": ["Wärme", "Fortgesetzte Bewegung"],
        "better_en": ["Warmth", "Continued motion"],
        "worse_de": ["Kälte", "Nässe", "Ruhebeginn"],
        "worse_en": ["Cold", "Wet", "Beginning of motion"],
        "diff": ["Rhus tox", "Mezereum"],
        "sphere": ["Gelenke", "Kopfhaut", "Magen-Darm-Kanal"],
        "tier": 3
    },
    {
        "id": "cajuputum",
        "latin": "Cajuputum (Oleum cajuputi)",
        "cat": "plant",
        "de_name": "Kajeputöl",
        "en_name": "Cajuput Oil",
        "es_name": "Cajeput",
        "fr_name": "Cajeput",
        "it_name": "Cajeput",
        "el_name": "Καγιεπούτ",
        "ru_name": "Каяпут",
        "de_essence": "Boerickes Tympanites- und Schluckaufmittel: Enorme Blähungsauftreibung, Zunge fühlt sich zu dick an, nervöser Singultus und hysterische Krämpfe.",
        "en_essence": "Boericke's celebrated carminative: enormous flatulent distention, retroverted tongue feeling, persistent nervous hiccough, and hysterical spasms.",
        "indications_de": ["Meteorismus & Trommelbauch", "Hartnäckiger Schluckauf (Singultus)", "Hysterische Globusempfindung"],
        "indications_en": ["Tympanites and gaseous distention", "Obstinate nervous hiccough", "Globus hystericus and tongue swelling"],
        "keynotes_de": ["Bauch trommelartig aufgetrieben, kann keine beengende Kleidung ertragen", "Patient hat das Gefühl, die Zunge sei geschwollen und verlege den Hals", "Schluckauf paroxysmal bei nervösen, hysterischen Patienten"],
        "keynotes_en": ["Abdomen puffed up like a drum, cannot bear tight clothing", "Tongue feels swollen, filling whole mouth; chokes on swallowing", "Spasmodic hiccough triggered by emotional distress"],
        "better_de": ["Abgang von Winden", "Aufstoßen"],
        "better_en": ["Passing flatus", "Eructation"],
        "worse_de": ["Eng anliegende Kleidung", "Essen"],
        "worse_en": ["Tight clothes", "Eating"],
        "diff": ["Asafoetida", "Carbo veg", "Ignatia"],
        "sphere": ["Magen-Darm-Trakt", "Speiseröhre", "Nervensystem"],
        "tier": 2
    },
    {
        "id": "calluna-vulgaris",
        "latin": "Calluna vulgaris",
        "cat": "plant",
        "de_name": "Besenheide / Heidekraut",
        "en_name": "Heather",
        "es_name": "Brezo común",
        "fr_name": "Bruyère commune",
        "it_name": "Brugo",
        "el_name": "Ερείκη",
        "ru_name": "Вереск обыкновенный",
        "de_essence": "Chronische Zystitis mit Hämaturie, Harnsäuregrieß, brennender Schmerz in Blase und Nieren.",
        "en_essence": "Chronic cystitis with microscopic hematuria, uric acid sand, and burning pain in bladder neck.",
        "indications_de": ["Chronische Zystitis & Harngrieß", "Mikrohämaturie", "Prostatareizung"],
        "indications_en": ["Chronic cystitis with gravel", "Microhematuria", "Prostatic irritation"],
        "keynotes_de": ["Brennen und Schneiden am Blasenblasenhals während der Miktion", "Urin enthält rötlichen Harnsäuresand", "Linderung durch reichliches Trinken von heißem Wasser"],
        "keynotes_en": ["Burning cutting at neck of bladder during urination", "Urine cloudy depositing reddish gravel", "Relieved by drinking copiously of warm fluids"],
        "better_de": ["Wärme", "Reichliches Trinken"],
        "better_en": ["Warmth", "Abundant fluids"],
        "worse_de": ["Kälte", "Nässe", "Harndrang unterdrücken"],
        "worse_en": ["Cold", "Wet feet", "Retaining urine"],
        "diff": ["Uva ursi", "Berberis", "Thlaspi"],
        "sphere": ["Harnblase", "Blasenhals", "Nieren"],
        "tier": 2
    },
    {
        "id": "caltha-palustris",
        "latin": "Caltha palustris",
        "cat": "plant",
        "de_name": "Sumpfdotterblume",
        "en_name": "Marsh Marigold",
        "es_name": "Hierba centella",
        "fr_name": "Populage des marais",
        "it_name": "Calta palustre",
        "el_name": "Κάλθα",
        "ru_name": "Калужница болотная",
        "de_essence": "Pemphigus mit schmerzhaften Blasen, eitrige Hauteffloreszenzen und krampfartige Uterusbeschwerden.",
        "en_essence": "Pemphigus with painful burning bullae, pustular dermatitis, and uterine cramps.",
        "indications_de": ["Pemphigus & Blasenbildung", "Pustulöses Ekzem", "Dysmenorrhoe mit Übelkeit"],
        "indications_en": ["Pemphigus and bullous eruptions", "Pustular eczema", "Dysmenorrhea with nausea"],
        "keynotes_de": ["Große wässrige Blasen auf entzündeter roter Hautunterlage", "Unerträgliches Brennen und Jucken der Blasen", "Krämpfe im Uterus strahlen in die Oberschenkel"],
        "keynotes_en": ["Large bullae filled with clear or turbid fluid on inflamed skin", "Burning stinging pain in skin lesions", "Uterine cramps radiating down thighs"],
        "better_de": ["Kühle Umschläge"],
        "better_en": ["Cool applications"],
        "worse_de": ["Wärme", "Kratzen"],
        "worse_en": ["Warmth", "Scratching"],
        "diff": ["Ranunculus bulbosus", "Rhus tox", "Cantharis"],
        "sphere": ["Haut", "Uterus", "Nervensystem"],
        "tier": 3
    },
    {
        "id": "canchalagua",
        "latin": "Canchalagua (Centaurium chilense)",
        "cat": "plant",
        "de_name": "Chilenisches Tausendgüldenkraut",
        "en_name": "California Centaury",
        "es_name": "Canchalagua",
        "fr_name": "Canchalagua",
        "it_name": "Canchalagua",
        "el_name": "Καντσαλάγκουα",
        "ru_name": "Канчалагуа",
        "de_essence": "Boerickes Wechselfiebermittel: Periodisches Intermittensfieber mit schwerem Zerschlagenheitsgefühl im Kopf, Ohrensausen und Milzschmerz.",
        "en_essence": "Boericke's intermittent fever remedy: periodic malaria-like chills, bruised soreness of head, ringing in ears, and splenic tenderness.",
        "indications_de": ["Intermittierende Malariafieber", "Zerschlagenheits-Cephalgie", "Milzvergrößerung & Schmerz"],
        "indications_en": ["Intermittent malarial paroxysms", "Bruised aching headache", "Splenic congestion and soreness"],
        "keynotes_de": ["Gefühl, als ob der ganze Kopf zerschlagen und wund wäre", "Schüttelfrost beginnt im Rücken und breitet sich über den ganzen Körper aus", "Heftiges Summen und Klingeln in beiden Ohren"],
        "keynotes_en": ["General bruised aching in head and eyeballs", "Chills begin in spine and spread outward", "Ringing tinnitus accompanying periodic fevers"],
        "better_de": ["Warme Einhüllung", "Schwitzen"],
        "better_en": ["Warm wrapping", "Sweating"],
        "worse_de": ["Kälte", "Zugluft", "Vormittags"],
        "worse_en": ["Cold", "Drafts", "Morning hours"],
        "diff": ["China", "Gelsemium", "Eupatorium perfoliatum"],
        "sphere": ["Thermoregulation", "Milz", "Kopf", "Ohren"],
        "tier": 2
    },
    {
        "id": "carica-papaya",
        "latin": "Carica papaya",
        "cat": "plant",
        "de_name": "Melonenbaum / Papaya",
        "en_name": "Papaya",
        "es_name": "Papaya",
        "fr_name": "Papayer",
        "it_name": "Papaia",
        "el_name": "Παπάγια",
        "ru_name": "Папайя",
        "de_essence": "Dyspepsie durch mangelnde Magensäure- und Enzymsekretion, unvollständig verdaute Speisen im Stuhl, Leberträgheit und Völlegefühl.",
        "en_essence": "Enzymatic dyspepsia with deficient gastric and pancreatic secretion, lienteric undigested stools, and liver sluggishness.",
        "indications_de": ["Fermentative Dyspepsie", "Lienterie (unverdaute Speisen)", "Magen-Darm-Atonie"],
        "indications_en": ["Enzymatic indigestion", "Undigested food in stool", "Gastrointestinal atony"],
        "keynotes_de": ["Speisen liegen stundenlang wie ein schwerer Stein im Magen", "Stuhl enthält erkennbare Reste der Mahlzeit", "Fett- und Fleischunverträglichkeit mit sauer-faulem Aufstoßen"],
        "keynotes_en": ["Food remains like a leaden weight in epigastrium", "Passes undigested particles in soft stool", "Intolerance of meats and fats with heavy foul eructations"],
        "better_de": ["Mäßige Bewegung im Freien"],
        "better_en": ["Gentle walking outdoors"],
        "worse_de": ["Nach Fleischmahlzeiten", "Überessen"],
        "worse_en": ["After meat", "Overeating"],
        "diff": ["Carbo veg", "Nux vomica", "Lycopodium"],
        "sphere": ["Magen", "Pankreas", "Darmtrakt"],
        "tier": 2
    },
    {
        "id": "cascara-sagrada",
        "latin": "Cascara sagrada (Rhamnus purshiana)",
        "cat": "plant",
        "de_name": "Amerikanische Faulbaumrinde",
        "en_name": "Sacred Bark",
        "es_name": "Cáscara sagrada",
        "fr_name": "Cascara sagrada",
        "it_name": "Cascara sagrada",
        "el_name": "Κασκάρα σαγκράντα",
        "ru_name": "Каскара саграда",
        "de_essence": "Boerickes chronisches Obstipationsmittel: Chronische Atonie des Kolons, hartnäckige Stuhlverstopfung ohne Drang, Hämorrhoiden und Magenleere.",
        "en_essence": "Boericke's celebrated chronic constipation remedy: restored intestinal muscular tonicity, obstinate constipation without urging, and hemorrhoids.",
        "indications_de": ["Chronische atonische Obstipation", "Darmträgheit nach Abführmittelmissbrauch", "Kongestive Hämorrhoiden"],
        "indications_en": ["Chronic atonic constipation", "Intestinal sluggishness from purgative abuse", "Congestive hemorrhoids"],
        "keynotes_de": ["Stuhlverstopfung über Tage ohne jeden physiologischen Reiz", "Tonisiert die erschlaffte Darmmuskulatur dauerhaft", "Kongestion im Rektum mit schmerzhaftem Druck"],
        "keynotes_en": ["Absence of desire for stool for days without distress", "Restores natural peristalsis to relaxed intestinal wall", "Rectal fullness and aching hemorrhoids"],
        "better_de": ["Reichliches Wassertrinken"],
        "better_en": ["Drinking plenty of water"],
        "worse_de": ["Sitzende Lebensweise"],
        "worse_en": ["Sedentary lifestyle"],
        "diff": ["Hydrastis", "Nux vomica", "Collinsonia"],
        "sphere": ["Dickdarm", "Rektum", "Pfortadersystem"],
        "tier": 1
    },
    {
        "id": "cascarilla",
        "latin": "Cascarilla (Croton eluteria)",
        "cat": "plant",
        "de_name": "Kaskarillbaum",
        "en_name": "Sweet-Bark",
        "es_name": "Cascarilla",
        "fr_name": "Cascarille",
        "it_name": "Cascarilla",
        "el_name": "Κασκαρίλλα",
        "ru_name": "Каскарилла",
        "de_essence": "Boerickes Paradoxon: Kalte Extremitäten bei warmem Magen; schmerzlose, reichliche Darmblutungen, Durchfall mit Schleimhautfetzen.",
        "en_essence": "Boericke's striking keynote: cold extremities with subjective heat in stomach; painless bright red rectal bleeding, and mucous diarrhea.",
        "indications_de": ["Schmerzlose Darmblutung", "Dyspepsie mit Magenhitze", "Kälte der Extremitäten"],
        "indications_en": ["Painless intestinal hemorrhage", "Dyspepsia with warm stomach", "Cold hands and feet"],
        "keynotes_de": ["Stuhlgang gefolgt von reichlichem, schmerzlosen Blutabgang", "Magen fühlt sich warm und voll an, während Hände und Füße eiskalt sind", "Häufiges Verlangen nach warmen Getränken"],
        "keynotes_en": ["Copious painless hemorrhage from bowels after hard or soft stool", "Stomach feels comfortably warm while extremities are icy cold", "Desire for warm aromatic drinks"],
        "better_de": ["Wärme an den Füßen"],
        "better_en": ["Warmth to feet"],
        "worse_de": ["Nach dem Stuhlgang", "Kälte"],
        "worse_en": ["After stool", "Cold"],
        "diff": ["Hamamelis", "Phosphorus", "Cinchona"],
        "sphere": ["Darmschleimhaut", "Rektalvenen", "Magen"],
        "tier": 2
    },
    {
        "id": "cassia-sophera",
        "latin": "Cassia sophera",
        "cat": "plant",
        "de_name": "Sophera-Kassie",
        "en_name": "Senna sophera",
        "es_name": "Casusa",
        "fr_name": "Cassia sophera",
        "it_name": "Cassia sophera",
        "el_name": "Κασσία",
        "ru_name": "Кассия софера",
        "de_essence": "Boerickes indisches Asthmamittel: Krampfhafter Husten, Winterasthma, chronische Bronchitis und ringförmige Flechten (Tinea / Ringelflechte).",
        "en_essence": "Boericke's classic Indian asthma remedy: spasmodic bronchial cough, winter asthma, and ringworm (tinea) skin eruptions.",
        "indications_de": ["Winterasthma & Reizhusten", "Chronische Bronchitis", "Tinea & Ringelflechte"],
        "indications_en": ["Winter asthma", "Chronic bronchitis with wheezing", "Ringworm (tinea corporis)"],
        "keynotes_de": ["Atemnot tritt regelmäßig im Winter bei nasskaltem Wetter auf", "Krampfartiger Hustenanfall raubt den Schlaf", "Ringförmige, schuppende Herde auf Brust und Rücken"],
        "keynotes_en": ["Asthmatic wheezing recurring every winter in damp cold", "Suffocative paroxysmal cough waking patient at night", "Circular erythematous scaly patches on trunk"],
        "better_de": ["Wärme", "Aufrechtes Sitzen"],
        "better_en": ["Warmth", "Sitting upright"],
        "worse_de": ["Nasskaltes Wetter", "Winter", "Nachts"],
        "worse_en": ["Damp cold weather", "Winter", "Night"],
        "diff": ["Blatta orientalis", "Justicia adhatoda", "Bacillinum"],
        "sphere": ["Bronchien", "Haut", "Atmungsorgane"],
        "tier": 2
    },
    {
        "id": "castoreum",
        "latin": "Castoreum",
        "cat": "animal",
        "de_name": "Bibergeil",
        "en_name": "Castor",
        "es_name": "Castóreo",
        "fr_name": "Castoréum",
        "it_name": "Castoreo",
        "el_name": "Καστόριο",
        "ru_name": "Кастореум (бобровая струя)",
        "de_essence": "Boerickes Hysteriemittel: Ausgeprägte nervöse Erschöpfung bei hysterischen Frauen, krampfhafte Unterleibskoliken, Zittrigkeit und Kältegefühl.",
        "en_essence": "Boericke's classic neurotic remedy: extreme nervous exhaustion in hysterical women, spasmodic abdominal colic, trembling, and internal chilling.",
        "indications_de": ["Hysterische Erschöpfungszustände", "Krampfhafte Menstruationskolik", "Nervöses Zittern"],
        "indications_en": ["Hysterical nervous prostration", "Spasmodic dysmenorrheal colic", "Nervous trembling and chilliness"],
        "keynotes_de": ["Zittern und Schwäche bei geringster Erregung oder Überanstrengung", "Bauchkolik bessert nur durch Zusammenkrümmen und festen Druck", "Ständige innere Kälte mit Frösteln"],
        "keynotes_en": ["Profound trembling and faintness from trivial excitement", "Colic compels patient to bend double and apply hard pressure", "Marked chilliness and sensitivity to cold drafts"],
        "better_de": ["Zusammenkrümmen", "Fester Druck", "Wärme"],
        "better_en": ["Bending double", "Hard pressure", "Warmth"],
        "worse_de": ["Aufregung", "Kälte", "Nach Menses"],
        "worse_en": ["Excitement", "Cold", "After menses"],
        "diff": ["Moschus", "Ignatia", "Valeriana"],
        "sphere": ["Vegetatives Nervensystem", "Uterus", "Gemüt"],
        "tier": 2
    },
    {
        "id": "centaurea-cyanus",
        "latin": "Centaurea cyanus",
        "cat": "plant",
        "de_name": "Kornblume",
        "en_name": "Cornflower",
        "es_name": "Aciano",
        "fr_name": "Bleuet des champs",
        "it_name": "Fiordaliso",
        "el_name": "Κενταύρια",
        "ru_name": "Василек синий",
        "de_essence": "Reizkonjunktivitis, Überanstrengung der Augen durch feine Arbeit, Tränenfluss und wiederkehrende Lidrandentzündung.",
        "en_essence": "Irritable conjunctivitis, eye strain from fine work, smarting lachrymation, and recurrent blepharitis.",
        "indications_de": ["Asthenopie & Augenüberlastung", "Katarrhalische Konjunktivitis", "Lidrandentzündung"],
        "indications_en": ["Eye-strain from fine work", "Catarrhal conjunctivitis", "Marginal blepharitis"],
        "keynotes_de": ["Brennen und Brennschmerz in den Augen nach Lesen oder Nähen", "Lider morgens verklebt, rote Bindehaut", "Wohltuende Erleichterung durch Auswaschen mit Kornblumenextrakt"],
        "keynotes_en": ["Smarting burning in eyes after prolonged near work", "Lids agglutinated in morning with injected sclera", "Soothes irritated ocular membranes"],
        "better_de": ["Augen schließen", "Kühle Waschungen"],
        "better_en": ["Closing eyes", "Cool washing"],
        "worse_de": ["Künstliches Licht", "Lesen", "Rauch"],
        "worse_en": ["Artificial light", "Reading", "Smoke"],
        "diff": ["Euphrasia", "Ruta", "Cineraria"],
        "sphere": ["Augen", "Augenlider", "Konjunktiven"],
        "tier": 3
    },
    {
        "id": "centaurium-erythraea",
        "latin": "Centaurium erythraea",
        "cat": "plant",
        "de_name": "Echtes Tausendgüldenkraut",
        "en_name": "Centaury",
        "es_name": "Centaurea menor",
        "fr_name": "Petite centaurée",
        "it_name": "Centauro maggiore",
        "el_name": "Ερυθραία",
        "ru_name": "Золототысячник обыкновенный",
        "de_essence": "Atonische Dyspepsie mit bitterem Aufstoßen, Appetitlosigkeit nach schweren Krankheiten, Leberstauung und chronisches Sodbrennen.",
        "en_essence": "Atonic dyspepsia with bitter eructations, anorexia following debilitating diseases, liver stasis, and chronic pyrosis.",
        "indications_de": ["Atonische Dyspepsie", "Anorexie & Rekonvaleszenz", "Gallenstauung"],
        "indications_en": ["Atonic dyspepsia", "Anorexia and debility", "Biliary stasis"],
        "keynotes_de": ["Bitterer Geschmack im Mund mit Widerwillen gegen Speisen", "Schweregefühl im Magen kurz nach Beginn des Essens", "Regt die Gallen- und Magensaftsekretion kräftig an"],
        "keynotes_en": ["Persistent bitter taste with distaste for all food", "Fullness and weight in stomach after only few mouthfuls", "Stimulates glandular secretions of digestive tract"],
        "better_de": ["Kleine Mahlzeiten", "Ruhe"],
        "better_en": ["Small meals", "Rest"],
        "worse_de": ["Schwere Speisen", "Überlastung"],
        "worse_en": ["Heavy meals", "Overexertion"],
        "diff": ["Gentiana lutea", "Nux vomica", "Hydrastis"],
        "sphere": ["Magen", "Leber", "Gallenblase"],
        "tier": 2
    },
    {
        "id": "cephalandra-indica",
        "latin": "Cephalandra indica",
        "cat": "plant",
        "de_name": "Indischer Efeu-Kürbis",
        "en_name": "Kundru",
        "es_name": "Cephalandra",
        "fr_name": "Cephalandra",
        "it_name": "Cephalandra",
        "el_name": "Κεφαλένδρα",
        "ru_name": "Цефаландра индийская",
        "de_essence": "Boerickes indisches Diabetesmittel: Diabetes mellitus mit unstillbarem Durst, Mundtrockenheit, massiver Glukosurie und rascher Abmagerung.",
        "en_essence": "Boericke's celebrated Indian diabetes specific: diabetes mellitus with burning unquenchable thirst, dryness of mouth, glycosuria, and exhaustion.",
        "indications_de": ["Diabetes mellitus mit Glykosurie", "Unstillbarer Durst & Mundtrockenheit", "Diabetische Erschöpfung"],
        "indications_en": ["Diabetes mellitus with glycosuria", "Unquenchable burning thirst", "Diabetic prostration"],
        "keynotes_de": ["Trinkt riesige Mengen kaltes Wasser ohne Durststillung", "Mund und Lippen wie ausgedörrt und brennend heiß", "Urin reichlich, enthält reichlich Zucker; Patient magert sichtlich ab"],
        "keynotes_en": ["Drinks huge quantities of cold water without quenching thirst", "Mouth and tongue parched, dry, and burning hot", "Profuse clear urine loaded with sugar with rapid wasting"],
        "better_de": ["Kaltes Trinken (kurzzeitig)"],
        "better_en": ["Cold drinks (temporarily)"],
        "worse_de": ["Körperliche Anstrengung", "Fasten"],
        "worse_en": ["Physical exertion", "Fasting"],
        "diff": ["Syzygium jambolanum", "Abroma augusta", "Uranium nitricum"],
        "sphere": ["Pankreas", "Kohlenhydratstoffwechsel", "Nieren"],
        "tier": 1
    },
    {
        "id": "cetraria-islandica",
        "latin": "Cetraria islandica",
        "cat": "plant",
        "de_name": "Isländisches Moos",
        "en_name": "Iceland Moss",
        "es_name": "Musgo de Islandia",
        "fr_name": "Lichen d'Islande",
        "it_name": "Lichene d'Islanda",
        "el_name": "Βρύον της Ισλανδίας",
        "ru_name": "Цетрария исландская",
        "de_essence": "Chronische Phthisis pulmonum mit auszehrendem Husten, eitrigem Auswurf, Nachtschweißen, Durchfall und Magenbrennen.",
        "en_essence": "Chronic pulmonary phthisis with exhausting cough, purulent sputum, debilitating night sweats, and digestive irritability.",
        "indications_de": ["Auszehrender Phthisis-Husten", "Eitriger Bronchialauswurf", "Schwächende Nachtschweiße"],
        "indications_en": ["Consumptive exhausting cough", "Purulent bronchial expectoration", "Debilitating night sweats"],
        "keynotes_de": ["Ständiger Hustenreiz mit Schmerzen im oberen Brustkorb", "Auswurf gelblich-grün, bitter-salzig schmeckend", "Starke körperliche Abmagerung mit Nachtschweiß"],
        "keynotes_en": ["Constant tickling cough with soreness in upper chest", "Copious yellowish-green sputum with salty or bitter taste", "Rapid emaciation accompanied by nocturnal sweating"],
        "better_de": ["Warme Getränke", "Ruhe"],
        "better_en": ["Warm drinks", "Rest"],
        "worse_de": ["Kaltes Einatmen", "Sprechen", "Nachts"],
        "worse_en": ["Inhaling cold air", "Talking", "Night"],
        "diff": ["Stannum", "Myosotis", "Balsamum peruvianum"],
        "sphere": ["Lungen", "Bronchien", "Schleimhäute"],
        "tier": 2
    },
    {
        "id": "chaparro-amargoso",
        "latin": "Chaparro amargoso",
        "cat": "plant",
        "de_name": "Bitterbusch / Geißdorn",
        "en_name": "Goat-Bush",
        "es_name": "Chaparro amargoso",
        "fr_name": "Chaparro",
        "it_name": "Chaparro amargoso",
        "el_name": "Τσαπάρο",
        "ru_name": "Чапарро амаргозо",
        "de_essence": "Boerickes Spezifikum bei Amöbenruhr: Chronische Dysenterie mit dunklem Blut, quälendem Rektaltenesmus, schmerzhaftem Ziehen und Leberschwellung.",
        "en_essence": "Boericke's celebrated specific for amoebic dysentery: chronic bloody flux, severe painful tenesmus, hepatic tenderness, and mucous diarrhea.",
        "indications_de": ["Amöbenruhr & chronische Dysenterie", "Schmerzhafter Rektaltenesmus", "Blutig-schleimige Stühle"],
        "indications_en": ["Amoebic dysentery", "Painful rectal tenesmus", "Bloody mucous stools"],
        "keynotes_de": ["Häufige kleine Stühle aus reinem Blut und gallertigem Schleim", "Quälendes Drängen im Mastdarm vor und nach dem Stuhl", "Druckschmerz über dem aufsteigenden Kolon und der Leber"],
        "keynotes_en": ["Frequent small discharges of dark blood and jelly-like mucus", "Intense persistent rectal tenesmus not relieved by stool", "Tenderness over caecum and ascending colon"],
        "better_de": ["Nach Entleerung (nur vorübergehend)"],
        "better_en": ["After evacuation (temporarily)"],
        "worse_de": ["Nach dem Essen", "Bewegung"],
        "worse_en": ["After eating", "Motion"],
        "diff": ["Mercurius corrosivus", "Nux vomica", "Trombidium"],
        "sphere": ["Dickdarm", "Rektum", "Leber"],
        "tier": 1
    }
]
