#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Boericke Expansion Batch 4 (remedies G to Z)
"""

BATCH4_REMEDIES = [
    {
        "id": "geum-rivale",
        "latin": "Geum rivale",
        "cat": "plant",
        "de_name": "Bach-Nelkenwurz",
        "en_name": "Water Avens",
        "es_name": "Cariofilada acuática",
        "fr_name": "Benoîte des ruisseaux",
        "it_name": "Erba benedetta acquatica",
        "el_name": "Γέυον",
        "ru_name": "Гравилат речной",
        "de_essence": "Reißende Blasenschmerzen, chronische Schleimdiarrhoe und passive Schleimhautblutungen.",
        "en_essence": "Tearing bladder pain with burning, chronic mucous diarrhea, and passive mucosal hemorrhages.",
        "indications_de": ["Reißende Blasenschmerzen", "Chronische Schleimdiarrhoe", "Muköse Blutungen"],
        "indications_en": ["Tearing bladder pain", "Chronic mucous diarrhea", "Mucosal hemorrhages"],
        "keynotes_de": ["Reißendes Ziehen in der Blasenregion vor der Entleerung", "Stühle schleimig mit Bauchkrämpfen", "Allgemeines Gefühl von Beckenerschlaffung"],
        "keynotes_en": ["Tearing in bladder region prior to voiding", "Mucous stools with tenesmus", "General sensation of pelvic relaxation"],
        "better_de": ["Wärme", "Ruhe"],
        "better_en": ["Warmth", "Rest"],
        "worse_de": ["Kälte", "Nässe"],
        "worse_en": ["Cold", "Dampness"],
        "diff": ["Uva ursi", "Chimaphila"],
        "sphere": ["Harnblase", "Darmschleimhaut"],
        "tier": 3
    },
    {
        "id": "ginkgo-biloba",
        "latin": "Ginkgo biloba",
        "cat": "plant",
        "de_name": "Ginkgobaum",
        "en_name": "Maidenhair Tree",
        "es_name": "Ginkgo",
        "fr_name": "Ginkgo biloba",
        "it_name": "Ginkgo biloba",
        "el_name": "Γκίνγκο",
        "ru_name": "Гинкго двулопастный",
        "de_essence": "Zerebrale Durchblutungsstörungen, Schwindel, Tinnitus, Gedächtnisschwäche und Kälte der Akren bei Arteriosklerose.",
        "en_essence": "Cerebral circulatory insufficiency, vertigo, tinnitus, memory loss, and peripheral arterial chilliness in arteriosclerosis.",
        "indications_de": ["Zerebrale Zirkulationsstörung", "Tinnitus & vaskulärer Schwindel", "Vergesslichkeit & Benommenheit"],
        "indications_en": ["Cerebral circulatory deficit", "Tinnitus and vascular vertigo", "Memory failure and haziness"],
        "keynotes_de": ["Schwindel und Taubheitsgefühl im Kopf bei arteriosklerotischen Patienten", "Ständiges Rauschen und Brausen in den Ohren", "Kalte Finger und Zehen mit Kribbeln"],
        "keynotes_en": ["Vertigo and head numbness in elderly or arteriosclerotic subjects", "Persistent whooshing and buzzing tinnitus", "Cold extremities with paresthesias"],
        "better_de": ["Frische Luft", "Mäßige Bewegung"],
        "better_en": ["Fresh air", "Gentle walking"],
        "worse_de": ["Langes Liegen", "Wärmestau"],
        "worse_en": ["Prolonged recumbency", "Overheating"],
        "diff": ["Baryta carbonica", "Secale", "Conium"],
        "sphere": ["Hirngefäße", "Innenohr", "Periphere Arterien"],
        "tier": 1
    },
    {
        "id": "humulus-lupulus",
        "latin": "Humulus lupulus",
        "cat": "plant",
        "de_name": "Echter Hopfen",
        "en_name": "Hops",
        "es_name": "Lúpulo",
        "fr_name": "Houblon",
        "it_name": "Luppolo",
        "el_name": "Λυκίσκος",
        "ru_name": "Хмель обыкновенный",
        "de_essence": "Boerickes Sedativum: Nervöse Schlaflosigkeit, Blasentenesmus bei Neurasthenikern, zittrige Schwäche und Delirium tremens.",
        "en_essence": "Boericke's celebrated sedative: nervous insomnia, vesical tenesmus in neurasthenics, trembling exhaustion, and delirium tremens.",
        "indications_de": ["Nervöse Schlaflosigkeit", "Blasenreizung & Strangurie", "Zittrige Erschöpfung"],
        "indications_en": ["Nervous sleeplessness", "Vesical tenesmus / dysuria", "Tremulous nervous exhaustion"],
        "keynotes_de": ["Schlaflosigkeit durch unruhige Gedankenflut und Herzklopfen", "Brennen und schmerzhafter Krampf im Blasenhals", "Zittern der Hände bei nervöser Erschöpfung"],
        "keynotes_en": ["Insomnia from crowded thoughts and nervous excitement", "Burning dysuria and twitching at neck of bladder", "Tremor of limbs with general weakness"],
        "better_de": ["Ruhige dunkle Umgebung"],
        "better_en": ["Dark quiet surroundings"],
        "worse_de": ["Koffein", "Aufregung"],
        "worse_en": ["Coffee", "Excitement"],
        "diff": ["Passiflora", "Valeriana", "Cannabis sativa"],
        "sphere": ["Zentralnervensystem", "Harnblase", "Schlaf"],
        "tier": 2
    },
    {
        "id": "justicia-adhatoda",
        "latin": "Justicia adhatoda",
        "cat": "plant",
        "de_name": "Malabarnuss",
        "en_name": "Adhatoda vasica",
        "es_name": "Nuez de Malabar",
        "fr_name": "Noyer des Indes",
        "it_name": "Noce di Malabar",
        "el_name": "Ιουστικία",
        "ru_name": "Юстиция сосудистая",
        "de_essence": "Boerickes indisches Hauptmittel bei Atemwegsinfekten: Erstickender Kitzelhusten, akuter Schnupfen mit Dauerniesen und paroxysmales Asthma.",
        "en_essence": "Boericke's celebrated respiratory specific: suffocative paroxysmal cough, acute coryza with sneezing, bronchial asthma, and whooping cough.",
        "indications_de": ["Erstickender Kitzelhusten", "Akuter Schnupfen mit Niesanfällen", "Asthma bronchiale"],
        "indications_en": ["Suffocative racking cough", "Acute violent coryza and sneezing", "Asthmatic bronchospasm"],
        "keynotes_de": ["Hustenanfall führt fast zum Ersticken; Engegefühl in der Brust", "Unaufhörliches Niesen mit wässrigem Nasenausfluss und Tränen", "Keuchhusten mit Schleimrasseln und Erbrechen"],
        "keynotes_en": ["Suffocative cough paroxysms threatening asphyxia", "Incessant sneezing with profuse watery acrid discharge", "Whooping cough with tough mucus and retching"],
        "better_de": ["Aufrechtes Sitzen", "Frische Luft"],
        "better_en": ["Sitting erect", "Open air"],
        "worse_de": ["Geschlossene warme Räume", "Liegen"],
        "worse_en": ["Closed warm room", "Lying down"],
        "diff": ["Ipecacuanha", "Drosera", "Blatta orientalis"],
        "sphere": ["Bronchien", "Kehlkopf", "Nasenschleimhaut"],
        "tier": 1
    },
    {
        "id": "lactuca-virosa",
        "latin": "Lactuca virosa",
        "cat": "plant",
        "de_name": "Gift-Lattich",
        "en_name": "Wild Lettuce",
        "es_name": "Lechuga silvestre",
        "fr_name": "Laitue vireuse",
        "it_name": "Lattuga velenosa",
        "el_name": "Αγριομάρουλο",
        "ru_name": "Латук ядовитый",
        "de_essence": "Krampfhafter, trockener Erstickungshusten, Hydrothorax mit schwerer Atemnot, Schlaflosigkeit durch zerebrale Übererregung.",
        "en_essence": "Suffocative tight paroxysmal cough, hydrothorax with air hunger, and wakeful insomnia from cerebral excitement.",
        "indications_de": ["Krampfhusten & Hydrothorax", "Nervöse Schlaflosigkeit", "Präkordiale Enge"],
        "indications_en": ["Spasmodic cough and hydrothorax", "Nervous sleeplessness", "Precordial tightness"],
        "keynotes_de": ["Trockener, hohler Husten, der den Patienten aufrecht ins Bett zwingt", "Gefühl von Zusammenschnürung im Brustkorb mit Atemmangel", "Ständige Schläfrigkeit, kann aber vor Unruhe nicht einschlafen"],
        "keynotes_en": ["Tight suffocative cough waking patient suddenly", "Constriction of chest as if lungs were restricted", "Drowsiness yet complete inability to sleep from twitching"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting upright"],
        "worse_de": ["Flaches Liegen", "Nachts"],
        "worse_en": ["Lying flat", "Night"],
        "diff": ["Hyoscyamus", "Drosera", "Sticta"],
        "sphere": ["Atemwege", "Pleura", "Gehirn"],
        "tier": 2
    },
    {
        "id": "lapis-albus",
        "latin": "Lapis albus",
        "cat": "mineral",
        "de_name": "Gasteiner Gneis / Weisser Stein",
        "en_name": "Silico-Fluoride of Calcium",
        "es_name": "Lapis albus",
        "fr_name": "Lapis albus",
        "it_name": "Lapis albus",
        "el_name": "Λευκός λίθος",
        "ru_name": "Лапис альбус",
        "de_essence": "Boerickes Drüsen- und Strumamittel: Elastische Struma, chronische Lymphadenitis, Schmerzen bei malignen Drüsentumoren und Fibrome.",
        "en_essence": "Boericke's classic glandular remedy: elastic goiter, scrofulous lymphadenitis, burning pain in glandular tumors, and uterine fibroids.",
        "indications_de": ["Elastische Schilddrüsenvergrößerung (Struma)", "Chronische Lymphknotenverhärtung", "Brennende Tumorschmerzen"],
        "indications_en": ["Elastic thyroid goitre", "Indurated lymphatic glands", "Burning pain in neoplasm"],
        "keynotes_de": ["Struma fühlt sich weich-elastisch, nicht knochenhart an", "Brennende, stechende Schmerzen in geschwollenen Drüsen", "Mammafibrome und skrofulöse Halsdrüsen"],
        "keynotes_en": ["Goitre has an elastic, pliable feel rather than stony hardness", "Burning shooting pain in glandular indurations", "Fibroadenoma of breast and scrofulous nodes"],
        "better_de": ["Wärme", "Leichte Massage"],
        "better_en": ["Warmth", "Gentle handling"],
        "worse_de": ["Kälte", "Druck"],
        "worse_en": ["Cold", "Hard pressure"],
        "diff": ["Iodium", "Spongia", "Conium"],
        "sphere": ["Schilddrüse", "Lymphdrüsen", "Mammae"],
        "tier": 2
    },
    {
        "id": "latrodectus-mactans",
        "latin": "Latrodectus mactans",
        "cat": "animal",
        "de_name": "Schwarze Witwe",
        "en_name": "Black Widow Spider",
        "es_name": "Viuda negra",
        "fr_name": "Veuve noire",
        "it_name": "Vedova nera",
        "el_name": "Μαύρη χήρα",
        "ru_name": "Каракурт (черная вдова)",
        "de_essence": "Boerickes Angina-pectoris-Spezifikum: Furchtbare präkordiale Schmerzen, strahlen in die linke Schulter und den Arm bis in die Finger, Todesangst.",
        "en_essence": "Boericke's celebrated angina pectoris specific: agonizing precordial constriction radiating down left arm to fingertips, cold sweat, and fear of death.",
        "indications_de": ["Angina pectoris & Myokardischämie", "Präkordialer Vernichtungsschmerz", "Ausstrahlung in den linken Arm"],
        "indications_en": ["Angina pectoris", "Severe precordial constriction", "Radiation down left arm with numbness"],
        "keynotes_de": ["Schmerz schnürt das Herz wie ein eiserner Reifen zusammen", "Taubheit und Lähmungsgefühl des linken Armes bis zu den Fingerspitzen", "Kalter Schweiß, flacher Puls und unerträgliche Todesangst"],
        "keynotes_en": ["Violent constrictive precordial pain as if heart were grasped", "Numbness and aching extending down left arm to fingers", "Profound collapse with cold clammy sweat and dread of dying"],
        "better_de": ["Völlige Ruhe im Sitzen"],
        "better_en": ["Absolute quiet in sitting posture"],
        "worse_de": ["Die geringste Bewegung", "Aufstehen"],
        "worse_en": ["Slightest motion", "Rising"],
        "diff": ["Spigelia", "Cactus grandiflorus", "Digitalis"],
        "sphere": ["Koronararterien", "Myokard", "Nervus ulnaris"],
        "tier": 1
    },
    {
        "id": "lecithinum",
        "latin": "Lecithinum",
        "cat": "animal",
        "de_name": "Lecithin",
        "en_name": "Lecithin",
        "es_name": "Lecitina",
        "fr_name": "Lécithine",
        "it_name": "Lecitina",
        "el_name": "Λεκιθίνη",
        "ru_name": "Лецитин",
        "de_essence": "Boerickes Rekonvaleszenz- und Nährstoffmittel: Geistige und körperliche Erschöpfung, Anämie, Kachexie und neurasthenische Schlaflosigkeit.",
        "en_essence": "Boericke's valued nutrient tonic: mental and nervous exhaustion, post-febrile debility, anemia, emaciation, and insomnia.",
        "indications_de": ["Neurasthenische Erschöpfung", "Sekundäre Anämie & Abmagerung", "Geistige Überarbeitung"],
        "indications_en": ["Neurasthenic brain-fag", "Anemia and bodily wasting", "Mental exhaustion in students"],
        "keynotes_de": ["Boericke: 'Vermehrt die Zahl der roten Blutkörperchen und steigert das Körpergewicht'", "Müdigkeit, geistige Leere und Konzentrationsschwäche", "Gibt Nervenstärke und vitalisiert die Ernährung"],
        "keynotes_en": ["Boericke: 'Increases red corpuscles and builds up bodily weight'", "Tired brain, inability to sustain intellectual effort", "Restores vitality in neurasthenic convalescence"],
        "better_de": ["Gutes Essen", "Ausruhen"],
        "better_en": ["Nourishing diet", "Rest"],
        "worse_de": ["Geistige Anstrengung", "Schlafmangel"],
        "worse_en": ["Mental effort", "Loss of sleep"],
        "diff": ["Alfalfa", "Avena sativa", "Phosphoric acid"],
        "sphere": ["Zentralnervensystem", "Erythrozyten", "Ernährung"],
        "tier": 1
    },
    {
        "id": "leonurus-cardiaca",
        "latin": "Leonurus cardiaca",
        "cat": "plant",
        "de_name": "Echtes Herzgespann / Löwenschwanz",
        "en_name": "Motherwort",
        "es_name": "Agripalma",
        "fr_name": "Agripaume cardiaque",
        "it_name": "Cardiaca",
        "el_name": "Λεόνουρος",
        "ru_name": "Пустырник сердечный",
        "de_essence": "Nervöses Herzklopfen, kardiale Reizbarkeit im Klimakterium, Dysmenorrhoe und Schilddrüsenüberfunktion.",
        "en_essence": "Nervous palpitations, cardiac irritability in climacteric women, delayed painful menses, and thyrotoxic tachycardia.",
        "indications_de": ["Kardiale Neurose & Tachykardie", "Klimakterische Beschwerden", "Krampfhafte Menses"],
        "indications_en": ["Cardiac neurosis and palpitation", "Climacteric hot flushes", "Spasmodic dysmenorrhea"],
        "keynotes_de": ["Herzrasen bei emotionaler Aufregung mit Engegefühl", "Hitzewallungen und Schweißausbrüche in den Wechseljahren", "Krämpfe vor der Menses bessern bei Einsetzen des Flusses"],
        "keynotes_en": ["Rapid fluttering palpitations provoked by emotional stress", "Climacteric restlessness with sudden hot flushings", "Uterine cramping relieved as soon as menses appears"],
        "better_de": ["Ruhelage", "Wärme"],
        "better_en": ["Resting quiet", "Warmth"],
        "worse_de": ["Emotionale Erregung", "Körperliche Hektik"],
        "worse_en": ["Emotional turmoil", "Hurry"],
        "diff": ["Lycopus", "Crataegus", "Lachesis"],
        "sphere": ["Herz", "Uterus", "Schilddrüse"],
        "tier": 2
    },
    {
        "id": "leptandra-virginica",
        "latin": "Leptandra virginica",
        "cat": "plant",
        "de_name": "Virginischer Ehrenpreis",
        "en_name": "Culver's Root",
        "es_name": "Leptandra",
        "fr_name": "Véronique de Virginie",
        "it_name": "Leptandra",
        "el_name": "Λεπτάνδρα",
        "ru_name": "Лептандра виргинская",
        "de_essence": "Boerickes Lebermittel: Schwarze, teerartige, übelriechende Stühle (Melaena), Leberstauung mit dumpfem Schmerz und Gallenschläfrigkeit.",
        "en_essence": "Boericke's hallmark liver remedy: black, tarry, fetid stools, portal congestion, dull hepatic aching, and bilious drowsy headache.",
        "indications_de": ["Teerstühle & Melaena", "Chronische Leberstauung", "Gallenkopfschmerz mit Zungenbelag"],
        "indications_en": ["Black tarry stools", "Hepatic portal congestion", "Bilious headache with coated tongue"],
        "keynotes_de": ["Stühle pechschwarz, teerig, extrem faulig riechend", "Dumpfer Dauerschmerz in der Leber strahlt zum Magen", "Zunge dick gelb oder braun belegt in der Mitte"],
        "keynotes_en": ["Stools black as tar, mushy, extremely offensive", "Constant dull ache in right lobe of liver and gall-bladder", "Tongue coated thick yellow along middle line"],
        "better_de": ["Nach dem Stuhlgang"],
        "better_en": ["After stool"],
        "worse_de": ["Liegen auf dem Bauch", "Morgens"],
        "worse_en": ["Lying on stomach", "Morning"],
        "diff": ["Podophyllum", "Chelidonium", "Mercurius"],
        "sphere": ["Leber", "Pfortadersystem", "Darmschleimhaut"],
        "tier": 1
    },
    {
        "id": "liatris-spicata",
        "latin": "Liatris spicata",
        "cat": "plant",
        "de_name": "Prachtscharte",
        "en_name": "Colic Root / Button Snake-Root",
        "es_name": "Liatris",
        "fr_name": "Liatride en épi",
        "it_name": "Liatride",
        "el_name": "Λιάτρις",
        "ru_name": "Лиатрис колосистая",
        "de_essence": "Boerickes Diuretikum bei vaskulärer Wassersucht: Unterdrückter Harnabgang, kardiale und renale Ödeme, Blähungskoliken.",
        "en_essence": "Boericke's active diuretic: suppressed or deficient urination, general dropsy of cardiac or renal origin, and colic.",
        "indications_de": ["Wassersucht & Ödeme", "Oligurie & Harnretention", "Blähungskoliken"],
        "indications_en": ["General dropsy", "Suppression of urine / oliguria", "Flatulent colic"],
        "keynotes_de": ["Wassereinlagerung im Gewebe bei fast fehlender Harnmenge", "Reizt die Nierenepithelien zur reichlichen Wasserausscheidung an", "Kolikartige Schmerzen im Unterbauch"],
        "keynotes_en": ["Extensive anasarca with suppressed urinary excretion", "Powerful natural stimulant of renal secretion", "Abdominal griping with flatulence"],
        "better_de": ["Reichliche Miktion"],
        "better_en": ["Free urination"],
        "worse_de": ["Kälte", "Liegen"],
        "worse_en": ["Cold", "Lying down"],
        "diff": ["Apocynum", "Oxydendrum", "Digitalis"],
        "sphere": ["Nieren", "Blase", "Gefäßsystem"],
        "tier": 2
    },
    {
        "id": "lycopus-europaeus",
        "latin": "Lycopus europaeus",
        "cat": "plant",
        "de_name": "Ufer-Wolfstrapp",
        "en_name": "Bitter Bugleweed",
        "es_name": "Marrubio acuático",
        "fr_name": "Lycope d'Europe",
        "it_name": "Marrubio d'acqua",
        "el_name": "Λύκοπος",
        "ru_name": "Зюзник европейский",
        "de_essence": "Schilddrüsenüberfunktion, nervöse Tachykardie, hervortretende Augäpfel (Exophthalmus) und Hämoptysen.",
        "en_essence": "Hyperthyroidism, tumultuous cardiac palpitations, exophthalmos, and pulmonary hemorrhages.",
        "indications_de": ["Thyreotoxikose & Tachykardie", "Exophthalmus & Herzklopfen", "Hämoptysis bei Lungenerkrankung"],
        "indications_en": ["Hyperthyroidism / Basedow", "Exophthalmos and palpitations", "Hemoptysis in chest diseases"],
        "keynotes_de": ["Ungestümes Herzklopfen, das die Brustwand erschüttert", "Puls schnell, unregelmäßig, gespannt", "Bluthusten mit nervöser Unruhe und Furcht"],
        "keynotes_en": ["Tumultuous cardiac action jarring entire thorax", "Pulse rapid, bounding, irregular, easily excited", "Spitting of blood with chest oppression"],
        "better_de": ["Ruhe im Bett"],
        "better_en": ["Rest in bed"],
        "worse_de": ["Körperliche Anstrengung", "Aufregung"],
        "worse_en": ["Physical effort", "Excitement"],
        "diff": ["Lycopus virginicus", "Spigelia", "Iodium"],
        "sphere": ["Schilddrüse", "Herz", "Lungenkreislauf"],
        "tier": 2
    },
    {
        "id": "marrubium-vulgare",
        "latin": "Marrubium vulgare",
        "cat": "plant",
        "de_name": "Gemeiner Andorn",
        "en_name": "White Horehound",
        "es_name": "Marrubio blanco",
        "fr_name": "Marrube blanc",
        "it_name": "Marrubio comune",
        "el_name": "Μαρούβιο",
        "ru_name": "Шандра обыкновенная",
        "de_essence": "Chronische Bronchitis mit reichlichem Rasselgeräusch, zähem Schleim, Atemnot und dyspeptischer Schleimansammlung.",
        "en_essence": "Chronic bronchitis with copious bronchial rattling, tenacious mucus, dyspnea, and catarrhal dyspepsia.",
        "indications_de": ["Chronische Rasselbronchitis", "Zäher Bronchialschleim", "Schleimige Dyspepsie"],
        "indications_en": ["Chronic rattling bronchitis", "Tenacious bronchial mucus", "Catarrhal dyspepsia"],
        "keynotes_de": ["Lautes Schleimrasseln in der Brust ohne Kraft zum Abhusten", "Husten quält besonders morgens beim Erwachen", "Bitterer Magenkatarrh mit Schleimerbrechen"],
        "keynotes_en": ["Loud mucous rattling in chest with weak expectoration", "Cough violent on waking in morning", "Catarrhal stomach with mucus in vomitus"],
        "better_de": ["Wärme", "Nach Auswurf"],
        "better_en": ["Warmth", "After expectoration"],
        "worse_de": ["Morgens", "Kaltes Wetter"],
        "worse_en": ["Morning", "Cold weather"],
        "diff": ["Antimonium tartaricum", "Senega"],
        "sphere": ["Bronchien", "Schleimhäute", "Magen"],
        "tier": 2
    },
    {
        "id": "melilotus-alba",
        "latin": "Melilotus alba",
        "cat": "plant",
        "de_name": "Weißer Steinklee",
        "en_name": "White Sweet Clover",
        "es_name": "Trébol de olor blanco",
        "fr_name": "Mélilot blanc",
        "it_name": "Meliloto bianco",
        "el_name": "Μελίλωτος ο λευκός",
        "ru_name": "Донник белый",
        "de_essence": "Boerickes Kongestionsmittel: Berstender Stirnkopfschmerz mit hochrotem Gesicht, Erleichterung durch Nasenbluten (Epistaxis).",
        "en_essence": "Boericke's celebrated congestive headache remedy: bursting frontal headache with flushed face, miraculously relieved by epistaxis.",
        "indications_de": ["Kongestiver Berstkopfschmerz", "Epistaxis mit Entlastung", "Zerebrale Hyperämie"],
        "indications_en": ["Congestive bursting headache", "Epistaxis bringing relief", "Cerebral hyperaemia"],
        "keynotes_de": ["Schläfen und Halsschlagadern pochen sichtbar", "Heftigster Kopfschmerz verschwindet schlagartig, sobald Nasenbluten einsetzt", "Gesicht hochrot, brennend heiß, Augen injiziert"],
        "keynotes_en": ["Throbbing carotids and pounding temples", "Agonizing head pain ceases as soon as nosebleed occurs", "Face fiercely red and hot, eyes injected"],
        "better_de": ["Nasenbluten (Epistaxis)", "Ruhe"],
        "better_en": ["Nosebleed (epistaxis)", "Rest"],
        "worse_de": ["Bewegung", "Bücken", "Nachmittags"],
        "worse_en": ["Motion", "Stooping", "Afternoon"],
        "diff": ["Belladonna", "Glonoinum", "Melilotus officinalis"],
        "sphere": ["Gehirngefäße", "Kopf", "Nasenschleimhaut"],
        "tier": 1
    },
    {
        "id": "melissa-officinalis",
        "latin": "Melissa officinalis",
        "cat": "plant",
        "de_name": "Zitronenmelisse",
        "en_name": "Lemon Balm",
        "es_name": "Melisa / Toronjil",
        "fr_name": "Mélisse officinale",
        "it_name": "Melissa comune",
        "el_name": "Μέλισσα η φαρμακευτική",
        "ru_name": "Мелисса лекарственная",
        "de_essence": "Nervöse Magenbeschwerden, Herzflattern durch Blähungen (Roemheld-Syndrom), Angst und nervöse Schlaflosigkeit.",
        "en_essence": "Nervous gastrointestinal distress, cardiac fluttering from gaseous pressure (Roemheld syndrome), anxiety, and insomnia.",
        "indications_de": ["Nervöse Magenspasmen", "Roemheld-Syndrom & Herzstolpern", "Einschlafstörungen"],
        "indications_en": ["Nervous stomach spasms", "Gastro-cardiac syndrome", "Sleep onset insomnia"],
        "keynotes_de": ["Herzpochen wird ausgelöst durch Blähungen im Magen", "Krämpfe bessern durch warmes Trinken und Entspannung", "Sanftes Nerventonikum für überempfindliche Gemüter"],
        "keynotes_en": ["Cardiac fluttering provoked by flatulent distention", "Cramps ameliorated by warm infusions and relaxation", "Gentle soothing tonic for nervous hypochondriasis"],
        "better_de": ["Warme Getränke", "Ruhe"],
        "better_en": ["Warm drinks", "Rest"],
        "worse_de": ["Kummer", "Hektik", "Schwere Speisen"],
        "worse_en": ["Grief", "Hurry", "Heavy food"],
        "diff": ["Passiflora", "Ignatia", "Chamomilla"],
        "sphere": ["Magen", "Vegetatives Nervensystem", "Herz"],
        "tier": 2
    },
    {
        "id": "mentha-piperita",
        "latin": "Mentha piperita",
        "cat": "plant",
        "de_name": "Pfefferminze",
        "en_name": "Peppermint",
        "es_name": "Menta piperita",
        "fr_name": "Menthe poivrée",
        "it_name": "Menta piperita",
        "el_name": "Μέντα η πιπερώδης",
        "ru_name": "Мята перечная",
        "de_essence": "Boerickes Leitsymptom beim Husten: Trockener, unstillbarer Hustenreiz, ausgelöst durch Einatmen kalter Luft; Gastralgie mit Aufstoßen.",
        "en_essence": "Boericke's hallmark cough symptom: dry, paroxysmal cough instantly triggered by inhaling cold air; gastralgia with loud gas eructations.",
        "indications_de": ["Kaltluft-induzierter Husten", "Kitzeln in der Fossa suprasternalis", "Gasblähungen & Gastralgie"],
        "indications_en": ["Cough triggered by cold air", "Tickling in suprasternal fossa", "Gaseous gastralgia"],
        "keynotes_de": ["Jeder Atemzug kalter Luft provoziert sofortigen Husten", "Patient deckt den Mund mit Schal zu, um die Luft anzuwärmen", "Aufstoßen von riesigen Gasmengen erleichtert den Magen"],
        "keynotes_en": ["Every inhalation of cold air provokes violent cough", "Compelled to wrap scarf over mouth to warm inhaled air", "Immense noisy eructations of tasteless gas"],
        "better_de": ["Mund zudecken", "Warme Raumluft"],
        "better_en": ["Covering mouth", "Warm air"],
        "worse_de": ["Kaltes Einatmen", "Sprechen", "Rauch"],
        "worse_en": ["Inhaling cold air", "Speaking", "Smoke"],
        "diff": ["Rumex", "Spongia", "Carbo veg"],
        "sphere": ["Trachea", "Kehlkopf", "Magen"],
        "tier": 1
    },
    {
        "id": "mentha-pulegium",
        "latin": "Mentha pulegium",
        "cat": "plant",
        "de_name": "Polei-Minze",
        "en_name": "Pennyroyal",
        "es_name": "Poleo",
        "fr_name": "Menthe pouliot",
        "it_name": "Menta romana / Puleggio",
        "el_name": "Φλισκούνι",
        "ru_name": "Мята болотная",
        "de_essence": "Unterdrückte Menstruation durch Kälte, krampfhafte Beckenkoliken, Uterusatonie und zäher Kehlkopfkatarrh.",
        "en_essence": "Suppressed menses from getting feet wet, spasmodic pelvic colic, uterine atony, and tracheal catarrh.",
        "indications_de": ["Amenorrhoe nach Kälteeinwirkung", "Uterine Krampfkolik", "Trachealer Reizhusten"],
        "indications_en": ["Amenorrhea from cold exposure", "Spasmodic uterine colic", "Tracheal cough with thick mucus"],
        "keynotes_de": ["Ausbleiben der Menses nach nasskalten Füßen", "Bohrender Schmerz über dem Schambein", "Zäher Schleim im Kehlkopf schwer zu lösen"],
        "keynotes_en": ["Suppression of flow after getting feet chilled or wet", "Bearing-down and griping above pubes", "Tenacious phlegm in upper respiratory tract"],
        "better_de": ["Heiße Fußbäder", "Wärme"],
        "better_en": ["Hot foot-baths", "Warmth"],
        "worse_de": ["Kälte", "Nasse Füße"],
        "worse_en": ["Cold", "Wet feet"],
        "diff": ["Pulsatilla", "Senecio", "Hedeoma"],
        "sphere": ["Uterus", "Beckenorgane", "Trachea"],
        "tier": 2
    },
    {
        "id": "myrrha",
        "latin": "Myrrha (Commiphora myrrha)",
        "cat": "plant",
        "de_name": "Myrrhe",
        "en_name": "Myrrh",
        "es_name": "Mirra",
        "fr_name": "Myrrhe",
        "it_name": "Mirra",
        "el_name": "Σμύρνα",
        "ru_name": "Мирра",
        "de_essence": "Boerickes Mund- und Schleimhautmittel: Schwammiges, blutendes Zahnfleisch, schmerzhafte Aphthen, Mundgeruch und eitriger Bronchialkatarrh.",
        "en_essence": "Boericke's mucous membrane astringent: spongy bleeding gums, painful aphthae, fetid breath, and chronic purulent bronchitis.",
        "indications_de": ["Gingivitis & schwammiges Zahnfleisch", "Schmerzhafte Aphthen", "Chronische eitrige Bronchitis"],
        "indications_en": ["Spongy bleeding gums", "Painful oral aphthae", "Purulent bronchial catarrh"],
        "keynotes_de": ["Zahnfleisch weich, weicht von den Zähnen zurück und blutet leicht", "Geschwüre im Mund mit fauligem Geruch", "Reichlicher, eitriger, übelriechender Hustenauswurf"],
        "keynotes_en": ["Gums spongy, retracted, bleeding on slightest touch", "Foul aphthous ulcerations in oral cavity", "Copious purulent fetid expectoration from chest"],
        "better_de": ["Warme Mundspülungen"],
        "better_en": ["Warm mouth rinses"],
        "worse_de": ["Kauen", "Kälte"],
        "worse_en": ["Chewing", "Cold"],
        "diff": ["Mercurius", "Hydrastis", "Baptisia"],
        "sphere": ["Mundschleimhaut", "Zahnfleisch", "Bronchien"],
        "tier": 2
    },
    {
        "id": "myrtus-communis",
        "latin": "Myrtus communis",
        "cat": "plant",
        "de_name": "Gemeine Myrte",
        "en_name": "Myrtle",
        "es_name": "Mirto común",
        "fr_name": "Myrte commun",
        "it_name": "Mirto comune",
        "el_name": "Μυρτιά",
        "ru_name": "Мирт обыкновенный",
        "de_essence": "Boerickes spezifisches Schmerzsymptom: Stechender Schmerz in der linken Brustspitze unter dem Schlüsselbein, der direkt nach hinten zum linken Schulterblatt durchsticht.",
        "en_essence": "Boericke's hallmark key pain: stitch in upper left chest under clavicle, piercing straight through to left scapula, with dry hacking cough.",
        "indications_de": ["Stechender Schmerz linke Lungenspitze", "Schmerz strahlt zur linken Scapula", "Trockener Auszehrungshusten"],
        "indications_en": ["Stitch in left apex below clavicle", "Pain piercing straight through to scapula", "Incipient phthisis with dry cough"],
        "keynotes_de": ["Schmerz wie ein Nadelstich von der linken Schlüsselbeingrube geradewegs durch zur Schulterblattrückseite", "Trockener Reizhusten mit Blutfäden im Schleim", "Brennen in der linken Brustwarze"],
        "keynotes_en": ["Stitching pain from left infraclavicular region straight through to scapula", "Dry hacking cough with bloody streaks in sputum", "Burning sensation in left chest and nipple"],
        "better_de": ["Ruhiges flaches Liegen"],
        "better_en": ["Lying quietly flat"],
        "worse_de": ["Tiefes Einatmen", "Husten", "Bewegung"],
        "worse_en": ["Deep breathing", "Coughing", "Motion"],
        "diff": ["Pix liquida", "Theridion", "Anisum stellatum"],
        "sphere": ["Linke Lungenspitze", "Thoraxwand", "Scapula"],
        "tier": 1
    },
    {
        "id": "nasturtium-officinale",
        "latin": "Nasturtium officinale",
        "cat": "plant",
        "de_name": "Echte Brunnenkresse",
        "en_name": "Watercress",
        "es_name": "Berro de agua",
        "fr_name": "Cresson de fontaine",
        "it_name": "Crescione d'acqua",
        "el_name": "Κάρδαμο του νερού",
        "ru_name": "Жеруха обыкновенная",
        "de_essence": "Urolithiasis, Zystitis mit schmerzhafter Strangurie, Harnsäuregrieß, skorbutisches Zahnfleisch und Magenbrennen.",
        "en_essence": "Nephrolithiasis, painful catarrhal cystitis, uric acid sediment, scorbutic spongy gums, and gastric acidity.",
        "indications_de": ["Harnsteine & Nierengrieß", "Schmerzhafte Zystitis", "Skorbutische Zahnfleischentzündung"],
        "indications_en": ["Urinary calculi and gravel", "Painful catarrhal dysuria", "Scorbutic bleeding gums"],
        "keynotes_de": ["Krampfartiger Schneideschmerz in der Nierengegend strahlt zur Blase", "Urin trüb mit ziegelrotem Sediment", "Zahnfleisch blutet bei geringstem Druck"],
        "keynotes_en": ["Cutting colic in ureter radiating toward bladder", "Urine heavy with red brick-dust sediment", "Gums swollen, bleeding, scorbutic"],
        "better_de": ["Warmes Wassertrinken"],
        "better_en": ["Warm water"],
        "worse_de": ["Kälte", "Erschütterung"],
        "worse_en": ["Cold", "Jarring"],
        "diff": ["Berberis", "Sarsaparilla"],
        "sphere": ["Nieren", "Harnleiter", "Zahnfleisch"],
        "tier": 2
    },
    {
        "id": "nyctanthes-arbor-tristis",
        "latin": "Nyctanthes arbor-tristis",
        "cat": "plant",
        "de_name": "Trauriger Nachtjasmin",
        "en_name": "Night Jasmine / Parijat",
        "es_name": "Jazmín de la noche",
        "fr_name": "Arbre triste",
        "it_name": "Gelsomino notturno",
        "el_name": "Νυκτάνθης",
        "ru_name": "Никтантес",
        "de_essence": "Boerickes indisches Fieber- und Ischiasmittel: Biliöses Wechselfieber mit bitterem Erbrechen, Ischialgie, Gelenkschwellung und Obstipation.",
        "en_essence": "Boericke's celebrated Indian fever and sciatica remedy: bilious intermittent fever with bitter vomiting, sciatica, and chronic rheumatism.",
        "indications_de": ["Biliöses Wechselfieber", "Hartnäckige Ischialgie", "Bitteres Gallenerbrechen"],
        "indications_en": ["Bilious intermittent fever", "Obstinate sciatica", "Bitter bilious vomiting"],
        "keynotes_de": ["Fieberanfall mit unstillbarem Erbrechen von rein galliger Flüssigkeit", "Heftige ziehende Ischiasschmerzen entlang des Oberschenkels", "Verstopfung mit trockenem, hartem Stuhl"],
        "keynotes_en": ["Fever paroxysm accompanied by violent vomiting of pure bile", "Severe neuralgic sciatica worse at night and turning in bed", "Obstinate constipation with dry knotty stool"],
        "better_de": ["Warme Auflagen", "Ruhe"],
        "better_en": ["Warm applications", "Rest"],
        "worse_de": ["Nachts", "Bettwärme", "Kälte"],
        "worse_en": ["Night", "Warmth of bed", "Cold"],
        "diff": ["Eupatorium perfoliatum", "Colocynthis", "China"],
        "sphere": ["Nervus ischiadicus", "Leber", "Thermoregulation"],
        "tier": 1
    }
]
