#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Boericke Expansion Batch 6 (9 classic landmark remedies)
"""

BATCH6_REMEDIES = [
    {
        "id": "silphium-laciniatum",
        "latin": "Silphium laciniatum",
        "cat": "plant",
        "de_name": "Kompasspflanze",
        "en_name": "Compass Plant / Rosinweed",
        "es_name": "Planta brújula",
        "fr_name": "Silphion lacinié",
        "it_name": "Pianta bussola",
        "el_name": "Σίλφιον",
        "ru_name": "Сильфиум дольчатый",
        "de_essence": "Boerickes Katarrh- und Asthmamittel: Reichlicher schleimig-eitriger Auswurf, chronischer Husten der Phthisis, Lungenemphysem und Bronchiektasen.",
        "en_essence": "Boericke's catarrhal asthma remedy: profuse stringy mucous expectoration, chronic phthisical cough, pulmonary emphysema, and bronchiectasis.",
        "indications_de": ["Asthma mit reichlichem Schleim", "Chronische Bronchiektasen", "Emphysem mit Hustenreiz"],
        "indications_en": ["Catarrhal bronchial asthma", "Chronic bronchiectasis", "Emphysema with paroxysmal cough"],
        "keynotes_de": ["Auswurf enorm reichlich, gelb-grünlich, zäh und fadenförmig", "Atemnot mit Engegefühl im Sternum", "Rasselnde Geräusche in den Lungen bei Reizhusten"],
        "keynotes_en": ["Copious light-colored stringy mucous expectoration", "Dyspnea with constriction across mid-sternum", "Loose rattling in respiratory passages"],
        "better_de": ["Aufrechtes Sitzen", "Abhusten"],
        "better_en": ["Sitting upright", "Expectoration"],
        "worse_de": ["Flaches Liegen", "Zugluft"],
        "worse_en": ["Lying flat", "Drafts"],
        "diff": ["Senega", "Balsamum peruvianum", "Stannum"],
        "sphere": ["Bronchien", "Lungenparenchym"],
        "tier": 1
    },
    {
        "id": "spartium-scoparium",
        "latin": "Spartium scoparium (Cytisus scoparius)",
        "cat": "plant",
        "de_name": "Besenginster",
        "en_name": "Broom",
        "es_name": "Retama de escobas",
        "fr_name": "Genêt à balais",
        "it_name": "Ginestra dei carbonai",
        "el_name": "Σπάρτο",
        "ru_name": "Дрок красильный / Ракитник",
        "de_essence": "Boerickes Diuretikum und Kardiotonikum: Schwacher, unregelmäßiger Herzrhythmus, Myokarderschlaffung, kardiale Ödeme und Urinstauung.",
        "en_essence": "Boericke's celebrated cardiotonic and diuretic: feeble irregular pulse, myocardial relaxation, cardiac dropsy, and suppressed urination.",
        "indications_de": ["Kardiale Ödeme & Wassersucht", "Myokardschwäche & Arrhythmie", "Verminderte Harnausscheidung"],
        "indications_en": ["Cardiac dropsy and edema", "Myocardial debility / arrhythmia", "Suppressed urinary excretion"],
        "keynotes_de": ["Steigert die Kontraktionskraft des ermüdeten Myokards", "Fördert mächtig die Wasserausscheidung der Nieren", "Puls unregelmäßig, fadenförmig bei geringster Anstrengung"],
        "keynotes_en": ["Strengthens weak cardiac contractions and restores tone", "Acts as an energetic stimulating diuretic in general anasarca", "Pulse irregular, thready, slow or suddenly quickened"],
        "better_de": ["Ruhelage", "Reichliche Diurese"],
        "better_en": ["Resting", "Free diuresis"],
        "worse_de": ["Anstrengung", "Flachliegen"],
        "worse_en": ["Exertion", "Lying flat"],
        "diff": ["Digitalis", "Crataegus", "Strophanthus"],
        "sphere": ["Myokard", "Nieren", "Blutkreislauf"],
        "tier": 1
    },
    {
        "id": "abroma-augusta",
        "latin": "Abroma augusta",
        "cat": "plant",
        "de_name": "Königsfaser / Abroma",
        "en_name": "Devil's Cotton",
        "es_name": "Abroma",
        "fr_name": "Abrome",
        "it_name": "Abroma",
        "el_name": "Αβρώμα",
        "ru_name": "Аброма величественная",
        "de_essence": "Boerickes indisches Diabetesmittel: Diabetes mellitus mit extremer Abmagerung, brennendem Durst, Polyurie, Schlaflosigkeit und Dysmenorrhoe.",
        "en_essence": "Boericke's celebrated Indian diabetes specific: marked glycosuria, rapid emaciation, unquenchable thirst, polyuria, and dysmenorrhea.",
        "indications_de": ["Diabetes mellitus mit Abmagerung", "Unstillbarer Durst & Polyurie", "Krampfhafte Dysmenorrhoe"],
        "indications_en": ["Diabetes mellitus with emaciation", "Unquenchable thirst and polyuria", "Congestive dysmenorrhea"],
        "keynotes_de": ["Patient trinkt riesige Wassermengen und hat Heißhunger, magert dennoch ab", "Urin scheidet reichlich Zucker aus bei hohem spezifischem Gewicht", "Menses unregelmäßig, dunkel, mit krampfartigem Wehenschmerz"],
        "keynotes_en": ["Insatiable hunger and thirst yet continuous loss of flesh", "Urine loaded with sugar, high specific gravity", "Colicky labor-like dysmenorrhea with dark clotted flow"],
        "better_de": ["Nach dem Essen", "Wärme"],
        "better_en": ["After eating", "Warmth"],
        "worse_de": ["Fasten", "Kälte", "Anstrengung"],
        "worse_en": ["Fasting", "Cold", "Exertion"],
        "diff": ["Syzygium", "Cephalandra", "Uranium nitricum"],
        "sphere": ["Pankreas", "Glukosestoffwechsel", "Uterus"],
        "tier": 1
    },
    {
        "id": "ailanthus-glandulosa",
        "latin": "Ailanthus glandulosa",
        "cat": "plant",
        "de_name": "Götterbaum",
        "en_name": "Tree of Heaven",
        "es_name": "Árbol del cielo",
        "fr_name": "Ailante glanduleux",
        "it_name": "Albero del paradiso",
        "el_name": "Αείλανθος",
        "ru_name": "Айлант высочайший",
        "de_essence": "Boerickes Malignitäts- und Scharlachmittel: Bösartige Scharlachformen, stuporöse Benommenheit, dunkelrote, geschwollene Tonsillen und Petechien.",
        "en_essence": "Boericke's celebrated adynamic specific: malignant scarlatinal stupor, dusky swollen throat, ulcerated tonsils, and purplish eruptions.",
        "indications_de": ["Bösartiges Scharlachfieber", "Septische Tonsillitis mit Nekroseneigung", "Stuporöse Erschöpfungszustände"],
        "indications_en": ["Malignant scarlatina", "Septic dusky tonsillitis with ulceration", "Adynamic stupor in severe toxemia"],
        "keynotes_de": ["Gesicht dunkelrot, aufgedunsen, apathischer Stupor mit offenem Mund", "Rachen livide, dunkel geschwollen, schmerzhaftes Schlucken mit Foetor", "Ausschlag spärlich, bläulich-rot, kommt nicht recht heraus"],
        "keynotes_en": ["Dusky red bloated face with semi-conscious stupor", "Throat livid, dark red, swollen, tonsils ulcerated with foul odor", "Rash scanty, bluish, petechial, slow to develop"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting upright"],
        "worse_de": ["Aufrichten (Schwindel)", "Liegen"],
        "worse_en": ["Rising up (vertigo)", "Lying flat"],
        "diff": ["Baptisia", "Lachesis", "Rhus tox"],
        "sphere": ["Rachen", "Mandeln", "Blut", "Zentralnervensystem"],
        "tier": 1
    },
    {
        "id": "alchemilla-vulgaris",
        "latin": "Alchemilla vulgaris",
        "cat": "plant",
        "de_name": "Gewöhnlicher Frauenmantel",
        "en_name": "Lady's Mantle",
        "es_name": "Alquimila / Pie de león",
        "fr_name": "Alchémille commune",
        "it_name": "Erba stella / Ventaglina",
        "el_name": "Αλχεμίλλη",
        "ru_name": "Манжетка обыкновенная",
        "de_essence": "Boerickes Becken- und Uterusadstringens: Uteruserschlaffung, chronische Menorrhagie, schmerzhafter Fluor albus und Beckensenkungsgefühl.",
        "en_essence": "Boericke's pelvic tonic: uterine relaxation, passive menorrhagia, obstinate leucorrhea, and bearing-down dragging in hypogastrium.",
        "indications_de": ["Uteruserschlaffung & Senkungsgefühl", "Chronische Menorrhagie", "Hartnäckiger Fluor albus"],
        "indications_en": ["Uterine relaxation and prolapse feeling", "Passive chronic menorrhagia", "Obstinate catarrhal leucorrhea"],
        "keynotes_de": ["Gefühl, als ob die Beckenorgane nach unten herausfallen wollten", "Menses zu lang anhaltend, blass oder klumpig dunkel", "Wirksames pflanzliches Gewebetonikum für das weibliche Becken"],
        "keynotes_en": ["Constant dragging and bearing-down in lower pelvis", "Protracted passive menstrual flow causing exhaustion", "Tones relaxed pelvic ligaments and mucosal lining"],
        "better_de": ["Ruhe im Liegen", "Wärme"],
        "better_en": ["Resting recumbent", "Warmth"],
        "worse_de": ["Langes Stehen", "Heben schwerer Lasten"],
        "worse_en": ["Prolonged standing", "Heavy lifting"],
        "diff": ["Fraxinus americana", "Helonias", "Sepia"],
        "sphere": ["Uterus", "Beckenbänder", "Endometrium"],
        "tier": 1
    },
    {
        "id": "allium-sativum",
        "latin": "Allium sativum",
        "cat": "plant",
        "de_name": "Knoblauch",
        "en_name": "Garlic",
        "es_name": "Ajo",
        "fr_name": "Ail cultivé",
        "it_name": "Aglio comune",
        "el_name": "Σκόρδο",
        "ru_name": "Чеснок посевной",
        "de_essence": "Boerickes Fleischfresser-Mittel: Chronischer Bronchialkatarrh und Dyspepsie bei Fleischessern, zäher schleimiger Auswurf, Hüftschmerz und Meteorismus.",
        "en_essence": "Boericke's celebrated remedy for flesh-eaters: chronic bronchial catarrh, dyspepsia in meat-eaters, tough gelatinous expectoration, and hip pain.",
        "indications_de": ["Bronchialkatarrh bei Fleischessern", "Gastrointestinale Dyspepsie", "Hüft- und Beckenschmerz"],
        "indications_en": ["Bronchial catarrh in flesh-eaters", "Dyspepsia from meat diet", "Sacro-iliac and hip ache"],
        "keynotes_de": ["Boericke: 'Besonders geeignet für Personen, die viel Fleisch essen'", "Husten mit reichlichem, zähem, fadenförmigem Schleim, schwer zu lösen", "Bauchblähung und Druck im Magen kurz nach dem Essen"],
        "keynotes_en": ["Boericke: 'Adapted to flesh-eaters who eat more than they drink'", "Cough with copious tenacious gelatinous mucus, difficult to expectorate", "Enormous flatulent distention and stomach burning"],
        "better_de": ["Vorüberbeugen", "Aufrechtes Sitzen"],
        "better_en": ["Bending forward", "Sitting upright"],
        "worse_de": ["Fleischgenuss", "Kälte", "Nach dem Essen"],
        "worse_en": ["Eating meat", "Cold", "After meals"],
        "diff": ["Allium cepa", "Nux vomica", "Senega"],
        "sphere": ["Bronchialschleimhaut", "Magen-Darm-Trakt", "Blutdruck"],
        "tier": 1
    },
    {
        "id": "anthoxanthum-odoratum",
        "latin": "Anthoxanthum odoratum",
        "cat": "plant",
        "de_name": "Gewöhnliches Ruchgras",
        "en_name": "Sweet Vernal Grass",
        "es_name": "Gramínea olorosa",
        "fr_name": "Flouve odorante",
        "it_name": "Paleo odoroso",
        "el_name": "Ανθοξάνθιον",
        "ru_name": "Душистый колосок обыкновенный",
        "de_essence": "Boerickes Heuschnupfen-Spezifikum: Akuter saisonaler Heuschnupfen, Nieskrämpfe, brennender Tränenfluss, Gaumenkitzeln und Heuasthma.",
        "en_essence": "Boericke's celebrated hay fever specific: acute seasonal pollinosis, violent sneezing paroxysms, burning tears, itching palate, and hay asthma.",
        "indications_de": ["Saisonaler Heuschnupfen (Pollinosis)", "Krampfartiges Dauerniesen", "Heuasthma mit Brustenge"],
        "indications_en": ["Seasonal hay fever / pollinosis", "Incessant paroxysmal sneezing", "Hay asthma with chest tightness"],
        "keynotes_de": ["Unaufhörliche Niesanfälle, sobald der Patient mit Heu oder Gras in Berührung kommt", "Brennender, scharfer Ausfluss aus Nase und Augen", "Kitzeln im weichen Gaumen und in der Luftröhre"],
        "keynotes_en": ["Incessant paroxysmal sneezing triggered by grass pollen and freshly cut hay", "Acrid burning watery coryza excoriating upper lip", "Tickling in soft palate and posterior nares provoking suffocative cough"],
        "better_de": ["Geschlossene Räume", "Kühle Waschungen"],
        "better_en": ["Closed room", "Cool washing"],
        "worse_de": ["Frisch gemähtes Heu", "Gräserpollen", "Im Freien"],
        "worse_en": ["Fresh-cut hay", "Grass pollen", "Outdoors"],
        "diff": ["Sabadilla", "Arundo mauritanica", "Wyethia"],
        "sphere": ["Nasenschleimhaut", "Augen", "Gaumen", "Bronchien"],
        "tier": 1
    },
    {
        "id": "aquilegia-vulgaris",
        "latin": "Aquilegia vulgaris",
        "cat": "plant",
        "de_name": "Gemeine Akelei",
        "en_name": "Columbine",
        "es_name": "Aguileña",
        "fr_name": "Ancolie commune",
        "it_name": "Aquilegia comune",
        "el_name": "Ακουιλέγια",
        "ru_name": "Водосбор обыкновенный",
        "de_essence": "Boerickes Hysteriemittel: Clavus hystericus (nagelartiger Scheitelschmerz), krampfhafte Dysmenorrhoe bei jungen Mädchen und Globus hystericus.",
        "en_essence": "Boericke's hysterical cephalalgia remedy: clavus hystericus (sensation as of a nail driven into vertex), spasmodic dysmenorrhea, and globus.",
        "indications_de": ["Clavus hystericus (Scheitelschmerz)", "Krampfhafte Pubertäts-Dysmenorrhoe", "Globusgefühl & Hysterie"],
        "indications_en": ["Clavus hystericus (vertex nail pain)", "Spasmodic dysmenorrhea in girls", "Globus hystericus and weepiness"],
        "keynotes_de": ["Schmerz auf dem Scheitelpunkt, als ob ein spitzer Nagel hineingetrieben würde", "Menses verspätet, spärlich, begleitet von krampfartigen Bauchschmerzen", "Hysterisches Zusammenschnüren der Kehle beim Schlucken"],
        "keynotes_en": ["Fixed boring ache at vertex as if a sharp nail were driven into brain", "Delayed scanty menses with violent pelvic spasms in young girls", "Globus sensation rising from stomach into throat"],
        "better_de": ["Ruhiges Liegen in Stille"],
        "better_en": ["Quiet recumbency in dark"],
        "worse_de": ["Aufregung", "Lärm", "Licht", "Vor Menses"],
        "worse_en": ["Excitement", "Noise", "Light", "Before menses"],
        "diff": ["Ignatia", "Coffea", "Pulsatilla"],
        "sphere": ["Vertex (Scheitel)", "Uterus", "Nervensystem"],
        "tier": 1
    },
    {
        "id": "aralia-racemosa",
        "latin": "Aralia racemosa",
        "cat": "plant",
        "de_name": "Amerikanische Narde",
        "en_name": "American Spikenard",
        "es_name": "Nardo americano",
        "fr_name": "Aralie à grappes",
        "it_name": "Aralia a grappoli",
        "el_name": "Αραλία",
        "ru_name": "Аралия кистевидная",
        "de_essence": "Boerickes klassisches Asthmamittel um 23 Uhr: Trockener krampfhafter Husten sofort nach dem Hinlegen, pfeifende Atmung und Heuschnupfen.",
        "en_essence": "Boericke's celebrated 11 PM asthma remedy: dry spasmodic cough triggered immediately upon lying down, loud wheezing, and hay fever.",
        "indications_de": ["Asthmaanfälle um 23 Uhr", "Krampfhusten beim Hinlegen", "Saisonaler Heuschnupfen"],
        "indications_en": ["Asthma attacks at 11 PM", "Spasmodic cough on lying down", "Seasonal hay fever"],
        "keynotes_de": ["Boericke: 'Hustenanfall tritt regelmäßig um 23 Uhr auf nach erstem Schlaf'", "Patient muss sich sofort aufsetzen, sonst Erstickungsgefühl", "Wässrige, salzige, scharfe Nieskoryza"],
        "keynotes_en": ["Boericke: 'Dry spasmodic cough coming on about 11 PM after a short sleep'", "Must sit up immediately in bed to breathe", "Copious watery excoriating nasal discharge with frequent sneezing"],
        "better_de": ["Aufrechtes Sitzen im Bett"],
        "better_en": ["Sitting erect in bed"],
        "worse_de": ["Hinlegen", "Zugluft", "23 Uhr"],
        "worse_en": ["Lying down", "Drafts", "11 PM"],
        "diff": ["Sambucus", "Spongia", "Arsenicum album"],
        "sphere": ["Bronchien", "Larynx", "Nasenschleimhaut"],
        "tier": 1
    },
    {
        "id": "amygdalus-persica",
        "latin": "Amygdalus persica",
        "cat": "plant",
        "de_name": "Pfirsichbaum",
        "en_name": "Peach Tree",
        "es_name": "Melocotonero",
        "fr_name": "Pêcher",
        "it_name": "Pesco",
        "el_name": "Ροδακινιά",
        "ru_name": "Персик обыкновенный",
        "de_essence": "Boerickes Magenberuhigungsmittel: Hartnäckiges Erbrechen von Kindern, Magenreizung, morgendliche Übelkeit und Schluckauf.",
        "en_essence": "Boericke's gastric sedative: intractable vomiting in children, gastric irritation, morning nausea of pregnancy, and singultus.",
        "indications_de": ["Hartnäckiges Magenerbrechen", "Schwangerschaftserbrechen", "Gastrische Reizung & Singultus"],
        "indications_en": ["Intractable vomiting in children", "Morning sickness in pregnancy", "Gastric irritability and hiccups"],
        "keynotes_de": ["Magen toleriert weder Speisen noch Getränke, sofortiges Wiedererbrechen", "Zunge rot, papillär vergrößert, an den Rändern glänzend", "Wirkt prompt lindernd auf sensible gastrische Nervenfasern"],
        "keynotes_en": ["Stomach intolerant of food or water, prompt regurgitation", "Tongue elongated, pointed with red tipped edges", "Calms irritated gastric mucosal filaments"],
        "better_de": ["Kühles kohlensäurehaltiges Wasser"],
        "better_en": ["Sips of cold water"],
        "worse_de": ["Nahrungsaufnahme", "Morgens"],
        "worse_en": ["Ingestion of food", "Morning"],
        "diff": ["Ipecacuanha", "Bismuthum", "Symphoricarpus"],
        "sphere": ["Magen-Vagusnerv", "Pylorus"],
        "tier": 1
    },
    {
        "id": "arbutus-unedo",
        "latin": "Arbutus unedo",
        "cat": "plant",
        "de_name": "Westlicher Erdbeerbaum",
        "en_name": "Strawberry Tree",
        "es_name": "Madroño",
        "fr_name": "Arbousier",
        "it_name": "Corbezzolo",
        "el_name": "Κουμαριά",
        "ru_name": "Земляничное дерево обыкновенное",
        "de_essence": "Boerickes Gicht- und Rheumamittel: Schmerzhafte Gichtarthritis mit tiefsitzendem Kreuzschmerz, Harnsäureablagerungen und Bläschenausschlägen.",
        "en_essence": "Boericke's gouty arthritis remedy: inflammatory arthritic pains, lumbago, uric acid gravel, and vesicular erythema.",
        "indications_de": ["Gichtige Arthritis & Gelenkschmerz", "Chronische Lumbalgie", "Erythematöse Hauteruptionen"],
        "indications_en": ["Gouty arthritis and joint ache", "Chronic lumbago and backache", "Vesicular erythema with itching"],
        "keynotes_de": ["Brennende stechende Schmerzen in den kleinen Finger- und Zehengelenken", "Urin stark sauer mit reichlich rotem Ziegelsediment", "Lumbago verschlimmert sich durch langes Sitzen"],
        "keynotes_en": ["Sharp burning pains in smaller joints of hands and feet", "Urine acid with heavy brick-dust sediment", "Lumbosacral ache exacerbated by prolonged sitting"],
        "better_de": ["Wärme", "Leichte Bewegung"],
        "better_en": ["Warmth", "Gentle motion"],
        "worse_de": ["Kälte", "Ruhe", "Feuchtes Wetter"],
        "worse_en": ["Cold", "Rest", "Damp weather"],
        "diff": ["Urtica urens", "Colchicum", "Ledum"],
        "sphere": ["Gelenke", "Nieren / Harnsäure", "Lendenwirbelsäule"],
        "tier": 1
    },
    {
        "id": "alnus-serrulata",
        "latin": "Alnus serrulata",
        "cat": "plant",
        "de_name": "Glattblättrige Erle",
        "en_name": "Tag Alder",
        "es_name": "Aliso americano",
        "fr_name": "Aulne serrulé",
        "it_name": "Ontano d'America",
        "el_name": "Σκληθροειδές",
        "ru_name": "Ольха мелкопильчатая",
        "de_essence": "Boerickes Skrofulose- und Drüsenmittel: Chronische Lymphdrüsenschwellungen, nässende Ekzeme, chronische Hämaturie und Rektumblutungen.",
        "en_essence": "Boericke's scrofulous glandular alterative: chronic lymphadenitis, weeping impetigo, passive hematuria, and rectal hemorrhage.",
        "indications_de": ["Skrofulöse Drüsenschwellung", "Chronisches nässendes Ekzem", "Schmerzlose Hämaturie"],
        "indications_en": ["Scrofulous lymphadenitis", "Chronic impetiginous eczema", "Passive painless hematuria"],
        "keynotes_de": ["Hals- und Mesenterialdrüsen vergrößert, derb und schmerzlos", "Ekzemkrusten hinter den Ohren und im Gesicht mit Schuppung", "Reguliert die Hämatopoese und fördert den Lymphabfluss"],
        "keynotes_en": ["Enlarged indolent cervical and mesenteric glands", "Weeping crusty eruptions behind ears and scalp", "Acts on glandular tissue and venous passive congestion"],
        "better_de": ["Trockene frische Luft"],
        "better_en": ["Dry fresh air"],
        "worse_de": ["Nässe", "Frühjahr"],
        "worse_en": ["Dampness", "Springtime"],
        "diff": ["Cistus canadensis", "Scrophularia", "Juglans"],
        "sphere": ["Lymphknoten", "Haut", "Venen"],
        "tier": 1
    },
    {
        "id": "ampelopsis-quinquefolia",
        "latin": "Ampelopsis quinquefolia (Parthenocissus)",
        "cat": "plant",
        "de_name": "Fünfblättriger Wilder Wein",
        "en_name": "Virginia Creeper",
        "es_name": "Enredadera de Virginia",
        "fr_name": "Vigne vierge vraie",
        "it_name": "Vite del Canada",
        "el_name": "Παρθενοκισσός",
        "ru_name": "Виноград девичий пятилисточковый",
        "de_essence": "Boerickes Nierenödem- und Heiserkeitsmittel: Renale Wassersucht nach Infekten, chronische Laryngitis mit morgendlicher Heiserkeit und Dilatation des Herzens.",
        "en_essence": "Boericke's renal dropsy and chronic hoarseness remedy: post-infectious anasarca, chronic laryngitis with early morning aphonia, and cardiac dilation.",
        "indications_de": ["Renale Wassersucht & Ödeme", "Chronische morgendliche Laryngitis", "Herzhypertrophie mit Dyspnoe"],
        "indications_en": ["Renal dropsy and anasarca", "Chronic morning laryngeal hoarseness", "Cardiac dilation with dyspnea"],
        "keynotes_de": ["Schwellung der Unterlider und Knöchel mit vermindertem Urin", "Völlige Stimmlosigkeit morgens, spricht nur im Flüsterton", "Engegefühl in der Herzgegend mit Pulsunregelmäßigkeit"],
        "keynotes_en": ["Puffiness of lower eyelids and extremities with albuminous urine", "Chronic laryngeal irritation with aphonia on waking", "Cardiac palpitations on exertion with pulse fluttering"],
        "better_de": ["Wärme", "Leichtes Aufrichten"],
        "better_en": ["Warmth", "Elevating head"],
        "worse_de": ["Morgens", "Kälte", "Körperliche Überanstrengung"],
        "worse_en": ["Morning", "Cold", "Physical exertion"],
        "diff": ["Apocynum", "Digitalis", "Senega"],
        "sphere": ["Nieren", "Larynx", "Herzmuskel"],
        "tier": 1
    },
    {
        "id": "abelmoschus",
        "latin": "Abelmoschus (Hibiscus abelmoschus)",
        "cat": "plant",
        "de_name": "Bisamstrauch",
        "en_name": "Musk Mallow",
        "es_name": "Abelmosco",
        "fr_name": "Ambrette / Gombo musqué",
        "it_name": "Abelmosco",
        "el_name": "Αβελμόσχος",
        "ru_name": "Абельмош мускусный",
        "de_essence": "Boerickes Angst- und Zwangsmittel: Wahnhafte Angst vor Tieren und Insekten, Herzklopfen, Schluckkrämpfe und nervöses Zittern.",
        "en_essence": "Boericke's fear and tremor remedy: morbid dread of venomous animals, cardiac neurosis, dysphagia, and muscular tremors.",
        "indications_de": ["Wahnhafte Tierphobie", "Kardiale Neurose mit Palpitationen", "Spastischer Ösophagus"],
        "indications_en": ["Morbid zoophobia", "Cardiac neurosis with palpitations", "Esophageal spasms"],
        "keynotes_de": ["Patient hat ständige Angst, von giftigen Tieren gebissen oder gestochen zu werden", "Kloßgefühl im Schlund mit plötzlicher Erstickungsangst", "Zittern der Hände bei geringster Gemütserregung"],
        "keynotes_en": ["Obsessive fear of snakes and poisonous spiders or insects", "Spasmodic constriction of throat preventing swallowing", "Muscular trembling from emotional excitement"],
        "better_de": ["Ruhe im Freien"],
        "better_en": ["Rest in open air"],
        "worse_de": ["Dunkelheit", "Alleinsein"],
        "worse_en": ["Darkness", "Being alone"],
        "diff": ["Moschus", "Stramonium", "Lachesis"],
        "sphere": ["Nervensystem", "Ösophagus", "Herz"],
        "tier": 1
    },
    {
        "id": "aconitum-lycoctonum",
        "latin": "Aconitum lycoctonum",
        "cat": "plant",
        "de_name": "Gelber Eisenhut / Wolfs-Eisenhut",
        "en_name": "Great Yellow Wolfsbane",
        "es_name": "Acónito matalobos",
        "fr_name": "Tue-loup jaune",
        "it_name": "Aconito licoctono",
        "el_name": "Ακόνιτο το λυκοκτόνο",
        "ru_name": "Борец северный (волчий)",
        "de_essence": "Boerickes Drüsenschwellungsmittel: Chronische Schwellung der Hals- und Achseldrüsen, Hodenschmerz, Juckreiz am Anus und Zungenbrennen.",
        "en_essence": "Boericke's glandular specific: chronic induration of cervical and axillary lymph nodes, orchitis, intense anal pruritus, and burning tip of tongue.",
        "indications_de": ["Chronische Lymphadenitis", "Hodenschwellung & Orchitis", "Hartnäckiger Pruritus ani"],
        "indications_en": ["Chronic lymphadenitis", "Indurated orchitis", "Intolerable pruritus ani"],
        "keynotes_de": ["Drüsen wie Schrotkugeln geschwollen, derb und schmerzhaft", "Brennen und Stechen an der Zungenspitze wie von Nadeln", "Harnblase gereizt mit häufigem Miktionsdrang"],
        "keynotes_en": ["Hard indurated lymphatic glands resembling shot under skin", "Piercing stinging on tip of tongue as from hot needles", "Vesical tenesmus with scalding urine"],
        "better_de": ["Mäßige Wärme"],
        "better_en": ["Moderate warmth"],
        "worse_de": ["Kälte", "Berührung"],
        "worse_en": ["Cold", "Touch"],
        "diff": ["Aconitum napellus", "Clematis", "Phytolacca"],
        "sphere": ["Lymphdrüsen", "Männliche Genitalien", "Zunge"],
        "tier": 1
    },
    {
        "id": "adlumia-fungosa",
        "latin": "Adlumia fungosa",
        "cat": "plant",
        "de_name": "Kletternder Erdrauch / Schwammwicke",
        "en_name": "Climbing Fumitory",
        "es_name": "Fumaria trepadora",
        "fr_name": "Adlumie fongueuse",
        "it_name": "Adlumia fungosa",
        "el_name": "Αδλουμία",
        "ru_name": "Адлумия губчатая",
        "de_essence": "Boerickes Leber- und Milzmittel: Chronische Vergrößerung und Schwere von Leber und Milz, Ikterus, dumpfer Kopfschmerz und Schläfrigkeit.",
        "en_essence": "Boericke's hepatic and splenic remedy: chronic hypertrophy of liver and spleen, jaundice, dull occipital ache, and languor.",
        "indications_de": ["Hepatomegalie & Splenomegalie", "Chronischer milder Ikterus", "Schweregefühl im Abdomen"],
        "indications_en": ["Hepatosplenomegaly", "Subacute catarrhal jaundice", "Fullness in hypochondria"],
        "keynotes_de": ["Dumpfer, bohrender Druck im rechten Oberbauch", "Stuhl hell, gallenarm mit Blähungsauftreibung", "Konstante Müdigkeit und Schwere der Augenlider"],
        "keynotes_en": ["Aching soreness across right and left hypochondria", "Clay-colored pale stool with bitter morning taste", "Overwhelming drowsiness after noon"],
        "better_de": ["Frische Luft", "Aufrechtes Gehen"],
        "better_en": ["Open air", "Walking erect"],
        "worse_de": ["Nach dem Essen", "Liegen auf der rechten Seite"],
        "worse_en": ["After meals", "Lying on right side"],
        "diff": ["Ceanothus", "Carduus marianus", "Chelidonium"],
        "sphere": ["Leber", "Milz", "Pfortader"],
        "tier": 1
    },
    {
        "id": "agrostemma-githago",
        "latin": "Agrostemma githago (Lychnis)",
        "cat": "plant",
        "de_name": "Kornrade",
        "en_name": "Corn Cockle",
        "es_name": "Neguilla",
        "fr_name": "Nielle des blés",
        "it_name": "Gittaione comune",
        "el_name": "Αγρόστεμμα",
        "ru_name": "Куколь обыкновенный",
        "de_essence": "Boerickes Schleimhaut- und Paralyse-Mittel: Schwindel, gastrische Brennschmerzen, Speichelfluss, Lähmigkeitsgefühl in Beinen und Zungentaubheit.",
        "en_essence": "Boericke's mucosal and paretic remedy: vertigo, intense burning gastralgia, profuse salivation, leg weakness, and numbness of tongue.",
        "indications_de": ["Brennende Gastralgie", "Akute Schleimhautreizung", "Lokale Paresen & Gangunsicherheit"],
        "indications_en": ["Burning gastralgia", "Acute mucosal catarrh", "Paretic leg weakness"],
        "keynotes_de": ["Brennen von Schlund bis Magen mit unstillbarem Erbrechen", "Taubheitsgefühl der Zunge und Schlucklähmung", "Muskelschwäche der Beine mit Stolpern beim Gehen"],
        "keynotes_en": ["Intense scalding heat from pharynx through stomach", "Numbness and loss of mobility in tongue", "Motor debility and paretic weakness of lower limbs"],
        "better_de": ["Ruhelage im Bett"],
        "better_en": ["Quiet rest in bed"],
        "worse_de": ["Gehen", "Nahrungsaufnahme"],
        "worse_en": ["Walking", "Eating"],
        "diff": ["Conium", "Gelsemium", "Arsenicum"],
        "sphere": ["Magenschleimhaut", "Periphere Motorik", "Zunge"],
        "tier": 1
    }
]
