#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Boericke Expansion Batch 5 (remedies P to Z)
"""

BATCH5_REMEDIES = [
    {
        "id": "oenothera-biennis",
        "latin": "Oenothera biennis",
        "cat": "plant",
        "de_name": "Gemeine Nachtkerze",
        "en_name": "Evening Primrose",
        "es_name": "Hierba del asno",
        "fr_name": "Onagre bisannuelle",
        "it_name": "Enotera",
        "el_name": "Οινοθήρα",
        "ru_name": "Энотера двулетняя",
        "de_essence": "Boerickes Diorrhoemittel bei Säuglingen: Sommerdurchfall, postfebrile Diarrhoe und hydrozephalusähnliche Schwäche nach Darminfektion.",
        "en_essence": "Boericke's infantile diarrhea specific: summer cholera infantum, exhausted languor, and hydrocephaloid states following bowel exhaustion.",
        "indications_de": ["Säuglings-Sommerdiarrhoe", "Postenteritische Erschöpfung", "Chronische Darmkatarrhe"],
        "indications_en": ["Infantile summer diarrhea", "Post-enteritis prostration", "Chronic catarrhal enteritis"],
        "keynotes_de": ["Wässrige, reichliche Entleerungen ohne Geruch", "Extremes Erschöpfungsgefühl nach dem Stuhl", "Kind liegt apathisch mit halb offenen Augen"],
        "keynotes_en": ["Exhausting watery painless evacuations", "Profound languor and limpness following stool", "Infant lies stuporous with half-closed eyes"],
        "better_de": ["Ruhe im Liegen"],
        "better_en": ["Quiet recumbency"],
        "worse_de": ["Sommerhitze", "Nach dem Stuhl"],
        "worse_en": ["Summer heat", "After stool"],
        "diff": ["Aethusa", "Chamomilla", "Cinchona"],
        "sphere": ["Dünndarm", "Säuglingsstoffwechsel"],
        "tier": 2
    },
    {
        "id": "olea-europaea",
        "latin": "Olea europaea",
        "cat": "plant",
        "de_name": "Ölbaum / Olivenbaum",
        "en_name": "Olive Tree",
        "es_name": "Olivo",
        "fr_name": "Olivier",
        "it_name": "Olivo",
        "el_name": "Ελιά",
        "ru_name": "Олива европейская",
        "de_essence": "Arterielle Hypertonie, zerebrale Durchblutungsnot mit Schwindel und arteriosklerotischer Kopfschmerz.",
        "en_essence": "Arterial hypertension, cerebral circulatory insufficiency with dizzy heaviness, and arteriosclerotic tension.",
        "indications_de": ["Arterielle Hypertonie", "Arteriosklerotischer Schwindel", "Vaskuläre Cephalgie"],
        "indications_en": ["Essential hypertension", "Arteriosclerotic vertigo", "Vascular tension headache"],
        "keynotes_de": ["Hoher Blutdruck mit rotem Kopf und Schläfendruck", "Dauerschwindel bei älteren Patienten", "Senkt den vaskulären Widerstand"],
        "keynotes_en": ["Elevated blood pressure with flushing and temporal tension", "Chronic vertigo in elderly sclerotic patients", "Reduces vascular resistance"],
        "better_de": ["Kühle Luft", "Ruhe"],
        "better_en": ["Cool air", "Rest"],
        "worse_de": ["Wärme", "Bücken", "Aufregung"],
        "worse_en": ["Warmth", "Stooping", "Excitement"],
        "diff": ["Viscum album", "Baryta carbonica", "Crataegus"],
        "sphere": ["Arterien", "Gehirndurchblutung"],
        "tier": 2
    },
    {
        "id": "origanum-majorana",
        "latin": "Origanum majorana",
        "cat": "plant",
        "de_name": "Echter Majoran",
        "en_name": "Sweet Marjoram",
        "es_name": "Mejorana",
        "fr_name": "Marjolaine",
        "it_name": "Maggiorana",
        "el_name": "Μαντζουράνα",
        "ru_name": "Майоран садовый",
        "de_essence": "Boerickes Nymphomanie- und Erotomaniemittel: Pathologisch gesteigerter Sexualtrieb, hysterische Brustschmerzen und Masturbationsdrang.",
        "en_essence": "Boericke's erotic excitement remedy: pathological sexual excitation, nymphomania, hysterical breast tenderness, and masturbatory impulse.",
        "indications_de": ["Erotomanie & Nymphomanie", "Hysterische Mamma-Hyperästhesie", "Sexuelle Neurose"],
        "indications_en": ["Erotomania and nymphomania", "Hyperesthetic breast pain", "Sexual nervous irritability"],
        "keynotes_de": ["Ständige erotische Impulse mit quälendem Schuldgefühl", "Brüste geschwollen und extrem berührungsempfindlich", "Hysterische Unruhe bessert durch harte körperliche Arbeit"],
        "keynotes_en": ["Uncontrollable erotic impulses and vivid sexual thoughts", "Breasts swollen, tender, cannot bear touch of dress", "Restlessness relieved only by heavy physical exertion"],
        "better_de": ["Schwere körperliche Arbeit"],
        "better_en": ["Heavy manual work"],
        "worse_de": ["Rußige Gedanken", "Alleinsein", "Bettwärme"],
        "worse_en": ["Idle solitude", "Warmth of bed"],
        "diff": ["Platina", "Cantharis", "Hyoscyamus"],
        "sphere": ["Sexualzentren", "Mammae", "Gemüt"],
        "tier": 2
    },
    {
        "id": "ornithogalum-umbellatum",
        "latin": "Ornithogalum umbellatum",
        "cat": "plant",
        "de_name": "Dolden-Milchstern",
        "en_name": "Star of Bethlehem",
        "es_name": "Leche de gallina",
        "fr_name": "Ornithogale en ombelle",
        "it_name": "Latte di gallina",
        "el_name": "Ορνιθόγαλον",
        "ru_name": "Птицемлечник зонтичный",
        "de_essence": "Boerickes Pylorus- und Magengeschwürmittel: Pylorusstenose, brennender Dauerschmerz im Magen mit saurem Erbrechen und gastrisches Karzinom.",
        "en_essence": "Boericke's celebrated gastric and pyloric specific: chronic ulceration of stomach, pyloric obstruction, persistent agony, and coffee-ground vomiting.",
        "indications_de": ["Ulcus ventriculi & Pylorospasmus", "Brennender Magen-Dauerschmerz", "Kaffeesatzerbrechen"],
        "indications_en": ["Gastric ulcer and pylorospasm", "Severe agonizing stomach pain", "Coffee-ground vomiting"],
        "keynotes_de": ["Schmerz strahlt vom Epigastrium durch die Brust zum Rücken", "Gefühl, als ob ein eiserner Pflock im Pylorus stecke", "Nahrung staut sich stundenlang im Magen"],
        "keynotes_en": ["Agonizing gastric pain radiating across chest to spine", "Sensation of hard knot or impaction at pylorus", "Food remains undigested, returned as sour coffee-grounds"],
        "better_de": ["Erbrechen", "Warmes Wasser"],
        "better_en": ["Emesis", "Warm drinks"],
        "worse_de": ["Feste Nahrung", "Nachts"],
        "worse_en": ["Solid food", "Night"],
        "diff": ["Condurango", "Hydrastis", "Arsenicum album"],
        "sphere": ["Magen", "Pylorus", "Speiseröhre"],
        "tier": 1
    },
    {
        "id": "orthosiphon-stamineus",
        "latin": "Orthosiphon stamineus",
        "cat": "plant",
        "de_name": "Katzenbart / Indischer Blasentee",
        "en_name": "Java Tea",
        "es_name": "Té de Java",
        "fr_name": "Moustaches de chat",
        "it_name": "Tè di Giava",
        "el_name": "Ορθοσίφων",
        "ru_name": "Ортосифон тычиночный",
        "de_essence": "Nephrolithiasis, Harnsäurediathese, chronische Zystitis und schmerzhafte Miktion mit Harngrieß.",
        "en_essence": "Nephrolithiasis, uric acid diathesis, chronic cystitis with sandy urine, and painful strangury.",
        "indications_de": ["Urat-Nephrolithiasis & Nierengrieß", "Chronische Zystitis", "Ödeme bei Nierenschwäche"],
        "indications_en": ["Uric acid stones / gravel", "Chronic vesical catarrh", "Renal edema"],
        "keynotes_de": ["Kräftige Ausscheidung von stickstoffhaltigen Schlacken und Sand", "Schmerzhafter Blasendrang mit brennendem Ausfluss", "Fördert die natürliche Nierenperfusion"],
        "keynotes_en": ["Promotes copious discharge of uric acid crystals and sand", "Aching dysuria with cloudy alkaline urine", "Powerful flushing diuretic in stone diathesis"],
        "better_de": ["Reichliches Wassertrinken"],
        "better_en": ["Drinking copious water"],
        "worse_de": ["Kälte", "Durststrecke"],
        "worse_en": ["Cold", "Fluid restriction"],
        "diff": ["Berberis", "Solidago", "Uva ursi"],
        "sphere": ["Nieren", "Blase", "Harnsäurestoffwechsel"],
        "tier": 2
    },
    {
        "id": "paullinia-cupana",
        "latin": "Paullinia cupana (Guarana)",
        "cat": "plant",
        "de_name": "Guaraná",
        "en_name": "Guarana",
        "es_name": "Guaraná",
        "fr_name": "Guarana",
        "it_name": "Guaranà",
        "el_name": "Γκουαρανά",
        "ru_name": "Гуарана",
        "de_essence": "Boerickes Migränemittel: Hemikranie nach geistiger Überarbeitung, Katerkopfschmerz nach Alkohol oder Tabak, Schläfenklopfen.",
        "en_essence": "Boericke's sick-headache remedy: hemicrania after mental exhaustion, throbbing hangover headache from alcohol or tobacco, and tinnitus.",
        "indications_de": ["Überarbeitungs-Hemikranie", "Katerkopfschmerz & Übelkeit", "Nervöse geistige Erschöpfung"],
        "indications_en": ["Hemicrania from mental strain", "Alcoholic hangover headache", "Intellectual fatigue"],
        "keynotes_de": ["Klopfen in den Schläfen mit Flimmern vor den Augen", "Kopfschmerz beginnt morgens beim Erwachen nach Nachtarbeit", "Bessert zuverlässig nach Ruhe und kühler Luft"],
        "keynotes_en": ["Throbbing in temples with visual flickers and nausea", "Headache awakens patient in morning after mental vigils", "Relieved promptly by cool air and quiet recumbency"],
        "better_de": ["Ruhe", "Kühle Luft"],
        "better_en": ["Rest", "Cool air"],
        "worse_de": ["Geistige Anstrengung", "Alkohol", "Lärm"],
        "worse_en": ["Mental effort", "Alcohol", "Noise"],
        "diff": ["Coffea", "Epiphegus", "Nux vomica"],
        "sphere": ["Zerebrale Arterien", "Schläfen", "Gehirn"],
        "tier": 1
    },
    {
        "id": "phaseolus-nanus",
        "latin": "Phaseolus nanus",
        "cat": "plant",
        "de_name": "Buschbohne",
        "en_name": "Dwarf Bean",
        "es_name": "Judía enana",
        "fr_name": "Haricot nain",
        "it_name": "Fagiolo nano",
        "el_name": "Φασίολος",
        "ru_name": "Фасоль обыкновенная (карликовая)",
        "de_essence": "Boerickes Herzmittel: Plötzliche Herzschwäche mit fadenförmigem, schnellem Puls, Angstgefühl in der Brust, Myokardschwäche und Diabetes.",
        "en_essence": "Boericke's celebrated heart remedy: sudden cardiac exhaustion with rapid thready pulse, precordial dread, dilatation, and glycosuria.",
        "indications_de": ["Akute Herzinsuffizienz & Myokardschwäche", "Präkordiale Beklemmung & Angst", "Diabetische Herzkrankheit"],
        "indications_en": ["Acute cardiac failure and dilatation", "Precordial anguish with weak pulse", "Diabetic heart complications"],
        "keynotes_de": ["Puls kaum tastbar, unregelmäßig, rasend schnell", "Gefühl, als ob das Herz aufhören würde zu schlagen", "Patient greift mit Todesangst an die Brust"],
        "keynotes_en": ["Pulse barely perceptible, rapid, thready, fluttering", "Terrifying feeling that heart will stop beating unless moving", "Sudden cardiac sinking with dropsy and sugar in urine"],
        "better_de": ["Völlige Bettruhe im Halbsitzen"],
        "better_en": ["Quiet rest semi-reclining"],
        "worse_de": ["Geringste Bewegung", "Aufrichten"],
        "worse_en": ["Slightest motion", "Straightening up"],
        "diff": ["Crataegus", "Digitalis", "Strophanthus"],
        "sphere": ["Myokard", "Reizleitungssystem", "Pankreas"],
        "tier": 1
    },
    {
        "id": "pichi-pichi",
        "latin": "Pichi-pichi (Fabiana imbricata)",
        "cat": "plant",
        "de_name": "Pichi-Pichi / Fabiana",
        "en_name": "Pichi",
        "es_name": "Pichi",
        "fr_name": "Pichi",
        "it_name": "Pichi",
        "el_name": "Πίτσι",
        "ru_name": "Пичи-пичи (Фабиана)",
        "de_essence": "Boerickes Urologikum: Schmerzhafter Blasenhalskrampf, Prostatahypertrophie mit Harndrang, Hämaturie bei Steinen und Urethritis.",
        "en_essence": "Boericke's renowned urological specific: agonizing vesical tenesmus, enlarged prostate with dysuria, uric acid gravel, and catarrhal urethritis.",
        "indications_de": ["Blasenhalsspasmus & Strangurie", "Prostatahypertrophie & Restharn", "Hämaturie bei Harnsteinen"],
        "indications_en": ["Prostatic dysuria and strangury", "Vesical tenesmus", "Hematuria from gravel"],
        "keynotes_de": ["Unerträgliches Brennen und Krampfen am Ende der Miktion", "Schwieriger Harnstart bei älteren Männern mit Prostatavergrößerung", "Urin voll gelblichem Schleim und feinem Grieß"],
        "keynotes_en": ["Agonizing cramping burning at conclusion of urination", "Difficult stammering urination in elderly prostatic sufferers", "Urine cloudy with pus, mucus, and sandy calculi"],
        "better_de": ["Heißes Sitzbad"],
        "better_en": ["Hot sitz-bath"],
        "worse_de": ["Verhalten des Harns", "Kälte"],
        "worse_en": ["Retaining urine", "Cold"],
        "diff": ["Pareira brava", "Chimaphila", "Sabal serrulata"],
        "sphere": ["Blasenhals", "Prostata", "Urethra"],
        "tier": 1
    },
    {
        "id": "piper-methysticum",
        "latin": "Piper methysticum (Kava-Kava)",
        "cat": "plant",
        "de_name": "Kava-Kava / Rauschpfeffer",
        "en_name": "Kava-Kava",
        "es_name": "Kava",
        "fr_name": "Kava-kava",
        "it_name": "Kava-kava",
        "el_name": "Κάβα-κάβα",
        "ru_name": "Кава-кава (перец опьяняющий)",
        "de_essence": "Boerickes Leitsymptom: Alle Schmerzen und Ängste werden völlig vergessen und bessern, sobald die Aufmerksamkeit abgelenkt wird; Neurasthenie.",
        "en_essence": "Boericke's hallmark keynote: all pains, neuralgias, and mental distress are completely forgotten and relieved by diverting the attention; soothing tonic.",
        "indications_de": ["Aufmerksamkeits-gebesserte Neuralgie", "Nervöse Angst & Unruhe", "Chronische Gonorrhoe & Zystitis"],
        "indications_en": ["Neuralgia relieved by diversion", "Anxiety and nervous exhaustion", "Subacute gonorrheal urethritis"],
        "keynotes_de": ["Patient leidet furchtbar, aber Schmerz verschwindet schlagartig bei angeregter Unterhaltung", "Tiefe geistige Ruhe und Entspannung ohne Narkose", "Schuppende Hautveränderungen mit starkem Juckreiz"],
        "keynotes_en": ["Pains completely vanish when mind is actively entertained or distracted", "Produces pleasant serene calm and muscular relaxation", "Scaly dry cutaneous eruptions with burning"],
        "better_de": ["Ablenkung der Aufmerksamkeit", "Unterhaltung"],
        "better_en": ["Diverting attention", "Entertaining company"],
        "worse_de": ["Alleinsein", "An die Schmerzen denken"],
        "worse_en": ["Solitude", "Thinking of symptoms"],
        "diff": ["Helonias", "Oxalicum acidum", "Gelsemium"],
        "sphere": ["Gemüt", "Zentralnervensystem", "Urethra", "Haut"],
        "tier": 1
    },
    {
        "id": "piscidia-erythrina",
        "latin": "Piscidia erythrina",
        "cat": "plant",
        "de_name": "Jamaika-Hundsbaum",
        "en_name": "Jamaica Dogwood",
        "es_name": "Piscidia",
        "fr_name": "Bois de poisson",
        "it_name": "Piscidia",
        "el_name": "Πισκίδια",
        "ru_name": "Писцидия",
        "de_essence": "Boerickes harmloses Analgetikum und Hypnotikum: Schlaflosigkeit durch unerträgliche Nervenschmerzen, Trigeminusneuralgie, Zahnschmerz und Menstruationskrampf.",
        "en_essence": "Boericke's celebrated herbal anodyne and hypnotic: relieves agonizing pain preventing sleep, facial neuralgia, toothache, and dysmenorrhea.",
        "indications_de": ["Schlaflosigkeit durch Nervenschmerz", "Heftige Trigeminusneuralgie", "Krampfhafte Dysmenorrhoe"],
        "indications_en": ["Insomnia from unbearable pain", "Facial trigeminal neuralgia", "Spasmodic dysmenorrhea"],
        "keynotes_de": ["Patient kann vor rasendem Schmerz im Gesicht kein Auge zutun", "Stillt Schmerzen verlässlich, ohne die Verdauung zu lähmen", "Entkrampft den Uterus bei wehenartigen Menstruationsschmerzen"],
        "keynotes_en": ["Quiets nervous system and induces restful sleep in severe pain", "Excellent substitute for opium without constipation or nausea", "Eases agonizing labor-like uterine cramping"],
        "better_de": ["Wärme", "Ruhiges Liegen"],
        "better_en": ["Warmth", "Quiet recumbency"],
        "worse_de": ["Kälte", "Berührung", "Nachts"],
        "worse_en": ["Cold", "Touch", "Night"],
        "diff": ["Passiflora", "Chamomilla", "Magnesia phosphorica"],
        "sphere": ["Sensible Nerven", "Schlaf", "Uterus"],
        "tier": 1
    },
    {
        "id": "populus-candicans",
        "latin": "Populus candicans",
        "cat": "plant",
        "de_name": "Balsampappel",
        "en_name": "Balm of Gilead",
        "es_name": "Álamo balsámico",
        "fr_name": "Peuplier baumier",
        "it_name": "Pioppo balsamico",
        "el_name": "Βαλσαμική λεύκη",
        "ru_name": "Тополь бальзамический",
        "de_essence": "Boerickes Stimmband- und Heiserkeitsmittel: Plötzlicher Stimmverlust (Aphonie) bei Rednern und Sängern, Kitzelhusten und brennender Kehlkopf.",
        "en_essence": "Boericke's vocal chord specific: acute loss of voice (aphonia) in public speakers and singers, dry throat burning, and tickling cough.",
        "indications_de": ["Akute Aphonie (Stimmverlust)", "Sänger- und Redner-Heiserkeit", "Trachealer Kitzelhusten"],
        "indications_en": ["Acute aphonia / voice loss", "Singer's laryngitis and hoarseness", "Dry tracheal hacking cough"],
        "keynotes_de": ["Stimme versagt plötzlich mitten in der Rede oder beim Gesang", "Brennen und Wundheitsgefühl tief im Kehlkopf", "Kitzelhusten mit zähem Schleim morgens"],
        "keynotes_en": ["Sudden total loss of voice after vocal overuse or cold air", "Sore raw burning sensation deep in larynx", "Irritating hacking cough from larynx with scanty tough mucus"],
        "better_de": ["Stimmschonung", "Warme Dämpfe"],
        "better_en": ["Vocal rest", "Warm steam"],
        "worse_de": ["Sprechen", "Singen", "Kaltes Einatmen"],
        "worse_en": ["Speaking", "Singing", "Inhaling cold air"],
        "diff": ["Causticum", "Argentum metallicum", "Arum triphyllum"],
        "sphere": ["Stimmbänder", "Larynx", "Trachea"],
        "tier": 1
    },
    {
        "id": "populus-tremuloides",
        "latin": "Populus tremuloides",
        "cat": "plant",
        "de_name": "Amerikanische Zitterpappel",
        "en_name": "American Aspen",
        "es_name": "Álamo temblón",
        "fr_name": "Peuplier faux-tremble",
        "it_name": "Pioppo tremulo americano",
        "el_name": "Τρέμουσα λεύκη",
        "ru_name": "Осина американская",
        "de_essence": "Boerickes Zystitis- und Miktionsmittel: Schmerzhafter Blasendrang nach Katheterisierung oder Operation, Schwangerschaftszystitis und Tenesmus.",
        "en_essence": "Boericke's classic vesical tenesmus remedy: severe scalding dysuria after catheterization or pelvic surgery, pregnancy cystitis, and mucus in urine.",
        "indications_de": ["Postoperative Zystitis & Katheterreiz", "Zystitis in der Schwangerschaft", "Schmerzhafter Harnblasen-Tenesmus"],
        "indications_en": ["Cystitis after catheterization", "Vesical distress in pregnancy", "Painful scalding urination"],
        "keynotes_de": ["Brennender, schneidender Schmerz hinter dem Schambein nach Urinieren", "Urin enthält zähen Schleim und Eiterfäden", "Häufiger quälender Harndrang mit geringem Abgang"],
        "keynotes_en": ["Severe burning and cramping behind pubes during and after micturition", "Catarrhal urine loaded with tenacious pus and mucus", "Urgent desire to urinate every few minutes with scanty flow"],
        "better_de": ["Wärme am Unterbauch"],
        "better_en": ["Warmth to hypogastrium"],
        "worse_de": ["Kälte", "Nach dem Wasserlassen"],
        "worse_en": ["Cold", "After urinating"],
        "diff": ["Cantharis", "Chimaphila", "Equisetum"],
        "sphere": ["Harnblase", "Blasenhals", "Urethra"],
        "tier": 1
    },
    {
        "id": "pothos-foetidus",
        "latin": "Pothos foetidus (Symplocarpus)",
        "cat": "plant",
        "de_name": "Stinkkohl",
        "en_name": "Skunk Cabbage",
        "es_name": "Col fétida",
        "fr_name": "Chou puant",
        "it_name": "Cavolo fétido",
        "el_name": "Βρωμολάχανο",
        "ru_name": "Симплокарпус вонючий",
        "de_essence": "Boerickes Leitsymptom beim Asthma: Asthmaanfall wird prompt gebessert oder beendet durch den Abgang von Stuhl; Stauballergie und Brustkrampf.",
        "en_essence": "Boericke's remarkable keynote in asthma: asthma paroxysm is immediately relieved by evacuation of bowels; dust allergy and chest constriction.",
        "indications_de": ["Asthma durch Stuhlgang gebessert", "Stauballergisches Asthma bronchiale", "Krampfhaftes Ersticken bei Inhalation"],
        "indications_en": ["Asthma ameliorated by stool", "Dust-induced bronchospasm", "Suffocative chest constriction"],
        "keynotes_de": ["Boericke: 'Asthmaanfall erleichtert durch Stuhlgang'", "Schlimmste Atemnot beim Einatmen von feinstem Staub", "Angst und Beklemmung in der Brust, Patient reißt die Kleider auf"],
        "keynotes_en": ["Boericke: 'Asthma is relieved by stool'", "Sudden violent dyspnea provoked by inhaling smallest dust particles", "Chest feels constricted, patient tears clothes from throat"],
        "better_de": ["Abgang von Stuhlgang", "Frische Luft"],
        "better_en": ["Evacuation of bowels", "Fresh air"],
        "worse_de": ["Einatmen von Staub", "Geringste Bewegung"],
        "worse_en": ["Inhaling dust", "Slight exertion"],
        "diff": ["Ipecacuanha", "Arsenicum album", "Blatta orientalis"],
        "sphere": ["Bronchialmuskulatur", "Darm-Lungen-Reflex", "Atmung"],
        "tier": 1
    },
    {
        "id": "primula-obconica",
        "latin": "Primula obconica",
        "cat": "plant",
        "de_name": "Becher-Primel",
        "en_name": "Poison Primrose",
        "es_name": "Prímula obcónica",
        "fr_name": "Primevère obconique",
        "it_name": "Primula obconica",
        "el_name": "Πρίμουλα",
        "ru_name": "Примула обратноконическая",
        "de_essence": "Boerickes Kontaktdermatitis-Mittel: Schrecklicher Juckreiz, erythematöse Bläscheneruptionen, feuchtes Ekzem und Schwellung von Gesicht und Händen.",
        "en_essence": "Boericke's premier contact dermatitis remedy: intolerable itching, papular erythema with blisters, wet eczema, and facial swelling.",
        "indications_de": ["Kontaktdermatitis & Primelallergie", "Unerträglicher Hautjuckreiz", "Feuchtes Bläschenekzem"],
        "indications_en": ["Contact dermatitis from plants", "Intolerable cutaneous itching", "Vesicular moist eczema"],
        "keynotes_de": ["Brennender Juckreiz treibt fast zum Wahnsinn, Kratzen bringt keine Erleichterung", "Ödematöse Schwellung von Lidern, Gesicht und Fingern", "Kleine Bläschen brechen auf und sondern scharfe Flüssigkeit ab"],
        "keynotes_en": ["Intense burning itching worse at night; rubbing aggravates", "Edematous swelling of face, eyelids, and hands", "Vesicles break down discharging clear sticky lymph"],
        "better_de": ["Feuchte Kälteumschläge"],
        "better_en": ["Cold wet compresses"],
        "worse_de": ["Berührung", "Wärme", "Kratzen", "Nachts"],
        "worse_en": ["Touch", "Warmth", "Scratching", "Night"],
        "diff": ["Rhus toxicodendron", "Anacardium", "Croton tiglium"],
        "sphere": ["Haut", "Subkutis", "Augenlider"],
        "tier": 1
    },
    {
        "id": "prunus-virginiana",
        "latin": "Prunus virginiana",
        "cat": "plant",
        "de_name": "Virginische Traubenkirsche",
        "en_name": "Wild Black Cherry",
        "es_name": "Cerezo de Virginia",
        "fr_name": "Cerisier de Virginie",
        "it_name": "Pruno della Virginia",
        "el_name": "Άγρια κερασιά",
        "ru_name": "Черемуха виргинская",
        "de_essence": "Boerickes Herz- und Hustenmittel: Unaufhörlicher, quälender Reizhusten bei Herzschwäche, kardiale Dyspnoe und atone Magenschwäche.",
        "en_essence": "Boericke's cardiac cough specific: persistent racking tickling cough in heart failure, cardiac dyspnea, and weak digestion.",
        "indications_de": ["Kardialer Reizhusten", "Herzklopfen bei Mitralinsuffizienz", "Schwäche der Verdauung"],
        "indications_en": ["Cardiac tickling cough", "Palpitation in mitral weakness", "Atonic gastrointestinal debility"],
        "keynotes_de": ["Husten bricht aus bei geringster Anstrengung oder beim Liegen", "Herztöne schwach, Puls unregelmäßig und wechselhaft", "Beruhigt den nervösen Hustenreflex und stärkt die Herzaktion"],
        "keynotes_en": ["Cough comes on when attempting to lie down or walk rapidly", "Feeble cardiac action with fluttering thready pulse", "Soothes irritated respiratory nerves and supports myocardium"],
        "better_de": ["Ruhe im Sitzen"],
        "better_en": ["Quiet sitting"],
        "worse_de": ["Flaches Liegen", "Treppensteigen"],
        "worse_en": ["Lying flat", "Climbing stairs"],
        "diff": ["Laurocerasus", "Crataegus", "Lycopus"],
        "sphere": ["Herz", "Atemnerven", "Magen"],
        "tier": 1
    },
    {
        "id": "ptelea-trifoliata",
        "latin": "Ptelea trifoliata",
        "cat": "plant",
        "de_name": "Dreiblättrige Hopfenbuche / Lederbaum",
        "en_name": "Wafer Ash / Hop Tree",
        "es_name": "Ptelea",
        "fr_name": "Orme de Samarie",
        "it_name": "Ptelea",
        "el_name": "Πτελέα",
        "ru_name": "Птелея трехлистная",
        "de_essence": "Boerickes Leitsymptom der Leber: Schweregefühl und schmerzhafter Zug in der Lebergegend, schlimmer beim Liegen auf der linken Seite; Gelbsucht.",
        "en_essence": "Boericke's celebrated liver keynote: heavy aching and dragging in right hypochondrium, worse lying on left side; jaundice and bitter taste.",
        "indications_de": ["Schmerzhafte Leberstauung", "Verschlimmerung beim Linksliegen", "Chronischer Ikterus mit Bittergeschmack"],
        "indications_en": ["Hepatic congestion and tenderness", "Aggravation from lying on left side", "Chronic jaundice with bitter tongue"],
        "keynotes_de": ["Beim Liegen auf der linken Seite zieht die schwere Leber schmerzhaft nach unten", "Zunge dick weißlich-gelb belegt, bitterer Geschmack im Mund", "Ständiges Gefühl von Magenleere und Völle zugleich"],
        "keynotes_en": ["Lying on left side produces intolerable dragging ache in liver", "Tongue coated thick yellowish-white with bitter taste", "Hepatic torpor with headache and aching limbs"],
        "better_de": ["Liegen auf der rechten (schmerzhaften) Seite"],
        "better_en": ["Lying on right (affected) side"],
        "worse_de": ["Liegen auf der linken Seite", "Morgens"],
        "worse_en": ["Lying on left side", "Morning"],
        "diff": ["Chelidonium", "Bryonia", "Carduus marianus"],
        "sphere": ["Leber", "Gallengänge", "Magen"],
        "tier": 1
    },
    {
        "id": "quassia-amara",
        "latin": "Quassia amara",
        "cat": "plant",
        "de_name": "Bitterholz / Quassia",
        "en_name": "Quassia Wood",
        "es_name": "Cuasia",
        "fr_name": "Quassie amère",
        "it_name": "Quassio",
        "el_name": "Κουάσσια",
        "ru_name": "Квассия горькая",
        "de_essence": "Boerickes Madenwurmmittel (Oxyuren): Quälender Afterjuckreiz bei Madenwürmern, Leberdyspepsie, Magenleere und Zirrhose mit Aszites.",
        "en_essence": "Boericke's specific for pinworms (oxyuris vermicularis): intense anal itching, liver dyspepsia, stomach emptiness, and cirrhotic ascites.",
        "indications_de": ["Madenwurmbefall (Oxyuriasis)", "Quälender analer Pruritus", "Chronische Leberzirrhose mit Aszites"],
        "indications_en": ["Pinworm / threadworm infestation", "Intolerable anal pruritus", "Cirrhosis with ascites"],
        "keynotes_de": ["Heftiger Afterjuckreiz nachts im Bett durch herumkriechende Würmer", "Magen fühlt sich flau und leer an; Verlangen nach bitteren Tonika", "Oberbauchdruck und dumpfer Schmerz im rechten Leberlappen"],
        "keynotes_en": ["Intolerable rectal itching at night from pinworms", "Empty faint feeling in stomach with heartburn and regurgitation", "Hepatic cirrhosis with abdominal dropsy and pale stools"],
        "better_de": ["Kühle Anwendungen am After"],
        "better_en": ["Cool rectal applications"],
        "worse_de": ["Bettwärme", "Nachts", "Nach dem Essen"],
        "worse_en": ["Warmth of bed", "Night", "After eating"],
        "diff": ["Cina", "Teucrium marum verum", "Santoninum"],
        "sphere": ["Rektum", "Darmparasiten", "Leber"],
        "tier": 1
    },
    {
        "id": "quercus-glandium-spiritus",
        "latin": "Quercus glandium spiritus",
        "cat": "plant",
        "de_name": "Eichelgeist",
        "en_name": "Spirit of Acorns",
        "es_name": "Espíritu de bellotas",
        "fr_name": "Esprit de glands de chêne",
        "it_name": "Spirito di ghiande",
        "el_name": "Απόσταγμα βελανιδιών",
        "ru_name": "Кверкус спиритус (спирт желудей)",
        "de_essence": "Boerickes Antidot gegen Alkoholismus: Unterdrückt das Verlangen nach Alkohol, kuriert alkoholische Milzvergrößerung, Aszites und Gicht.",
        "en_essence": "Boericke's celebrated antidote to chronic alcoholism: banishes the craving for spirits, cures alcoholic splenic enlargement, and ascites.",
        "indications_de": ["Chronischer Alkoholismus & Suchtdrang", "Alkoholische Splenomegalie", "Aszites & Leberfibrose"],
        "indications_en": ["Chronic alcoholism and craving", "Splenic hypertrophy from alcohol", "Ascites and portal hypertension"],
        "keynotes_de": ["Nimmt den unstillbaren Zwang nach Schnaps und Alkohol", "Schmerzhafte Schwellung und Härte der Milz", "Atem riecht faulig-alkoholisch, Gesicht teigig aufgedunsen"],
        "keynotes_en": ["Antidotes the craving for alcohol and relieves intoxicating effects", "Painful hypertrophy of spleen with left hypochondriac stitch", "Dropsy and breathlessness in old alcoholics"],
        "better_de": ["Ausruhen", "Alkoholabstinenz"],
        "better_en": ["Rest", "Total abstinence"],
        "worse_de": ["Alkoholgenuss", "Feuchtigkeit"],
        "worse_en": ["Drinking alcohol", "Dampness"],
        "diff": ["Nux vomica", "Capsicum", "Ceanothus"],
        "sphere": ["Milz", "Pfortader", "Alkoholsucht"],
        "tier": 1
    },
    {
        "id": "rhamnus-californica",
        "latin": "Rhamnus californica",
        "cat": "plant",
        "de_name": "Kalifornischer Kreuzdorn",
        "en_name": "California Coffee-Tree",
        "es_name": "Espino cerval de California",
        "fr_name": "Nerprun de Californie",
        "it_name": "Ranno di California",
        "el_name": "Ράμνος της Καλιφόρνιας",
        "ru_name": "Крушина калифорнийская",
        "de_essence": "Boerickes Rheumatismus- und Muskelschmerzmittel: Entzündlicher Gelenkrheumatismus, Myalgien, Gicht und schmerzhafte Gelenkschwellung.",
        "en_essence": "Boericke's specific for inflammatory muscular and articular rheumatism: acute arthritis, severe myalgias, gouty swellings, and lumbago.",
        "indications_de": ["Akuter Gelenkrheumatismus", "Heftige Myalgien & Muskelkater", "Gichtarthritis & Lumbago"],
        "indications_en": ["Acute articular rheumatism", "Severe muscular myalgias", "Gouty joint swellings and lumbago"],
        "keynotes_de": ["Reißende, bohrende Schmerzen in den großen Gelenken", "Gelenke rot, geschwollen und berührungsempfindlich", "Schmerzlinderung nach anhaltender leichter Bewegung"],
        "keynotes_en": ["Tearing, deep boring pains in joints and muscular bellies", "Joints swollen, red, hot, exquisitely sensitive", "Stiffness and aching ameliorated after gentle continuous movement"],
        "better_de": ["Sanfte fortgesetzte Bewegung", "Wärme"],
        "better_en": ["Gentle continuous motion", "Warmth"],
        "worse_de": ["Ruhebeginn", "Nasskaltes Wetter"],
        "worse_en": ["Beginning of motion", "Damp cold weather"],
        "diff": ["Rhus toxicodendron", "Bryonia", "Colchicum"],
        "sphere": ["Gelenke", "Skelettmuskulatur", "Sehnen"],
        "tier": 1
    },
    {
        "id": "rhus-aromatica",
        "latin": "Rhus aromatica",
        "cat": "plant",
        "de_name": "Duftender Sumach",
        "en_name": "Fragrant Sumach",
        "es_name": "Zumaque aromático",
        "fr_name": "Sumac aromatique",
        "it_name": "Sommacco aromatico",
        "el_name": "Αρωματικός σούμακ",
        "ru_name": "Сумах ароматный",
        "de_essence": "Boerickes Bettnässer- und Enuresismittel: Nächtliche Enuresis bei Kindern, atonische Dranginkontinenz alter Leute, Hämaturie und Polyurie.",
        "en_essence": "Boericke's premier enuresis specific: nocturnal enuresis in children, atonic urinary incontinence in the aged, hematuria, and diabetes insipidus.",
        "indications_de": ["Enuresis nocturna (Bettnässen)", "Senile Harninkontinenz", "Hämaturie & Polyurie"],
        "indications_en": ["Nocturnal enuresis in children", "Senile urinary incontinence", "Painless hematuria and diabetes"],
        "keynotes_de": ["Unwillkürlicher Harnabgang im Schlaf bei blassen, schwächlichen Kindern", "Ständiges Tröpfeln von Urin bei altersschwachem Blasenschließmuskel", "Reine, schmerzlose Blutbeimengung im Urin"],
        "keynotes_en": ["Involuntary micturition during sound sleep in children", "Continuous involuntary dribbling of urine in aged patients with atony", "Profuse pale urine with microhematuria or glycosuria"],
        "better_de": ["Wärme", "Trockenes Wetter"],
        "better_en": ["Warmth", "Dry weather"],
        "worse_de": ["Nachts im Schlaf", "Kälte und Nässe"],
        "worse_en": ["Night during sleep", "Cold and damp"],
        "diff": ["Equisetum", "Causticum", "Sepia"],
        "sphere": ["Blasenschließmuskel", "Harnblase", "Nieren"],
        "tier": 1
    },
    {
        "id": "sabal-serrulata",
        "latin": "Sabal serrulata (Serenoa repens)",
        "cat": "plant",
        "de_name": "Sägepalme",
        "en_name": "Saw Palmetto",
        "es_name": "Palmetto / Sabal",
        "fr_name": "Palmier nain",
        "it_name": "Sabal serrulata",
        "el_name": "Σαβάλ",
        "ru_name": "Сабаль мелкопильчатый",
        "de_essence": "Boerickes großes Prostatamittel: Gutartige Prostatahypertrophie (BPH), schmerzhaftes Urintröpfeln, Restharn, Blasenreizung und Schwinden der Brüste.",
        "en_essence": "Boericke's premier prostate specific: benign prostatic hyperplasia (BPH), constant urging with dribbling, retained urine, and mammary atrophy.",
        "indications_de": ["Benigne Prostatahyperplasie (BPH)", "Schmerzhaftes Urintröpfeln & Strangurie", "Mammaschwund & Ovarienatrophie"],
        "indications_en": ["Benign prostatic hypertrophy", "Urinary dribbling and hesitation", "Mammary atrophy and ovarian atony"],
        "keynotes_de": ["Vergrößerte, derbe Prostata mit ständigem, quälendem Harndrang nachts", "Harnstrahl schwach, geteilt oder bricht immer wieder ab", "Förderung der Drüsenregeneration bei verkümmerten Organen"],
        "keynotes_en": ["Enlarged tender prostate with frequent nocturnal calls to urinate", "Difficult, slow, dribbling urination with severe aching in bladder neck", "Boericke: 'The true homeopathic catheter'"],
        "better_de": ["Warmes Bad", "Aufrechtes Sitzen"],
        "better_en": ["Warm bath", "Upright sitting"],
        "worse_de": ["Nachts", "Kälte", "Langes Sitzen"],
        "worse_en": ["Night", "Cold", "Prolonged sitting"],
        "diff": ["Chimaphila", "Pareira brava", "Thuja"],
        "sphere": ["Prostata", "Blasenhals", "Mammae", "Genitalorgane"],
        "tier": 1
    },
    {
        "id": "salix-nigra",
        "latin": "Salix nigra",
        "cat": "plant",
        "de_name": "Schwarze Weide",
        "en_name": "Black Willow",
        "es_name": "Sauce negro",
        "fr_name": "Saule noir",
        "it_name": "Salice nero",
        "el_name": "Μαύρη ιτιά",
        "ru_name": "Ива черная",
        "de_essence": "Boerickes pflanzliches Sedativum bei sexueller Reizung: Hypersexualität, schmerzhafte nächtliche Pollutionen, Priapismus, Nymphomanie und Ovarialgie.",
        "en_essence": "Boericke's celebrated sexual sedative: excessive erotic excitability, painful nocturnal emissions, priapism, nymphomania, and ovarian neuralgia.",
        "indications_de": ["Hypersexualität & Erotomanie", "Schmerzhafte Pollutionen & Priapismus", "Reizung der Ovarien"],
        "indications_en": ["Sexual over-excitability", "Painful emissions / priapism", "Ovarian neuralgia and dysmenorrhea"],
        "keynotes_de": ["Ständige erotische Reizungen rauben den Schlaf und erschöpfen den Geist", "Dämpft zuverlässig übersteigertes sexuelles Verlangen", "Schmerzen in der Leistengegend strahlen in die Oberschenkel"],
        "keynotes_en": ["Excessive erotic excitability causing sleeplessness and nervous agitation", "Acts reliably to quiet morbid sexual passion and genital irritation", "Sore aching in ovarian region radiating into thighs"],
        "better_de": ["Ablenkung", "Kälte"],
        "better_en": ["Distraction", "Coolness"],
        "worse_de": ["Bettwärme", "Alleinsein", "Morgens"],
        "worse_en": ["Warmth of bed", "Solitude", "Morning"],
        "diff": ["Origanum", "Picricum acidum", "Agnus castus"],
        "sphere": ["Sexualnerven", "Ovarien", "Genitalreflexe"],
        "tier": 1
    },
    {
        "id": "salvia-officinalis",
        "latin": "Salvia officinalis",
        "cat": "plant",
        "de_name": "Echter Salbei",
        "en_name": "Common Sage",
        "es_name": "Salvia común",
        "fr_name": "Sauge officinale",
        "it_name": "Salvia comune",
        "el_name": "Φασκόμηλο",
        "ru_name": "Шалфей лекарственный",
        "de_essence": "Boerickes führendes Schweißhemmungsmittel: Schwächende Nachtschweiße bei Phthisis und Rekonvaleszenz, Galaktostase beim Abstillen und Pharyngitis.",
        "en_essence": "Boericke's premier anhidrotic: debilitating night sweats of tuberculosis and convalescence, suppresses lactation when weaning, and sore throat.",
        "indications_de": ["Schwächende Nachtschweiße", "Galaktostase beim Abstillen", "Subakute Pharyngitis & Heiserkeit"],
        "indications_en": ["Debilitating night sweats", "Arresting milk secretion in weaning", "Subacute pharyngitis and hoarseness"],
        "keynotes_de": ["Wäsche nachts klatschnass geschwitzt, Patient erwacht zerschlagen", "Trocknet übermäßigen Milchfluss sanft und zuverlässig ab", "Rachen rot, geschwollen, kitzlig mit Schleimbelegung"],
        "keynotes_en": ["Profuse drenching sweats at night leaving patient exhausted", "Arrests persistent excessive lactation safely and rapidly", "Tickling raw sensation in pharynx with mucous tickle"],
        "better_de": ["Kühle Luft", "Trockene Kleidung"],
        "better_en": ["Cool air", "Dry clothing"],
        "worse_de": ["Wärmestau", "Nachts im Bett"],
        "worse_en": ["Overheating", "Night in bed"],
        "diff": ["Silicea", "China", "Pilocarpus"],
        "sphere": ["Schweißdrüsen", "Mammae (Laktation)", "Rachen"],
        "tier": 1
    },
    {
        "id": "sarcolacticum-acidum",
        "latin": "Sarcolacticum acidum",
        "cat": "mineral",
        "de_name": "Fleischmilchsäure",
        "en_name": "Sarcolactic Acid",
        "es_name": "Ácido sarcoláctico",
        "fr_name": "Acide sarcolactique",
        "it_name": "Acido sarcolattico",
        "el_name": "Σαρκογαλακτικό οξύ",
        "ru_name": "Сарколактикум ацидум",
        "de_essence": "Boerickes Muskelerschöpfungsmittel: Extreme Muskelschwäche nach sportlicher Höchstleistung, Influenza oder Überlastung; Muskelkater und Wadenkrämpfe.",
        "en_essence": "Boericke's celebrated muscular prostration remedy: extreme muscular tiredness after athletic exertion, influenza, myalgia, and cramps.",
        "indications_de": ["Schwere Muskelerschöpfung & Myalgie", "Postvirale Schwäche (nach Grippe)", "Wadenkrämpfe & Gliederschwere"],
        "indications_en": ["Severe muscular exhaustion", "Post-influenzal prostration", "Calf cramps and heavy limbs"],
        "keynotes_de": ["Muskeln fühlen sich an wie mit Blei gefüllt und zerschlagen", "Treppensteigen fast unmöglich vor brennendem Muskelschmerz", "Erhöht die Ausdauer und beschleunigt den Laktatabbau"],
        "keynotes_en": ["Muscles feel leaden, stiff, bruised, and sore to touch", "Ascending stairs or raising arms is an agonizing effort", "Rapidly relieves lactic acid accumulation and fatigue"],
        "better_de": ["Flaches Ausruhen", "Wärme"],
        "better_en": ["Lying flat resting", "Warmth"],
        "worse_de": ["Körperliche Anstrengung", "Treppensteigen"],
        "worse_en": ["Physical exertion", "Climbing stairs"],
        "diff": ["Arnica", "Gelsemium", "Zincum metallicum"],
        "sphere": ["Skelettmuskulatur", "Muskelstoffwechsel", "Nerven"],
        "tier": 1
    },
    {
        "id": "scilla-maritima",
        "latin": "Scilla maritima (Squilla)",
        "cat": "plant",
        "de_name": "Meerzwiebel",
        "en_name": "Sea Onion",
        "es_name": "Escila marítima",
        "fr_name": "Scille maritime",
        "it_name": "Scilla marittima",
        "el_name": "Σκίλλα η ναυτική",
        "ru_name": "Морской лук",
        "de_essence": "Boerickes Leitsymptom beim Husten: Unwillkürlicher Harnabgang bei jedem Hustenstoß; rasselnder Bronchialhusten mit reichlichem Schleim und Herzödemen.",
        "en_essence": "Boericke's celebrated cough keynote: involuntary spurting of urine with every cough; loose rattling cough with profuse mucus, and cardiac dropsy.",
        "indications_de": ["Husten mit unwillkürlichem Harnverlust", "Lockerer Rasselhusten mit Schleim", "Kardiale Wassersucht"],
        "indications_en": ["Cough with involuntary urination", "Loose rattling cough with mucus", "Cardiac dropsy and dyspnea"],
        "keynotes_de": ["Urin spritzt bei jedem Hustenstoß unwillkürlich heraus", "Husten scheppert laut mit reichlichem, salzig schmeckendem Schleim", "Ödeme an den Knöcheln bei Herz- und Nierenschwäche"],
        "keynotes_en": ["Spurting of urine with sneezing or coughing", "Loose rattling cough with sweet or salty slimy expectoration", "Extensive dropsy of extremities from cardiac failure"],
        "better_de": ["Aufrechtes Sitzen", "Warme Getränke"],
        "better_en": ["Sitting upright", "Warm drinks"],
        "worse_de": ["Morgens", "Kälte", "Husten"],
        "worse_en": ["Morning", "Cold air", "Coughing"],
        "diff": ["Causticum", "Natrum muriaticum", "Antimonium tartaricum"],
        "sphere": ["Bronchien", "Blasenschließmuskel", "Myokard"],
        "tier": 1
    },
    {
        "id": "scrophularia-nodosa",
        "latin": "Scrophularia nodosa",
        "cat": "plant",
        "de_name": "Knotige Braunwurz",
        "en_name": "Figwort",
        "es_name": "Escrofularia",
        "fr_name": "Scrofulaire noueuse",
        "it_name": "Scrofularia nodosa",
        "el_name": "Σκροφουλάρια",
        "ru_name": "Норичник узловатый",
        "de_essence": "Boerickes Drüsen- und Mammamittel: Verhärtete Knoten in den Mammae (Fibroadenome), chronische Halslymphknotenschwellung, Ekzeme hinter den Ohren.",
        "en_essence": "Boericke's premier glandular specific: hard nodular breast tumors (fibroadenoma), chronic cervical lymphadenitis, and retro-auricular eczema.",
        "indications_de": ["Fibroadenome der Mammae", "Chronische Lymphknotenverhärtung", "Ekzeme hinter den Ohren"],
        "indications_en": ["Fibroadenoma of breasts", "Indurated scrofulous lymph glands", "Eczema behind ears"],
        "keynotes_de": ["Knoten in den Brüsten schmerzhaft bei Berührung, verhärtet vor Menses", "Kettenförmig vergrößerte Halsdrüsen", "Nässender, krustiger Ausschlag in den Falten hinter den Ohren"],
        "keynotes_en": ["Hard painful lumps in breast tissue worse before menses", "Chronic painless enlargement of cervical lymphatic chains", "Crusted, oozing eczema behind ears with deep fissures"],
        "better_de": ["Wärme", "Sanfter Schutz"],
        "better_en": ["Warmth", "Gentle protection"],
        "worse_de": ["Kälte", "Druck", "Vor der Menses"],
        "worse_en": ["Cold", "Pressure", "Before menses"],
        "diff": ["Asterias rubens", "Conium", "Cistus canadensis"],
        "sphere": ["Mammae", "Lymphdrüsen", "Hautfalten"],
        "tier": 1
    },
    {
        "id": "sedum-acre",
        "latin": "Sedum acre",
        "cat": "plant",
        "de_name": "Scharfer Mauerpfeffer",
        "en_name": "Biting Stonecrop",
        "es_name": "Pimienta de muros",
        "fr_name": "Poivre des murailles",
        "it_name": "Borracina acre",
        "el_name": "Σέδον το δριμύ",
        "ru_name": "Очиток едкий",
        "de_essence": "Boerickes Analfissuren- und Hämorrhoidenmittel: Schrecklicher schneidender Schmerz im Anus nach dem Stuhl, blutende Fissuren und rektale Krämpfe.",
        "en_essence": "Boericke's celebrated anal fissure specific: agonizing cutting and constrictive pain in anus after stool, bleeding fissures, and rectal spasms.",
        "indications_de": ["Schmerzhafte Analfissuren", "Brennende Hämorrhoiden", "Postdefäkatorischer Rektalspasmus"],
        "indications_en": ["Painful anal fissures", "Burning hemorrhoids", "Severe post-defecation rectal spasm"],
        "keynotes_de": ["Schmerz im After hält stundenlang nach der Stuhlentleerung an", "Anus krampft sich schmerzhaft zusammen; Fissur blutet leicht", "Patient fürchtet den nächsten Stuhlgang wegen der Schmerzen"],
        "keynotes_en": ["Severe cutting pain in anus persisting for hours after stool", "Anal sphincter tightly contracted and in painful spasm", "Bleeding fissures healed rapidly under its influence"],
        "better_de": ["Warmes Sitzbad"],
        "better_en": ["Warm sitz-bath"],
        "worse_de": ["Stuhlgang", "Sitzen", "Gehen"],
        "worse_en": ["Defecation", "Sitting", "Walking"],
        "diff": ["Ratanhia", "Nitricum acidum", "Paeonia"],
        "sphere": ["Anus", "Sphincter ani", "Rektalschleimhaut"],
        "tier": 1
    },
    {
        "id": "sempervivum-tectorum",
        "latin": "Sempervivum tectorum",
        "cat": "plant",
        "de_name": "Echte Hauswurz / Donnerbart",
        "en_name": "Houseleek",
        "es_name": "Siempreviva mayor",
        "fr_name": "Joubarbe des toits",
        "it_name": "Semprevivo maggiore",
        "el_name": "Αείζωον",
        "ru_name": "Молодило кровельное",
        "de_essence": "Boerickes Zungen- und Mundgeschwürmittel: Bösartige Zungengeschwüre, Aphthen, schmerzhafte Rhagaden der Brustwarzen, Verbrennungen und Warzen.",
        "en_essence": "Boericke's specific for indurated tongue ulcers: aphthae, bleeding raghades of nipples, superficial burns, and jagged warts.",
        "indications_de": ["Ulzerationen & Rhagaden der Zunge", "Schmerzhafte Brustwarzenrhagaden", "Aphthen & Verbrennungen"],
        "indications_en": ["Indurated ulcer of tongue", "Fissured bleeding nipples", "Mouth aphthae and burns"],
        "keynotes_de": ["Knotiges Geschwür am Zungenrand mit stechendem Schmerz", "Brustwarzen rissig und wund beim Stillen", "Heilt hartnäckige Schleimhautläsionen und Warzen"],
        "keynotes_en": ["Indurated sore on border of tongue with stabbing pain", "Nipples cracked, bleeding, ulcerated in nursing mothers", "Promotes healing of indolent ulcers and excrescences"],
        "better_de": ["Kühle Anwendungen"],
        "better_en": ["Cool applications"],
        "worse_de": ["Säurehaltige Speisen", "Berührung"],
        "worse_en": ["Acid foods", "Touch"],
        "diff": ["Galium aparine", "Nitricum acidum", "Hydrastis"],
        "sphere": ["Zunge", "Mundhöhle", "Brustwarzen", "Haut"],
        "tier": 1
    }
]
