# scripts/build_classical_database.py
import sys
import os

sys.path.insert(0, os.path.abspath("."))

import re
import json

from scripts.full_remedy_roster import ROSTER
from scripts.full_remedy_roster_part2 import ROSTER_PART2
from scripts.full_remedy_roster_part3 import ROSTER_PART3

ALL_NEW_REMEDIES = ROSTER + ROSTER_PART2 + ROSTER_PART3
print(f"Total new classical remedies to generate: {len(ALL_NEW_REMEDIES)}")

CATEGORY_MAP = {
    "plant": {
        "de": "Pflanzlich", "en": "Plant", "es": "Vegetal", "fr": "Végétal",
        "it": "Vegetale", "el": "Φυτικό", "ru": "Растительное"
    },
    "mineral": {
        "de": "Mineralisch", "en": "Mineral", "es": "Mineral", "fr": "Minéral",
        "it": "Minerale", "el": "Ορυκτό", "ru": "Минеральное"
    },
    "animal": {
        "de": "Tierisch", "en": "Animal", "es": "Animal", "fr": "Animal",
        "it": "Animale", "el": "Ζωικό", "ru": "Животное"
    },
    "nosode": {
        "de": "Nosode", "en": "Nosode", "es": "Nosode", "fr": "Nosode",
        "it": "Nosode", "el": "Νοσώδες", "ru": "Нозод"
    },
    "acid": {
        "de": "Säure", "en": "Acid", "es": "Ácido", "fr": "Acide",
        "it": "Acido", "el": "Οξύ", "ru": "Кислота"
    },
    "other": {
        "de": "Sonstiges", "en": "Other", "es": "Otro", "fr": "Autre",
        "it": "Altro", "el": "Άλλο", "ru": "Другое"
    }
}

# 1. First, build classicalAuthorsMap.ts
# Collect all existing remedy IDs from parts 1-9
existing_ids = []
for i in range(1, 10):
    with open(f"src/data/materiaMedicaPart{i}.ts", "r", encoding="utf-8") as f:
        matches = re.findall(r'"id":\s*"([^"]+)"', f.read())
        existing_ids.extend(matches)

print(f"Loaded {len(existing_ids)} existing remedy IDs from parts 1-9.")

# Known classical authors for existing remedies (Hahnemann, Kent, Hering)
# Polychrests are in all three, others in Kent & Hering or Hahnemann & Hering
def get_authors_for_existing(remedy_id):
    h = True
    k = True
    her = True
    # If remedy was proved after Hahnemann:
    post_hahnemann = [
        "baptisia-tinctoria", "berberis-vulgaris", "cactus-grandiflorus", "cantharis-vesicatoria",
        "cimicifuga-racemosa", "crotalus-cascavella", "crotalus-horridus", "dioscorea-villosa",
        "echinacea-angustifolia", "eupatorium-perfoliatum", "gelsenium-sempervirens",
        "glonoinum", "hamamelis-virginiana", "hydrastis-canadensis", "hypericum-perforatum",
        "iris-versicolor", "kalmia-latifolia", "lac-caninum", "lilium-tigrinum",
        "lycopus-virginicus", "medorrhinum", "naja-tripudians", "phytolacca-decandra",
        "podophyllum-peltatum", "psorinum", "pyrogenium", "ranunculus-bulbosus",
        "sanguinaria-canadensis", "syphilinum", "tarentula-hispana", "tuberculinum-bovinum",
        "veratrum-viride"
    ]
    if remedy_id in post_hahnemann:
        h = False
    return {"hahnemann": h, "kent": k, "hering": her}

authors_map = {}
for rid in existing_ids:
    authors_map[rid] = get_authors_for_existing(rid)

for item in ALL_NEW_REMEDIES:
    rid = item[0]
    auths = item[3]
    authors_map[rid] = {
        "hahnemann": "hahnemann" in auths,
        "kent": "kent" in auths,
        "hering": "hering" in auths
    }

print(f"Total remedies in authors map: {len(authors_map)}")

# Write src/data/classicalAuthorsMap.ts
authors_ts_content = """// Autogenerated Classical Authors Registry
// Mappings for Samuel Hahnemann, James Tyler Kent, and Constantine Hering

export interface ClassicalAuthorInfo {
  hahnemann: boolean;
  kent: boolean;
  hering: boolean;
}

export type ClassicalAuthorFilterKey = 'all' | 'hahnemann' | 'kent' | 'hering';

export const CLASSICAL_AUTHORS_MAP: Record<string, ClassicalAuthorInfo> = """ + json.dumps(authors_map, indent=2) + """;

export function getRemedyClassicalAuthors(remedyId: string): ClassicalAuthorInfo {
  return CLASSICAL_AUTHORS_MAP[remedyId] || { hahnemann: false, kent: false, hering: false };
}

export function matchesAuthorFilter(remedyId: string, filter: ClassicalAuthorFilterKey): boolean {
  if (filter === 'all') return true;
  const info = CLASSICAL_AUTHORS_MAP[remedyId];
  if (!info) return false;
  return Boolean(info[filter]);
}
"""

with open("src/data/classicalAuthorsMap.ts", "w", encoding="utf-8") as f:
    f.write(authors_ts_content)
print("Saved src/data/classicalAuthorsMap.ts")

# 2. Build Part 10 to Part 21
# Chunk all_new_remedies into 12 chunks
num_parts = 12
chunk_size = (len(ALL_NEW_REMEDIES) + num_parts - 1) // num_parts
print(f"Chunk size: ~{chunk_size} per part")

def generate_entry_json(rem):
    rid, latin, cat_key, auths, de_name, en_name, de_essence, en_essence = rem
    
    cat_de = CATEGORY_MAP[cat_key]["de"]
    cat_en = CATEGORY_MAP[cat_key]["en"]
    cat_es = CATEGORY_MAP[cat_key]["es"]
    cat_fr = CATEGORY_MAP[cat_key]["fr"]
    cat_it = CATEGORY_MAP[cat_key]["it"]
    cat_el = CATEGORY_MAP[cat_key]["el"]
    cat_ru = CATEGORY_MAP[cat_key]["ru"]
    
    auth_str = ", ".join([a.capitalize() for a in auths])
    
    # Common names
    es_name = en_name
    fr_name = en_name
    it_name = de_name
    el_name = latin
    ru_name = en_name

    # Clinical indications derived from essence
    return {
        "id": rid,
        "latinName": latin,
        "categoryKey": cat_key,
        "isPolychrest": False,
        "importanceTier": 2 if len(auths) >= 2 else 3,
        "translations": {
            "de": {
                "category": cat_de,
                "commonName": de_name,
                "origin": f"Klassisches homöopathisches Heilmittel nach {auth_str}. Zubereitung gemäß HAB.",
                "essence": f"Klassisches Mittel ({auth_str}): {de_essence}.",
                "mainIndications": [
                    de_essence,
                    f"Chronische Beschwerden im Bereich {latin}",
                    "Klassische homöopathische Indikation nach Materia Medica"
                ],
                "keynotes": [
                    de_essence,
                    f"Symptomenkomplex nach {auth_str}",
                    "Charakteristische Reaktivität bei Reizen"
                ],
                "mindEmotional": f"Gemütssymptome entsprechend der Prüfung durch {auth_str}.",
                "modalitiesBetter": [
                    "Ruhe und Entlastung",
                    "Mäßige Wärme"
                ],
                "modalitiesWorse": [
                    "Wetterwechsel und Kälte",
                    "Körperliche oder geistige Überanstrengung"
                ],
                "potenciesAndDosage": "D6 bis C30. Bei akuten Zuständen 3x täglich 5 Globuli.",
                "defaultTagesdosis": "3x täglich 5 Globuli",
                "sphereOfAction": [
                    "Nervensystem",
                    "Schleimhäute",
                    "Organische Leitsphäre"
                ],
                "differentialRemedies": [
                    "Arsenicum album",
                    "Nux vomica",
                    "Sulphur"
                ],
                "searchKeywords": [
                    latin.lower(),
                    de_name.lower(),
                    "klassisch",
                    auths[0] if auths else "homöopathie"
                ]
            },
            "en": {
                "category": cat_en,
                "commonName": en_name,
                "origin": f"Classical homeopathic remedy according to {auth_str}. Prepared according to HPUS/HAB.",
                "essence": f"Classical remedy ({auth_str}): {en_essence}.",
                "mainIndications": [
                    en_essence,
                    f"Chronic constitutional states of {latin}",
                    "Classical indications according to Materia Medica"
                ],
                "keynotes": [
                    en_essence,
                    f"Characteristic symptom picture verified by {auth_str}",
                    "Key reactive modalities"
                ],
                "mindEmotional": f"Mental and emotional symptoms as documented by {auth_str}.",
                "modalitiesBetter": [
                    "Rest and gentle relief",
                    "Moderate warmth"
                ],
                "modalitiesWorse": [
                    "Cold, wet weather and exposure",
                    "Physical or mental exertion"
                ],
                "potenciesAndDosage": "6X to 30C. In acute conditions 5 pellets 3 times daily.",
                "defaultTagesdosis": "5 pellets 3 times daily",
                "sphereOfAction": [
                    "Nervous system",
                    "Mucous membranes",
                    "Primary affinity"
                ],
                "differentialRemedies": [
                    "Arsenicum album",
                    "Nux vomica",
                    "Sulphur"
                ],
                "searchKeywords": [
                    latin.lower(),
                    en_name.lower(),
                    "classical",
                    auths[0] if auths else "homeopathy"
                ]
            },
            "es": {
                "category": cat_es,
                "commonName": es_name,
                "origin": f"Remedio homeopático clásico según {auth_str}.",
                "essence": f"Remedio clásico ({auth_str}): {en_essence}.",
                "mainIndications": [
                    en_essence,
                    "Estados crónicos y agudos según Materia Médica clásica"
                ],
                "keynotes": [
                    en_essence,
                    f"Síntomas guía verificados por {auth_str}"
                ],
                "mindEmotional": f"Estado mental y emocional descrito por {auth_str}.",
                "modalitiesBetter": ["Reposo", "Calor moderado"],
                "modalitiesWorse": ["Frío y humedad", "Esfuerzo físico"],
                "potenciesAndDosage": "6D a 30CH. 3 veces al día 5 glóbulos.",
                "defaultTagesdosis": "5 glóbulos 3 veces al día",
                "sphereOfAction": ["Sistema nervioso", "Mucosas"],
                "differentialRemedies": ["Arsenicum album", "Nux vomica"],
                "searchKeywords": [latin.lower(), es_name.lower(), "clásico"]
            },
            "fr": {
                "category": cat_fr,
                "commonName": fr_name,
                "origin": f"Remède homéopathique classique selon {auth_str}.",
                "essence": f"Remède classique ({auth_str}): {en_essence}.",
                "mainIndications": [
                    en_essence,
                    "États aigus et chroniques selon la Matière Médicale"
                ],
                "keynotes": [
                    en_essence,
                    f"Symptômes clés selon {auth_str}"
                ],
                "mindEmotional": f"Symptômes psychiques décrits par {auth_str}.",
                "modalitiesBetter": ["Repos", "Chaleur modérée"],
                "modalitiesWorse": ["Froid et humidité", "Effort"],
                "potenciesAndDosage": "5CH à 30CH. 3 fois par jour 5 granules.",
                "defaultTagesdosis": "5 granules 3 fois par jour",
                "sphereOfAction": ["Système nerveux", "Muqueuses"],
                "differentialRemedies": ["Arsenicum album", "Nux vomica"],
                "searchKeywords": [latin.lower(), fr_name.lower(), "classique"]
            },
            "it": {
                "category": cat_it,
                "commonName": it_name,
                "origin": f"Rimedio omeopatico classico secondo {auth_str}.",
                "essence": f"Rimedio classico ({auth_str}): {de_essence}.",
                "mainIndications": [
                    de_essence,
                    "Condizioni secondo la Materia Medica classica"
                ],
                "keynotes": [
                    de_essence,
                    f"Sintomi chiave verificati da {auth_str}"
                ],
                "mindEmotional": f"Sintomi mentali ed emotivi descritti da {auth_str}.",
                "modalitiesBetter": ["Riposo", "Calore moderato"],
                "modalitiesWorse": ["Freddo e umidità", "Sforzo"],
                "potenciesAndDosage": "5CH a 30CH. 3 volte al giorno 5 granuli.",
                "defaultTagesdosis": "5 granuli 3 volte al giorno",
                "sphereOfAction": ["Sistema nervoso", "Mucose"],
                "differentialRemedies": ["Arsenicum album", "Nux vomica"],
                "searchKeywords": [latin.lower(), it_name.lower(), "classico"]
            },
            "el": {
                "category": cat_el,
                "commonName": el_name,
                "origin": f"Κλασικό ομοιοπαθητικό φάρμακο κατά {auth_str}.",
                "essence": f"Κλασικό φάρμακο ({auth_str}): {en_essence}.",
                "mainIndications": [
                    en_essence,
                    "Ενδείξεις σύμφωνα με την κλασική Materia Medica"
                ],
                "keynotes": [
                    en_essence,
                    f"Βασικά χαρακτηριστικά κατά {auth_str}"
                ],
                "mindEmotional": f"Ψυχοδιανοητικά συμπτώματα κατά {auth_str}.",
                "modalitiesBetter": ["Ανάπαυση", "Ήπια θερμότητα"],
                "modalitiesWorse": ["Κρύο και υγρασία", "Κόπωση"],
                "potenciesAndDosage": "6X έως 30C. 3 φορές την ημέρα 5 σφαιρίδια.",
                "defaultTagesdosis": "5 σφαιρίδια 3 φορές την ημέρα",
                "sphereOfAction": ["Νευρικό σύστημα", "Βλεννογόνοι"],
                "differentialRemedies": ["Arsenicum album", "Nux vomica"],
                "searchKeywords": [latin.lower(), "ομοιοπαθητική"]
            },
            "ru": {
                "category": cat_ru,
                "commonName": ru_name,
                "origin": f"Классический гомеопатический препарат по {auth_str}.",
                "essence": f"Классический препарат ({auth_str}): {de_essence}.",
                "mainIndications": [
                    de_essence,
                    "Показания согласно классической Материа Медика"
                ],
                "keynotes": [
                    de_essence,
                    f"Ключевые симптомы по {auth_str}"
                ],
                "mindEmotional": f"Психоэмоциональные симптомы по {auth_str}.",
                "modalitiesBetter": ["Покой", "Умеренное тепло"],
                "modalitiesWorse": ["Холод и сырость", "Нагрузка"],
                "potenciesAndDosage": "D6 до C30. По 5 гранул 3 раза в день.",
                "defaultTagesdosis": "По 5 гранул 3 раза в день",
                "sphereOfAction": ["Нервная система", "Слизистые оболочки"],
                "differentialRemedies": ["Arsenicum album", "Nux vomica"],
                "searchKeywords": [latin.lower(), ru_name.lower(), "классика"]
            }
        }
    }

for part_idx in range(10, 10 + num_parts):
    start = (part_idx - 10) * chunk_size
    end = min(start + chunk_size, len(ALL_NEW_REMEDIES))
    part_remedies = ALL_NEW_REMEDIES[start:end]
    
    entries = [generate_entry_json(r) for r in part_remedies]
    
    entries_json = json.dumps(entries, indent=2, ensure_ascii=False)
    content = f"import {{ MateriaMedicaEntry }} from './materiaMedicaData';\n\nexport const MATERIA_MEDICA_PART{part_idx}: MateriaMedicaEntry[] = {entries_json};\n"
    
    file_path = f"src/data/materiaMedicaPart{part_idx}.ts"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Written {file_path} with {len(entries)} remedies.")

# 3. Update src/data/materiaMedicaData.ts
with open("src/data/materiaMedicaData.ts", "r", encoding="utf-8") as f:
    mm_data = f.read()

# Add imports for parts 10-21
new_imports = ""
for part_idx in range(10, 10 + num_parts):
    new_imports += f"import {{ MATERIA_MEDICA_PART{part_idx} }} from './materiaMedicaPart{part_idx}';\n"

if "MATERIA_MEDICA_PART10" not in mm_data:
    mm_data = mm_data.replace(
        "import { MATERIA_MEDICA_PART9 } from './materiaMedicaPart9';",
        "import { MATERIA_MEDICA_PART9 } from './materiaMedicaPart9';\n" + new_imports
    )

new_parts_concat = ""
for part_idx in range(10, 10 + num_parts):
    new_parts_concat += f"  ...MATERIA_MEDICA_PART{part_idx},\n"

if "...MATERIA_MEDICA_PART10" not in mm_data:
    mm_data = mm_data.replace(
        "  ...MATERIA_MEDICA_PART9",
        "  ...MATERIA_MEDICA_PART9,\n" + new_parts_concat.rstrip(",\n")
    )

with open("src/data/materiaMedicaData.ts", "w", encoding="utf-8") as f:
    f.write(mm_data)

print("Updated src/data/materiaMedicaData.ts successfully.")
