# scripts/catalog_a_f.py
# Compact catalog of classical remedies A - F

REMEDIES_A_F = [
    # (id, latin, cat, authors, poly, tier, de_name, en_name, de_origin, en_origin, de_essence, en_essence, de_inds, en_inds, de_keys, en_keys, de_mind, en_mind, de_better, en_better, de_worse, en_worse, sphere, diffs, keywords)
    (
        "actaea-spicata", "Actaea spicata", "plant", ["kent", "hering"], False, 2,
        "Christophskraut", "Baneberry",
        "Frische Wurzel von Actaea spicata (Hahnenfußgewächse).", "Fresh root of Actaea spicata (Ranunculaceae).",
        "Rheumatoide Schwellung der kleinen Hand- und Fußgelenke, extrem empfindlich gegen Berührung und Kälte.",
        "Rheumatic inflammation of the small joints of hands and feet, acutely sensitive to touch and cold air.",
        ["Arthrose der Finger- und Zehengelenke", "Gicht der Handgelenke", "Neuralgien des Gesichts"],
        ["Arthritis of small finger and toe joints", "Wrist gout", "Facial neuralgia"],
        ["Schwellung der Fingergelenke nach geringer Anstrengung", "Gelenke schwellen nach Ermüdung an", "Schmerz reißend und stechend"],
        ["Swelling of finger joints after slight exertion", "Joints swell after fatigue", "Tearing stitching pain"],
        "Ängstlich, fürchtet den Tod, besonders nachts im Bett.", "Anxious, fears death, especially at night in bed.",
        ["Wärme", "Ruhiges Liegen"], ["Warmth", "Quiet lying"],
        ["Berührung", "Kälte", "Bewegung der Gelenke"], ["Touch", "Cold", "Motion of joints"],
        ["Kleine Gelenke", "Sehnen", "Periost"], ["Caulophyllum", "Ledum", "Ruta"], ["fingergelenke", "rheuma", "gicht", "christophskraut"]
    ),
    (
        "adonis-vernalis", "Adonis vernalis", "plant", ["hering"], False, 2,
        "Frühlings-Adonisröschen", "Pheasant's Eye",
        "Ganze blühende Pflanze von Adonis vernalis.", "Whole flowering plant of Adonis vernalis.",
        "Herzmittel bei Myokardschwäche, unregelmäßigem Puls und kardialen Ödemen mit Beklemmung.",
        "Cardiac remedy for weak irregular heart action, low vitality, and dropsy.",
        ["Herzinsuffizienz mit Ödemen", "Kardiale Dyspnoe", "Herzklopfen bei Schilddrüsenüberfunktion"],
        ["Congestive heart failure with edema", "Cardiac dyspnea", "Palpitations in hyperthyroidism"],
        ["Präkordialer Druck mit Schweregefühl auf der Brust", "Puls schnell, schwach und unregelmäßig", "Wassersucht mit spärlichem Urin"],
        ["Precordial oppression with heaviness on chest", "Pulse rapid, feeble, irregular", "Dropsy with scanty urine"],
        "Ängstlich um das Herz, unruhig, furchtsam im Dunkeln.", "Anxious about heart, restless, fearful in dark.",
        ["Ruhe im Sitzen", "Frische Luft"], ["Rest in sitting posture", "Fresh air"],
        ["Körperliche Anstrengung", "Flaches Liegen"], ["Physical exertion", "Lying flat"],
        ["Herzmuskel", "Gefäßtonus", "Nierenfunktion"], ["Digitalis", "Crataegus", "Convallaria"], ["herzinsuffizienz", "puls", "ödeme", "herzklopfen", "adonis"]
    ),
    (
        "alstonia-scholaris", "Alstonia scholaris", "plant", ["hering"], False, 3,
        "Dita-Rinde", "Dita Bark",
        "Rinde von Alstonia scholaris.", "Bark of Alstonia scholaris.",
        "Malariale Rekonvaleszenz mit chronischer Diarrhö, Schwäche und Verdauungsversagen.",
        "Malarial debility with chronic camp diarrhea, indigestion, and profound exhaustion.",
        ["Chronische Diarrhö nach Tropenreisen", "Postinfektiöse Erschöpfung", "Dyspepsie mit Zungenbelag"],
        ["Chronic tropical diarrhea", "Post-infectious exhaustion", "Dyspepsia with coated tongue"],
        ["Wässrige, unverdaut abfließende Stühle", "Leeregefühl in der Magengrube", "Ständiges Frösteln trotz Wärme"],
        ["Watery lienteric stools", "Empty sinking sensation in epigastrium", "Chilly even in warm room"],
        "Geistig erschöpft, apathisch, melancholisch.", "Brain fag, listless, melancholic.",
        ["Wärme", "Nach Ruhe"], ["Warmth", "After rest"],
        ["Nach dem Essen", "Geringe Kälte"], ["After eating", "Slight cold"],
        ["Darmtrakt", "Blutbildung", "Milz"], ["China", "Chininum ars", "Alstonia"], ["ditarinde", "durchfall", "tropen", "schwäche"]
    ),
    (
        "alumina-phosphorica", "Alumina phosphorica", "mineral", ["kent"], False, 3,
        "Aluminiumphosphat", "Aluminium Phosphate",
        "Synthetische Verbindung aus Tonerde und Phosphorsäure.", "Synthetic compound of alumina and phosphoric acid.",
        "Tiefe Nervenschwäche mit Gedächtnisverlust, chronischer Obstipation und Kälteempfindlichkeit.",
        "Profound nervous exhaustion with loss of memory, atonic constipation, and chilliness.",
        ["Parästhesien & Taubheitsgefühl", "Atonische Obstipation", "Geistige Erschöpfung", "Wirbelsäulenschwäche"],
        ["Paresthesia & numbness", "Atonic constipation", "Mental exhaustion", "Spinal weakness"],
        ["Trägheit des Rektums, weicher Stuhl erfordert starkes Pressen", "Kältegefühl in Wirbelsäule und Knochen", "Verwirrung über die eigene Person"],
        ["Inactivity of rectum, soft stool expelled with difficulty", "Coldness in spine and bones", "Confusion of personal identity"],
        "Gedächtnisschwund, ängstlich am Morgen, verwirrt.", "Loss of memory, morning anxiety, confused identity.",
        ["Wärme", "Ruhiges Sitzen"], ["Warmth", "Quiet sitting"],
        ["Kälte", "Geistige Arbeit", "Morgens"], ["Cold", "Mental labor", "Morning"],
        ["Rückenmark", "ZNS", "Rektum"], ["Alumina", "Phosphorus", "Plumbum"], ["aluminiumphosphat", "nervenschwäche", "obstipation", "gedächtnis"]
    ),
    (
        "alumina-silicata", "Alumina silicata", "mineral", ["kent"], False, 3,
        "Aluminiumsilikat", "Aluminium Silicate",
        "Natürliches Aluminiumsilikat (Kaolin).", "Natural aluminium silicate (kaolin).",
        "Chronische Schwächezustände mit Eiterungsneigung, trockenem Katarrh und Verstopfung.",
        "Chronic debilitated states with tendency to suppuration, dry crusty catarrh, and constipation.",
        ["Rhinitis mit dicken Krusten", "Chronische Kachexie", "Obstipation durch Trockenheit"],
        ["Crusty nasal catarrh", "Chronic cachexia", "Constipation from dryness"],
        ["Trockenheit aller Schleimhäute", "Kältegefühl im Rücken und den Knochen", "Magert trotz gutem Appetit ab"],
        ["Dryness of mucous membranes", "Coldness in back and bones", "Emaciation despite good appetite"],
        "Mürrisch, niedergeschlagen, abgeneigt gegen Gesellschaft.", "Sullen, despondent, averse to company.",
        ["Wärme", "Trockene Luft"], ["Warmth", "Dry atmosphere"],
        ["Kälte & Feuchtigkeit", "Geistige Anstrengung"], ["Cold and damp", "Mental exertion"],
        ["Schleimhäute", "Nervensystem", "Knochen"], ["Alumina", "Silicea"], ["krusten", "silikat", "abmagerung", "trockenheit"]
    ),
    (
        "ambrosia-artemisiifolia", "Ambrosia artemisiifolia", "plant", ["hering"], False, 2,
        "Beifußblättrige Ambrosie", "Ragweed",
        "Frische blühende Zweige von Ambrosia artemisiifolia.", "Fresh flowering tops of Ambrosia artemisiifolia.",
        "Spezifisches Heuschnupfenmittel mit heftigem Juckreiz der Augenlider und wässrigem Fließschnupfen.",
        "Specific remedy for hay fever with intense itching of eyelids and profuse watery coryza.",
        ["Heuschnupfen & Pollenallergie", "Asthma bronchiale im Spätsommer", "Allergische Konjunktivitis"],
        ["Hay fever & pollinosis", "Late summer asthma", "Allergic conjunctivitis"],
        ["Unerträgliches Jucken in Augen und Nase", "Ständiges Niesen mit wässrigem Sekret", "Engegefühl in der Brust bei Allergenkontakt"],
        ["Intolerable itching of eyes and nose", "Constant sneezing with watery discharge", "Chest wheezing upon pollen exposure"],
        "Gereizt durch das ständige Niesen, schläfrig am Tag.", "Irritable from sneezing, drowsy during day.",
        ["Geschlossene Räume", "Kühle Waschungen der Augen"], ["Indoors", "Cool bathing of eyes"],
        ["Freie Luft", "Pollenflug", "Spätsommer"], ["Open air", "Pollen exposure", "Late summer"],
        ["Nasenschleimhaut", "Augenbindehaut", "Bronchien"], ["Sabadilla", "Allium cepa", "Euphrasia"], ["heuschnupfen", "ambrosia", "pollenallergie", "augenjucken", "niesen"]
    ),
    (
        "ammoniacum-gummi", "Ammoniacum gummi", "plant", ["hering"], False, 3,
        "Ammoniakgummi", "Gum Ammoniac",
        "Gummicharz von Dorema ammoniacum.", "Gum resin of Dorema ammoniacum.",
        "Chronischer Bronchialkatarrh bei älteren Menschen mit reichlichem zähem Schleim und Asthma.",
        "Chronic bronchial catarrh in elderly subjects with tenacious mucus and asthmatic wheezing.",
        ["Senile Bronchitis", "Lungenemphysem", "Asthma mit zähem Auswurf"],
        ["Senile bronchitis", "Emphysema", "Asthma with tough expectoration"],
        ["Zäher, fadenziehender Schleim, schwer aufzuhusten", "Rasselnde Atmung mit Kurzatmigkeit bei Bewegung", "Gefühl von Rauch in den Atemwegen"],
        ["Tenacious adherent mucus difficult to raise", "Rattling breathing with dyspnea on walking", "Sensation of smoke in larynx"],
        "Ängstlich bei Atemnot, unruhig in der Nacht.", "Anxious with dyspnea, restless at night.",
        ["Warmes Einhüllen", "Aufrechtes Sitzen"], ["Warm wrapping", "Sitting upright"],
        ["Kaltes feuchtes Wetter", "Gehen", "Liegen"], ["Cold damp weather", "Walking", "Lying down"],
        ["Bronchialschleimhaut", "Lunge", "Kehlkopf"], ["Senega", "Antimonium tart", "Kali bich"], ["senile bronchitis", "zäher schleim", "ammoniakgummi", "emphysem"]
    ),
    (
        "ammonium-benzoicum", "Ammonium benzoicum", "mineral", ["hering"], False, 3,
        "Ammoniumbenzoat", "Ammonium Benzoate",
        "Salz aus Ammoniak und Benzoesäure.", "Salt of ammonia and benzoic acid.",
        "Harnsäure-Diathese mit gichtigen Ablagerungen, rauchigem Urin und stechendem Geruch.",
        "Uric acid diathesis with gouty concretions, smoky turbid urine, and pungent ammoniacal odor.",
        ["Gichtknoten & Arthritis urica", "Chronische Zystitis", "Albuminurie mit Ödemen"],
        ["Gouty deposits & arthritis", "Chronic cystitis", "Albuminuria with swelling"],
        ["Urin dunkel, rauchig mit stechendem Geruch nach Pferdeharn", "Gichtige Schwellung der Zehen- und Fingergelenke", "Ödeme der Lider"],
        ["Urine dark smoky with pungent horse-like odor", "Gouty swelling of small joints", "Edema of eyelids"],
        "Trübsinnig, mürrisch bei Schmerzen.", "Gloomy, irritable during pains.",
        ["Wärme", "Viel Trinken"], ["Warmth", "Copious fluids"],
        ["Kälte", "Fleischverzehr", "Nässe"], ["Cold", "Meat diet", "Wet weather"],
        ["Nieren & Harnwege", "Gelenke", "Stoffwechsel"], ["Benzoic acid", "Ammonium carb", "Berberis"], ["ammoniumbenzoat", "gicht", "harnsäure", "rauchiger urin"]
    ),
    (
        "ammonium-bromatum", "Ammonium bromatum", "mineral", ["hering"], False, 3,
        "Ammoniumbromid", "Ammonium Bromide",
        "Synthetisches Salz aus Ammoniak und Bromwasserstoff.", "Salt of ammonia and hydrobromic acid.",
        "Krampfhusten mit Erstickungsgefühl, Larynxkitzeln und Rötung der Augenränder.",
        "Spasmodic suffocation cough with laryngeal tickling and redness of lid margins.",
        ["Keuchhusten & Spasmen", "Chronische Pharyngitis", "Reizhusten nachts"],
        ["Whooping cough spasms", "Chronic pharyngitis", "Dry nocturnal cough"],
        ["Plötzlicher Kitzelhusten beim Hinlegen", "Krampfartiger Husten bis zum Erbrechen", "Zungenwurzel fühlt sich wie geschwollen an"],
        ["Sudden tickling cough on lying down", "Suffocative paroxysms ending in vomiting", "Root of tongue feels swollen"],
        "Nervös, fahrig, schreckhaft bei Geräuschen.", "Nervous, easily startled by sounds.",
        ["Aufrechtes Sitzen", "Warme Getränke"], ["Sitting erect", "Warm drinks"],
        ["Hinlegen", "Nachts zwischen 2 und 4 Uhr"], ["Lying down", "Night 2-4 AM"],
        ["Kehlkopf & Trachea", "Nervensystem", "Augenlider"], ["Drosera", "Bromium", "Hyoscyamus"], ["ammoniumbromid", "krampfhusten", "kitzelhusten", "erstickungsgefühl"]
    ),
    (
        "ammonium-causticum", "Ammonium causticum", "mineral", ["hering"], False, 3,
        "Salmiakgeist", "Ammonia Water",
        "Wässrige Lösung von gasförmigem Ammoniak.", "Aqueous solution of ammonia gas.",
        "Heftigste Kehlkopfentzündung mit Membranbildung, Erstickungsanfällen und brennendem Wundschmerz.",
        "Violent membranous croup with suffocative spasms and raw burning pain in larynx.",
        ["Akute Laryngitis membranosa", "Kruppartige Anfälle", "Verätzungen der Schleimhaut"],
        ["Membranous croup", "Suffocative laryngeal spasm", "Mucosal caustic burns"],
        ["Brennender Schmerz im Hals wie mit Säure verätzt", "Stridor mit Erstickungsangst", "Vollständige Aphonie mit Speichelfluss"],
        ["Burning rawness in throat as if scalded", "Loud stridor with terror of suffocation", "Complete aphonia with salivation"],
        "Todesangst durch Erstickungsnot, verzweifelt.", "Terror of death from suffocation, desperate.",
        ["Frische feuchte Luft", "Aufrechtes Sitzen"], ["Cool humid air", "Sitting erect"],
        ["Schlucken", "Liegen", "Sprechen"], ["Swallowing", "Lying down", "Speaking"],
        ["Kehlkopf & Trachea", "Rachenschleimhaut"], ["Spongia", "Hepar sulph", "Bromium"], ["salmiakgeist", "krupp", "kehlkopf", "erstickung", "aphonie"]
    ),
    (
        "ammonium-iodatum", "Ammonium iodatum", "mineral", ["hering"], False, 3,
        "Ammoniumiodid", "Ammonium Iodide",
        "Salz aus Ammoniak und Iodwasserstoff.", "Salt of ammonia and hydriodic acid.",
        "Katarrhe der oberen Atemwege mit Schwellung der Lymphe und Schilddrüse, schlimmer in warmer Stube.",
        "Catarrh of upper airways with glandular and thyroid enlargement, worse in warm rooms.",
        ["Chronische Laryngitis", "Struma & Lymphknotenschwellung", "Asthmatische Bronchitis"],
        ["Chronic laryngitis", "Goiter & lymphadenopathy", "Asthmatic bronchitis"],
        ["Schwellung der Halslymphknoten mit Heiserkeit", "Trockener, schmerzhafter Kehlkopfhusten", "Verlangen nach frischer Luft"],
        ["Cervical lymph node swelling with hoarseness", "Dry painful laryngeal cough", "Craving for fresh open air"],
        "Unruhig, ängstlich, leicht erregbar.", "Restless, anxious, easily excited.",
        ["Kühle frische Luft", "Kaltes Trinken"], ["Cool open air", "Cold drinks"],
        ["Warme geschlossene Räume", "Nachts"], ["Warm closed rooms", "Night"],
        ["Schilddrüse & Lymphdrüsen", "Atemwege"], ["Iodium", "Ammonium carb", "Spongia"], ["ammoniumiodid", "lymphknoten", "schilddrüse", "struma", "heiserkeit"]
    ),
    (
        "ammonium-muriaticum", "Ammonium muriaticum", "mineral", ["hahnemann", "kent", "hering"], True, 2,
        "Salmiaksalz", "Ammonium Chloride",
        "Reines Ammoniumchlorid (NH4Cl).", "Pure ammonium chloride (NH4Cl).",
        "Fettiger Rumpf mit dünnen Beinen, wässriger beißender Schnupfen und Verkürzung der Beugesehnen.",
        "Fat bloated body with thin extremities, acrid watery coryza, and tension in hamstring tendons.",
        ["Beißender Schnupfen & Rhinitis", "Ischialgie mit Sehnenverkürzung", "Obstipation mit bröckeligem Stuhl"],
        ["Acrid burning coryza", "Sciatica with tendon contraction", "Crumbly dry constipation"],
        ["Sehnen in den Kniekehlen wie zu kurz, kann Beine nicht strecken", "Stuhl bröckelig, bricht am Afterrand ab", "Reichlicher dünner Fließschnupfen macht Oberlippe wund"],
        ["Hamstring tendons feel shortened and tight", "Hard crumbling stool breaks at anal margin", "Watery acrid coryza excoriating upper lip"],
        "Mürrisch, schweigsam, traurig, will nicht sprechen.", "Sullen, taciturn, weeping, averse to talking.",
        ["Freie Luft", "Reiben & Massage"], ["Open air", "Rubbing & massage"],
        ["Sitzen", "Kälte", "Morgens"], ["Sitting posture", "Cold", "Morning"],
        ["Sehnen & Bänder", "Schleimhäute", "Rektum"], ["Ammonium carb", "Causticum", "Rhus tox"], ["salmiak", "sehnenverkürzung", "ischias", "bröckeliger stuhl", "schnupfen"]
    ),
    (
        "ammonium-phosphoricum", "Ammonium phosphoricum", "mineral", ["kent"], False, 3,
        "Ammoniumphosphat", "Ammonium Phosphate",
        "Synthetisches Salz aus Ammoniak und Phosphorsäure.", "Synthetic salt of ammonia and phosphoric acid.",
        "Gichtige Knötchen an Fingern und Gelenken mit Bronchitis und Harnsäureüberlastung.",
        "Gouty nodosities in finger joints of patients subject to bronchitis and uric acid diathesis.",
        ["Arthritis urica", "Heberden-Knoten", "Chronische Bronchitis bei Gicht"],
        ["Gouty arthritis", "Heberden's nodes", "Chronic gouty bronchitis"],
        ["Gichtknoten an Fingern und Zehen", "Harnsäure-Urin mit stechendem Geruch", "Tiefer Husten mit zähem Schleim"],
        ["Gouty concretions in finger and toe joints", "Uric acid urine with pungent ammoniacal odor", "Deep cough with tenacious mucus"],
        "Reizbar bei Schmerzen, mürrisch.", "Irritable during arthritic pains, morose.",
        ["Wärme", "Ruhige Lage"], ["Warmth", "Quiet rest"],
        ["Kälte & Nässe", "Fleischkost"], ["Cold and wet", "Rich meat diet"],
        ["Gelenke & Sehnen", "Stoffwechsel", "Atemwege"], ["Benzoic acid", "Ledum", "Colchicum"], ["gicht", "gichtknoten", "harnsäure", "fingergelenke"]
    ),
    (
        "ammonium-valerianicum", "Ammonium valerianicum", "mineral", ["hering"], False, 3,
        "Ammoniumvalerianat", "Ammonium Valerianate",
        "Salz aus Ammoniak und Baldriansäure.", "Salt of ammonia and valeric acid.",
        "Nervöse Herzbeschwerden, Schlaflosigkeit und Hysterie bei überreizten Personen.",
        "Nervous cardiac palpitations, insomnia, and hysteria in hypersensitive individuals.",
        ["Nervöses Herzklopfen", "Schlaflosigkeit durch Gedankenandrang", "Hysterische Globusbeschwerden"],
        ["Nervous palpitations", "Insomnia from racing thoughts", "Hysterical globus"],
        ["Herzrasen bei geringster emotionaler Erregung", "Hyperästhesie aller Sinne", "Neuralgischer Kopfschmerz"],
        ["Tachycardia from emotional excitement", "Hyperesthesia of all senses", "Neuralgic clavus headache"],
        "Hysterisch, wechselhafte Stimmung, kann nicht abschalten.", "Hysterical, variable moods, racing mind.",
        ["Bewegung im Freien", "Ablenkung"], ["Motion in open air", "Diversion"],
        ["Emotionale Aufregung", "Ruhe", "Koffein"], ["Emotional excitement", "Quiet rest", "Caffeine"],
        ["Vegetatives Nervensystem", "Herz & Gefäße"], ["Valeriana", "Coffea", "Ignatia"], ["ammoniumvalerianat", "baldrian", "herzklopfen", "hysterie"]
    ),
    (
        "amylenum-nitrosum", "Amylenum nitrosum", "mineral", ["hering"], False, 2,
        "Amylnitrit", "Amyl Nitrite",
        "Flüssiger Salpetrigsäure-Isoamylester.", "Liquid isoamyl nitrite.",
        "Plötzliche Hitzewallungen im Klimakterium mit scharlachrotem Gesicht, Pulsieren der Halsschlagadern und Angst.",
        "Sudden climacteric flushes of heat with crimson face, throbbing carotids, and profound anxiety.",
        ["Klimakterische Hitzewallungen", "Angina pectoris mit Beklemmung", "Gefäßkrämpfe & Erröten"],
        ["Climacteric hot flashes", "Angina pectoris", "Vasospasm & blushing"],
        ["Plötzliche Hitze steigt in den Kopf, Gesicht wird feuerrot", "Pulsieren der Karotiden und Schläfenarterien", "Gefühl von Enge um die Brust und den Hals"],
        ["Surge of heat ascending to head with scarlet face", "Visible throbbing of carotids and temples", "Constriction around chest and neck"],
        "Große Angst, Furcht vor Ohnmacht oder Schlaganfall.", "Intense anxiety, fear of fainting or apoplexy.",
        ["Frische kühle Luft", "Kaltes Wasser ins Gesicht"], ["Cool fresh air", "Cold water to face"],
        ["Klimakterium", "Wärme", "Geringste Aufregung"], ["Climacteric", "Warmth", "Slightest excitement"],
        ["Vasomotorische Nerven", "Herzkranzgefäße", "Gehirndurchblutung"], ["Glonoinum", "Lachesis", "Belladonna"], ["amylnitrit", "hitzewallungen", "klimakterium", "rotes gesicht"]
    ),
    (
        "anagallis-arvensis", "Anagallis arvensis", "plant", ["hering"], False, 3,
        "Ackergauchheil", "Scarlet Pimpernel",
        "Ganze frische blühende Pflanze von Anagallis arvensis.", "Whole fresh flowering plant of Anagallis arvensis.",
        "Hautausschläge an den Handflächen mit Bläschen, Juckreiz und Reizung der Harnröhre.",
        "Vesicular eruptions on palms of hands with violent itching and urethral irritation.",
        ["Dyshidrotisches Handekzem", "Urethritis & Brennen beim Wasserlassen", "Warzen an den Händen"],
        ["Dyshidrotic hand eczema", "Urethritis with burning", "Warts on hands"],
        ["Kleine Bläschen an Händen und Fingern mit starkem Juckreiz", "Kitzeln und Kribbeln in der Harnröhre", "Trockene Schuppung der Handflächen"],
        ["Small itchy vesicles on palms and fingers", "Tickling in urethra before urination", "Dry scaling of palms"],
        "Fröhlich, redselig, wechselnd zu Missmut.", "Exhilarated, talkative, alternating with moodiness.",
        ["Kaffee", "Kratzen bis es blutet"], ["Coffee", "Scratching until it bleeds"],
        ["Wasserberührung", "Seife", "Kälte"], ["Contact with water", "Soap", "Cold"],
        ["Haut der Handflächen", "Harnröhre"], ["Graphites", "Mezereum", "Rhus tox"], ["ackergauchheil", "handekzem", "bläschen", "juckreiz"]
    ),
    (
        "angustura-vera", "Angustura vera", "plant", ["hahnemann", "hering"], False, 3,
        "Echte Angusturarinde", "Angostura Bark",
        "Rinde von Galipea officinalis. Von Hahnemann geprüft.", "Bark of Galipea officinalis. Proved by Hahnemann.",
        "Krämpfe, Tetanusneigung, Steifigkeit der Gelenke und Karies der Knochen.",
        "Convulsive spasms, tetanic rigidity, joint stiffness, and bone caries.",
        ["Trismus & Tetanuskrämpfe", "Knochenkaries & Knochenschmerzen", "Sehnenschmerzen"],
        ["Trismus & tetanic spasms", "Caries of long bones", "Tendon contractures"],
        ["Krampfhaftes Zusammenziehen der Muskeln bei geringster Berührung", "Knochenschmerzen wie zerschlagen", "Knacken in allen Gelenken bei Bewegung"],
        ["Tetanic spasms of muscles on slightest touch", "Bruised pain in long bones", "Cracking in all joints upon motion"],
        "Extrem reizbar, verstimmt, leicht beleidigt.", "Extremely irritable, touchy, easily offended.",
        ["Wärme", "Ruhiges Liegen"], ["Warmth", "Quiet lying"],
        ["Berührung", "Kälte", "Plötzliche Bewegung"], ["Touch", "Cold", "Sudden motion"],
        ["Knochen & Periost", "Muskulatur & Sehnen", "Nervensystem"], ["Cicuta", "Nux vomica", "Ruta"], ["krämpfe", "knochenkaries", "tetanus", "steifigkeit"]
    ),
    (
        "anhalonium-lewinii", "Anhalonium lewinii", "plant", ["hering"], False, 3,
        "Peyote-Kaktus", "Peyote",
        "Getrocknete Spitzen des Kaktus Lophophora williamsii.", "Dried tops of cactus Lophophora williamsii.",
        "Farbenreiche visuelle Halluzinationen, Entfremdung der Sinne und Depersonalisation.",
        "Brilliant colored visual hallucinations, depersonalization, and heightened sensory awareness.",
        ["Migräne mit visuellen Auren", "Schlaflosigkeit mit lebhaften Bildern", "Neurasthenie"],
        ["Migraine with visual aura", "Insomnia with kaleidoscope imagery", "Neurasthenia"],
        ["Wunderbare Farbenpracht vor geschlossenen Augen", "Gefühl der Spaltung der Persönlichkeit", "Verändertes Zeitempfinden"],
        ["Gorgeous kaleidoscopic visual imagery", "Sensation of divided personality", "Loss of time sense"],
        "Gefühl von Weltentrücktheit, Apathie gegen Pflichten.", "Detached from surroundings, apathy towards duties.",
        ["Dunkler ruhiger Raum", "Liegen"], ["Dark quiet room", "Lying down"],
        ["Bewegung", "Helles Licht", "Lärm"], ["Motion", "Bright light", "Noise"],
        ["ZNS & Wahrnehmung", "Sehnerv"], ["Cannabis indica", "Stramonium", "Belladonna"], ["peyote", "visionen", "farben", "halluzination"]
    ),
    (
        "anisum-stellatum", "Anisum stellatum", "plant", ["hahnemann", "hering"], False, 3,
        "Sternanis", "Star Anise",
        "Reife Früchte von Illicium verum.", "Ripe fruit of Illicium verum.",
        "Stechende Schmerzen in der dritten rechten Rippe mit Husten und Hämoptyse.",
        "Sharp stitching pains in third right rib with cough and hemoptysis.",
        ["Interkostalneuralgie", "Krampfhusten mit Stechen", "Säuglingskoliken"],
        ["Intercostal neuralgia", "Spasmodic cough with stitching", "Infantile colic"],
        ["Scharfer stechender Schmerz an der 3. rechten Rippe zum Knorpel", "Kolikschmerzen bei Säuglingen mit Blähungen", "Zäher Schleim mit bitterem Geschmack"],
        ["Sharp stitching pain at 3rd right rib junction", "Flatulent infantile colic", "Tough phlegm tasting bitter"],
        "Unruhig, weinerlich bei Koliken.", "Restless, whimpering from colic.",
        ["Warme Auflagen", "Aufstoßen & Windabgang"], ["Warm compresses", "Eructation and flatus"],
        ["Brustkorbbewegung", "Tiefes Einatmen", "Kälte"], ["Chest movement", "Deep breathing", "Cold"],
        ["Brustkorb & Rippen", "Darm & Blähungen", "Atemwege"], ["Bryonia", "Colocynthis", "Ranunculus"], ["sternanis", "rippenschmerz", "dritte rippe", "blähungskolik"]
    ),
    (
        "anthemis-nobilis", "Anthemis nobilis", "plant", ["hering"], False, 3,
        "Römische Kamille", "Roman Chamomile",
        "Frische Blütenköpfe von Chamaemelum nobile.", "Fresh flower heads of Chamaemelum nobile.",
        "Gastrische Beschwerden mit kaltem Frösteln, Zungenkribbeln und dyspeptischem Kopfschmerz.",
        "Gastric derangement with cold shivering, tingling of tongue, and dyspeptic headache.",
        ["Dyspepsie mit Kältegefühl", "Gastralgie nach schwerem Essen", "Gallenbeschwerden"],
        ["Dyspepsia with chilliness", "Gastralgia after rich food", "Biliary disorders"],
        ["Schweregefühl und Kälte im Magen", "Zunge brennt und kribbelt wie bestäubt", "Kopfschmerz zieht vom Nacken zur Stirn"],
        ["Sensation of cold heaviness in stomach", "Tongue burns and tingles", "Headache ascending from occiput to forehead"],
        "Mürrisch, ungeduldig, aber weniger zornig als Chamomilla.", "Morose, impatient, less violent than Chamomilla.",
        ["Wärme", "Leichte Bewegung"], ["Warmth", "Gentle motion"],
        ["Kälte", "Fettige Speisen", "Geistige Arbeit"], ["Cold", "Fatty food", "Mental labor"],
        ["Magen-Darm-Trakt", "Kopfnervern", "Gallenwege"], ["Chamomilla", "Nux vomica", "Pulsatilla"], ["römische kamille", "dyspepsie", "kälte im magen", "zungenbrennen"]
    ),
    (
        "anthracinum", "Anthracinum", "nosode", ["hering"], False, 2,
        "Milzbrand-Nosode", "Anthrax Nosode",
        "Nosode aus Milzbrandgift, potenziert über C30.", "Nosode from anthrax poison, potentized above 30C.",
        "Maligne Eiterungen, Karbunkel mit unerträglich brennenden Schmerzen und septischem Verfall.",
        "Malignant suppurations, carbuncles with unbearable burning pain and septic collapse.",
        ["Schwere Karbunkel & Furunkulose", "Gangrän & septische Phlegmone", "Insektenstiche mit septischem Verlauf"],
        ["Severe carbuncles & furunculosis", "Gangrene & septic phlegmon", "Septic insect bites"],
        ["Unerträgliche, brennende Schmerzen wie von glühenden Kohlen", "Karbunkel mit schwärzlichem Kern", "Schneller Verfall der Kräfte"],
        ["Unbearable burning pain as from glowing coals", "Carbuncles with blackish center", "Rapid sinking of strength"],
        "Todesangst, Delirium mit Hinfälligkeit, Apathie.", "Fear of death, low delirium, apathy.",
        ["Warme Anwendungen"], ["Warm applications"],
        ["Geringste Berührung", "Kälte", "Nachts"], ["Slightest touch", "Cold", "Night"],
        ["Haut & Unterhaut", "Blut & Lymphe", "Gefäße"], ["Arsenicum album", "Tarentula cubensis", "Lachesis"], ["karbunkel", "milzbrand", "brennen wie feuer", "sepsis"]
    ),
    (
        "antimonium-arsenicosum", "Antimonium arsenicosum", "mineral", ["hering"], False, 3,
        "Antimonarsenit", "Antimony Arsenite",
        "Chemische Verbindung aus Antimon und Arsenik.", "Chemical compound of antimony and arsenic.",
        "Schwere Lungenentzündung bei geschwächten Patienten mit reichlichem Rasselgeräusch und Kollapsneigung.",
        "Severe pulmonary catarrh with copious rattling and cardiac failure in exhausted subjects.",
        ["Pleuropneumonie & Lungenödem", "Senile Bronchitis", "Asthma cardiale"],
        ["Pleuropneumonia & pulmonary edema", "Senile bronchitis", "Cardiac asthma"],
        ["Ausgeprägtes feuchtes Rasseln auf beiden Lungen", "Kalte Schweiße und Schwäche", "Erstickungsnot zwingt zum Aufsitzen"],
        ["Copious moist rattling in both lungs", "Cold sweats and extreme debility", "Suffocation compels sitting upright"],
        "Todesangst bei Atemnot, unruhig und erschöpft.", "Anxiety of death with suffocation, restless yet weak.",
        ["Aufrechtes Sitzen", "Frische kühle Luft"], ["Sitting erect", "Cool open air"],
        ["Liegen", "Wärme", "Geringe Anstrengung"], ["Lying down", "Warmth", "Slight exertion"],
        ["Lunge & Alveolen", "Herz-Kreislauf-System"], ["Antimonium tart", "Arsenicum album", "Carbo veg"], ["antimonarsenit", "lungenödem", "rasseln", "senile bronchitis"]
    ),
    (
        "antimonium-iodatum", "Antimonium iodatum", "mineral", ["hering"], False, 3,
        "Antimoniodid", "Antimony Iodide",
        "Verbindung aus Antimon und Iod.", "Compound of antimony and iodine.",
        "Subakute Bronchitis mit süßlich-gelblichem Auswurf, Abmagerung und nächtlichen Schweißen.",
        "Subacute bronchitis with sweetish yellowish expectoration, wasting, and night sweats.",
        ["Chronischer Husten & Pleuritis", "Bronchiektasen", "Scrophulose der Drüsen"],
        ["Chronic cough & pleurisy", "Bronchiectasis", "Glandular scrofula"],
        ["Gelblich-zäher Schleim mit süßlichem Geschmack", "Abmagerung trotz Appetit", "Trockener Kitzelhusten im Hals"],
        ["Yellowish sticky expectoration with sweetish taste", "Emaciation despite eating", "Tickling dry cough in throat"],
        "Reizbar, weinerlich, will allein sein.", "Irritable, weeping, wishes to be alone.",
        ["Frische kühle Luft"], ["Cool fresh air"],
        ["Warme Räume", "Anstrengung", "Nachts"], ["Warm rooms", "Exertion", "Night"],
        ["Bronchien & Lunge", "Lymphdrüsen"], ["Kali bich", "Iodium", "Stannum"], ["antimoniodid", "bronchitis", "abmagerung", "nachtschweiß"]
    ),
    (
        "antimonium-sulfuratum-aurantiacum", "Antimonium sulfuratum aurantiacum", "mineral", ["kent", "hering"], False, 3,
        "Goldschwefel", "Golden Sulfide of Antimony",
        "Amorphes Antimontrisulfid mit Schwefel.", "Amorphous antimony trisulfide.",
        "Zäher Schleim in Bronchien und Nase, rasselnder Husten und Hautjucken.",
        "Tough mucus in bronchi and nose, rattling cough with acne and pruritus.",
        ["Chronischer Bronchialkatarrh", "Akne pustulosa", "Rhinitis sicca mit Verkrustung"],
        ["Chronic bronchial catarrh", "Acne pustulosa", "Crusty dry rhinitis"],
        ["Schleim ist gelb, zäh und schwer aufzuhusten", "Juckende Pusteln auf Brust und Rücken", "Gefühl von Fülle in den Bronchien"],
        ["Phlegm yellow, sticky, difficult to raise", "Itching pustules on chest and back", "Sensation of fullness in chest"],
        "Träge, mürrisch am Morgen.", "Sluggish, irritable in morning.",
        ["Frische Luft", "Aufrechtes Sitzen"], ["Fresh air", "Sitting upright"],
        ["Liegen", "Warme feuchte Luft"], ["Lying down", "Warm humid air"],
        ["Bronchien", "Hautdrüsen", "Nase"], ["Antimonium tart", "Sulfur", "Kali bich"], ["goldschwefel", "zäher auswurf", "akne", "pusteln"]
    ),
    (
        "apium-graveolens", "Apium graveolens", "plant", ["hering"], False, 3,
        "Echter Sellerie", "Celery",
        "Frische oberirdische Teile und Samen von Apium graveolens.", "Fresh seeds and tops of Apium graveolens.",
        "Nervöse Unruhe, Kopfschmerzen von hinten nach vorn und Urtikaria mit Juckreiz.",
        "Nervous fidgets, headaches moving forward, and urticaria with intense itching.",
        ["Urtikaria & Nesselsucht", "Nervöse Schlaflosigkeit", "Zystitis mit Harndrang"],
        ["Urticaria & nettle rash", "Nervous insomnia", "Cystitis with urge"],
        ["Kopfschmerz schießt vom Hinterkopf bis über die Augen", "Nesselsucht nach Kälteeinwirkung", "Zucken der Gliedmaßen beim Einschlafen"],
        ["Headache shooting from occiput forward over eyes", "Urticaria after exposure to cold", "Twitching of limbs on dropping to sleep"],
        "Rastlose Unruhe, kann die Beine nicht ruhig halten.", "Restless fidgets, cannot keep legs still.",
        ["Bewegung", "Wärme"], ["Motion", "Warmth"],
        ["Ruhe", "Kälte", "Nachts"], ["Rest", "Cold", "Night"],
        ["Harnblase", "Haut", "Zentrales Nervensystem"], ["Urtica urens", "Apis", "Zincum"], ["sellerie", "nesselsucht", "unruhe", "nervöse beine"]
    ),
    (
        "apocynum-androsaemifolium", "Apocynum androsaemifolium", "plant", ["hering"], False, 3,
        "Fliegenfängerkraut", "Spreading Dogbane",
        "Frische Wurzel von Apocynum androsaemifolium.", "Fresh root of Apocynum androsaemifolium.",
        "Gelenkschmerzen mit Steifigkeit, profusem Schweiß und Schwere in den Extremitäten.",
        "Arthralgia with stiffness, profuse sweat, and heaviness of limbs.",
        ["Rheumatismus der großen Gelenke", "Ischialgie mit Schwellung", "Krampfadern an den Beinen"],
        ["Rheumatism of large joints", "Sciatica with swelling", "Varicose veins of legs"],
        ["Schmerz wechselt von Gelenk zu Gelenk", "Schwellung der Füße mit Schweregefühl", "Profuser kalter Schweiß"],
        ["Pains wandering from joint to joint", "Swelling of feet with heaviness", "Profuse cold sweating"],
        "Niedergeschlagen, schläfrig, willenlos.", "Depressed, drowsy, lack of energy.",
        ["Sanfte Bewegung", "Trockene Wärme"], ["Gentle motion", "Dry warmth"],
        ["Ruhe", "Nässe und Kälte"], ["Rest", "Damp cold"],
        ["Gelenke", "Gefäße", "Vegetativum"], ["Bryonia", "Rhus tox", "Pulsatilla"], ["fliegenfängerkraut", "rheuma", "wanderschmerz", "gelenke"]
    ),
    (
        "apomorphinum", "Apomorphinum", "mineral", ["hering"], False, 3,
        "Apomorphin", "Apomorphine",
        "Potenziertes Apomorphinhydrochlorid.", "Potentized apomorphine hydrochloride.",
        "Heftigstes reflexartiges Erbrechen ohne Vorwarnung, Seekrankheit und Schwangerschaftserbrechen.",
        "Violent reflex vomiting with sudden projectile ejection, seasickness, and pregnancy nausea.",
        ["Unstillbares Erbrechen", "Kinetose & Seekrankheit", "Schwangerschaftserbrechen (Hyperemesis)"],
        ["Incessant vomiting", "Motion sickness & seasickness", "Hyperemesis gravidarum"],
        ["Plötzliches Erbrechen ohne vorherige Übelkeit", "Gefühl von Taumel und Schwäche im Kopf", "Erbrechen von Schleim und Speise resten"],
        ["Sudden projectile vomiting without preceding nausea", "Giddiness and faintness in head", "Vomiting of mucus and food"],
        "Benommen, ängstlich durch ständiges Würgen.", "Stupefied, anxious from constant retching.",
        ["Ruhiges Liegen mit geschlossenen Augen"], ["Quiet lying with eyes closed"],
        ["Bewegung des Schiffes oder Wagens", "Aufrichten", "Gerüche"], ["Motion of ship or carriage", "Rising up", "Smells"],
        ["Brechzentrum in der Medulla", "Magen-Darm-Trakt"], ["Ipecacuanha", "Tabacum", "Cocculus"], ["apomorphin", "erbrechen", "seekrankheit", "reiseübelkeit"]
    ),
    (
        "aralia-racemosa", "Aralia racemosa", "plant", ["hering"], False, 2,
        "Amerikanische Narde", "American Spikenard",
        "Frische Wurzel von Aralia racemosa.", "Fresh root of Aralia racemosa.",
        "Asthmaanfälle kurz nach dem Einschlafen (um Mitternacht), mit Pfeifen und trockenem Husten.",
        "Asthmatic attacks coming on immediately after falling asleep (around midnight), with wheezing.",
        ["Asthma bronchiale nachts", "Heuschnupfen mit Asthma", "Kitzelhusten im Kehlkopf"],
        ["Nocturnal asthma", "Hay fever with asthma", "Tickling laryngeal cough"],
        ["Wacht nach erstem Schlaf (23-24 Uhr) mit Erstickungsgefühl auf", "Lautes Pfeifen und Rasseln beim Ausatmen", "Wässriger, brennender Schnupfen mit Niesen"],
        ["Awakens after first sleep (11 PM-midnight) suffocating", "Loud wheezing and whistling on expiration", "Watery excoriating coryza with sneezing"],
        "Ängstlich beim Erwachen aus dem Schlaf, fürchtet das Ersticken.", "Anxious on waking from sleep, fears suffocation.",
        ["Aufrechtes Sitzen und Vorbeugen", "Frische Luft"], ["Sitting erect and bending forward", "Fresh air"],
        ["Hinlegen", "Schlafbeginn um Mitternacht", "Zugluft"], ["Lying down", "Falling asleep at midnight", "Drafts"],
        ["Bronchialbaum", "Kehlkopf", "Nasenschleimhaut"], ["Sambucus", "Lachesis", "Arsenicum album"], ["asthma", "mitternacht", "aufwachen mit erstickung", "aralia"]
    ),
    (
        "aranea-diadema", "Aranea diadema", "animal", ["hering"], False, 2,
        "Kreuzspinne", "Diadem Spider",
        "Ganze lebende Kreuzspinne (Araneus diadematus).", "Whole living diadem spider.",
        "Extreme Kälteempfindlichkeit, Frösteln bis ins Knochenmark, Verschlimmerung an feuchten Orten.",
        "Extreme chilliness, icy coldness penetrating to the bone marrow, worse in damp rainy weather.",
        ["Malariales Frösteln & Wechselfieber", "Knochenneuralgien & Zahnschmerzen", "Blutungen aus allen Körperöffnungen"],
        ["Malarial chilliness & intermittent fever", "Bone neuralgia & toothache", "Hemorrhages from orifices"],
        ["Gefühl, als seien die Knochen aus Eis gemacht", "Täglich pünktlich zur selben Stunde auftretendes Frösteln", "Gefühl von Vergrößerung und Schwellung der Hände"],
        ["Sensation as if bones were made of ice", "Chill returning precisely at same hour daily", "Sensation of enlargement and swelling of hands"],
        "Gleichgültig, apathisch vor Kälte.", "Indifferent, apathetic from chilliness.",
        ["Trockenes warmes Wetter", "Rauch von Tabak"], ["Warm dry weather", "Tobacco smoking"],
        ["Nässe & Feuchtigkeit", "Regenwetter", "Baden"], ["Dampness & humidity", "Rainy weather", "Bathing"],
        ["Vegetatives Nervensystem", "Knochen & Knochenmark", "Blut"], ["China", "Cedron", "Dulcamara"], ["kreuzspinne", "knochenkälte", "wechselfieber", "periodizität"]
    ),
    (
        "argentum-cyanatum", "Argentum cyanatum", "mineral", ["hering"], False, 3,
        "Silberzyanid", "Silver Cyanide",
        "Chemische Verbindung aus Silber und Blausäure.", "Chemical compound of silver and hydrocyanic acid.",
        "Krämpfe, Angina pectoris mit Erstickungsanfällen und brennenden Kehlkopfschmerzen.",
        "Convulsive spasms, angina pectoris with suffocative attacks and burning in larynx.",
        ["Laryngitis mit Aphonie", "Angina pectoris", "Krampfartige Hustenanfälle"],
        ["Laryngitis with aphonia", "Angina pectoris", "Suffocative cough attacks"],
        ["Stimmverlust nach Singen oder Sprechen", "Engegefühl und Zusammenschnürung in der Brust", "Brennender Schmerz in der Luftröhre"],
        ["Loss of voice after vocal strain", "Constriction and tightness in chest", "Burning in trachea"],
        "Schreckhaft, Todesfurcht bei pectangionösen Anfällen.", "Fearful of death during cardiac attacks.",
        ["Ruhige Lage", "Frische Luft"], ["Quiet rest", "Fresh air"],
        ["Sprechen", "Kälte", "Anstrengung"], ["Speaking", "Cold", "Exertion"],
        ["Kehlkopf", "Herzkranzgefäße", "ZNS"], ["Argentum nitricum", "Hydrocyanic acid", "Spongia"], ["silberzyanid", "angina pectoris", "stimmlosigkeit", "krampf"]
    ),
    (
        "argentum-iodatum", "Argentum iodatum", "mineral", ["hering"], False, 3,
        "Silberiodid", "Silver Iodide",
        "Synthetische Verbindung aus Silber und Iod.", "Synthetic compound of silver and iodine.",
        "Chronische Drüsenschwellungen, Kehlkopfentzündung bei Sängern und Abmagerung.",
        "Chronic glandular hypertrophy, singer's laryngitis, and progressive emaciation.",
        ["Sängerknötchen & Laryngitis", "Struma & Lymphadenitis", "Katarrhe mit zähem Schleim"],
        ["Singer's nodes & laryngitis", "Goiter & lymphadenitis", "Catarrh with sticky phlegm"],
        ["Heiserkeit von Rednern und Sängern mit zähem Schleim", "Schilddrüsenvergrößerung mit Herzklopfen", "Gewichtsverlust trotz gutem Essen"],
        ["Hoarseness in vocalists with tenacious mucus", "Thyroid enlargement with tachycardia", "Weight loss despite good appetite"],
        "Gehetzt, unruhig, eilig bei allen Tätigkeiten.", "Hurried, restless, anxious disposition.",
        ["Kühle frische Luft", "Kaltes Waschen"], ["Cool open air", "Cold washing"],
        ["Warme Räume", "Stimmanstrengung"], ["Warm rooms", "Vocal exertion"],
        ["Kehlkopf & Stimmbänder", "Schilddrüse", "Lymphe"], ["Argentum met", "Iodium", "Spongia"], ["silberiodid", "sänger", "heiserkeit", "struma"]
    ),
    (
        "aristolochia-clematitis", "Aristolochia clematitis", "plant", ["hering"], False, 2,
        "Osterluzei", "Birthwort",
        "Frische blühende Pflanze von Aristolochia clematitis.", "Fresh flowering plant of Aristolochia clematitis.",
        "Harnwegsinfekte mit Tenesmus, Fluor albus und venöse Stauungen im kleinen Becken.",
        "Urinary tract infections with tenesmus, leucorrhea, and pelvic venous congestion.",
        ["Zystitis mit ständigem Harndrang", "Fluor albus & Kolpitis", "Menstruationsstörungen"],
        ["Cystitis with constant urging", "Leucorrhea & vaginitis", "Menstrual irregularity"],
        ["Ständiger schmerzhafter Harndrang, Urin brennt", "Gelblicher, wundmachender Ausfluss", "Schweregefühl im Unterleib wie Herabdrängen"],
        ["Constant painful urging with burning urine", "Yellowish excoriating leucorrhea", "Bearing down sensation in lower abdomen"],
        "Reizbar vor der Menstruation, weinerlich.", "Irritable before menses, tearful.",
        ["Bewegung im Freien", "Wärme"], ["Walking in open air", "Warmth"],
        ["Kälte & Nässe", "Vor der Periode", "Sitzen"], ["Cold and wet", "Before menses", "Sitting"],
        ["Harnblase", "Weibliche Genitalien", "Venen"], ["Pulsatilla", "Sepia", "Cantharis"], ["osterluzei", "blasenentzündung", "ausfluss", "unterleib"]
    )
]

print(f"Catalog A-F part contains {len(REMEDIES_A_F)} remedies.")
