# scripts/classical_remedy_roster.py
"""
Complete roster of classical remedies from:
- Samuel Hahnemann (Materia Medica Pura & Chronic Diseases)
- James Tyler Kent (Lectures on Homeopathic Materia Medica)
- Constantine Hering (Guiding Symptoms of Our Materia Medica)
"""

# Master catalog of classical remedies: (latin_name, id, category, authors_list, common_de, common_en)
# authors: 'h' = hahnemann, 'k' = kent, 'he' = hering
CLASSICAL_ROSTER = [
    ("Abies canadensis", "abies-canadensis", "plant", ["kent", "hering"], "Kanadische Hemlocktanne", "Hemlock Spruce"),
    ("Abies nigra", "abies-nigra", "plant", ["kent", "hering"], "Schwarzfichte", "Black Spruce"),
    ("Abrotanum", "abrotanum", "plant", ["kent", "hering"], "Eberraute", "Southernwood"),
    ("Absinthium", "absinthium", "plant", ["hering"], "Wermut", "Wormwood"),
    ("Aceticum acidum", "aceticum-acidum", "acid", ["kent", "hering"], "Essigsäure", "Acetic Acid"),
    ("Aconitum napellus", "aconitum", "plant", ["hahnemann", "kent", "hering"], "Blauer Eisenhut", "Monkshood"),
    ("Actaea racemosa", "cimicifuga", "plant", ["kent", "hering"], "Traubensilberkerze", "Black Cohosh"),
    ("Actaea spicata", "actaea-spicata", "plant", ["kent", "hering"], "Christophskraut", "Baneberry"),
    ("Adonis vernalis", "adonis-vernalis", "plant", ["hering"], "Frühlings-Adonisröschen", "Pheasant's Eye"),
    ("Aesculus hippocastanum", "aesculus-hippocastanum", "plant", ["kent", "hering"], "Rosskastanie", "Horse Chestnut"),
    ("Aethusa cynapium", "aethusa-cynapium", "plant", ["kent", "hering"], "Hundspetersilie", "Fool's Parsley"),
    ("Agaricus muscarius", "agaricus", "plant", ["hahnemann", "kent", "hering"], "Fliegenpilz", "Fly Agaric"),
    ("Agnus castus", "agnus-castus", "plant", ["hahnemann", "kent", "hering"], "Mönchspfeffer", "Chaste Tree"),
    ("Ailanthus glandulosa", "ailanthus-glandulosa", "plant", ["kent", "hering"], "Götterbaum", "Tree of Heaven"),
    ("Aletris farinosa", "aletris-farinosa", "plant", ["kent", "hering"], "Mehlige Sternwurzel", "Star Grass"),
    ("Allium cepa", "allium-cepa", "plant", ["kent", "hering"], "Küchenzwiebel", "Red Onion"),
    ("Allium sativum", "allium-sativum", "plant", ["kent", "hering"], "Knoblauch", "Garlic"),
    ("Aloe socotrina", "aloe-socotrina", "plant", ["hahnemann", "kent", "hering"], "Echte Aloe", "Socotrine Aloe"),
    ("Alstonia scholaris", "alstonia-scholaris", "plant", ["hering"], "Dita-Rinde", "Dita Bark"),
    ("Alumina", "alumina", "mineral", ["hahnemann", "kent", "hering"], "Tonerde", "Argilla / Aluminium Oxide"),
    ("Alumina phosphorica", "alumina-phosphorica", "mineral", ["kent"], "Aluminiumphosphat", "Aluminium Phosphate"),
    ("Alumina silicata", "alumina-silicata", "mineral", ["kent"], "Aluminiumsilikat", "Aluminium Silicate"),
    ("Ambra grisea", "ambra", "animal", ["hahnemann", "kent", "hering"], "Graue Ambra", "Ambergris"),
    ("Ambrosia artemisiifolia", "ambrosia", "plant", ["hering"], "Beifußblättrige Ambrosie", "Ragweed"),
    ("Ammoniacum gummi", "ammoniacum", "plant", ["hering"], "Ammoniakgummi", "Gum Ammoniac"),
    ("Ammonium benzoicum", "ammonium-benzoicum", "mineral", ["hering"], "Ammoniumbenzoat", "Ammonium Benzoate"),
    ("Ammonium bromatum", "ammonium-bromatum", "mineral", ["hering"], "Ammoniumbromid", "Ammonium Bromide"),
    ("Ammonium carbonicum", "ammonium-carbonicum", "mineral", ["hahnemann", "kent", "hering"], "Hirschhornsalz", "Ammonium Carbonate"),
    ("Ammonium causticum", "ammonium-causticum", "mineral", ["hering"], "Salmiakgeist", "Ammonia Water"),
    ("Ammonium iodatum", "ammonium-iodatum", "mineral", ["hering"], "Ammoniumiodid", "Ammonium Iodide"),
    ("Ammonium muriaticum", "ammonium-muriaticum", "mineral", ["hahnemann", "kent", "hering"], "Salmiaksalz", "Ammonium Chloride"),
    ("Ammonium phosphoricum", "ammonium-phosphoricum", "mineral", ["kent"], "Ammoniumphosphat", "Ammonium Phosphate"),
    ("Ammonium valerianicum", "ammonium-valerianicum", "mineral", ["hering"], "Ammoniumvalerianat", "Ammonium Valerianate"),
    ("Amylenum nitrosum", "amylenum-nitrosum", "mineral", ["hering"], "Amylnitrit", "Amyl Nitrite"),
    ("Anacardium orientale", "anacardium", "plant", ["hahnemann", "kent", "hering"], "Elefantenlausbaum", "Marking Nut"),
    ("Anagallis arvensis", "anagallis", "plant", ["hering"], "Ackergauchheil", "Scarlet Pimpernel"),
    ("Angustura vera", "angustura-vera", "plant", ["hahnemann", "hering"], "Echte Angusturarinde", "Angostura Bark"),
    ("Anhalonium lewinii", "anhalonium", "plant", ["hering"], "Peyote-Kaktus", "Peyote"),
    ("Anisum stellatum", "anisum-stellatum", "plant", ["hahnemann", "hering"], "Sternanis", "Star Anise"),
    ("Anthemis nobilis", "anthemis-nobilis", "plant", ["hering"], "Römische Kamille", "Roman Chamomile"),
    ("Anthracinum", "anthracinum", "nosode", ["hering"], "Milzbrand-Nosode", "Anthrax Nosode"),
    ("Antimonium arsenicosum", "antimonium-arsenicosum", "mineral", ["hering"], "Antimonarsenit", "Antimony Arsenite"),
    ("Antimonium crudum", "antimonium-crudum", "mineral", ["hahnemann", "kent", "hering"], "Schwarzer Spießglanz", "Black Antimony Sulfide"),
    ("Antimonium iodatum", "antimonium-iodatum", "mineral", ["hering"], "Antimoniodid", "Antimony Iodide"),
    ("Antimonium sulfuratum aurantiacum", "antimonium-sulfuratum-aurantiacum", "mineral", ["kent", "hering"], "Goldschwefel", "Golden Sulfide of Antimony"),
    ("Antimonium tartaricum", "antimonium-tartaricum", "mineral", ["hahnemann", "kent", "hering"], "Brechweinstein", "Tartar Emetic"),
    ("Apis mellifica", "apis", "animal", ["kent", "hering"], "Honigbiene", "Honey Bee"),
    ("Apium graveolens", "apium-graveolens", "plant", ["hering"], "Echter Sellerie", "Celery"),
    ("Apocynum androsaemifolium", "apocynum-androsaemifolium", "plant", ["hering"], "Fliegenfängerkraut", "Spreading Dogbane"),
    ("Apocynum cannabinum", "apocynum-cannabinum", "plant", ["kent", "hering"], "Indianischer Hanf", "Indian Hemp"),
    ("Apomorphinum", "apomorphinum", "mineral", ["hering"], "Apomorphin", "Apomorphine"),
    ("Aralia racemosa", "aralia-racemosa", "plant", ["hering"], "Amerikanische Narde", "American Spikenard"),
    ("Aranea diadema", "aranea-diadema", "animal", ["hering"], "Kreuzspinne", "Diadem Spider"),
    ("Argentum cyanatum", "argentum-cyanatum", "mineral", ["hering"], "Silberzyanid", "Silver Cyanide"),
    ("Argentum iodatum", "argentum-iodatum", "mineral", ["hering"], "Silberiodid", "Silver Iodide"),
    ("Argentum metallicum", "argentum-metallicum", "mineral", ["hahnemann", "kent", "hering"], "Reines Silber", "Silver"),
    ("Argentum nitricum", "argentum-nitricum", "mineral", ["kent", "hering"], "Silbernitrat / Höllenstein", "Silver Nitrate"),
    ("Aristolochia clematitis", "aristolochia", "plant", ["hering"], "Osterluzei", "Birthwort"),
    ("Arnica montana", "arnica", "plant", ["hahnemann", "kent", "hering"], "Bergwohlverleih", "Leopard's Bane"),
    ("Arsenicum album", "arsenicum-album", "mineral", ["hahnemann", "kent", "hering"], "Weißer Arsenik", "White Arsenic"),
    ("Arsenicum bromatum", "arsenicum-bromatum", "mineral", ["hering"], "Arsenikbromid", "Arsenic Bromide"),
    ("Arsenicum hydrogenisatum", "arsenicum-hydrogenisatum", "mineral", ["kent", "hering"], "Arsenwasserstoff", "Arsine"),
    ("Arsenicum iodatum", "arsenicum-iodatum", "mineral", ["kent", "hering"], "Arsentriiodid", "Arsenic Triiodide"),
    ("Arsenicum metallicum", "arsenicum-metallicum", "mineral", ["kent", "hering"], "Metallisches Arsen", "Metallic Arsenic"),
    ("Arsenicum sulfuratum flavum", "arsenicum-sulfuratum-flavum", "mineral", ["kent", "hering"], "Auripigment", "Yellow Sulfide of Arsenic"),
    ("Arsenicum sulfuratum rubrum", "arsenicum-sulfuratum-rubrum", "mineral", ["hering"], "Realgar", "Red Sulfide of Arsenic"),
    ("Artemisia vulgaris", "artemisia-vulgaris", "plant", ["hering"], "Gemeiner Beifuß", "Mugwort"),
    ("Arum dracontium", "arum-dracontium", "plant", ["hering"], "Drachenwurz", "Green Dragon"),
    ("Arum maculatum", "arum-maculatum", "plant", ["hering"], "Gefleckter Aronstab", "Cuckoo Pint"),
    ("Arum triphyllum", "arum-triphyllum", "plant", ["kent", "hering"], "Dreiblättriger Aronstab", "Jack-in-the-Pulpit"),
    ("Arundo mauritanica", "arundo-mauritanica", "plant", ["hering"], "Italienisches Pfahlrohr", "Reed"),
    ("Asa foetida", "asa-foetida", "plant", ["hahnemann", "kent", "hering"], "Stinkasant / Teufelsdreck", "Asafetida"),
    ("Asarum europaeum", "asarum", "plant", ["hahnemann", "kent", "hering"], "Europäische Haselwurz", "Wild Ginger"),
    ("Asclepias cornuti", "asclepias-cornuti", "plant", ["hering"], "Syrische Seidenpflanze", "Milkweed"),
    ("Asclepias tuberosa", "asclepias-tuberosa", "plant", ["hering"], "Knollige Seidenpflanze", "Pleurisy Root"),
    ("Asparagus officinalis", "asparagus", "plant", ["hering"], "Gemüsespargel", "Garden Asparagus"),
    ("Astacus fluviatilis", "astacus-fluviatilis", "animal", ["hering"], "Flusskrebs", "Crawfish"),
    ("Asterias rubens", "asterias-rubens", "animal", ["kent", "hering"], "Roter Seestern", "Starfish"),
    ("Atropinum sulfuricum", "atropinum", "plant", ["hering"], "Atropinsulfat", "Atropine Sulfate"),
    ("Aurum arsenicosum", "aurum-arsenicosum", "mineral", ["kent"], "Goldarsenit", "Gold Arsenite"),
    ("Aurum bromatum", "aurum-bromatum", "mineral", ["hering"], "Goldbromid", "Gold Bromide"),
    ("Aurum iodatum", "aurum-iodatum", "mineral", ["kent", "hering"], "Goldiodid", "Gold Iodide"),
    ("Aurum metallicum", "aurum-metallicum", "mineral", ["hahnemann", "kent", "hering"], "Reines Blattgold", "Metallic Gold"),
    ("Aurum muriaticum", "aurum-muriaticum", "mineral", ["kent", "hering"], "Goldchlorid", "Gold Chloride"),
    ("Aurum muriaticum kalinatum", "aurum-muriaticum-kalinatum", "mineral", ["hering"], "Kaliumgoldchlorid", "Potassium Gold Chloride"),
    ("Aurum muriaticum natronatum", "aurum-muriaticum-natronatum", "mineral", ["kent", "hering"], "Natriumgoldchlorid", "Sodium Chloroaurate"),
    ("Aurum sulfuratum", "aurum-sulfuratum", "mineral", ["kent", "hering"], "Goldsulfid", "Gold Sulfide"),
    ("Badiaga", "badiaga", "animal", ["kent", "hering"], "Süßwasserschwamm", "Fresh-Water Sponge"),
    ("Balsamum peruvianum", "balsamum-peruvianum", "plant", ["hering"], "Perubalsam", "Balsam of Peru"),
    ("Baptisia tinctoria", "baptisia", "plant", ["kent", "hering"], "Wilder Indigo", "Wild Indigo"),
    ("Baryta acetica", "baryta-acetica", "mineral", ["hahnemann", "hering"], "Bariumacetat", "Barium Acetate"),
    ("Baryta carbonica", "baryta-carbonica", "mineral", ["hahnemann", "kent", "hering"], "Bariumcarbonat", "Barium Carbonate"),
    ("Baryta iodata", "baryta-iodata", "mineral", ["kent", "hering"], "Bariumiodid", "Barium Iodide"),
    ("Baryta muriatica", "baryta-muriatica", "mineral", ["kent", "hering"], "Bariumchlorid", "Barium Chloride"),
    ("Belladonna", "belladonna", "plant", ["hahnemann", "kent", "hering"], "Tollkirsche", "Deadly Nightshade"),
    ("Bellis perennis", "bellis-perennis", "plant", ["hering"], "Gänseblümchen", "Daisy"),
    ("Benzinum", "benzinum", "mineral", ["hering"], "Petrolether", "Benzene"),
    ("Benzinum dinitricum", "benzinum-dinitricum", "mineral", ["hering"], "Dinitrobenzol", "Dinitrobenzene"),
    ("Benzoicum acidum", "benzoic-acid", "acid", ["kent", "hering"], "Benzoesäure", "Benzoic Acid"),
    ("Berberis aquifolium", "berberis-aquifolium", "plant", ["hering"], "Mahonie", "Mountain Grape"),
    ("Berberis vulgaris", "berberis", "plant", ["kent", "hering"], "Sauerdorn / Berberitze", "Barberry"),
    ("Bismuthum subnitricum", "bismuthum", "mineral", ["hahnemann", "kent", "hering"], "Wismutsubnitrat", "Bismuth Subnitrate"),
    ("Blatta americana", "blatta-americana", "animal", ["hering"], "Amerikanische Kakerlake", "American Cockroach"),
    ("Blatta orientalis", "blatta-orientalis", "animal", ["hering"], "Orientalische Kakerlake", "Indian Cockroach"),
    ("Boldo", "boldo", "plant", ["hering"], "Boldoblätter", "Boldo"),
    ("Borax veneta", "borax", "mineral", ["hahnemann", "kent", "hering"], "Natriumborat", "Borax"),
    ("Bothrops lanceolatus", "bothrops", "animal", ["hering"], "Lanzenotter", "Yellow Viper"),
    ("Bovista lycoperdon", "bovista", "plant", ["hahnemann", "kent", "hering"], "Warzen-Bovist", "Puffball"),
    ("Brachyglottis repens", "brachyglottis", "plant", ["hering"], "Puka-Puka", "Puka-Puka"),
    ("Bromium", "bromium", "mineral", ["kent", "hering"], "Reines Brom", "Bromine"),
    ("Bryonia alba", "bryonia", "plant", ["hahnemann", "kent", "hering"], "Weiße Zaunrübe", "White Bryony"),
    ("Bufo rana", "bufo-rana", "animal", ["kent", "hering"], "Erdkröte", "Toad Poison"),
    ("Cactus grandiflorus", "cactus", "plant", ["kent", "hering"], "Königin der Nacht", "Night-Blooming Cereus"),
    ("Cadmium metallicum", "cadmium-metallicum", "mineral", ["hering"], "Metallisches Cadmium", "Cadmium Metal"),
    ("Cadmium sulfuratum", "cadmium-sulfuratum", "mineral", ["kent", "hering"], "Cadmiumsulfid", "Cadmium Sulfate"),
    ("Cainca", "cainca", "plant", ["hering"], "Kainkawurzel", "Cahinca"),
    ("Caladium seguinum", "caladium", "plant", ["kent", "hering"], "Schweigrohr", "American Arum"),
    ("Calcarea arsenicosa", "calcarea-arsenicosa", "mineral", ["kent", "hering"], "Calciumarsenit", "Calcium Arsenite"),
    ("Calcarea carbonica", "calcarea-carbonica", "mineral", ["hahnemann", "kent", "hering"], "Austernschalenkalk", "Calcium Carbonate"),
    ("Calcarea fluorica", "calcarea-fluorica", "mineral", ["kent", "hering"], "Flussspat", "Calcium Fluoride"),
    ("Calcarea hypophosphorosa", "calcarea-hypophosphorosa", "mineral", ["hering"], "Calciumhypophosphit", "Calcium Hypophosphite"),
    ("Calcarea iodata", "calcarea-iodata", "mineral", ["kent", "hering"], "Calciumiodid", "Calcium Iodide"),
    ("Calcarea phosphorica", "calcarea-phosphorica", "mineral", ["kent", "hering"], "Calciumphosphat", "Calcium Phosphate"),
    ("Calcarea silicata", "calcarea-silicata", "mineral", ["kent"], "Calciumsilikat", "Calcium Silicate"),
    ("Calcarea sulfurica", "calcarea-sulfurica", "mineral", ["kent", "hering"], "Gips / Calciumsulfat", "Calcium Sulfate / Gypsum"),
    ("Calendula officinalis", "calendula", "plant", ["kent", "hering"], "Ringelblume", "Marigold"),
    ("Calotropis gigantea", "calotropis", "plant", ["hering"], "Mudar-Rinde", "Madar Bark"),
    ("Camphora", "camphora", "plant", ["hahnemann", "kent", "hering"], "Kampfer", "Camphor"),
    ("Cannabis indica", "cannabis-indica", "plant", ["kent", "hering"], "Indischer Hanf", "Indian Hemp"),
    ("Cannabis sativa", "cannabis-sativa", "plant", ["hahnemann", "kent", "hering"], "Echter Hanf", "Hemp"),
    ("Cantharis vesicatoria", "cantharis", "animal", ["hahnemann", "kent", "hering"], "Spanische Fliege", "Spanish Fly"),
    ("Capsicum annuum", "capsicum", "plant", ["hahnemann", "kent", "hering"], "Spanischer Pfeffer", "Cayenne Pepper"),
    ("Carbo animalis", "carbo-animalis", "animal", ["hahnemann", "kent", "hering"], "Tierkohle", "Animal Charcoal"),
    ("Carbo vegetabilis", "carbo-vegetabilis", "plant", ["hahnemann", "kent", "hering"], "Holzkohle", "Vegetable Charcoal"),
    ("Carbolicum acidum", "carbolic-acid", "acid", ["kent", "hering"], "Karbolsäure / Phenol", "Carbolic Acid / Phenol"),
    ("Carboneum sulfuratum", "carboneum-sulfuratum", "mineral", ["kent", "hering"], "Schwefelkohlenstoff", "Carbon Bisulfide"),
    ("Carduus marianus", "carduus-marianus", "plant", ["kent", "hering"], "Mariendistel", "St. Mary's Thistle"),
    ("Castanea vesca", "castanea-vesca", "plant", ["hering"], "Edelkastanie", "Chestnut"),
    ("Castor equi", "castor-equi", "animal", ["hering"], "Kastanienwarze des Pferdes", "Rudimentary Thumb of Horse"),
    ("Castoreum", "castoreum", "animal", ["hering"], "Bibergeil", "Beaver Secretion"),
    ("Caulophyllum thalictroides", "caulophyllum", "plant", ["kent", "hering"], "Frauenwurzel", "Blue Cohosh"),
    ("Causticum", "causticum", "mineral", ["hahnemann", "kent", "hering"], "Hahnemanns Ätzstoff", "Causticum Hahnemanni"),
    ("Ceanothus americanus", "ceanothus", "plant", ["kent", "hering"], "Säckelblume", "New Jersey Tea"),
    ("Cedron", "cedron", "plant", ["kent", "hering"], "Cedronbohne", "Cedron Seed"),
    ("Cenchris contortrix", "cenchris", "animal", ["kent", "hering"], "Kupferkopfschlange", "Copperhead Snake"),
    ("Centranthus ruber", "centranthus", "plant", ["hering"], "Spornblume", "Red Valerian"),
    ("Cepa", "cepa", "plant", ["kent", "hering"], "Zwiebel", "Onion"),
    ("Chamomylla vulgaris", "chamomilla", "plant", ["hahnemann", "kent", "hering"], "Echte Kamille", "German Chamomile"),
    ("Chelidonium majus", "chelidonium", "plant", ["hahnemann", "kent", "hering"], "Schöllkraut", "Greater Celandine"),
    ("Chenopodium anthelminticum", "chenopodium", "plant", ["hering"], "Wurmsamen-Drüsengänsefuß", "Wormseed"),
    ("Chimaphila umbellata", "chimaphila", "plant", ["hering"], "Dolden-Winterlieb", "Pipsissewa"),
    ("China officinalis", "cinchona", "plant", ["hahnemann", "kent", "hering"], "Chinarinde", "Peruvian Bark"),
    ("Chininum arsenicosum", "chininum-arsenicosum", "mineral", ["kent", "hering"], "Chininarsenit", "Quinine Arsenite"),
    ("Chininum sulfuricum", "chininum-sulfuricum", "mineral", ["kent", "hering"], "Chininsulfat", "Quinine Sulfate"),
    ("Chionanthus virginica", "chionanthus", "plant", ["hering"], "Schneeflockenblume", "Fringe Tree"),
    ("Chlorum", "chlorum", "mineral", ["hering"], "Chlorwasser", "Chlorine"),
    ("Cicuta virosa", "cicuta", "plant", ["hahnemann", "kent", "hering"], "Wasserschierling", "Water Hemlock"),
    ("Cimicifuga racemosa", "cimicifuga-racemosa", "plant", ["kent", "hering"], "Schwarze Schlangenwurzel", "Black Cohosh"),
    ("Cina maritima", "cina", "plant", ["hahnemann", "kent", "hering"], "Zitwersamen", "Wormseed"),
    ("Cinchona officinalis", "cinchona-officinalis", "plant", ["hahnemann", "kent", "hering"], "Chinarinde", "China Bark"),
    ("Cinnabaris", "cinnabaris", "mineral", ["hahnemann", "kent", "hering"], "Zinnober", "Red Mercuric Sulfide"),
    ("Cinnamomum ceylanicum", "cinnamomum", "plant", ["hering"], "Echter Zimt", "Cinnamon"),
    ("Cistus canadensis", "cistus-canadensis", "plant", ["kent", "hering"], "Kanadisches Sonnenröschen", "Rock Rose"),
    ("Clematis erecta", "clematis", "plant", ["hahnemann", "kent", "hering"], "Aufrechte Waldrebe", "Virgin's Bower"),
    ("Cobaltum metallicum", "cobaltum", "mineral", ["hering"], "Metallisches Kobalt", "Cobalt Metal"),
    ("Coca", "coca", "plant", ["kent", "hering"], "Kokastrauch", "Coca Leaves"),
    ("Cocculus indicus", "cocculus", "plant", ["hahnemann", "kent", "hering"], "Kockelskörner", "Indian Cockle"),
    ("Coccus cacti", "coccus-cacti", "animal", ["kent", "hering"], "Cochenillelaus", "Cochineal"),
    ("Coffea cruda", "coffea", "plant", ["hahnemann", "kent", "hering"], "Rohkaffee", "Raw Coffee"),
    ("Colchicum autumnale", "colchicum", "plant", ["hahnemann", "kent", "hering"], "Herbstzeitlose", "Meadow Saffron"),
    ("Collinsonia canadensis", "collinsonia", "plant", ["kent", "hering"], "Grießwurz / Steinwurzel", "Stone Root"),
    ("Colocynthis", "colocynthis", "plant", ["hahnemann", "kent", "hering"], "Koloquinte", "Bitter Apple"),
    ("Comocladia dentata", "comocladia", "plant", ["hering"], "Guao", "Guao"),
    ("Conium maculatum", "conium", "plant", ["hahnemann", "kent", "hering"], "Gefleckter Schierling", "Poison Hemlock"),
    ("Convallaria majalis", "convallaria", "plant", ["hering"], "Maiglöckchen", "Lily of the Valley"),
    ("Copaiva officinalis", "copaiva", "plant", ["hering"], "Kopaivabalsam", "Balsam of Copaiva"),
    ("Corallium rubrum", "corallium-rubrum", "animal", ["hering"], "Rote Koralle", "Red Coral"),
    ("Cornus circinata", "cornus-circinata", "plant", ["hering"], "Rundblättriger Hartriegel", "Round-Leaved Dogwood"),
    ("Cornus florida", "cornus-florida", "plant", ["hering"], "Blumen-Hartriegel", "Flowering Dogwood"),
    ("Crocus sativus", "crocus", "plant", ["hahnemann", "kent", "hering"], "Safran", "Saffron"),
    ("Crotalus horridus", "crotalus-horridus", "animal", ["kent", "hering"], "Wald-Klapperschlange", "Timber Rattlesnake"),
    ("Croton tiglium", "croton-tiglium", "plant", ["kent", "hering"], "Krotonölbaum", "Croton Oil Seed"),
    ("Cubeba officinalis", "cubeba", "plant", ["hering"], "Kubebenpfeffer", "Cubebs"),
    ("Cuprum aceticum", "cuprum-aceticum", "mineral", ["hahnemann", "hering"], "Kupferacetat", "Copper Acetate"),
    ("Cuprum arsenicosum", "cuprum-arsenicosum", "mineral", ["hering"], "Kupferarsenit", "Scheele's Green"),
    ("Cuprum metallicum", "cuprum-metallicum", "mineral", ["hahnemann", "kent", "hering"], "Metallisches Kupfer", "Metallic Copper"),
    ("Curare", "curare", "plant", ["kent", "hering"], "Pfeilgift Curare", "Arrow Poison"),
    ("Cyclamen europaeum", "cyclamen", "plant", ["hahnemann", "kent", "hering"], "Europäisches Alpenveilchen", "Sowbread")
]

print(f"Classical roster has {len(CLASSICAL_ROSTER)} entries in this catalog.")
