# -*- coding: utf-8 -*-
# Boericke remedies for Part 26 (remedies 133 to 165: K - Y)

PART26_REMEDIES = [
    {
        "id": "kalmia-latifolia",
        "latin": "Kalmia latifolia",
        "cat": "plant",
        "de_name": "Breitblättriger Berglorbeer",
        "en_name": "Mountain Laurel",
        "es_name": "Laurel de montaña",
        "fr_name": "Laurier des montagnes",
        "it_name": "Alloro di montagna",
        "el_name": "Κάλμια η πλατύφυλλος",
        "ru_name": "Кальмия широколистная",
        "de_essence": "Boerickes großes Herz- und Rheumatismusmittel: Rheumatische Schmerzen wandern von oben nach unten; heftiges Herzklopfen mit Bradykardie und wandernden Neuralgien.",
        "en_essence": "Boericke's hallmark cardiac and rheumatic remedy: pains shoot downward from above; acute rheumatism shifting to heart with bradycardia and fulgurant neuralgias.",
        "indications_de": ["Kardialer Rheumatismus & Endokarditis", "Rheumatische Schmerzen von oben nach unten", "Rechtseitige Fazialisneuralgie"],
        "indications_en": ["Cardiac rheumatism and valve lesions", "Rheumatism descending from above downwards", "Right-sided supraorbital and facial neuralgia"],
        "keynotes_de": ["Schmerzen schießen von den Hüften in die Füße hinab", "Herzklopfen mit langsamem, schwachem Puls (Bradykardie)", "Schmerzen wandern blitzartig und greifen das Herz an"],
        "keynotes_en": ["Pains shift rapidly, shooting from above downwards", "Heart action slow, weak, with fluttering palpitation", "Violent facial neuralgia worse sunrise to sunset"],
        "better_de": ["Fortgesetzte Bewegung"],
        "better_en": ["Continued motion"],
        "worse_de": ["Bücken", "Sonnenaufgang bis Sonnenuntergang", "Liegen auf linker Seite"],
        "worse_en": ["Bending forward", "With the sun", "Lying on left side"],
        "diff": ["Spigelia", "Rhus tox", "Digitalis", "Cactus"],
        "sphere": ["Herz", "Klappenapparat", "Nerven", "Gelenke"],
        "tier": 1
    },
    {
        "id": "lathyrus-sativus",
        "latin": "Lathyrus sativus",
        "cat": "plant",
        "de_name": "Saat-Platterbse",
        "en_name": "Chick-Pea",
        "es_name": "Almorta",
        "fr_name": "Gesse cultivée",
        "it_name": "Cicerchia comune",
        "el_name": "Λάθυρος ο εδώδιμος",
        "ru_name": "Чина посевная",
        "de_essence": "Spastische Spinalparalyse, spastischer Gang, multiple Sklerose mit gesteigerten Reflexen und Schwere der Beine.",
        "en_essence": "Spastic spinal paralysis, spastic gait, lateral sclerosis, hyperactive reflexes, and trembling exhaustion of lower limbs.",
        "indications_de": ["Spastische Parese & Paraplegie", "Multiple Sklerose (Begleittherapie)", "Spastischer Scheren-Gang"],
        "indications_en": ["Spastic paralysis of legs", "Lateral sclerosis and tremors", "Hyper-reflexia with ankle clonus"],
        "keynotes_de": ["Spastischer Gang; Füße schleifen und stoßen aneinander", "Überschießende Patellarsehnenreflexe", "Lähmungsgefühl ohne nennenswerte Schmerzen"],
        "keynotes_en": ["Spastic scissor gait with drag of toes", "Excessive patellar and ankle reflexes", "Motor paralysis of lower limbs without sensory loss"],
        "better_de": ["Ruhelage im Bett"],
        "better_en": ["Resting flat in bed"],
        "worse_de": ["Kälte", "Gehversuche", "Feuchtigkeit"],
        "worse_en": ["Cold air", "Attempted walking", "Dampness"],
        "diff": ["Plumbum", "Conium", "Oxalicum acidum"],
        "sphere": ["Rückenmark", "Motorische Bahnen", "Untere Extremitäten"],
        "tier": 2
    },
    {
        "id": "laurocerasus",
        "latin": "Laurocerasus",
        "cat": "plant",
        "de_name": "Kirschlorbeer",
        "en_name": "Cherry Laurel",
        "es_name": "Laurel cerezo",
        "fr_name": "Laurier-cerise",
        "it_name": "Lauroceraso",
        "el_name": "Δαφνοκέρασος",
        "ru_name": "Лавровишня",
        "de_essence": "Boerickes Kollapsmittel: Zyanose, Atemstillstand, Erstickungshusten mit gurgelndem Trinken und mangelnde Lebensreaktion.",
        "en_essence": "Boericke's collapse remedy: cyanosis, gasping respiration, dry suffocative cough, gurgling sound when swallowing liquids, and lack of vital reaction.",
        "indications_de": ["Zyanose & Asphyxie bei Neugeborenen", "Kardialer Kollaps mit Kälte", "Gurgelndes Geräusch beim Trinken"],
        "indications_en": ["Cyanosis and infant asphyxia", "Cardiac failure with gasping breath", "Drink rolls audibly down the esophagus"],
        "keynotes_de": ["Flüssigkeit gurgelt mit lautem Geräusch den Ösophagus hinab", "Bläuliche Hautfärbung (Zyanose) mit Eiseskälte", "Herzschwäche ohne Schmerz; Patient ringt lautlos nach Luft"],
        "keynotes_en": ["Audible gurgling of liquids down gullet into stomach", "Cyanotic blue tint of skin and mucous membranes", "Extreme prostration with dyspnea relieved by lying down"],
        "better_de": ["Flaches Liegen", "Im Freien"],
        "better_en": ["Lying flat", "Open air"],
        "worse_de": ["Aufrechtes Sitzen", "Abends"],
        "worse_en": ["Sitting erect", "Evening"],
        "diff": ["Carbo vegetabilis", "Camphora", "Digitalis"],
        "sphere": ["Herz", "Atemzentrum", "Blutoxygenierung"],
        "tier": 2
    },
    {
        "id": "lemna-minor",
        "latin": "Lemna minor",
        "cat": "plant",
        "de_name": "Kleine Wasserlinse",
        "en_name": "Duckweed",
        "es_name": "Lenteja de agua",
        "fr_name": "Petite lentille d'eau",
        "it_name": "Lenticchia d'acqua",
        "el_name": "Λέμνα η ελάσσων",
        "ru_name": "Ряска малая",
        "de_essence": "Boerickes Nasenpolypenmittel: Verstopfte Nase durch Schwellung der Polypen, besonders bei feuchtem Regenwetter; Verlust von Geruch und Geschmack.",
        "en_essence": "Boericke's premier remedy for nasal polyps: polyps swell and obstruct nostrils in damp rainy weather; foul odor and loss of smell.",
        "indications_de": ["Nasenpolypen mit Verstopfung", "Chronische Ozaena & übler Geruch", "Verlust des Geruchssinns (Anosmie)"],
        "indications_en": ["Nasal polypi expanding in damp weather", "Atrophic rhinitis and ozaena", "Anosmia and post-nasal drip"],
        "keynotes_de": ["Polypen schwellen bei jedem Wetterumschwung zu Regen massiv an", "Fauliger Geruch aus der Nase mit Eiterkrusten", "Trockener Rachen morgens durch Mundatmung"],
        "keynotes_en": ["Nasal polyps swell and occlude nose during wet weather", "Putrid offensive stench from nostrils", "Complete loss of taste and smell from nasal catarrh"],
        "better_de": ["Trockenes, klares Wetter"],
        "better_en": ["Dry clear weather"],
        "worse_de": ["Feuchtes, regnerisches Wetter"],
        "worse_en": ["Damp rainy weather"],
        "diff": ["Teucrium marum", "Sanguinaria nitrica", "Thuja"],
        "sphere": ["Nasenschleimhaut", "Polypen", "Riechnerv"],
        "tier": 2
    },
    {
        "id": "linaria-vulgaris",
        "latin": "Linaria vulgaris",
        "cat": "plant",
        "de_name": "Gemeines Leinkraut",
        "en_name": "Toad-Flax / Butter and Eggs",
        "es_name": "Linaria común",
        "fr_name": "Linaire commune",
        "it_name": "Linaiola comune",
        "el_name": "Λινάρια η κοινή",
        "ru_name": "Льнянка обыкновенная",
        "de_essence": "Enuresis nocturna, schmerzhafte blutende Hämorrhoiden, Ohnmachtsanfälle und Urethralbrennen.",
        "en_essence": "Nocturnal enuresis, painful bleeding hemorrhoids, fainting spells without cause, and urinary irritation.",
        "indications_de": ["Enuresis nocturna bei Kindern", "Entzündete Hämorrhoiden", "Plötzliche Ohnmachten"],
        "indications_en": ["Bed-wetting in young patients", "Painful inflamed hemorrhoids", "Syncope without organic heart disease"],
        "keynotes_de": ["Nächtliches Einnässen bei schlaffen Kindern", "Hämorrhoiden schmerzen quälend beim Sitzen", "Häufiger, schmerzhafter Harndrang"],
        "keynotes_en": ["Involuntary bed-wetting in childhood", "Painful protruding hemorrhoidal piles", "Frequent urging to pass water with tenesmus"],
        "better_de": ["Wärme"],
        "better_en": ["Warmth"],
        "worse_de": ["Sitzen", "Kälte"],
        "worse_en": ["Sitting", "Cold"],
        "diff": ["Equisetum", "Collinsonia", "Aesculus"],
        "sphere": ["Harnblase", "Rektum", "Kreislauf"],
        "tier": 3
    },
    {
        "id": "lobelia-inflata",
        "latin": "Lobelia inflata",
        "cat": "plant",
        "de_name": "Aufgeblasene Lobelie / Indianertabak",
        "en_name": "Indian Tobacco",
        "es_name": "Tabaco indio",
        "fr_name": "Lobélie enflée",
        "it_name": "Tabacco indiano",
        "el_name": "Λοβελία η διογκωμένη",
        "ru_name": "Лобелия вздутая",
        "de_essence": "Boerickes Vagus- und Asthmamittel: Todesübelkeit mit eiskaltem Schweiß, Atemnot mit Gefühl des Zuschnürens der Brust und kardiale Schwäche.",
        "en_essence": "Boericke's premier vagus nerve and asthma remedy: deadly deathly nausea with cold sweat, asthmatic constriction of chest, and cardiac faintness.",
        "indications_de": ["Asthma bronchiale mit Erstickung", "Todesübelkeit & kaltes Schwitzen", "Schwangerschaftserbrechen"],
        "indications_en": ["Spasmodic asthma with chest constriction", "Deathly sickening nausea with cold sweat", "Obstinate morning sickness of pregnancy"],
        "keynotes_de": ["Übelkeit so entsetzlich, dass der Patient dem Tode nahe scheint", "Eiskalter Schweiß an Stirn und Händen während der Übelkeit", "Gefühl von unerträglichem Zuschnüren und Leere in der Magengrube"],
        "keynotes_en": ["Deathly sickening faint nausea with cold drenching sweat", "Sensation of intolerable ring or band constricting chest", "Asthma worse from slightest exertion or tobacco smoke"],
        "better_de": ["Schnelles Gehen", "Warmes Trinken"],
        "better_en": ["Rapid walking", "Warm drinks"],
        "worse_de": ["Tabakrauch", "Kälte", "Geringste Bewegung"],
        "worse_en": ["Tobacco smoke", "Cold", "Slightest exertion"],
        "diff": ["Tabacum", "Ipecacuanha", "Antimonium tartaricum"],
        "sphere": ["Vagusnerv", "Atemwege", "Magen", "Herzkreislauf"],
        "tier": 1
    },
    {
        "id": "lycopus-virginicus",
        "latin": "Lycopus virginicus",
        "cat": "plant",
        "de_name": "Virginischer Wolfstrapp",
        "en_name": "Bugle-Weed",
        "es_name": "Marrubio acuático",
        "fr_name": "Lycope de Virginie",
        "it_name": "Lycopus della Virginia",
        "el_name": "Λύκοπους ο παρθενικός",
        "ru_name": "Зюзник виргинский",
        "de_essence": "Boerickes Schilddrüsen- und Herzmittel: Morbus Basedow mit Exophthalmus, jagendem Puls, kardialen Blutungen und zittriger Unruhe.",
        "en_essence": "Boericke's classic thyroid-heart remedy: exophthalmic goiter (Graves' disease), tumultuously throbbing heart, cardiac hemoptysis, and nervous tremors.",
        "indications_de": ["Morbus Basedow & Hyperthyreose", "Tachykardie & Herzjagen", "Kardiale Hämoptysen"],
        "indications_en": ["Exophthalmic goiter with tachycardia", "Tumultuous cardiac action with weak pulse", "Hemoptysis accompanying organic heart disease"],
        "keynotes_de": ["Herz schlägt mit ungestümer Kraft, der Radialpuls ist jedoch fadenförmig", "Hervortretende Augäpfel bei Schilddrüsenüberfunktion", "Bluthusten mit beklemmendem Herzschmerz"],
        "keynotes_en": ["Tumultuous pounding heartbeat contrasted with small weak radial pulse", "Exophthalmos, staring eyes, and enlarged thyroid", "Hemoptysis with constrictive precordial stitch"],
        "better_de": ["Flaches Liegen auf dem Rücken"],
        "better_en": ["Lying flat on back"],
        "worse_de": ["Liegen auf der linken Seite", "Aufstieg", "Bewegung"],
        "worse_en": ["Lying on left side", "Ascending stairs", "Motion"],
        "diff": ["Iodum", "Spigelia", "Crataegus", "Digitalis"],
        "sphere": ["Schilddrüse", "Herz", "Gefäßsystem", "Lungen"],
        "tier": 1
    },
    {
        "id": "magnesia-sulfurica",
        "latin": "Magnesia sulfurica",
        "cat": "mineral",
        "de_name": "Magnesiumsulfat / Bittersalz",
        "en_name": "Epsom Salt",
        "es_name": "Sulfato de magnesio",
        "fr_name": "Sulfate de magnésie",
        "it_name": "Solfato di magnesio",
        "el_name": "Θειικό μαγνήσιο",
        "ru_name": "Магнезия сульфурика",
        "de_essence": "Reichliche wässrige Diarrhoe am frühen Morgen, brennende Schmerzen zwischen den Schulterblättern und Hautausschläge.",
        "en_essence": "Copious early-morning watery diarrhea, burning interscapular ache, rheumatic stitch, and itching eruptions.",
        "indications_de": ["Morgendlicher Durchfall", "Brennender Schmerz zwischen Schulterblättern", "Urtikaria & Pickel"],
        "indications_en": ["Early morning watery diarrhea", "Burning ache between shoulder blades", "Pruritic acne and vesicular eruptions"],
        "keynotes_de": ["Wässriger Stuhl treibt morgens früh aus dem Bett", "Brennen am Rücken zwischen den Scapulae", "Stechende Schmerzen in den Seiten beim Husten"],
        "keynotes_en": ["Watery bowel movements driving patient from bed at dawn", "Intense burning pain between scapulae", "Stitching chest pains worse on deep inspiration"],
        "better_de": ["Warme Einhüllung", "Gehen"],
        "better_en": ["Warm wrapping", "Walking about"],
        "worse_de": ["Frühmorgens", "Kälte"],
        "worse_en": ["Early morning", "Cold"],
        "diff": ["Sulfur", "Magnesia carbonica", "Natrium sulfuricum"],
        "sphere": ["Darmtrakt", "Rücken", "Haut"],
        "tier": 3
    },
    {
        "id": "mancinella",
        "latin": "Mancinella",
        "cat": "plant",
        "de_name": "Manchinelbaum",
        "en_name": "Hippomane Mancinella",
        "es_name": "Manzanillo de playa",
        "fr_name": "Mancenillier",
        "it_name": "Mancinella",
        "el_name": "Μανκινέλλα",
        "ru_name": "Манцинелла",
        "de_essence": "Dunkle depressive Zustände mit Furcht vor Wahnsinn, Blasenbildung auf der Haut und heftiges Brennen in Hals und Ösophagus.",
        "en_essence": "Melancholia with fear of insanity, severe vesication of skin with blackish crusts, and scalding in throat and gullet.",
        "indications_de": ["Pemphigus & bullöse Dermatitis", "Brennende Ösophagitis", "Schwermut & Angst vor Wahnsinn"],
        "indications_en": ["Bullous vesicular dermatosis", "Scalding burning throughout gullet", "Anxious depression and dread of losing mind"],
        "keynotes_de": ["Große Blasen mit ätzender, brennender Flüssigkeit", "Brennen im Hals als sei kochendes Wasser hinuntergeschüttet", "Ständige Todesangst und Furcht vor dem Verrücktwerden"],
        "keynotes_en": ["Large bullae and blisters discharging corrosive fluid", "Burning in esophagus as if from boiling oil", "Profound gloom with fear of impending insanity"],
        "better_de": ["Warmes Zimmer"],
        "better_en": ["Warm room"],
        "worse_de": ["Kaltes Wasser", "Nasses Wetter"],
        "worse_en": ["Cold water", "Damp weather"],
        "diff": ["Cantharis", "Anacardium", "Arsenicum album"],
        "sphere": ["Haut", "Ösophagus", "Gemüt"],
        "tier": 3
    },
    {
        "id": "medusa",
        "latin": "Medusa",
        "cat": "animal",
        "de_name": "Qualle",
        "en_name": "Jelly-Fish",
        "es_name": "Medusa",
        "fr_name": "Méduse",
        "it_name": "Medusa",
        "el_name": "Μέδουσα",
        "ru_name": "Медуза",
        "de_essence": "Plötzliche, generalisierte Urtikaria mit brennendem Stechen, Quincke-Ödem der Lippen und Laktationsstörungen.",
        "en_essence": "Sudden, generalized severe urticaria with burning pricking, angioedema of face and lips, and deficient lactation.",
        "indications_de": ["Akutes Angioödem & Urtikaria", "Nesselsucht nach Meeresfrüchten", "Mangelnde Muttermilchsekretion"],
        "indications_en": ["Acute angioedema and severe hives", "Nettle rash from sea-bath or shell-fish", "Suppressed secretion of breast milk"],
        "keynotes_de": ["Haut schwillt quaddelartig an mit stechendem Brennen", "Gesicht und Lippen massiv ödematös verquollen", "Stimuliert die Milchsekretion bei stillenden Müttern"],
        "keynotes_en": ["Sudden eruption of burning stinging wheals over body", "Edematous swelling of eyelids, ears, and lips", "Restores suppressed secretion of breast milk in mothers"],
        "better_de": ["Ruhelage"],
        "better_en": ["Rest"],
        "worse_de": ["Baden im Meer", "Wärme"],
        "worse_en": ["Bathing in sea water", "Warmth"],
        "diff": ["Apis mellifica", "Urtica urens", "Astacus fluviatilis"],
        "sphere": ["Haut", "Subkutangewebe", "Milchdrüsen"],
        "tier": 3
    },
    {
        "id": "melilotus-officinalis",
        "latin": "Melilotus officinalis",
        "cat": "plant",
        "de_name": "Echter Steinklee",
        "en_name": "Yellow Sweet Clover",
        "es_name": "Meliloto amarillo",
        "fr_name": "Mélilot officinal",
        "it_name": "Meliloto",
        "el_name": "Μελίλωτος ο φαρμακευτικός",
        "ru_name": "Донник лекарственный",
        "de_essence": "Boerickes Leitsymptom: Hochrotes, pulsierendes Kongestionsgesicht mit Berstkopfschmerz, der durch NASENBLUTEN SOFORT BESSER WIRD.",
        "en_essence": "Boericke's premier congestive headache: throbbing, bursting head with intensely flushed red face, PROMPTLY RELIEVED BY EPISTAXIS.",
        "indications_de": ["Kongestiver Berstkopfschmerz", "Hyperämie des Gehirns & Apoplexgefahr", "Epistaxis mit Erleichterung"],
        "indications_en": ["Violent congestive bursting headache", "Cerebral engorgement and throbbing carotids", "Epistaxis which affords instant relief"],
        "keynotes_de": ["Kopfschmerz so grausam, dass der Kopf zu bersten droht", "Gesicht hochrot bis purpurn; pochende Halsschlagadern", "Nasenbluten bringt schlagartige, wunderbare Besserung aller Schmerzen"],
        "keynotes_en": ["Bursting, agonizing headache as if cranium would fly open", "Face intensely purple-red with throbbing carotids", "Profuse epistaxis brings immediate miraculous relief"],
        "better_de": ["Nasenbluten", "Reichliche Menstruation", "Liegen"],
        "better_en": ["Epistaxis (nosebleed)", "Profuse menses", "Lying down"],
        "worse_de": ["Vor Stürmen", "Bewegung", "16 Uhr"],
        "worse_en": ["Before storms", "Motion", "4 p.m."],
        "diff": ["Belladonna", "Glonoinum", "Ferrum phosphoricum"],
        "sphere": ["Zerebrale Zirkulation", "Kopfgefäße", "Blut"],
        "tier": 1
    },
    {
        "id": "menyanthes-trifoliata",
        "latin": "Menyanthes trifoliata",
        "cat": "plant",
        "de_name": "Fieberklee / Bitterklee",
        "en_name": "Buckbean",
        "es_name": "Trébol de agua",
        "fr_name": "Trèfle d'eau",
        "it_name": "Trifoglio fibrino",
        "el_name": "Μηνυάνθης",
        "ru_name": "Вахта трёхлистная",
        "de_essence": "Boerickes Druck-Symptom: Schwere Kopfschmerzen mit Gefühl eines schweren Gewichts auf dem Scheitel, gebessert durch FESTEN HANDDRUCK; Eiseskälte der Hände und Füße.",
        "en_essence": "Boericke's heavy pressure symptom: bursting vertex headache RELIEVED BY HARD PRESSURE of hand; icy coldness of hands and feet during chill.",
        "indications_de": ["Scheitelkopfschmerz mit Druckgefühl", "Fieberfrost mit Eiseskälte der Akren", "Krampfhaftes Muskelzucken"],
        "indications_en": ["Vertex headache relieved by hard hand pressure", "Icy coldness of extremities during ague", "Spasmodic twitching of isolated muscles"],
        "keynotes_de": ["Gefühl als läge ein Zentnergewicht auf dem Scheitel", "Patient presst die Hände mit aller Kraft auf den Kopf zur Linderung", "Hände und Füße eiskalt, während der Rumpf glüht"],
        "keynotes_en": ["Heavy pressing weight on vertex as from a stone", "Compelled to compress head firmly with hands for relief", "Icy coldness of hands and feet up to knees during paroxysm"],
        "better_de": ["Fester Druck mit den Händen", "Gehen im Zimmer"],
        "better_en": ["Hard pressure with hand", "Walking indoors"],
        "worse_de": ["Ruhe", "Sitzen", "Abends"],
        "worse_en": ["Rest", "Sitting quiet", "Evening"],
        "diff": ["Gelsemium", "Veratrum album", "Spigelia"],
        "sphere": ["Kopf", "Scheitel", "Thermoregulation"],
        "tier": 2
    },
    {
        "id": "mephitis-mephitica",
        "latin": "Mephitis mephitica",
        "cat": "animal",
        "de_name": "Stinktier-Sekret",
        "en_name": "Skunk",
        "es_name": "Mofeta",
        "fr_name": "Moufette",
        "it_name": "Moffetta",
        "el_name": "Μεφίτις",
        "ru_name": "Мефитис мефитика",
        "de_essence": "Boerickes klassisches Keuchhustenmittel: Krampfhafter Erstickungshusten, Kind kann nicht ausatmen und scheint blau anzulaufen.",
        "en_essence": "Boericke's classic whooping cough remedy: violent spasmodic paroxysms where patient cannot exhale, turning blue in the face.",
        "indications_de": ["Keuchhusten (Pertussis)", "Spasmodischer Erstickungshusten", "Husten nach Mitternacht"],
        "indications_en": ["Whooping cough with severe spasms", "Violent suffocative laryngeal cough", "Cough paroxysms worse lying down"],
        "keynotes_de": ["Patient kann nach einem Hustenanfall nicht ausatmen; Erstickungsnot", "Gesicht wird zyanotisch, Krämpfe drohen", "Hustenanfälle kehren alle paar Minuten wieder"],
        "keynotes_en": ["Spasms of cough where patient cannot exhale; chokes and turns purple", "Paroxysms recur every few minutes with vomiting", "Awakened at night by sudden suffocative paroxysms"],
        "better_de": ["Kaltes Wasser trinken", "Frische Luft"],
        "better_en": ["Cold water drinks", "Cold fresh air"],
        "worse_de": ["Nachts nach Mitternacht", "Flaches Liegen"],
        "worse_en": ["Night after midnight", "Lying down flat"],
        "diff": ["Corallium rubrum", "Drosera", "Cuprum metallicum"],
        "sphere": ["Kehlkopf", "Atemmuskulatur", "Bronchien"],
        "tier": 2
    },
    {
        "id": "millefolium",
        "latin": "Millefolium",
        "cat": "plant",
        "de_name": "Gemeine Schafgarbe",
        "en_name": "Yarrow",
        "es_name": "Milenrama",
        "fr_name": "Millefeuille",
        "it_name": "Millefoglio",
        "el_name": "Αχίλλεια η χιλιάφυλλος",
        "ru_name": "Тысячелистник обыкновенный",
        "de_essence": "Boerickes oberstes Hämostyptikum für schmerzlose, hellrote, flüssige Blutungen aus allen Körperöffnungen ohne Fieber oder Angst.",
        "en_essence": "Boericke's pre-eminent anti-hemorrhagic for painless, bright red, fluid hemorrhages from any outlet, without fever or anxiety.",
        "indications_de": ["Hämaturie & Nierenblutung", "Lungenblutung (Hämoptysis)", "Schmerzlose Metrorrhagie"],
        "indications_en": ["Hematuria without pain", "Hemoptysis in phthisis", "Painless bright red uterine hemorrhage"],
        "keynotes_de": ["Blut ist rein hellrot, flüssig und fließt ohne Angst und ohne Fieber (Gegenteil von Aconitum)", "Blutungen nach Stürzen, Heben oder Verletzungen", "Boericke: 'Das verlässlichste Mittel zur Blutstillung'"],
        "keynotes_en": ["Hemorrhage of bright red fluid blood without anxiety or fever (contrast Aconite)", "Bleeding following mechanical fall, lifting, or sprains", "Boericke: 'One of our most dependable styptics'"],
        "better_de": ["Ruhelage"],
        "better_en": ["Quiet rest"],
        "worse_de": ["Unterdrückte Lochien", "Körperliche Anstrengung"],
        "worse_en": ["Suppressed lochia", "Physical effort"],
        "diff": ["Acalypha indica", "Erigeron", "Ipecacuanha", "Hamamelis"],
        "sphere": ["Kapillaren", "Uterus", "Harnwege", "Lunge"],
        "tier": 1
    },
    {
        "id": "mitchella-repens",
        "latin": "Mitchella repens",
        "cat": "plant",
        "de_name": "Rebhuhnbeere",
        "en_name": "Partridge-Berry",
        "es_name": "Baya de perdiz",
        "fr_name": "Pain de perdrix",
        "it_name": "Mitchella",
        "el_name": "Μιτσέλλα",
        "ru_name": "Митчелла ползучая",
        "de_essence": "Boerickes Uterus- und Blasenmittel: Erleichtert die Geburt, lindert falsche Wehen, heilt Uterusengorgement und Zystitis mit Strangurie.",
        "en_essence": "Boericke's uterine and bladder tonic: facilitates easy labor, relieves false pains, dispels uterine engorgement and catarrhal cystitis.",
        "indications_de": ["Geburtsvorbereitung & Wehenerleichterung", "Uteruskongestion & Zervizitis", "Katarrhalische Zystitis"],
        "indications_en": ["Obstetric prep for easy labor", "Uterine engorgement with aching", "Catarrhal cystitis with dysuria"],
        "keynotes_de": ["Bereitet den Uterus auf eine schmerzärmere, zügige Geburt vor", "Ständiger schmerzhafter Harndrang mit brennendem Urin", "Schweregefühl im Becken bei Uterusretroflexion"],
        "keynotes_en": ["Prepares uterus for easy and prompt delivery", "Constant painful urging to urinate with burning", "Pelvic aching with dragging soreness"],
        "better_de": ["Ruhe im Liegen"],
        "better_en": ["Lying down quiet"],
        "worse_de": ["Gehen", "Langes Stehen"],
        "worse_en": ["Walking", "Protracted standing"],
        "diff": ["Caulophyllum", "Cimicifuga", "Chimaphila"],
        "sphere": ["Uterus", "Blase", "Beckenorgane"],
        "tier": 2
    },
    {
        "id": "myosotis-arvensis",
        "latin": "Myosotis arvensis",
        "cat": "plant",
        "de_name": "Acker-Vergissmeinnicht",
        "en_name": "Field Forget-Me-Not",
        "es_name": "No me olvides del campo",
        "fr_name": "Myosotis des champs",
        "it_name": "Nontiscordardimé",
        "el_name": "Μυοσωτίς η αρουραία",
        "ru_name": "Незабудка полевая",
        "de_essence": "Chronische Bronchitis mit profusem, schleimig-eitrigem Auswurf, Nachtschweißen, Abmagerung und Husten nach Grippe.",
        "en_essence": "Chronic bronchitis with profuse mucopurulent expectoration, night-sweats, emaciation, and post-influenzal chest affections.",
        "indications_de": ["Chronische eitrige Bronchitis", "Post-influenzer Husten mit Schwäche", "Lungenphthisis mit Auszehrung"],
        "indications_en": ["Chronic purulent bronchitis", "Post-grippal cough with chest soreness", "Bronchial phthisis with wasting"],
        "keynotes_de": ["Husten mit reichlichem, gelbem, zähem Eitersputum", "Schmerz in der linken Brust beim Husten", "Erschöpfung mit Auszehrung und Nachtschweiß"],
        "keynotes_en": ["Cough with copious yellowish-green purulent sputum", "Painful soreness in left chest on coughing", "Night sweats with progressive constitutional wasting"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting upright"],
        "worse_de": ["Liegen auf der linken Seite", "Frühmorgens"],
        "worse_en": ["Lying on left side", "Early morning"],
        "diff": ["Stannum", "Balsamum peruvianum", "Eriodictyon"],
        "sphere": ["Bronchien", "Lunge", "Brustwand"],
        "tier": 3
    },
    {
        "id": "myrica-cerifera",
        "latin": "Myrica cerifera",
        "cat": "plant",
        "de_name": "Wachsmyrte",
        "en_name": "Bayberry / Wax Myrtle",
        "es_name": "Árbol de la cera",
        "fr_name": "Arbre à cire",
        "it_name": "Mirica cerifera",
        "el_name": "Μυρίκη η κηροφόρος",
        "ru_name": "Мирика восконосная",
        "de_essence": "Boerickes Lebermittel: Tiefer Ikterus mit lehmfarbenem Stuhl, zäher klebriger Schleim im Rachen und bleierne Schläfrigkeit.",
        "en_essence": "Boericke's classic hepatic remedy: deep bronze jaundice, clay-colored stool, thick sticky mucous coating in pharynx, and profound lethargy.",
        "indications_de": ["Ikterus mit Gelbfärbung der Haut", "Gallenstau & Schläfrigkeit", "Zäher Schleim im Mund und Rachen"],
        "indications_en": ["Catarrhal jaundice with bronzed skin", "Hepatic torpor with mental sluggishness", "Tenacious ropy mucus in pharynx"],
        "keynotes_de": ["Haut und Skleren tief gelb bis bronzefarben verfärbt", "Mund und Rachen voller zähem, klebrigem Schleim, der schwer abzuhusten ist", "Bleierne Müdigkeit und Apathie bei Leberschwäche"],
        "keynotes_en": ["Deep yellow jaundiced skin, conjunctiva, and nails", "Mouth filled with sticky, tenacious, offensive mucus", "Heavy drowsiness and mental dullness with bitter taste"],
        "better_de": ["Frische Luft"],
        "better_en": ["Open air"],
        "worse_de": ["Warmes Zimmer", "Morgens"],
        "worse_en": ["Warm room", "Morning"],
        "diff": ["Chelidonium", "Hydrastis", "Carduus marianus"],
        "sphere": ["Leber", "Gallenblase", "Schleimhäute"],
        "tier": 2
    },
    {
        "id": "nuphar-luteum",
        "latin": "Nuphar luteum",
        "cat": "plant",
        "de_name": "Gelbe Teichrose",
        "en_name": "Yellow Pond-Lily",
        "es_name": "Nenúfar amarillo",
        "fr_name": "Nénuphar jaune",
        "it_name": "Ninfea gialla",
        "el_name": "Νούφαρο κίτρινο",
        "ru_name": "Кубышка жёлтая",
        "de_essence": "Morgendlicher, schmerzloser Durchfall (um 4–5 Uhr) und völlige sexuelle Impotenz mit schlaffen Genitalien und Libidoverlust.",
        "en_essence": "Painless morning diarrhea (at 4 to 5 a.m.) and complete sexual impotence with relaxed cold genitals and total loss of libido.",
        "indications_de": ["Morgendliche schmerzlose Diarrhoe", "Erektile Impotenz & Libidoverlust", "Chronische Enteritis"],
        "indications_en": ["Painless morning diarrhea (4 to 5 a.m.)", "Complete erectile impotence", "Retraction and coldness of male organs"],
        "keynotes_de": ["Wässriger Stuhl treibt den Patienten um 5 Uhr früh schmerzlos aus dem Bett", "Vollständige Schlaffheit der Geschlechtsteile ohne jedes Verlangen", "Starke Schwäche in den Kniekehlen"],
        "keynotes_en": ["Yellow watery diarrhea rushing patient out of bed at 5 a.m.", "Complete absence of sexual desire; organs cold and retracted", "Excessive exhaustion and weakness in limbs after stool"],
        "better_de": ["Ruhelage"],
        "better_en": ["Rest"],
        "worse_de": ["Frühmorgens (4-5 Uhr)"],
        "worse_en": ["Early morning"],
        "diff": ["Sulfur", "Podophyllum", "Agnum castus"],
        "sphere": ["Darmtrakt", "Männliche Geschlechtsorgane"],
        "tier": 2
    },
    {
        "id": "ocimum-canum",
        "latin": "Ocimum canum",
        "cat": "plant",
        "de_name": "Graues Basilikum",
        "en_name": "Brazilian Alfavaca",
        "es_name": "Albahaca de Brasil",
        "fr_name": "Basilic brésilien",
        "it_name": "Basilico cano",
        "el_name": "Ώκιμον το πολιόν",
        "ru_name": "Базилик седой",
        "de_essence": "Boerickes Nierenkolikmittel: Schreckliche Nierenkoliken (besonders RECHTS) mit heftigem Erbrechen und reichlich rotem Ziegelmehlsediment.",
        "en_essence": "Boericke's premier renal colic remedy: agonizing right-sided kidney colic with intractable vomiting and heavy red brick-dust sand in urine.",
        "indications_de": ["Rechtsseitige Nierenkolik", "Harnsäuresteine & Ziegelmehlsediment", "Krampfhafte Zystitis"],
        "indications_en": ["Acute right-sided renal colic", "Uric acid gravel and brick-dust sediment", "Violent nephralgia with vomiting"],
        "keynotes_de": ["Unerträgliche Schmerzen in der rechten Niere mit Schreien und Winden", "Urin dick, trüb mit massenhaft rotem Harnsäuresand", "Heftiges Erbrechen und Brechreiz während der Kolik"],
        "keynotes_en": ["Violent pain in right ureter, writhing and groaning with colic", "Urine leaves thick red sand coating the chamber pot", "Intractable vomiting accompanies nephritic paroxysm"],
        "better_de": ["Nach Abgang von Harnsand"],
        "better_en": ["After passing gravel"],
        "worse_de": ["Rechte Seite", "Bewegung"],
        "worse_en": ["Right side", "Motion"],
        "diff": ["Lycopodium", "Berberis", "Hydrangea"],
        "sphere": ["Rechte Niere", "Ureter", "Harnblase"],
        "tier": 1
    },
    {
        "id": "oenanthe-crocata",
        "latin": "Oenanthe crocata",
        "cat": "plant",
        "de_name": "Safran-Rebpendolde",
        "en_name": "Water Dropwort / Hemlock Dropwort",
        "es_name": "Nabo del diablo",
        "fr_name": "Oenanthe safranée",
        "it_name": "Finocchio d'acqua",
        "el_name": "Οινάνθη η κροκοειδής",
        "ru_name": "Омежник водяной",
        "de_essence": "Boerickes Epilepsiemittel: Epileptiforme Krämpfe, plötzlicher Bewusstseinsverlust mit Schaum vor dem Mund, Zungenbiss und Zyanose.",
        "en_essence": "Boericke's celebrated epilepsy remedy: violent epileptiform convulsions, sudden fall with foam at mouth, bitten tongue, and stertorous coma.",
        "indications_de": ["Epilepsie (Grand Mal)", "Puerperalkrämpfe & Eklampsie", "Spasmen mit Bewusstlosigkeit"],
        "indications_en": ["Epileptiform convulsions", "Puerperal eclampsia", "Spasms with cyanosis and lockjaw"],
        "keynotes_de": ["Plötzlicher Sturz mit lautem Schrei und Schaum vor dem Mund", "Zähne fest zusammengebissen (Trismus); blutiger Zungenbiss", "Gesicht geschwollen, livid und verzerrt"],
        "keynotes_en": ["Sudden epileptic seizure with scream, froth at mouth, and lockjaw", "Bloody froth from bitten tongue and dark livid face", "Prolonged stertorous stupor follows convulsions"],
        "better_de": ["Nach Erwachen aus dem Koma"],
        "better_en": ["After waking from sleep"],
        "worse_de": ["Kälte", "Wasser", "Schwangerschaft"],
        "worse_en": ["Cold", "Water", "Pregnancy"],
        "diff": ["Cicuta virosa", "Cuprum metallicum", "Hydrocyanicum acidum"],
        "sphere": ["Gehirn", "Krampfzentrum", "Motorik"],
        "tier": 2
    },
    {
        "id": "oleander",
        "latin": "Oleander",
        "cat": "plant",
        "de_name": "Echter Oleander",
        "en_name": "Rose Laurel",
        "es_name": "Adelfa / Laurel rosa",
        "fr_name": "Laurier-rose",
        "it_name": "Oleandro",
        "el_name": "Νήριον το ροδοδάφνη",
        "ru_name": "Олеандр обыкновенный",
        "de_essence": "Boerickes Leitsymptom: Schmerzhafter, unwillkürlicher Stuhlabgang beim Abgehen von Winden; nässende Ekzeme des Hinterkopfes und geistige Trägheit.",
        "en_essence": "Boericke's hallmark: involuntary passing of stool when passing flatus; oozing eczema on occiput and behind ears, and slow mental comprehension.",
        "indications_de": ["Stuhlabgang bei Blähungsabgang", "Nässendes Ekzem an Kopf und Ohren", "Schwäche und Zittern der Beine"],
        "indications_en": ["Involuntary stool with emission of flatus", "Humid weeping eczema of occiput and ears", "Paralytic weakness and trembling of knees"],
        "keynotes_de": ["Unwillkürlicher Stuhl beim Abgang kleinster Windmengen", "Hinterkopf und Ohren voller juckender, nässender Krusten", "Geistige Schwerfälligkeit; versteht Worte erst nach Wiederholung"],
        "keynotes_en": ["Passes stool unconsciously along with flatus", "Raw weeping eczema behind ears and across occiput with crusts", "Mental slowness; cannot grasp questions without effort"],
        "better_de": ["Liegen im Bett"],
        "better_en": ["Lying in bed"],
        "worse_de": ["Entkleiden", "Reiben", "Ruhe"],
        "worse_en": ["Undressing", "Rubbing", "Rest"],
        "diff": ["Aloe", "Petroleum", "Graphites"],
        "sphere": ["Rektum", "Sphinkter", "Haut", "Gehirn"],
        "tier": 2
    },
    {
        "id": "onosmodium-virginianum",
        "latin": "Onosmodium virginianum",
        "cat": "plant",
        "de_name": "Falscher Steinsame",
        "en_name": "False Gromwell",
        "es_name": "Onosmodio",
        "fr_name": "Onosmode",
        "it_name": "Onosmodio",
        "el_name": "Ονόσμωδιον",
        "ru_name": "Оносмодиум виргинский",
        "de_essence": "Boerickes Augen- und Neurastheniemittel: Augenmuskellähmung, Asthenopie nach Überanstrengung, linksseitiger Kopfschmerz und sexuelle Atonie.",
        "en_essence": "Boericke's eyestrain and neurasthenia remedy: ciliary and extra-ocular muscle paresis, asthenopia, left-sided occipital migraine, and sexual atony.",
        "indications_de": ["Asthenopie & Übermüdung der Augen", "Linksseitige Okzipitalmigräne", "Nervöse Erschöpfung & Muskelschwäche"],
        "indications_en": ["Asthenopia and muscular ocular strain", "Left-sided occipito-temporal migraine", "Neurasthenia and heavy trembling limbs"],
        "keynotes_de": ["Augenmuskeln fühlen sich müde, überanstrengt und zittrig an", "Kopfschmerz beginnt im Hinterkopf und zieht ins linke Auge", "Taubheitsgefühl und Unsicherheit in den Beinen"],
        "keynotes_en": ["Tension and pain in ocular muscles from reading or fine work", "Dull heavy ache in occiput shooting to left temple and eyeball", "Extreme muscular weakness; walks as if intoxicated"],
        "better_de": ["Schlaf", "Flaches Liegen"],
        "better_en": ["Sleep", "Lying down flat"],
        "worse_de": ["Naharbeit", "Augenbewegung", "Kälte"],
        "worse_en": ["Eye strain", "Motion of eyes", "Cold"],
        "diff": ["Ruta", "Gelsemium", "Natrium muriaticum"],
        "sphere": ["Augenmuskeln", "Okzipitalnerv", "Zentralnervensystem"],
        "tier": 2
    },
    {
        "id": "oxydendrum-arboreum",
        "latin": "Oxydendrum arboreum",
        "cat": "plant",
        "de_name": "Sauerbaum",
        "en_name": "Sour-Wood / Sorrel-Tree",
        "es_name": "Árbol ácido",
        "fr_name": "Andromède en arbre",
        "it_name": "Ossidentro",
        "el_name": "Οξύδενδρον",
        "ru_name": "Оксидендрум древовидный",
        "de_essence": "Boerickes Wassersuchtmittel: Kardiale und renale Ödeme, Aszites, Atemnot beim Aufrichten und verminderte Harnausscheidung.",
        "en_essence": "Boericke's celebrated dropsy remedy: general anasarca, ascites, cardiac dropsy, severe dyspnea, and suppressed urine.",
        "indications_de": ["Generalisierte Wassersucht (Anasarka)", "Aszites bei Leber- und Herzschwäche", "Oligurie mit Dyspnoe"],
        "indications_en": ["General anasarca and ascites", "Cardiac hydrops with dyspnea", "Scanty dark urine with swelling"],
        "keynotes_de": ["Massive Wassereinlagerung in Bauch und Beinen", "Erstickende Atemnot, zwingt zum Aufrichten im Bett", "Reichliche Diurese führt zur Heilung"],
        "keynotes_en": ["Rapid relief of dropsical effusions throughout tissues", "Dyspnea on lying down; compelled to sit up", "Acts as a potent and safe natural diuretic"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting upright"],
        "worse_de": ["Flaches Liegen", "Bewegung"],
        "worse_en": ["Lying flat", "Motion"],
        "diff": ["Apocynum", "Digitalis", "Adonis vernalis"],
        "sphere": ["Nieren", "Seröse Höhlen", "Herz"],
        "tier": 2
    },
    {
        "id": "pareira-brava",
        "latin": "Pareira brava",
        "cat": "plant",
        "de_name": "Grießwurz",
        "en_name": "Virgin-Vine",
        "es_name": "Pareira brava",
        "fr_name": "Pareira brava",
        "it_name": "Pareira brava",
        "el_name": "Παρέιρα μπράβα",
        "ru_name": "Парейра брава",
        "de_essence": "Boerickes Nieren-Leitsymptom: Unerträgliche Schmerzen beim Wasserlassen; kann nur auf den Knien urinieren, während der Kopf den Boden berührt.",
        "en_essence": "Boericke's hallmark renal remedy: excruciating pain on micturition; CAN URINATE ONLY ON KNEES with head pressing against the floor.",
        "indications_de": ["Nephrolithiasis & Nierenkolik", "Schwere Strangurie & Dysurie", "Prostatavergrößerung mit Harnsperre"],
        "indications_en": ["Renal colic radiating to thighs and toes", "Excruciating dysuria with violent straining", "Prostatic obstruction with urine retention"],
        "keynotes_de": ["Kann Urin nur entleeren, wenn er sich auf Hände und Knie stützt", "Schmerz strahlt von der Niere durch den Schenkel bis in die Zehen", "Urin riecht stechend nach Ammoniak mit dickem Schleim"],
        "keynotes_en": ["Can only pass urine on hands and knees with head against floor", "Pain cuts from kidneys straight down thighs to toes", "Urine contains thick ropy white mucus and ammoniacal stench"],
        "better_de": ["Knie-Ellenbogen-Lage"],
        "better_en": ["Kneeling posture"],
        "worse_de": ["Aufrechtes Stehen", "Nachts"],
        "worse_en": ["Standing upright", "Night"],
        "diff": ["Berberis", "Chimaphila", "Cantharis", "Uva ursi"],
        "sphere": ["Ureteren", "Harnblase", "Prostata", "Oberschenkelnerven"],
        "tier": 1
    },
    {
        "id": "passiflora-incarnata",
        "latin": "Passiflora incarnata",
        "cat": "plant",
        "de_name": "Fleischfarbene Passionsblume",
        "en_name": "Passion-Flower",
        "es_name": "Pasionaria",
        "fr_name": "Passiflore",
        "it_name": "Passiflora",
        "el_name": "Πασιφλόρα",
        "ru_name": "Пассифлора инкарнатная",
        "de_essence": "Boerickes sicheres natürliches Sedativum: Schlaflosigkeit durch geistige Sorgen und Überarbeitung, Delirium tremens, Krämpfe und Unruhe.",
        "en_essence": "Boericke's reliable natural sedative: insomnia from mental worry and exhaustion, delirium tremens, infantile convulsions, and quiet natural sleep.",
        "indications_de": ["Hartnäckige nervöse Schlaflosigkeit", "Zerebrale Unruhe & Überarbeitung", "Kindliche Krämpfe & Zahnung"],
        "indications_en": ["Obstinate insomnia from worry or exhaustion", "Delirium tremens and alcohol tremors", "Infantile teething convulsions"],
        "keynotes_de": ["Erzeugt natürlichen, erholenden Schlaf ohne morgendliche Benommenheit", "Beruhigt den rastlosen Gedankenstrom nachts im Bett", "Krämpfe von Säuglingen bei Zahnung oder Fieber"],
        "keynotes_en": ["Induces quiet natural restorative sleep without grogginess", "Quiets torrential thoughts preventing sleep in neurotics", "Relieves spasms and twitchings in infants and alcoholics"],
        "better_de": ["Ruhiges Liegen"],
        "better_en": ["Resting quietly"],
        "worse_de": ["Nachts", "Geistige Aufregung"],
        "worse_en": ["Night", "Mental worry"],
        "diff": ["Avena sativa", "Scutellaria", "Coffea"],
        "sphere": ["Gehirn", "Schlafzentrum", "Motorische Nerven"],
        "tier": 1
    },
    {
        "id": "petroselinum-sativum",
        "latin": "Petroselinum sativum",
        "cat": "plant",
        "de_name": "Gartenpetersilie",
        "en_name": "Parsley",
        "es_name": "Perejil",
        "fr_name": "Persil",
        "it_name": "Prezzemolo",
        "el_name": "Πετροσέλινον το ήμερον",
        "ru_name": "Петрушка посевная",
        "de_essence": "Boerickes Harndrang-Symptom: Plötzlicher, unwiderstehlicher Harndrang; Kind tanzt vor Schmerz auf und ab; Kitzeln und Jucken in der Urethra.",
        "en_essence": "Boericke's urgent micturition keynote: sudden, irresistible desire to urinate; child dances up and down with agony; drawing itch along urethra.",
        "indications_de": ["Plötzlicher imperativer Harndrang", "Urethritis mit heftigem Jucken", "Zystitis bei Kindern"],
        "indications_en": ["Sudden imperative call to urinate", "Tingling, itching, and biting along urethra", "Subacute gonorrhea and cystitis"],
        "keynotes_de": ["Harndrang kommt plötzlich und muss auf der Sekunde entleert werden", "Kind springt und tanzt vor Miktionsdrang und Schmerz", "Kitzeln tief in der Fossa navicularis"],
        "keynotes_en": ["Sudden urge to void urine comes with irresistible force", "Children dance up and down when the desire seizes them", "Crawling, tickling itching in navicular fossa"],
        "better_de": ["Sofortiges Wasserlassen"],
        "better_en": ["Immediate urination"],
        "worse_de": ["Zurückhalten des Urins"],
        "worse_en": ["Resisting urge"],
        "diff": ["Cannabis sativa", "Cantharis", "Clematis"],
        "sphere": ["Urethra", "Blasenhals", "Harnwege"],
        "tier": 2
    },
    {
        "id": "psoralea-corylifolia",
        "latin": "Psoralea corylifolia",
        "cat": "plant",
        "de_name": "Babchi",
        "en_name": "Babchi Seeds",
        "es_name": "Babchi",
        "fr_name": "Babchi",
        "it_name": "Babchi",
        "el_name": "Ψωραλέα",
        "ru_name": "Псоралея лещинолистная",
        "de_essence": "Boerickes Vitiligomittel: Depigmentierung der Haut, Weißfleckenkrankheit, Psoriasis, Alopezie und hartnäckige Dermatosen.",
        "en_essence": "Boericke's celebrated vitiligo remedy: depigmentation of skin, leucoderma, psoriasis, alopecia areata, and recalcitrant dermatoses.",
        "indications_de": ["Vitiligo (Weißfleckenkrankheit)", "Leukodermie & Pigmentverlust", "Psoriasis & kreisrunder Haarausfall"],
        "indications_en": ["Vitiligo and leucoderma", "Pigment loss of skin patches", "Psoriasis and alopecia areata"],
        "keynotes_de": ["Fördert die Repigmentierung weißer Hautstellen", "Schuppige, juckende Flecken an Extremitäten", "Regt die Melaninbildung der Haut an"],
        "keynotes_en": ["Stimulates melanogenesis and repigmentation in leucoderma", "Scaly dry patches on exposed cutaneous surfaces", "Effective in patchy hair loss (alopecia)"],
        "better_de": ["Mäßiges Sonnenlicht"],
        "better_en": ["Moderate sunlight"],
        "worse_de": ["Kälte"],
        "worse_en": ["Cold"],
        "diff": ["Hydrocotyle", "Arsenicum sulfuratum flavum"],
        "sphere": ["Haut", "Melanozyten", "Haarfollikel"],
        "tier": 2
    },
    {
        "id": "santoninum",
        "latin": "Santoninum",
        "cat": "mineral",
        "de_name": "Santonin",
        "en_name": "Santonin",
        "es_name": "Santonina",
        "fr_name": "Santonine",
        "it_name": "Santonina",
        "el_name": "Σαντονίνη",
        "ru_name": "Сантонин",
        "de_essence": "Boerickes Xanthopsie- und Wurmmittel: Gelbsehen (alle Objekte erscheinen gelb oder violett), Wurmbeschwerden, Zähneknirschen und Enuresis.",
        "en_essence": "Boericke's classic xanthopsia remedy: yellow sight (chromatopsia), helminthiasis, nocturnal teeth-grinding, and strabismus.",
        "indications_de": ["Gelbsehen (Xanthopsie)", "Spulwürmer & Oxyuren", "Nächtliches Zähneknirschen"],
        "indications_en": ["Xanthopsia (yellow vision)", "Ascariasis and helminthic irritations", "Nocturnal bruxism (grinding teeth)"],
        "keynotes_de": ["Alles erscheint dem Patienten leuchtend gelb gefärbt (Xanthopsie)", "Kind knirscht nachts im Schlaf laut mit den Zähnen", "Bohren in der Nase und unruhiger Schlaf bei Wurmbefall"],
        "keynotes_en": ["Visual chromatopsia; everything appears vivid yellow or green", "Violent teeth-grinding during sleep in children", "Constant picking and rubbing of nose with intestinal worms"],
        "better_de": ["Wärme"],
        "better_en": ["Warmth"],
        "worse_de": ["Nachts", "Ruhe"],
        "worse_en": ["Night", "Rest"],
        "diff": ["Cina", "Teucrium", "Spigelia"],
        "sphere": ["Sehnerv", "Augen", "Darmtrakt", "Nervensystem"],
        "tier": 2
    },
    {
        "id": "scutellaria-lateriflora",
        "latin": "Scutellaria lateriflora",
        "cat": "plant",
        "de_name": "Helmkraut",
        "en_name": "Skullcap",
        "es_name": "Escutelaria",
        "fr_name": "Scutellaire",
        "it_name": "Scutellaria",
        "el_name": "Σκουτελλάρια",
        "ru_name": "Шлемник бокоцветковый",
        "de_essence": "Nervöse Erschöpfung durch Überarbeitung, zerebrale Hyperästhesie, zittriges Zucken der Muskeln, Schlaflosigkeit und Herzklopfen.",
        "en_essence": "Nervous exhaustion from mental overwork, cerebral hyperesthesia, choreic muscular twitchings, sleeplessness, and irregular heart.",
        "indications_de": ["Nervöse Erschöpfung & Burnout", "Muskelzuckungen & Chorea", "Schlaflosigkeit durch Gedankenkreisen"],
        "indications_en": ["Nervous prostration from business worry", "Choreic twitchings of limbs", "Insomnia with restless vivid dreams"],
        "keynotes_de": ["Unruhe und Zuckungen der Arme und Beine", "Stirnkopfschmerz nach geistiger Überlastung", "Herzbeschwerden nervösen Ursprungs"],
        "keynotes_en": ["Involuntary twitching and tremors of limbs", "Aching frontal headache in students and professionals", "Nervous heart with fluttering and weakness"],
        "better_de": ["Frische Luft", "Schlaf"],
        "better_en": ["Open air", "Sleep"],
        "worse_de": ["Geistige Anstrengung", "Lärm"],
        "worse_en": ["Mental exertion", "Noise"],
        "diff": ["Passiflora", "Avena sativa", "Ignatia", "Valeriana"],
        "sphere": ["Gehirn", "Zentralnervensystem", "Muskeln"],
        "tier": 2
    },
    {
        "id": "solidago-virgaurea",
        "latin": "Solidago virgaurea",
        "cat": "plant",
        "de_name": "Echte Goldrute",
        "en_name": "Golden-Rod",
        "es_name": "Vara de oro",
        "fr_name": "Verge d'or",
        "it_name": "Verga d'oro",
        "el_name": "Σολιντάγκο",
        "ru_name": "Золотарник обыкновенный",
        "de_essence": "Boerickes großes Nierentonikum: Schmerzhafte Nierenentzündung, druckempfindliche Nieren, spärlicher dunkler Urin und Hautausschläge.",
        "en_essence": "Boericke's celebrated kidney tonic: painful nephritis, exquisite tenderness of kidney region to touch, scanty dark urine, and uremic eczema.",
        "indications_de": ["Nephritis & Niereninsuffizienz", "Druckschmerz in den Nierenlagern", "Urämischer Juckreiz der Beine"],
        "indications_en": ["Acute and chronic nephritis", "Kidneys sensitive to slightest touch or jar", "Scanty red-brown urine and uremic dermatitis"],
        "keynotes_de": ["Nieren so empfindlich, dass der Patient kaum berührt werden kann", "Urin dunkel, rotbraun, mit reichlich Schleim und Sediment", "Boericke: 'Reinigt die Nieren und beugt Uterus- und Prostatakomplikationen vor'"],
        "keynotes_en": ["Kidneys tender, sensitive to pressure, cannot bear jarring", "Urine dark, reddish-brown, with heavy sediment", "Boericke: 'Acts as a specific tonic to kidney tubules'"],
        "better_de": ["Reichliche Diurese"],
        "better_en": ["Abundant flow of urine"],
        "worse_de": ["Druck", "Erschütterung", "Kälte"],
        "worse_en": ["Pressure on back", "Jarring", "Cold"],
        "diff": ["Berberis", "Uva ursi", "Chimaphila"],
        "sphere": ["Nieren", "Tubulussystem", "Harnwege", "Haut"],
        "tier": 1
    },
    {
        "id": "strophanthus-hispidus",
        "latin": "Strophanthus hispidus",
        "cat": "plant",
        "de_name": "Kombe-Strophanthus",
        "en_name": "Kombe Seed",
        "es_name": "Estrofanto",
        "fr_name": "Strophanthe",
        "it_name": "Strofanto",
        "el_name": "Στρόφανθος",
        "ru_name": "Строфант щетинистый",
        "de_essence": "Boerickes sicheres Herztonikum: Kardiale Dekompensation mit unregelmäßigem Puls, Ödemen, Atemnot und Alkohol- oder Nikotin-Herz.",
        "en_essence": "Boericke's reliable heart tonic: cardiac insufficiency with irregular rapid pulse, anasarca, dyspnea, and tobacco/alcoholic heart.",
        "indications_de": ["Kardiale Insuffizienz & Ödeme", "Unregelmäßiger fadenförmiger Puls", "Nikotin- & Raucherherz"],
        "indications_en": ["Cardiac dropsy and failure", "Irregular, rapid, feeble heart action", "Toxic tobacco and alcoholic heart"],
        "keynotes_de": ["Puls schnell, schwach, kaum tastbar und völlig arrhythmisch", "Ödeme der Knöchel und Beine bei Herzkranken", "Boericke: 'Wirkt rasch und kumuliert nicht wie Digitalis'"],
        "keynotes_en": ["Pulse rapid, small, thready, undulating, and irregular", "Extensive dropsy and edema of lower limbs in cardiacs", "Boericke: 'Safer than Digitalis; does not produce cumulative poisoning'"],
        "better_de": ["Ruhelage", "Frische Luft"],
        "better_en": ["Rest", "Fresh air"],
        "worse_de": ["Anstrengung", "Tabak", "Alkohol"],
        "worse_en": ["Exertion", "Tobacco", "Alcohol"],
        "diff": ["Digitalis", "Crataegus", "Convallaria"],
        "sphere": ["Myokard", "Reizleitungssystem", "Kreislauf"],
        "tier": 1
    },
    {
        "id": "thlaspi-bursa-pastoris",
        "latin": "Thlaspi bursa pastoris",
        "cat": "plant",
        "de_name": "Gewöhnliches Hirtentäschel",
        "en_name": "Shepherd's Purse (Thlaspi)",
        "es_name": "Hierba del pastor",
        "fr_name": "Bourse-à-pasteur (Thlaspi)",
        "it_name": "Borsapastore",
        "el_name": "Θλάσπι",
        "ru_name": "Ярутка пастушья сумка",
        "de_essence": "Boerickes oberstes Uterusblutungsmittel: Unaufhörliche Metrorrhagie bei Myomen, Hämaturie mit Ziegelmehlsand und Kolik.",
        "en_essence": "Boericke's pre-eminent anti-hemorrhagic for uterine fibroid bleeding, profuse protracted metrorrhagia, and hematuria with gravel.",
        "indications_de": ["Profuse Uterusblutungen bei Myom", "Chronische Metrorrhagie", "Hämaturie & Harnsäuregrieß"],
        "indications_en": ["Uterine hemorrhage in fibroid tumors", "Protracted metrorrhagia with dark clots", "Hematuria with renal sand and dysuria"],
        "keynotes_de": ["Blutung hört kaum auf; kaum ist eine Periode vorbei, beginnt die nächste", "Blut dunkel, klumpig mit krampfhaftem Wehenschmerz", "Ziegelmehlartiger roter Harnsäuresand im Urin"],
        "keynotes_en": ["Hemorrhage scarcely ceases; one period scarcely ends before another begins", "Blood dark, clotted, accompanied by violent uterine cramps", "Copious red brick-dust sand in urine with burning colic"],
        "better_de": ["Ruhe im Bett"],
        "better_en": ["Rest in bed"],
        "worse_de": ["Geringste Bewegung", "Vor und nach Menses"],
        "worse_en": ["Slightest motion", "Before and after menses"],
        "diff": ["Trillium pendulum", "Sabina", "Erigeron", "Millefolium"],
        "sphere": ["Uterus", "Myome", "Blutgefäße", "Nieren"],
        "tier": 1
    },
    {
        "id": "yucca-filamentosa",
        "latin": "Yucca filamentosa",
        "cat": "plant",
        "de_name": "Fädige Palmlilie",
        "en_name": "Bear-Grass",
        "es_name": "Yuca de filamentos",
        "fr_name": "Yucca filamenteux",
        "it_name": "Yucca filamentosa",
        "el_name": "Γιούκα η νηματοειδής",
        "ru_name": "Юкка нитчатая",
        "de_essence": "Boerickes Gallen- und Kopfschmerzmittel: Bilöser Stirnkopfschmerz, Zunge schmutzig gelb belegt mit Zahnabdrücken und Blähungskoliken.",
        "en_essence": "Boericke's bilious and hepatic headache: frontal migraine, tongue heavily coated yellow showing teeth imprints, and flatus colics.",
        "indications_de": ["Bilöse Migräne & Kopfschmerz", "Leberstau mit gelbem Zungenbelag", "Chronischer Durchfall mit Winden"],
        "indications_en": ["Bilious frontal and temporal headache", "Hepatic engorgement with flabby yellow tongue", "Chronic flatulent diarrhea with soreness"],
        "keynotes_de": ["Zunge dick schmutzig-gelb belegt, geschwollen mit Zahnrändern", "Druckschmerz in der Leber zieht in den Rücken", "Gallenartiger Kopfschmerz über den Augen"],
        "keynotes_en": ["Tongue broad, flabby, heavily coated yellow with teeth indents", "Aching in liver extending to back and shoulders", "Severe frontal headache with bitter bilious taste"],
        "better_de": ["Nach Abgang von Wind und Stuhl"],
        "better_en": ["After emission of flatus and stool"],
        "worse_de": ["Morgens", "Bewegung"],
        "worse_en": ["Morning", "Motion"],
        "diff": ["Chelidonium", "Podophyllum", "Hydrastis"],
        "sphere": ["Leber", "Gallenblase", "Zunge", "Schläfen"],
        "tier": 2
    }
]
