# -*- coding: utf-8 -*-
# Boericke remedies for Part 24 (remedies 67 to 99: C - G)

PART24_REMEDIES = [
    {
        "id": "cynodon-dactylon",
        "latin": "Cynodon dactylon",
        "cat": "plant",
        "de_name": "Hundszahngras",
        "en_name": "Bermuda Grass / Durba",
        "es_name": "Grama común",
        "fr_name": "Chiendent pied-de-poule",
        "it_name": "Gramigna rossa",
        "el_name": "Κυνόδους ο δάκτυλος",
        "ru_name": "Свинорой пальчатый",
        "de_essence": "Hämostyptikum bei profusen Blutungen, Epistaxis, Hämorrhoidalblutung und vesikaler Harnsäure-Reizung.",
        "en_essence": "Anti-hemorrhagic in profuse epistaxis, bleeding piles, hematuria, and chronic vesical catarrh.",
        "indications_de": ["Nasenbluten (Epistaxis)", "Hämorrhoidalblutung", "Dysurie mit Harndrang"],
        "indications_en": ["Epistaxis and nasal hemorrhage", "Bleeding hemorrhoids", "Dysuria and tenesmus of bladder"],
        "keynotes_de": ["Ständige Blutungsneigung aus allen Öffnungen", "Brennen beim Urinieren mit schleimigem Bodensatz", "Kopfschmerz nach Blutverlust"],
        "keynotes_en": ["Marked hemorrhagic tendency from mucous outlets", "Burning strangury with mucous deposit", "Exhaustion after hemorrhages"],
        "better_de": ["Kühle Umschläge"],
        "better_en": ["Cool applications"],
        "worse_de": ["Hitze", "Sonneneinstrahlung"],
        "worse_en": ["Heat", "Sun exposure"],
        "diff": ["Hamamelis", "Millefolium", "Ficus religiosa"],
        "sphere": ["Blutgefäße", "Harnwege", "Nasenschleimhaut"],
        "tier": 3
    },
    {
        "id": "cypripedium-pubescens",
        "latin": "Cypripedium pubescens",
        "cat": "plant",
        "de_name": "Gelber Frauenschuh",
        "en_name": "Yellow Lady's Slipper",
        "es_name": "Zapatilla de dama",
        "fr_name": "Sabot de Vénus",
        "it_name": "Pianella della Madonna",
        "el_name": "Κυπριπέδιον",
        "ru_name": "Башмачок пушистый",
        "de_essence": "Boerickes Kinderschlafmittel: Schlaflosigkeit nervöser Kinder, die nachts aufwachen, spielen und lachen wollen; Gehirnüberreizung.",
        "en_essence": "Boericke's infantile sleep remedy: nervous sleeplessness in children who awake at night cheerful, wanting to play; cerebral hyperesthesia.",
        "indications_de": ["Kindliche Schlaflosigkeit", "Zerebrale Hyperästhesie", "Zahnungsbeschwerden"],
        "indications_en": ["Insomnia in teething children", "Nervous erethism and mental overactivity", "Twitchings and restlessness"],
        "keynotes_de": ["Kind wacht mitten in der Nacht auf und ist hellwach, will spielen", "Zuckungen der Glieder bei Überreizung", "Beruhigt das Nervensystem ohne Betäubung"],
        "keynotes_en": ["Child wakes up at 2 a.m. full of play, lively and cheerful", "Nervous twitching from brain exhaustion", "Quiets nervous excitation safely"],
        "better_de": ["Sanftes Wiegen", "Spiel"],
        "better_en": ["Gentle rocking", "Distraction"],
        "worse_de": ["Nachts", "Geistige Überreizung", "Zahnung"],
        "worse_en": ["Night", "Mental excitement", "Dentition"],
        "diff": ["Chamomilla", "Coffea", "Scutellaria", "Passiflora"],
        "sphere": ["Gehirn", "Zentralnervensystem", "Kindliche Psyche"],
        "tier": 2
    },
    {
        "id": "daphne-indica",
        "latin": "Daphne indica",
        "cat": "plant",
        "de_name": "Indischer Seidelbast",
        "en_name": "Sweet-scented Spurge Laurel",
        "es_name": "Dafne dulce",
        "fr_name": "Daphné de l'Inde",
        "it_name": "Dafne indiana",
        "el_name": "Δάφνη η ινδική",
        "ru_name": "Волчеягодник индийский",
        "de_essence": "Erhöhte Reizbarkeit, Gefühl als seien die Glieder vom Körper getrennt, rheumatische Schmerzen und Abneigung gegen Tabak.",
        "en_essence": "Nervous erethism, erratic shooting pains, sensation as if limbs were separated from body, and tobacco craving/aversion.",
        "indications_de": ["Reißende rheumatische Schmerzen", "Zahn- und Kieferschmerzen", "Tabakabneigung mit Übelkeit"],
        "indications_en": ["Erratic shooting rheumatic pains", "Toothache and jaw neuralgia", "Sensation of separation of body parts"],
        "keynotes_de": ["Gefühl als seien die Beine oder Arme vom Rumpf abgetrennt", "Schmerzen schießen blitzschnell von einem Gelenk zum anderen", "Ekel vor Tabakrauch"],
        "keynotes_en": ["Strange feeling as if parts of body were severed", "Sudden shooting pains jumping from joint to joint", "Repugnance to tobacco smoke"],
        "better_de": ["Frische Luft", "Ruhelage"],
        "better_en": ["Open air", "Rest"],
        "worse_de": ["Tabakrauch", "Kälte", "Nachts"],
        "worse_en": ["Tobacco smoke", "Cold", "Night"],
        "diff": ["Mezereum", "Staphisagria", "Rhus tox"],
        "sphere": ["Nervensystem", "Knochen", "Gelenke"],
        "tier": 3
    },
    {
        "id": "dioscorea-villosa",
        "latin": "Dioscorea villosa",
        "cat": "plant",
        "de_name": "Wilde Jamswurzel",
        "en_name": "Wild Yam",
        "es_name": "Ñame silvestre",
        "fr_name": "Igname sauvage",
        "it_name": "Igname selvatico",
        "el_name": "Διοσκορέα η δασύτριχος",
        "ru_name": "Диоскорея мохнатая",
        "de_essence": "Boerickes Kolikmittel: Heftigste Bauchkrämpfe, Galle- und Nierenkoliken, die sich NUR DURCH RÜCKBEUGEN (Überstrecken) bessern (Gegenteil von Colocynthis).",
        "en_essence": "Boericke's hallmark colic remedy: violent abdominal, gall-stone, and renal colics relieved ONLY BY BENDING BACKWARD (opposite of Colocynthis).",
        "indications_de": ["Bauchkoliken & Gallenkolik", "Nierenkolik mit Ausstrahlung", "Reizdarmsyndrom"],
        "indications_en": ["Violent abdominal colic", "Gall-bladder and renal colic", "Flatulent colic in neurotics"],
        "keynotes_de": ["Schmerz zwingt den Patienten, sich rückwärts zu überstrecken", "Schmerzen strahlen vom Nabel sternförmig in alle Glieder aus", "Zusammenkrümmen verschlimmert unerträglich"],
        "keynotes_en": ["Colic relieved only by stretching out and bending backward", "Pains radiate from navel outwards into chest and limbs", "Bending double makes pain unbearable (contrast Colocynthis)"],
        "better_de": ["Rückwärtsbeugen", "Aufrechtes Stehen", "Bewegung"],
        "better_en": ["Bending backward", "Standing erect", "Walking about"],
        "worse_de": ["Zusammenkrümmen", "Liegen", "Nach dem Essen"],
        "worse_en": ["Bending double", "Lying down", "After meals"],
        "diff": ["Colocynthis", "Magnesia phosphorica", "Plumbum"],
        "sphere": ["Abdominalnerven", "Gallenwege", "Darmmuskulatur"],
        "tier": 1
    },
    {
        "id": "dolichos-pruriens",
        "latin": "Dolichos pruriens",
        "cat": "plant",
        "de_name": "Juckbohne",
        "en_name": "Cowhage",
        "es_name": "Pica-pica / Mucuna",
        "fr_name": "Pois à gratter",
        "it_name": "Fagiolo pungente",
        "el_name": "Δόλιχος",
        "ru_name": "Мукуна жгучая",
        "de_essence": "Boerickes Leitsymptom: Rasender Hautjuckreiz ohne sichtbaren Ausschlag, besonders bei Leberleiden, Schwangerschaft und Gelbsucht.",
        "en_essence": "Boericke's hallmark: intense generalized itching of skin without any perceptible rash, especially in jaundice and pregnancy.",
        "indications_de": ["Intolerabler Pruritus sine materia", "Schwangerschaftsjuckreiz", "Ikterischer Juckreiz"],
        "indications_en": ["Intolerable pruritus without rash", "Pruritus of pregnancy and jaundice", "Right-sided throat pain under jaw"],
        "keynotes_de": ["Juckreiz am ganzen Körper ohne jede Hautveränderung", "Kratzen verschlimmert das Jucken zur Raserei", "Stechender Schmerz unter dem rechten Kieferwinkel"],
        "keynotes_en": ["Maddening pruritus all over without skin eruption", "Scratching drives patient frantic, worse in bed", "Sharp pain behind right tonsil extending to jaw"],
        "better_de": ["Kaltes Wasser"],
        "better_en": ["Cold bathing"],
        "worse_de": ["Wärme des Bettes", "Nachts", "Kratzen"],
        "worse_en": ["Warmth of bed", "Night", "Scratching"],
        "diff": ["Radium bromatum", "Sulfur", "Urtica urens"],
        "sphere": ["Haut", "Leber", "Gallenwege"],
        "tier": 2
    },
    {
        "id": "echinacea-angustifolia",
        "latin": "Echinacea angustifolia",
        "cat": "plant",
        "de_name": "Schmalblättriger Sonnenhut",
        "en_name": "Purple Cone-Flower",
        "es_name": "Equinácea",
        "fr_name": "Échinacée à feuilles étroites",
        "it_name": "Echinacea",
        "el_name": "Εχινακεία η στενόφυλλος",
        "ru_name": "Эхинацея узколистная",
        "de_essence": "Boerickes Meistermittel für Blutvergiftung und Septikämie: Maligne Infektionen, Furunkel, Schlangenbisse, Gangrän und Abwehrschwäche.",
        "en_essence": "Boericke's premier blood cleanser and septic antidote: malignant infections, boils, carbuncles, snake bites, and systemic prostration.",
        "indications_de": ["Septikämie & Blutvergiftung", "Maligne Furunkulose & Karbunkel", "Schlangenbisse & septische Wunden"],
        "indications_en": ["Septicemia and blood poisoning", "Recurrent boils and malignant carbuncles", "Septic bites and gangrenous wounds"],
        "keynotes_de": ["Übelriechende, jauchige Absonderungen mit Fieber", "Tiefgreifende septische Erschöpfung mit Schüttelfrost", "Boericke: 'Stimuliert die Leukozytose und reinigt das Blut'"],
        "keynotes_en": ["Foul, putrid, dark discharges with adynamic fever", "Profound septic depression with aching in limbs", "Boericke: 'The sovereign remedy for blood depravation'"],
        "better_de": ["Ruhelage", "Wärme"],
        "better_en": ["Rest", "Warmth"],
        "worse_de": ["Körperliche Anstrengung", "Kälte"],
        "worse_en": ["Physical exertion", "Cold"],
        "diff": ["Anthracinum", "Baptisia", "Arsenicum album", "Pyrogenium"],
        "sphere": ["Blut", "Immunabwehr", "Lymphsystem", "Haut"],
        "tier": 1
    },
    {
        "id": "elaterium",
        "latin": "Elaterium",
        "cat": "plant",
        "de_name": "Spritzgurke",
        "en_name": "Squirting Cucumber",
        "es_name": "Pepinillo del diablo",
        "fr_name": "Concombre d'âne",
        "it_name": "Cocomero asinino",
        "el_name": "Ελατήριον",
        "ru_name": "Бешеный огурец",
        "de_essence": "Gewaltsame, schussartige, wässrig-olivgrüne Entleerungen aus dem Darm mit Schüttelfrost und Gähnen.",
        "en_essence": "Violent, copious, gushing frothy watery green stools accompanied by yawning, chilliness, and prostration.",
        "indications_de": ["Akute Cholerine & Durchfall", "Schussartige wässrige Stühle", "Urtikaria nach Durchfall"],
        "indications_en": ["Cholera morbus and gushing diarrhea", "Watery frothy green stool like a torrent", "Urticaria alternating with diarrhea"],
        "keynotes_de": ["Stuhl schießt mit gewaltiger Kraft explosionsartig hervor", "Stuhl ist schaumig, wässrig und grasgrün", "Frostschauer mit unstillbarem Gähnen vor dem Stuhlgang"],
        "keynotes_en": ["Stool expelled with tremendous force in a torrent", "Olive-green, frothy, watery discharges", "Chilliness with prolonged yawning before stool"],
        "better_de": ["Ruhelage im Bett"],
        "better_en": ["Quiet rest in bed"],
        "worse_de": ["Feuchte Kälte", "Stehen", "Zugluft"],
        "worse_en": ["Damp cold", "Standing", "Draft"],
        "diff": ["Croton tiglium", "Podophyllum", "Veratrum album"],
        "sphere": ["Dünn- und Dickdarm", "Gastrointestinaltrakt"],
        "tier": 3
    },
    {
        "id": "ephedra-vulgaris",
        "latin": "Ephedra vulgaris",
        "cat": "plant",
        "de_name": "Meerträubel",
        "en_name": "Ephedra / Ma Huang",
        "es_name": "Efedra",
        "fr_name": "Éphèdre",
        "it_name": "Efedra",
        "el_name": "Εφέδρα η κοινή",
        "ru_name": "Эфедра двухколосковая",
        "de_essence": "Schwere Atemnot, Asthma bronchiale mit Herzklopfen, linksseitiger Kopfschmerz und Schilddrüsenschwellung.",
        "en_essence": "Severe dyspnea, bronchial asthma with violent palpitations, left-sided hemicrania, and exophthalmic goiter.",
        "indications_de": ["Asthma bronchiale mit Enge", "Kardiale Dyspnoe", "Morbus Basedow"],
        "indications_en": ["Bronchial asthma with suffocation", "Cardiac dyspnea and tachycardia", "Exophthalmos and thyroid swelling"],
        "keynotes_de": ["Schwere Erstickungsanfälle mit Herzrasen", "Harter, schneller Puls mit Brustbeklemmung", "Brennen und Druck in den Augen"],
        "keynotes_en": ["Sudden suffocative asthma with pounding heart", "Fast bounding pulse with thoracic tightness", "Protrusion of eyeballs and neck fullness"],
        "better_de": ["Frische Luft", "Ruhe"],
        "better_en": ["Fresh air", "Rest"],
        "worse_de": ["Geringste Bewegung", "Nachts"],
        "worse_en": ["Slightest exertion", "Night"],
        "diff": ["Arsenicum album", "Grindelia", "Lycopus"],
        "sphere": ["Bronchien", "Herz", "Schilddrüse"],
        "tier": 3
    },
    {
        "id": "epigea-repens",
        "latin": "Epigea repens",
        "cat": "plant",
        "de_name": "Kriechende Scheinbeere",
        "en_name": "Trailing Arbutus / Gravel Weed",
        "es_name": "Arbusto rastrero",
        "fr_name": "Fleur de mai",
        "it_name": "Erba della ghiaia",
        "el_name": "Επίγαια η έρπουσα",
        "ru_name": "Эпигея ползучая",
        "de_essence": "Harnsäuregrieß, chronische Zystitis mit reichlichem braunem Bodensatz und Reizung des Blasenblasenhalses.",
        "en_essence": "Chronic cystitis with copious brown mucous sediment, uric acid gravel, and dysuria.",
        "indications_de": ["Zystitis mit Harngrieß", "Harnsäurediathese", "Dysurie mit Schleimabgang"],
        "indications_en": ["Chronic cystitis with lithuria", "Uric acid gravel colic", "Tenesmus of bladder neck"],
        "keynotes_de": ["Urin enthält Massen von braunem Schleim und rotem Sand", "Schmerzhaftes Brennen beim Urinieren", "Reizung der Blase nach geringster Kälte"],
        "keynotes_en": ["Urine heavy with bloody mucous sediment and red sand", "Scalding burning strangury", "Bladder irritation aggravated by cold damp"],
        "better_de": ["Warme Bäder", "Reichliches Trinken"],
        "better_en": ["Warm baths", "Copious water"],
        "worse_de": ["Kälte", "Langes Gehen"],
        "worse_en": ["Cold", "Long walking"],
        "diff": ["Uva ursi", "Pareira brava", "Chimaphila"],
        "sphere": ["Blase", "Nieren", "Harnwege"],
        "tier": 3
    },
    {
        "id": "equisetum-hyemale",
        "latin": "Equisetum hyemale",
        "cat": "plant",
        "de_name": "Winterschachtelhalm",
        "en_name": "Horsetail / Scouring Rush",
        "es_name": "Cola de caballo",
        "fr_name": "Prêle d'hiver",
        "it_name": "Coda cavallina",
        "el_name": "Ιππουρίς η χειμερινή",
        "ru_name": "Хвощ зимующий",
        "de_essence": "Boerickes Hauptmittel bei Enuresis nocturna und Blasenreizung: ständiger schmerzhafter Harndrang, der nach Entleerung NICHT besser wird.",
        "en_essence": "Boericke's premier remedy for nocturnal enuresis and cystitis: constant severe dysuria and urging NOT relieved by emptying bladder.",
        "indications_de": ["Enuresis nocturna bei Kindern", "Schmerzhafte Zystitis & Blasenkatarrh", "Tenesmus der Harnblase"],
        "indications_en": ["Nocturnal enuresis in children", "Painful cystitis with full bladder sensation", "Vesical tenesmus after micturition"],
        "keynotes_de": ["Völlegefühl und dumpfer Schmerz in der Blase bessern sich nicht nach dem Wasserlassen", "Kind nässt nachts ein, oft bei Alpträumen", "Urin enthält viel Epithel und Schleim"],
        "keynotes_en": ["Severe pain in bladder neck; voiding gives NO relief to constant aching fullness", "Nocturnal bed-wetting in children without organic cause", "Urine turbid with copious albuminous flakes and mucus"],
        "better_de": ["Vorübergehend durch Liegen auf dem Rücken"],
        "better_en": ["Temporarily by lying on back"],
        "worse_de": ["Druck auf die Blase", "Nach dem Wasserlassen", "Kälte"],
        "worse_en": ["Pressure on hypogastrium", "After urination", "Cold damp"],
        "diff": ["Cantharis", "Apis mellifica", "Petroselinum"],
        "sphere": ["Blase", "Blasenhals", "Nieren"],
        "tier": 1
    },
    {
        "id": "erigeron-canadense",
        "latin": "Erigeron canadense",
        "cat": "plant",
        "de_name": "Kanadisches Berufkraut",
        "en_name": "Fleabane",
        "es_name": "Erigerón del Canadá",
        "fr_name": "Vergerette du Canada",
        "it_name": "Cespica canadese",
        "el_name": "Εριγέρων ο καναδικός",
        "ru_name": "Мелколепестник канадский",
        "de_essence": "Plötzliche, schwallartige Blutungen mit hellrotem Blut bei jeder Bewegung; Uterusblutung, Hämaturie und Hämorrhoiden.",
        "en_essence": "Sudden, gushing bright-red hemorrhages aggravated by the least motion; metrorrhagia, hematuria, and bleeding piles.",
        "indications_de": ["Schwallartige Metrorrhagie", "Hämaturie mit Blasenreiz", "Akutes Nasenbluten"],
        "indications_en": ["Gushing bright-red metrorrhagia", "Vesical hematuria with tenesmus", "Epistaxis and hemoptysis"],
        "keynotes_de": ["Helles Blut schießt bei der geringsten Bewegung hervor", "Blutungen begleitet von Brennen in den Harnwegen", "Blutung nach Abort oder schwerem Heben"],
        "keynotes_en": ["Profuse bright-red blood flowing in gushes, worse slightest movement", "Painful urination with bloody flow", "Post-partum and post-abortive hemorrhage"],
        "better_de": ["Vollkommene Ruhe im Bett"],
        "better_en": ["Absolute quiet in bed"],
        "worse_de": ["Geringste Bewegung", "Aufstehen"],
        "worse_en": ["Slightest motion", "Rising upright"],
        "diff": ["Millefolium", "Sabina", "Trillium pendulum"],
        "sphere": ["Uterus", "Blase", "Blutgefäße"],
        "tier": 2
    },
    {
        "id": "eriodictyon-californicum",
        "latin": "Eriodictyon californicum",
        "cat": "plant",
        "de_name": "Yerba Santa",
        "en_name": "Yerba Santa",
        "es_name": "Yerba santa",
        "fr_name": "Yerba santa",
        "it_name": "Yerba santa",
        "el_name": "Ιεροδίκτυον",
        "ru_name": "Эриодиктион калифорнийский",
        "de_essence": "Boerickes Klassiker bei Bronchialasthma nach Influenza mit reichlichem, zähem Schleim, Heiserkeit und Nachtschweißen.",
        "en_essence": "Boericke's classic for post-influenzal asthma with profuse thick expectoration, chest soreness, and night sweats.",
        "indications_de": ["Asthma bronchiale nach Grippe", "Chronische Bronchitis mit Auswurf", "Erweichender Brusthusten"],
        "indications_en": ["Post-influenzal bronchial asthma", "Chronic rattling bronchitis", "Bronchial phthisis with wasting"],
        "keynotes_de": ["Asthmaanfälle nach Erkältung oder Grippe", "Rasseln in der Brust mit süßlichem, dickem Schleim", "Erschöpfender Husten mit Gewichtsverlust"],
        "keynotes_en": ["Asthma alternating with chronic mucous discharges", "Loud rattling in chest with thick mucopurulent sputum", "Exhausting cough with hectic sweats"],
        "better_de": ["Reichlicher Auswurf", "Aufrechtes Sitzen"],
        "better_en": ["Free expectoration", "Sitting erect"],
        "worse_de": ["Kaltes Wetter", "Liegen"],
        "worse_en": ["Cold weather", "Lying down"],
        "diff": ["Grindelia", "Arsenicum album", "Antimonium tartaricum"],
        "sphere": ["Bronchien", "Lunge", "Atemwege"],
        "tier": 2
    },
    {
        "id": "eryngium-aquaticum",
        "latin": "Eryngium aquaticum",
        "cat": "plant",
        "de_name": "Wasser-Mannstreu",
        "en_name": "Button Snake-Root",
        "es_name": "Eringio acuático",
        "fr_name": "Panicaut aquatique",
        "it_name": "Calcatreppola acquatica",
        "el_name": "Ερύγγιον το υδρόβιον",
        "ru_name": "Синеголовник водяной",
        "de_essence": "Heftige Blasenkrämpfe mit schneidendem Schmerz in der Harnröhre, Prostatabeschwerden und Nierenkolik.",
        "en_essence": "Violent vesical tenesmus, burning cutting pain in urethra, prostatic discharge, and renal colic.",
        "indications_de": ["Krampfhafte Zystitis", "Prostatavergrößerung mit Dysurie", "Schneidender Miktionsschmerz"],
        "indications_en": ["Spasmodic cystitis and strangury", "Prostatic congestion with gleet", "Renal colic radiating to groin"],
        "keynotes_de": ["Schneidender Schmerz von den Nieren in die Blase und den Penis", "Häufiger, schmerzhafter Harndrang bei Prostatismus", "Gefühl von Verengung im Blasenhals"],
        "keynotes_en": ["Burning cutting along urethra during and after urination", "Constant painful urging in prostatic enlargement", "Sharp dragging colic from kidneys to bladder"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting upright"],
        "worse_de": ["Bewegung", "Nach dem Wasserlassen"],
        "worse_en": ["Motion", "After urination"],
        "diff": ["Cantharis", "Chimaphila", "Equisetum"],
        "sphere": ["Blasenhals", "Harnröhre", "Prostata"],
        "tier": 3
    },
    {
        "id": "eucalyptus-globulus",
        "latin": "Eucalyptus globulus",
        "cat": "plant",
        "de_name": "Blauer Eukalyptus",
        "en_name": "Blue Gum Tree",
        "es_name": "Eucalipto común",
        "fr_name": "Eucalyptus commun",
        "it_name": "Eucalipto",
        "el_name": "Ευκάλυπτος ο σφαιρικός",
        "ru_name": "Эвкалипт шаровидный",
        "de_essence": "Boerickes Antiseptikum: Toxische Infektionen, eitrige Bronchitis, übelriechende Zystitis, Wechselfieber und Nierenbeckeneiterung.",
        "en_essence": "Boericke's celebrated antiseptic: toxic fevers, purulent bronchitis, foul-smelling cystitis, malaria, and pyelonephritis.",
        "indications_de": ["Eitrige Bronchitis & Bronchiektasen", "Zystitis mit übelriechendem Urin", "Chronisches Wechselfieber"],
        "indications_en": ["Purulent fetid bronchitis", "Chronic catarrhal cystitis with foul odor", "Malaria cachexia and typhoid states"],
        "keynotes_de": ["Übelriechender, eitriger Auswurf in großen Mengen", "Urin riecht nach faulem Ei mit reichlich Eiterflocken", "Brennendes Heißgefühl im Magen mit bitterem Geschmack"],
        "keynotes_en": ["Profuse fetid purulent expectoration with chest tightness", "Offensive urine with pus and catarrhal flakes", "High septic fever with violent pulsating headache"],
        "better_de": ["Frische Luft"],
        "better_en": ["Fresh open air"],
        "worse_de": ["Feuchte Kälte", "Nachts"],
        "worse_en": ["Damp cold", "Night"],
        "diff": ["Baptisia", "Arsenicum album", "Terebinthina"],
        "sphere": ["Bronchien", "Blase", "Nierenbecken", "Blut"],
        "tier": 2
    },
    {
        "id": "euonymus-europaeus",
        "latin": "Euonymus europaeus",
        "cat": "plant",
        "de_name": "Europäisches Pfaffenhütchen",
        "en_name": "Spindle Tree",
        "es_name": "Bonetero europeo",
        "fr_name": "Fusain d'Europe",
        "it_name": "Berretta da prete",
        "el_name": "Ευώνυμος ο ευρωπαϊκός",
        "ru_name": "Бересклет европейский",
        "de_essence": "Leberstauung mit chronischer Obstipation, bilöser Kopfschmerz, Hämorrhoiden und Albuminurie.",
        "en_essence": "Hepatic congestion with obstinate constipation, bilious sick headache, hemorrhoids, and albuminuria.",
        "indications_de": ["Chronische Leberüberlastung", "Bilöser Kopfschmerz mit Übelkeit", "Hämorrhoiden mit Verstopfung"],
        "indications_en": ["Hepatic torpor and congestion", "Bilious morning headache", "Constipation with backache"],
        "keynotes_de": ["Druckschmerz in der Lebergegend mit Schwindel", "Harte, lehmfarbene Stühle mit Anusjucken", "Stirnkopfschmerz nach fettigem Essen"],
        "keynotes_en": ["Deep soreness in right hypochondrium with jaundice", "Obstinate constipation with dry clay-colored stool", "Frontal headache with gastric acidity"],
        "better_de": ["Ruhelage"],
        "better_en": ["Quiet rest"],
        "worse_de": ["Fettige Nahrung", "Bücken"],
        "worse_en": ["Fatty food", "Bending forward"],
        "diff": ["Chelidonium", "Podophyllum", "Carduus marianus"],
        "sphere": ["Leber", "Pfortadersystem", "Darm"],
        "tier": 3
    },
    {
        "id": "fagopyrum-esculentum",
        "latin": "Fagopyrum esculentum",
        "cat": "plant",
        "de_name": "Echter Buchweizen",
        "en_name": "Buckwheat",
        "es_name": "Alforfón / Trigo sarraceno",
        "fr_name": "Sarrasin commun",
        "it_name": "Grano saraceno",
        "el_name": "Φαγόπυρον το εδώδιμον",
        "ru_name": "Гречиха посевная",
        "de_essence": "Boerickes Hautjuckmittel: Rasendes Hautjucken besonders in den Beugen, Schuppen, Kopfschmerz mit Augendruck und Herzklopfen.",
        "en_essence": "Boericke's skin-itching remedy: intense pruritus of flexures and scalp, scaly eruptions, eye ache, and palpitation.",
        "indications_de": ["Quälender Juckreiz der Hautfalten", "Erythem & Ekzeme der Kopfhaut", "Kopfschmerz mit Augenstechen"],
        "indications_en": ["Intense pruritus of elbows and knees", "Erythematous eruptions and eczema", "Throbbing occipital headache with eye pain"],
        "keynotes_de": ["Jucken in Ellenbeugen und Kniekehlen raubt den Schlaf", "Kratzen verschlimmert den Juckreiz und erzeugt Brennen", "Rote, schuppige Flecken auf der Haut"],
        "keynotes_en": ["Intolerable itching in flexures of joints, worse scratching", "Scaly dry erythematous patches", "Visible pulsation of temporal arteries with eye soreness"],
        "better_de": ["Kaltes Wasser", "Frische Luft"],
        "better_en": ["Cold bathing", "Open air"],
        "worse_de": ["Kratzen", "Wärme des Bettes", "Nachmittag"],
        "worse_en": ["Scratching", "Warmth of bed", "Afternoon"],
        "diff": ["Radium bromatum", "Sulfur", "Dolichos"],
        "sphere": ["Haut", "Gelenkbeugen", "Augen"],
        "tier": 3
    },
    {
        "id": "ficus-religiosa",
        "latin": "Ficus religiosa",
        "cat": "plant",
        "de_name": "Pappelfeige / Bodhibaum",
        "en_name": "Sacred Fig / Ashwatha",
        "es_name": "Higuera sagrada",
        "fr_name": "Figuier des pagodes",
        "it_name": "Fico sacro",
        "el_name": "Συκή η ιερά",
        "ru_name": "Фикус священный",
        "de_essence": "Boerickes indisches Hämostyptikum: Hämoptysen, Hämaturie, profuse Menorrhagie und Bluterbrechen mit hellem Blut.",
        "en_essence": "Boericke's celebrated Indian anti-hemorrhagic: hemoptysis, hematuria, profuse menorrhagia, and hematemesis of bright red blood.",
        "indications_de": ["Lungenblutung (Hämoptoe)", "Hämaturie & Nierenblutung", "Profuse Uterusblutungen"],
        "indications_en": ["Hemoptysis from chest affections", "Vesical hematuria", "Profuse menorrhagia and metrorrhagia"],
        "keynotes_de": ["Plötzliche Blutung von frischem, hellem Blut ohne Gerinnsel", "Husten löst sofort Blutspeien aus", "Schwindel und Schwäche nach Blutverlust"],
        "keynotes_en": ["Prompt arrest of bright-red hemorrhages from any orifice", "Cough immediately brings up arterial blood", "Profound faintness following blood loss"],
        "better_de": ["Absolute Bettruhe"],
        "better_en": ["Absolute rest in bed"],
        "worse_de": ["Bewegung", "Husten", "Anstrengung"],
        "worse_en": ["Motion", "Coughing", "Exertion"],
        "diff": ["Acalypha indica", "Millefolium", "Ipecacuanha"],
        "sphere": ["Blutgefäße", "Lunge", "Harnblase", "Uterus"],
        "tier": 2
    },
    {
        "id": "formica-rufa",
        "latin": "Formica rufa",
        "cat": "animal",
        "de_name": "Rote Waldameise",
        "en_name": "Red Wood Ant",
        "es_name": "Hormiga roja",
        "fr_name": "Fourmi rousse",
        "it_name": "Formica rossa",
        "el_name": "Μύρμηξ ο ερυθρός",
        "ru_name": "Рыжий лесной муравей",
        "de_essence": "Gicht, chronischer Gelenkrheumatismus, Nesselsucht mit brennendem Schmerz und Nierenreizung mit Harnsäureablagerungen.",
        "en_essence": "Gouty arthritis, chronic articular rheumatism, burning urticaria, and urinary tract catarrh with uric acid sediment.",
        "indications_de": ["Chronische Gicht & Arthritis", "Brennende Nesselsucht (Urtikaria)", "Nierenbeckenkatarrh mit Grieß"],
        "indications_en": ["Chronic gout and rheumatic stiffness", "Burning stinging urticaria", "Renal gravel and urinary catarrh"],
        "keynotes_de": ["Schmerzen tauchen plötzlich auf und wandern von Gelenk zu Gelenk", "Brennen und Stechen wie von Ameisenbissen", "Schlimmer durch kaltes Wasser, besser durch Druck"],
        "keynotes_en": ["Pains appear suddenly and jump from joint to joint", "Burning stinging stinging as if stung by ants", "Right-sided predominance; worse cold applications"],
        "better_de": ["Druck", "Wärme", "Reiben"],
        "better_en": ["Pressure", "Warmth", "Rubbing"],
        "worse_de": ["Kaltes Wasser", "Schneewetter", "Vor Stürmen"],
        "worse_en": ["Cold water", "Snowy weather", "Before a storm"],
        "diff": ["Apis mellifica", "Rhus tox", "Colchicum"],
        "sphere": ["Gelenke", "Haut", "Harnwege"],
        "tier": 2
    },
    {
        "id": "fraxinus-americana",
        "latin": "Fraxinus americana",
        "cat": "plant",
        "de_name": "Weiß-Esche",
        "en_name": "White Ash",
        "es_name": "Fresno blanco americano",
        "fr_name": "Frêne blanc",
        "it_name": "Frassino bianco",
        "el_name": "Φράξινος ο λευκός",
        "ru_name": "Ясень белый",
        "de_essence": "Boerickes bewährtes Uterusmittel: Uterusvergrößerung, Uterusmyome, Prolaps und Drängen im Becken bei schlaffem Gewebe.",
        "en_essence": "Boericke's celebrated uterine tonic: uterine enlargement, fibroids, prolapsus uteri, and dragging pelvic heaviness.",
        "indications_de": ["Uterusmyome & Gebärmuttervergrößerung", "Uterusprolaps & Senkungsgefühl", "Chronische Fluor albus"],
        "indications_en": ["Uterine fibroid tumors", "Prolapsus and retroversion of uterus", "Dragging bearing-down pelvic weight"],
        "keynotes_de": ["Schweregefühl im Unterleib als fiele alles heraus", "Uterus vergrößert, schlaff und myomatös verändert", "Dumpfer Schmerz in der linken Leiste"],
        "keynotes_en": ["Bearing-down sensation in pelvis as if organs would drop out", "Enlarged sluggish fibrous uterus", "Dull ache in left inguinal and hypogastric region"],
        "better_de": ["Liegen mit hochgelagertem Becken"],
        "better_en": ["Lying down with hips elevated"],
        "worse_de": ["Langes Stehen", "Gehen", "Heben"],
        "worse_en": ["Protracted standing", "Walking", "Lifting"],
        "diff": ["Aletris farinosa", "Helonias", "Sepia"],
        "sphere": ["Uterus", "Beckenorgane", "Bindegewebe"],
        "tier": 2
    },
    {
        "id": "galium-aparine",
        "latin": "Galium aparine",
        "cat": "plant",
        "de_name": "Klettenlabkraut",
        "en_name": "Cleavers / Goosegrass",
        "es_name": "Galio / Amor del hortelano",
        "fr_name": "Gaillet gratteron",
        "it_name": "Caglio asprello",
        "el_name": "Γάλιον το απαρίνη",
        "ru_name": "Подмаренник цепкий",
        "de_essence": "Boerickes Nieren- und Drüsenmittel: Zystitis, Harnsäuregrieß, Dysurie, verhärtete Drüsen und chronische Hautulzerationen.",
        "en_essence": "Boericke's diuretic and glandular remedy: cystitis with gravel, dysuria, indurated glands, and indolent cutaneous ulcers.",
        "indications_de": ["Zystitis mit Stein- und Grießbildung", "Verhärtete Lymphknoten", "Chronische Ulzera & Psoriasis"],
        "indications_en": ["Cystitis with painful gravel", "Hard nodular lymph glands", "Indolent skin ulcers and scaly eruptions"],
        "keynotes_de": ["Schmerzhafte Miktion mit Harngrieß", "Verhärtete Drüsen an Hals und Leiste", "Reinigt Haut und Nieren bei Stoffwechselschlacken"],
        "keynotes_en": ["Dysuria with burning in bladder and sand in urine", "Stony induration of lymphoid tissues", "Favors healthy granulations in chronic ulcers"],
        "better_de": ["Reichliche Flüssigkeitszufuhr"],
        "better_en": ["Abundant water intake"],
        "worse_de": ["Kälte", "Feuchtigkeit"],
        "worse_en": ["Cold", "Dampness"],
        "diff": ["Uva ursi", "Chimaphila", "Phytolacca"],
        "sphere": ["Blase", "Nieren", "Lymphdrüsen", "Haut"],
        "tier": 3
    },
    {
        "id": "gentiana-lutea",
        "latin": "Gentiana lutea",
        "cat": "plant",
        "de_name": "Gelber Enzian",
        "en_name": "Yellow Gentian",
        "es_name": "Genciana amarilla",
        "fr_name": "Gentiane jaune",
        "it_name": "Genziana maggiore",
        "el_name": "Γεντιανή η κίτρινη",
        "ru_name": "Горечавка жёлтая",
        "de_essence": "Boerickes Magentonikum: Atonische Dyspepsie mit Völlegefühl, saurem Aufstoßen, Appetitlosigkeit und Blähungskoliken.",
        "en_essence": "Boericke's gastric tonic: atonic dyspepsia with flatulent distension, acid eructations, anorexia, and dragging colics.",
        "indications_de": ["Atonische Dyspepsie & Magenschwäche", "Appetitmangel bei Rekonvaleszenz", "Schmerzhafte Blähungen"],
        "indications_en": ["Atonic dyspepsia and gastric debility", "Anorexia in convalescence", "Painful flatulent abdominal colic"],
        "keynotes_de": ["Magen fühlt sich schwer, voll und schlaff an", "Saures, bitteres Aufstoßen nach jeder Nahrung", "Heißhunger wechselt mit völlem Ekel ab"],
        "keynotes_en": ["Sensation of fullness and dragging weight in epigastrium", "Acid bitter eructations and slow digestion", "Ravenous hunger alternating with repugnance to food"],
        "better_de": ["Nach dem Essen", "Frische Luft"],
        "better_en": ["After eating", "Open air"],
        "worse_de": ["Nüchterner Magen", "Nachmittags"],
        "worse_en": ["Fasting", "Afternoon"],
        "diff": ["Hydrastis", "Nux vomica", "China"],
        "sphere": ["Magen", "Pfortadersystem", "Dünndarm"],
        "tier": 2
    },
    {
        "id": "geranium-maculatum",
        "latin": "Geranium maculatum",
        "cat": "plant",
        "de_name": "Gefleckter Storchschnabel",
        "en_name": "Spotted Cranesbill",
        "es_name": "Geranio manchado",
        "fr_name": "Géranium maculé",
        "it_name": "Geranio macchiato",
        "el_name": "Γεράνιον το κηλιδωτόν",
        "ru_name": "Герань пятнистая",
        "de_essence": "Boerickes starkes Adstringens und Hämostyptikum: Magenbluten (Hämatemesis), Hämoptysen, chronische Diarrhoe und Schwindel.",
        "en_essence": "Boericke's powerful astringent and styptic: gastric hemorrhage (hematemesis), hemoptysis, chronic camp diarrhea, and diplopia.",
        "indications_de": ["Bluterbrechen (Hämatemesis)", "Lungenblutung (Hämoptoe)", "Chronischer Durchfall mit Schleim"],
        "indications_en": ["Hematemesis and gastric ulcer bleeding", "Hemoptysis and pulmonary oozing", "Chronic camp diarrhea with mucous stools"],
        "keynotes_de": ["Rasches Stillen von Blutungen aus Magen und Lunge", "Schwindel mit Doppeltsehen beim schnellen Gehen", "Chronische Diarrhoe schwächt den Körper kachektisch"],
        "keynotes_en": ["Prompt arrest of passive venous hemorrhages from stomach or lungs", "Giddiness with diplopia on rapid motion", "Continuous watery diarrhea with severe exhaustion"],
        "better_de": ["Absolute Bettruhe"],
        "better_en": ["Bed rest"],
        "worse_de": ["Bewegung", "Schnelles Gehen"],
        "worse_en": ["Motion", "Walking fast"],
        "diff": ["Hamamelis", "Hydrastis", "Ipecacuanha"],
        "sphere": ["Magenschleimhaut", "Lunge", "Darm"],
        "tier": 2
    },
    {
        "id": "grindelia-robusta",
        "latin": "Grindelia robusta",
        "cat": "plant",
        "de_name": "Robustes Kaugummi-Kraut",
        "en_name": "Rosin-Wood / Gum-Plant",
        "es_name": "Grindelia",
        "fr_name": "Grindélia",
        "it_name": "Grindelia",
        "el_name": "Γρινδελία η ισχυρά",
        "ru_name": "Гринделия мощная",
        "de_essence": "Boerickes Leitsymptom: Erstickungsangst beim Einschlafen; hört auf zu atmen, sobald er einschläft, und erwacht nach Luft ringend.",
        "en_essence": "Boericke's hallmark: respiratory arrest on falling asleep; ceases breathing the moment sleep approaches and wakes gasping for breath.",
        "indications_de": ["Schlafapnoe & Einschlaferstickung", "Bronchialasthma mit Schleimrasseln", "Cheyne-Stokes-Atmung"],
        "indications_en": ["Sleep apnea and suffocation on falling asleep", "Bronchial asthma with loud mucus rattling", "Cheyne-Stokes breathing in cardiac cases"],
        "keynotes_de": ["Sobald der Patient einschläft, setzt der Atem aus; muss erschrocken aufspringen", "Erstickungshusten mit klebrigem Schleimauswurf", "Herz- und Lungenfunktionsstörung"],
        "keynotes_en": ["Stops breathing on dropping off to sleep; wakes gasping and terrified", "Violent asthmatic attacks with tenacious expectoration", "Heart weak, irregular, with suffocative paroxysms"],
        "better_de": ["Aufrechtes Sitzen", "Husten von Schleim"],
        "better_en": ["Sitting erect", "Expectoration of mucus"],
        "worse_de": ["Beim Einschlafen", "Flaches Liegen"],
        "worse_en": ["Falling asleep", "Lying flat"],
        "diff": ["Lachesis", "Arsenicum album", "Carbo vegetabilis"],
        "sphere": ["Atemzentrum", "Vagusnerv", "Bronchien", "Herz"],
        "tier": 1
    }
]
