# -*- coding: utf-8 -*-
# Boericke remedies for Part 25 (remedies 100 to 132: G - J)

PART25_REMEDIES = [
    {
        "id": "guaco",
        "latin": "Guaco",
        "cat": "plant",
        "de_name": "Mikania guaco",
        "en_name": "Climbing Hempweed",
        "es_name": "Guaco",
        "fr_name": "Guaco",
        "it_name": "Guaco",
        "el_name": "Γκουάκο",
        "ru_name": "Гуако",
        "de_essence": "Rückenmarkserkrankungen, spinale Reizung, Lähmungsgefühl der Beine, Neuralgien und Gegengift bei Schlangenbissen.",
        "en_essence": "Spinal irritation, nervous paralysis of lower limbs, severe brachial neuralgias, and antidote to venomous bites.",
        "indications_de": ["Spinale Reizung & Rückenschmerz", "Parästhesien & Schwäche der Beine", "Neuralgien von Hals und Armen"],
        "indications_en": ["Spinal irritation with burning in back", "Paretic weakness and heaviness of limbs", "Brachial and cervico-facial neuralgias"],
        "keynotes_de": ["Brennender Schmerz entlang der Wirbelsäule", "Schwere und Gehunfähigkeit der Beine", "Zuckungen und Kribbeln in den Händen"],
        "keynotes_en": ["Severe burning along spine from occiput down", "Paralytic heaviness of lower extremities", "Tearing neuralgias along upper extremities"],
        "better_de": ["Wärme", "Ruhe"],
        "better_en": ["Warmth", "Rest"],
        "worse_de": ["Bewegung", "Kälte", "Nachts"],
        "worse_en": ["Motion", "Cold", "Night"],
        "diff": ["Oxalicum acidum", "Secale", "Zincum"],
        "sphere": ["Rückenmark", "Periphere Nerven", "Wirbelsäule"],
        "tier": 3
    },
    {
        "id": "guarea-trichilioides",
        "latin": "Guarea trichilioides",
        "cat": "plant",
        "de_name": "Ballonholz",
        "en_name": "Ball Wood",
        "es_name": "Guarea",
        "fr_name": "Bois rouge",
        "it_name": "Guarea",
        "el_name": "Γκουαρέα",
        "ru_name": "Гварея",
        "de_essence": "Augenaffektionen: Chemosis, geschwollene Konjunktiven, Sehstörungen, Keuchhusten und Erbrechen nach Husten.",
        "en_essence": "Ocular chemosis, conjunctival engorgement, visual distortions, spasmodic whooping cough with vomiting.",
        "indications_de": ["Chemosis der Augenbindehaut", "Konjunktivitis mit Schwellung", "Spasmodischer Keuchhusten"],
        "indications_en": ["Chemosis and conjunctival hypertrophy", "Swollen lids and visual cloudiness", "Whooping cough ending in vomiting"],
        "keynotes_de": ["Bindehaut wie ein wassergefüllter Sack geschwollen", "Objekte erscheinen grau oder verzerrt", "Hustenanfall endet mit Erbrechen von Nahrung"],
        "keynotes_en": ["Chemosis; conjunctiva elevated around cornea like a bladder", "Grey haze before sight; objects appear distorted", "Suffocative cough with vomiting of food"],
        "better_de": ["Kühle Umschläge"],
        "better_en": ["Cool compresses"],
        "worse_de": ["Licht", "Wärme"],
        "worse_en": ["Light", "Warmth"],
        "diff": ["Apis mellifica", "Euphrasia", "Drosera"],
        "sphere": ["Augen", "Konjunktiven", "Bronchien"],
        "tier": 3
    },
    {
        "id": "guatteria-gaumeri",
        "latin": "Guatteria gaumeri",
        "cat": "plant",
        "de_name": "Yumel",
        "en_name": "Yumel",
        "es_name": "Yumel",
        "fr_name": "Yumel",
        "it_name": "Yumel",
        "el_name": "Γκουατέρια",
        "ru_name": "Гуаттерия Гаумера",
        "de_essence": "Boerickes Cholesterinsänker: Hypercholesterinämie, Gallensteine, Fettstoffwechselstörungen und Leberverfettung.",
        "en_essence": "Boericke's celebrated cholesterol regulator: hypercholesterolemia, cholelithiasis, and fatty liver degeneration.",
        "indications_de": ["Erhöhtes Cholesterin", "Gallensteine (Cholelithiasis)", "Fettleber & Lebervergrößerung"],
        "indications_en": ["Hypercholesterolemia", "Biliary calculi and gravel", "Fatty liver degeneration"],
        "keynotes_de": ["Normalisiert chronisch erhöhte Blutfette", "Druckempfindlichkeit im rechten Oberbauch", "Reguliert den Fettstoffwechsel der Leber"],
        "keynotes_en": ["Acts effectively to lower blood cholesterol levels", "Tenderness over gall-bladder region", "Aids elimination of biliary stones"],
        "better_de": ["Leichte Kost", "Bewegung"],
        "better_en": ["Light diet", "Gentle exercise"],
        "worse_de": ["Fettige Speisen", "Alkohol"],
        "worse_en": ["Rich fatty food", "Alcohol"],
        "diff": ["Cholesterinum", "Chelidonium", "Carduus marianus"],
        "sphere": ["Leber", "Gallenblase", "Lipidstoffwechsel"],
        "tier": 2
    },
    {
        "id": "gymnocladus-canadensis",
        "latin": "Gymnocladus canadensis",
        "cat": "plant",
        "de_name": "Geweihbaum",
        "en_name": "Kentucky Coffee Tree",
        "es_name": "Cafetero de Kentucky",
        "fr_name": "Chicot du Canada",
        "it_name": "Albero del caffè del Kentucky",
        "el_name": "Γυμνόκλαδος ο καναδικός",
        "ru_name": "Бундук канадский",
        "de_essence": "Scharlachartige Ausschläge, Halsschmerzen mit dunkelroter Schwellung, Stirnkopfschmerz und zerschlagenes Gefühl.",
        "en_essence": "Scarlatinal eruptions, dark bluish throat inflammation, throbbing frontal headache, and bruised heaviness.",
        "indications_de": ["Scharlachartiges Exanthem", "Schwere Pharyngitis & Angina", "Stirnkopfschmerz mit Augendruck"],
        "indications_en": ["Scarlatinal exanthem", "Dark livid sore throat", "Throbbing frontal headache over eyebrows"],
        "keynotes_de": ["Rachen dunkelrot bis bläulich geschwollen", "Brennen und Stechen im Hals beim Schlucken", "Haut brennt und schält sich scharlachartig ab"],
        "keynotes_en": ["Livid, bluish discoloration of fauces and tonsils", "Sore bruised feeling in muscles and eyeballs", "Erysipelatous and scarlatinal skin redness"],
        "better_de": ["Kühle Luft"],
        "better_en": ["Cool air"],
        "worse_de": ["Wärme", "Schlucken", "Licht"],
        "worse_en": ["Warmth", "Swallowing", "Light"],
        "diff": ["Belladonna", "Lachesis", "Ailanthus"],
        "sphere": ["Rachen", "Haut", "Gehirn"],
        "tier": 3
    },
    {
        "id": "haematoxylon-campechianum",
        "latin": "Haematoxylon campechianum",
        "cat": "plant",
        "de_name": "Blauholzbaum",
        "en_name": "Logwood",
        "es_name": "Palo de Campeche",
        "fr_name": "Bois de Campêche",
        "it_name": "Campeggio",
        "el_name": "Αιματόξυλον το καμπεκιανόν",
        "ru_name": "Кампешевое дерево",
        "de_essence": "Krampfhafte Enge in Brust und Magen, Gefühl einer Eisenstange quer über den Brustkorb und schmerzhafte Dysmenorrhoe.",
        "en_essence": "Constriction of chest and stomach; feeling of an iron bar across chest, and painful spasmodic dysmenorrhea.",
        "indications_de": ["Brustbeklemmung mit Engegefühl", "Krampfhafter Magenschmerz", "Dysmenorrhoe mit Frösteln"],
        "indications_en": ["Sensation of a bar across chest", "Gastralgia with spasmodic tightening", "Spasmodic dysmenorrhea"],
        "keynotes_de": ["Gefühl als liege eine schwere Eisenstange quer über der Brust", "Krampfhaftes Zusammenziehen des Magens nach dem Essen", "Frösteln mit Kreuzschmerzen während der Menses"],
        "keynotes_en": ["Constriction across chest as if squeezed by an iron band", "Gastric cramps extending to throat", "Colic with painful chilliness during menses"],
        "better_de": ["Wärme", "Bücken"],
        "better_en": ["Warmth", "Bending forward"],
        "worse_de": ["Kälte", "Nach dem Essen"],
        "worse_en": ["Cold", "After meals"],
        "diff": ["Cactus grandiflorus", "Lilium tigrinum"],
        "sphere": ["Brustkorb", "Herz", "Magen"],
        "tier": 3
    },
    {
        "id": "hamamelis-virginiana",
        "latin": "Hamamelis virginiana",
        "cat": "plant",
        "de_name": "Virginische Zaubernuss",
        "en_name": "Witch-Hazel",
        "es_name": "Hamamelis",
        "fr_name": "Hamamélis de Virginie",
        "it_name": "Amamelide",
        "el_name": "Αμαμηλίς η παρθενική",
        "ru_name": "Гамамелис виргинский",
        "de_essence": "Boerickes oberstes Venenmittel: Passive venöse Blutungen mit dunklem, nicht gerinnendem Blut; Varizen, Hämorrhoiden und Zerschlagenheitsschmerz.",
        "en_essence": "Boericke's pre-eminent venous remedy: passive venous oozing of dark, uncoagulated blood; varicosities, thrombophlebitis, and bruised soreness.",
        "indications_de": ["Varikose & Phlebitis", "Blutende schmerzhafte Hämorrhoiden", "Passive venöse Blutungen"],
        "indications_en": ["Varicose veins and phlebitis", "Bleeding, protruding hemorrhoids", "Passive venous hemorrhages"],
        "keynotes_de": ["Venen prall gestaut, knotig geschwollen und wund", "Passiver Abgang von dunklem, zähflüssigem Venenblut", "Gefühl von Zerschlagenheit und Wundheit in den betroffenen Partien"],
        "keynotes_en": ["Veins engorged, painful, dilated, and knotty", "Passive, slow, dark venous hemorrhage from any mucous surface", "Intense bruised soreness in affected veins"],
        "better_de": ["Ruhelage mit Hochlagerung"],
        "better_en": ["Rest with elevation of limbs"],
        "worse_de": ["Wärme", "Berührung", "Bewegung"],
        "worse_en": ["Warmth", "Touch", "Motion"],
        "diff": ["Pulsatilla", "Vipera", "Collinsonia", "Aesculus"],
        "sphere": ["Venensystem", "Rektum", "Haut", "Blut"],
        "tier": 1
    },
    {
        "id": "hecla-lava",
        "latin": "Hecla lava",
        "cat": "mineral",
        "de_name": "Hecla-Lava",
        "en_name": "Lava from Mount Hecla",
        "es_name": "Lava del Monte Hekla",
        "fr_name": "Lave de l'Hekla",
        "it_name": "Lava dell'Hekla",
        "el_name": "Λάβα της Χέκλα",
        "ru_name": "Гекла лава",
        "de_essence": "Boerickes Knochenspezifikum: Exostosen, Knochentumore, Periostitis, Kiefernekrosen, Fersensporn und Zahngeschwüre.",
        "en_essence": "Boericke's premier bone remedy: exostoses, osteitis, periostitis of jaws, calcaneal spurs, bone tumors, and dental abscesses.",
        "indications_de": ["Fersensporn & Exostosen", "Kiefernekrose & Zahngeschwüre", "Periostitis & Knochenschmerzen"],
        "indications_en": ["Calcaneal spur (heel spur)", "Exostosis of jaw and facial bones", "Severe dental abscess and periostitis"],
        "keynotes_de": ["Knochenwucherungen und stechende Fersensporn-Schmerzen", "Kieferschwellung nach Zahnextraktion oder Karies", "Boericke: 'Besonders wirksam bei Knochenerkrankungen des Kiefers'"],
        "keynotes_en": ["Exostoses, nodosities, and painful heel spurs", "Swelling of jaws and alveolar periosteum", "Boericke: 'Acts specifically on bones of jaw and facial skeleton'"],
        "better_de": ["Wärme", "Ruhelage"],
        "better_en": ["Warmth", "Rest"],
        "worse_de": ["Druck", "Berührung", "Kauen"],
        "worse_en": ["Pressure", "Touch", "Chewing"],
        "diff": ["Silicea", "Calcarea fluorica", "Mercurius", "Symphytum"],
        "sphere": ["Knochen", "Kiefer", "Periost", "Zähne"],
        "tier": 1
    },
    {
        "id": "hedeoma-pulegioides",
        "latin": "Hedeoma pulegioides",
        "cat": "plant",
        "de_name": "Amerikanischer Poleiminze",
        "en_name": "Pennyroyal",
        "es_name": "Poleo americano",
        "fr_name": "Pouliot américain",
        "it_name": "Pulegio americano",
        "el_name": "Ηδεώμα",
        "ru_name": "Хедеома полевая",
        "de_essence": "Amenorrhoe nach Durchnässung der Füße, quälende Wehenschmerzen mit Erbrechen und Nierenkolik.",
        "en_essence": "Amenorrhea from catching cold in feet, false dragging labor pains, intense nausea, and renal tenesmus.",
        "indications_de": ["Amenorrhoe durch Kälte an den Füßen", "Schwangerschaftserbrechen", "Nierenkolik mit Brennen"],
        "indications_en": ["Suppressed menses from wet feet", "Gastric nausea of pregnancy", "Renal colic radiating to bladder"],
        "keynotes_de": ["Menses bleiben nach nassen Füßen aus; Ziehen im Kreuz", "Ständige Übelkeit beim Anblick von Speisen", "Schneidender Schmerz von den Ureteren in die Oberschenkel"],
        "keynotes_en": ["Sudden amenorrhea after wet cold feet", "Obstinate nausea with retching and faintness", "Ureteral colic cutting through to thighs"],
        "better_de": ["Heiße Fußbäder", "Ruhe"],
        "better_en": ["Hot foot-baths", "Rest"],
        "worse_de": ["Kälte", "Nässe", "Bewegung"],
        "worse_en": ["Cold", "Wet feet", "Motion"],
        "diff": ["Pulsatilla", "Sepia", "Caulophyllum"],
        "sphere": ["Uterus", "Magen", "Nierenwege"],
        "tier": 3
    },
    {
        "id": "heliotropium-peruvianum",
        "latin": "Heliotropium peruvianum",
        "cat": "plant",
        "de_name": "Vanilleblume",
        "en_name": "Peruvian Heliotrope",
        "es_name": "Heliotropo del Perú",
        "fr_name": "Héliotrope du Pérou",
        "it_name": "Eliotropio peruviano",
        "el_name": "Ηλιοτρόπιον το περουβιανόν",
        "ru_name": "Гелиотроп перуанский",
        "de_essence": "Uterine Kongestionen, Schmerzen in der Gebärmutter, Zystitis mit schmerzhafter Strangurie und Enuresis.",
        "en_essence": "Uterine engorgement, bearing down, acute and chronic cystitis with strangury, and enuresis.",
        "indications_de": ["Uterusdrängen & Senkung", "Zystitis mit schmerzhafter Miktion", "Spasmodischer Husten"],
        "indications_en": ["Uterine bearing down and congestion", "Cystitis with severe dysuria", "Spasmodic dry cough"],
        "keynotes_de": ["Druckgefühl im Becken wie vor Menses", "Schmerzhafte Harnentleerung Tropfen für Tropfen", "Nervöse Unruhe"],
        "keynotes_en": ["Bearing down in hypogastrium", "Urination painful with constant straining", "Nervous anxiety"],
        "better_de": ["Ruhelage"],
        "better_en": ["Rest"],
        "worse_de": ["Stehen", "Gehen"],
        "worse_en": ["Standing", "Walking"],
        "diff": ["Sepia", "Lilium tigrinum"],
        "sphere": ["Uterus", "Harnblase"],
        "tier": 3
    },
    {
        "id": "hydrangea-arborescens",
        "latin": "Hydrangea arborescens",
        "cat": "plant",
        "de_name": "Waldhortensie",
        "en_name": "Seven-Barks",
        "es_name": "Hortensia silvestre",
        "fr_name": "Hortensia sauvage",
        "it_name": "Ortensia arborea",
        "el_name": "Υδραγγεία η δενδροειδής",
        "ru_name": "Гортензия древовидная",
        "de_essence": "Boerickes Nierensteinmittel: Akute Nierenkolik, Harnsäuregrieß, weißer Bodensatz im Urin, Prostatavergrößerung und Schwindel.",
        "en_essence": "Boericke's celebrated kidney stone remedy: sharp renal colic, gravel, white amorphous urinary sediment, and prostatic hypertrophy.",
        "indications_de": ["Nierenkolik & Nephrolithiasis", "Harnsäuregrieß & Sediment", "Prostataadenom mit Schmerz"],
        "indications_en": ["Renal colic from calculi", "Gravel and white amorphous deposits", "Prostatic hypertrophy with urinary stoppage"],
        "keynotes_de": ["Akute krampfhafte Schmerzen in den Nieren mit Schüttelfrost", "Urin enthält reichlich weißen oder gelben Sand", "Schwierige Miktion bei vergrößerter Prostata"],
        "keynotes_en": ["Violent aching in kidneys accompanied by chilliness", "Profuse white deposit of phosphates and gravel in urine", "Great relief after passage of gravel"],
        "better_de": ["Nach Abgang von Sand/Grieß"],
        "better_en": ["After passing gravel"],
        "worse_de": ["Linke Seite", "Vor dem Wasserlassen"],
        "worse_en": ["Left side", "Before urination"],
        "diff": ["Berberis", "Sarsaparilla", "Pareira brava", "Solidago"],
        "sphere": ["Nieren", "Ureteren", "Harnblase", "Prostata"],
        "tier": 2
    },
    {
        "id": "hydrocotyle-asiatica",
        "latin": "Hydrocotyle asiatica",
        "cat": "plant",
        "de_name": "Indischer Wassernabel / Gotu Kola",
        "en_name": "Indian Pennywort / Gotu Kola",
        "es_name": "Centella asiática",
        "fr_name": "Centelle d'Asie",
        "it_name": "Centella asiatica",
        "el_name": "Υδροκοτύλη η ασιατική",
        "ru_name": "Центелла азиатская (Готу Кола)",
        "de_essence": "Boerickes Hauptmittel bei Psoriasis, Lepra, exzessiver Verdickung und Schuppung der Haut sowie Zervixhypertrophie.",
        "en_essence": "Boericke's premier remedy for psoriasis, follicular keratosis, cutaneous hypertrophy, scales, and cervical induration.",
        "indications_de": ["Psoriasis vulgaris & Psoriasis guttata", "Exzessive Verhornung & Schuppung", "Uterushalsverhärtung"],
        "indications_en": ["Psoriasis of palms, soles, and trunk", "Thick circular epidermal scales", "Hypertrophy and induration of cervix"],
        "keynotes_de": ["Dicke, trockene Hornschuppen blättern in kreisrunden Scheiben ab", "Unerträgliches Jucken besonders an den Sohlen", "Verdickung der Haut mit Rissen und Abschälung"],
        "keynotes_en": ["Immense circular crusts and dry scales exfoliating from skin", "Pruritus especially of palms and soles", "Induration of connective tissues and skin thickening"],
        "better_de": ["Ruhelage"],
        "better_en": ["Rest"],
        "worse_de": ["Wärme", "Berührung"],
        "worse_en": ["Warmth", "Touch"],
        "diff": ["Arsenicum album", "Berberis aquifolium", "Sepia"],
        "sphere": ["Haut", "Epidermis", "Bindegewebe", "Zervix"],
        "tier": 2
    },
    {
        "id": "hyoscyaminum",
        "latin": "Hyoscyaminum",
        "cat": "mineral",
        "de_name": "Hyoscyamin",
        "en_name": "Hyoscyamine",
        "es_name": "Hiosciamina",
        "fr_name": "Hyoscyamine",
        "it_name": "Giosciamina",
        "el_name": "Υοσκυαμίνη",
        "ru_name": "Гиосциамин",
        "de_essence": "Delirium mit Verfolgungswahn, Tremor, Schlaflosigkeit mit wirren Träumen, Muskelspasmen und spastischer Husten.",
        "en_essence": "Delirium with persecutory ideas, motor tremors, twitching of muscles, insomnia, and dry nocturnal cough.",
        "indications_de": ["Delirium tremens & Verwirrtheit", "Muskelzuckungen & Tremor", "Nervöse Schlaflosigkeit"],
        "indications_en": ["Delirium with suspicious illusions", "Muscular tremors and spasms", "Nervous sleeplessness"],
        "keynotes_de": ["Zittern der Hände und Zunge bei Aufregung", "Wahnhafte Furcht vergiftet zu werden", "Trockener, krampfhafter Husten nachts im Liegen"],
        "keynotes_en": ["Trembling of extremities with motor incoordination", "Delusional suspiciousness and hallucinations", "Dry nocturnal hacking cough worse lying down"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting upright"],
        "worse_de": ["Nachts", "Liegen", "Aufregung"],
        "worse_en": ["Night", "Lying flat", "Mental excitement"],
        "diff": ["Hyoscyamus niger", "Stramonium", "Agaricus"],
        "sphere": ["Gehirn", "Motorische Nerven", "Atemwege"],
        "tier": 3
    },
    {
        "id": "hypericum-perforatum",
        "latin": "Hypericum perforatum",
        "cat": "plant",
        "de_name": "Echtes Johanniskraut",
        "en_name": "St. John's Wort",
        "es_name": "Hierba de San Juan",
        "fr_name": "Millepertuis perforé",
        "it_name": "Iperico / Erba di San Giovanni",
        "el_name": "Υπερικόν το διάτρητον",
        "ru_name": "Зверобой продырявленный",
        "de_essence": "Boerickes 'Arnika der Nerven': Nervenverletzungen, Quetschungen von Fingern und Zehen, Steißbeinsturz, Zahnextraktion und Phantomschmerzen.",
        "en_essence": "Boericke's 'Arnica of the nerves': mechanical nerve trauma, crushed fingers and toes, falls on coccyx, post-extraction pain, and phantom limb pain.",
        "indications_de": ["Nervenverletzungen & Quetschwunden", "Steißbeintrauma & Sturz auf den Steiß", "Zahnschmerzen nach Zahnbehandlung"],
        "indications_en": ["Mechanical injuries of nerve-rich parts", "Fall on coccyx with exquisite tenderness", "Post-surgical and post-extraction neuralgias"],
        "keynotes_de": ["Schmerz schießt zentralwärts entlang des Nervenverlaufs", "Unerträglich stechende, reißende Nervenschmerzen", "Boericke: 'Verhindert Tetanus und lindert Nervenquetschung sofort'"],
        "keynotes_en": ["Darting, excruciating pains shooting proximally along nerve trunk", "Excessive painfulness of parts; cannot bear touch or pressure", "Boericke: 'The great remedy for crushed fingertips and coccyx injuries'"],
        "better_de": ["Ruhiges Liegen mit Kopf nach hinten"],
        "better_en": ["Lying quietly bending head backward"],
        "worse_de": ["Geringste Berührung", "Kälte", "Nebliges Wetter"],
        "worse_en": ["Slightest touch", "Cold dampness", "Fog"],
        "diff": ["Arnica", "Ledum", "Symphytum", "Rhus tox"],
        "sphere": ["Periphere Nerven", "Steißbein", "Zähne", "Gehirn"],
        "tier": 1
    },
    {
        "id": "iberis-amara",
        "latin": "Iberis amara",
        "cat": "plant",
        "de_name": "Bittere Schleifenblume",
        "en_name": "Bitter Candy-Tuft",
        "es_name": "Iberis amargo",
        "fr_name": "Ibéris amer",
        "it_name": "Iberide amara",
        "el_name": "Ιβηρίς η πικρά",
        "ru_name": "Иберис горький",
        "de_essence": "Boerickes Herzmittel: Herzhypertrophie, Tachykardie mit Erschütterung des Brustkorbs, Atemnot beim Bücken und kardiale Angst.",
        "en_essence": "Boericke's cardiac remedy: hypertrophy of heart, full bounding pulse jarring chest wall, choking dyspnea on turning or stooping.",
        "indications_de": ["Kardiale Hypertrophie & Tachykardie", "Herzstolpern bei Bewegung", "Präkordialschmerz mit Atemnot"],
        "indications_en": ["Cardiac hypertrophy and palpitation", "Irregular pounding heart jar", "Dyspnea on slightest exertion or stooping"],
        "keynotes_de": ["Herzschläge erschüttern den Hals und den ganzen Brustkorb", "Atemnot und Würgen beim geringsten Vorbeugen", "Puls voll, unregelmäßig, intermittierend"],
        "keynotes_en": ["Conscious of every heartbeat; jars whole frame up to throat", "Choking tightness in throat on stooping or walking", "Full bounding irregular pulse with vertigo"],
        "better_de": ["Frische kühle Luft", "Aufrechtes Ruhen"],
        "better_en": ["Cool open air", "Rest in sitting posture"],
        "worse_de": ["Liegen auf der linken Seite", "Bücken", "Aufstieg"],
        "worse_en": ["Lying on left side", "Stooping", "Ascending"],
        "diff": ["Digitalis", "Crataegus", "Spigelia", "Cactus"],
        "sphere": ["Herz", "Kreislaufsystem", "Atemwege"],
        "tier": 2
    },
    {
        "id": "ichthyolum",
        "latin": "Ichthyolum",
        "cat": "mineral",
        "de_name": "Ichthyol / Ammoniumbituminosulfonat",
        "en_name": "Ichthyol",
        "es_name": "Ictiol",
        "fr_name": "Ichthyol",
        "it_name": "Ittiolo",
        "el_name": "Ιχθυόλη",
        "ru_name": "Ихтиол",
        "de_essence": "Chronischer Rheumatismus, Arthritis deformans, chronische Bronchitis alter Menschen und schuppende Hautleiden.",
        "en_essence": "Chronic arthritis deformans, polyarthritis, winter cough of elderly, and dry scaly cutaneous eruptions.",
        "indications_de": ["Arthritis deformans & Gelenkschwellung", "Chronische Winterbronchitis", "Psoriasis & schuppendes Ekzem"],
        "indications_en": ["Chronic gouty arthritis and joint deformities", "Bronchial catarrh of elderly", "Psoriasis and chronic eczema"],
        "keynotes_de": ["Gelenke der Hände und Füße geschwollen, deformiert und schmerzhaft", "Zäher, übelriechender Auswurf bei alten Patienten", "Trockene, juckende, schuppende Haut"],
        "keynotes_en": ["Painful swelling and stiffness in deformative polyarthritis", "Cough with purulent offensive sputum in aged", "Dry scaly pruritic lesions on extremities"],
        "better_de": ["Wärme", "Trockenes Wetter"],
        "better_en": ["Warmth", "Dry weather"],
        "worse_de": ["Kälte", "Feuchtigkeit"],
        "worse_en": ["Cold", "Damp weather"],
        "diff": ["Sulfur", "Thuja", "Antimonium tartaricum"],
        "sphere": ["Gelenke", "Haut", "Bronchien"],
        "tier": 3
    },
    {
        "id": "ilicium-anisatum",
        "latin": "Ilicium anisatum",
        "cat": "plant",
        "de_name": "Sternanis",
        "en_name": "Star Anise",
        "es_name": "Anís estrellado",
        "fr_name": "Badiane de Chine",
        "it_name": "Anice stellato",
        "el_name": "Ιλλίκιον το ανισοειδές",
        "ru_name": "Анис звёздчатый",
        "de_essence": "Heftiger stechender Schmerz im dritten rechten Interkostalraum (Rippenknorpel), Blähungskoliken und Reizhusten.",
        "en_essence": "Sharp stitching pain in right third costal cartilage, flatulent infantile colic, and spasmodic cough.",
        "indications_de": ["Schmerz im 3. rechten Rippenknorpel", "Säuglings-Drei-Monats-Koliken", "Husten mit Pleurareiz"],
        "indications_en": ["Localized stitch in right third costal junction", "Infantile flatulent colic", "Cough with tough expectoration"],
        "keynotes_de": ["Punktförmiger stechender Schmerz rechts am 3. Rippenknorpel", "Blähungskoliken bei Babys mit Schreien und Krümmen", "Trockener, schmerzhafter Husten"],
        "keynotes_en": ["Well-defined acute stitch at third right costal cartilage", "Painful flatulent distension in young infants", "Hacking cough with bloody taste"],
        "better_de": ["Wärme am Bauch"],
        "better_en": ["Warmth to abdomen"],
        "worse_de": ["Tiefe Einatmung", "Bewegung"],
        "worse_en": ["Deep inspiration", "Motion"],
        "diff": ["Bryonia", "Colocynthis", "Chamomilla"],
        "sphere": ["Brustwand", "Interkostalnerven", "Darm"],
        "tier": 3
    },
    {
        "id": "indium-metallicum",
        "latin": "Indium metallicum",
        "cat": "mineral",
        "de_name": "Indium",
        "en_name": "Indium",
        "es_name": "Indio",
        "fr_name": "Indium",
        "it_name": "Indio",
        "el_name": "Ίνδιον",
        "ru_name": "Индий металлический",
        "de_essence": "Chronische Kopfschmerzen mit Schweregefühl, sexuelle Erschöpfung mit nächtlichen Samenergüssen und Rückenschmerz.",
        "en_essence": "Frontal and occipital heaviness, sexual debility with emissions, lumbar backache, and morning throat dryness.",
        "indications_de": ["Chronischer Stirnkopfschmerz", "Sexuelle Schwäche & Pollutionen", "Rückenschmerz im Lendenbereich"],
        "indications_en": ["Dull throbbing frontal headache", "Sexual debility with involuntary emissions", "Severe lumbar backache on rising"],
        "keynotes_de": ["Schmerz über den Augen breitet sich bis zum Scheitel aus", "Erschöpfung nach Samenerguss mit Knieschwäche", "Hals morgens trocken mit zähem Schleim"],
        "keynotes_en": ["Heavy pressing ache over eyes and temples", "Weakness of knees following nocturnal emissions", "Throat dry, sore, and tough to swallow on waking"],
        "better_de": ["Kaltes Wasser auf den Kopf", "Ruhe"],
        "better_en": ["Cold water applications to head", "Rest"],
        "worse_de": ["Nach dem Essen", "Bücken", "Geistige Anstrengung"],
        "worse_en": ["After eating", "Bending", "Mental work"],
        "diff": ["Selenium", "Acidum phosphoricum", "Zincum"],
        "sphere": ["Gehirn", "Männliche Genitalien", "Lendenwirbelsäule"],
        "tier": 3
    },
    {
        "id": "iris-versicolor",
        "latin": "Iris versicolor",
        "cat": "plant",
        "de_name": "Verschiedenfarbige Schwertlilie",
        "en_name": "Blue Flag",
        "es_name": "Lirio azul",
        "fr_name": "Iris versicolore",
        "it_name": "Giaggiolo americano",
        "el_name": "Ίρις η ποικιλόχρους",
        "ru_name": "Ирис разноцветный",
        "de_essence": "Boerickes Migränemittel: Periodische Wochenend-Migräne mit Sehstörungen (Aura), brennendem saurem Erbrechen und Pankreasreizung.",
        "en_essence": "Boericke's classic sick headache: Sunday/weekend migraine with visual aura, burning acid vomiting excoriating throat, and pancreatic distress.",
        "indications_de": ["Klassische Migräne mit Aura", "Hyperazidität mit saurem Erbrechen", "Akute und chronische Pankreatitis"],
        "indications_en": ["Periodical sick migraine with aura", "Burning acid gastralgia and vomiting", "Pancreatic salivation and greasy diarrhea"],
        "keynotes_de": ["Sehstörung oder Flimmern geht dem Kopfschmerz voraus", "Erbrochenes ist so sauer, dass es die Zähne stumpf macht und den Hals verbrennt", "Brennen im gesamten Verdauungstrakt von Mund bis Rektum"],
        "keynotes_en": ["Visual blurring or aura precedes frontal headache", "Vomitus intensely sour, scalding mouth, excoriating throat", "Burning throughout entire alimentary canal with fatty stools"],
        "better_de": ["Fortgesetzte Bewegung"],
        "better_en": ["Continued gentle motion"],
        "worse_de": ["Ruhe", "Ruhetage (Wochenende)", "Abends"],
        "worse_en": ["Rest", "Days of rest (weekends)", "Evening"],
        "diff": ["Kali bichromicum", "Pulsatilla", "Sanguinaria"],
        "sphere": ["Pankreas", "Magen", "Schläfennerven", "Galle"],
        "tier": 1
    },
    {
        "id": "jaborandi",
        "latin": "Jaborandi",
        "cat": "plant",
        "de_name": "Jaborandistrauch",
        "en_name": "Pilocarpus",
        "es_name": "Jaborandi",
        "fr_name": "Jaborandi",
        "it_name": "Gaborandi",
        "el_name": "Ιαβοράνδη",
        "ru_name": "Яборанди",
        "de_essence": "Boerickes Schweiß- und Speichelmittel: Profuser Schweiß, unstillbarer Speichelfluss, Akkommodationskrampf der Augen und Hitzewallungen.",
        "en_essence": "Boericke's supreme diaphoretic: profuse salivation, drenching sweats, ciliary spasm/myopia, and menopausal hot flushes.",
        "indications_de": ["Akkommodationskrämpfe der Augen", "Exzessiver Speichelfluss (Ptyalismus)", "Schwitzen & Hitzewallungen"],
        "indications_en": ["Spasm of accommodation and eyestrain", "Profuse ptyalism and salivation", "Drenching night-sweats and hot flashes"],
        "keynotes_de": ["Augenmuskeln krampfen nach feiner Naharbeit; Myopie", "Speichel und Schweiß fließen in Strömen", "Kopfschmerz nach Überanstrengung der Augen"],
        "keynotes_en": ["Extreme spasm of accommodation after fine sewing or reading", "Saliva pours out in mouthfuls with drenched perspiration", "Eye exhaustion with twitching of lids and blurred vision"],
        "better_de": ["Augenruhe"],
        "better_en": ["Resting eyes"],
        "worse_de": ["Naharbeit", "Künstliches Licht", "Kälte"],
        "worse_en": ["Near eye work", "Artificial light", "Cold"],
        "diff": ["Pilocarpinum", "Physostigma", "Ruta"],
        "sphere": ["Augenmuskeln", "Speicheldrüsen", "Schweißdrüsen"],
        "tier": 2
    },
    {
        "id": "jacaranda-caroba",
        "latin": "Jacaranda caroba",
        "cat": "plant",
        "de_name": "Karobabaum",
        "en_name": "Caroba",
        "es_name": "Jacarandá caroba",
        "fr_name": "Caroba",
        "it_name": "Caroba",
        "el_name": "Ιακαράνδα",
        "ru_name": "Жакаранда кароба",
        "de_essence": "Syphilitische und venerische Ulzera, Schwellung des Penis, rheumatische Gonorrhoe und Muskelsteifigkeit.",
        "en_essence": "Veneric ulcers, genital chancre, blennorrhagic rheumatism, and morning muscular stiffness.",
        "indications_de": ["Genitalgeschwüre & Schankeroide", "Urethritis mit Ausfluss", "Rheumatoide Muskelschmerzen"],
        "indications_en": ["Indurated genital ulcers", "Urethral discharge and chordee", "Muscular stiffness on morning rising"],
        "keynotes_de": ["Schmerzhafte Vorhautschwellung und Geschwüre", "Eitriger Ausfluss mit Schmerzen in der Leiste", "Steifheit und Ziehen in den Muskeln"],
        "keynotes_en": ["Prepuce painful, swollen, with irritable sores", "Purulent discharge with chordee and groin soreness", "Aching muscular soreness on waking"],
        "better_de": ["Wärme"],
        "better_en": ["Warmth"],
        "worse_de": ["Morgens", "Berührung"],
        "worse_en": ["Morning", "Touch"],
        "diff": ["Mercurius", "Thuja", "Nitricum acidum"],
        "sphere": ["Genitalien", "Schleimhäute", "Muskeln"],
        "tier": 3
    },
    {
        "id": "jalapa",
        "latin": "Jalapa",
        "cat": "plant",
        "de_name": "Jalape",
        "en_name": "Jalap",
        "es_name": "Jalapa",
        "fr_name": "Jalap",
        "it_name": "Gialappa",
        "el_name": "Ιαλάπα",
        "ru_name": "Ялапа",
        "de_essence": "Boerickes Kindermittel: Säuglinge sind tagsüber ruhig und brav, schreien und weinen aber die GANZE NACHT vor Bauchschmerzen.",
        "en_essence": "Boericke's infant keynote: child quiet all day, but SCREAMS AND CRIES ALL NIGHT from griping abdominal colic.",
        "indications_de": ["Nächtliche Säuglingskoliken", "Wässrige schmerzhafte Diarrhoe", "Rastlose nächtliche Unruhe"],
        "indications_en": ["Night screaming of infants from colic", "Watery griping diarrhea in children", "Restlessness and insomnia of babies"],
        "keynotes_de": ["Das Kind ist am Tag engelhaft, brüllt jedoch die gesamte Nacht durch", "Krampfhafte Schmerzen mit wässrigen, gärenden Stühlen", "Ziehen der Beinchen an den Bauch"],
        "keynotes_en": ["Child good all day, screams all night with colic", "Violent cramping around navel with watery stools", "Flexes legs onto abdomen from intense pain"],
        "better_de": ["Nach Entleerung von Stuhl und Wind"],
        "better_en": ["After passing stool and flatus"],
        "worse_de": ["Nachts"],
        "worse_en": ["At night"],
        "diff": ["Chamomilla", "Rheum", "Magnesia phosphorica"],
        "sphere": ["Darmtrakt", "Säuglingspsyche", "Vegetativum"],
        "tier": 2
    },
    {
        "id": "jonosia-asoca",
        "latin": "Jonosia asoca",
        "cat": "plant",
        "de_name": "Asokabaum",
        "en_name": "Bark of Asoka Tree",
        "es_name": "Árbol de Asoka",
        "fr_name": "Arbre d'Ashoka",
        "it_name": "Albero di Ashoka",
        "el_name": "Ασόκα",
        "ru_name": "Ашока",
        "de_essence": "Boerickes berühmtes indisches Frauenmittel: Zyklusstörungen, Amenorrhoe, Metrorrhagie, Uteruskongestion und Ovarialschmerz.",
        "en_essence": "Boericke's celebrated Indian female tonic: menstrual irregularities, amenorrhea, metrorrhagia, uterine colic, and ovarian aching.",
        "indications_de": ["Zyklusunregelmäßigkeiten & Amenorrhoe", "Metrorrhagie mit krampfhaften Schmerzen", "Ovarialneuralgie & Fluor albus"],
        "indications_en": ["Amenorrhea and delayed menses", "Uterine colic with profuse metrorrhagia", "Ovarian neuralgia and leucorrhea"],
        "keynotes_de": ["Reguliert die Menstruation sanft und zuverlässig", "Krampfhafte Wehenschmerzen im Unterbauch während der Menses", "Starke Erschöpfung und Kopfschmerz bei Mensesausfall"],
        "keynotes_en": ["Powerful regulator of female endocrine cycle", "Spasmodic labor-like bearing-down pains during flow", "Reflex congestive headaches with delayed menses"],
        "better_de": ["Frische Luft", "Ruhe"],
        "better_en": ["Open air", "Rest"],
        "worse_de": ["Vor und während der Menses"],
        "worse_en": ["Before and during menstruation"],
        "diff": ["Pulsatilla", "Sepia", "Aletris farinosa"],
        "sphere": ["Uterus", "Ovarien", "Weibliches Hormonsystem"],
        "tier": 2
    }
]
