# -*- coding: utf-8 -*-
# Boericke remedies for Part 23 (remedies 34 to 66: B - C)

PART23_REMEDIES = [
    {
        "id": "boletus-laricis",
        "latin": "Boletus laricis",
        "cat": "plant",
        "de_name": "Lärchenschwamm",
        "en_name": "White Agaric",
        "es_name": "Agarico blanco",
        "fr_name": "Agaric blanc",
        "it_name": "Agarico bianco",
        "el_name": "Αγαρικόν των λαρύκων",
        "ru_name": "Лиственничная губка",
        "de_essence": "Erschöpfende Nachtschweiße bei Phthisis, Gallenstauung, Kopfschmerz und intermittierendes Fieber.",
        "en_essence": "Exhausting night-sweats in phthisis, hepatic congestion, dull frontal headache, and intermittent fever.",
        "indications_de": ["Schwächende Nachtschweiße", "Gallenstau & Ikterus", "Intermittierendes Fieber"],
        "indications_en": ["Exhausting night-sweats", "Hepatic congestion with bitter taste", "Intermittent fever with prostration"],
        "keynotes_de": ["Kalter, klebriger Nachtschweiß schwächt den Körper", "Druckschmerz in der Lebergegend mit Ikterus", "Stumpfer Stirnkopfschmerz am Morgen"],
        "keynotes_en": ["Profuse drenching night-sweats in chest complaints", "Tenderness over liver with yellow tongue", "Dull heavy frontal ache"],
        "better_de": ["Ruhelage"],
        "better_en": ["Quiet rest"],
        "worse_de": ["Nachts", "Körperliche Bewegung"],
        "worse_en": ["Night", "Physical motion"],
        "diff": ["Cinchona", "Acidum phosphoricum", "Agaricus"],
        "sphere": ["Haut", "Leber", "Schweißdrüsen"],
        "tier": 3
    },
    {
        "id": "bothrops-lanceolatus",
        "latin": "Bothrops lanceolatus",
        "cat": "animal",
        "de_name": "Lanzenotter",
        "en_name": "Yellow Viper",
        "es_name": "Víbora de foseta / Fer-de-lance",
        "fr_name": "Fer de lance",
        "it_name": "Vipera lanceolata",
        "el_name": "Λογχοκέφαλος έχιδνα",
        "ru_name": "Ботропс ланцетовидный",
        "de_essence": "Zerebrale Thrombosen, Apoplexie mit Aphasie (Sprachverlust ohne Zungenlähmung), Amaurose und septische Nekrosen.",
        "en_essence": "Cerebral thrombosis, hemiplegia with complete aphasia (inability to articulate words), amaurosis, and septic necrosis.",
        "indications_de": ["Apoplexie & Schlaganfall mit Aphasie", "Zerebrale Thrombosen", "Maligne Phlegmone"],
        "indications_en": ["Stroke with motor aphasia", "Cerebral and peripheral thrombosis", "Septic gangrenous cellulitis"],
        "keynotes_de": ["Versteht alles, kann aber kein Wort hervorbringen (Aphasie)", "Plötzliche Erblindung nach Thrombose", "Schwarze, nekrotische Hautinfiltrate"],
        "keynotes_en": ["Understands spoken words but unable to utter speech (motor aphasia)", "Day-blindness, amaurosis from thrombosis", "Dark fluid blood oozing from orifices"],
        "better_de": ["Ruhige Lage"],
        "better_en": ["Quiet rest"],
        "worse_de": ["Aufregung", "Bewegung"],
        "worse_en": ["Excitement", "Motion"],
        "diff": ["Lachesis", "Crotalus horridus", "Baryta carbonica"],
        "sphere": ["Zerebrale Gefäße", "Sprachzentrum", "Blutgerinnung"],
        "tier": 2
    },
    {
        "id": "bovista-gigantea",
        "latin": "Bovista gigantea",
        "cat": "plant",
        "de_name": "Riesenbovist",
        "en_name": "Puff-Ball",
        "es_name": "Bovista gigante",
        "fr_name": "Vesse-de-loup géante",
        "it_name": "Vescia gigante",
        "el_name": "Βοβίστα η γιγαντιαία",
        "ru_name": "Порховка гигантская",
        "de_essence": "Urtikaria bei Aufregung, Schwellungsgefühl, Ungeschicklichkeit der Hände (lässt Gegenstände fallen) und Metrorrhagien.",
        "en_essence": "Urticaria excited by emotion, sensation of puffiness, awkwardness of hands (drops objects), and intermenstrual bleeding.",
        "indications_de": ["Urtikaria nach Waschen oder Erregung", "Ungeschicklichkeit der Hände", "Metrorrhagie zwischen den Perioden"],
        "indications_en": ["Urticaria on excitement or washing", "Awkwardness of hands and dropping things", "Intermenstrual hemorrhage"],
        "keynotes_de": ["Gefühl als sei der Körper oder Kopf riesig geschwollen", "Hände so kraftlos und ungeschickt, dass Scheren und Tassen fallen", "Quälende Nesselsucht am ganzen Körper"],
        "keynotes_en": ["Sensation as if whole body or head were enormously enlarged", "Paralytic clumsiness of hands; drops cups and pens", "Urticaria with intolerable itching, worse bathing"],
        "better_de": ["Bücken", "Warme Speisen"],
        "better_en": ["Bending double", "Warm food"],
        "worse_de": ["Waschen und Wasser", "Vollmond", "Am frühen Morgen"],
        "worse_en": ["Washing", "Full moon", "Early morning"],
        "diff": ["Apis mellifica", "Rhus tox", "Sepia"],
        "sphere": ["Haut", "Venen", "Motorische Nerven", "Uterus"],
        "tier": 2
    },
    {
        "id": "brachyglottis-repens",
        "latin": "Brachyglottis repens",
        "cat": "plant",
        "de_name": "Puka-Puka",
        "en_name": "Puka-Puka",
        "es_name": "Puka-Puka",
        "fr_name": "Puka-Puka",
        "it_name": "Puka-Puka",
        "el_name": "Βραχυγλωττίς",
        "ru_name": "Брахиглоттис",
        "de_essence": "Nierenaffektionen mit Albuminurie, dumpfem Schmerz in der Nierengegend und ständigem Harndrang.",
        "en_essence": "Renal affections with albuminuria, aching tenderness in lumbar kidney region, and constant bladder pressure.",
        "indications_de": ["Albuminurie & Zystitis", "Nierenschmerz mit Druck", "Schwäche im Kreuz"],
        "indications_en": ["Albuminuria and cystitis", "Aching kidney pain", "Lumbar weakness with dragging"],
        "keynotes_de": ["Schmerzhafte Zerrüttung in der Nierengegend", "Urin enthält Schleim, Eiweiß und Zylinder", "Ständiger Miktionsdrang mit Schmerz in der Urethra"],
        "keynotes_en": ["Sore aching pain in back across lumbar region", "Urine contains albumen, casts, and lithates", "Urgent urge with soreness in bladder neck"],
        "better_de": ["Ausruhen im Sitzen"],
        "better_en": ["Resting seated"],
        "worse_de": ["Gehen", "Kälte"],
        "worse_en": ["Walking", "Cold"],
        "diff": ["Helonias", "Terebinthina", "Berberis"],
        "sphere": ["Nieren", "Blase", "Harnwege"],
        "tier": 3
    },
    {
        "id": "cahinca",
        "latin": "Cahinca",
        "cat": "plant",
        "de_name": "Kainkawurzel",
        "en_name": "Snowberry / Chiococca",
        "es_name": "Cainca",
        "fr_name": "Cahinca",
        "it_name": "Cainca",
        "el_name": "Καΐνκα",
        "ru_name": "Каинка",
        "de_essence": "Wassersucht, Aszites und kardiale Ödeme mit verminderter Harnausscheidung und ständiger Atemnot.",
        "en_essence": "Renal and cardiac dropsy with oliguria, severe dyspnea on walking, and digestive oppression.",
        "indications_de": ["Wassersucht & Hydrops", "Ödeme bei Nierenschwäche", "Miktionsbeschwerden"],
        "indications_en": ["General dropsy and ascites", "Edema of kidney weakness", "Dysuria and scanty urine"],
        "keynotes_de": ["Plötzlich auftretende Ödeme mit Urinmangel", "Schwere Atemnot beim Gehen", "Ständiger Drang bei minimaler Urinausscheidung"],
        "keynotes_en": ["Rapid accumulation of fluids with suppressed urine", "Dyspnea on moderate walking", "Frequent urging with dripping urine"],
        "better_de": ["Reichliche Diurese"],
        "better_en": ["Free flow of urine"],
        "worse_de": ["Bewegung", "Feuchtes Wetter"],
        "worse_en": ["Motion", "Damp weather"],
        "diff": ["Apocynum", "Digitalis", "Bryonia"],
        "sphere": ["Nieren", "Seröse Häute", "Herz"],
        "tier": 3
    },
    {
        "id": "caladium-seguinum",
        "latin": "Caladium seguinum",
        "cat": "plant",
        "de_name": "Dieffenbachie",
        "en_name": "American Arum",
        "es_name": "Caladio",
        "fr_name": "Caladium",
        "it_name": "Caladio",
        "el_name": "Καλάδιον",
        "ru_name": "Каладиум",
        "de_essence": "Erektile Impotenz bei erhaltener sexueller Erregung; unerträglicher Juckreiz der Genitalien und Abneigung gegen Tabak.",
        "en_essence": "Erectile failure with active desire; intolerable pruritus vulvae or scroti, and aversion to tobacco.",
        "indications_de": ["Impotenz bei starkem Verlangen", "Pruritus vulvae & scroti", "Tabakabneigung & Herzklopfen"],
        "indications_en": ["Erectile impotence with desire", "Pruritus vulvae et scroti", "Tobacco heart and craving/aversion"],
        "keynotes_de": ["Glied erschlafft während der Erregung", "Quälendes Jucken der Genitalien, schlimmer bei Wärme", "Tabakrauch erzeugt Herzklopfen und Übelkeit"],
        "keynotes_en": ["Organs relaxed during sexual excitement; cold relaxed penis", "Maddening pruritus of vulva/scrotum", "Aversion to tobacco smoke which induces tremors"],
        "better_de": ["Schlaf am Tage"],
        "better_en": ["Short sleep during day"],
        "worse_de": ["Wärme", "Tabak", "Liegen"],
        "worse_en": ["Warmth", "Tobacco smoke", "Lying down"],
        "diff": ["Agnum castus", "Selenium", "Lycopodium"],
        "sphere": ["Männliche & weibliche Genitalien", "Haut", "Nervensystem"],
        "tier": 2
    },
    {
        "id": "calotropis-gigantea",
        "latin": "Calotropis gigantea",
        "cat": "plant",
        "de_name": "Mudar",
        "en_name": "Mudar Bark",
        "es_name": "Mudar",
        "fr_name": "Mudar",
        "it_name": "Mudar",
        "el_name": "Καλότροπος η γιγαντιαία",
        "ru_name": "Калотропис гигантский",
        "de_essence": "Chronische Hauterkrankungen, Lupus, Lepra und syphilitische Knochenschmerzen mit Kachexie.",
        "en_essence": "Lupus, tubercular skin lesions, severe ulcerations, and osteocopic pains with chronic cachexia.",
        "indications_de": ["Lupus erythematodes & Vulgaris", "Chronische Ulzera der Haut", "Nächtliche Knochenschmerzen"],
        "indications_en": ["Lupus and ulcerative skin lesions", "Indolent tubercular ulcers", "Nocturnal bone pains"],
        "keynotes_de": ["Geschwüre mit verdickten Rändern und fauligem Ausfluss", "Knochenschmerzen in Beinen und Schienbein", "Gewichtsverlust mit Kachexie"],
        "keynotes_en": ["Ulcers with indurated margins refusing to heal", "Tearing aching in long bones at night", "Profound constitutional emaciation"],
        "better_de": ["Wärme"],
        "better_en": ["Warmth"],
        "worse_de": ["Nachts", "Kälte"],
        "worse_en": ["Night", "Cold"],
        "diff": ["Hydrocotyle", "Syphilinum", "Arsenicum iodatum"],
        "sphere": ["Haut", "Knochen", "Bindegewebe"],
        "tier": 3
    },
    {
        "id": "canna-angustifolia",
        "latin": "Canna angustifolia",
        "cat": "plant",
        "de_name": "Schmalblättriges Blumenrohr",
        "en_name": "Indian Shot",
        "es_name": "Caña de Indias",
        "fr_name": "Balisiers",
        "it_name": "Canna d'India",
        "el_name": "Κάννα η στενόφυλλος",
        "ru_name": "Канна узколистная",
        "de_essence": "Nervöse Kopfschmerzen mit Brennen der Augenlider, Heiserkeit und spastischem Husten.",
        "en_essence": "Nervous hemicrania with burning eyelids, laryngeal irritation, and dry barking cough.",
        "indications_de": ["Nervöser Kopfschmerz", "Laryngitis mit Kitzeln", "Brennende Augen"],
        "indications_en": ["Nervous hemicrania", "Laryngeal irritation with tickling", "Smarting burning of eyelids"],
        "keynotes_de": ["Einseitiger Kopfschmerz über einem Auge", "Kitzeln im Kehlkopf treibt zum Husten", "Brennen der Konjunktiven"],
        "keynotes_en": ["Unilateral frontal headache", "Constant tickling in larynx provoking cough", "Smarting heat in palpebrae"],
        "better_de": ["Ruhe im Dunkeln"],
        "better_en": ["Rest in darkened room"],
        "worse_de": ["Geistige Anstrengung", "Licht"],
        "worse_en": ["Mental exertion", "Light"],
        "diff": ["Belladonna", "Spigelia"],
        "sphere": ["Nervensystem", "Kehlkopf", "Augen"],
        "tier": 3
    },
    {
        "id": "capsella-bursa-pastoris",
        "latin": "Capsella bursa pastoris",
        "cat": "plant",
        "de_name": "Hirtentäschelkraut",
        "en_name": "Shepherd's Purse",
        "es_name": "Bolsa de pastor",
        "fr_name": "Bourse-à-pasteur",
        "it_name": "Borsa del pastore",
        "el_name": "Καψέλλα ο θύλαξ του ποιμένος",
        "ru_name": "Пастушья сумка",
        "de_essence": "Boerickes großes Hämostyptikum bei Uterusblutungen, Metrorrhagie, Nierengrieß und schmerzhafter Hämaturie.",
        "en_essence": "Boericke's celebrated anti-hemorrhagic in uterine fibroid bleeding, metrorrhagia, renal calculi, and hematuria.",
        "indications_de": ["Profuse Uterusblutungen", "Harnblasenblutung & Hämaturie", "Harnsäuregrieß mit Kolik"],
        "indications_en": ["Profuse uterine hemorrhage and metrorrhagia", "Hematuria from gravel", "Renal calculi and brick-dust sediment"],
        "keynotes_de": ["Uterusblutung mit dunklen Klumpen bei Myomen", "Starke Schmerzen in der Niere mit Ziegelmehlsediment", "Krampfhaftes Zusammenziehen des Uterus"],
        "keynotes_en": ["Excessive passive uterine bleeding with dark clots", "Renal colic with copious red uric acid sand", "Aching pelvic heaviness"],
        "better_de": ["Ruhelage im Bett"],
        "better_en": ["Resting flat in bed"],
        "worse_de": ["Bewegung", "Aufstehen"],
        "worse_en": ["Motion", "Rising up"],
        "diff": ["Thlaspi bursa pastoris", "Sabina", "Erigeron"],
        "sphere": ["Uterus", "Nieren", "Harnwege"],
        "tier": 2
    },
    {
        "id": "carduus-marianus",
        "latin": "Carduus marianus",
        "cat": "plant",
        "de_name": "Mariendistel",
        "en_name": "St. Mary's Thistle",
        "es_name": "Cardo mariano",
        "fr_name": "Chardon-Marie",
        "it_name": "Cardo mariano",
        "el_name": "Σίλυβον το μαριανόν",
        "ru_name": "Расторопша пятнистая",
        "de_essence": "Boerickes Hauptmittel bei Leberleiden: Schwellung und Schmerz des linken und rechten Leberlappens, Ikterus und Krampfadern.",
        "en_essence": "Boericke's prime remedy for liver disease: sensitive engorged liver, jaundice, portal congestion, and varicose veins.",
        "indications_de": ["Leberzirrhose & Fettleber", "Gallenstauung mit Gelbsucht", "Pfortaderstau mit Hämorrhoiden"],
        "indications_en": ["Hepatic cirrhosis and fatty liver", "Jaundice with gallstones", "Portal stasis with varices and hemorrhoids"],
        "keynotes_de": ["Schmerzhafte Lebervergrößerung, besonders linker Leberlappen", "Goldgelber, galliger Urin und lehmfarbene Stühle", "Kann nicht auf der linken Seite liegen"],
        "keynotes_en": ["Painful engorgement of liver, left lobe sensitive", "Golden-yellow bile-stained urine, clay-colored stools", "Cannot lie on left side without pain"],
        "better_de": ["Nach dem Stuhlgang"],
        "better_en": ["After stool"],
        "worse_de": ["Liegen auf der linken Seite", "Bücken", "Bier"],
        "worse_en": ["Lying on left side", "Bending forward", "Beer"],
        "diff": ["Chelidonium", "Taraxacum", "Hydrastis"],
        "sphere": ["Leber", "Pfortadersystem", "Galle", "Venen"],
        "tier": 1
    },
    {
        "id": "castanea-vesca",
        "latin": "Castanea vesca",
        "cat": "plant",
        "de_name": "Edelkastanie",
        "en_name": "Chestnut",
        "es_name": "Castaño común",
        "fr_name": "Châtaignier commun",
        "it_name": "Castagno europeo",
        "el_name": "Καστανέα η εδώδιμος",
        "ru_name": "Каштан посевной",
        "de_essence": "Keuchhusten und krampfhafter Husten, besonders in der Frühphase mit Erstickungsanfällen beim Trinken.",
        "en_essence": "Pertussis (whooping cough) in early catarrhal/paroxysmal stage, violent spasmodic coughing triggered by drinking.",
        "indications_de": ["Keuchhusten (Pertussis)", "Krampfhafter Husten", "Husten beim Schlucken"],
        "indications_en": ["Whooping cough in paroxysmal stage", "Spasmodic bronchial cough", "Cough brought on by drinking liquids"],
        "keynotes_de": ["Hustenanfall wird durch jeden Schluck Flüssigkeit ausgelöst", "Erstickendes Würgen mit rotem Gesicht", "Gefühl von Zerspringen des Brustkorbs"],
        "keynotes_en": ["Paroxysm provoked immediately upon drinking water", "Suffocating choking fits with livid face", "Dry violent shaking cough"],
        "better_de": ["Warmes Zimmer"],
        "better_en": ["Warm room"],
        "worse_de": ["Kaltes Trinken", "Einatmen kalter Luft"],
        "worse_en": ["Drinking cold water", "Cold air inhalation"],
        "diff": ["Drosera", "Corallium rubrum", "Cuprum metallicum"],
        "sphere": ["Kehlkopf", "Bronchien", "Atemwege"],
        "tier": 3
    },
    {
        "id": "castor-equi",
        "latin": "Castor equi",
        "cat": "animal",
        "de_name": "Pferdehorn",
        "en_name": "Rudimentary Thumb of Horse",
        "es_name": "Castor equi",
        "fr_name": "Castor equi",
        "it_name": "Castor equi",
        "el_name": "Κάστωρ ίππειος",
        "ru_name": "Кастор экви",
        "de_essence": "Schmerzhafte, blutige Rhagaden der Brustwarzen bei Stillenden; Steißbeinschmerz und Warzen an den Händen.",
        "en_essence": "Cracked, ulcerated, bleeding nipples in nursing mothers; coccydynia and horny warts on hands.",
        "indications_de": ["Wunde & rissige Brustwarzen", "Schmerzhaftes Steißbein (Kokzygodynie)", "Verhornte Warzen"],
        "indications_en": ["Cracked, ulcerated nipples of nursing women", "Coccydynia on sitting", "Horny flat warts on forehead and hands"],
        "keynotes_de": ["Brustwarzen wund, rissig und blutend wie zerfetzt", "Steißbein extrem druckempfindlich beim Sitzen", "Haut trocken und rissig"],
        "keynotes_en": ["Nipples exquisitely sore, ulcerated, and bleeding", "Coccyx so painful cannot endure sitting on hard chair", "Horny indurations on skin"],
        "better_de": ["Weiche Polsterung"],
        "better_en": ["Soft cushions"],
        "worse_de": ["Beim Stillen", "Sitzen"],
        "worse_en": ["Nursing", "Sitting on hard seats"],
        "diff": ["Graphites", "Phytolacca", "Hypericum"],
        "sphere": ["Brustwarzen", "Steißbein", "Haut"],
        "tier": 3
    },
    {
        "id": "caulophyllum-thalictroides",
        "latin": "Caulophyllum thalictroides",
        "cat": "plant",
        "de_name": "Frauenwurz",
        "en_name": "Blue Cohosh",
        "es_name": "Cohosh azul",
        "fr_name": "Caulophylle",
        "it_name": "Caulofillo",
        "el_name": "Καουλόφυλλον",
        "ru_name": "Стеблелист василистниковидный",
        "de_essence": "Boerickes großes Geburtshilfemittel: Wehenschwäche mit krampfhaften Schmerzen, Uterusrigidität und Rheuma der Fingergelenke.",
        "en_essence": "Boericke's prime obstetric remedy: labor weakness with false spasmodic pains, rigid os uteri, and small-joint rheumatism in women.",
        "indications_de": ["Wehenschwäche & krampfhafte Wehen", "Uterusrigidität bei der Geburt", "Rheumatismus der kleinen Fingergelenke"],
        "indications_en": ["Deficient or spasmodic labor pains", "Rigid os during parturition", "Rheumatism of small joints in women"],
        "keynotes_de": ["Wehen krampfhaft, unkoordiniert und erschöpfend", "Schmerzen strahlen in alle Richtungen aus", "Schwellung und Schmerz der Fingergelenke bei Frauen"],
        "keynotes_en": ["Labor pains severe but spasmodic and ineffective", "Rigid spasmodic os uteri delaying delivery", "Erratic rheumatic pains in fingers and wrists"],
        "better_de": ["Wärme", "Sanfte Bewegung"],
        "better_en": ["Warmth", "Gentle motion"],
        "worse_de": ["Kaffee", "Kälte", "Später Abend"],
        "worse_en": ["Coffee", "Cold air", "Late afternoon"],
        "diff": ["Actaea racemosa", "Secale", "Pulsatilla"],
        "sphere": ["Uterus", "Wehen", "Kleine Gelenke"],
        "tier": 2
    },
    {
        "id": "ceanothus-americanus",
        "latin": "Ceanothus americanus",
        "cat": "plant",
        "de_name": "Amerikanische Säckelblume",
        "en_name": "New Jersey Tea",
        "es_name": "Té de Nueva Jersey",
        "fr_name": "Céanothe d'Amérique",
        "it_name": "Ceanoto",
        "el_name": "Κεάνωθος ο αμερικανικός",
        "ru_name": "Цеанотус американский",
        "de_essence": "Boerickes Hauptmittel bei Milzerkrankungen: Splenomegalie, tiefer Schmerz im linken Hypochondrium und chronische Malaria.",
        "en_essence": "Boericke's premier spleen remedy: splenomegaly, deep aching soreness in left hypochondrium, and malarial cachexia.",
        "indications_de": ["Splenomegalie & Milztumor", "Tiefer Schmerz in der linken Flanke", "Chronische Malaria"],
        "indications_en": ["Enlarged spleen and chronic splenomegaly", "Deep aching soreness in left hypochondrium", "Chronic ague and malarial anemia"],
        "keynotes_de": ["Ständiger dumpfer Schmerz in der Milzgegend", "Patient kann nicht auf der linken Seite liegen", "Vergrößerte Milz drückt auf Magen und Rippenbogen"],
        "keynotes_en": ["Constant heavy dull ache in left hypochondrium", "Inability to lie on left side", "Huge spleen engorgement with anemia"],
        "better_de": ["Liegen auf der rechten Seite"],
        "better_en": ["Lying on right side"],
        "worse_de": ["Liegen auf der linken Seite", "Kälte"],
        "worse_en": ["Lying on left side", "Cold dampness"],
        "diff": ["China", "Arsenicum album", "Polymnia"],
        "sphere": ["Milz", "Pfortadersystem", "Blut"],
        "tier": 2
    },
    {
        "id": "cedron",
        "latin": "Cedron",
        "cat": "plant",
        "de_name": "Simaba cedron",
        "en_name": "Rattlesnake Bean",
        "es_name": "Cedrón",
        "fr_name": "Cédron",
        "it_name": "Cedron",
        "el_name": "Σιμάμπα κέδρον",
        "ru_name": "Цедрон",
        "de_essence": "Uhrwerkartige Periodizität: Neuralgien und Wechselfieber kehren auf die Minute genau zur selben Stunde wieder.",
        "en_essence": "Clockwork periodicity: neuralgias, ciliary neuralgia, and intermittent fevers recurring precisely at the same hour.",
        "indications_de": ["Periodische Neuralgien & Ziliarnerv", "Intermittierendes Wechselfieber", "Gürtelrose mit Periodizität"],
        "indications_en": ["Clockwork facial and supraorbital neuralgia", "Periodical malaria paroxysms", "Herpes zoster with clockwork recurrence"],
        "keynotes_de": ["Schmerzen kehren auf die Minute genau wieder (z. B. täglich 10 Uhr)", "Reißender Schmerz über dem linken Auge bis in den Schläfenbereich", "Frostschauer immer zur gleichen Tageszeit"],
        "keynotes_en": ["Symptoms return with clockwork precision at exact same minute", "Severe supra-orbital pain over left eye extending to temples", "Chills recur precisely on the hour"],
        "better_de": ["Aufrechtes Stehen", "Druck"],
        "better_en": ["Standing erect", "Firm pressure"],
        "worse_de": ["Nach dem Schlafen", "Nachts", "Liegen"],
        "worse_en": ["After sleep", "Night", "Lying down"],
        "diff": ["Chinchona", "Aranea diadema", "Spigelia"],
        "sphere": ["Nervensystem", "Trigeminus", "Ziliarnerven"],
        "tier": 2
    },
    {
        "id": "chionanthus-virginica",
        "latin": "Chionanthus virginica",
        "cat": "plant",
        "de_name": "Schneeflockenstrauch",
        "en_name": "Fringe-Tree",
        "es_name": "Árbol de las nieves",
        "fr_name": "Chionanthe de Virginie",
        "it_name": "Albero della neve",
        "el_name": "Χιονάνθη η παρθενική",
        "ru_name": "Хионантус виргинский",
        "de_essence": "Boerickes großes Gallenmittel: Schmerzhafter Ikterus, Gallestauung, Kopfschmerz mit Erbrechen von Galle und Diabetes mellitus.",
        "en_essence": "Boericke's celebrated hepatic remedy: recurring jaundice, biliary colic, sick headaches with bile vomiting, and hepatic diabetes.",
        "indications_de": ["Ikterus & chronische Gallenstauung", "Bilöse Migräne & Kopfschmerz", "Lebervergrößerung"],
        "indications_en": ["Jaundice and acute cholelithiasis", "Bilious sick headaches", "Hypertrophy of liver with dark urine"],
        "keynotes_de": ["Druckschmerz in der Leber und über der Gallenblase", "Schwere Gelbsucht mit grünlich-braunem Urin", "Periodischer Stirnkopfschmerz mit Gallenbrechen"],
        "keynotes_en": ["Severe aching soreness in umbilical and gall-bladder region", "Pronounced jaundice with dark bile-tinted urine", "Periodic frontal migraine with green bilious vomiting"],
        "better_de": ["Liegen auf dem Bauch"],
        "better_en": ["Lying on abdomen"],
        "worse_de": ["Bewegung", "Aufstehen"],
        "worse_en": ["Motion", "Jarring"],
        "diff": ["Chelidonium", "Carduus marianus", "Podophyllum"],
        "sphere": ["Gallenblase", "Leber", "Pankreas"],
        "tier": 2
    },
    {
        "id": "cistus-canadensis",
        "latin": "Cistus canadensis",
        "cat": "plant",
        "de_name": "Kanadisches Sonnenröschen",
        "en_name": "Rock Rose",
        "es_name": "Jara del Canadá",
        "fr_name": "Ciste du Canada",
        "it_name": "Cisto del Canada",
        "el_name": "Κίστος ο καναδικός",
        "ru_name": "Цистус канадский",
        "de_essence": "Extreme Kälteempfindlichkeit des Rachens: jede Einatmung kalter Luft schmerzt wie Eis; vergrößerte Halsdrüsen und Skrofulose.",
        "en_essence": "Extreme coldness in throat: inhaled air feels like ice; chronic pharyngitis, indurated cervical lymph nodes, and scrofula.",
        "indications_de": ["Pharyngitis mit Eiseskälte im Hals", "Skrofulöse Halsdrüsenschwellung", "Chronischer Nasenkatarrh"],
        "indications_en": ["Pharyngitis with icy feeling on inhalation", "Chronic induration of cervical glands", "Ozaena and chronic nasopharyngeal catarrh"],
        "keynotes_de": ["Einatmung fühlt sich an, als zöge Eisluft durch den Rachen", "Muss den Hals ständig mit Schals warm einhüllen", "Chronische eitrige Absonderungen mit Skrofulose"],
        "keynotes_en": ["Inhaled air feels icy cold in pharynx", "Compelled to swallow continually to moisten dry throat", "Hard scrofulous swellings of neck"],
        "better_de": ["Nach dem Essen", "Warmes Einhüllen"],
        "better_en": ["After eating", "Warm wraps"],
        "worse_de": ["Einatmen kalter Luft", "Geringste Zugluft"],
        "worse_en": ["Inhaling cold air", "Slight draft"],
        "diff": ["Hepar sulfuris", "Silicea", "Calcarea phosphorica"],
        "sphere": ["Rachen", "Halsdrüsen", "Atemwege"],
        "tier": 2
    },
    {
        "id": "clematis-erecta",
        "latin": "Clematis erecta",
        "cat": "plant",
        "de_name": "Aufrechte Waldrebe",
        "en_name": "Virgin's Bower",
        "es_name": "Clemátide erguida",
        "fr_name": "Clématite droite",
        "it_name": "Clematide eretta",
        "el_name": "Κληματίς η ορθή",
        "ru_name": "Ломонос прямой",
        "de_essence": "Harnröhrenstriktur, unterbrochener Harnstrahl (intermittierendes Wasserlassen), Hodenentzündung und brennende Bläschenekzeme.",
        "en_essence": "Urethral stricture, interrupted urine stream (passes in drops then flows), orchitis, and vesicular burning eczema.",
        "indications_de": ["Harnröhrenstriktur & Dysurie", "Orchitis & Hodenschwellung", "Vesikulöse Ekzeme am Kopf"],
        "indications_en": ["Urethral stricture and painful micturition", "Orchitis with painful swelling of testicles", "Eczematous itching eruptions on scalp"],
        "keynotes_de": ["Urinstrahl bricht plötzlich ab und fließt nach Pausen weiter", "Schmerzhaft geschwollene, verhärtete Hoden", "Brennende Bläschenausschläge, schlimmer durch Waschen"],
        "keynotes_en": ["Urine stream interrupted; starts, stops, and dribbles", "Right testicle swollen, painful, and retracted", "Vesicular eruptions with unbearable burning itch"],
        "better_de": ["Im Freien", "Schwitzen"],
        "better_en": ["Open air", "Sweating"],
        "worse_de": ["Nachts", "Wärme des Bettes", "Waschen"],
        "worse_en": ["Night", "Warmth of bed", "Washing in cold water"],
        "diff": ["Petroselinum", "Thuja", "Pulsatilla"],
        "sphere": ["Harnröhre", "Hoden", "Haut"],
        "tier": 2
    },
    {
        "id": "cobaltum-metallicum",
        "latin": "Cobaltum metallicum",
        "cat": "mineral",
        "de_name": "Kobalt",
        "en_name": "Cobalt",
        "es_name": "Cobalto",
        "fr_name": "Cobalt",
        "it_name": "Cobalto",
        "el_name": "Κοβάλτιον",
        "ru_name": "Кобальт металлический",
        "de_essence": "Kreuzschmerzen mit Schwäche, die sich im Sitzen dramatisch verschlimmern; sexuelle Neurasthenie und morgendlicher Rückenschmerz.",
        "en_essence": "Lumbar and sacral backache worse while sitting; sexual neurasthenia, nocturnal emissions, and morning back stiffness.",
        "indications_de": ["Kreuzschmerz schlimmer im Sitzen", "Sexuelle Neurasthenie & Pollutionen", "Rückensteifigkeit"],
        "indications_en": ["Lumbago aggravated by sitting", "Sexual neurasthenia and seminal weakness", "Backache worse on rising"],
        "keynotes_de": ["Schwere Schmerzen im Kreuzbein, unerträglich beim Sitzen", "Erschöpfung nach Samenerguss mit Zittern der Knie", "Rückenschmerz zwingt zum Aufstehen und Umhergehen"],
        "keynotes_en": ["Severe backache in sacrum, worse sitting, compelled to walk", "Seminal emissions followed by lumbar weakness and knee tremor", "Pain in small of back waking patient early morning"],
        "better_de": ["Gehen", "Liegen"],
        "better_en": ["Walking", "Lying down"],
        "worse_de": ["Sitzen", "Nach Samenerguss", "Morgens"],
        "worse_en": ["Sitting", "After emissions", "Morning"],
        "diff": ["Sepia", "Zincum", "Kali carbonicum"],
        "sphere": ["Lendenwirbelsäule", "Geschlechtsorgane", "Nerven"],
        "tier": 3
    },
    {
        "id": "coccus-cacti",
        "latin": "Coccus cacti",
        "cat": "animal",
        "de_name": "Cochenillelaus",
        "en_name": "Cochineal",
        "es_name": "Cochinilla",
        "fr_name": "Cochenille",
        "it_name": "Cocciniglia",
        "el_name": "Κόκκος ο κάκτινος",
        "ru_name": "Кошениль",
        "de_essence": "Boerickes Meistermittel für krampfhaften Keuchhusten mit Massen von zähem, fadenförmigem, klarem Schleim, der zu Erbrechen führt.",
        "en_essence": "Boericke's master remedy for whooping cough with paroxysms ending in profuse vomiting of tough, stringy, ropy mucus.",
        "indications_de": ["Keuchhusten & Spasmodischer Husten", "Zäher, fadenziehender Schleimauswurf", "Nierenkolik mit Ziegelmehlsediment"],
        "indications_en": ["Whooping cough and spasmodic bronchial cough", "Expectoration of immense quantities of ropy tough mucus", "Renal colic with uric acid sediment"],
        "keynotes_de": ["Hustenanfall endet mit Erbrechen von meterlang fadenförmigem Schleim", "Erwacht um 6–7 Uhr morgens mit heftigem Husten", "Kitzeln im Kehlkopf wie von einer Feder"],
        "keynotes_en": ["Violent coughing fit ending with vomiting stringy mucus", "Paroxysms awaken patient around 6 a.m.", "Laryngeal tickling as if caused by a feather"],
        "better_de": ["Kaltes Trinken", "Kühle frische Luft"],
        "better_en": ["Cold drinks", "Cool open air"],
        "worse_de": ["Warmes Zimmer", "Morgens beim Aufwachen", "Bürsten der Zähne"],
        "worse_en": ["Warm room", "On waking in morning", "Brushing teeth"],
        "diff": ["Drosera", "Kali bichromicum", "Corallium rubrum"],
        "sphere": ["Kehlkopf", "Bronchien", "Harnwege"],
        "tier": 2
    },
    {
        "id": "collinsonia-canadensis",
        "latin": "Collinsonia canadensis",
        "cat": "plant",
        "de_name": "Grieswurz",
        "en_name": "Stone-Root",
        "es_name": "Raíz de piedra",
        "fr_name": "Collinsonie du Canada",
        "it_name": "Collinsonia",
        "el_name": "Κολλινσονία η καναδική",
        "ru_name": "Коллинсония канадская",
        "de_essence": "Boerickes führendes Mittel bei schmerzhaften, blutenden Hämorrhoiden mit chronischer Obstipation, Pfortaderstau und Herzklopfen.",
        "en_essence": "Boericke's leading remedy for painful bleeding hemorrhoids with chronic pelvic congestion, obstinate constipation, and palpitation.",
        "indications_de": ["Schmerzhafte blutende Hämorrhoiden", "Hartnäckige Obstipation mit Stuhldrang", "Pfortaderstau & Herzklopfen"],
        "indications_en": ["Painful bleeding hemorrhoids", "Obstinate constipation with dry lumpy stool", "Pelvic portal stasis with cardiac reflex"],
        "keynotes_de": ["Gefühl von Holzsplittern oder Sand im Rektum", "Hämorrhoiden wechseln mit Herzbeschwerden ab", "Schwere Hämorrhoidalschmerzen während der Schwangerschaft"],
        "keynotes_en": ["Sensation of sharp gravel or wooden sticks in rectum", "Hemorrhoids alternate with palpitations or chest pain", "Severe bleeding hemorrhoids of pregnancy"],
        "better_de": ["Wärme"],
        "better_en": ["Warmth"],
        "worse_de": ["Geringste Bewegung", "Kälte"],
        "worse_en": ["Slightest motion", "Cold"],
        "diff": ["Aesculus", "Aloe", "Nux vomica", "Hamamelis"],
        "sphere": ["Rektum", "Hämorrhoidalvenen", "Herz"],
        "tier": 1
    },
    {
        "id": "comocladia-dentata",
        "latin": "Comocladia dentata",
        "cat": "plant",
        "de_name": "Guao",
        "en_name": "Guao",
        "es_name": "Guao",
        "fr_name": "Guao",
        "it_name": "Guao",
        "el_name": "Κομοκλάδια",
        "ru_name": "Комокладия зубчатая",
        "de_essence": "Augenschmerzen mit Gefühl von Vergrößerung der Bulbi, ziliäre Neuralgie, Schwellung des Gesichts und Erysipel.",
        "en_essence": "Violent ciliary neuralgia with feeling as if eyeball were too large for orbit; facial erysipelas and chronic ulcerations.",
        "indications_de": ["Glaukom & Ziliardruckschmerz", "Schwellungsgefühl der Augen", "Gesichtserysipel mit Bläschen"],
        "indications_en": ["Ciliary neuralgia and glaucoma", "Sensation of eyeball bursting or enlarged", "Facial erysipelas and vesicular dermatitis"],
        "keynotes_de": ["Auge fühlt sich an, als würde es aus der Höhle gedrückt", "Augenschmerz strahlt in den Hinterkopf aus", "Gesicht rot und geschwollen mit brennendem Jucken"],
        "keynotes_en": ["Right eye feels immensely swollen and pushed out of head", "Pain in eye radiates straight through to occiput", "Face intensely red, swollen, and itching"],
        "better_de": ["Reiben", "Gehen im Freien"],
        "better_en": ["Rubbing", "Walking in open air"],
        "worse_de": ["Wärme", "Berührung", "Rechte Seite"],
        "worse_en": ["Warmth", "Touch", "Right side"],
        "diff": ["Spigelia", "Rhus tox", "Prunus spinosa"],
        "sphere": ["Augen", "Trigeminus", "Haut"],
        "tier": 3
    },
    {
        "id": "condurango",
        "latin": "Condurango",
        "cat": "plant",
        "de_name": "Kondurangorinde",
        "en_name": "Condurango Bark",
        "es_name": "Condurango",
        "fr_name": "Condurango",
        "it_name": "Condurango",
        "el_name": "Κονδουράνγκο",
        "ru_name": "Кондуранго",
        "de_essence": "Boerickes Klassiker bei schmerzhaften Mundwinkelrhagaden, chronischem Magenulkus mit Erbrechen und Magenkachexie.",
        "en_essence": "Boericke's classic for painful cracked angles of mouth, gastric ulcers, burning gastralgia, and cachexia.",
        "indications_de": ["Mundwinkelrhagaden (Perlèche)", "Chronisches Magengeschwür (Ulkus)", "Brennender Magenschmerz & Erbrechen"],
        "indications_en": ["Deep painful fissures at mouth corners (perlèche)", "Chronic gastric ulcer", "Burning stomach ache with coffee-ground vomiting"],
        "keynotes_de": ["Tiefe, schmerzhafte Risse in beiden Mundwinkeln", "Brennen und Stechen im Epigastrium nach jedem Essen", "Chronischer Gewichtsverlust bei Magenerkrankungen"],
        "keynotes_en": ["Fissures at corners of mouth, ulcerated and painful", "Constant burning distress in stomach with vomiting", "Extreme emaciation in gastric diseases"],
        "better_de": ["Ruhelage", "Milde Nahrung"],
        "better_en": ["Rest", "Bland diet"],
        "worse_de": ["Nach Nahrungsaufnahme"],
        "worse_en": ["After eating"],
        "diff": ["Hydrastis", "Nitricum acidum", "Arsenicum album"],
        "sphere": ["Magen", "Mundwinkel", "Schleimhäute"],
        "tier": 2
    },
    {
        "id": "convallaria-majalis",
        "latin": "Convallaria majalis",
        "cat": "plant",
        "de_name": "Maiglöckchen",
        "en_name": "Lily of the Valley",
        "es_name": "Lirio de los valles",
        "fr_name": "Muguet de mai",
        "it_name": "Mughetto",
        "el_name": "Κονβαλλάρια η μαϊάλιος",
        "ru_name": "Ландыш майский",
        "de_essence": "Boerickes rhythmisches Herzmittel: Herzstolpern, Extrasystolen mit Gefühl des Herzstillstands, Dyspnoe und kardiale Ödeme.",
        "en_essence": "Boericke's rhythmic heart remedy: fluttering irregular pulse, extrasystoles, sensation as if heart stopped, and dropsy.",
        "indications_de": ["Arrhythmie & Herzstolpern", "Kardiale Dyspnoe beim Gehen", "Ödeme durch Herzmuskelschwäche"],
        "indications_en": ["Cardiac arrhythmia and fluttering heart", "Exertional dyspnea with oppression", "Cardiac dropsy and venous engorgement"],
        "keynotes_de": ["Gefühl, als schlage das Herz in der gesamten Brust oder stehe still", "Stolpernder, unregelmäßiger Puls bei Tabakabusus", "Atemnot zwingt zum Aufrichten im Bett"],
        "keynotes_en": ["Heart feels as if beating throughout entire chest", "Fluttering palpitating action with feeling of sudden cessation", "Dyspnea on slight walking, must sit erect"],
        "better_de": ["Aufrechtes Sitzen im Freien"],
        "better_en": ["Sitting erect in open air"],
        "worse_de": ["Aufsteigen", "Liegen auf der linken Seite"],
        "worse_en": ["Ascending", "Lying on left side"],
        "diff": ["Crataegus", "Digitalis", "Adonis vernalis"],
        "sphere": ["Herz", "Myokard", "Kreislauf", "Nieren"],
        "tier": 2
    },
    {
        "id": "copaiva-officinalis",
        "latin": "Copaiva officinalis",
        "cat": "plant",
        "de_name": "Kopaivabalsam",
        "en_name": "Balsam of Copaiva",
        "es_name": "Bálsamo de copaiba",
        "fr_name": "Copahu",
        "it_name": "Balsamo di copaiva",
        "el_name": "Κοπαΐβα η φαρμακευτική",
        "ru_name": "Копайский бальзам",
        "de_essence": "Schleimhautentzündungen der Harnwege: brennende Urethritis mit ständigem Harndrang, Urtikaria und Katarrh.",
        "en_essence": "Mucous membrane inflammation of urinary tract: burning urethritis with constant urge, nettle rash, and catarrh.",
        "indications_de": ["Akute Urethritis & Zystitis", "Brennender Harndrang", "Urtikaria mit Schwellung"],
        "indications_en": ["Acute urethritis and bladder catarrh", "Burning strangury and frequent urge", "Urticarial eruptions with fever"],
        "keynotes_de": ["Brennen und Schneiden in der Harnröhre vor und nach dem Urinieren", "Urin riecht nach Veilchen und geht tröpfelnd ab", "Nesselausschlag mit quälendem Juckreiz"],
        "keynotes_en": ["Burning smarting along urethra before and after urination", "Urine smelling of violets, passed in drops with pain", "Nettle rash with furious itching"],
        "better_de": ["Reichliche Flüssigkeit"],
        "better_en": ["Copious fluid intake"],
        "worse_de": ["Kälte", "Nach dem Wasserlassen"],
        "worse_en": ["Cold air", "After urination"],
        "diff": ["Cantharis", "Cannabis sativa", "Cubeba"],
        "sphere": ["Harnröhre", "Blase", "Schleimhäute", "Haut"],
        "tier": 3
    },
    {
        "id": "corallium-rubrum",
        "latin": "Corallium rubrum",
        "cat": "animal",
        "de_name": "Rote Edelkoralle",
        "en_name": "Red Coral",
        "es_name": "Coral rojo",
        "fr_name": "Corail rouge",
        "it_name": "Corallo rosso",
        "el_name": "Κοράλλιον το ερυθρόν",
        "ru_name": "Кораллиум рубрум",
        "de_essence": "Boerickes klassisches Hustenmittel: Maschinengewehrartiger, minutenschneller Schuss-Husten, der dem Patienten den Atem raubt.",
        "en_essence": "Boericke's minute-gun cough remedy: rapid, violent, explosive paroxysms of coughing closely following one another, taking the breath away.",
        "indications_de": ["Keuchhusten & Spasmodischer Schuss-Husten", "Erstickender nächtlicher Husten", "Chronischer Nasenkatarrh"],
        "indications_en": ["Minute-gun whooping cough", "Suffocative paroxysmal spasms", "Ulcerated post-nasal catarrh"],
        "keynotes_de": ["Hustenstöße folgen so schnell aufeinander, dass keine Luft geholt werden kann", "Gesicht wird blaurot vor Hustenanstrengung", "Luft fühlt sich beim Einatmen eiskalt an"],
        "keynotes_en": ["Cough paroxysms follow so rapidly that breath cannot be caught", "Face turns purple-red with exhaustion from coughing", "Inspired air feels intensely cold to larynx"],
        "better_de": ["Künstliche Wärme", "Warmes Zudecken"],
        "better_en": ["Artificial heat", "Wrapping head warmly"],
        "worse_de": ["Luftzug", "Kälte", "Nachts"],
        "worse_en": ["Draft of air", "Cold", "Night"],
        "diff": ["Drosera", "Coccus cacti", "Spongia"],
        "sphere": ["Kehlkopf", "Atemwege", "Nervensystem"],
        "tier": 2
    },
    {
        "id": "cornus-circinata",
        "latin": "Cornus circinata",
        "cat": "plant",
        "de_name": "Rundblättriger Hartriegel",
        "en_name": "Green Osier",
        "es_name": "Cornejo de hoja redonda",
        "fr_name": "Cornouiller à feuilles rondes",
        "it_name": "Corniolo circinato",
        "el_name": "Κρανία",
        "ru_name": "Кизил круглолистный",
        "de_essence": "Chronische Diarrhoe mit aphthöser Stomatitis, dunklen Gallenabgängen, Schwäche und Schläfrigkeit nach dem Essen.",
        "en_essence": "Chronic camp diarrhea with aphthous ulcerations of mouth, bilious discharges, drowsiness, and profound weakness.",
        "indications_de": ["Chronische Diarrhoe & Enteritis", "Aphthen im Mund", "Schläfrigkeit nach dem Essen"],
        "indications_en": ["Chronic diarrhea and dysentery", "Aphthous stomatitis", "Post-prandial stupor and biliousness"],
        "keynotes_de": ["Wässrige, dunkle Stühle mit Brennen im Rektum", "Mund und Zunge voller schmerzhafter Aphthen", "Unüberwindbare Schläfrigkeit nach jeder Mahlzeit"],
        "keynotes_en": ["Copious watery bilious stools with burning in anus", "Ulcerated aphthae in mouth and tongue", "Overwhelming drowsiness after meals with debility"],
        "better_de": ["Ruhelage"],
        "better_en": ["Quiet rest"],
        "worse_de": ["Morgens", "Nach dem Essen"],
        "worse_en": ["Morning", "After eating"],
        "diff": ["Baptisia", "Hydrastis", "China"],
        "sphere": ["Darmtrakt", "Mundschleimhaut", "Leber"],
        "tier": 3
    },
    {
        "id": "corydalis-formosa",
        "latin": "Corydalis formosa",
        "cat": "plant",
        "de_name": "Lerchensporn",
        "en_name": "Turkey Pea",
        "es_name": "Coridales",
        "fr_name": "Corydale",
        "it_name": "Corydalis",
        "el_name": "Κορυδαλίς",
        "ru_name": "Хохлатка красивая",
        "de_essence": "Syphilitische Knochenschmerzen, vergrößerte Lymphdrüsen, Magenschwäche und chronische Hautleiden.",
        "en_essence": "Syphilitic and scrofulous nodes, osteocopic nocturnal pains, gastric catarrh, and cachexia.",
        "indications_de": ["Syphilitische Knochenschmerzen", "Skrofulöse Drüsenverhärtungen", "Chronische Gastritis mit Erbrechen"],
        "indications_en": ["Syphilitic nodes and bone pains", "Scrofulous lymphadenitis", "Gastric catarrh with nausea"],
        "keynotes_de": ["Schmerzen in den Knochen nachts verschlimmert", "Geschwollene, schmerzlose Hals- und Leistendrüsen", "Magenbrennen mit saurem Aufstoßen"],
        "keynotes_en": ["Nocturnal boring pains in bones and nodes", "Indurated glands of neck and groins", "Sour vomiting with pain in stomach"],
        "better_de": ["Wärme"],
        "better_en": ["Warmth"],
        "worse_de": ["Nachts", "Kälte"],
        "worse_en": ["Night", "Cold"],
        "diff": ["Mercurius", "Kalium iodatum", "Phytolacca"],
        "sphere": ["Knochen", "Drüsen", "Magen"],
        "tier": 3
    },
    {
        "id": "cotyledon-umbilicus",
        "latin": "Cotyledon umbilicus",
        "cat": "plant",
        "de_name": "Nabelkraut",
        "en_name": "Pennywort",
        "es_name": "Ombligo de Venus",
        "fr_name": "Nombril de Vénus",
        "it_name": "Ombelico di Venere",
        "el_name": "Κοτυληδών ο ομφαλός",
        "ru_name": "Пупочник скальный",
        "de_essence": "Hysterische Zustände, Beklemmung am Herzen, Atemnot und Globus-Gefühl im Kehlkopf.",
        "en_essence": "Hysterical manifestations, heart choking, emotional dyspnea, and choking sensation in pharynx.",
        "indications_de": ["Hysterisches Globusgefühl", "Herzbeklemmung durch Emotionen", "Gelenkschmerzen"],
        "indications_en": ["Hysterical choking sensation", "Emotional cardiac distress", "Aching joint soreness"],
        "keynotes_de": ["Gefühl als würde die Kehle zugeschnürt", "Herzklopfen bei jeder emotionalen Aufregung", "Schweregefühl in den Gliedern"],
        "keynotes_en": ["Sensation of constriction in larynx and throat", "Choking palpitations from slight emotional upsets", "Aching bruised fatigue in limbs"],
        "better_de": ["Frische Luft", "Weinen"],
        "better_en": ["Open air", "Weeping"],
        "worse_de": ["Emotionen", "Wärme"],
        "worse_en": ["Emotions", "Warmth"],
        "diff": ["Ignatia", "Asa foetida", "Moschus"],
        "sphere": ["Vegetatives Nervensystem", "Kehlkopf", "Herz"],
        "tier": 3
    },
    {
        "id": "crataegus-oxyacantha",
        "latin": "Crataegus oxyacantha",
        "cat": "plant",
        "de_name": "Echter Weißdorn",
        "en_name": "Hawthorn",
        "es_name": "Espino albar",
        "fr_name": "Aubépine épineuse",
        "it_name": "Biancospino",
        "el_name": "Κράταιγος ο οξυάκανθος",
        "ru_name": "Боярышник обыкновенный",
        "de_essence": "Boerickes größtes Herztonikum: Stärkt den insuffizienten Herzmuskel, senkt den Blutdruck, heilt Angina pectoris und Altersherz ohne Nebenwirkungen.",
        "en_essence": "Boericke's premier cardiac tonic: strengthens failing myocardium, dissolves arteriosclerotic plaques, relieves angina pectoris, and tonifies the aged heart.",
        "indications_de": ["Chronische Myokardinsuffizienz & Altersherz", "Angina pectoris & Präkordialschmerz", "Hypertonie & Arteriosklerose"],
        "indications_en": ["Chronic myocardial weakness and aged heart", "Angina pectoris with precordial oppression", "Arteriosclerosis and high blood pressure"],
        "keynotes_de": ["Extreme Atemnot bei der geringsten Bewegung ohne Ödeme", "Präkordialer Schmerz zieht in die linke Schulter und den Arm", "Boericke: 'Das sicherste Herztonikum, das niemals schadet'"],
        "keynotes_en": ["Extreme dyspnea on slightest exertion without dropsy", "Precordial ache radiating down left arm", "Boericke: 'Acts as a genuine solvent on crustaceous and calcareous deposits'"],
        "better_de": ["Frische Luft", "Ruhiges Ausruhen"],
        "better_en": ["Quiet rest in open air"],
        "worse_de": ["Körperliche Anstrengung", "Warmes Zimmer"],
        "worse_en": ["Physical exertion", "Warm room"],
        "diff": ["Digitalis", "Strophanthus", "Convallaria", "Adonis vernalis"],
        "sphere": ["Herzmuskel", "Herzkranzgefäße", "Arterien"],
        "tier": 1
    },
    {
        "id": "croton-tiglium",
        "latin": "Croton tiglium",
        "cat": "plant",
        "de_name": "Krotonölbaum",
        "en_name": "Purging Nut",
        "es_name": "Croton tiglium",
        "fr_name": "Croton tiglium",
        "it_name": "Croton tiglium",
        "el_name": "Κρότων ο τίγλιος",
        "ru_name": "Кротон слабительный",
        "de_essence": "Boerickes Leitsymptom: Schussartige, wässrige Diarrhoe unmittelbar nach jedem Essen oder Trinken; unerträglich juckende Bläschenekzeme.",
        "en_essence": "Boericke's keynote: sudden gushing, watery diarrhea coming out like a shot immediately after eating or drinking; intensely itching vesicular eczema.",
        "indications_de": ["Schussartige wässrige Diarrhoe", "Intolerabler Juckreiz der Haut", "Brustwarzenschmerz beim Stillen"],
        "indications_en": ["Gushing watery diarrhea like a shot", "Intense itching vesicular dermatitis", "Pain in nipples extending to shoulder-blade on nursing"],
        "keynotes_de": ["Stuhl schießt mit einem Knall wie aus einer Spritze hervor", "Jeder Bissen oder Schluck treibt sofort auf die Toilette", "Brustwarzenschmerz strahlt beim Saugen des Kindes direkt zum Schulterblatt"],
        "keynotes_en": ["Stool comes out with a sudden gush like water from a hydrant", "Eating or drinking triggers instantaneous stool urgency", "Drawing pain in nipple extending through to scapula while nursing"],
        "better_de": ["Sanftes Reiben", "Schlaf"],
        "better_en": ["Gentle rubbing", "Sleep"],
        "worse_de": ["Essen oder Trinken", "Sommer", "Nacht"],
        "worse_en": ["Eating or drinking", "Summer", "Night"],
        "diff": ["Podophyllum", "Veratrum album", "Rhus tox"],
        "sphere": ["Darmtrakt", "Haut", "Mammae"],
        "tier": 2
    },
    {
        "id": "cubeba-officinalis",
        "latin": "Cubeba officinalis",
        "cat": "plant",
        "de_name": "Kubebenpfeffer",
        "en_name": "Cubebs",
        "es_name": "Cubeba",
        "fr_name": "Poivre à queue",
        "it_name": "Cubebe",
        "el_name": "Πέπερι το κομβικόν",
        "ru_name": "Кубеба",
        "de_essence": "Schleimhautentzündung der Harnwege und Atemwege mit dickem, zähem Schleim, brennender Urethritis und Reizhusten.",
        "en_essence": "Catarrhal inflammation of genito-urinary tract and respiratory organs with thick mucous discharge, scalding dysuria, and cough.",
        "indications_de": ["Urethritis mit dickem Ausfluss", "Zystitis mit Brennschmerz", "Chronischer Bronchialhusten"],
        "indications_en": ["Catarrhal urethritis with thick discharge", "Cystitis with scalding urination", "Bronchial cough with rattling expectoration"],
        "keynotes_de": ["Schneidendes Brennen in der Urethra nach der Miktion", "Dicker, übelriechender Schleimausfluss", "Husten mit reichlichem, zähem Auswurf"],
        "keynotes_en": ["Severe smarting along urethra after urination", "Thick ropy discharge from bladder and urethra", "Harsh cough with tenacious expectoration"],
        "better_de": ["Warme Umschläge"],
        "better_en": ["Warm applications"],
        "worse_de": ["Kälte", "Nach dem Wasserlassen"],
        "worse_en": ["Cold", "After urination"],
        "diff": ["Copaiva", "Cantharis", "Cannabis sativa"],
        "sphere": ["Harnröhre", "Blase", "Bronchialschleimhaut"],
        "tier": 3
    },
    {
        "id": "cuprum-aceticum",
        "latin": "Cuprum aceticum",
        "cat": "mineral",
        "de_name": "Kupferacetat",
        "en_name": "Copper Acetate",
        "es_name": "Acetato de cobre",
        "fr_name": "Acétate de cuivre",
        "it_name": "Acetato di rame",
        "el_name": "Οξικός χαλκός",
        "ru_name": "Меди ацетат",
        "de_essence": "Krampfanfälle, Angina pectoris mit Erstickungsgefühl, Wadenkrämpfe und zerebrale Entzündungen nach unterdrückten Exanthemen.",
        "en_essence": "Violent spasms, angina pectoris with suffocative constriction, cramps in calves, and cerebral repercussion of suppressed rashes.",
        "indications_de": ["Spasmen & tonische Krämpfe", "Angina pectoris mit Erstickungsnot", "Krämpfe nach unterdrücktem Ausschlag"],
        "indications_en": ["Violent spasmodic contractions", "Angina pectoris with suffocation", "Brain affections from suppressed eruptions"],
        "keynotes_de": ["Daumen werden krampfhaft in die Handfläche eingeschlagen", "Plötzliche krampfhafte Angina-Attacken", "Heftige Schmerzen im Abdomen mit Wadenkrämpfen"],
        "keynotes_en": ["Thumbs clenched tightly into palms during convulsions", "Angina pectoris with agonizing sense of constriction in chest", "Violent abdominal cramps radiating to calves"],
        "better_de": ["Trinken von kaltem Wasser", "Druck"],
        "better_en": ["Sips of cold water", "Pressure"],
        "worse_de": ["Berührung", "Kälte", "Nachts"],
        "worse_en": ["Touch", "Cold", "Night"],
        "diff": ["Cuprum metallicum", "Magnesia phosphorica"],
        "sphere": ["Nervensystem", "Muskeln", "Herz"],
        "tier": 2
    }
]
