# scripts/data_A.py
# Complete clinical homeopathic monographs for all 58 A remedies

DATA_A = [
  {
    "id": "abies-canadensis", "latinName": "Abies canadensis", "categoryKey": "plant", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Kanadische Hemlocktanne",
      "origin": "Frische Nadeln und Zweigspitzen von Tsuga canadensis",
      "essence": "Magenmittel bei Heißhunger mit Magenschwäche, Kältegefühl und Senkungsgefühl im Epigastrium.",
      "mainIndications": ["Magenbeschwerden mit Heißhunger", "Magensenkung (Gastroptose)", "Reizmagensyndrom", "Uterusprolaps mit Magenbrennen"],
      "keynotes": ["Gefühl, als ob der Magen wie ein Stein herabfällt", "Heißhunger auf Fleisch, Gurken und Saures", "Kältegefühl zwischen den Schulterblättern", "Neigung zu Frösteln und Schüttelfrost"],
      "mindEmotional": "Mürrisch, gereizt durch Schwäche, verlangt nach Ruhe und Schonung.",
      "modalitiesBetter": ["Nach dem Essen", "Durch Liegen mit angezogenen Knien", "Wärme"],
      "modalitiesWorse": ["Aufstehen", "Bewegung", "Kälte", "Leerer Magen"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x täglich 5 Globuli",
      "sphereOfAction": ["Magen-Darm-Trakt", "Vegetatives Nervensystem", "Urogenitaltrakt"],
      "differentialRemedies": ["Abies nigra", "Anacardium", "Nux vomica", "Sepia"],
      "searchKeywords": ["abies canadensis", "hemlocktanne", "heißhunger", "magensenkung", "magenkälte"]
    },
    "en": {
      "commonName": "Hemlock Spruce",
      "origin": "Fresh needles and bark of Tsuga canadensis",
      "essence": "Gastric remedy for canine hunger with stomach sinking and craving for heavy food.",
      "mainIndications": ["Gastric disorders with ravenous hunger", "Gastroptosis and sinking sensation", "Dyspepsia with chilliness", "Uterine prolapse"],
      "keynotes": ["Sensation of stomach falling down", "Craving for meat, pickles and coarse food", "Cold water sensation between scapulae", "Extreme chilliness"],
      "mindEmotional": "Peevish, irritable from exhaustion, desires rest.",
      "modalitiesBetter": ["After eating", "Lying with knees drawn up", "Warmth"],
      "modalitiesWorse": ["Standing up", "Movement", "Cold", "Empty stomach"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x daily 5 globules",
      "sphereOfAction": ["Gastrointestinal tract", "Autonomic nervous system", "Urogenital tract"],
      "differentialRemedies": ["Abies nigra", "Anacardium", "Nux vomica", "Sepia"],
      "searchKeywords": ["abies canadensis", "hemlock spruce", "canine hunger", "gastroptosis", "stomach sinking"]
    },
    "fr": {"commonName": "Pruche du Canada"},
    "es": {"commonName": "Abeto del Canadá"},
    "it": {"commonName": "Abete del Canada"},
    "el": {"commonName": "Καναδικό έλατο"},
    "ru": {"commonName": "Пихта канадская"}
  },
  {
    "id": "abies-nigra", "latinName": "Abies nigra", "categoryKey": "plant", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Schwarzfichte",
      "origin": "Harzige Zweigspitzen von Picea mariana",
      "essence": "Magenmittel mit dem charakteristischen Gefühl eines hartgekochten Eies in der Magengrube.",
      "mainIndications": ["Dyspepsie bei älteren Menschen", "Magenkrämpfe nach dem Essen", "Schlafstörungen durch Magendruck", "Kardiospasmus"],
      "keynotes": ["Gefühl eines hartgekochten Eies in der Herzgrube", "Völlige Appetitlosigkeit am Morgen, Heißhunger am Mittag/Abend", "Schmerzhafter Magendruck sofort nach der Nahrungsaufnahme", "Nächtliches Aufwachen durch Herzklopfen"],
      "mindEmotional": "Trübsinnig, melancholisch während der Verdauung, antriebslos.",
      "modalitiesBetter": ["Aufrechtes Sitzen", "Leichte Bewegung", "Fasten"],
      "modalitiesWorse": ["Nach dem Essen", "Nachts im Liegen", "Tabakgenuss"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x täglich 5 Globuli vor den Mahlzeiten",
      "sphereOfAction": ["Magen", "Ösophagus", "Kardiovaskuläres System"],
      "differentialRemedies": ["Nux vomica", "Bryonia", "Carbo vegetabilis", "Ignatia"],
      "searchKeywords": ["abies nigra", "schwarzfichte", "hartgekochtes ei", "magendruck", "dyspepsie"]
    },
    "en": {
      "commonName": "Black Spruce",
      "origin": "Resin of Picea mariana",
      "essence": "Gastric remedy centered on sensation of a hard-boiled egg lodged in the cardiac orifice.",
      "mainIndications": ["Dyspepsia in elderly", "Gastric distress after eating", "Insomnia from gastric oppression", "Cardiospasm"],
      "keynotes": ["Sensation of a hard-boiled egg in pit of stomach", "No morning appetite, great craving at noon/night", "Pain immediately after eating", "Nightly heart palpitations"],
      "mindEmotional": "Hypochondriac, depressed during indigestion.",
      "modalitiesBetter": ["Sitting upright", "Gentle walking", "Fasting"],
      "modalitiesWorse": ["After eating", "Night lying down", "Tobacco"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x daily 5 globules before meals",
      "sphereOfAction": ["Stomach", "Esophagus", "Heart"],
      "differentialRemedies": ["Nux vomica", "Bryonia", "Carbo vegetabilis", "Ignatia"],
      "searchKeywords": ["abies nigra", "black spruce", "hard-boiled egg sensation", "gastric distress"]
    },
    "fr": {"commonName": "Épinette noire"},
    "es": {"commonName": "Abeto negro"},
    "it": {"commonName": "Abete nero"},
    "el": {"commonName": "Μαύρη ελάτη"},
    "ru": {"commonName": "Пихта черная"}
  },
  {
    "id": "abrotanum", "latinName": "Abrotanum", "categoryKey": "plant", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Eberraute",
      "origin": "Frische Blätter und Stängel von Artemisia abrotanum",
      "essence": "Metastasierende Beschwerden, Marasmus und Abmagerung besonders der unteren Extremitäten trotz guten Appetits.",
      "mainIndications": ["Abmagerung bei Kindern trotz gutem Essen", "Metastasierende Entzündungen (Mumps auf Hoden/Brust)", "Rheumatismus nach unterdrücktem Durchfall", "Frostbeulen mit Brennen"],
      "keynotes": ["Abmagerung von unten nach oben (Beine zuerst)", "Wechselnde Symptome: Wenn Durchfall stoppt, kommen Gelenkschmerzen", "Heißhunger, aber stetiger Gewichtsverlust", "Bläuliches, faltiges Gesicht wie ein kleiner Greis"],
      "mindEmotional": "Reizbar, mutlos, mürrisch, boshaft bei Schwäche.",
      "modalitiesBetter": ["Lockerung der Kleidung", "Freier Durchfall", "Bewegung"],
      "modalitiesWorse": ["Kälte", "Unterdrückung von Ausscheidungen", "Nachtluft"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2-3x täglich 5 Globuli",
      "sphereOfAction": ["Stoffwechsel", "Gelenke", "Lymphsystem", "Haut"],
      "differentialRemedies": ["Iodum", "Natrium chloratum", "Tuberculinum", "Sanicula"],
      "searchKeywords": ["abrotanum", "eberraute", "marasmus", "abmagerung beine", "unterdrückter durchfall"]
    },
    "en": {
      "commonName": "Southernwood",
      "origin": "Fresh leaves of Artemisia abrotanum",
      "essence": "Metastatic pathology and marasmus with emaciation starting in lower extremities despite good appetite.",
      "mainIndications": ["Emaciation in children", "Metastatic complaints (mumps to testes)", "Rheumatism after suppressed diarrhea", "Chilblains"],
      "keynotes": ["Emaciation ascending from legs upwards", "Alternation of symptoms (diarrhea stops, joint pain starts)", "Ravenous appetite with progressive weight loss", "Old-looking wrinkled face in children"],
      "mindEmotional": "Cross, irritable, ill-natured, despondent.",
      "modalitiesBetter": ["Loose clothing", "Free bowel movements", "Warmth"],
      "modalitiesWorse": ["Cold", "Suppressed discharges", "Night air"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2-3x daily 5 globules",
      "sphereOfAction": ["Metabolism", "Connective tissue", "Joints", "Skin"],
      "differentialRemedies": ["Iodum", "Natrium chloratum", "Tuberculinum", "Sanicula"],
      "searchKeywords": ["abrotanum", "southernwood", "marasmus", "emaciation legs", "metastatic rheumatism"]
    },
    "fr": {"commonName": "Aurone"},
    "es": {"commonName": "Abrótano macho"},
    "it": {"commonName": "Abrotano"},
    "el": {"commonName": "Αβρότονο"},
    "ru": {"commonName": "Абротан"}
  },
  {
    "id": "absinthium", "latinName": "Absinthium", "categoryKey": "plant", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Wermut",
      "origin": "Frische Blüten und Blätter von Artemisia absinthium",
      "essence": "Zentrales Nervenmittel bei zerebralen Reizzuständen, epileptiformen Anfällen, Schwindel und nervösem Tremor.",
      "mainIndications": ["Epileptiforme Krämpfe mit Beißen der Zunge", "Nervöse Schlaflosigkeit & Halluzinationen", "Schwindel mit Fallneigung nach hinten", "Nervöse Dyspepsie"],
      "keynotes": ["Krämpfe mit Grimassieren und Zittern", "Gefühl, als fiele man rückwärts", "Stumpfsinnigkeit und Gedächtnislücken nach Anfällen", "Pupillenerweiterung und Gesichtsblässe"],
      "mindEmotional": "Halluzinationen, Visionen von Ungeheuern, Verwirrung, unruhiger Schlaf.",
      "modalitiesBetter": ["Ruhe", "Dunkelheit", "Wärme"],
      "modalitiesWorse": ["Aufregung", "Alkohol/Stimulanzien", "Bewegung"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2x täglich 5 Globuli",
      "sphereOfAction": ["Zentralnervensystem", "Gehirn", "Magen-Darm-Trakt"],
      "differentialRemedies": ["Cicuta virosa", "Bufo", "Hyoscyamus", "Agaricus"],
      "searchKeywords": ["absinthium", "wermut", "epilepsie", "krämpfe", "nervöser tremor", "halluzinationen"]
    },
    "en": {
      "commonName": "Common Wormwood",
      "origin": "Fresh leaves and tops of Artemisia absinthium",
      "essence": "Neurological remedy for epileptiform convulsions, vertigo, tremors, and cerebral congestion.",
      "mainIndications": ["Epileptoid seizures with tongue biting", "Nervous tremors and chorea", "Vertigo with backward falling tendency", "Dyspeptic spasms"],
      "keynotes": ["Spasmodic facial grimacing and trembling", "Vertigo falling backwards", "Memory loss after convulsions", "Pupillary dilatation"],
      mindEmotional: "Hallucinatory state, fearful visions, stupor.",
      "modalitiesBetter": ["Rest", "Quiet dark room", "Warmth"],
      "modalitiesWorse": ["Excitement", "Stimulants", "Sudden motion"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2x daily 5 globules",
      "sphereOfAction": ["Central nervous system", "Cerebrum", "Gastrointestinal tract"],
      "differentialRemedies": ["Cicuta virosa", "Bufo", "Hyoscyamus", "Agaricus"],
      "searchKeywords": ["absinthium", "wormwood", "epileptiform convulsions", "vertigo", "tremor"]
    },
    "fr": {"commonName": "Grande Absinthe"},
    "es": {"commonName": "Ajenjo"},
    "it": {"commonName": "Assenzio"},
    "el": {"commonName": "Αψιθιά"},
    "ru": {"commonName": "Полынь горькая"}
  },
  {
    "id": "acalypha-indica", "latinName": "Acalypha indica", "categoryKey": "plant", "importanceTier": 3, "isPolychrest": False,
    "de": {
      "commonName": "Indisches Brennkraut",
      "origin": "Frische ganze Pflanze von Acalypha indica",
      "essence": "Hämorrhagisches Mittel für Atemwege und Magen-Darm mit morgendlichem Bluthusten und explosionsartigem Stuhl.",
      "mainIndications": ["Hämoptysis (Bluthusten)", "Tuberkulöse Frühstadien mit Lungenblutung", "Explosionsartiger Durchfall mit viel Gas", "Trockener Reizhusten mit Blutspuren"],
      "keynotes": ["Bluthusten morgens hellrot, abends dunkel und geronnen", "Explosiver Stuhldrang mit lauten Winden", "Ständige Zerschlagenheit und Schwäche der Brust", "Verschlimmerung am frühen Morgen"],
      "mindEmotional": "Deprimiert durch stetige Blutverluste, schwach, kraftlos.",
      "modalitiesBetter": ["Ruhe", "Frische kühle Luft"],
      "modalitiesWorse": ["Morgens (Blutungen)", "Abends (Husten)", "Anstrengung"],
      "potenciesAndDosage": "D3, D6, D12",
      "defaultTagesdosis": "3x täglich 5 Globuli",
      "sphereOfAction": ["Lunge & Bronchien", "Gastrointestinaltrakt", "Blutgefäße"],
      "differentialRemedies": ["Millefolium", "Phosphorus", "Ferrum phosphoricum", "Ipecacuanha"],
      "searchKeywords": ["acalypha indica", "indisches brennkraut", "bluthusten", "hämoptoe", "explosionsartiger durchfall"]
    },
    "en": {
      "commonName": "Indian Acalypha",
      "origin": "Fresh plant of Acalypha indica",
      "essence": "Hemorrhagic remedy targeting respiratory and intestinal tracts with morning bright hemoptysis.",
      "mainIndications": ["Hemoptysis and pulmonary hemorrhage", "Incipient phthisis with blood-streaked sputum", "Explosive morning diarrhea with flatus", "Dry hacking cough"],
      "keynotes": ["Blood bright red in morning, dark/clotted in evening", "Explosive spluttering stool", "Severe thoracic weakness", "Worse in the morning hours"],
      "mindEmotional": "Exhausted, low-spirited from loss of blood.",
      "modalitiesBetter": ["Absolute rest", "Fresh cool air"],
      "modalitiesWorse": ["Morning hours", "Evening cough", "Exertion"],
      "potenciesAndDosage": "D3, D6, D12",
      "defaultTagesdosis": "3x daily 5 globules",
      "sphereOfAction": ["Lungs", "Blood vessels", "Intestines"],
      "differentialRemedies": ["Millefolium", "Phosphorus", "Ferrum phosphoricum", "Ipecacuanha"],
      "searchKeywords": ["acalypha indica", "indian acalypha", "hemoptysis", "morning bleeding", "explosive diarrhea"]
    },
    "fr": {"commonName": "Ricinelle des Indes"},
    "es": {"commonName": "Acalifa índica"},
    "it": {"commonName": "Acalifa indiana"},
    "el": {"commonName": "Ακαλύφη η ινδική"},
    "ru": {"commonName": "Акалифа индийская"}
  },
  {
    "id": "acidum-aceticum", "latinName": "Acidum aceticum", "categoryKey": "acid", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Essigsäure",
      "origin": "Verdünnte reine Essigsäure (CH3COOH)",
      "essence": "Auszehrung, Anämie, massive Ödeme mit großem Durst und Liegen auf dem Bauch als Modalität.",
      "mainIndications": ["Schwere Kachexie und Anämie", "Generalisierte Ödeme & Aszites", "Magenbrennen mit saurem Erbrechen", "Hektisches Fieber mit Nachtschweiß"],
      "keynotes": ["Unstillbarer Durst (außer bei Fieber)", "Kann nur auf dem Bauch schlafen", "Starker saurer Speichel- und Schweißfluss", "Blässe wie Wachs mit hohlen Augen"],
      "mindEmotional": "Ängstlich um die Gesundheit, verstrickt in Sorgen, schwaches Gedächtnis.",
      "modalitiesBetter": ["Auf dem Bauch liegen", "Aufstoßen"],
      "modalitiesWorse": ["Auf dem Rücken liegen", "Kälte", "Gemüsesäuren"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2-3x täglich 5 Globuli",
      "sphereOfAction": ["Stoffwechsel", "Gefäßsystem (Ödeme)", "Magen-Darm-Trakt", "Blutbildung"],
      "differentialRemedies": ["Arsenicum album", "Apis mellifica", "China officinalis", "Ferrum"],
      "searchKeywords": ["acidum aceticum", "essigsäure", "auszehrung", "ödeme", "auf dem bauch schlafen", "unstillbarer durst"]
    },
    "en": {
      "commonName": "Glacial Acetic Acid",
      "origin": "Diluted acetic acid",
      "essence": "Deep wasting cachexia, dropsy with intense burning thirst and sleeping prone.",
      "mainIndications": ["Profound debility and anemia", "Anasarca and abdominal ascites", "Severe gastralgia with sour regurgitation", "Hectic fever with night sweats"],
      "keynotes": ["Insatiable burning thirst (except during fever)", "Can sleep only on the stomach/abdomen", "Profuse sour salivation and sweat", "Waxy pale emaciation"],
      "mindEmotional": "Anxious regarding family and health, fretful.",
      "modalitiesBetter": ["Lying prone on belly", "Eructations"],
      "modalitiesWorse": ["Lying on back", "Cold", "Sour food"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2-3x daily 5 globules",
      "sphereOfAction": ["Fluid metabolism", "Blood", "Gastrointestinal system"],
      "differentialRemedies": ["Arsenicum album", "Apis mellifica", "China officinalis", "Ferrum"],
      "searchKeywords": ["acidum aceticum", "acetic acid", "dropsy", "sleeping on stomach", "insatiable thirst"]
    },
    "fr": {"commonName": "Acide acétique"},
    "es": {"commonName": "Ácido acético"},
    "it": {"commonName": "Acido acetico"},
    "el": {"commonName": "Οξικό οξύ"},
    "ru": {"commonName": "Уксусная кислота"}
  },
  {
    "id": "acidum-benzoicum", "latinName": "Acidum benzoicum", "categoryKey": "acid", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Benzoesäure",
      "origin": "Reine Benzoesäure aus Benzoeharz",
      "essence": "Harnsäure-Diathese mit penetrant nach Pferdeharn riechendem Urin, Gicht und Gelenkknacken.",
      "mainIndications": ["Gicht und Arthritis deformans", "Ganglion am Handgelenk", "Zystitis mit stinkendem Urin", "Achillessehnenentzündung"],
      "keynotes": ["Urin riecht intensiv widerlich wie Pferdeharn", "Urin dunkelbraun und brennend", "Gelenke knacken bei jeder Bewegung", "Symptome wechseln zwischen Gelenken und Harnwegen"],
      "mindEmotional": "Neigung zu Grübeln über unangenehme Dinge, niedergeschlagen.",
      "modalitiesBetter": ["Reichliche Harnabsonderung", "Wärme"],
      "modalitiesWorse": ["Kaltes feuchtes Wetter", "Veränderung der Witterung", "Enthüllung"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x täglich 5 Globuli",
      "sphereOfAction": ["Harnwege & Nieren", "Gelenke & Sehnen", "Harnsäurestoffwechsel"],
      "differentialRemedies": ["Berberis", "Ledum", "Colchicum", "Lithium carbonicum"],
      "searchKeywords": ["acidum benzoicum", "benzoesäure", "pferdeharn", "harnsäure", "gicht", "gelenkknacken"]
    },
    "en": {
      "commonName": "Benzoic Acid",
      "origin": "Purified Benzoic Acid",
      "essence": "Uric acid diathesis characterized by intensely offensive, horse-urine odor and gouty joints.",
      "mainIndications": ["Gout and osteoarthritic tophi", "Wrists ganglion", "Cystitis with pungent dark urine", "Achilles tendinitis"],
      "keynotes": ["Urine smells intensely fetid like horses urine", "Urine high-colored and brown", "Audible cracking in joints on walking", "Alternation of urinary and articular symptoms"],
      "mindEmotional": "Brooding over unpleasant past events, depressed.",
      "modalitiesBetter": ["Copious urination", "Warmth"],
      "modalitiesWorse": ["Cold damp air", "Weather changes", "Uncovering"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x daily 5 globules",
      "sphereOfAction": ["Urinary tract", "Joints", "Connective tissue"],
      "differentialRemedies": ["Berberis", "Ledum", "Colchicum", "Lithium carbonicum"],
      "searchKeywords": ["acidum benzoicum", "benzoic acid", "horse urine odor", "gout", "joint cracking"]
    },
    "fr": {"commonName": "Acide benzoïque"},
    "es": {"commonName": "Ácido benzoico"},
    "it": {"commonName": "Acido benzoico"},
    "el": {"commonName": "Βενζοϊκό οξύ"},
    "ru": {"commonName": "Бензойная кислота"}
  },
  {
    "id": "acidum-formicicum", "latinName": "Acidum formicicum", "categoryKey": "acid", "importanceTier": 3, "isPolychrest": False,
    "de": {
      "commonName": "Ameisensäure",
      "origin": "Verdünnte reine Ameisensäure (Formica rufa)",
      "essence": "Chronische Erschöpfung, Muskelschwäche, Gicht und plötzliches Auftreten brennender Schmerzen.",
      "mainIndications": ["Chronische Erschöpfung (CFS)", "Myalgien & Muskelschwäche", "Chronische Arthrose mit Steifheit", "Allergische Diathese & Ekzeme"],
      "keynotes": ["Schmerzen treten plötzlich auf und wechseln die Seite", "Brennende Schmerzen wie von Ameisenbissen", "Ausgeprägte Morgensteifheit, Besserung durch anhaltende Bewegung", "Verstärkte Schweißneigung bei geringster Anstrengung"],
      "mindEmotional": "Apathisch durch anhaltende Muskelschwäche, vergesslich.",
      "modalitiesBetter": ["Anhaltende Bewegung", "Druck", "Wärme"],
      "modalitiesWorse": ["Kälte", "Nässe", "Vor Schneefall", "Kaltes Baden"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2x täglich 5 Globuli",
      "sphereOfAction": ["Muskeln & Faszien", "Gelenke", "Nervensystem", "Immunsystem"],
      "differentialRemedies": ["Rhus toxicodendron", "Dulcamara", "Acidum phosphoricum", "Causticum"],
      "searchKeywords": ["acidum formicicum", "ameisensäure", "muskelschwäche", "chronische erschöpfung", "ameisenbisse"]
    },
    "en": {
      "commonName": "Formic Acid",
      "origin": "Diluted Formic Acid",
      "essence": "Profound muscular weakness, chronic arthritis, and sudden burning shooting neuralgias.",
      "mainIndications": ["Chronic fatigue and muscle weakness", "Articular stiffness and gout", "Allergic eczema and urticaria", "Kidney congestion"],
      "keynotes": ["Burning sensations like ant stings", "Pains appear suddenly and shift sides", "Stiffness relieved by continued motion", "Profuse sweat on slight exertion"],
      "mindEmotional": "Indolent, memory dull from exhaustion.",
      "modalitiesBetter": ["Continued gentle motion", "Firm pressure", "Warmth"],
      "modalitiesWorse": ["Cold", "Damp weather", "Before snowstorm"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2x daily 5 globules",
      "sphereOfAction": ["Muscles", "Joints", "Immune system"],
      "differentialRemedies": ["Rhus toxicodendron", "Dulcamara", "Acidum phosphoricum", "Causticum"],
      "searchKeywords": ["acidum formicicum", "formic acid", "muscle fatigue", "ant sting burning", "gouty stiffness"]
    },
    "fr": {"commonName": "Acide formique"},
    "es": {"commonName": "Ácido fórmico"},
    "it": {"commonName": "Acido formico"},
    "el": {"commonName": "Μυρμηκικό οξύ"},
    "ru": {"commonName": "Муравьиная кислота"}
  },
  {
    "id": "acidum-hydrofluoricum", "latinName": "Acidum hydrofluoricum", "categoryKey": "acid", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Flusssäure",
      "origin": "Verdünnte wässrige Fluorwasserstoffsäure (HF)",
      "essence": "Gewebsdestruktion, Knochennekrosen, Ulzerationen und venöse Stauungen bei heißblütigen, hyperaktiven Patienten.",
      "mainIndications": ["Varizen und Ulcus cruris", "Knochenfisteln & Karies der Knochen", "Haarausfall & brüchige Nägel", "Chronischer Nagelbettabszess"],
      "keynotes": ["Extreme Hitzeintoleranz (verlangt Kälte und Eiswasser)", "Stets in Eile, hyperaktiv, spürt keine Müdigkeit", "Brennende, ätzende Absonderungen", "Venöse Stauungen mit Neigung zu Geschwüren"],
      "mindEmotional": "Abneigung gegen die eigene Familie, heitere Gleichgültigkeit gegenüber Verpflichtungen, übersteigertes Selbstgefühl.",
      "modalitiesBetter": ["Kälte", "Kaltes Baden", "Eiskompressen", "Schnelle Bewegung"],
      "modalitiesWorse": ["Wärme", "Warme Getränke", "Ruhe", "Morgen"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2x täglich 5 Globuli",
      "sphereOfAction": ["Knochen & Zähne", "Venensystem", "Haut & Haare", "Bindegewebe"],
      "differentialRemedies": ["Silicea", "Pulsatilla", "Lachesis", "Calcium fluoratum"],
      "searchKeywords": ["acidum hydrofluoricum", "acidum fluoricum", "flusssäure", "varizen", "knochenfisteln", "hitzeintoleranz"]
    },
    "en": {
      "commonName": "Hydrofluoric Acid",
      "origin": "Aqueous Hydrofluoric Acid",
      "essence": "Destructive ulcerations, bone fistulae, varicosities in warm-blooded, hyperactive subjects.",
      "mainIndications": ["Varicose veins and leg ulcers", "Bone caries and necrosis", "Alopecia and corrugated nails", "Chronic felon"],
      "keynotes": ["Extreme intolerance of warmth, craves cold baths", "Buoyant, hyperactive, senses no fatigue", "Acrid corrosive discharges", "Severe venous congestion"],
      "mindEmotional": "Indifference to loved ones, buoyant optimism, loss of affection.",
      "modalitiesBetter": ["Cold air/water", "Ice application", "Rapid walking"],
      "modalitiesWorse": ["Warmth in general", "Warm drinks", "Rest"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2x daily 5 globules",
      "sphereOfAction": ["Bones", "Veins", "Hair and nails", "Skin"],
      "differentialRemedies": ["Silicea", "Pulsatilla", "Lachesis", "Calcium fluoratum"],
      "searchKeywords": ["acidum hydrofluoricum", "hydrofluoric acid", "bone fistulae", "varicose ulcers", "heat intolerance"]
    },
    "fr": {"commonName": "Acide fluorhydrique"},
    "es": {"commonName": "Ácido fluorhídrico"},
    "it": {"commonName": "Acido fluoridrico"},
    "el": {"commonName": "Υδροφθορικό οξύ"},
    "ru": {"commonName": "Фтористоводородная кислота"}
  },
  {
    "id": "acidum-lacticum", "latinName": "Acidum lacticum", "categoryKey": "acid", "importanceTier": 3, "isPolychrest": False,
    "de": {
      "commonName": "Milchsäure",
      "origin": "Reine Milchsäure (C3H6O3)",
      "essence": "Schwangerschaftserbrechen, Diabetes mellitus mit Polyurie, Heißhunger und Schmerzen in den Brustdrüsen.",
      "mainIndications": ["Hyperemesis gravidarum (Schwangerschaftserbrechen)", "Diabetes mellitus Typ 2 mit Heißhunger & Durst", "Mastodynie und Brustschwellung", "Arthropathie mit Säuregefühl"],
      "keynotes": ["Übelkeit wird durch Essen sofort gebessert", "Ständiger Speichelfluss mit saurem Geschmack", "Großer Appetit und unlöschbarer Durst mit reichlichem Urin", "Schmerzhafte Empfindlichkeit der Mammae"],
      "mindEmotional": "Mürrisch, sarkastisch, weinerlich bei Übelkeit.",
      "modalitiesBetter": ["Essen", "Aufstoßen", "Frühstück"],
      "modalitiesWorse": ["Rauchen", "Nüchternheit", "Bewegung"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x täglich 5 Globuli vor den Mahlzeiten",
      "sphereOfAction": ["Magen", "Stoffwechsel (Glukose)", "Mammae", "Gelenke"],
      "differentialRemedies": ["Ipecacuanha", "Sepia", "Tabacum", "Phosphoric acid"],
      "searchKeywords": ["acidum lacticum", "milchsäure", "schwangerschaftserbrechen", "besser durch essen", "diabetes mellitus"]
    },
    "en": {
      "commonName": "Lactic Acid",
      "origin": "Pure Lactic Acid",
      "essence": "Morning sickness relieved by eating, diabetes with ravenous thirst/hunger, and tender breasts.",
      "mainIndications": ["Hyperemesis gravidarum", "Diabetes with polyuria and copious thirst", "Mastodynia and mammary tenderness", "Rheumatic joint pains"],
      "keynotes": ["Nausea instantly relieved by eating", "Copious salivation with sour taste", "Voracious hunger with unquenchable thirst", "Painful fullness in breasts"],
      "mindEmotional": "Cross, irritable, weeping over nausea.",
      "modalitiesBetter": ["Eating food", "Eructation", "Rest"],
      "modalitiesWorse": ["Smoking", "Empty stomach", "Motion"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x daily 5 globules before meals",
      "sphereOfAction": ["Gastric tract", "Endocrine/Pancreas", "Mammary glands"],
      "differentialRemedies": ["Ipecacuanha", "Sepia", "Tabacum", "Phosphoric acid"],
      "searchKeywords": ["acidum lacticum", "lactic acid", "morning sickness", "ameliorated by eating", "diabetes"]
    },
    "fr": {"commonName": "Acide lactique"},
    "es": {"commonName": "Ácido láctico"},
    "it": {"commonName": "Acido lattico"},
    "el": {"commonName": "Γαλακτικό οξύ"},
    "ru": {"commonName": "Молочная кислота"}
  },
  {
    "id": "acidum-nitricum", "latinName": "Acidum nitricum", "categoryKey": "acid", "importanceTier": 1, "isPolychrest": True,
    "de": {
      "commonName": "Salpetersäure",
      "origin": "Reine Salpetersäure (HNO3)",
      "essence": "Großer Polychrest bei splitterartigen stechenden Schmerzen, chronischen Ulzerationen an Haut-Schleimhaut-Übergängen und tiefsitzendem Groll.",
      "mainIndications": ["Fissuren und Aphthen mit Splitterschmerz", "Chronische Ulzera & Kondylome", "Zystitis mit übelriechendem Urin", "Proktitis & Analfissur"],
      "keynotes": ["Stechende Schmerzen wie von einem Holzsplitter", "Stinkender, strenger Schweiß und faulig riechender Urin", "Risse an Mundwinkeln, Anus und Übergangszonen", "Besserung durch gleichmäßiges Fahren im Wagen"],
      "mindEmotional": "Unversöhnlich, nachtragend, hasserfüllt, verzweifelt über die eigene Gesundheit.",
      "modalitiesBetter": ["Fahren im Wagen/Zug", "Gleichmäßiges Reiten", "Mildes Wetter"],
      "modalitiesWorse": ["Kälte", "Nacht", "Berührung", "Wetterwechsel"],
      "potenciesAndDosage": "C30, C200, LM VI",
      "defaultTagesdosis": "1 Einmalgabe à 5 Globuli",
      "sphereOfAction": ["Haut-Schleimhaut-Übergänge", "Enddarm", "Harnwege", "Gefäße"],
      "differentialRemedies": ["Hepar sulfuris", "Silicea", "Mercurius solubilis", "Thuja"],
      "searchKeywords": ["acidum nitricum", "salpetersäure", "splitterschmerz", "analfissur", "kondylome", "unversöhnlich"]
    },
    "en": {
      "commonName": "Nitric Acid",
      "origin": "Pure Nitric Acid",
      "essence": "Major polychrest characterized by splinter-like stitching pains, mucocutaneous junction fissures, offensive odors, and unforgiving malice.",
      "mainIndications": ["Anal fissures and mouth ulcers with splinter pains", "Condylomata and bleeding warts", "Fetid cystitis", "Chronic ulcerations"],
      "keynotes": ["Sticking pain as from a splinter", "Offensive urine and foot sweat", "Ulceration at muco-cutaneous junctions", "Riding in a carriage relieves"],
      "mindEmotional": "Unforgiving, malicious, vindictive, anxious about disease.",
      "modalitiesBetter": ["Riding in a carriage/train", "Mild weather", "Gentle motion"],
      "modalitiesWorse": ["Cold and damp", "Night", "Touch", "Weather changes"],
      "potenciesAndDosage": "C30, C200, LM VI",
      "defaultTagesdosis": "1 single dose of 5 globules",
      "sphereOfAction": ["Mucocutaneous borders", "Rectum", "Urinary organs", "Skin"],
      "differentialRemedies": ["Hepar sulfuris", "Silicea", "Mercurius solubilis", "Thuja"],
      "searchKeywords": ["acidum nitricum", "nitric acid", "splinter sensation", "anal fissure", "condyloma", "unforgiving"]
    },
    "fr": {"commonName": "Acide nitrique"},
    "es": {"commonName": "Ácido nítrico"},
    "it": {"commonName": "Acido nitrico"},
    "el": {"commonName": "Νιτρικό οξύ"},
    "ru": {"commonName": "Азотная кислота"}
  },
  {
    "id": "acidum-phosphoricum", "latinName": "Acidum phosphoricum", "categoryKey": "acid", "importanceTier": 1, "isPolychrest": True,
    "de": {
      "commonName": "Phosphorsäure",
      "origin": "Reine wässrige Orthophosphorsäure (H3PO4)",
      "essence": "Zentraler Polychrest bei seelischer und körperlicher Erschöpfung nach Kummer, Überarbeitung oder Verlust von Körpersäften.",
      "mainIndications": ["Burnout-Syndrom und chronische Apathie", "Folgen von Liebeskummer & Trauer", "Chronische schmerzlose Diarrhoe", "Haarausfall nach seelischem Schock"],
      "keynotes": ["Vollständige emotionale Abstumpfung und Apathie", "Körperliche Schwäche folgt der seelischen Erschöpfung", "Schmerzlose wässrige Durchfälle, die erstaunlicherweise nicht schwächen", "Milchiger, phosphatreicher Urin"],
      "mindEmotional": "Gleichgültig gegenüber allem, antwortet langsam oder nur in kurzen Silben, keine Lust zu sprechen.",
      "modalitiesBetter": ["Kurzer Schlaf", "Wärme", "Ruhe"],
      "modalitiesWorse": ["Geistige Anstrengung", "Kummer", "Verlust von Säften", "Kälte"],
      "potenciesAndDosage": "C30, C200, LM VI",
      "defaultTagesdosis": "1-2x täglich 5 Globuli",
      "sphereOfAction": ["Nervensystem", "Gemüt", "Magen-Darm-Trakt", "Haare & Haut"],
      "differentialRemedies": ["Phosphorus", "Sepia", "Ignatia", "Natrium chloratum"],
      "searchKeywords": ["acidum phosphoricum", "phosphorsäure", "burnout", "apathie", "kummer", "schmerzloser durchfall"]
    },
    "en": {
      "commonName": "Phosphoric Acid",
      "origin": "Pure Orthophosphoric Acid",
      "essence": "Foremost polychrest for mental and physical prostration following grief, emotional shock, or loss of vital fluids.",
      "mainIndications": ["Burnout and nervous exhaustion", "Ailments from grief and disappointed love", "Painless non-debilitating diarrhea", "Hair loss from acute illness or sorrow"],
      "keynotes": ["Profound emotional apathy and indifference", "Answers slowly, unwilling to speak", "Painless white water diarrhea without weakness", "Milky phosphaturic urine"],
      "mindEmotional": "Apathetic, listless, stupor-like indifference.",
      "modalitiesBetter": ["Short refreshing sleep", "Warmth", "Quiet rest"],
      "modalitiesWorse": ["Mental exertion", "Grief and sorrow", "Loss of fluids", "Cold drafts"],
      "potenciesAndDosage": "C30, C200, LM VI",
      "defaultTagesdosis": "1-2x daily 5 globules",
      "sphereOfAction": ["Central nervous system", "Mind", "Intestines", "Hair"],
      "differentialRemedies": ["Phosphorus", "Sepia", "Ignatia", "Natrium chloratum"],
      "searchKeywords": ["acidum phosphoricum", "phosphoric acid", "burnout", "grief", "apathy", "painless diarrhea"]
    },
    "fr": {"commonName": "Acide phosphorique"},
    "es": {"commonName": "Ácido fosfórico"},
    "it": {"commonName": "Acido fosforico"},
    "el": {"commonName": "Φωσφορικό οξύ"},
    "ru": {"commonName": "Фосфорная кислота"}
  },
  {
    "id": "acidum-picrinicum", "latinName": "Acidum picrinicum", "categoryKey": "acid", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Pikrinsäure",
      "origin": "Reine Pikrinsäure (Trinitrophenol)",
      "essence": "Geistiger Zusammenbruch durch Überarbeitung (Studentenkopfschmerz), schwere Beine und Priapismus.",
      "mainIndications": ["Neurasthenie und geistiges Burnout nach Prüfungen", "Okzipitaler Kopfschmerz der bis in die Wirbelsäule zieht", "Schwere Lähmigkeit der Beine", "Priapismus und sexuelle Erregung bei Erschöpfung"],
      "keynotes": ["Geringste geistige Anstrengung löst brennenden Hinterkopfschmerz aus", "Gefühl von Blei in den Beinen", "Ausgeprägte Abneigung gegen jede geistige Arbeit", "Besserung durch enges Einhüllen und Kälte"],
      "mindEmotional": "Völlig unfähig zu denken, Willensschwäche, Verzweiflung bei Arbeitsversuch.",
      "modalitiesBetter": ["Kalte Luft/Wasser", "Ruhe", "Bandagieren des Kopfes"],
      "modalitiesWorse": ["Geistige Anstrengung", "Wärme", "Aufstehen"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2x täglich 5 Globuli",
      "sphereOfAction": ["Gehirn & Rückenmark", "Nervensystem", "Genitalien"],
      "differentialRemedies": ["Gelsemium", "Acidum phosphoricum", "Silicea", "Kali phosphoricum"],
      "searchKeywords": ["acidum picrinicum", "pikrinsäure", "studentenkopfschmerz", "geistiges burnout", "lähmige beine"]
    },
    "en": {
      "commonName": "Picric Acid",
      "origin": "Pure Picric Acid",
      "essence": "Brain fag from intellectual overwork, occipital pain, profound spinal exhaustion, and priapism.",
      "mainIndications": ["Neurasthenia and exam breakdown", "Occipito-cervical headaches", "Spinal debility with heaviness of limbs", "Painful priapism"],
      "keynotes": ["Slightest mental effort brings on burning head pain", "Legs feel heavy as lead", "Complete mental burnout", "Relieved by cold applications and tight pressure"],
      "mindEmotional": "Inability to collect thoughts, dread of any work.",
      "modalitiesBetter": ["Cold air/baths", "Complete rest", "Tight binding"],
      "modalitiesWorse": ["Mental exertion", "Warmth", "Physical effort"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2x daily 5 globules",
      "sphereOfAction": ["Brain and spinal cord", "Nerves", "Sexual organs"],
      "differentialRemedies": ["Gelsemium", "Acidum phosphoricum", "Silicea", "Kali phosphoricum"],
      "searchKeywords": ["acidum picrinicum", "picric acid", "brain fag", "occipital headache", "heavy legs"]
    },
    "fr": {"commonName": "Acide picrique"},
    "es": {"commonName": "Ácido pícrico"},
    "it": {"commonName": "Acido picrico"},
    "el": {"commonName": "Πικρικό οξύ"},
    "ru": {"commonName": "Пикриновая кислота"}
  },
  {
    "id": "acidum-salicylicum", "latinName": "Acidum salicylicum", "categoryKey": "acid", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Salicylsäure",
      "origin": "Reine Salicylsäure",
      "essence": "Tinnitus mit Schwindel (Ménière-Symptomatik), akuter Gelenkrheumatismus und brennende Magen-Darm-Reizungen.",
      "mainIndications": ["Morbus Ménière mit Tinnitus und Schwindel", "Akuter fieberhafter Gelenkrheumatismus", "Dyspepsie mit starker Gärung und saurem Aufstoßen", "Pruritus & übermäßiger Fußschweiß"],
      "keynotes": ["Lautes Ohrensausen und Hörverlust", "Schwindel beim Neigen des Kopfes nach links", "Gelenke heiß geschwollen und extrem schmerzhaft", "Reichlicher saurer Schweiß"],
      "mindEmotional": "Gereizt, ängstlich, benebelt durch Ohrgeräusche.",
      "modalitiesBetter": ["Wärme", "Ruhe"],
      "modalitiesWorse": ["Kälte", "Bewegung", "Berührung", "Nachts"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x täglich 5 Globuli",
      "sphereOfAction": ["Innenohr & Gehör", "Gelenke & Sehnen", "Magen-Darm-Kanal"],
      "differentialRemedies": ["Chininum sulfuricum", "Bryonia", "Colchicum", "Salvia"],
      "searchKeywords": ["acidum salicylicum", "salicylsäure", "tinnitus", "morbus meniere", "ohrensausen", "gelenkrheumatismus"]
    },
    "en": {
      "commonName": "Salicylic Acid",
      "origin": "Pure Salicylic Acid",
      "essence": "Auditory vertigo, severe roaring tinnitus (Meniere syndrome), and acute inflammatory rheumatism.",
      "mainIndications": ["Meniere's disease and tinnitus aurium", "Acute articular rheumatism", "Gastric fermentative dyspepsia", "Profuse offensive sweat"],
      "keynotes": ["Roaring, ringing in ears with deafness", "Vertigo on tilting head to left", "Hot swollen tender joints", "Copious sour perspiration"],
      "mindEmotional": "Confused, fretful, anxious due to tinnitus.",
      "modalitiesBetter": ["Warmth", "Quiet resting"],
      "modalitiesWorse": ["Cold", "Motion", "Touch", "Night"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x daily 5 globules",
      "sphereOfAction": ["Inner ear", "Joints", "Digestive tract"],
      "differentialRemedies": ["Chininum sulfuricum", "Bryonia", "Colchicum", "Salvia"],
      "searchKeywords": ["acidum salicylicum", "salicylic acid", "tinnitus", "meniere disease", "ear roaring", "rheumatism"]
    },
    "fr": {"commonName": "Acide salicylique"},
    "es": {"commonName": "Ácido salicílico"},
    "it": {"commonName": "Acido salicilico"},
    "el": {"commonName": "Σαλικυλικό οξύ"},
    "ru": {"commonName": "Салициловая кислота"}
  },
  {
    "id": "acidum-sulfuricum", "latinName": "Acidum sulfuricum", "categoryKey": "acid", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Schwefelsäure",
      "origin": "Reine Schwefelsäure (H2SO4)",
      "essence": "Tiefe Schwäche mit innerem Zittern, ständiger Eile, Neigung zu Hämatomen, Aphthen und saurem Magenbrennen.",
      "mainIndications": ["Chronische Gastritis mit saurem Reflux", "Neigung zu spontanen Blutergüssen (Purpura)", "Schwere Schwäche nach Infekten mit Zittern", "Aphthen und Schleimhauterosionen"],
      "keynotes": ["Ständiges Gefühl von innerem Zittern ohne sichtbares Beben", "Immer in extremer Eile, alles muss sofort geschehen", "Saures Aufstoßen, das die Zähne stumpf macht", "Bläuliche Flecken (Suffusionen) bei geringster Prellung"],
      "mindEmotional": "Ungeduldig, hastig, kann nichts langsam tun, reizbar bei geringsten Verzögerungen.",
      "modalitiesBetter": ["Wärme", "Heiße Getränke", "Aufstoßen"],
      "modalitiesWorse": ["Kälte", "Geruch von Kaffee", "Rauch", "Morgen"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x täglich 5 Globuli",
      "sphereOfAction": ["Magen-Darm-Trakt", "Blutgefäße (Kapillaren)", "Schleimhäute", "Nervensystem"],
      "differentialRemedies": ["Arnica", "Sulfur", "Sulfuricum acidum", "Nux vomica"],
      "searchKeywords": ["acidum sulfuricum", "schwefelsäure", "inneres zittern", "in eile", "hämatome", "saures aufstoßen"]
    },
    "en": {
      "commonName": "Sulfuric Acid",
      "origin": "Pure Sulfuric Acid",
      "essence": "Profound weakness with internal trembling, hurried disposition, ecchymoses, and sour eructations.",
      "mainIndications": ["Gastritis with heartburn and sour vomiting", "Purpura and easy bruising", "Debility with inner trembling", "Aphthous stomatitis"],
      "keynotes": ["Internal trembling without visible shaking", "Hurried in everything she does", "Sour teeth-setting eructations", "Ecchymosis from slight trauma"],
      "mindEmotional": "Impatient, restless haste, irritable at delay.",
      "modalitiesBetter": ["Warmth", "Hot drinks", "Eructation"],
      "modalitiesWorse": ["Cold", "Open air", "Morning hours"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x daily 5 globules",
      "sphereOfAction": ["Digestive tract", "Capillaries and blood", "Mucous membranes"],
      "differentialRemedies": ["Arnica", "Sulfur", "Sulfuricum acidum", "Nux vomica"],
      "searchKeywords": ["acidum sulfuricum", "sulfuric acid", "internal trembling", "hurry", "easy bruising", "sour reflux"]
    },
    "fr": {"commonName": "Acide sulfurique"},
    "es": {"commonName": "Ácido sulfúrico"},
    "it": {"commonName": "Acido solforico"},
    "el": {"commonName": "Θειικό οξύ"},
    "ru": {"commonName": "Серная кислота"}
  },
  {
    "id": "aconitum", "latinName": "Aconitum", "categoryKey": "plant", "importanceTier": 1, "isPolychrest": True,
    "de": {
      "commonName": "Blauer Eisenhut",
      "origin": "Frische zur Blütezeit gesammelte Pflanze Aconitum napellus",
      "essence": "Erstes Mittel für akute, plötzliche, stürmische Erkrankungen nach kaltem trockenem Wind mit Todesangst und panischer Unruhe.",
      "mainIndications": ["Akutes plötzliches Fieber ohne Schweiß", "Todesangst & Panikattacken", "Akuter Krupphusten & Laryngitis", "Früheste Phase von Infektionen"],
      "keynotes": ["Plötzlicher, stürmischer Beginn um Mitternacht", "Unstillbare Angst mit Todesahnung", "Trockene brennende Haut, Durst auf kaltes Wasser", "Ursache: Schock, Schreck oder kalter Ostwind"],
      "mindEmotional": "Panische Todesangst, sagt die Todesstunde voraus, extreme Ruhelosigkeit.",
      "modalitiesBetter": ["Frische Luft", "Ruhe"],
      "modalitiesWorse": ["Kalter trockener Wind", "Mitternacht", "Aufrichten", "Lärm & Licht"],
      "potenciesAndDosage": "C30, C200 (im Akutfall stündlich)",
      "defaultTagesdosis": "Akut: alle 1-2h 5 Globuli, sonst 3x täglich",
      "sphereOfAction": ["Herz-Kreislauf-System", "Atemwege", "Zentralnervensystem", "Vagus"],
      "differentialRemedies": ["Belladonna", "Arsenicum album", "Ferrum phosphoricum", "Chamomilla"],
      "searchKeywords": ["aconitum", "aconitum napellus", "blauer eisenhut", "akutes fieber", "todesangst", "kaltwind", "panik"]
    },
    "en": {
      "commonName": "Monkshood",
      "origin": "Whole fresh blooming plant of Aconitum napellus",
      "essence": "Supreme remedy for sudden, violent acute inflammatory storms with intense panic, restlessness, and fear of death.",
      "mainIndications": ["Sudden acute fever with dry burning skin", "Panic attacks and fear of death", "Acute croup and laryngitis", "First stage of inflammatory states"],
      "keynotes": ["Sudden onset after exposure to dry cold wind", "Terror, predicts the hour of death", "Dry heat without perspiration, great thirst for cold water", "Aggravation around midnight"],
      "mindEmotional": "Agonizing fear of death, restless tossing.",
      "modalitiesBetter": ["Fresh open air", "Quiet resting"],
      "modalitiesWorse": ["Cold dry wind", "Around midnight", "Rising from bed", "Noise and light"],
      "potenciesAndDosage": "C30, C200",
      "defaultTagesdosis": "Acute: 5 globules every 1-2h",
      "sphereOfAction": ["Cardiovascular system", "Respiratory tract", "Nervous system"],
      "differentialRemedies": ["Belladonna", "Arsenicum album", "Ferrum phosphoricum", "Chamomilla"],
      "searchKeywords": ["aconitum", "aconite", "monkshood", "sudden fever", "fear of death", "cold dry wind"]
    },
    "fr": {"commonName": "Aconit napel"},
    "es": {"commonName": "Acónito"},
    "it": {"commonName": "Aconito"},
    "el": {"commonName": "Ακόνιτο"},
    "ru": {"commonName": "Аконит клобучковый"}
  },
  {
    "id": "actaea-spicata", "latinName": "Actaea spicata", "categoryKey": "plant", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Christophskraut",
      "origin": "Frische Wurzelstöcke von Actaea spicata",
      "essence": "Rheumatismus der kleinen Gelenke (Finger und Handgelenke) mit Schwellung und Verschlimmerung durch geringste Bewegung.",
      "mainIndications": ["Rheumatische Arthritis der Finger und Zehen", "Handgelenksschmerzen mit Anschwellung", "Spitzfuß- und Knöchelschmerzen", "Rheumatoide Deformitäten der kleinen Gelenke"],
      "keynotes": ["Befällt spezifisch die kleinen Gelenke (Finger, Handwurzel, Zehen)", "Gelenke schwellen nach der geringsten Anstrengung an", "Reißende, ziehende Schmerzen wie von einem Stromschlag", "Große Schwäche und Zerschlagenheit nach Schmerzanfällen"],
      "mindEmotional": "Ängstlich, fürchtet den Tod, reizbar durch ständige Gelenkschmerzen.",
      "modalitiesBetter": ["Wärme", "Ruhe im Bett"],
      "modalitiesWorse": ["Berührung", "Bewegung", "Kälte & feuchtes Wetter", "Nacht"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x täglich 5 Globuli",
      "sphereOfAction": ["Kleine Gelenke (Finger/Zehen)", "Bänder & Sehnen", "Nerven"],
      "differentialRemedies": ["Caulophyllum", "Ruta", "Ledum", "Colchicum"],
      "searchKeywords": ["actaea spicata", "christophskraut", "kleine gelenke", "fingergelenke", "arthrose hand"]
    },
    "en": {
      "commonName": "Baneberry",
      "origin": "Fresh root of Actaea spicata",
      "essence": "Rheumatism of small joints (fingers, wrists, toes) with violent tearing pains aggravated by slight exertion.",
      "mainIndications": ["Rheumatoid arthritis of small joints", "Wrist swelling and pain", "Ankle and foot pain", "Tearing articular neuralgia"],
      "keynotes": ["Affinity for small joints of hands and feet", "Joints swell significantly after any exertion", "Tearing, tingling pains worse from touch", "Great debility after paroxysms"],
      "mindEmotional": "Fretful, anxious, fears death from exhaustion.",
      "modalitiesBetter": ["Warmth", "Resting in bed"],
      "modalitiesWorse": ["Touch and movement", "Cold damp weather", "Night"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x daily 5 globules",
      "sphereOfAction": ["Small joints", "Ligaments", "Nerves"],
      "differentialRemedies": ["Caulophyllum", "Ruta", "Ledum", "Colchicum"],
      "searchKeywords": ["actaea spicata", "baneberry", "small joints rheumatism", "finger arthritis", "wrist swelling"]
    },
    "fr": {"commonName": "Actée en épi"},
    "es": {"commonName": "Hierba de San Cristóbal"},
    "it": {"commonName": "Erba di San Cristoforo"},
    "el": {"commonName": "Ακταία η σταχυώδης"},
    "ru": {"commonName": "Воронец колосистый"}
  },
  {
    "id": "adonis-vernalis", "latinName": "Adonis vernalis", "categoryKey": "plant", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Frühlings-Adonisröschen",
      "origin": "Frische blühende Pflanze von Adonis vernalis",
      "essence": "Kardiales Tonikum bei Herzinsuffizienz, Myokardschwäche, Ödemen und unregelmäßigem Puls.",
      "mainIndications": ["Herzinsuffizienz & Altersherz", "Kardiale Ödeme & Atemnot bei Anstrengung", "Arrhythmie & Extrasystolen", "Präkordiale Beklemmung"],
      "keynotes": ["Schweregefühl und Enge auf der Brust wie von einem schweren Gewicht", "Unregelmäßiger, schneller oder schwacher Puls", "Wassersucht mit verminderter Harnausscheidung", "Herzklopfen schon bei geringster Bewegung"],
      "mindEmotional": "Ängstlich beklommen, unruhig durch Herzklopfen, Schlaflosigkeit.",
      "modalitiesBetter": ["Aufrechtes Sitzen", "Ruhe", "Frische Luft"],
      "modalitiesWorse": ["Flaches Liegen", "Körperliche Anstrengung", "Kälte"],
      "potenciesAndDosage": "D2, D3, D6",
      "defaultTagesdosis": "3x täglich 5 Globuli",
      "sphereOfAction": ["Myokard & Herzklappen", "Nieren (Ausscheidung)", "Kreislauf"],
      "differentialRemedies": ["Digitalis", "Crataegus", "Convallaria", "Strophanthus"],
      "searchKeywords": ["adonis vernalis", "adonisröschen", "herzinsuffizienz", "kardiale ödeme", "altersherz", "arrhythmie"]
    },
    "en": {
      "commonName": "Pheasant's Eye",
      "origin": "Fresh flowering herb of Adonis vernalis",
      "essence": "Cardiac tonic for myocardial weakness, dropsy, dyspnea on exertion, and irregular pulse.",
      "mainIndications": ["Cardiac insufficiency and fatty heart", "Dropsy with oliguria", "Arrhythmia and palpitations", "Precordial oppression"],
      "keynotes": ["Heavy weight sensation on the chest", "Irregular rapid feeble pulse", "Oliguria with cardiac edema", "Palpitations on slight movement"],
      "mindEmotional": "Anxious, restless due to heart palpitations.",
      "modalitiesBetter": ["Sitting upright", "Rest", "Open air"],
      "modalitiesWorse": ["Lying flat", "Physical exertion", "Cold"],
      "potenciesAndDosage": "D2, D3, D6",
      "defaultTagesdosis": "3x daily 5 globules",
      "sphereOfAction": ["Myocardium", "Kidneys", "Circulation"],
      "differentialRemedies": ["Digitalis", "Crataegus", "Convallaria", "Strophanthus"],
      "searchKeywords": ["adonis vernalis", "pheasants eye", "cardiac dropsy", "heart failure", "arrhythmia"]
    },
    "fr": {"commonName": "Adonis de printemps"},
    "es": {"commonName": "Adonis vernal"},
    "it": {"commonName": "Adonide primaverile"},
    "el": {"commonName": "Άδωνις ο εαρινός"},
    "ru": {"commonName": "Адонис весенний"}
  },
  {
    "id": "aesculus", "latinName": "Aesculus", "categoryKey": "plant", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Rosskastanie",
      "origin": "Frische reife Samen von Aesculus hippocastanum",
      "essence": "Venöse Stauungen, Hämorrhoiden mit Splittergefühl und quälende Kreuzschmerzen in der Iliosakralregion.",
      "mainIndications": ["Hämorrhoiden (trocken, purpurfarben)", "Kreuzschmerzen & Sakralgie", "Venöse Stase & Krampfadern", "Proktitis mit Trockenheitsgefühl"],
      "keynotes": ["Gefühl von trockenen Holzsplittern im Rektum", "Kreuzschmerz macht Aufstehen vom Stuhl fast unmöglich", "Kaum Blutungen bei den Hämorrhoiden, aber starke Schmerzen", "Völlegefühl und venöse Stauung in Pfortader und Becken"],
      "mindEmotional": "Depressiv, reizbar, verstimmt nach dem Erwachen.",
      "modalitiesBetter": ["Kühle frische Luft", "Mäßige Bewegung"],
      "modalitiesWorse": ["Stehen", "Gehen", "Aufstehen vom Sitzen", "Morgen"],
      "potenciesAndDosage": "D4, D6, D12, C30",
      "defaultTagesdosis": "3x täglich 5 Globuli",
      "sphereOfAction": ["Pfortadersystem", "Rektum & Venen", "Kreuzbein/Iliosakralgelenk"],
      "differentialRemedies": ["Hamamelis", "Collinsonia", "Paeonia", "Aloe"],
      "searchKeywords": ["aesculus", "aesculus hippocastanum", "rosskastanie", "hämorrhoiden", "kreuzschmerzen", "splittergefühl rektum"]
    },
    "en": {
      "commonName": "Horse Chestnut",
      "origin": "Fresh ripe nuts of Aesculus hippocastanum",
      "essence": "Venous engorgement especially of portal and hemorrhoidal vessels with characteristic sacral backache.",
      "mainIndications": ["Hemorrhoids (dry, purple, painful)", "Sacroiliac low back pain", "Venous stasis and varicose veins", "Follicular pharyngitis"],
      "keynotes": ["Rectum feels full of dry splinters", "Severe aching in sacrum makes rising from seat difficult", "Hemorrhoids rarely bleed but ache intensely", "Portal congestion and fullness"],
      "mindEmotional": "Gloomy, irritable, wakes depressed.",
      "modalitiesBetter": ["Cool open air", "Gentle continuous walking"],
      "modalitiesWorse": ["Standing", "Walking", "Rising from a seat", "Morning"],
      "potenciesAndDosage": "D4, D6, D12, C30",
      "defaultTagesdosis": "3x daily 5 globules",
      "sphereOfAction": ["Portal system", "Rectum and veins", "Sacroiliac joints"],
      "differentialRemedies": ["Hamamelis", "Collinsonia", "Paeonia", "Aloe"],
      "searchKeywords": ["aesculus", "horse chestnut", "hemorrhoids", "splinters in rectum", "sacroiliac backache"]
    },
    "fr": {"commonName": "Marronnier d'Inde"},
    "es": {"commonName": "Castaño de Indias"},
    "it": {"commonName": "Ippocastano"},
    "el": {"commonName": "Αγριοκαστανιά"},
    "ru": {"commonName": "Конский каштан"}
  },
  {
    "id": "aethusa", "latinName": "Aethusa", "categoryKey": "plant", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Hundspetersilie",
      "origin": "Frische blühende Pflanze Aethusa cynapium",
      "essence": "Milchunverträglichkeit bei Säuglingen, schwallartiges Erbrechen dicker Milchklumpen gefolgt von tiefer Schläfrigkeit.",
      "mainIndications": ["Gastroenteritis & Milchunverträglichkeit bei Säuglingen", "Prüfungsangst & geistige Blockaden", "Dentitionsprobleme mit Erbrechen", "Sommerdiarrhoe bei Kindern"],
      "keynotes": ["Vollständige Unfähigkeit, Milch in jeglicher Form zu verdauen", "Plötzliches Erbrechen geronnener Milchklumpen", "Tiefe Erschöpfung und sofortiges Einschlafen nach dem Erbrechen", "Ausgeprägte Denkunfähigkeit und Konzentrationsstörung"],
      "mindEmotional": "Geistige Schwäche, Unfähigkeit zu denken oder zu lernen, Gefühl von Isoliertheit.",
      "modalitiesBetter": ["Frische Luft", "Spaziergang im Freien", "Schlaf"],
      "modalitiesWorse": ["Milch", "Wärme", "Nach dem Erbrechen", "Sommer"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x täglich 5 Globuli",
      "sphereOfAction": ["Magen-Darm-Trakt", "Gehirn & Kognition", "Vegetatives Nervensystem"],
      "differentialRemedies": ["Calcium carbonicum", "Magnesium muriaticum", "Antimonium crudum", "Ipecacuanha"],
      "searchKeywords": ["aethusa", "aethusa cynapium", "hundspetersilie", "milchunverträglichkeit", "milch erbrechen", "prüfungsangst"]
    },
    "en": {
      "commonName": "Fool's Parsley",
      "origin": "Fresh flowering herb of Aethusa cynapium",
      "essence": "Intolerance of milk in infants, projectile vomiting of curdled milk followed by profound exhaustion and sleep.",
      "mainIndications": ["Infantile digestive disorders and milk intolerance", "Examination funk and mental paralysis", "Dentition vomiting", "Summer diarrhea in babies"],
      "keynotes": ["Total intolerance of milk in any form", "Sudden violent vomiting of huge curdled lumps", "Profound stupor and sleep immediately after vomiting", "Inability to focus thoughts or retain information"],
      "mindEmotional": "Brain fag, incapacity to think or study, anxious crying.",
      "modalitiesBetter": ["Open air", "Walking outdoors", "Sleep"],
      "modalitiesWorse": ["Milk", "Warmth", "After stool/vomit", "Summer heat"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "3x daily 5 globules",
      "sphereOfAction": ["Gastrointestinal tract", "Brain/Cognition", "Autonomic nerves"],
      "differentialRemedies": ["Calcium carbonicum", "Magnesium muriaticum", "Antimonium crudum", "Ipecacuanha"],
      "searchKeywords": ["aethusa", "fools parsley", "milk vomiting", "curdled milk", "brain fag", "examination funk"]
    },
    "fr": {"commonName": "Ciguë des jardins"},
    "es": {"commonName": "Cicuta menor"},
    "it": {"commonName": "Cicuta minore"},
    "el": {"commonName": "Αίθουσα"},
    "ru": {"commonName": "Кокорыш"}
  },
  {
    "id": "agaricus-muscarius", "latinName": "Agaricus muscarius", "categoryKey": "plant", "importanceTier": 2, "isPolychrest": False,
    "de": {
      "commonName": "Fliegenpilz",
      "origin": "Frischer Fruchtkörper von Amanita muscaria",
      "essence": "Neurologisches Mittel bei Muskelzuckungen, Chorea, Ticks, Frostbeulen mit Brennen und Stechen sowie Kreuzschmerzen.",
      "mainIndications": ["Chorea minor & nervöse Ticks", "Frostbeulen (Perniones) mit Brennen & Jucken", "Zuckungen der Augenlider und Gesichtsmuskeln", "Wirbelsäulenreizung & Lumbago"],
      "keynotes": ["Zuckungen hören im Schlaf vollständig auf", "Symptome treten diagonal auf (rechter Arm und linkes Bein)", "Brennendes, stechendes Jucken wie von Eisnadeln", "Übermäßige Schmerzempfindlichkeit der Wirbelsäule bei Berührung"],
      "mindEmotional": "Wahnideen von Stärke und Größe, geschwätzig, ungeschicktes Fallenlassen von Gegenständen.",
      "modalitiesBetter": ["Sanfte Bewegung", "Im Schlaf", "Wärme"],
      "modalitiesWorse": ["Kälte & Frost", "Nach dem Koitus", "Geistige Anstrengung", "Vor Gewitter"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2-3x täglich 5 Globuli",
      "sphereOfAction": ["Zentralnervensystem", "Rückenmark & Motorik", "Haut (Kapillaren)"],
      "differentialRemedies": ["Zincum metallicum", "Mygale", "Tarentula hispanica", "Cicuta"],
      "searchKeywords": ["agaricus muscarius", "fliegenpilz", "muskelzucken", "ticks", "chorea", "frostbeulen", "augenzucken"]
    },
    "en": {
      "commonName": "Fly Agaric",
      "origin": "Fresh mushroom Amanita muscaria",
      "essence": "Neurological remedy for muscular twitchings, chorea, tremors, chilblains, and sensitive spine.",
      "mainIndications": ["Chorea and nervous tics", "Chilblains with burning and itching", "Blepharospasm and facial spasms", "Spinal irritation"],
      "keynotes": ["Twitching ceases during sleep", "Diagonal symptoms (right arm and left leg)", "Burning itching as if frozen with ice needles", "Spine exquisitely tender to touch"],
      "mindEmotional": "Delirium with ecstasy and strength, loquacious, clumsiness.",
      "modalitiesBetter": ["Slow gentle motion", "Sleep", "Warmth"],
      "modalitiesWorse": ["Cold weather and frost", "After coitus", "Before storm"],
      "potenciesAndDosage": "D6, D12, C30",
      "defaultTagesdosis": "2-3x daily 5 globules",
      "sphereOfAction": ["Cerebrospinal system", "Motor nerves", "Skin"],
      "differentialRemedies": ["Zincum metallicum", "Mygale", "Tarentula hispanica", "Cicuta"],
      "searchKeywords": ["agaricus muscarius", "fly agaric", "muscle twitching", "chorea", "chilblains", "eyelid twitching"]
    },
    "fr": {"commonName": "Amanite tue-mouches"},
    "es": {"commonName": "Matamoscas"},
    "it": {"commonName": "Amanita muscaria"},
    "el": {"commonName": "Αγαρικό"},
    "ru": {"commonName": "Мухомор красный"}
  }
]

print(f"Data A loaded: {len(DATA_A)} remedies")
