# scripts/full_remedy_roster.py
# Complete authoritative roster of 314 classical remedies from Hahnemann, Kent, and Hering

ROSTER = [
    # A
    ("actaea-spicata", "Actaea spicata", "plant", ["kent", "hering"], "Christophskraut", "Baneberry", "Rheuma kleiner Gelenke", "Small joint arthritis"),
    ("adonis-vernalis", "Adonis vernalis", "plant", ["hering"], "Frühlings-Adonisröschen", "Pheasant's Eye", "Herzinsuffizienz und Ödeme", "Heart failure and dropsy"),
    ("alstonia-scholaris", "Alstonia scholaris", "plant", ["hering"], "Dita-Rinde", "Dita Bark", "Malariale Rekonvaleszenz und Durchfall", "Malarial debility and diarrhea"),
    ("alumina-phosphorica", "Alumina phosphorica", "mineral", ["kent"], "Aluminiumphosphat", "Aluminium Phosphate", "Nervenschwäche und Obstipation", "Nervous exhaustion and constipation"),
    ("alumina-silicata", "Alumina silicata", "mineral", ["kent"], "Aluminiumsilikat", "Aluminium Silicate", "Trockener Katarrh und Verstopfung", "Dry catarrh and constipation"),
    ("ambrosia-artemisiifolia", "Ambrosia artemisiifolia", "plant", ["hering"], "Beifußblättrige Ambrosie", "Ragweed", "Heuschnupfen mit Augenjucken", "Hay fever with eye itching"),
    ("ammoniacum-gummi", "Ammoniacum gummi", "plant", ["hering"], "Ammoniakgummi", "Gum Ammoniac", "Seniler Bronchialkatarrh mit zähem Schleim", "Senile bronchial catarrh"),
    ("ammonium-benzoicum", "Ammonium benzoicum", "mineral", ["hering"], "Ammoniumbenzoat", "Ammonium Benzoate", "Gicht mit rauchigem Urin", "Gout with smoky urine"),
    ("ammonium-bromatum", "Ammonium bromatum", "mineral", ["hering"], "Ammoniumbromid", "Ammonium Bromide", "Krampfhusten und Larynxkitzeln", "Spasmodic suffocation cough"),
    ("ammonium-causticum", "Ammonium causticum", "mineral", ["hering"], "Salmiakgeist", "Ammonia Water", "Krupp mit Verätzungsgefühl im Kehlkopf", "Membranous croup with rawness"),
    ("ammonium-iodatum", "Ammonium iodatum", "mineral", ["hering"], "Ammoniumiodid", "Ammonium Iodide", "Laryngitis und Struma", "Laryngitis and goiter"),
    ("ammonium-muriaticum", "Ammonium muriaticum", "mineral", ["hahnemann", "kent", "hering"], "Salmiaksalz", "Ammonium Chloride", "Sehnenverkürzung und bröckeliger Stuhl", "Hamstring contraction and crumbly stool"),
    ("ammonium-phosphoricum", "Ammonium phosphoricum", "mineral", ["kent"], "Ammoniumphosphat", "Ammonium Phosphate", "Gichtknoten an Fingern", "Gouty finger nodosities"),
    ("ammonium-valerianicum", "Ammonium valerianicum", "mineral", ["hering"], "Ammoniumvalerianat", "Ammonium Valerianate", "Nervöses Herzklopfen und Schlaflosigkeit", "Nervous palpitations and insomnia"),
    ("amylenum-nitrosum", "Amylenum nitrosum", "mineral", ["hering"], "Amylnitrit", "Amyl Nitrite", "Klimakterische Hitzewallungen mit Erröten", "Climacteric hot flushes"),
    ("anagallis-arvensis", "Anagallis arvensis", "plant", ["hering"], "Ackergauchheil", "Scarlet Pimpernel", "Bläschenekzem an Händen und Urethritis", "Palmar vesicular eczema and urethritis"),
    ("angustura-vera", "Angustura vera", "plant", ["hahnemann", "hering"], "Echte Angusturarinde", "Angostura Bark", "Krämpfe, Tetanus und Knochenschmerzen", "Tetanic spasms and bone pain"),
    ("anhalonium-lewinii", "Anhalonium lewinii", "plant", ["hering"], "Peyote-Kaktus", "Peyote", "Visuelle Halluzinationen und Farbensehen", "Visual hallucinations and colors"),
    ("anisum-stellatum", "Anisum stellatum", "plant", ["hahnemann", "hering"], "Sternanis", "Star Anise", "Schmerz an dritter rechter Rippe und Koliken", "Third rib stitch and colic"),
    ("anthemis-nobilis", "Anthemis nobilis", "plant", ["hering"], "Römische Kamille", "Roman Chamomile", "Magenkälte und dyspeptischer Kopfschmerz", "Gastric coldness and headache"),
    ("anthracinum", "Anthracinum", "nosode", ["hering"], "Milzbrand-Nosode", "Anthrax Nosode", "Maligne Karbunkel und brennende Schmerzen", "Malignant carbuncles with burning"),
    ("antimonium-arsenicosum", "Antimonium arsenicosum", "mineral", ["hering"], "Antimonarsenit", "Antimony Arsenite", "Pneumonie mit lautem Rasseln", "Pneumonia with loud rattling"),
    ("antimonium-iodatum", "Antimonium iodatum", "mineral", ["hering"], "Antimoniodid", "Antimony Iodide", "Bronchitis mit zähem süßlichem Auswurf", "Bronchitis with sweetish sputum"),
    ("antimonium-sulfuratum-aurantiacum", "Antimonium sulfuratum aurantiacum", "mineral", ["kent", "hering"], "Goldschwefel", "Golden Sulfide of Antimony", "Zäher Schleim und Akne pustulosa", "Tenacious mucus and acne"),
    ("apium-graveolens", "Apium graveolens", "plant", ["hering"], "Echter Sellerie", "Celery", "Urtikaria und nervöse Unruhe", "Urticaria and nervous fidgets"),
    ("apocynum-androsaemifolium", "Apocynum androsaemifolium", "plant", ["hering"], "Fliegenfängerkraut", "Spreading Dogbane", "Gelenkrheuma mit Schweregefühl", "Joint rheumatism and heaviness"),
    ("apocynum-cannabinum", "Apocynum cannabinum", "plant", ["kent", "hering"], "Indianischer Hanf", "Indian Hemp", "Wassersucht mit großem Durst", "Dropsy with intense thirst"),
    ("apomorphinum", "Apomorphinum", "mineral", ["hering"], "Apomorphin", "Apomorphine", "Heftiges reflexartiges Erbrechen", "Violent projectile reflex vomiting"),
    ("aralia-racemosa", "Aralia racemosa", "plant", ["hering"], "Amerikanische Narde", "American Spikenard", "Asthma um Mitternacht nach erstem Schlaf", "Asthma at midnight after first sleep"),
    ("aranea-diadema", "Aranea diadema", "animal", ["hering"], "Kreuzspinne", "Diadem Spider", "Knochenkälte und Wechselfieber", "Bone chill and intermittent fever"),
    ("argentum-cyanatum", "Argentum cyanatum", "mineral", ["hering"], "Silberzyanid", "Silver Cyanide", "Laryngitis und Angina pectoris", "Laryngitis and angina pectoris"),
    ("argentum-iodatum", "Argentum iodatum", "mineral", ["hering"], "Silberiodid", "Silver Iodide", "Sängerknötchen und Heiserkeit", "Singer's nodes and hoarseness"),
    ("argentum-metallicum", "Argentum metallicum", "mineral", ["hahnemann", "kent", "hering"], "Reines Silber", "Silver", "Kehlkopfschäden bei Sprechern und Sängern", "Laryngeal weakness in vocalists"),
    ("aristolochia-clematitis", "Aristolochia clematitis", "plant", ["hering"], "Osterluzei", "Birthwort", "Zystitis und Beckenstauung", "Cystitis and pelvic congestion"),
    ("arsenicum-bromatum", "Arsenicum bromatum", "mineral", ["hering"], "Arsenikbromid", "Arsenic Bromide", "Akne und Drüsenschwellungen", "Acne and glandular induration"),
    ("arsenicum-hydrogenisatum", "Arsenicum hydrogenisatum", "mineral", ["kent", "hering"], "Arsenwasserstoff", "Arsine", "Schwere Hämolyse und Kollaps", "Severe hemolysis and collapse"),
    ("arsenicum-iodatum", "Arsenicum iodatum", "mineral", ["kent", "hering"], "Arsentriiodid", "Arsenic Triiodide", "Allergischer Fließschnupfen und Psoriasis", "Excoriating coryza and psoriasis"),
    ("arsenicum-metallicum", "Arsenicum metallicum", "mineral", ["kent", "hering"], "Metallisches Arsen", "Metallic Arsenic", "Ödeme und brennende Neuralgien", "Edema and burning neuralgia"),
    ("arsenicum-sulfuratum-flavum", "Arsenicum sulfuratum flavum", "mineral", ["kent", "hering"], "Auripigment", "Yellow Sulfide of Arsenic", "Hartnäckige Ekzeme und feuchter Husten", "Stubborn eczema and moist cough"),
    ("arsenicum-sulfuratum-rubrum", "Arsenicum sulfuratum rubrum", "mineral", ["hering"], "Realgar", "Red Sulfide of Arsenic", "Ulzera und Schleimhautentzündungen", "Ulcers and mucosal inflammation"),
    ("artemisia-vulgaris", "Artemisia vulgaris", "plant", ["hering"], "Gemeiner Beifuß", "Mugwort", "Epileptiforme Krämpfe bei Schreck", "Epileptiform spasms from fright"),
    ("arum-dracontium", "Arum dracontium", "plant", ["hering"], "Drachenwurz", "Green Dragon", "Kehlkopfkatarrh und Schluckschmerz", "Laryngeal catarrh and painful swallowing"),
    ("arum-maculatum", "Arum maculatum", "plant", ["hering"], "Gefleckter Aronstab", "Cuckoo Pint", "Brennen der Zunge und Nasenbluten", "Burning of tongue and epistaxis"),
    ("arundo-mauritanica", "Arundo mauritanica", "plant", ["hering"], "Italienisches Pfahlrohr", "Reed", "Heuschnupfen mit Gaumenjucken", "Hay fever with itchy palate"),
    ("asa-foetida", "Asa foetida", "plant", ["hahnemann", "kent", "hering"], "Stinkasant", "Asafetida", "Globus hystericus und Knochenschmerzen", "Globus hystericus and bone pain"),
    ("asarum-europaeum", "Asarum europaeum", "plant", ["hahnemann", "kent", "hering"], "Haselwurz", "Wild Ginger", "Überempfindlichkeit gegen Kratzgeräusche", "Oversensitivity to scratching sounds"),
    ("asclepias-cornuti", "Asclepias cornuti", "plant", ["hering"], "Syrische Seidenpflanze", "Milkweed", "Kopfschmerz mit reichlichem Urinieren", "Headache with profuse urination"),
    ("asclepias-tuberosa", "Asclepias tuberosa", "plant", ["hering"], "Knollige Seidenpflanze", "Pleurisy Root", "Pleuritis mit stechendem Schmerz", "Pleurisy with sharp stitching pain"),
    ("asparagus-officinalis", "Asparagus officinalis", "plant", ["hering"], "Gemüsespargel", "Garden Asparagus", "Herzklopfen und Harndrang mit Uringeruch", "Palpitations and smelly urine"),
    ("astacus-fluviatilis", "Astacus fluviatilis", "animal", ["hering"], "Flusskrebs", "Crawfish", "Nesselsucht am ganzen Körper mit Leberbezug", "General urticaria with liver affection"),
    ("asterias-rubens", "Asterias rubens", "animal", ["kent", "hering"], "Roter Seestern", "Starfish", "Mamma-Affektionen und Hitzewallungen", "Mammary affections and flushes of heat"),
    ("atropinum-sulfuricum", "Atropinum sulfuricum", "plant", ["hering"], "Atropinsulfat", "Atropine Sulfate", "Akute Mydriasis und zerebrale Hyperämie", "Pupillary dilation and flushed head"),
    ("aurum-arsenicosum", "Aurum arsenicosum", "mineral", ["kent"], "Goldarsenit", "Gold Arsenite", "Herzleiden mit schwerer Depression", "Heart disease with severe depression"),
    ("aurum-bromatum", "Aurum bromatum", "mineral", ["hering"], "Goldbromid", "Gold Bromide", "Nervöse Depression und Schlaflosigkeit", "Nervous depression and insomnia"),
    ("aurum-iodatum", "Aurum iodatum", "mineral", ["kent", "hering"], "Goldiodid", "Gold Iodide", "Arteriosklerose und Herzhypertrophie", "Arteriosclerosis and cardiac hypertrophy"),
    ("aurum-muriaticum", "Aurum muriaticum", "mineral", ["kent", "hering"], "Goldchlorid", "Gold Chloride", "Uterusmyome und Herzpalpitationen", "Uterine fibroids and palpitations"),
    ("aurum-muriaticum-kalinatum", "Aurum muriaticum kalinatum", "mineral", ["hering"], "Kaliumgoldchlorid", "Potassium Gold Chloride", "Uterusschwellungen und Sklerose", "Uterine induration and sclerosis"),
    ("aurum-muriaticum-natronatum", "Aurum muriaticum natronatum", "mineral", ["kent", "hering"], "Natriumgoldchlorid", "Sodium Chloroaurate", "Uterussenkung und Myome", "Uterine prolapse and fibroids"),
    ("aurum-sulfuratum", "Aurum sulfuratum", "mineral", ["kent", "hering"], "Goldsulfid", "Gold Sulfide", "Nachtschweiß und depressive Verzweiflung", "Night sweats and depressive despair"),
    # B
    ("badiaga", "Badiaga", "animal", ["kent", "hering"], "Süßwasserschwamm", "Fresh-Water Sponge", "Schmerzhafte Augenäpfel und Drüsenschwellungen", "Sore eyeballs and glandular swelling"),
    ("balsamum-peruvianum", "Balsamum peruvianum", "plant", ["hering"], "Perubalsam", "Balsam of Peru", "Eiteriger Bronchialkatarrh und Hautrisse", "Purulent bronchial catarrh and rhagades"),
    ("baryta-acetica", "Baryta acetica", "mineral", ["hahnemann", "hering"], "Bariumacetat", "Barium Acetate", "Senile Schwäche und Gedächtnisverlust", "Senile weakness and memory loss"),
    ("baryta-iodata", "Baryta iodata", "mineral", ["kent", "hering"], "Bariumiodid", "Barium Iodide", "Verhärtete Tonsillen und Lymphknoten", "Indurated tonsils and lymph nodes"),
    ("baryta-muriatica", "Baryta muriatica", "mineral", ["kent", "hering"], "Bariumchlorid", "Barium Chloride", "Arteriosklerose bei alten Menschen", "Arteriosclerosis in the aged"),
    ("benzinum", "Benzinum", "mineral", ["hering"], "Petrolether", "Benzene", "Geruchshalluzinationen und Ptosis", "Olfactory hallucinations and ptosis"),
    ("benzinum-dinitricum", "Benzinum dinitricum", "mineral", ["hering"], "Dinitrobenzol", "Dinitrobenzene", "Sehstörungen und Zyanose", "Amblyopia and cyanosis"),
    ("berberis-aquifolium", "Berberis aquifolium", "plant", ["hering"], "Mahonie", "Mountain Grape", "Chronische Akne und Schuppenflechte", "Chronic acne and scaly skin"),
    ("bismuthum-subnitricum", "Bismuthum subnitricum", "mineral", ["hahnemann", "kent", "hering"], "Wismutsubnitrat", "Bismuth Subnitrate", "Erbrechen von Wasser sobald es den Magen erreicht", "Vomiting of water as soon as it reaches stomach"),
    ("blatta-americana", "Blatta americana", "animal", ["hering"], "Amerikanische Kakerlake", "American Cockroach", "Gelbsucht und Aszites", "Jaundice and ascites"),
    ("blatta-orientalis", "Blatta orientalis", "animal", ["hering"], "Orientalische Kakerlake", "Indian Cockroach", "Akutes Asthma bronchiale mit Schleimrasseln", "Acute asthma with suffocative cough"),
    ("boldo", "Boldo", "plant", ["hering"], "Boldoblätter", "Boldo", "Leberträgheit und Cholezystitis", "Hepatic torpor and cholecystitis"),
    ("bothrops-lanceolatus", "Bothrops lanceolatus", "animal", ["hering"], "Lanzenotter", "Yellow Viper", "Aphasie, Thrombosen und Gangrän", "Aphasia, thrombosis, and gangrene"),
    ("bovista-lycoperdon", "Bovista lycoperdon", "plant", ["hahnemann", "kent", "hering"], "Warzen-Bovist", "Puffball", "Schwellungsgefühl und Ungeschicklichkeit", "Puffy swelling and drops things from hands"),
    ("brachyglottis-repens", "Brachyglottis repens", "plant", ["hering"], "Puka-Puka", "Puka-Puka", "Nierenirritation und Brightsche Krankheit", "Renal irritation and albuminuria"),
    ("bromium", "Bromium", "mineral", ["kent", "hering"], "Reines Brom", "Bromine", "Kehlkopfkrupp und Tonsillitis bei Blonden", "Croup and hard glands in fair complexions"),
    ("bufo-rana", "Bufo rana", "animal", ["kent", "hering"], "Erdkröte", "Toad Poison", "Krämpfe im Schlaf und geistige Retardierung", "Convulsions during sleep and low mentality"),
    # C
    ("cadmium-metallicum", "Cadmium metallicum", "mineral", ["hering"], "Metallisches Cadmium", "Cadmium Metal", "Gesichtslähmung und Magenreizung", "Facial paralysis and gastric burning"),
    ("cadmium-sulfuratum", "Cadmium sulfuratum", "mineral", ["kent", "hering"], "Cadmiumsulfid", "Cadmium Sulfate", "Kaffeesatzerbrechen und Kältegefühl", "Coffee-ground vomiting and severe chilliness"),
    ("cainca", "Cainca", "plant", ["hering"], "Kainkawurzel", "Cahinca", "Ödeme und Nierenschwäche", "Anasarca and renal insufficiency"),
    ("caladium-seguinum", "Caladium seguinum", "plant", ["kent", "hering"], "Schweigrohr", "American Arum", "Genitaler Pruritus und Tabakabneigung", "Genital pruritus and tobacco craving"),
    ("calcarea-arsenicosa", "Calcarea arsenicosa", "mineral", ["kent", "hering"], "Calciumarsenit", "Calcium Arsenite", "Herzklopfen bei Nephritis und Kachexie", "Palpitations in nephritis and cachexia"),
    ("calcarea-hypophosphorosa", "Calcarea hypophosphorosa", "mineral", ["hering"], "Calciumhypophosphit", "Calcium Hypophosphite", "Abszesse und chronische Kachexie", "Abscesses and wasting debility"),
    ("calcarea-iodata", "Calcarea iodata", "mineral", ["kent", "hering"], "Calciumiodid", "Calcium Iodide", "Chronisch vergrößerte Mandeln bei Kindern", "Enlarged scrofulous tonsils in children"),
    ("calcarea-silicata", "Calcarea silicata", "mineral", ["kent"], "Calciumsilikat", "Calcium Silicate", "Tiefe Frösteligkeit und Hornhautgeschwüre", "Deep chilliness and corneal ulcers"),
    ("calcarea-sulfurica", "Calcarea sulfurica", "mineral", ["kent", "hering"], "Calciumsulfat / Gips", "Calcium Sulfate", "Dickflüssige gelbe Eiterungen", "Thick lumpy yellow suppuration"),
    ("calotropis-gigantea", "Calotropis gigantea", "plant", ["hering"], "Mudar-Rinde", "Madar Bark", "Lupus, Lepra und Hautverdickungen", "Lupus and thickened skin affections"),
    ("cannabis-indica", "Cannabis indica", "plant", ["kent", "hering"], "Indischer Hanf", "Indian Hemp", "Zeitraffergefühl und unendliche Weite", "Exaggeration of time and space"),
    ("cannabis-sativa", "Cannabis sativa", "plant", ["hahnemann", "kent", "hering"], "Echter Hanf", "Hemp", "Brennende Schmerzen in der Urethra beim Urinieren", "Burning urethral pains while urinating"),
    ("capsicum-annuum", "Capsicum annuum", "plant", ["hahnemann", "kent", "hering"], "Spanischer Pfeffer", "Cayenne Pepper", "Mastoiditis und Heimweh mit rotem Gesicht", "Mastoiditis and homesickness with red cheeks"),
    ("carbo-animalis", "Carbo animalis", "animal", ["hahnemann", "kent", "hering"], "Tierkohle", "Animal Charcoal", "Härte von Drüsen und venöse Stauung", "Hard indurated glands and copper spots"),
    ("carbolicum-acidum", "Carbolicum acidum", "acid", ["kent", "hering"], "Karbolsäure", "Carbolic Acid", "Plötzliche Schwäche und septischer Kollaps", "Profound prostration and septic collapse"),
    ("carboneum-sulfuratum", "Carboneum sulfuratum", "mineral", ["kent", "hering"], "Schwefelkohlenstoff", "Carbon Bisulfide", "Periphere Neuropathie und Ischias", "Peripheral neuropathy and sciatica"),
    ("carduus-marianus", "Carduus marianus", "plant", ["kent", "hering"], "Mariendistel", "St. Mary's Thistle", "Leberstauung, Gelbsucht und Hämorrhoiden", "Liver congestion, jaundice, and varices"),
    ("castanea-vesca", "Castanea vesca", "plant", ["hering"], "Edelkastanie", "Chestnut", "Keuchhusten mit trockenem, bellendem Ton", "Early whooping cough with dry violent bark"),
    ("castor-equi", "Castor equi", "animal", ["hering"], "Kastanienwarze des Pferdes", "Horse Rudimentary Thumb", "Wunde rissige Brustwarzen und Warzen", "Cracked sore nipples and warts"),
    ("castoreum", "Castoreum", "animal", ["hering"], "Bibergeil", "Beaver Secretion", "Nervöse Erschöpfung nach schweren Krankheiten", "Nervous exhaustion after severe fevers"),
    ("caulophyllum-thalictroides", "Caulophyllum thalictroides", "plant", ["kent", "hering"], "Frauenwurzel", "Blue Cohosh", "Wehenschwäche und Fingergelenkrheuma", "Labor pains cease and small joint pains"),
    ("ceanothus-americanus", "Ceanothus americanus", "plant", ["kent", "hering"], "Säckelblume", "New Jersey Tea", "Milzvergrößerung und tiefer linker Flankenschmerz", "Splenomegaly and deep left hypochondriac pain"),
    ("cedron", "Cedron", "plant", ["kent", "hering"], "Cedronbohne", "Cedron Seed", "Uhrwerkartige Periodizität von Schmerzen und Fieber", "Clockwork periodicity of pain and chill"),
    ("cenchris-contortrix", "Cenchris contortrix", "animal", ["kent", "hering"], "Kupferkopfschlange", "Copperhead Snake", "Beklemmung an Brust und Hals, lebhafte Träume", "Tightness around neck and chest, vivid dreams"),
    ("centranthus-ruber", "Centranthus ruber", "plant", ["hering"], "Spornblume", "Red Valerian", "Nervöse Tachykardie und Schlafstörung", "Nervous tachycardia and restlessness"),
    ("chenopodium-anthelminticum", "Chenopodium anthelminticum", "plant", ["hering"], "Wurmsamen-Gänsefuß", "Wormseed", "Tinnitus, Schwindel und Torticollis", "Tinnitus, vertigo, and scapular pain"),
    ("chimaphila-umbellata", "Chimaphila umbellata", "plant", ["hering"], "Dolden-Winterlieb", "Pipsissewa", "Prostatahypertrophie und dicker Schleimurin", "Prostatic enlargement and ropy mucus urine"),
    ("chininum-arsenicosum", "Chininum arsenicosum", "mineral", ["kent", "hering"], "Chininarsenit", "Quinine Arsenite", "Schwäche nach Infekten und Asthma", "Post-infectious asthenia and asthma"),
    ("chininum-sulfuricum", "Chininum sulfuricum", "mineral", ["kent", "hering"], "Chininsulfat", "Quinine Sulfate", "Periodisches Wechselfieber und Tinnitus", "Periodic malaria fever and buzzing in ears"),
    ("chionanthus-virginica", "Chionanthus virginica", "plant", ["hering"], "Schneeflockenblume", "Fringe Tree", "Chronische Gelbsucht und Gallenstauung", "Chronic jaundice and biliary engorgement"),
    ("chlorum", "Chlorum", "mineral", ["hering"], "Chlorwasser", "Chlorine", "Stimmritzenkrampf und Lungenkrämpfe", "Laryngeal spasm and gas poisoning"),
    ("cinnabaris", "Cinnabaris", "mineral", ["hahnemann", "kent", "hering"], "Zinnober", "Red Mercuric Sulfide", "Kopfschmerz wie ein Band um die Stirn", "Pain like a heavy band around forehead"),
    ("cinnamomum-ceylanicum", "Cinnamomum ceylanicum", "plant", ["hering"], "Echter Zimt", "Cinnamon", "Hellrote Uterusblutungen bei Anstrengung", "Bright red uterine hemorrhage from exertion"),
    ("cistus-canadensis", "Cistus canadensis", "plant", ["kent", "hering"], "Kanadisches Sonnenröschen", "Rock Rose", "Kältegefühl in Rachen und Brust, Skrofulose", "Cold sensation in throat and chest"),
    ("clematis-erecta", "Clematis erecta", "plant", ["hahnemann", "kent", "hering"], "Aufrechte Waldrebe", "Virgin's Bower", "Urethrastriktur und geschwollene Hoden", "Urethral stricture and orchitis"),
    ("cobaltum-metallicum", "Cobaltum metallicum", "mineral", ["hering"], "Metallisches Kobalt", "Cobalt Metal", "Kreuzschmerzen beim Sitzen und Pollutionen", "Lumbar backache while sitting"),
    ("coca", "Coca", "plant", ["kent", "hering"], "Kokastrauch", "Coca Leaves", "Höhenkrankheit und Atemnot beim Bergsteigen", "Mountain sickness and breathlessness"),
    ("coccus-cacti", "Coccus cacti", "animal", ["kent", "hering"], "Cochenillelaus", "Cochineal", "Krampfhusten mit fadenziehendem Schleim", "Spasmodic cough with stringy clear mucus"),
    ("collinsonia-canadensis", "Collinsonia canadensis", "plant", ["kent", "hering"], "Grießwurz", "Stone Root", "Hämorrhoiden wie Sand im Rektum", "Hemorrhoids with gravel sensation in rectum"),
    ("comocladia-dentata", "Comocladia dentata", "plant", ["hering"], "Guao", "Guao", "Augenschmerzen wie aus dem Kopf gezerrt", "Eye pain as if drawn into head"),
    ("convallaria-majalis", "Convallaria majalis", "plant", ["hering"], "Maiglöckchen", "Lily of the Valley", "Herzklopfen und unregelmäßiger Puls", "Palpitations and trembling heart action"),
    ("copaiva-officinalis", "Copaiva officinalis", "plant", ["hering"], "Kopaivabalsam", "Balsam of Copaiva", "Brennen beim Urinieren und Urtikaria", "Burning micturition and roseola rash"),
    ("corallium-rubrum", "Corallium rubrum", "animal", ["hering"], "Rote Koralle", "Red Coral", "Heftiger bellender Maschinengewehrhusten", "Violent rapid-fire spasmodic cough"),
    ("cornus-circinata", "Cornus circinata", "plant", ["hering"], "Rundblättriger Hartriegel", "Round-Leaved Dogwood", "Aphthöse Stomatitis und chronische Diarrhö", "Aphthous stomatitis and chronic diarrhea"),
    ("cornus-florida", "Cornus florida", "plant", ["hering"], "Blumen-Hartriegel", "Flowering Dogwood", "Intermittierendes Fieber mit Schläfrigkeit", "Intermittent fever with drowsiness"),
    ("crocus-sativus", "Crocus sativus", "plant", ["hahnemann", "kent", "hering"], "Safran", "Saffron", "Fadenartige dunkle Blutungen und Hysterie", "Black ropy hemorrhages and hysteria"),
    ("crotalus-horridus", "Crotalus horridus", "animal", ["kent", "hering"], "Wald-Klapperschlange", "Timber Rattlesnake", "Zersetzung des Blutes und Sepsis", "Decomposition of blood and purpura"),
    ("croton-tiglium", "Croton tiglium", "plant", ["kent", "hering"], "Krotonölbaum", "Croton Oil Seed", "Schlagartiger wässriger Stuhl nach dem Trinken", "Sudden gushing watery stool after drinking"),
    ("cubeba-officinalis", "Cubeba officinalis", "plant", ["hering"], "Kubebenpfeffer", "Cubebs", "Schleimhautkatarrh der Blase und Urethra", "Bladder catarrh with burning discharge"),
    ("cuprum-aceticum", "Cuprum aceticum", "mineral", ["hahnemann", "hering"], "Kupferacetat", "Copper Acetate", "Krampfanfälle und stechende Zungenkrämpfe", "Convulsions and tongue spasms"),
    ("cuprum-arsenicosum", "Cuprum arsenicosum", "mineral", ["hering"], "Kupferarsenit", "Scheele's Green", "Magen-Darm-Krämpfe mit kaltem Schweiß", "Gastrointestinal cramps with cold sweat"),
    ("curare", "Curare", "plant", ["kent", "hering"], "Pfeilgift Curare", "Arrow Poison", "Lähmung der Atemmuskeln und Ptosis", "Paralysis of respiratory muscles and ptosis"),
    ("cyclamen-europaeum", "Cyclamen europaeum", "plant", ["hahnemann", "kent", "hering"], "Alpenveilchen", "Sowbread", "Flimmern vor den Augen und Schuldgefühle", "Flickering before eyes and grief/guilt"),
    # D
    ("damiana", "Damiana", "plant", ["hering"], "Damiana", "Damiana", "Sexuelle Schwäche und Neurasthenie", "Sexual debility and neurasthenia"),
    ("daphne-indica", "Daphne indica", "plant", ["hering"], "Indischer Seidelbast", "Indian Daphne", "Knochenschmerzen und stinkender Schweiß", "Bone pain and fetid breath"),
    ("dirca-palustris", "Dirca palustris", "plant", ["hering"], "Lederholz", "Leatherwood", "Dyspepsie mit neuralgischem Kopfschmerz", "Dyspepsia with neuralgic headache"),
    ("dolichos-pruriens", "Dolichos pruriens", "plant", ["hering"], "Juckbohne", "Cowhage", "Intensiver Juckreiz ohne Ausschlag bei Gelbsucht", "Intense itching without eruption in jaundice"),
    ("doryphora-decemlineata", "Doryphora decemlineata", "animal", ["kent", "hering"], "Kartoffelkäfer", "Colorado Potato Beetle", "Urethritis mit Blasenbrennen", "Urethritis with burning tenesmus"),
    # E
    ("elaps-corallinus", "Elaps corallinus", "animal", ["kent", "hering"], "Korallenschlange", "Coral Snake", "Schwarze Blutungen und Kältegefühl im Magen", "Black hemorrhages and cold feeling in stomach"),
    ("elaterium", "Elaterium", "plant", ["hering"], "Spritzgurke", "Squirting Cucumber", "Explosiver wässriger Durchfall", "Explosive watery diarrhea with frothing"),
    ("epilobium-palustre", "Epilobium palustre", "plant", ["hering"], "Sumpf-Weidenröschen", "Willow Herb", "Chronische Diarrhö und Prostatabeschwerden", "Chronic diarrhea and prostatic troubles"),
    ("epiphegus-virginiana", "Epiphegus virginiana", "plant", ["hering"], "Buchenkrebswurz", "Beechdrops", "Kopfschmerz nach geistiger Erschöpfung", "Nervous headache from mental fatigue"),
    ("equisetum-hyemale", "Equisetum hyemale", "plant", ["hering"], "Winterschachtelhalm", "Horsetail", "Blasenreizung mit Völlegefühl und Enuresis", "Bladder irritation with fullness and enuresis"),
    ("erigeron-canadense", "Erigeron canadense", "plant", ["hering"], "Kanadisches Berufkraut", "Fleabane", "Helle schwallartige Blutungen", "Bright gushing hemorrhages on movement"),
    ("eriodictyon-californicum", "Eriodictyon californicum", "plant", ["hering"], "Yerba Santa", "Yerba Santa", "Bronchitis mit zähem Schleim und Asthma", "Bronchial catarrh and asthmatic wheezing"),
    ("eryngium-aquaticum", "Eryngium aquaticum", "plant", ["hering"], "Wasser-Mannstreu", "Button Snakeroot", "Brennender Harndrang und Urethritis", "Burning tenesmus and urethritis"),
    ("eucalyptus-globulus", "Eucalyptus globulus", "plant", ["hering"], "Blauer Eukalyptus", "Blue Gum Tree", "Katarrhe mit septischem Fieber", "Catarrhal affections with septic fever"),
    ("eugenia-jambos", "Eugenia jambos", "plant", ["hering"], "Rosenapfel", "Rose Apple", "Akne und Schluckauf", "Acne simplex and obstinate hiccups"),
    ("euonymus-atropurpureus", "Euonymus atropurpureus", "plant", ["hering"], "Spindelstrauch", "Wahoo", "Leberstauung mit Kopfschmerz", "Hepatic congestion with albuminuria"),
    ("eupatorium-purpureum", "Eupatorium purpureum", "plant", ["kent", "hering"], "Purpur-Wasserdost", "Gravel Root", "Nierensteine und intermittierendes Fieber", "Renal gravel and urinary irritation"),
    ("euphorbia-corollata", "Euphorbia corollata", "plant", ["hering"], "Blüten-Wolfsmilch", "Large Flowering Spurge", "Choleraartige Brechdurchfälle", "Choleraic vomiting and purging"),
    ("euphorbium-officinarum", "Euphorbium officinarum", "plant", ["hahnemann", "hering"], "Wolfsmilchharz", "Spurge Resin", "Brennende Schmerzen in Knochen und Magen", "Burning pains in bones and stomach"),
    ("eupion", "Eupion", "mineral", ["hering"], "Holzteer-Destillat", "Wood Tar Distillate", "Kreuzschmerz und Uterussymptome", "Sacral backache and uterine disorders"),
    # F
    ("ferrum-aceticum", "Ferrum aceticum", "mineral", ["hahnemann", "hering"], "Eisenacetat", "Iron Acetate", "Blutarmut und blasse Schleimhäute", "Anemia and pale mucous membranes"),
    ("ferrum-arsenicosum", "Ferrum arsenicosum", "mineral", ["kent"], "Eisenarsenit", "Iron Arsenite", "Milztumor bei schwerer Anämie", "Enlarged spleen with profound anemia"),
    ("ferrum-iodatum", "Ferrum iodatum", "mineral", ["kent", "hering"], "Eiseniodid", "Iron Iodide", "Drüsenschwellungen und Uterussenkung", "Scrofulous glands and uterine prolapse"),
    ("ferrum-magneticum", "Ferrum magneticum", "mineral", ["hahnemann", "hering"], "Magnetit", "Loadstone", "Lendenlahmheit und Bauchblähungen", "Paralytic lumbar weakness and flatus"),
    ("ferrum-muriaticum", "Ferrum muriaticum", "mineral", ["hering"], "Eisenchlorid", "Iron Chloride", "Schulterschmerz und Blutarmut", "Shoulder joint pain and anemia"),
    ("ferrum-picricum", "Ferrum picricum", "mineral", ["hering"], "Eisenpikrat", "Iron Picrate", "Warzen an Händen und Prostatahypertrophie", "Warts on hands and prostatic hypertrophy"),
    ("ferrum-sulfuricum", "Ferrum sulfuricum", "mineral", ["hering"], "Eisenvitriol", "Iron Sulfate", "Morbus Basedow und Koliken", "Graves disease and watery diarrhea"),
    ("formica-rufa", "Formica rufa", "animal", ["hering"], "Rote Waldameise", "Red Ant", "Rheumatische Gelenksteifigkeit und Nierenstau", "Rheumatic stiffness and renal gravel"),
    ("fragaria-vesca", "Fragaria vesca", "plant", ["hering"], "Walderdbeere", "Wild Strawberry", "Urtikaria nach Erdbeergenuss", "Urticaria and anaphylactoid edema"),
    ("fraxinus-americana", "Fraxinus americana", "plant", ["hering"], "Weißesche", "White Ash", "Uterusvergrößerung und Myome", "Uterine hypertrophy and prolapse"),
    # G
    ("gambogia", "Gambogia", "plant", ["hering"], "Gummigutt", "Gamboge", "Explosiver Durchfall mit Schwallentleerung", "Sudden explosive stool with relief"),
    ("gentiana-lutea", "Gentiana lutea", "plant", ["hering"], "Gelber Enzian", "Yellow Gentian", "Magenatonie und Völlegefühl", "Gastric atony and flatulence"),
    ("geranium-maculatum", "Geranium maculatum", "plant", ["hering"], "Gefleckter Storchschnabel", "Cranesbill", "Profuse Hämorrhagien und Magengeschwüre", "Profuse hemorrhages and gastric ulcer"),
    ("geum-rivale", "Geum rivale", "plant", ["hering"], "Bach-Nelkenwurz", "Water Avens", "Blasenschleim und Zystitis", "Mucous cystitis and tearing pains"),
    ("gnaphalium-polycephalum", "Gnaphalium polycephalum", "plant", ["hering"], "Ruhrkraut", "Cudweed", "Ischias mit Taubheitsgefühl im Bein", "Sciatica with alternating numbness"),
    ("gossypium-herbaceum", "Gossypium herbaceum", "plant", ["hering"], "Baumwollstaude", "Cotton Plant", "Uterusatonie und morgendliche Übelkeit", "Uterine inertia and morning sickness"),
    ("granatum", "Granatum", "plant", ["hering"], "Granatapfelbaum", "Pomegranate", "Bandwurmkoliken und Speichelfluss", "Tapeworm colic and salivation"),
    ("gratiola-officinalis", "Gratiola officinalis", "plant", ["kent", "hering"], "Gottesgnadenkraut", "Hedge Hyssop", "Sommerdiarrhö mit gelbem Schwallstuhl", "Summer diarrhea with gushing stool"),
    ("grindelia-robusta", "Grindelia robusta", "plant", ["hering"], "Grindelienkraut", "Gum Plant", "Atemstillstand beim Einschlafen", "Stops breathing when falling asleep"),
    ("guaco", "Guaco", "plant", ["hering"], "Mikania", "Guaco", "Paralyse und spinale Schmerzen", "Paralysis and spinal tenderness"),
    ("guaiacum-officinale", "Guaiacum officinale", "plant", ["hahnemann", "kent", "hering"], "Guajakharz", "Guaiacum Resin", "Gelenksteifigkeit und Tonsillitis", "Arthritic stiffness and acute tonsillitis"),
    ("guarea-trichilioides", "Guarea trichilioides", "plant", ["hering"], "Kugelfruchtbaum", "Ballwood", "Konjunktivitis und Chemosis", "Conjunctivitis and orbital pain"),
    ("gymnocladus-canadensis", "Gymnocladus canadensis", "plant", ["hering"], "Amerikanischer Geweihbaum", "Kentucky Coffee Tree", "Pharyngitis und Schläfrigkeit", "Pharyngitis and erysipelatous swelling")
]

print(f"Roster part 1 has {len(ROSTER)} entries.")
