# scripts/full_remedy_roster_part2.py
# Roster Part 2: H through P

ROSTER_PART2 = [
    # H
    ("haematoxylon-campechianum", "Haematoxylon campechianum", "plant", ["hering"], "Blauholz", "Logwood", "Engegefühl in der Herzgrube und Koliken", "Constriction of precordium and angina"),
    ("hedeoma-pulegioides", "Hedeoma pulegioides", "plant", ["hering"], "Amerikanische Poleiminze", "Pennyroyal", "Dysmenorrhoe und Gastritis", "Dysmenorrhea and bearing down"),
    ("hekla-lava", "Hekla lava", "mineral", ["hering"], "Hekla-Lava", "Lava from Mt. Hekla", "Knochenexostosen und Kiefertumore", "Exostosis of jaw and bone necrosis"),
    ("helianthus-annuus", "Helianthus annuus", "plant", ["hering"], "Sonnenblume", "Sunflower", "Intermittierendes Fieber und Milzschmerz", "Intermittent fever and spleen enlargement"),
    ("helonias-dioica", "Helonias dioica", "plant", ["kent", "hering"], "Falsches Einhorn", "Unicorn Root", "Uteruserschöpfung und Bewusstsein der Gebärmutter", "Conscious of uterus, renal fatigue"),
    ("hydrangea-arborescens", "Hydrangea arborescens", "plant", ["hering"], "Wald-Hortensie", "Seven-Barks", "Nierengrieß und Blasensteine", "Renal gravel and backache"),
    ("hydrocotyle-asiatica", "Hydrocotyle asiatica", "plant", ["hering"], "Asiatischer Wassernabel", "Indian Pennywort", "Hautverdickungen, Psoriasis und Pemphigus", "Psoriasis, thickened skin, and pemphigus"),
    ("hydrocyanicum-acidum", "Hydrocyanicum acidum", "acid", ["hering"], "Blausäure", "Hydrocyanic Acid", "Plötzlicher Kollaps und Zyanose", "Sudden collapse, convulsions, and cyanosis"),
    # I
    ("iberis-amara", "Iberis amara", "plant", ["hering"], "Bittere Schleifenblume", "Bitter Candytuft", "Herzhypertrophie mit Tachykardie", "Cardiac hypertrophy and arrhythmia"),
    ("illicium-anisatum", "Illicium anisatum", "plant", ["hahnemann", "hering"], "Sternanis", "Star Anise", "Dritte Rippe rechts schmerzt", "Third right rib tenderness"),
    ("indigo-tinctoria", "Indigo tinctoria", "plant", ["hering"], "Echter Indigo", "Indigo", "Epilepsie mit Aura und Melancholie", "Epileptiform spasms and gloominess"),
    ("indium-metallicum", "Indium metallicum", "mineral", ["hering"], "Metallisches Indium", "Indium Metal", "Kopfschmerz und sexuelle Erschöpfung", "Throbbing frontal headache and debility"),
    ("inula-helenium", "Inula helenium", "plant", ["hering"], "Echter Alant", "Elecampane", "Bronchialkatarrh mit Kitzelhusten", "Bronchial catarrh with dry tickling"),
    ("iridium-metallicum", "Iridium metallicum", "mineral", ["hering"], "Metallisches Iridium", "Iridium Metal", "Schwäche der Wirbelsäule und Gicht", "Spinal exhaustion and gout"),
    # J
    ("jaborandi", "Jaborandi", "plant", ["hering"], "Jaborandiblätter", "Pilocarpus", "Profuse Schweiße und Speichelfluss", "Profuse sweating, salivation, and blurred vision"),
    ("jacaranda-caroba", "Jacaranda caroba", "plant", ["hering"], "Carobabaum", "Jacaranda", "Gonorrhoe und Schleimhautulzera", "Venereal ulcers and urethral inflammation"),
    ("jalapa", "Jalapa", "plant", ["hering"], "Jalapenwurzel", "Jalap", "Kinder schreien nachts und Kolikdurchfall", "Infant night crying with watery colic"),
    ("jatropha-curcas", "Jatropha curcas", "plant", ["hering"], "Purgiernuss", "Purging Nut", "Plötzlicher wässriger Brechdurchfall", "Profuse watery choleraic diarrhea"),
    ("juglans-cinerea", "Juglans cinerea", "plant", ["hering"], "Butternuss", "Butternut", "Leberstauung, Nackenstarre und Ekzem", "Hepatic congestion and occipital pain"),
    ("juglans-regia", "Juglans regia", "plant", ["hering"], "Walnuss", "Walnut", "Lymphadenitis und schuppige Hautausschläge", "Lymphadenitis and crusty eczema"),
    # K
    ("kalium-arsenicosum", "Kalium arsenicosum", "mineral", ["kent"], "Kaliumarsenit", "Potassium Arsenite", "Hartnäckige chronische Hautleiden", "Intractable skin scales and ulcers"),
    ("kalium-bromatum", "Kalium bromatum", "mineral", ["kent"], "Kaliumbromid", "Potassium Bromide", "Nervöse Handunruhe und Gedächtnislücken", "Fidgety hands and memory loss"),
    ("kalium-chloricum", "Kalium chloricum", "mineral", ["kent"], "Kaliumchlorat", "Potassium Chlorate", "Stomatitis ulcerosa und Nephritis", "Ulcerative stomatitis and nephritis"),
    ("kalium-cyanatum", "Kalium cyanatum", "mineral", ["hering"], "Kaliumzyanid", "Potassium Cyanide", "Schwere Gesichtsneuralgie", "Intense ciliary and facial neuralgia"),
    ("kalium-ferrocyanatum", "Kalium ferrocyanatum", "mineral", ["hering"], "Kaliumhexacyanoferrat", "Potassium Ferrocyanide", "Schwaches Herz mit Blässe", "Fatty heart with chlorosis"),
    ("kalium-hypophosphorosum", "Kalium hypophosphorosum", "mineral", ["hering"], "Kaliumhypophosphit", "Potassium Hypophosphite", "Nervöse Abmagerung und Husten", "Nervous emaciation and cough"),
    ("kalium-iodatum", "Kalium iodatum", "mineral", ["kent", "hering"], "Kaliumiodid", "Potassium Iodide", "Wässriger scharfer Schnupfen und Knochenschmerzen", "Profuse acrid coryza and periostitis"),
    ("kalium-muriaticum", "Kalium muriaticum", "mineral", ["kent", "hering"], "Kaliumchlorid", "Potassium Chloride", "Weiß belegte Zunge und Paukenhöhlenkatarrh", "White tongue coating and eustachian catarrh"),
    ("kalium-nitricum", "Kalium nitricum", "mineral", ["hahnemann", "kent", "hering"], "Kalisalpeter", "Saltpeter", "Asthma und stechende Lungenschmerzen", "Asthma with chest stitches"),
    ("kalium-oxalicum", "Kalium oxalicum", "mineral", ["hering"], "Kaliumoxalat", "Potassium Oxalate", "Magenkrämpfe und Lumbalgie", "Gastric cramps and lumbar pain"),
    ("kalium-permanganicum", "Kalium permanganicum", "mineral", ["hering"], "Kaliumpermanganat", "Potassium Permanganate", "Diphtherie und fötider Mundgeruch", "Diphtheritic throat and fetor"),
    ("kalium-silicatum", "Kalium silicatum", "mineral", ["kent"], "Kaliumsilikat", "Potassium Silicate", "Kälteempfindlichkeit und chronische Schwäche", "Extreme chilliness and exhaustion"),
    ("kalium-sulfuricum", "Kalium sulfuricum", "mineral", ["kent", "hering"], "Kaliumsulfat", "Potassium Sulfate", "Gelbe schleimige Absonderungen", "Yellow slimy secretions and skin peeling"),
    ("kalmia-latifolia", "Kalmia latifolia", "plant", ["kent", "hering"], "Berglorbeer", "Mountain Laurel", "Wandernde Neuralgien von oben nach unten", "Neuralgia shooting downwards"),
    ("kreosotum", "Kreosotum", "mineral", ["hahnemann", "kent", "hering"], "Buchenholzkreosot", "Beechwood Creosote", "Schnelle Karies und brennende Ausscheidungen", "Rapid tooth decay and excoriating discharges"),
    # L
    ("lac-caninum", "Lac caninum", "animal", ["kent"], "Hundemilch", "Dog's Milk", "Schmerzen wechseln die Seite und Mastodynie", "Pains alternate sides, sore breasts"),
    ("lac-defloratum", "Lac defloratum", "animal", ["kent"], "Entrahmte Kuhmilch", "Skimmed Cow's Milk", "Migräne mit starker Obstipation", "Sick headache with great constipation"),
    ("lachnanthes-tinctoria", "Lachnanthes tinctoria", "plant", ["kent", "hering"], "Wollblume", "Spiritweed", "Schiefhals und Hitze zwischen den Schultern", "Torticollis and burning in spine"),
    ("lactuca-virosa", "Lactuca virosa", "plant", ["hering"], "Giftlattich", "Wild Lettuce", "Erstickender Reizhusten und Schläfrigkeit", "Suffocating dry tickling cough"),
    ("lapis-albus", "Lapis albus", "mineral", ["hering"], "Gasteiner Gneis", "White Stone of Gastein", "Elastische Drüsentumore und Struma", "Elastic tumors of glands and goiter"),
    ("lappa-arctium", "Lappa arctium", "plant", ["hering"], "Große Klette", "Burdock", "Krustige Kopfhautekzeme und Uterusprolaps", "Crusted head eczema and uterine prolapse"),
    ("latrodectus-mactans", "Latrodectus mactans", "animal", ["hering"], "Schwarze Witwe", "Black Widow Spider", "Angina pectoris mit Ausstrahlung in linken Arm", "Violent precordial pain radiating down left arm"),
    ("laurocerasus", "Laurocerasus", "plant", ["kent", "hering"], "Kirschlorbeer", "Cherry Laurel", "Zyanose und Herzschwäche ohne Angst", "Cyanosis and cardiac collapse without dyspnea"),
    ("leptandra-virginica", "Leptandra virginica", "plant", ["kent", "hering"], "Virginischer Ehrenpreis", "Culver's Root", "Schwarze Teerstühle und Leberstau", "Jet black tarlike stools and jaundice"),
    ("lilium-tigrinum", "Lilium tigrinum", "plant", ["kent", "hering"], "Tigerlilie", "Tiger Lily", "Uterusdrang nach unten und Herzklopfen", "Bearing down with heart palpitations"),
    ("linum-usitatissimum", "Linum usitatissimum", "plant", ["hering"], "Leinsamen", "Flaxseed", "Heuschnupfen und Zungenbrennen", "Asthmatic hay fever and urticaria"),
    ("lithium-carbonicum", "Lithium carbonicum", "mineral", ["kent", "hering"], "Lithiumcarbonat", "Lithium Carbonate", "Gicht der kleinen Gelenke und Herzschmerz", "Small joint gout and cardiac ache"),
    ("lobelia-cardinalis", "Lobelia cardinalis", "plant", ["hering"], "Kardinals-Lobelie", "Cardinal Flower", "Schlafsucht und Zungenschwäche", "Drowsiness and thirst for cold water"),
    ("lobelia-inflata", "Lobelia inflata", "plant", ["kent", "hering"], "Indianertabak", "Indian Tobacco", "Übelkeit mit kaltem Schweiß und Schwäche", "Nausea with cold perspiration"),
    ("lycopus-virginicus", "Lycopus virginicus", "plant", ["kent", "hering"], "Virginischer Wolfstrapp", "Bugleweed", "Basedow-Krankheit mit Herzklopfen", "Exophthalmic goiter with bounding heart"),
    ("lyssinum", "Lyssinum", "nosode", ["kent", "hering"], "Tollwut-Nosode", "Hydrophobinum", "Krämpfe beim Anblick von fließendem Wasser", "Spasms on running water sight"),
    # M
    ("magnesia-carbonica", "Magnesia carbonica", "mineral", ["hahnemann", "kent", "hering"], "Magnesiumcarbonat", "Magnesium Carbonate", "Grüne schaumige Durchfälle und Neuralgien", "Green frothy stools and nerve pains"),
    ("magnesia-muriatica", "Magnesia muriatica", "mineral", ["hahnemann", "kent", "hering"], "Magnesiumchlorid", "Magnesium Chloride", "Schafkotartiger harter Stuhl", "Knotty sheep-dung stools"),
    ("magnesia-sulfurica", "Magnesia sulfurica", "mineral", ["kent", "hering"], "Bittersalz", "Epsom Salt", "Wässriger Morgendurchfall und Kreuzschmerz", "Early morning watery diarrhea"),
    ("magnolia-grandiflora", "Magnolia grandiflora", "plant", ["hering"], "Immergrüne Magnolie", "Magnolia", "Präkordiale Enge und rheumatische Schmerzen", "Precordial suffocation and stiffness"),
    ("mancinella", "Mancinella", "plant", ["kent", "hering"], "Manchinelbaum", "Hippomane Mancinella", "Bläschenausschlag mit Brennen", "Erythema with intense burning blisters"),
    ("mandragora-officinarum", "Mandragora officinarum", "plant", ["hering"], "Alraune", "Mandrake", "Magenkrämpfe und pupilläre Lähmung", "Gastric cramps and mydriasis"),
    ("manganum-aceticum", "Manganum aceticum", "mineral", ["hahnemann", "hering"], "Manganacetat", "Manganese Acetate", "Knochenschmerzen und Husten im Liegen besser", "Bone tenderness, cough relieved lying down"),
    ("manganum-metallicum", "Manganum metallicum", "mineral", ["kent", "hering"], "Metallisches Mangan", "Manganese Metal", "Anämie und Parkinsonismus mit Gehstörung", "Anemia and Parkinsonian gait"),
    ("marum-verum", "Teucrium marum verum", "plant", ["hahnemann", "kent", "hering"], "Katzengamander", "Cat Thyme", "Nasenpolypen und Aftermadenwürmer", "Nasal polypi and pinworms"),
    ("medorrhinum", "Medorrhinum", "nosode", ["kent"], "Sykotische Nosode", "Medorrhinum", "Unruhe der Beine, Besserung am Meer", "Restless legs, relieved at seashore"),
    ("melilotus-alba", "Melilotus alba", "plant", ["kent", "hering"], "Weißer Steinklee", "Sweet Clover", "Pulsierender Stauungskopfschmerz mit Nasenbluten", "Congestive headache relieved by epistaxis"),
    ("menyanthes-trifoliata", "Menyanthes trifoliata", "plant", ["hahnemann", "kent", "hering"], "Fieberklee", "Buckbean", "Eiskalte Extremitäten und Druck auf den Scheitel", "Icy cold extremities, vertex pressure"),
    ("mephitis-mephitica", "Mephitis mephitica", "animal", ["kent", "hering"], "Stinktier-Sekret", "Skunk Secretion", "Keuchhusten mit Erstickungsanfällen", "Whooping cough with suffocative paroxysms"),
    ("mercurialis-perennis", "Mercurialis perennis", "plant", ["hering"], "Wald-Bingelkraut", "Dog's Mercury", "Trockene brennende Augen und Schläfrigkeit", "Dry burning eyes and heavy eyelids"),
    ("mercurius-auratus", "Mercurius auratus", "mineral", ["hering"], "Quecksilber-Gold-Amalgam", "Mercuric Gold", "Knochenschmerzen und Psoriasis", "Syphilitic bone pains and skin scales"),
    ("mercurius-biniodatus", "Mercurius biniodatus", "mineral", ["hering"], "Quecksilberdiiodid", "Red Mercuric Iodide", "Tonsillitis links mehr als rechts", "Tonsillitis, left worse than right"),
    ("mercurius-corrosivus", "Mercurius corrosivus", "mineral", ["kent", "hering"], "Sublimat", "Corrosive Sublimate", "Schwere blutige Ruhr mit Tenesmus", "Bloody dysentery with tenesmus"),
    ("mercurius-cyanatus", "Mercurius cyanatus", "mineral", ["hering"], "Quecksilberzyanid", "Mercuric Cyanide", "Diphtherische Membranen und Kollaps", "Malignant diphtheria and collapse"),
    ("mercurius-dulcis", "Mercurius dulcis", "mineral", ["hering"], "Kalomel", "Calomel", "Tubenkatharrh und Schwerhörigkeit", "Eustachian catarrh and deafness"),
    ("mercurius-iodatus-flavus", "Mercurius iodatus flavus", "mineral", ["kent", "hering"], "Quecksilberprotoiodid", "Yellow Mercurous Iodide", "Halsschmerz rechtsseitig mit gelber Zunge", "Right-sided throat pain, yellow tongue base"),
    ("mercurius-iodatus-ruber", "Mercurius iodatus ruber", "mineral", ["kent", "hering"], "Rotes Quecksilberiodid", "Red Mercuric Iodide", "Linksseitige Angina und Drüsenschwellung", "Left-sided angina and swollen tonsils"),
    ("mercurius-sulfuricus", "Mercurius sulfuricus", "mineral", ["hering"], "Turpethum minerale", "Yellow Mercuric Sulfate", "Hydrothorax und Atemnot", "Hydrothorax and dyspnea on walking"),
    ("mercurius-vivus", "Mercurius vivus", "mineral", ["hahnemann", "hering"], "Lebendiges Quecksilber", "Quicksilver", "Zittern, Schweiß ohne Besserung, Nachtverschlimmerung", "Tremor, night sweats without relief"),
    ("mitchella-repens", "Mitchella repens", "plant", ["hering"], "Rebhuhnbeere", "Partridgeberry", "Dysurie nach Entbindung und Uterusreizung", "Postpartum dysuria and cervix irritation"),
    ("moschus", "Moschus", "animal", ["hahnemann", "kent", "hering"], "Moschus", "Musk", "Hysterische Ohnmachten und Globus", "Hysterical faintings, spasms, and globus"),
    ("murex-purpurea", "Murex purpurea", "animal", ["kent", "hering"], "Purpurschnecke", "Purple Fish", "Starkes Herabdrängen im Uterus und sexuelle Erregung", "Uterine bearing down with sexual excitement"),
    ("muriaticum-acidum", "Muriaticum acidum", "acid", ["hahnemann", "kent", "hering"], "Salzsäure", "Muriatic Acid", "Große Schwäche, rutscht im Bett nach unten", "Profound debility, slides down in bed"),
    ("mygale-lasiodora", "Mygale lasiodora", "animal", ["hering"], "Schwarze Vogelspinne", "Black Cuban Spider", "Chorea mit unwillkürlichen Muskelzuckungen", "Chorea with facial twitching and grimaces"),
    ("myrica-cerifera", "Myrica cerifera", "plant", ["hering"], "Wachsmyrte", "Bayberry", "Leberstauung mit bronzeartiger Hautfarbe", "Hepatic torpor with bronze yellow skin"),
    ("myristica-sebifera", "Myristica sebifera", "plant", ["hering"], "Talg-Muskatnuss", "Virola Sebifera", "Homöopathisches Messer zur Abszessreifung", "Homeopathic knife for hastening suppuration"),
    ("myrtus-communis", "Myrtus communis", "plant", ["hering"], "Echte Myrte", "Myrtle", "Stechender Schmerz durch linke Lungenspitze", "Stitching pain through left apex to back"),
    # N
    ("naja-tripudians", "Naja tripudians", "animal", ["kent", "hering"], "Brillenschlange", "Cobra Poison", "Herzklappenfehler und Engegefühl im Hals", "Valvular heart disease and suffocative choking"),
    ("naphthalinum", "Naphthalinum", "mineral", ["hering"], "Naphthalin", "Naphthalene", "Heuschnupfen und Bronchitis bei Emphysem", "Coryza, hay fever, and cataracts"),
    ("narcissus-pseudonarcissus", "Narcissus pseudonarcissus", "plant", ["hering"], "Osterglocke", "Daffodil", "Krampfhusten und Larynxreizung", "Spasmodic cough and skin erythema"),
    ("nasturtium-aquaticum", "Nasturtium aquaticum", "plant", ["hering"], "Brunnenkresse", "Watercress", "Blasengrieß und Magenbeschwerden", "Urinary gravel and gastric flatulence"),
    ("natrum-arsenicosum", "Natrum arsenicosum", "mineral", ["kent"], "Natriumarsenit", "Sodium Arsenite", "Chronische Sinusitis mit Krusten", "Chronic sinusitis with crusty catarrh"),
    ("natrum-bicarbonicum", "Natrum bicarbonicum", "mineral", ["hering"], "Natriumhydrogencarbonat", "Baking Soda", "Sodbrennen und Dyspepsie", "Acid dyspepsia and heartburn"),
    ("natrum-carbonicum", "Natrum carbonicum", "mineral", ["hahnemann", "kent", "hering"], "Reine Soda", "Sodium Carbonate", "Kopfschmerz durch Sonne und Milchunverträglichkeit", "Headache from sun, aversion to milk"),
    ("natrum-hypochlorosum", "Natrum hypochlorosum", "mineral", ["hering"], "Natriumhypochlorit", "Sodium Hypochlorite", "Uterusatonie und schlaffe Beckenmuskeln", "Flaccid uterine prolapse and debility"),
    ("natrum-iodatum", "Natrum iodatum", "mineral", ["hering"], "Natriumiodid", "Sodium Iodide", "Chronische Bronchitis und Arteriosklerose", "Chronic bronchitis and hypertension"),
    ("natrum-nitricum", "Natrum nitricum", "mineral", ["hering"], "Natriumnitrat", "Sodium Nitrate", "Hämorrhagien und Hämoptyse", "Hemoptysis and purpura"),
    ("natrum-phosphoricum", "Natrum phosphoricum", "mineral", ["kent", "hering"], "Natriumphosphat", "Sodium Phosphate", "Saurer Magen mit gelbem Zungenbelag", "Sour stomach with golden yellow tongue coating"),
    ("natrum-salicylicum", "Natrum salicylicum", "mineral", ["hering"], "Natriumsalicylat", "Sodium Salicylate", "Tinnitus und Menière-Schwindel", "Tinnitus aurium and Meniere's disease"),
    ("natrum-silicofluoricum", "Natrum silicofluoricum", "mineral", ["hering"], "Salufer", "Sodium Silicofluoride", "Knochenkaries und Zahnschmelzschäden", "Bone caries and lupus"),
    ("niccolum-metallicum", "Niccolum metallicum", "mineral", ["hering"], "Metallisches Nickel", "Nickel Metal", "Periodischer Kopfschmerz und Husten", "Periodic headache and hacking cough"),
    ("niccolum-sulfuricum", "Niccolum sulfuricum", "mineral", ["hering"], "Nickelsulfat", "Nickel Sulfate", "Klimakterische Wallungen und Neurasthenie", "Climacteric flushings and spine ache"),
    ("nuphar-luteum", "Nuphar luteum", "plant", ["hering"], "Gelbe Teichrose", "Yellow Pond Lily", "Morgendlicher schmerzloser Durchfall", "Morning painless diarrhea and impotence"),
    ("nux-moschata", "Nux moschata", "plant", ["hahnemann", "kent", "hering"], "Muskatnuss", "Nutmeg", "Überwältigende Schläfrigkeit und Mundtrockenheit", "Overpowering sleepiness and dry mouth"),
    # O
    ("ocimum-canum", "Ocimum canum", "plant", ["hering"], "Brasilisches Basilikum", "Alfavaca", "Nierensteinkolik mit rotem Sand im Urin", "Renal colic with brick-dust urine"),
    ("oenanthe-crocata", "Oenanthe crocata", "plant", ["hering"], "Safranrebendolde", "Water Dropwort", "Epileptische Anfälle mit Bewusstlosigkeit", "Epileptic convulsions with foaming"),
    ("oleander", "Oleander", "plant", ["hahnemann", "kent", "hering"], "Rosenlorbeer", "Nerium Oleander", "Kopfschuppen mit Juckreiz und unwillkürlicher Stuhl", "Scalp scabs with involuntary stool on flatus"),
    ("oleum-animale", "Oleum animale", "animal", ["hering"], "Dippels Tieröl", "Animal Oil", "Nervöses Magenbrennen und Hodenschmerz", "Nervous gastralgia and testicular pulling"),
    ("oleum-jecoris-aselli", "Oleum jecoris aselli", "animal", ["hering"], "Dorschlebertran", "Cod Liver Oil", "Kachexie bei Kindern und Gelenksteife", "Rickets, emaciation, and soreness"),
    ("onosmodium-virginianum", "Onosmodium virginianum", "plant", ["hering"], "Falscher Steinsame", "False Gromwell", "Augenmuskelschwäche und Migräne", "Ocular strain headache and vertigo"),
    ("origanum-majorana", "Origanum majorana", "plant", ["hering"], "Echter Majoran", "Sweet Marjoram", "Hysterische Unruhe und Nymphomanie", "Erotomania and breast soreness"),
    ("osmium-metallicum", "Osmium metallicum", "mineral", ["hering"], "Metallisches Osmium", "Osmium Metal", "Heiserkeit mit grünem Schleim und Augenbrennen", "Hoarseness with greenish mucus"),
    ("ostrya-virginica", "Ostrya virginica", "plant", ["hering"], "Virginische Hopfenbuche", "Ironwood", "Dyspepsie mit Gallenstauung", "Malarial chills and bilious state"),
    ("ova-gallina-pellicula", "Ova gallina pellicula", "animal", ["hering"], "Eierschalenmembran", "Egg Shell Membrane", "Rückenschmerzen und Fluor albus", "Bearing down in back and leucorrhea"),
    ("oxalicum-acidum", "Oxalicum acidum", "acid", ["kent", "hering"], "Oxalsäure", "Oxalic Acid", "Schmerzen schlimmer beim Daran-Denken", "Pains worse thinking of them"),
    ("oxytropis-lamberti", "Oxytropis lamberti", "plant", ["hering"], "Locokraut", "Loco Weed", "Ataxie und unsicherer Gang", "Spinal locomotor ataxia and paralysis")
]

print(f"Roster Part 2 has {len(ROSTER_PART2)} entries.")
