# scripts/full_remedy_roster_part3.py
# Roster Part 3: P through Z

ROSTER_PART3 = [
    # P
    ("paeonia-officinalis", "Paeonia officinalis", "plant", ["hering"], "Pfingstrose", "Peony", "Bissige Afterfissuren und Hämorrhoiden", "Biting anal fissures and weeping piles"),
    ("palladium-metallicum", "Palladium metallicum", "mineral", ["kent", "hering"], "Metallisches Palladium", "Palladium Metal", "Gekränkter Stolz und rechtsseitige Ovarialgien", "Wounded pride, right-sided ovarian pain"),
    ("pareira-brava", "Pareira brava", "plant", ["hering"], "Grießwurz", "Virgin Vine", "Heftiger Harndrang, kann nur auf Knien urinieren", "Can only urinate on hands and knees"),
    ("paris-quadrifolia", "Paris quadrifolia", "plant", ["hering"], "Einbeere", "True Love", "Augenschmerz wie mit Faden nach hinten gezogen", "Eyeballs pulled backwards with threads"),
    ("passiflora-incarnata", "Passiflora incarnata", "plant", ["hering"], "Passionsblume", "Passion Flower", "Schlaflosigkeit bei Überarbeitung und Säuglingen", "Restless insomnia from mental strain"),
    ("petroselinum-sativum", "Petroselinum sativum", "plant", ["kent", "hering"], "Petersilie", "Parsley", "Plötzlicher unbezwingbarer Harndrang mit Kitzeln", "Sudden irresistible desire to urinate"),
    ("phellandrium-aquaticum", "Phellandrium aquaticum", "plant", ["hering"], "Wasserfenchel", "Water Dropwort", "Stichschmerz in der rechten Brustwarze und Husten", "Stitching pain in right breast and cough"),
    ("physostigma-venenosum", "Physostigma venenosum", "plant", ["hering"], "Kalabarbohne", "Calabar Bean", "Pupillenverengung und Akkommodationskrämpfe", "Myopia, pupillary contraction, twitching"),
    ("picricum-acidum", "Picricum acidum", "acid", ["kent", "hering"], "Pikrinsäure", "Picric Acid", "Schwere geistige Erschöpfung und Priapismus", "Brain fag, profound apathy, and priapism"),
    ("pimpinella-saxifraga", "Pimpinella saxifraga", "plant", ["hering"], "Kleine Bibernelle", "Burnet Saxifrage", "Heiserkeit und Kälteeiterung", "Laryngeal catarrh and chilliness"),
    ("pinus-sylvestris", "Pinus sylvestris", "plant", ["hering"], "Waldkiefer", "Scotch Pine", "Schwäche der Fußknöchel bei rachitischen Kindern", "Weak ankles in scrofulous children"),
    ("piper-methysticum", "Piper methysticum", "plant", ["hering"], "Kava-Kava", "Kava Kava", "Besserung aller Symptome durch Ablenkung", "Marked relief from mental diversion"),
    ("piper-nigrum", "Piper nigrum", "plant", ["hering"], "Schwarzer Pfeffer", "Black Pepper", "Brennender Magen- und Urethraschmerz", "Burning colic and urethral pain"),
    ("plantago-major", "Plantago major", "plant", ["hering"], "Breitwegerich", "Plantain", "Zahnschmerzen gebessert durch Zusammenbeißen", "Toothache relieved by eating and pressure"),
    ("platinum-metallicum", "Platinum metallicum", "mineral", ["hahnemann", "kent", "hering"], "Reines Platin", "Platinum", "Überheblichkeit, Schmerzen nehmen allmählich zu und ab", "Haughtiness, pains gradually wax and wane"),
    ("platinum-muriaticum", "Platinum muriaticum", "mineral", ["hering"], "Platinchlorid", "Platinum Chloride", "Nervenlähmungen und Dyspepsie", "Neuralgic headache and gastric weakness"),
    ("plumbum-aceticum", "Plumbum aceticum", "mineral", ["hahnemann", "hering"], "Bleiazetat", "Lead Acetate", "Kachexie und spastische Obstipation", "Cachexia and painter's colic"),
    ("plumbum-carbonicum", "Plumbum carbonicum", "mineral", ["hering"], "Bleiweiß", "White Lead", "Koliken mit Einziehung des Bauchnabels", "Violent colic, navel pulled to spine"),
    ("plumbum-iodatum", "Plumbum iodatum", "mineral", ["hering"], "Bleiiodid", "Lead Iodide", "Arteriosklerose und Sklerodermie", "Arteriosclerosis and indurations"),
    ("plumbum-metallicum", "Plumbum metallicum", "mineral", ["hahnemann", "kent", "hering"], "Metallisches Blei", "Lead", "Obstipation mit Gefühl der Nabelretraktion", "Obstinate constipation, blue gum line"),
    ("polygonum-hydropiperoides", "Polygonum hydropiperoides", "plant", ["hering"], "Wasserpfeffer", "Smartweed", "Uterusatonie und Menstruationskolik", "Amenorrhea and superficial burning"),
    ("polyporus-officinalis", "Polyporus officinalis", "plant", ["hering"], "Lärchenschwamm", "Larch Agaric", "Wechselfieber mit profusem Nachtschweiß", "Malarial fever and heavy night sweating"),
    ("populus-tremuloides", "Populus tremuloides", "plant", ["hering"], "Amerikanische Espe", "American Aspen", "Zystitis und Tenesmus post partum", "Post-operative cystitis and burning"),
    ("pothos-foetidus", "Pothos foetidus", "plant", ["hering"], "Stinkkohl", "Skunk Cabbage", "Asthma gebessert durch Stuhlgang", "Asthma relieved after passing stool"),
    ("prunus-spinosa", "Prunus spinosa", "plant", ["hering"], "Schlehdorn", "Blackthorn", "Ziliarneuralgie wie Augapfel zerspringend", "Ciliary neuralgia, eyeball feels bursting"),
    ("psorinum", "Psorinum", "nosode", ["kent"], "Psorische Nosode", "Psorinum", "Große Kälteempfindlichkeit, will warme Mütze im Sommer", "Chilly, wears fur cap in summer, despair"),
    ("ptelea-trifoliata", "Ptelea trifoliata", "plant", ["hering"], "Kleeulme", "Hop Tree", "Leberschmerz schlimmer beim Liegen auf linker Seite", "Liver soreness worse lying on left side"),
    # Q
    ("quassia-amara", "Quassia amara", "plant", ["hering"], "Bitterholz", "Quassia", "Magenleere und Madenwürmer", "Dyspepsia with empty sensation and worms"),
    ("quebracho", "Quebracho", "plant", ["hering"], "Weißes Quebracho", "Aspidosperma", "Lungenatemnot und Sauerstoffmangel", "Dyspnea from heart exertion, asthma"),
    ("quercus-robur", "Quercus robur", "plant", ["hering"], "Stieleiche", "Acorn", "Milzschwellung bei Alkoholikern", "Splenic hypertrophy in alcoholics"),
    # R
    ("radix-angelicae", "Radix angelicae", "plant", ["hering"], "Engelwurz", "Angelica", "Dyspepsie und Bronchialkatarrh", "Dyspeptic flatulence and cough"),
    ("radium-bromatum", "Radium bromatum", "mineral", ["kent"], "Radiumbromid", "Radium Bromide", "Rheumatische Schmerzen, Besserung durch heiße Bäder", "Aching pains relieved by hot baths"),
    ("ranunculus-acris", "Ranunculus acris", "plant", ["hering"], "Scharfer Hahnenfuß", "Meadow Crowfoot", "Gelenksteifigkeit und Hautbläschen", "Joint pain and dry burning skin"),
    ("ranunculus-bulbosus", "Ranunculus bulbosus", "plant", ["hahnemann", "kent", "hering"], "Knolliger Hahnenfuß", "Bulbous Buttercup", "Interkostalneuralgie und Herpes zoster", "Intercostal neuralgia and shingles"),
    ("ranunculus-sceleratus", "Ranunculus sceleratus", "plant", ["hahnemann", "kent", "hering"], "Gift-Hahnenfuß", "Marsh Celandine", "Landkartenzunge und beißende Blasen", "Mapped tongue and excoriating blisters"),
    ("raphanus-sativus", "Raphanus sativus", "plant", ["hering"], "Gartenrettich", "Black Radish", "Eingeklemmte Blähungen ohne Windabgang", "Incarcerated flatus, abdomen tympanitic"),
    ("ratanhia-peruviana", "Ratanhia peruviana", "plant", ["hering"], "Ratanhiawurzel", "Krameria", "Afterfissuren wie Glassplitter im Rektum", "Anal fissures like broken glass"),
    ("rheum-palmatum", "Rheum palmatum", "plant", ["hahnemann", "hering"], "Rhabarber", "Rhubarb", "Saurer Geruch des ganzen Körpers und Kolik", "Sour smelling child, screaming with colic"),
    ("rhus-aromatica", "Rhus aromatica", "plant", ["hering"], "Duftsumach", "Fragrant Sumac", "Enuresis nocturna und Inkontinenz", "Incontinence of urine and enuresis"),
    ("rhus-glabra", "Rhus glabra", "plant", ["hering"], "Kahlköpfiger Sumach", "Smooth Sumac", "Aphthen im Mund und Epistaxis", "Ulcerative aphthae and epistaxis"),
    ("rhus-venenata", "Rhus venenata", "plant", ["hering"], "Giftsumach", "Poison Sumac", "Schwere Urtikaria und Erythem", "Vesicular dermatitis and intense itching"),
    ("ricinus-communis", "Ricinus communis", "plant", ["hering"], "Rizinus", "Castor Oil", "Gastroenteritis mit Reiswasserstühlen", "Rice-water stools and nausea"),
    ("robinia-pseudoacacia", "Robinia pseudoacacia", "plant", ["hering"], "Falsche Akazie", "Black Locust", "Heftigstes saures Aufstoßen und Erbrechen", "Hyperchlorhydria with sour vomiting"),
    ("rosa-damascena", "Rosa damascena", "plant", ["hering"], "Damaszener Rose", "Damask Rose", "Heuschnupfen zu Beginn der Rosensaison", "Hay fever at beginning of summer"),
    ("rumex-crispus", "Rumex crispus", "plant", ["kent", "hering"], "Krauser Ampfer", "Yellow Dock", "Husten durch Einatmen kalter Luft, Mund bedecken", "Cough from cool air, covers mouth with sheet"),
    # S
    ("sabina", "Sabina", "plant", ["hahnemann", "kent", "hering"], "Sadebaum", "Savin", "Uterusblutungen vom Kreuzbein zum Schambein", "Uterine bleeding from sacrum to pubis"),
    ("saccharum-album", "Saccharum album", "plant", ["hering"], "Weißer Zucker", "White Sugar", "Heißhunger auf Süßigkeiten bei verwöhnten Kindern", "Craving sweets, petulant children"),
    ("saccharum-lactis", "Saccharum lactis", "animal", ["hering"], "Milchzucker", "Sugar of Milk", "Schlaflosigkeit und morgendlicher Kopfschmerz", "Nocturnal restlessness and headaches"),
    ("salicylicum-acidum", "Salicylicum acidum", "acid", ["hering"], "Salicylsäure", "Salicylic Acid", "Tinnitus, Menière und Magenbrennen", "Tinnitus, dizziness, and dyspepsia"),
    ("salix-nigra", "Salix nigra", "plant", ["hering"], "Schwarze Weide", "Black Willow", "Sexuelle Übererregbarkeit und Gonorrhoe", "Genital irritability and satyriasis"),
    ("sanicula-aqua", "Sanicula aqua", "mineral", ["kent"], "Sanicula-Mineralquelle", "Sanicula Springs", "Schlechter Körpergeruch trotz Waschens", "Offensive child despite washing"),
    ("santoninum", "Santoninum", "mineral", ["hering"], "Santonin", "Santonin", "Gelbsehen und Spulwürmer", "Xanthopsia (yellow vision) and roundworms"),
    ("saponaria-officinalis", "Saponaria officinalis", "plant", ["hering"], "Echtes Seifenkraut", "Soapwort", "Koryza mit Niesanfällen und Keratitis", "Violent sneezing coryza and eye ache"),
    ("sarsaparilla", "Sarsaparilla", "plant", ["hahnemann", "kent", "hering"], "Sarsaparille", "Smilax", "Unerträglicher Schmerz am Ende des Urinierens", "Excruciating pain at close of urination"),
    ("secale-cornutum", "Secale cornutum", "plant", ["hahnemann", "kent", "hering"], "Mutterkorn", "Ergot", "Körper eiskalt anzufassen, erträgt aber keine Decke", "Icy cold body yet cannot bear covers"),
    ("selenium-metallicum", "Selenium metallicum", "mineral", ["hahnemann", "kent", "hering"], "Mundanes Selen", "Selenium", "Haarausfall, Prostatatröpfeln und Heiserkeit", "Hair loss, involuntary prostatic dripping"),
    ("sempervivum-tectorum", "Sempervivum tectorum", "plant", ["hering"], "Hauswurz", "Houseleek", "Zungenkrebs und bösartige Aphthen", "Malignant aphthae and indurated tongue"),
    ("senecio-aureus", "Senecio aureus", "plant", ["kent", "hering"], "Goldenes Greiskraut", "Golden Ragwort", "Vikariierende Blutungen und Dysmenorrhoe", "Vicarious menstruation from lungs or kidneys"),
    ("senega", "Senega", "plant", ["kent", "hering"], "Klapperschlangenwurzel", "Snakeroot", "Rasselnder Schleim im Alter mit Brustdruck", "Abundant rattling phlegm in old people"),
    ("sinapis-alba", "Sinapis alba", "plant", ["hering"], "Weißer Senf", "White Mustard", "Koryza mit Speichelfluss und Magenbrennen", "Coryza with salivation and heartburn"),
    ("sinapis-nigra", "Sinapis nigra", "plant", ["hering"], "Schwarzer Senf", "Black Mustard", "Verstopfte Nase abwechselnd links und rechts", "Stoppage of left nostril alternating right"),
    ("solanum-carolinense", "Solanum carolinense", "plant", ["hering"], "Pferdenessel", "Horse Nettle", "Konvulsionen und Epilepsie zur Menses", "Convulsive seizures related to menses"),
    ("solanum-nigrum", "Solanum nigrum", "plant", ["hering"], "Schwarzer Nachtschatten", "Black Nightshade", "Meningismus mit Zuckungen und Kopfkongestion", "Meningeal irritation, contracted pupils"),
    ("solidago-virgaurea", "Solidago virgaurea", "plant", ["hering"], "Echte Goldrute", "Goldenrod", "Niereninsuffizienz mit spärlichem dunklem Urin", "Kidney tenderness with dark scanty urine"),
    ("spiraea-ulmaria", "Spiraea ulmaria", "plant", ["hering"], "Mädesüß", "Meadowsweet", "Gelenkrheumatismus mit sauren Schweißen", "Rheumatic joints with sour sweats"),
    ("squilla-maritima", "Squilla maritima", "plant", ["hahnemann", "kent", "hering"], "Meerzwiebel", "Sea Onion", "Husten mit unwillkürlichem Harnabgang", "Cough with involuntary spurt of urine"),
    ("stachys-betonica", "Stachys betonica", "plant", ["hering"], "Echte Betonie", "Wood Betony", "Kopfschmerz und zerebrale Erschöpfung", "Chronic nervous headache"),
    ("stannum-iodatum", "Stannum iodatum", "mineral", ["kent", "hering"], "Zinniodid", "Tin Iodide", "Erschöpfender chronischer Lungenkatarrh", "Chest weakness with sweetish expectoration"),
    ("stannum-metallicum", "Stannum metallicum", "mineral", ["hahnemann", "kent", "hering"], "Reines Zinn", "Tin Metal", "Brustschwäche, zu schwach zum Sprechen", "Profound chest weakness, too weak to talk"),
    ("sticta-pulmonaria", "Sticta pulmonaria", "plant", ["kent", "hering"], "Lungenflechte", "Lungmoss", "Trockenheit an der Nasenwurzel, kein Sekret", "Dull pressure at root of nose, dry rhinitis"),
    ("stillingia-sylvatica", "Stillingia sylvatica", "plant", ["hering"], "Königswurzel", "Queen's Root", "Knochen- und Periostschmerzen, Heiserkeit", "Syphilitic periostitis and deep hoarseness"),
    ("strontium-carbonicum", "Strontium carbonicum", "mineral", ["kent", "hering"], "Strontiumcarbonat", "Strontium Carbonate", "Schock nach Operationen und Knöchelverstauchung", "Post-operative shock and sprained ankles"),
    ("strontium-iodatum", "Strontium iodatum", "mineral", ["hering"], "Strontiumiodid", "Strontium Iodide", "Arteriosklerose mit Bluthochdruck", "Arteriosclerosis and myocardial weakness"),
    ("strophanthus-hispidus", "Strophanthus hispidus", "plant", ["hering"], "Kombé-Pfeilgift", "Strophanthus", "Herzschwäche mit schnellem flatterndem Puls", "Failing heart muscle with dropsy"),
    ("strychninum-metallicum", "Strychninum metallicum", "mineral", ["hering"], "Strychnin", "Strychnine", "Reflexkrämpfe bei geringster Berührung", "Tetanic spasms excited by touch"),
    ("strychninum-phosphoricum", "Strychninum phosphoricum", "mineral", ["hering"], "Strychninphosphat", "Strychnine Phosphate", "Spinale Schwäche und nervöse Erschöpfung", "Spinal exhaustion and nervous prostration"),
    ("sulfurosum-acidum", "Sulfurosum acidum", "acid", ["hering"], "Schweflige Säure", "Sulfurous Acid", "Pilzinfektionen und Diphtherie", "Ulcerative stomatitis and thrush"),
    ("sulphur-iodatum", "Sulphur iodatum", "mineral", ["kent", "hering"], "Schwefeliodid", "Sulfur Iodide", "Hartnäckige Akne und Flechten", "Barber's itch and chronic lichen"),
    ("syphilinum", "Syphilinum", "nosode", ["kent"], "Syphilitische Nosode", "Syphilinum", "Knochenschmerzen unerträglich von Sonnenuntergang bis Sonnenaufgang", "Linear bone pain worse dusk to dawn"),
    # T
    ("tanacetum-vulgare", "Tanacetum vulgare", "plant", ["hering"], "Rainfarn", "Tansy", "Krämpfe mit Schielen und Bauchschmerz", "Convulsions with strabismus"),
    ("taraxacum-officinale", "Taraxacum officinale", "plant", ["hahnemann", "kent", "hering"], "Löwenzahn", "Dandelion", "Landkartenzunge und Leberstauung", "Mapped tongue and bilious state"),
    ("tarentula-cubensis", "Tarentula cubensis", "animal", ["kent", "hering"], "Kubanische Vogelspinne", "Cuban Spider", "Bösartige Karbunkel mit bläulicher Verfärbung", "Carbuncles with purplish hue"),
    ("tarentula-hispana", "Tarentula hispana", "animal", ["kent", "hering"], "Spanische Tarantel", "Spanish Spider", "Rastlose motorische Unruhe, Besserung durch Musik", "Restless fidgets relieved by music"),
    ("taxus-baccata", "Taxus baccata", "plant", ["hering"], "Eibe", "Yew", "Pustulöse Hautausschläge und Magenleere", "Pustular skin eruptions and gastralgia"),
    ("tellurium-metallicum", "Tellurium metallicum", "mineral", ["hering"], "Metallisches Tellur", "Tellurium Metal", "Fischlakenartiger Geruch und Otitis", "Fish-brine body odor and otorrhea"),
    ("terebinthina", "Terebinthina", "mineral", ["hering"], "Terpentinöl", "Turpentine Oil", "Rauchiger blutiger Urin mit Kaffeesatzsediment", "Smoky albuminous urine with sediment"),
    ("theridion-curassavicum", "Theridion curassavicum", "animal", ["kent", "hering"], "Feuerspinne", "Orange Spider", "Überempfindlichkeit gegen Geräusche, Schwindel bei Augenschluss", "Hyperesthesia to noise, vertigo closing eyes"),
    ("thlaspi-bursa-pastoris", "Thlaspi bursa-pastoris", "plant", ["hering"], "Hirtentäschelkraut", "Shepherd's Purse", "Starke Uterusblutungen mit Krämpfen", "Profuse passive hemorrhage and gravel"),
    ("thyroidinum", "Thyroidinum", "nosode", ["hering"], "Schilddrüsen-Extrakt", "Thyroid Gland", "Myxödem, Kälte und Tachykardie", "Metabolic sluggishness and obesity"),
    ("tilia-europaea", "Tilia europaea", "plant", ["hering"], "Winterlinde", "Linden", "Schweiße mit Urtikaria und Zystitis", "Profuse sweat with warm urticaria"),
    ("trillium-pendulum", "Trillium pendulum", "plant", ["hering"], "Dreieckskraut", "Bethroot", "Hämorrhagien wie Becken auseinanderfallend", "Active uterine bleeding, hips fall apart"),
    ("trombidium-muscae", "Trombidium muscae", "animal", ["hering"], "Fliegenmilbe", "Fly Mite", "Schwere Ruhr nach dem Essen", "Dysentery immediately after eating"),
    # U
    ("ulmus-campestris", "Ulmus campestris", "plant", ["hering"], "Feldulme", "Elm Bark", "Juckende Flechten und Herpes", "Itching formication and squamous eczema"),
    ("uranium-nitricum", "Uranium nitricum", "mineral", ["hering"], "Uranylnitrat", "Uranium Nitrate", "Diabetes mellitus mit Polyurie und Abmagerung", "Diabetes mellitus with great emaciation"),
    ("usnea-barbata", "Usnea barbata", "plant", ["hering"], "Bartflechte", "Tree Moss", "Kongestiver Kopfschmerz wie Platzangst", "Congestive burst-like headache"),
    ("ustilago-maidis", "Ustilago maidis", "plant", ["hering"], "Maisbrand", "Corn Smut", "Flüssige dunkle Blutungen und Haarausfall", "Passive dark uterine hemorrhage and hair loss"),
    # V
    ("vaccininum", "Vaccininum", "nosode", ["hering"], "Kuhpocken-Nosode", "Vaccininum", "Folgen von Impfungen und Hautpusteln", "Post-vaccinal pustules and neuralgias"),
    ("valeriana-officinalis", "Valeriana officinalis", "plant", ["hahnemann", "kent", "hering"], "Echter Baldrian", "Valerian", "Hysterische Zustände, Schmerzen wandern umher", "Hysteria, feeling of floating in air"),
    ("variolinum", "Variolinum", "nosode", ["kent", "hering"], "Pocken-Nosode", "Variolinum", "Schwere Rückenschmerzen bei Fieber", "Severe lumbar aching and post-herpetic pain"),
    ("veratrum-viride", "Veratrum viride", "plant", ["kent", "hering"], "Grüne Nieswurz", "Green Hellebore", "Roter Streifen auf Zungenmitte und Herzrasen", "Red stripe down tongue and bounding pulse"),
    ("verbascum-thapsus", "Verbascum thapsus", "plant", ["hering"], "Große Königskerze", "Mullein", "Trompetenhusten und Zygomatikusneuralgie", "Trumpet-like deep hollow cough"),
    ("verbena-hastata", "Verbena hastata", "plant", ["hahnemann", "hering"], "Eisenkraut", "Blue Vervain", "Epilepsie und nervöser Krampfhusten", "Epileptiform spasms and insomnia"),
    ("vesicaria-communis", "Vesicaria communis", "plant", ["hering"], "Blasenkraut", "Bladderpod", "Zystitis und Prostatabrennen", "Acute and chronic cystitis with gravel"),
    ("viburnum-opulus", "Viburnum opulus", "plant", ["hering"], "Gemeiner Schneeball", "Cramp Bark", "Krampfartige Dysmenorrhoe mit Schenkelschmerz", "Spasmodic dysmenorrhea down thighs"),
    ("viburnum-prunifolium", "Viburnum prunifolium", "plant", ["hering"], "Pflaumenblättriger Schneeball", "Black Haw", "Drohender Abort und Nachwehen", "Threatened miscarriage and after-pains"),
    ("vinca-minor", "Vinca minor", "plant", ["hering"], "Kleines Immergrün", "Lesser Periwinkle", "Nässender Grind am Kopf mit verfilztem Haar", "Crusta lactea with matting of hair"),
    ("viola-odorata", "Viola odorata", "plant", ["hering"], "Wohlriechendes Veilchen", "Sweet Violet", "Augenpressen und hysterischer Kitzelhusten", "Tension across bridge of nose and eyes"),
    ("viola-tricolor", "Viola tricolor", "plant", ["hering"], "Stiefmütterchen", "Pansy", "Krustiges Gesichtsekzem mit Uringeruch wie Katzenharn", "Milk-crust eczema with cat-urine odor"),
    ("vipera-berus", "Vipera berus", "animal", ["hering"], "Kreuzotter", "German Viper", "Phlebitis, Bein schmerzt als würde es bersten", "Phlebitis, bursting feeling hanging down"),
    ("viscum-album", "Viscum album", "plant", ["hering"], "Mistel", "Mistletoe", "Bluthochdruck mit Schwindel und Epileptiform", "Hypertension with vertigo and palpitations"),
    # W
    ("wyethia-helenioides", "Wyethia helenioides", "plant", ["kent"], "Gift-Alant", "Poison Weed", "Extremes Kitzeln und Trockenheit im weichen Gaumen", "Itching and dryness of soft palate"),
    # X
    ("xanthoxylum-fraxineum", "Xanthoxylum fraxineum", "plant", ["hering"], "Gelbholz", "Prickly Ash", "Dysmenorrhoe mit linksseitiger Ischialgie", "Dysmenorrhea with left-sided sciatica"),
    # Y
    ("yucca-filamentosa", "Yucca filamentosa", "plant", ["hering"], "Palmlilie", "Bear Grass", "Bilöse Kopfschmerzen und gelblicher Stuhl", "Bilious headache and yellow coated tongue"),
    # Z
    ("zincum-aceticum", "Zincum aceticum", "mineral", ["hering"], "Zinkacetat", "Zinc Acetate", "Unruhe der Beine und zerebrale Erschöpfung", "Restless legs and brain fatigue"),
    ("zincum-arsenicosum", "Zincum arsenicosum", "mineral", ["hering"], "Zinkarsenit", "Zinc Arsenite", "Neuropathie und Schwäche nach Infekten", "Neuralgia and post-febrile weakness"),
    ("zincum-bromatum", "Zincum bromatum", "mineral", ["hering"], "Zinkbromid", "Zinc Bromide", "Kinderzucken und Teething-Krämpfe", "Chorea, dentition spasms in children"),
    ("zincum-carbonicum", "Zincum carbonicum", "mineral", ["hering"], "Zinkcarbonat", "Zinc Carbonate", "Schlaflosigkeit durch Fußunruhe", "Nervous twitching and restless feet"),
    ("zincum-cyanatum", "Zincum cyanatum", "mineral", ["hering"], "Zinkzyanid", "Zinc Cyanide", "Chorea minor und Zuckungen im Gesicht", "Chorea and facial twitches"),
    ("zincum-iodatum", "Zincum iodatum", "mineral", ["hering"], "Zinkiodid", "Zinc Iodide", "Drüsenschwellung bei nervösen Kindern", "Glandular hypertrophy in nervous subjects"),
    ("zincum-muriaticum", "Zincum muriaticum", "mineral", ["hering"], "Zinkchlorid", "Zinc Chloride", "Krämpfe und brennende Neuralgien", "Convulsions and burning neuralgias"),
    ("zincum-oxydatum", "Zincum oxydatum", "mineral", ["hering"], "Zinkoxid", "Zinc Oxide", "Magenkrämpfe und nervöser Schluckauf", "Gastric gastralgia and hiccups"),
    ("zincum-sulfuricum", "Zincum sulfuricum", "mineral", ["hering"], "Zinksulfat / Weißer Vitriol", "White Vitriol", "Erbrechen und Zuckungen der Augenmuskeln", "Persistent vomiting and eye spasms"),
    ("zingiber-officinale", "Zingiber officinale", "plant", ["hering"], "Ingwer", "Ginger", "Magenkoliken nach Trinken von Eiswasser", "Colic after drinking ice water, asthma")
]

print(f"Roster Part 3 has {len(ROSTER_PART3)} entries.")
