import fs from 'fs';
import path from 'path';
import { RawRemedy, buildEntry } from './buildRemedyUtils';

// Definition of all 297 remedies requested by the user
export const ALL_297_REMEDIES: RawRemedy[] = [
  // A - Part 1
  {
    id: 'abies-canadensis',
    latinName: 'Abies canadensis',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Kanadische Hemlocktanne',
      origin: 'Frische Nadeln und Zweigspitzen von Tsuga canadensis',
      essence: 'Magenmittel bei Heißhunger mit Magenschwäche, Kältegefühl und Senkungsgefühl im Epigastrium.',
      mainIndications: ['Magenbeschwerden mit Heißhunger', 'Magensenkung (Gastroptose)', 'Reizmagensyndrom', 'Uterusprolaps mit Magenbrennen'],
      keynotes: ['Gefühl, als ob der Magen wie ein Stein herabfällt', 'Heißhunger auf Fleisch, Gurken und Saures', 'Kältegefühl zwischen den Schulterblättern', 'Neigung zu Frösteln und Schüttelfrost'],
      mindEmotional: 'Mürrisch, gereizt durch Schwäche, verlangt nach Ruhe und Schonung.',
      modalitiesBetter: ['Nach dem Essen', 'Durch Liegen mit angezogenen Knien', 'Wärme'],
      modalitiesWorse: ['Aufstehen', 'Bewegung', 'Kälte', 'Leerer Magen'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Magen-Darm-Trakt', 'Vegetatives Nervensystem', 'Urogenitaltrakt'],
      differentialRemedies: ['Abies nigra', 'Anacardium', 'Nux vomica', 'Sepia'],
      searchKeywords: ['abies canadensis', 'hemlocktanne', 'heißhunger', 'magensenkung', 'magenkälte']
    },
    en: {
      commonName: 'Hemlock Spruce',
      origin: 'Fresh needles and bark of Tsuga canadensis',
      essence: 'Gastric remedy for canine hunger with stomach sinking and craving for heavy food.',
      mainIndications: ['Gastric disorders with ravenous hunger', 'Gastroptosis and sinking sensation', 'Dyspepsia with chilliness', 'Uterine prolapse'],
      keynotes: ['Sensation of stomach falling down', 'Craving for meat, pickles and coarse food', 'Cold water sensation between scapulae', 'Extreme chilliness'],
      mindEmotional: 'Pevish, irritable from exhaustion, desires rest.',
      modalitiesBetter: ['After eating', 'Lying with knees drawn up', 'Warmth'],
      modalitiesWorse: ['Standing up', 'Movement', 'Cold', 'Empty stomach'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '3x daily 5 globules',
      sphereOfAction: ['Gastrointestinal tract', 'Autonomic nervous system', 'Urogenital tract'],
      differentialRemedies: ['Abies nigra', 'Anacardium', 'Nux vomica', 'Sepia'],
      searchKeywords: ['abies canadensis', 'hemlock spruce', 'canine hunger', 'gastroptosis', 'stomach sinking']
    },
    fr: { commonName: 'Pruche du Canada' },
    es: { commonName: 'Abeto del Canadá' },
    it: { commonName: 'Abete del Canada' },
    el: { commonName: 'Καναδικό έλατο' },
    ru: { commonName: 'Пихта канадская' }
  },
  {
    id: 'abies-nigra',
    latinName: 'Abies nigra',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Schwarzfichte',
      origin: 'Harzige Zweigspitzen von Picea mariana',
      essence: 'Magenmittel mit dem charakteristischen Gefühl eines hartgekochten Eies in der Magengrube.',
      mainIndications: ['Dyspepsie bei älteren Menschen', 'Magenkrämpfe nach dem Essen', 'Schlafstörungen durch Magendruck', 'Kardiospasmus'],
      keynotes: ['Gefühl eines hartgekochten Eies in der Herzgrube', 'Völlige Appetitlosigkeit am Morgen, Heißhunger am Mittag/Abend', 'Schmerzhafter Magendruck sofort nach der Nahrungsaufnahme', 'Nächtliches Aufwachen durch Herzklopfen'],
      mindEmotional: 'Trübsinnig, melancholisch während der Verdauung, antriebslos.',
      modalitiesBetter: ['Aufrechtes Sitzen', 'Leichte Bewegung', 'Fasten'],
      modalitiesWorse: ['Nach dem Essen', 'Nachts im Liegen', 'Tabakgenuss'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '3x täglich 5 Globuli vor den Mahlzeiten',
      sphereOfAction: ['Magen', 'Ösophagus', 'Kardiovaskuläres System'],
      differentialRemedies: ['Nux vomica', 'Bryonia', 'Carbo vegetabilis', 'Ignatia'],
      searchKeywords: ['abies nigra', 'schwarzfichte', 'hartgekochtes ei', 'magendruck', 'dyspepsie']
    },
    en: {
      commonName: 'Black Spruce',
      origin: 'Resin of Picea mariana',
      essence: 'Gastric remedy centered on sensation of a hard-boiled egg lodged in the cardiac orifice.',
      mainIndications: ['Dyspepsia in elderly', 'Gastric distress after eating', 'Insomnia from gastric oppression', 'Cardiospasm'],
      keynotes: ['Sensation of a hard-boiled egg in pit of stomach', 'No morning appetite, great craving at noon/night', 'Pain immediately after eating', 'Nightly heart palpitations'],
      mindEmotional: 'Hypochondriac, depressed during indigestion.',
      modalitiesBetter: ['Sitting upright', 'Gentle walking', 'Fasting'],
      modalitiesWorse: ['After eating', 'Night lying down', 'Tobacco'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '3x daily 5 globules before meals',
      sphereOfAction: ['Stomach', 'Esophagus', 'Heart'],
      differentialRemedies: ['Nux vomica', 'Bryonia', 'Carbo vegetabilis', 'Ignatia'],
      searchKeywords: ['abies nigra', 'black spruce', 'hard-boiled egg sensation', 'gastric distress']
    },
    fr: { commonName: 'Épinette noire' },
    es: { commonName: 'Abeto negro' },
    it: { commonName: 'Abete nero' },
    el: { commonName: 'Μαύρη ελάτη' },
    ru: { commonName: 'Пихта черная' }
  },
  {
    id: 'abrotanum',
    latinName: 'Abrotanum',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Eberraute',
      origin: 'Frische Blätter und Stängel von Artemisia abrotanum',
      essence: 'Metastasierende Beschwerden, Marasmus und Abmagerung besonders der unteren Extremitäten trotz guten Appetits.',
      mainIndications: ['Abmagerung bei Kindern trotz gutem Essen', 'Metastasierende Entzündungen (Mumps auf Hoden/Brust)', 'Rheumatismus nach unterdrücktem Durchfall', 'Frostbeulen mit Brennen'],
      keynotes: ['Abmagerung von unten nach oben (Beine zuerst)', 'Wechselnde Symptome: Wenn Durchfall stoppt, kommen Gelenkschmerzen', 'Heißhunger, aber stetiger Gewichtsverlust', 'Bläuliches, faltiges Gesicht wie ein kleiner Greis'],
      mindEmotional: 'Reizbar, mutlos, mürrisch, boshaft bei Schwäche.',
      modalitiesBetter: ['Lockerung der Kleidung', 'Freier Durchfall', 'Bewegung'],
      modalitiesWorse: ['Kälte', 'Unterdrückung von Ausscheidungen', 'Nachtluft'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Stoffwechsel', 'Gelenke', 'Lymphsystem', 'Haut'],
      differentialRemedies: ['Iodum', 'Natrium chloratum', 'Tuberculinum', 'Sanicula'],
      searchKeywords: ['abrotanum', 'eberraute', 'marasmus', 'abmagerung beine', 'unterdrückter durchfall']
    },
    en: {
      commonName: 'Southernwood',
      origin: 'Fresh leaves of Artemisia abrotanum',
      essence: 'Metastatic pathology and marasmus with emaciation starting in lower extremities despite good appetite.',
      mainIndications: ['Emaciation in children', 'Metastatic complaints (mumps to testes)', 'Rheumatism after suppressed diarrhea', 'Chilblains'],
      keynotes: ['Emaciation ascending from legs upwards', 'Alternation of symptoms (diarrhea stops, joint pain starts)', 'Ravenous appetite with progressive weight loss', 'Old-looking wrinkled face in children'],
      mindEmotional: 'Cross, irritable, ill-natured, despondent.',
      modalitiesBetter: ['Loose clothing', 'Free bowel movements', 'Warmth'],
      modalitiesWorse: ['Cold', 'Suppressed discharges', 'Night air'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '2-3x daily 5 globules',
      sphereOfAction: ['Metabolism', 'Connective tissue', 'Joints', 'Skin'],
      differentialRemedies: ['Iodum', 'Natrium chloratum', 'Tuberculinum', 'Sanicula'],
      searchKeywords: ['abrotanum', 'southernwood', 'marasmus', 'emaciation legs', 'metastatic rheumatism']
    },
    fr: { commonName: 'Aurone' },
    es: { commonName: 'Abrótano macho' },
    it: { commonName: 'Abrotano' },
    el: { commonName: 'Αβρότονο' },
    ru: { commonName: 'Абротан' }
  },
  {
    id: 'absinthium',
    latinName: 'Absinthium',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Wermut',
      origin: 'Frische Blüten und Blätter von Artemisia absinthium',
      essence: 'Zentrales Nervenmittel bei zerebralen Reizzuständen, epileptiformen Anfällen, Schwindel und nervösem Tremor.',
      mainIndications: ['Epileptiforme Krämpfe mit Beißen der Zunge', 'Nervöse Schlaflosigkeit & Halluzinationen', 'Schwindel mit Fallneigung nach hinten', 'Nervöse Dyspepsie'],
      keynotes: ['Krämpfe mit Grimassieren und Zittern', 'Gefühl, als fiele man rückwärts', 'Stumpfsinnigkeit und Gedächtnislücken nach Anfällen', 'Pupillenerweiterung und Gesichtsblässe'],
      mindEmotional: 'Halluzinationen, Visionen von Ungeheuern, Verwirrung, unruhiger Schlaf.',
      modalitiesBetter: ['Ruhe', 'Dunkelheit', 'Wärme'],
      modalitiesWorse: ['Aufregung', 'Alkohol/Stimulanzien', 'Bewegung'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Zentralnervensystem', 'Gehirn', 'Magen-Darm-Trakt'],
      differentialRemedies: ['Cicuta virosa', 'Bufo', 'Hyoscyamus', 'Agaricus'],
      searchKeywords: ['absinthium', 'wermut', 'epilepsie', 'krämpfe', 'nervöser tremor', 'halluzinationen']
    },
    en: {
      commonName: 'Common Wormwood',
      origin: 'Fresh leaves and tops of Artemisia absinthium',
      essence: 'Neurological remedy for epileptiform convulsions, vertigo, tremors, and cerebral congestion.',
      mainIndications: ['Epileptoid seizures with tongue biting', 'Nervous tremors and chorea', 'Vertigo with backward falling tendency', 'Dyspeptic spasms'],
      keynotes: ['Spasmodic facial grimacing and trembling', 'Vertigo falling backwards', 'Memory loss after convulsions', 'Pupillary dilatation'],
      mindEmotional: 'Hallucinatory state, fearful visions, stupor.',
      modalitiesBetter: ['Rest', 'Quiet dark room', 'Warmth'],
      modalitiesWorse: ['Excitement', 'Stimulants', 'Sudden motion'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '2x daily 5 globules',
      sphereOfAction: ['Central nervous system', 'Cerebrum', 'Gastrointestinal tract'],
      differentialRemedies: ['Cicuta virosa', 'Bufo', 'Hyoscyamus', 'Agaricus'],
      searchKeywords: ['absinthium', 'wormwood', 'epileptiform convulsions', 'vertigo', 'tremor']
    },
    fr: { commonName: 'Grande Absinthe' },
    es: { commonName: 'Ajenjo' },
    it: { commonName: 'Assenzio' },
    el: { commonName: 'Αψιθιά' },
    ru: { commonName: 'Полынь горькая' }
  },
  {
    id: 'acalypha-indica',
    latinName: 'Acalypha indica',
    categoryKey: 'plant',
    importanceTier: 3,
    de: {
      commonName: 'Indisches Brennkraut',
      origin: 'Frische ganze Pflanze von Acalypha indica',
      essence: 'Hämorrhagisches Mittel für Atemwege und Magen-Darm mit morgendlichem Bluthusten und explosionsartigem Stuhl.',
      mainIndications: ['Hämoptysis (Bluthusten)', 'Tuberkulöse Frühstadien mit Lungenblutung', 'Explosionsartiger Durchfall mit viel Gas', 'Trockener Reizhusten mit Blutspuren'],
      keynotes: ['Bluthusten morgens hellrot, abends dunkel und geronnen', 'Explosiver Stuhldrang mit lauten Winden', 'Ständige Zerschlagenheit und Schwäche der Brust', 'Verschlimmerung am frühen Morgen'],
      mindEmotional: 'Deprimiert durch stetige Blutverluste, schwach, kraftlos.',
      modalitiesBetter: ['Ruhe', 'Frische kühle Luft'],
      modalitiesWorse: ['Morgens (Blutungen)', 'Abends (Husten)', 'Anstrengung'],
      potenciesAndDosage: 'D3, D6, D12',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Lunge & Bronchien', 'Gastrointestinaltrakt', 'Blutgefäße'],
      differentialRemedies: ['Millefolium', 'Phosphorus', 'Ferrum phosphoricum', 'Ipecacuanha'],
      searchKeywords: ['acalypha indica', 'indisches brennkraut', 'bluthusten', 'hämoptoe', 'explosionsartiger durchfall']
    },
    en: {
      commonName: 'Indian Acalypha',
      origin: 'Fresh plant of Acalypha indica',
      essence: 'Hemorrhagic remedy targeting respiratory and intestinal tracts with morning bright hemoptysis.',
      mainIndications: ['Hemoptysis and pulmonary hemorrhage', 'Incipient phthisis with blood-streaked sputum', 'Explosive morning diarrhea with flatus', 'Dry hacking cough'],
      keynotes: ['Blood bright red in morning, dark/clotted in evening', 'Explosive spluttering stool', 'Severe thoracic weakness', 'Worse in the morning hours'],
      mindEmotional: 'Exhausted, low-spirited from loss of blood.',
      modalitiesBetter: ['Absolute rest', 'Fresh cool air'],
      modalitiesWorse: ['Morning hours', 'Evening cough', 'Exertion'],
      potenciesAndDosage: 'D3, D6, D12',
      defaultTagesdosis: '3x daily 5 globules',
      sphereOfAction: ['Lungs', 'Blood vessels', 'Intestines'],
      differentialRemedies: ['Millefolium', 'Phosphorus', 'Ferrum phosphoricum', 'Ipecacuanha'],
      searchKeywords: ['acalypha indica', 'indian acalypha', 'hemoptysis', 'morning bleeding', 'explosive diarrhea']
    },
    fr: { commonName: 'Ricinelle des Indes' },
    es: { commonName: 'Acalifa índica' },
    it: { commonName: 'Acalifa indiana' },
    el: { commonName: 'Ακαλύφη η ινδική' },
    ru: { commonName: 'Акалифа индийская' }
  },
  {
    id: 'acidum-aceticum',
    latinName: 'Acidum aceticum',
    categoryKey: 'acid',
    importanceTier: 2,
    de: {
      commonName: 'Essigsäure',
      origin: 'Verdünnte reine Essigsäure (CH3COOH)',
      essence: 'Auszehrung, Anämie, massive Ödeme mit großem Durst und Liegen auf dem Bauch als Modalität.',
      mainIndications: ['Schwere Kachexie und Anämie', 'Generalisierte Ödeme & Aszites', 'Magenbrennen mit saurem Erbrechen', 'Hektisches Fieber mit Nachtschweiß'],
      keynotes: ['Unstillbarer Durst (außer bei Fieber)', 'Kann nur auf dem Bauch schlafen', 'Starker saurer Speichel- und Schweißfluss', 'Blässe wie Wachs mit hohlen Augen'],
      mindEmotional: 'Ängstlich um die Gesundheit, verstrickt in Sorgen, schwaches Gedächtnis.',
      modalitiesBetter: ['Auf dem Bauch liegen', 'Aufstoßen'],
      modalitiesWorse: ['Auf dem Rücken liegen', 'Kälte', 'Gemüsesäuren'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Stoffwechsel', 'Gefäßsystem (Ödeme)', 'Magen-Darm-Trakt', 'Blutbildung'],
      differentialRemedies: ['Arsenicum album', 'Apis mellifica', 'China officinalis', 'Ferrum'],
      searchKeywords: ['acidum aceticum', 'essigsäure', 'auszehrung', 'ödeme', 'auf dem bauch schlafen', 'unstillbarer durst']
    },
    en: {
      commonName: 'Glacial Acetic Acid',
      origin: 'Diluted acetic acid',
      essence: 'Deep wasting cachexia, dropsy with intense burning thirst and sleeping prone.',
      mainIndications: ['Profound debility and anemia', 'Anasarca and abdominal ascites', 'Severe gastralgia with sour regurgitation', 'Hectic fever with night sweats'],
      keynotes: ['Insatiable burning thirst (except during fever)', 'Can sleep only on the stomach/abdomen', 'Profuse sour salivation and sweat', 'Waxy pale emaciation'],
      mindEmotional: 'Anxious regarding family and health, fretful.',
      modalitiesBetter: ['Lying prone on belly', 'Eructations'],
      modalitiesWorse: ['Lying on back', 'Cold', 'Sour food'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '2-3x daily 5 globules',
      sphereOfAction: ['Fluid metabolism', 'Blood', 'Gastrointestinal system'],
      differentialRemedies: ['Arsenicum album', 'Apis mellifica', 'China officinalis', 'Ferrum'],
      searchKeywords: ['acidum aceticum', 'acetic acid', 'dropsy', 'sleeping on stomach', 'insatiable thirst']
    },
    fr: { commonName: 'Acide acétique' },
    es: { commonName: 'Ácido acético' },
    it: { commonName: 'Acido acetico' },
    el: { commonName: 'Οξικό οξύ' },
    ru: { commonName: 'Уксусная кислота' }
  },
  {
    id: 'acidum-benzoicum',
    latinName: 'Acidum benzoicum',
    categoryKey: 'acid',
    importanceTier: 2,
    de: {
      commonName: 'Benzoesäure',
      origin: 'Reine Benzoesäure aus Benzoeharz',
      essence: 'Harnsäure-Diathese mit penetrant nach Pferdeharn riechendem Urin, Gicht und Gelenkknacken.',
      mainIndications: ['Gicht und Arthritis deformans', 'Ganglion am Handgelenk', 'Zystitis mit stinkendem Urin', 'Achillessehnenentzündung'],
      keynotes: ['Urin riecht intensiv widerlich wie Pferdeharn', 'Urin dunkelbraun und brennend', 'Gelenke knacken bei jeder Bewegung', 'Symptome wechseln zwischen Gelenken und Harnwegen'],
      mindEmotional: 'Neigung zu Grübeln über unangenehme Dinge, niedergeschlagen.',
      modalitiesBetter: ['Reichliche Harnabsonderung', 'Wärme'],
      modalitiesWorse: ['Kaltes feuchtes Wetter', 'Veränderung der Witterung', 'Enthüllung'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Harnwege & Nieren', 'Gelenke & Sehnen', 'Harnsäurestoffwechsel'],
      differentialRemedies: ['Berberis', 'Ledum', 'Colchicum', 'Lithium carbonicum'],
      searchKeywords: ['acidum benzoicum', 'benzoesäure', 'pferdeharn', 'harnsäure', 'gicht', 'gelenkknacken']
    },
    en: {
      commonName: 'Benzoic Acid',
      origin: 'Purified Benzoic Acid',
      essence: 'Uric acid diathesis characterized by intensely offensive, horse-urine odor and gouty joints.',
      mainIndications: ['Gout and osteoarthritic tophi', 'Wrists ganglion', 'Cystitis with pungent dark urine', 'Achilles tendinitis'],
      keynotes: ['Urine smells intensely fetid like horses urine', 'Urine high-colored and brown', 'Audible cracking in joints on walking', 'Alternation of urinary and articular symptoms'],
      mindEmotional: 'Brooding over unpleasant past events, depressed.',
      modalitiesBetter: ['Copious urination', 'Warmth'],
      modalitiesWorse: ['Cold damp air', 'Weather changes', 'Uncovering'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '3x daily 5 globules',
      sphereOfAction: ['Urinary tract', 'Joints', 'Connective tissue'],
      differentialRemedies: ['Berberis', 'Ledum', 'Colchicum', 'Lithium carbonicum'],
      searchKeywords: ['acidum benzoicum', 'benzoic acid', 'horse urine odor', 'gout', 'joint cracking']
    },
    fr: { commonName: 'Acide benzoïque' },
    es: { commonName: 'Ácido benzoico' },
    it: { commonName: 'Acido benzoico' },
    el: { commonName: 'Βενζοϊκό οξύ' },
    ru: { commonName: 'Бензойная кислота' }
  },
  {
    id: 'acidum-formicicum',
    latinName: 'Acidum formicicum',
    categoryKey: 'acid',
    importanceTier: 3,
    de: {
      commonName: 'Ameisensäure',
      origin: 'Verdünnte reine Ameisensäure (Formica rufa)',
      essence: 'Chronische Erschöpfung, Muskelschwäche, Gicht und plötzliches Auftreten brennender Schmerzen.',
      mainIndications: ['Chronische Erschöpfung (CFS)', 'Myalgien & Muskelschwäche', 'Chronische Arthrose mit Steifheit', 'Allergische Diathese & Ekzeme'],
      keynotes: ['Schmerzen treten plötzlich auf und wechseln die Seite', 'Brennende Schmerzen wie von Ameisenbissen', 'Ausgeprägte Morgensteifheit, Besserung durch anhaltende Bewegung', 'Verstärkte Schweißneigung bei geringster Anstrengung'],
      mindEmotional: 'Apathisch durch anhaltende Muskelschwäche, vergesslich.',
      modalitiesBetter: ['Anhaltende Bewegung', 'Druck', 'Wärme'],
      modalitiesWorse: ['Kälte', 'Nässe', 'Vor Schneefall', 'Kaltes Baden'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Muskeln & Faszien', 'Gelenke', 'Nervensystem', 'Immunsystem'],
      differentialRemedies: ['Rhus toxicodendron', 'Dulcamara', 'Acidum phosphoricum', 'Causticum'],
      searchKeywords: ['acidum formicicum', 'ameisensäure', 'muskelschwäche', 'chronische erschöpfung', 'ameisenbisse']
    },
    en: {
      commonName: 'Formic Acid',
      origin: 'Diluted Formic Acid',
      essence: 'Profound muscular weakness, chronic arthritis, and sudden burning shooting neuralgias.',
      mainIndications: ['Chronic fatigue and muscle weakness', 'Articular stiffness and gout', 'Allergic eczema and urticaria', 'Kidney congestion'],
      keynotes: ['Burning sensations like ant stings', 'Pains appear suddenly and shift sides', 'Stiffness relieved by continued motion', 'Profuse sweat on slight exertion'],
      mindEmotional: 'Indolent, memory dull from exhaustion.',
      modalitiesBetter: ['Continued gentle motion', 'Firm pressure', 'Warmth'],
      modalitiesWorse: ['Cold', 'Damp weather', 'Before snowstorm'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '2x daily 5 globules',
      sphereOfAction: ['Muscles', 'Joints', 'Immune system'],
      differentialRemedies: ['Rhus toxicodendron', 'Dulcamara', 'Acidum phosphoricum', 'Causticum'],
      searchKeywords: ['acidum formicicum', 'formic acid', 'muscle fatigue', 'ant sting burning', 'gouty stiffness']
    },
    fr: { commonName: 'Acide formique' },
    es: { commonName: 'Ácido fórmico' },
    it: { commonName: 'Acido formico' },
    el: { commonName: 'Μυρμηκικό οξύ' },
    ru: { commonName: 'Муравьиная кислота' }
  },
  {
    id: 'acidum-hydrofluoricum',
    latinName: 'Acidum hydrofluoricum',
    categoryKey: 'acid',
    importanceTier: 2,
    de: {
      commonName: 'Flusssäure',
      origin: 'Verdünnte wässrige Fluorwasserstoffsäure (HF)',
      essence: 'Gewebsdestruktion, Knochennekrosen, Ulzerationen und venöse Stauungen bei heißblütigen, hyperaktiven Patienten.',
      mainIndications: ['Varizen und Ulcus cruris', 'Knochenfisteln & Karies der Knochen', 'Haarausfall & brüchige Nägel', 'Chronischer Nagelbettabszess'],
      keynotes: ['Extreme Hitzeintoleranz (verlangt Kälte und Eiswasser)', 'Stets in Eile, hyperaktiv, spürt keine Müdigkeit', 'Brennende, ätzende Absonderungen', 'Venöse Stauungen mit Neigung zu Geschwüren'],
      mindEmotional: 'Abneigung gegen die eigene Familie, heitere Gleichgültigkeit gegenüber Verpflichtungen, übersteigertes Selbstgefühl.',
      modalitiesBetter: ['Kälte', 'Kaltes Baden', 'Eiskompressen', 'Schnelle Bewegung'],
      modalitiesWorse: ['Wärme', 'Warme Getränke', 'Ruhe', 'Morgen'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Knochen & Zähne', 'Venensystem', 'Haut & Haare', 'Bindegewebe'],
      differentialRemedies: ['Silicea', 'Pulsatilla', 'Lachesis', 'Calcium fluoratum'],
      searchKeywords: ['acidum hydrofluoricum', 'acidum fluoricum', 'flusssäure', 'varizen', 'knochenfisteln', 'hitzeintoleranz']
    },
    en: {
      commonName: 'Hydrofluoric Acid',
      origin: 'Aqueous Hydrofluoric Acid',
      essence: 'Destructive ulcerations, bone fistulae, varicosities in warm-blooded, hyperactive subjects.',
      mainIndications: ['Varicose veins and leg ulcers', 'Bone caries and necrosis', 'Alopecia and corrugated nails', 'Chronic felon'],
      keynotes: ['Extreme intolerance of warmth, craves cold baths', 'Buoyant, hyperactive, senses no fatigue', 'Acrid corrosive discharges', 'Severe venous congestion'],
      mindEmotional: 'Indifference to loved ones, buoyant optimism, loss of affection.',
      modalitiesBetter: ['Cold air/water', 'Ice application', 'Rapid walking'],
      modalitiesWorse: ['Warmth in general', 'Warm drinks', 'Rest'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '2x daily 5 globules',
      sphereOfAction: ['Bones', 'Veins', 'Hair and nails', 'Skin'],
      differentialRemedies: ['Silicea', 'Pulsatilla', 'Lachesis', 'Calcium fluoratum'],
      searchKeywords: ['acidum hydrofluoricum', 'hydrofluoric acid', 'bone fistulae', 'varicose ulcers', 'heat intolerance']
    },
    fr: { commonName: 'Acide fluorhydrique' },
    es: { commonName: 'Ácido fluorhídrico' },
    it: { commonName: 'Acido fluoridrico' },
    el: { commonName: 'Υδροφθορικό οξύ' },
    ru: { commonName: 'Фтористоводородная кислота' }
  },
  {
    id: 'acidum-lacticum',
    latinName: 'Acidum lacticum',
    categoryKey: 'acid',
    importanceTier: 3,
    de: {
      commonName: 'Milchsäure',
      origin: 'Reine Milchsäure (C3H6O3)',
      essence: 'Schwangerschaftserbrechen, Diabetes mellitus mit Polyurie, Heißhunger und Schmerzen in den Brustdrüsen.',
      mainIndications: ['Hyperemesis gravidarum (Schwangerschaftserbrechen)', 'Diabetes mellitus Typ 2 mit Heißhunger & Durst', 'Mastodynie und Brustschwellung', 'Arthropathie mit Säuregefühl'],
      keynotes: ['Übelkeit wird durch Essen sofort gebessert', 'Ständiger Speichelfluss mit saurem Geschmack', 'Großer Appetit und unlöschbarer Durst mit reichlichem Urin', 'Schmerzhafte Empfindlichkeit der Mammae'],
      mindEmotional: 'Mürrisch, sarkastisch, weinerlich bei Übelkeit.',
      modalitiesBetter: ['Essen', 'Aufstoßen', 'Frühstück'],
      modalitiesWorse: ['Rauchen', 'Nüchternheit', 'Bewegung'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '3x täglich 5 Globuli vor den Mahlzeiten',
      sphereOfAction: ['Magen', 'Stoffwechsel (Glukose)', 'Mammae', 'Gelenke'],
      differentialRemedies: ['Ipecacuanha', 'Sepia', 'Tabacum', 'Phosphoric acid'],
      searchKeywords: ['acidum lacticum', 'milchsäure', 'schwangerschaftserbrechen', 'besser durch essen', 'diabetes mellitus']
    },
    en: {
      commonName: 'Lactic Acid',
      origin: 'Pure Lactic Acid',
      essence: 'Morning sickness relieved by eating, diabetes with ravenous thirst/hunger, and tender breasts.',
      mainIndications: ['Hyperemesis gravidarum', 'Diabetes with polyuria and copius thirst', 'Mastodynia and mammary tenderness', 'Rheumatic joint pains'],
      keynotes: ['Nausea instantly relieved by eating', 'Copious salivation with sour taste', 'Voracious hunger with unquenchable thirst', 'Painful fullness in breasts'],
      mindEmotional: 'Cross, irritable, weeping over nausea.',
      modalitiesBetter: ['Eating food', 'Eructation', 'Rest'],
      modalitiesWorse: ['Smoking', 'Empty stomach', 'Motion'],
      potenciesAndDosage: 'D6, D12, C30',
      defaultTagesdosis: '3x daily 5 globules before meals',
      sphereOfAction: ['Gastric tract', 'Endocrine/Pancreas', 'Mammary glands'],
      differentialRemedies: ['Ipecacuanha', 'Sepia', 'Tabacum', 'Phosphoric acid'],
      searchKeywords: ['acidum lacticum', 'lactic acid', 'morning sickness', 'ameliorated by eating', 'diabetes']
    },
    fr: { commonName: 'Acide lactique' },
    es: { commonName: 'Ácido láctico' },
    it: { commonName: 'Acido lattico' },
    el: { commonName: 'Γαλακτικό οξύ' },
    ru: { commonName: 'Молочная кислота' }
  }
];
