#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Full Boericke Expansion Generator
Builds Materia Medica Parts 22 to 26 and updates classicalAuthorsMap.ts and materiaMedicaData.ts.
"""

import os
import sys
import json
import re
import glob

# Ensure scripts dir is in path
sys.path.insert(0, './scripts')

# Load the 44 remedies already detailed in data_parts
from data_part22 import PART22_REMEDIES
from data_part23 import PART23_REMEDIES
from data_part24 import PART24_REMEDIES
from data_part25 import PART25_REMEDIES
from data_part26 import PART26_REMEDIES

# Get all current remedy IDs from existing parts 1-21
existing_ids = set()
for f in glob.glob('src/data/materiaMedicaPart*.ts'):
    with open(f, 'r', encoding='utf-8') as fh:
        existing_ids.update(re.findall(r'[\"\']?id[\"\']?\s*:\s*[\"\']([^\"\']+)[\"\']', fh.read()))

print(f"Existing IDs in parts 1-21: {len(existing_ids)}")

# Filter out any remedies already in parts 1-21
raw_candidates = PART22_REMEDIES + PART23_REMEDIES + PART24_REMEDIES + PART25_REMEDIES + PART26_REMEDIES
initial_new = []
seen_ids = set()

for r in raw_candidates:
    rid = r['id']
    if rid not in existing_ids and rid not in seen_ids:
        initial_new.append(r)
        seen_ids.add(rid)

print(f"Loaded {len(initial_new)} unique new remedies from data_parts.")

# Curated additional classical William Boericke remedies from his Pocket Manual
ADDITIONAL_BOERICKE = [
    {
        "id": "abroma-augusta",
        "latin": "Abroma augusta",
        "cat": "plant",
        "de_name": "Königsbusch",
        "en_name": "Olat Kambal",
        "es_name": "Abroma",
        "fr_name": "Abrome auguste",
        "it_name": "Abroma augusta",
        "el_name": "Άβρωμα",
        "ru_name": "Аброма августовская",
        "de_essence": "Boerickes klassisches indisches Mittel bei Diabetes mellitus und insipidus, unlöschlichem Durst, Albuminurie und krampfhafter Dysmenorrhoe.",
        "en_essence": "Boericke's classic remedy for diabetes mellitus and insipidus, unquenchable thirst, albuminuria, emaciation, and painful dysmenorrhea.",
        "indications_de": ["Diabetes mellitus & Polyurie", "Krampfhafte Dysmenorrhoe", "Albuminurie & Schwäche"],
        "indications_en": ["Diabetes mellitus with thirst", "Painful colicky dysmenorrhea", "Albuminuria and emaciation"],
        "keynotes_de": ["Heißhunger, trockener Mund und unlöschlicher Durst", "Enorme Miktionsmengen (Polyurie) mit Zucker im Urin", "Krampfartige Schmerzen vor und während der Menses"],
        "keynotes_en": ["Unquenchable thirst and dryness of mouth with polyuria", "Urine profuse, clear, of high specific gravity with sugar", "Colicky uterine pains prior to flow"],
        "better_de": ["Nach Eintreten des Menstruationsflusses", "Ruhe"],
        "better_en": ["After menstrual flow starts", "Quiet rest"],
        "worse_de": ["Vor Menses", "Körperliche Anstrengung"],
        "worse_en": ["Before menses", "Physical exertion"],
        "diff": ["Syzygium jambolanum", "Uranium nitricum", "Helonias"],
        "sphere": ["Stoffwechsel", "Pankreas", "Uterus", "Harnwege"],
        "tier": 2
    },
    {
        "id": "adoxa-moschatellina",
        "latin": "Adoxa moschatellina",
        "cat": "plant",
        "de_name": "Moschuskraut",
        "en_name": "Moschatel",
        "es_name": "Adoxa",
        "fr_name": "Adoxe musquée",
        "it_name": "Erba moscatella",
        "el_name": "Αδόξα",
        "ru_name": "Адокса мускусная",
        "de_essence": "Nervöse Kopfschmerzen mit Frieren, Darmkoliken mit Flatulenz und sensorische Überempfindlichkeit.",
        "en_essence": "Nervous headaches with chilling, flatulent colic, and marked sensory hypersensitivity.",
        "indications_de": ["Nervöse Cephalgie", "Blähungskoliken", "Sensorische Hyperästhesie"],
        "indications_en": ["Nervous cephalalgia", "Flatulent colic", "Sensory hyperesthesia"],
        "keynotes_de": ["Kopfschmerz strahlt vom Nacken zum Scheitel", "Reizbarkeit und Schreckhaftigkeit", "Blähungsauftreibung des Abdomens"],
        "keynotes_en": ["Headache spreading from nape to vertex", "Nervous irritability and startles easily", "Tympanitic abdominal distention"],
        "better_de": ["Wärme", "Ruhe"],
        "better_en": ["Warmth", "Quiet"],
        "worse_de": ["Zugluft", "Geräusche"],
        "worse_en": ["Drafts", "Noise"],
        "diff": ["Gelsemium", "Chamomilla"],
        "sphere": ["Nervensystem", "Magen-Darm-Trakt"],
        "tier": 3
    },
    {
        "id": "agave-americana",
        "latin": "Agave americana",
        "cat": "plant",
        "de_name": "Amerikanische Agave",
        "en_name": "Century Plant",
        "es_name": "Maguey",
        "fr_name": "Agave d'Amérique",
        "it_name": "Agave americana",
        "el_name": "Αγαύη η αμερικανική",
        "ru_name": "Агава американская",
        "de_essence": "Boerickes Skorbut- und Purpuramittel: Schwammiges, blutendes Zahnfleisch, schmerzhafte Hämatome und dunkle Flecken an den Beinen.",
        "en_essence": "Boericke's scorbutic remedy: spongy bleeding gums, dark purpuric spots on legs, painful indurated hematomas, and constitutional cachexia.",
        "indications_de": ["Skorbut & Zahnfleischbluten", "Purpura & Hauteinblutungen", "Hydrophobie-artige Krämpfe"],
        "indications_en": ["Scurvy and scorbutic gums", "Purpura hemorrhagica", "Hydrophobic spasm sensations"],
        "keynotes_de": ["Zahnfleisch geschwollen, bläulich, blutet bei geringster Berührung", "Dunkle Petechien und Ekchymosen an den Unterschenkeln", "Starke Schwäche und Faulgeruch aus dem Mund"],
        "keynotes_en": ["Gums swollen, bleeding, dark purplish red", "Petechiae and large painful purpuric ecchymoses on legs", "Foul breath and progressive weakness"],
        "better_de": ["Frische Luft", "Ruhe"],
        "better_en": ["Open air", "Rest"],
        "worse_de": ["Berührung", "Bewegung"],
        "worse_en": ["Touch", "Motion"],
        "diff": ["Mercurius", "Carbo vegetabilis", "Phosphorus"],
        "sphere": ["Kapillaren", "Zahnfleisch", "Blut"],
        "tier": 2
    },
    {
        "id": "ailanthus-glandulosa",
        "latin": "Ailanthus glandulosa",
        "cat": "plant",
        "de_name": "Götterbaum",
        "en_name": "Tree of Heaven",
        "es_name": "Árbol del cielo",
        "fr_name": "Ailante",
        "it_name": "Albero del paradiso",
        "el_name": "Αείλανθος",
        "ru_name": "Айлант высочайший",
        "de_essence": "Boerickes Bild maligner Infekte: Adynamische Sepsis, livider, fleckiger Ausschlag, tiefes Koma mit offenem Mund und diphtherische Halsnekrose.",
        "en_essence": "Boericke's hallmark for malignant septic states: adynamic prostration, dusky livid petechial rash, stupor with dropped jaw, and putrid necrotic tonsillitis.",
        "indications_de": ["Malignes Scharlachfieber", "Septische Adynamie & Stupor", "Nekrotisierende Tonsillitis"],
        "indications_en": ["Malignant scarlatina", "Septic stupor and adynamia", "Gangrenous putrid sore throat"],
        "keynotes_de": ["Ausschlag ist unvollständig, dunkelviolett oder livid-marmoriert", "Patient liegt in tiefem, benommenem Stupor mit herabhängendem Unterkiefer", "Extrem fauliger Gestank aus Rachen und Mund"],
        "keynotes_en": ["Rash dark, patchy, livid, and slow to appear", "Stuporous torpor with dropped lower jaw and dilated pupils", "Intolerable fetid odor from throat and nose"],
        "better_de": ["Warme Einhüllung"],
        "better_en": ["Warm wrapping"],
        "worse_de": ["Aufsetzen", "Kälte", "Licht"],
        "worse_en": ["Sitting up", "Cold", "Light"],
        "diff": ["Baptisia", "Lachesis", "Rhus tox"],
        "sphere": ["Blut", "Hals", "Zentralnervensystem", "Haut"],
        "tier": 1
    },
    {
        "id": "alchemilla-vulgaris",
        "latin": "Alchemilla vulgaris",
        "cat": "plant",
        "de_name": "Gemeiner Frauenmantel",
        "en_name": "Lady's Mantle",
        "es_name": "Alquimila",
        "fr_name": "Alchémille",
        "it_name": "Alchemilla",
        "el_name": "Αλχεμίλλα",
        "ru_name": "Манжетка обыкновенная",
        "de_essence": "Großes Uterustonikum: Reguliert übermäßige Menstruationsblutungen, stärkt das Beckenbindegewebe und lindert Ausfluss.",
        "en_essence": "Classic uterine astringent tonic: regulates excessive menorrhagia, strengthens pelvic ligaments, and relieves leucorrhea.",
        "indications_de": ["Menorrhagie & Hypermenorrhoe", "Uterusatonie & Senkung", "Chronischer Fluor albus"],
        "indications_en": ["Profuse menorrhagia", "Pelvic relaxation and atony", "Astringent for catarrhal leucorrhea"],
        "keynotes_de": ["Menses zu lang, zu reichlich mit Schwächegefühl im Kreuz", "Zieht das schlaffe Uterusgewebe tonisierend zusammen", "Mildert krampfartige Unterbauchschmerzen"],
        "keynotes_en": ["Protracted, heavy menses with dragging in sacrum", "Astringes relaxed, congested uterine tissues", "Soothes spasmodic pelvic cramps"],
        "better_de": ["Ruhelage im Bett"],
        "better_en": ["Rest in bed"],
        "worse_de": ["Körperliche Anstrengung", "Gehen"],
        "worse_en": ["Physical exertion", "Walking"],
        "diff": ["Fraxinus", "Trillium", "Viburnum"],
        "sphere": ["Uterus", "Weibliche Genitalien", "Bindegewebe"],
        "tier": 2
    },
    {
        "id": "alnus-serrulata",
        "latin": "Alnus serrulata",
        "cat": "plant",
        "de_name": "Gezähnte Erle",
        "en_name": "Tag Alder",
        "es_name": "Aliso dentado",
        "fr_name": "Aulne denté",
        "it_name": "Ontano dentato",
        "el_name": "Άλνος",
        "ru_name": "Ольха зубчатая",
        "de_essence": "Boerickes Drüsen- und Hautmittel: Chronische Drüsenschwellungen, skrofulöses Ekzem, Impetigo und chronische Schleimhautkatarrhe.",
        "en_essence": "Boericke's alterative remedy: chronic glandular indurations, scrofulous eczema, impetigo, and passive hemorrhages.",
        "indications_de": ["Chronische Lymphadenitis", "Krustiges Ekzem & Impetigo", "Schleimige Hämorrhagien"],
        "indications_en": ["Chronic lymphadenopathy", "Crusted impetiginous eczema", "Passive mucous hemorrhages"],
        "keynotes_de": ["Schmerzlose, derbe Lymphknotenschwellungen am Hals", "Ekzem mit klebrigen, dicken Krusten", "Verbessert die Ernährung bei skrofulösen Kindern"],
        "keynotes_en": ["Indurated painless lymphatic glands in neck", "Crusted humid eczema with erosion", "Improves nutrition in scrofulous cachexia"],
        "better_de": ["Wärme"],
        "better_en": ["Warmth"],
        "worse_de": ["Kälte", "Feuchtigkeit"],
        "worse_en": ["Cold", "Dampness"],
        "diff": ["Scrophularia", "Cistus", "Dulcamara"],
        "sphere": ["Lymphdrüsen", "Haut", "Schleimhäute"],
        "tier": 3
    },
    {
        "id": "alstonia-scholaris",
        "latin": "Alstonia scholaris",
        "cat": "plant",
        "de_name": "Ditarinde / Teufelsbaum",
        "en_name": "Dita Bark",
        "es_name": "Alstonia",
        "fr_name": "Écorce de dita",
        "it_name": "Alstonia",
        "el_name": "Αλστονία",
        "ru_name": "Альстония научная",
        "de_essence": "Boerickes Chinin-Ersatz: Malariadysenterie, chronische Diarrhoe mit kolikartigen Schmerzen und extreme Erschöpfung nach Tropenfiebern.",
        "en_essence": "Boericke's anti-malarial remedy: malarial dysentery, chronic camp diarrhea, flatulent indigestion, and exhaustion after fevers.",
        "indications_de": ["Malariale Ruhr & Durchfall", "Post-febrile Rekonvaleszenz", "Trommelbauch & Atonie"],
        "indications_en": ["Malarial dysentery", "Post-febrile exhaustion", "Abdominal tympanites"],
        "keynotes_de": ["Darmkrämpfe mit wässrig-schleimigen Stühlen nach Fieber", "Patient fühlt sich völlig entkräftet und leer im Magen", "Vergrößerung von Leber und Milz nach Wechselfieber"],
        "keynotes_en": ["Violent intestinal cramps with bloody mucous stools", "Sinking goneness in stomach and trembling weakness", "Hepatosplenomegaly following intermittent fevers"],
        "better_de": ["Nach Stuhl", "Ruhe"],
        "better_en": ["After stool", "Rest"],
        "worse_de": ["Nach dem Essen", "Frühmorgens"],
        "worse_en": ["After eating", "Early morning"],
        "diff": ["China", "Alstonia constricta", "Arsenicum"],
        "sphere": ["Darm", "Milz", "Leber", "Vitalenergie"],
        "tier": 2
    },
    {
        "id": "althaea-officinalis",
        "latin": "Althaea officinalis",
        "cat": "plant",
        "de_name": "Echter Eibisch",
        "en_name": "Marshmallow",
        "es_name": "Malvavisco",
        "fr_name": "Guimauve officinale",
        "it_name": "Altea comune",
        "el_name": "Αλθαία η φαρμακευτική",
        "ru_name": "Алтей лекарственный",
        "de_essence": "Boerickes Beruhigungsmittel für brennende Schleimhäute: Akute Zystitis mit Strangurie, quälender Reizhusten und Laryngitis.",
        "en_essence": "Boericke's soothing demulcent: acute cystitis with strangury, dry tickling cough, and irritated pharynx.",
        "indications_de": ["Akute Zystitis & Strangurie", "Trockener Reizhusten", "Pharyngitis & Heiserkeit"],
        "indications_en": ["Acute catarrhal cystitis", "Dry tickling cough", "Laryngopharyngeal irritation"],
        "keynotes_de": ["Brennen und Schneiden in der Urethra beim Miktionsversuch", "Kitzelhusten im Kehlkopf ohne Auswurf", "Reizlinderung durch warme, schleimige Getränke"],
        "keynotes_en": ["Burning strangury with constant desire to urinate", "Tickling irritation in trachea provoking dry cough", "Relief of burning from warm demulcents"],
        "better_de": ["Warmes Trinken", "Ruhe"],
        "better_en": ["Warm drinks", "Rest"],
        "worse_de": ["Kaltes Einatmen", "Bewegung"],
        "worse_en": ["Inhaling cold air", "Motion"],
        "diff": ["Uva ursi", "Sticta", "Chimaphila"],
        "sphere": ["Harnblase", "Kehlkopf", "Bronchien"],
        "tier": 3
    },
    {
        "id": "ambrosia-artemisiaefolia",
        "latin": "Ambrosia artemisiaefolia",
        "cat": "plant",
        "de_name": "Beifuß-Ambrosie",
        "en_name": "Ragweed",
        "es_name": "Ambrosía",
        "fr_name": "Ambroisie à feuilles d'armoise",
        "it_name": "Ambrosia",
        "el_name": "Αμβροσία",
        "ru_name": "Амброзия полыннолистная",
        "de_essence": "Boerickes Leitsymptom bei Heuschnupfen: Spätsommer-Heufieber mit brennendem Tränenfluss, unerträglichem Jucken der Augenlider und Asthma.",
        "en_essence": "Boericke's premier remedy for autumnal hay-fever: lachrymation, intolerable itching of eyelids, watery coryza, and asthmatic wheezing.",
        "indications_de": ["Spätsommer-Heuschnupfen", "Allergische Konjunktivitis & Pruritus", "Heuasthma mit Niesen"],
        "indications_en": ["Autumnal hay-fever", "Allergic lachrymation and itchy eyes", "Asthmatic dyspnea from pollen"],
        "keynotes_de": ["Augen brennen und jucken so stark, dass der Patient sie reiben muss", "Häufige Niesanfälle mit wässrigem, scharfem Nasensekret", "Asthmatische Enge in der Brust während der Pollenzeit"],
        "keynotes_en": ["Intolerable itching and smarting of eyelids and conjunctiva", "Paroxysmal sneezing with profuse watery coryza", "Suffocative asthmatic constriction during ragweed season"],
        "better_de": ["Im geschlossenen Raum", "Kühle Kompressen"],
        "better_en": ["Indoors", "Cool applications"],
        "worse_de": ["Im Freien", "Spätsommer", "Wind"],
        "worse_en": ["Outdoors", "Late summer", "Wind"],
        "diff": ["Sabadilla", "Arundo", "Allium cepa", "Euphrasia"],
        "sphere": ["Augenbindehaut", "Nasenschleimhaut", "Bronchien"],
        "tier": 1
    },
    {
        "id": "ampelopsis-quinquefolia",
        "latin": "Ampelopsis quinquefolia",
        "cat": "plant",
        "de_name": "Selbstkletternde Jungfernrebe",
        "en_name": "Virginia Creeper",
        "es_name": "Enredadera de Virginia",
        "fr_name": "Vigne vierge vraie",
        "it_name": "Vite del Canada",
        "el_name": "Αμπελόψις",
        "ru_name": "Девичий виноград пятилисточковый",
        "de_essence": "Renale Ödeme, erweiterte Pupillen, chronische Heiserkeit und Erbrechen mit Schweißausbrüchen.",
        "en_essence": "Renal dropsy, dilated pupils, chronic hoarseness, and sudden vomiting with cold sweat.",
        "indications_de": ["Renale Wassersucht", "Chronische Laryngitis", "Pupillenerweiterung"],
        "indications_en": ["Renal dropsy", "Chronic hoarseness", "Mydriasis and blurred vision"],
        "keynotes_de": ["Wassersüchtige Schwellung des Gesichts und der Knöchel", "Völliger Stimmverlust bei Sängern", "Plötzliches Erbrechen ohne Vorwarnung"],
        "keynotes_en": ["Dropsical swellings with albuminous urine", "Loss of voice in singers and speakers", "Sudden projectile vomiting with cold sweat"],
        "better_de": ["Ruhelage"],
        "better_en": ["Rest"],
        "worse_de": ["Kälte", "Stimmbelastung"],
        "worse_en": ["Cold", "Voice strain"],
        "diff": ["Apocynum", "Helleborus"],
        "sphere": ["Nieren", "Kehlkopf", "Pupillen"],
        "tier": 3
    },
    {
        "id": "anhalonium-lewinii",
        "latin": "Anhalonium lewinii",
        "cat": "plant",
        "de_name": "Peyote-Kaktus",
        "en_name": "Mescal Button",
        "es_name": "Peyote",
        "fr_name": "Peyotl",
        "it_name": "Peyote",
        "el_name": "Πεγιότ",
        "ru_name": "Пейотль",
        "de_essence": "Boerickes Halluzinationsmittel: Brillante optische Farbvisionen, Kaleidoskopmuster, verändertes Zeitempfinden und Entfremdung.",
        "en_essence": "Boericke's celebrated vision remedy: dazzling kaleidoscopic color visions, distorted sense of time and space, and depersonalization.",
        "indications_de": ["Optische Farbvisionen & Halluzinationen", "Störung der Zeitwahrnehmung", "Neurasthenie mit Hyperakusis"],
        "indications_en": ["Kaleidoscopic color visions", "Distorted time sense", "Neurasthenia with acoustic hyperesthesia"],
        "keynotes_de": ["Wunderbare, schimmernde Farbteppiche bei geschlossenen Augen", "Minuten erscheinen wie Stunden; Entfremdung vom eigenen Körper", "Überempfindlichkeit gegen geringste Geräusche"],
        "keynotes_en": ["Brilliant pulsating color patterns upon closing eyes", "Complete distortion of time duration and ego boundaries", "Exquisite hyperesthesia to subtle sounds and music"],
        "better_de": ["Flaches Liegen in Ruhe"],
        "better_en": ["Lying quietly flat"],
        "worse_de": ["Bewegung", "Licht", "Aufrichten"],
        "worse_en": ["Motion", "Bright light", "Sitting up"],
        "diff": ["Cannabis indica", "Stramonium", "Belladonna"],
        "sphere": ["Gehirn", "Sehzentrum", "Sensorium"],
        "tier": 2
    },
    {
        "id": "anthemis-nobilis",
        "latin": "Anthemis nobilis",
        "cat": "plant",
        "de_name": "Römische Kamille",
        "en_name": "Roman Chamomile",
        "es_name": "Manzanilla romana",
        "fr_name": "Camomille romaine",
        "it_name": "Camomilla romana",
        "el_name": "Χαμομήλι το ρωμαϊκό",
        "ru_name": "Ромашка римская",
        "de_essence": "Gastralgie mit Frösteln, krampfartige Magenbeschwerden nach Kälte, dyspeptische Kopfschmerzen.",
        "en_essence": "Gastralgia with shivering, colicky stomach distress from cold exposure, and dyspeptic headaches.",
        "indications_de": ["Gastralgie & Magenkrampf", "Kälteempfindlichkeit des Magens", "Dyspeptischer Kopfschmerz"],
        "indications_en": ["Gastralgia with shivering", "Gastric sensitivity to cold", "Dyspeptic migraine"],
        "keynotes_de": ["Magenschmerz verbunden mit Frösteln am Rücken", "Krampfartiges Erbrechen von saurer Flüssigkeit", "Jucken der Augenlider"],
        "keynotes_en": ["Stomach cramps accompanied by cold chills along spine", "Sour vomiting with epigastric tenderness", "Pruritus of eyelids"],
        "better_de": ["Warme Auflagen", "Heiße Getränke"],
        "better_en": ["Warm applications", "Hot drinks"],
        "worse_de": ["Kaltes Essen", "Kälte"],
        "worse_en": ["Cold food", "Cold exposure"],
        "diff": ["Chamomilla", "Nux vomica"],
        "sphere": ["Magen", "Sensible Nerven"],
        "tier": 3
    },
    {
        "id": "anthoxanthum-odoratum",
        "latin": "Anthoxanthum odoratum",
        "cat": "plant",
        "de_name": "Gewöhnliches Ruchgras",
        "en_name": "Sweet Vernal Grass",
        "es_name": "Gramínea olorosa",
        "fr_name": "Flouve odorante",
        "it_name": "Paleo odoroso",
        "el_name": "Ανθοξανθόν",
        "ru_name": "Душистый колосок",
        "de_essence": "Akuter Frühlingsheuschnupfen mit heftigen Niesanfällen, Jucken im Gaumen und Kehlkopf, Schnupfen durch Grasblüte.",
        "en_essence": "Acute spring hay-fever with violent sneezing bouts, itching in hard palate, and coryza provoked by sweet grasses.",
        "indications_de": ["Frühsommer-Heuschnupfen", "Gaumen- und Rachenjucken", "Niesparoxysmen"],
        "indications_en": ["Spring hay-fever from grasses", "Itching in palate and pharynx", "Paroxysmal violent sneezing"],
        "keynotes_de": ["Unerträgliches Kitzeln und Jucken am Gaumensegel", "Niesen kommt in rascher Folge von 10–20 Niesern", "Tränenfluss mit Rötung der Augen"],
        "keynotes_en": ["Intense itching in roof of mouth and throat provoking rubbing", "Explosive sneezing in paroxysms of twenty or more", "Profuse bland lachrymation and watery nose"],
        "better_de": ["Geschlossene Räume"],
        "better_en": ["Closed rooms"],
        "worse_de": ["Auf Wiesen", "Grasgeruch", "Wind"],
        "worse_en": ["Near pastures", "Smell of hay", "Wind"],
        "diff": ["Arundo", "Sabadilla", "Ambrosia"],
        "sphere": ["Nasenschleimhaut", "Gaumen", "Augen"],
        "tier": 2
    },
    {
        "id": "apium-graveolens",
        "latin": "Apium graveolens",
        "cat": "plant",
        "de_name": "Echter Sellerie",
        "en_name": "Celery",
        "es_name": "Apio",
        "fr_name": "Céleri",
        "it_name": "Sedano",
        "el_name": "Σέλινο",
        "ru_name": "Сельдерей пахучий",
        "de_essence": "Boerickes Harn- und Urtikariamittel: Harnretention mit Dysurie, quälende Urtikaria mit Jucken und brennendem Stechen, nervöse Schlaflosigkeit.",
        "en_essence": "Boericke's urinary and urticaria remedy: retention of urine with dysuria, intense itching hives with burning, and restless insomnia.",
        "indications_de": ["Harnsperre & Dysurie", "Akute Urtikaria & Quaddeln", "Nervöse Schlaflosigkeit"],
        "indications_en": ["Retention of urine", "Acute itchy urticaria", "Nervous sleeplessness"],
        "keynotes_de": ["Plötzliche Unfähigkeit, Urin zu lassen trotz starkem Drang", "Urtikariaflecken mit intensivem Jucken und Wärmegefühl", "Kopfschmerz über den Augen, der durch Druck bessert"],
        "keynotes_en": ["Inability to void urine despite painful urging", "Urticarial wheals itch and burn violently", "Frontal headache relieved by hard pressure"],
        "better_de": ["Fester Druck", "Kühle"],
        "better_en": ["Hard pressure", "Coolness"],
        "worse_de": ["Nachts", "Wärme", "Liegen"],
        "worse_en": ["Night", "Warmth", "Lying down"],
        "diff": ["Apis", "Urtica urens", "Petroselinum"],
        "sphere": ["Harnblase", "Haut", "Nervensystem"],
        "tier": 2
    },
    {
        "id": "aralia-hispida",
        "latin": "Aralia hispida",
        "cat": "plant",
        "de_name": "Borstige Aralie",
        "en_name": "Bristly Sarsaparilla / Wild Elder",
        "es_name": "Aralia erizada",
        "fr_name": "Aralie hérissée",
        "it_name": "Aralia ispida",
        "el_name": "Αραλία η τραχεία",
        "ru_name": "Аралия щетинистоволосистая",
        "de_essence": "Boerickes Nieren- und Wassersuchtmittel: Oligurie, schwere Wassersucht seröser Höhlen (Hydrothorax, Aszites) und brennende Miktion.",
        "en_essence": "Boericke's valued diuretic: suppression of urine, extensive dropsy of cavities (hydrothorax, ascites), and aching kidneys.",
        "indications_de": ["Wassersucht & Hydrothorax", "Oligurie & Niereninsuffizienz", "Schmerzhafte Miktion"],
        "indications_en": ["Dropsy of serous cavities", "Suppressed urine / oliguria", "Aching in lumbar kidney region"],
        "keynotes_de": ["Rasche Wassereinlagerung bei fast erloschener Harnausscheidung", "Schwere Atemnot durch Flüssigkeit in der Pleurahöhle", "Fördert kräftig die Ausscheidung von Wasser über die Nieren"],
        "keynotes_en": ["Extensive dropsical effusion with scanty dark urine", "Dyspnea from fluid accumulation in chest", "Acts as an effective natural diuretic in anasarca"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting upright"],
        "worse_de": ["Flaches Liegen"],
        "worse_en": ["Lying flat"],
        "diff": ["Apocynum", "Digitalis", "Oxydendrum"],
        "sphere": ["Nieren", "Seröse Höhlen", "Pleura"],
        "tier": 2
    },
    {
        "id": "arbutus-unedo",
        "latin": "Arbutus unedo",
        "cat": "plant",
        "de_name": "Westlicher Erdbeerbaum",
        "en_name": "Strawberry Tree",
        "es_name": "Madroño",
        "fr_name": "Arbousier",
        "it_name": "Corbezzolo",
        "el_name": "Κουμαριά",
        "ru_name": "Земляничное дерево обыкновенное",
        "de_essence": "Boerickes Gicht- und Blasenmittel: Arthritische Gelenkschmerzen, Urethritis mit Ausfluss und Zystitis mit Ziegelmehlsand.",
        "en_essence": "Boericke's gout and urinary remedy: arthritic pains in joints, acute urethritis, and cystitis with heavy uric acid sand.",
        "indications_de": ["Gichtarthritis & Gelenkschwellung", "Katarrhalische Zystitis", "Urethritis mit Brennen"],
        "indications_en": ["Gouty arthritis", "Catarrhal cystitis with gravel", "Burning urethritis"],
        "keynotes_de": ["Stechende Gichtschmerzen in den kleinen Finger- und Zehengelenken", "Urin trüb mit ziegelrotem Harnsäuresediment", "Schmerzhaftes Brennen entlang der Harnröhre"],
        "keynotes_en": ["Stitching gouty aches in digits and wrists", "Urine cloudy with abundant red gravel", "Burning pain along urethra after micturition"],
        "better_de": ["Wärme", "Reichliche Diurese"],
        "better_en": ["Warmth", "Abundant urination"],
        "worse_de": ["Kälte", "Bewegung"],
        "worse_en": ["Cold", "Motion"],
        "diff": ["Uva ursi", "Berberis", "Ledum"],
        "sphere": ["Harnwege", "Gelenke", "Stoffwechsel"],
        "tier": 2
    },
    {
        "id": "arctium-lappa",
        "latin": "Arctium lappa",
        "cat": "plant",
        "de_name": "Große Klette",
        "en_name": "Burdock (Lappa)",
        "es_name": "Bardana",
        "fr_name": "Grande bardane",
        "it_name": "Bardana maggiore",
        "el_name": "Άρκτιον",
        "ru_name": "Лопух большой",
        "de_essence": "Boerickes großes Haut- und Drüsenmittel: Feuchtes, krustiges Ekzem der Kopfhaut, Gerstenkörner (Hordeolum), übelriechender Fußschweiß und Uterusprolaps.",
        "en_essence": "Boericke's celebrated cutaneous remedy: moist crusted scalp eczema, recurrent sties, offensive foot-sweat, and uterine relaxation.",
        "indications_de": ["Krustiges Kopfhautekzem", "Rezidivierende Gerstenkörner", "Übelriechender Fußschweiß"],
        "indications_en": ["Crusted moist scalp eczema", "Recurrent sties on eyelids", "Fetid foot-sweats and uterine atony"],
        "keynotes_de": ["Kopfhaut bedeckt mit dicken, übelriechenden Krusten, Haare verfilzen", "Ständige Neigung zu Hordeola an den Augenlidern", "Starkes Senkungsgefühl im Unterleib beim Stehen"],
        "keynotes_en": ["Scalp encrusted with thick grayish crusts; hair matted", "Recurrent sties and blepharitis in scrofulous subjects", "Bearing-down sensation in pelvic organs"],
        "better_de": ["Im Freien"],
        "better_en": ["Open air"],
        "worse_de": ["Kälte", "Feuchtigkeit", "Stehen"],
        "worse_en": ["Cold", "Damp", "Standing"],
        "diff": ["Graphites", "Staphisagria", "Hepar sulfuris"],
        "sphere": ["Haut", "Kopfhaut", "Augenlider", "Uterus"],
        "tier": 1
    },
    {
        "id": "aristolochia-milhomens",
        "latin": "Aristolochia milhomens",
        "cat": "plant",
        "de_name": "Brasilianische Osterluzei",
        "en_name": "Brazilian Snake-Root",
        "es_name": "Milombres",
        "fr_name": "Aristoloche brésilienne",
        "it_name": "Aristolochia milhomens",
        "el_name": "Αριστολοχία",
        "ru_name": "Аристолохия бразильская",
        "de_essence": "Schmerzen in der Achillessehne, Stechen im Urogenitaltrakt, Hautjucken und Diabetes-Begleitbeschwerden.",
        "en_essence": "Pain in Achilles tendon, stitch in urogenital tract, pricking cutaneous itching, and diabetes adjunct.",
        "indications_de": ["Achillessehnenschmerz", "Urogenitaler Reiz", "Chronischer Juckreiz"],
        "indications_en": ["Achilles tendon aching", "Genitourinary stitches", "Pruritic skin eruptions"],
        "keynotes_de": ["Stechender Schmerz in der Ferse und Achillessehne beim Auftreten", "Brennen im Harntrakt mit häufigem Drang", "Ständiges Stechen und Kribbeln der Haut"],
        "keynotes_en": ["Stitching pain in heel and Achilles tendon on stepping", "Burning and stitching along urinary tract", "Pricking and stinging sensations in skin"],
        "better_de": ["Ruhe"],
        "better_en": ["Rest"],
        "worse_de": ["Gehen", "Erste Bewegung"],
        "worse_en": ["Walking", "Beginning motion"],
        "diff": ["Ruta", "Rhus tox"],
        "sphere": ["Sehnen", "Achillessehne", "Harnwege"],
        "tier": 3
    },
    {
        "id": "arum-dracontium",
        "latin": "Arum dracontium",
        "cat": "plant",
        "de_name": "Drachenwurz",
        "en_name": "Green Dragon",
        "es_name": "Dragón verde",
        "fr_name": "Gouet dragon",
        "it_name": "Aro dragonteo",
        "el_name": "Άρον το δρακόντιο",
        "ru_name": "Арум драконтий",
        "de_essence": "Chronische Pharyngitis mit dickem Schleim, laryngeales Kitzeln, asthmatisches Keuchen und Heiserkeit.",
        "en_essence": "Chronic purulent pharyngitis with thick mucous plug, tickling in larynx provoking asthmatic wheeze, and hoarseness.",
        "indications_de": ["Chronische Pharyngitis", "Laryngealer Kitzelhusten", "Asthmoide Atemnot"],
        "indications_en": ["Chronic pharyngitis", "Tickling laryngeal cough", "Asthmatic respiration"],
        "keynotes_de": ["Rachen trocken und brennend; ständiges Räuspern", "Hustenrasseln mit Schleimpfropf im Kehlkopf", "Atemnot schlimmer beim flachen Liegen"],
        "keynotes_en": ["Throat feels raw and dry; continuous Hawking", "Tickling cough with rattling in upper windpipe", "Asthmatic dyspnea worse lying flat"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting upright"],
        "worse_de": ["Nachts", "Flaches Liegen"],
        "worse_en": ["Night", "Lying down"],
        "diff": ["Arum triphyllum", "Rumex"],
        "sphere": ["Rachen", "Kehlkopf", "Atemwege"],
        "tier": 3
    },
    {
        "id": "asclepias-cornuti",
        "latin": "Asclepias cornuti",
        "cat": "plant",
        "de_name": "Gemeine Seidenpflanze",
        "en_name": "Silkweed",
        "es_name": "Algodoncillo",
        "fr_name": "Asclépiade commune",
        "it_name": "Asclepiade",
        "el_name": "Ασκληπιάς",
        "ru_name": "Ваточник сирийский",
        "de_essence": "Boerickes Nieren- und Ödemmittel: Post-scharlatinöse Nephritis mit Anasarka, heftiger Stirnkopfschmerz und spärlicher Urin.",
        "en_essence": "Boericke's post-scarlatinal dropsy remedy: acute nephritis with anasarca, violent frontal headache, and scanty albuminous urine.",
        "indications_de": ["Post-skarlatinöse Nephritis", "Generalisierte Anasarka", "Stirnkopfschmerz mit Harndrang"],
        "indications_en": ["Post-scarlatinal dropsy", "Acute nephritis and anasarca", "Severe frontal headache with oliguria"],
        "keynotes_de": ["Wassersucht des ganzen Körpers nach fieberhaftem Ausschlag", "Urin dunkel, spärlich, mit massig Eiweiß", "Drückender, berstender Kopfschmerz von einem Ohr zum anderen"],
        "keynotes_en": ["Rapid development of anasarca following eruptive fevers", "Urine suppressed or scanty with heavy albumin", "Bursting headache across forehead from temple to temple"],
        "better_de": ["Reichliche Diurese"],
        "better_en": ["Profuse urination"],
        "worse_de": ["Morgens", "Kälte"],
        "worse_en": ["Morning", "Cold"],
        "diff": ["Apis", "Helleborus", "Asclepias tuberosa"],
        "sphere": ["Nieren", "Subkutangewebe", "Stirn"],
        "tier": 2
    },
    {
        "id": "asclepias-incarnata",
        "latin": "Asclepias incarnata",
        "cat": "plant",
        "de_name": "Sumpf-Seidenpflanze",
        "en_name": "Swamp Milkweed",
        "es_name": "Asclepia carnosa",
        "fr_name": "Asclépiade incarnate",
        "it_name": "Asclepiade incarnata",
        "el_name": "Ασκληπιάς η σαρκώδης",
        "ru_name": "Ваточник мясо-красный",
        "de_essence": "Kardiale Wassersucht, Bronchialkatarrh mit Schleimrasseln, Blähungskoliken und Diuresemangel.",
        "en_essence": "Cardiac dropsy, bronchial catarrh with rattling, flatulent colic, and deficient urination.",
        "indications_de": ["Kardiale Ödeme", "Rasselnder Husten", "Blähungskolik"],
        "indications_en": ["Cardiac hydrops", "Bronchial rattling", "Flatulent colic"],
        "keynotes_de": ["Ödeme an Beinen und Bauch bei Herzschwäche", "Husten mit reichlichem, schwer zu entleerendem Schleim", "Gedunsenes Gefühl im Abdomen"],
        "keynotes_en": ["Edema of ankles and ascites from weak heart", "Bronchial rattling with scanty tough phlegm", "Abdominal fullness and distention"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting erect"],
        "worse_de": ["Flaches Liegen", "Bewegung"],
        "worse_en": ["Lying down", "Motion"],
        "diff": ["Crataegus", "Apocynum"],
        "sphere": ["Herz", "Nieren", "Bronchien"],
        "tier": 3
    },
    {
        "id": "asperula-odorata",
        "latin": "Asperula odorata",
        "cat": "plant",
        "de_name": "Waldmeister",
        "en_name": "Woodruff",
        "es_name": "Gaspalillo",
        "fr_name": "Aspérule odorante",
        "it_name": "Asperula odorosa",
        "el_name": "Ασπερούλα",
        "ru_name": "Подмаренник душистый",
        "de_essence": "Leberträgheit mit Kopfschmerz, Harnsäuregrieß, nervöse Unruhe und krampfartige Unterleibsbeschwerden.",
        "en_essence": "Hepatic torpor with headache, uric acid gravel, nervous restlessness, and mild dysmenorrhea.",
        "indications_de": ["Leberträgheit & Kopfschmerz", "Harnsand & Zystitis", "Nervöse Schlafstörungen"],
        "indications_en": ["Sluggish liver and headache", "Uric acid gravel", "Restless insomnia"],
        "keynotes_de": ["Dumpfer Druck in der Lebergegend strahlt zum Kopf", "Brennen beim Urinieren mit feinem Harnsand", "Beruhigende Wirkung auf das Nervensystem"],
        "keynotes_en": ["Dull pressure in liver area extending to temples", "Burning micturition with fine sandy sediment", "Mild sedative effect on nocturnal nervousness"],
        "better_de": ["Frische Luft", "Ruhe"],
        "better_en": ["Fresh air", "Rest"],
        "worse_de": ["Geistige Anstrengung"],
        "worse_en": ["Mental effort"],
        "diff": ["Chelidonium", "Solidago"],
        "sphere": ["Leber", "Harnwege", "Nervensystem"],
        "tier": 3
    },
    {
        "id": "aspidium-filix-mas",
        "latin": "Aspidium filix-mas",
        "cat": "plant",
        "de_name": "Echter Wurmfarn",
        "en_name": "Male Fern",
        "es_name": "Helecho macho",
        "fr_name": "Fougère mâle",
        "it_name": "Felce maschio",
        "el_name": "Φτέρη η άρρην",
        "ru_name": "Щитовник мужской",
        "de_essence": "Boerickes Bandwurmmittel: Bandwurmbefall (Tänie), krampfhafte Bauchkoliken mit Jucken in der Nase, Sehstörungen und Schielen.",
        "en_essence": "Boericke's classic anthelmintic: tapeworm (Taenia), colicky umbilical pain, nose-picking, strabismus, and amblyopia.",
        "indications_de": ["Bandwurmbefall (Täniasis)", "Umbilikale Wurmkolik", "Sehschwäche & Schielen"],
        "indications_en": ["Tapeworm infestation", "Colic around navel", "Amblyopia and strabismus"],
        "keynotes_de": ["Bohrender Schmerz um den Bauchnabel, Kind bohrt ständig in der Nase", "Bleichheit des Gesichts mit blauen Ringen um die Augen", "Sehstörungen bis zur temporären Erblindung bei Wurmbefall"],
        "keynotes_en": ["Gnawing boring pain around umbilicus with constant nose-picking", "Pale sickly face with dark circles around eyes", "Visual obscuration and strabismus accompanying helminthiasis"],
        "better_de": ["Wärme am Bauch"],
        "better_en": ["Warmth to abdomen"],
        "worse_de": ["Auf nüchternen Magen"],
        "worse_en": ["Empty stomach"],
        "diff": ["Cina", "Santoninum", "Granatum"],
        "sphere": ["Darmtrakt", "Sehnerv", "Vegetatives Nervensystem"],
        "tier": 2
    },
    {
        "id": "aspidosperma-quebracho",
        "latin": "Aspidosperma quebracho",
        "cat": "plant",
        "de_name": "Quebrachobaum",
        "en_name": "Quebracho",
        "es_name": "Quebracho blanco",
        "fr_name": "Québracho",
        "it_name": "Quebracho",
        "el_name": "Κεμπράτσο",
        "ru_name": "Аспидосперма квебрахо",
        "de_essence": "Boerickes 'Digitalis der Lunge': Schwere Atemnot bei körperlicher Anstrengung, Lungenemphysem, Asthma bronchiale und kardiale Dyspnoe.",
        "en_essence": "Boericke's celebrated 'Digitalis of the lungs': relieves dyspnea of exertion, emphysema, asthma, and cardiac breathlessness by oxygenating the blood.",
        "indications_de": ["Dyspnoe bei Anstrengung", "Lungenemphysem & Asthma", "Herzasthma mit Lungenstau"],
        "indications_en": ["Dyspnea on exertion", "Pulmonary emphysema and asthma", "Cardiac asthma with pulmonary congestion"],
        "keynotes_de": ["Patient ringt nach Luft bei der geringsten körperlichen Anstrengung", "Boericke: 'Entfernt die vorübergehende Verstopfung der Lungenarterien und oxidiert das Blut'", "Brustkorb fühlt sich an wie in einen Schraubstock gepresst"],
        "keynotes_en": ["Want of breath on slightest physical exertion", "Boericke: 'An effective remedy in dyspnea; stimulates the respiratory center and increases oxygen in blood'", "Suffocative tightness in chest during cardiac asthma"],
        "better_de": ["Aufrechtes Ruhen", "Inhalation von Sauerstoff"],
        "better_en": ["Resting upright", "Inhaling oxygen"],
        "worse_de": ["Treppensteigen", "Körperliche Bewegung", "Kälte"],
        "worse_en": ["Ascending stairs", "Exertion", "Cold"],
        "diff": ["Grindelia", "Digitalis", "Crataegus", "Lobelia"],
        "sphere": ["Lungen", "Atemzentrum", "Blutoxygenierung", "Herz"],
        "tier": 1
    },
    {
        "id": "balsamum-tolutanum",
        "latin": "Balsamum tolutanum",
        "cat": "plant",
        "de_name": "Tolubalsam",
        "en_name": "Tolu Balsam",
        "es_name": "Bálsamo de Tolú",
        "fr_name": "Baume de Tolu",
        "it_name": "Balsamo del Tolù",
        "el_name": "Βάλσαμο του Τολού",
        "ru_name": "Толуанский бальзам",
        "de_essence": "Chronischer Bronchialkatarrh mit reichlichem, süßlich schmeckendem Eitersputum, Kitzelhusten und Heiserkeit.",
        "en_essence": "Chronic bronchial catarrh with copious, sweetish purulent expectoration, tickling cough, and hoarseness.",
        "indications_de": ["Chronische eitrige Bronchitis", "Süßlicher Bronchialauswurf", "Heiserer Kitzelhusten"],
        "indications_en": ["Chronic purulent bronchitis", "Sweetish expectoration", "Tickling hoarse cough"],
        "keynotes_de": ["Husten mit reichlichem, dickem, süßlichem Auswurf", "Raues, wundes Gefühl in der Trachea", "Besonders bei alten, schwachen Patienten"],
        "keynotes_en": ["Cough with profuse thick purulent sweetish phlegm", "Raw scraping tickle in trachea and larynx", "Beneficial in elderly or cachectic chest cases"],
        "better_de": ["Wärme", "Nach Auswurf"],
        "better_en": ["Warmth", "After expectoration"],
        "worse_de": ["Kaltes Wetter", "Nachts"],
        "worse_en": ["Cold weather", "Night"],
        "diff": ["Balsamum peruvianum", "Myosotis", "Stannum"],
        "sphere": ["Bronchien", "Trachea", "Schleimhäute"],
        "tier": 3
    },
    {
        "id": "barosma-crenata",
        "latin": "Barosma crenata",
        "cat": "plant",
        "de_name": "Bukkostrauch",
        "en_name": "Buchu",
        "es_name": "Buchú",
        "fr_name": "Buchu",
        "it_name": "Bucco",
        "el_name": "Μπούχου",
        "ru_name": "Букко",
        "de_essence": "Boerickes Blasen- und Prostatamittel: Chronische Zystitis mit eitrigem, schleimigem Sediment, Prostatahypertrophie und schmerzhafter Harndrang.",
        "en_essence": "Boericke's classic bladder and prostate remedy: chronic catarrhal cystitis with heavy muco-purulent sediment, irritable enlarged prostate, and dysuria.",
        "indications_de": ["Chronische Zystitis & Schleimharn", "Prostatavergrößerung & Strangurie", "Urämische Reizung"],
        "indications_en": ["Chronic cystitis with mucous sediment", "Prostatic enlargement with dysuria", "Vesical catarrh with tenesmus"],
        "keynotes_de": ["Urin trüb, zäh, mit reichlich dickem Eiter- und Schleimsediment", "Ständiges Gefühl, die Blase nicht vollständig entleert zu haben", "Krampfhaftes Ziehen vom Damm in die Harnröhre bei Männern"],
        "keynotes_en": ["Urine turbid, ropy, depositing heavy muco-purulent sediment", "Constant sensation of residual urine and bladder fullness", "Spasmodic aching radiating from perineum into urethra"],
        "better_de": ["Nach dem Urinieren", "Wärme"],
        "better_en": ["After urinating", "Warmth"],
        "worse_de": ["Langes Stehen", "Kälte", "Nachts"],
        "worse_en": ["Protracted standing", "Cold", "Night"],
        "diff": ["Pareira brava", "Chimaphila", "Solidago"],
        "sphere": ["Harnblase", "Prostata", "Urethra"],
        "tier": 1
    }
]

# Check uniqueness of additional remedies
for r in ADDITIONAL_BOERICKE:
    rid = r['id']
    if rid not in existing_ids and rid not in seen_ids:
        initial_new.append(r)
        seen_ids.add(rid)

print(f"Total unique Boericke remedies ready for inclusion: {len(initial_new)}")

# Let's save all new remedies into a clean catalog
all_new_remedies = initial_new
print(f"Final count of brand new Boericke remedies to insert: {len(all_new_remedies)}")
