#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generates Materia Medica Parts 22 to 26 containing 165 classical William Boericke remedies.
Updates:
- src/data/materiaMedicaPart22.ts
- src/data/materiaMedicaPart23.ts
- src/data/materiaMedicaPart24.ts
- src/data/materiaMedicaPart25.ts
- src/data/materiaMedicaPart26.ts
- src/data/materiaMedicaData.ts
- src/data/classicalAuthorsMap.ts
"""

import json
import os

REMEDIES_DATA = [
    # --- PART 22 (33 remedies: A to B) ---
    {
        "id": "acalypha-indica",
        "latin": "Acalypha indica",
        "cat": "plant",
        "de_name": "Indische Brennnessel",
        "en_name": "Indian Nettle",
        "es_name": "Ortiga de la India",
        "fr_name": "Ortie de l'Inde",
        "it_name": "Ortica indiana",
        "el_name": "Ινδική τσουκνίδα",
        "ru_name": "Акалифа индийская",
        "de_essence": "Hervorragendes Mittel bei Hämoptysen und Lungenblutungen; morgens hellrotes Blut, abends dunkle Gerinnsel.",
        "en_essence": "A marked remedy for hemoptysis and chest haemorrhages; morning blood is bright red, evening dark and clotted.",
        "indications_de": ["Bluthusten (Hämoptysis)", "Morgendlicher Reizhusten", "Lungenblutung bei Phthisis"],
        "indications_en": ["Hemoptysis", "Morning racking cough", "Pulmonary hemorrhage"],
        "keynotes_de": ["Bluthusten morgens hellrot, abends dunkel klumpig", "Trockener Husten mit Blutstreifen", "Abzehrende Lungenschwäche"],
        "keynotes_en": ["Blood bright red in morning, dark clotted at night", "Dry cough followed by spitting of blood", "Exhausting chest weakness"],
        "better_de": ["Aufrechtes Sitzen", "Frische Luft"],
        "better_en": ["Sitting erect", "Open air"],
        "worse_de": ["Am frühen Morgen", "Flaches Liegen"],
        "worse_en": ["Early morning", "Lying down"],
        "diff": ["Millefolium", "Phosphorus", "Ipecacuanha"],
        "sphere": ["Lungen", "Atmungsorgane", "Blutgefäße"],
        "tier": 3
    },
    {
        "id": "adonis-vernalis",
        "latin": "Adonis vernalis",
        "cat": "plant",
        "de_name": "Frühlings-Adonisröschen",
        "en_name": "Pheasant's Eye",
        "es_name": "Adonis de primavera",
        "fr_name": "Adonis de printemps",
        "it_name": "Adonide primaverile",
        "el_name": "Άδωνις ο εαρινός",
        "ru_name": "Адонис весенний",
        "de_essence": "Großes Herztonikum nach Boericke bei Myokarddegeneration, unregelmäßigem Puls, Präkordialschmerz und Ödemen.",
        "en_essence": "Valuable cardiac tonic in Boericke's practice for fatty heart, irregular rapid pulse, dropsy, and dyspnea.",
        "indications_de": ["Kardiale Insuffizienz", "Ödeme durch Herzschwäche", "Präkordialer Engebeklemmungsschmerz"],
        "indications_en": ["Cardiac insufficiency", "Dropsy secondary to heart failure", "Precordial oppression and palpitation"],
        "keynotes_de": ["Herzklopfen mit unregelmäßigem, schnellem Puls", "Starke Atemnot bei der geringsten Anstrengung", "Wassersucht mit verminderter Harnausscheidung"],
        "keynotes_en": ["Palpitation with rapid irregular pulse", "Dyspnea on slightest exertion", "Oliguria with cardiac edema"],
        "better_de": ["Aufrechtes Ruhen", "Wärme"],
        "better_en": ["Quiet rest in upright posture", "Warmth"],
        "worse_de": ["Körperliche Anstrengung", "Treppensteigen"],
        "worse_en": ["Physical exertion", "Ascending stairs"],
        "diff": ["Crataegus", "Digitalis", "Strophanthus", "Convallaria"],
        "sphere": ["Herz-Kreislauf-System", "Myokard", "Nieren"],
        "tier": 2
    },
    {
        "id": "aletris-farinosa",
        "latin": "Aletris farinosa",
        "cat": "plant",
        "de_name": "Sternwurzel",
        "en_name": "Star Grass / Unicorn Root",
        "es_name": "Hierba estrella",
        "fr_name": "Alétris farineux",
        "it_name": "Aletride farinosa",
        "el_name": "Αλέτρις η αλευρώδης",
        "ru_name": "Алетрис мучнистый",
        "de_essence": "Großes Tonikum für anämische, erschöpfte Frauen mit Uterusatonie, Neigung zu Fehlgeburten und ständiger Müdigkeit.",
        "en_essence": "Anemic, debile tonic for women suffering from uterine atony, prolapse, nausea of pregnancy, and habitual miscarriages.",
        "indications_de": ["Uterusatonie & Gebärmuttersenkung", "Habitueller Abort", "Hartnäckiges Schwangerschaftserbrechen"],
        "indications_en": ["Uterine atony and prolapse", "Habitual miscarriages", "Obstinate vomiting of pregnancy"],
        "keynotes_de": ["Ständiges Schweregefühl im Unterleib", "Erschöpfung nach der geringsten Hausarbeit", "Heftige Übelkeit mit Ohnmachtsneigung"],
        "keynotes_en": ["Constant heavy bearing down in pelvis", "Extreme exhaustion from trivial housework", "Faintness and nausea during pregnancy"],
        "better_de": ["Ausruhen im Liegen", "Nach dem Essen"],
        "better_en": ["Rest in bed", "After eating"],
        "worse_de": ["Bücken", "Langes Stehen", "Anstrengung"],
        "worse_en": ["Bending", "Protracted standing", "Effort"],
        "diff": ["Helonias", "Sepia", "Fraxinus", "Caulophyllum"],
        "sphere": ["Uterus", "Weibliche Genitalien", "Blutbildung"],
        "tier": 2
    },
    {
        "id": "alfalfa",
        "latin": "Alfalfa",
        "cat": "plant",
        "de_name": "Luzerne / Alfalfa",
        "en_name": "Lucerne / Alfalfa",
        "es_name": "Alfalfa",
        "fr_name": "Luzerne",
        "it_name": "Erba medica",
        "el_name": "Μηδική η εδώδιμος (Άλφαλφα)",
        "ru_name": "Люцерна посевная",
        "de_essence": "Boerickes berühmtestes Rekonvaleszenz- und Nährtonikum; regt den Appetit an, stärkt die Verdauung und vertreibt Neurasthenie.",
        "en_essence": "Boericke's celebrated restorative tonic; acts as a fat producer, invigorates digestion, and relieves nervous depression.",
        "indications_de": ["Appetitlosigkeit & Gewichtsverlust", "Rekonvaleszenz nach Infekten", "Neurasthenie & Schlaflosigkeit"],
        "indications_en": ["Anorexia and malnutrition", "Convalescence from exhausting illness", "Neurasthenia and nervous insomnia"],
        "keynotes_de": ["Heißhunger am Vormittag", "Vertreibt depressive Gedanken und schenkt Vitalität", "Guter, tiefer Schlaf nach Einnahme"],
        "keynotes_en": ["Induces ravenous appetite with quick assimilation", "Clears mental depression and creates euphoria", "Deep, restorative sleep"],
        "better_de": ["Nach reichlichen Mahlzeiten", "Frische Luft"],
        "better_en": ["After eating", "Open air"],
        "worse_de": ["Fasten", "Geistige Überlastung"],
        "worse_en": ["Fasting", "Mental strain"],
        "diff": ["Avena sativa", "Ginseng", "China", "Lecithinum"],
        "sphere": ["Stoffwechsel", "Nervensystem", "Verdauung"],
        "tier": 2
    },
    {
        "id": "alstonia-constricta",
        "latin": "Alstonia constricta",
        "cat": "plant",
        "de_name": "Bittere Fieberrinde",
        "en_name": "Bitter Bark",
        "es_name": "Corteza amarga de Alstonia",
        "fr_name": "Écorce amère",
        "it_name": "Corteccia amara",
        "el_name": "Πικρός φλοιός Αλστονίας",
        "ru_name": "Альстония сжатая",
        "de_essence": "Malariaerschöpfung mit zittriger Magenschwäche, chronischem Durchfall und kachektischer Schwäche.",
        "en_essence": "Post-malarial debility with goneness in epigastrium, chronic diarrhea, and systemic exhaustion.",
        "indications_de": ["Post-Malaria-Zustände", "Chronischer Durchfall", "Magenatonie mit Zittern"],
        "indications_en": ["Post-malarial debility", "Chronic camp diarrhea", "Gastric atony with tremulousness"],
        "keynotes_de": ["Zittriges Schwächegefühl in der Magengrube", "Schleimige, schmerzhafte Stühle", "Periodische Erschöpfungsschübe"],
        "keynotes_en": ["Tremulous sensation in epigastrium", "Chronic mucous stools with debility", "Periodic exhaustion without high fever"],
        "better_de": ["Ruhelage", "Wärme"],
        "better_en": ["Resting quiet", "Warmth"],
        "worse_de": ["Körperliche Bewegung", "Nach dem Essen"],
        "worse_en": ["Exertion", "After meals"],
        "diff": ["China", "Hydrastis", "Arsenicum album"],
        "sphere": ["Magen-Darm-Trakt", "Milz", "Nervensystem"],
        "tier": 3
    },
    {
        "id": "ammoniacum-dorema",
        "latin": "Ammoniacum dorema",
        "cat": "plant",
        "de_name": "Dorema-Gummiharz",
        "en_name": "Gum Ammoniac",
        "es_name": "Goma amoníaco",
        "fr_name": "Gomme ammoniaque",
        "it_name": "Gomma ammoniaco",
        "el_name": "Αμμωνιακόν κόμμι",
        "ru_name": "Аммониакум",
        "de_essence": "Chronischer Bronchialkatarrh alter Menschen mit reichlichem Schleimrasseln und schwerem Auswurf.",
        "en_essence": "Chronic bronchial catarrh in elderly persons with heavy rattling of mucus and difficult expectoration.",
        "indications_de": ["Chronische Altersbronchitis", "Asthma mit zähem Schleim", "Gelenksteifigkeit"],
        "indications_en": ["Chronic bronchitis of the aged", "Asthma with tough phlegm", "Rheumatic joint stiffness"],
        "keynotes_de": ["Rasselnder Husten mit Schleimbeklemmung", "Gefühl von Rauch in der Luftröhre", "Schleim lässt sich kaum aushusten"],
        "keynotes_en": ["Rattling cough with oppression", "Sensation of smoke in larynx", "Tough mucus raised with difficulty"],
        "better_de": ["Wärme", "Aufrechtes Sitzen"],
        "better_en": ["Warmth", "Sitting upright"],
        "worse_de": ["Kaltes feuchtes Wetter", "Liegen"],
        "worse_en": ["Cold damp weather", "Lying down"],
        "diff": ["Antimonium tartaricum", "Senega", "Balsamum peruvianum"],
        "sphere": ["Bronchien", "Atemwege", "Gelenke"],
        "tier": 3
    },
    {
        "id": "amyl-nitrosum",
        "latin": "Amyl nitrosum",
        "cat": "mineral",
        "de_name": "Amylnitrit",
        "en_name": "Amyl Nitrite",
        "es_name": "Nitrito de amilo",
        "fr_name": "Nitrite d'amyle",
        "it_name": "Nitrito di amile",
        "el_name": "Νιτρώδες αμύλιο",
        "ru_name": "Амилнитрит",
        "de_essence": "Plötzliche Hitzewallungen im Klimakterium mit hochrotem Gesicht, Schweißausbrüchen, Pochen der Karotiden und Beklemmung.",
        "en_essence": "Sudden flushings of heat at menopause with throbbing carotids, drenching sweat, and precordial constriction.",
        "indications_de": ["Klimakterische Hitzewallungen", "Pulsierende Kopfschmerzen", "Angina pectoris mit Enge"],
        "indications_en": ["Climacteric hot flushes", "Congestive throbbing headaches", "Angina pectoris"],
        "keynotes_de": ["Plötzliche Hitzewellen zum Kopf mit Angst", "Sichtbares Pulsieren der Halsarterien", "Verlangen nach frischer Luft und offenen Fenstern"],
        "keynotes_en": ["Sudden surge of heat to face with anxiety", "Visible throbbing of carotids", "Craves fresh air and open windows"],
        "better_de": ["Frische Luft", "Kaltes Waschen"],
        "better_en": ["Open fresh air", "Cold water on face"],
        "worse_de": ["Geringste Aufregung", "Klimakterium", "Wärme"],
        "worse_en": ["Emotional excitement", "Menopause", "Warm room"],
        "diff": ["Lachesis", "Glonoinum", "Belladonna"],
        "sphere": ["Blutgefäße", "Vasomotorisches Nervensystem", "Herz"],
        "tier": 2
    },
    {
        "id": "anagallis-arvensis",
        "latin": "Anagallis arvensis",
        "cat": "plant",
        "de_name": "Ackergauchheil",
        "en_name": "Scarlet Pimpernel",
        "es_name": "Murajes",
        "fr_name": "Mouron rouge",
        "it_name": "Centonchio dei campi",
        "el_name": "Αναγαλλίς η αρουραία",
        "ru_name": "Очный цвет полевой",
        "de_essence": "Hautmittel bei hartnäckigem Jucken, Bläschenekzemen an Handflächen und Fingern sowie Urethralirritation.",
        "en_essence": "Marked cutaneous remedy for vesicular itching eczema on palms, fingers, and chronic urethral irritation.",
        "indications_de": ["Dyshidrotisches Handekzem", "Quälendes Hautjucken", "Chronische Urethritis"],
        "indications_en": ["Dyshidrotic eczema of palms", "Intolerable pruritus", "Chronic urethral irritation"],
        "keynotes_de": ["Bläschen an den Händen mit brennendem Juckreiz", "Haut trocken, rissig und schuppend", "Kribbeln und Brennen in der Harnröhre"],
        "keynotes_en": ["Vesicular eruption on hands with tingling itching", "Skin rough, dry, and chapped", "Tickling and burning along urethra"],
        "better_de": ["Kühle Umschläge"],
        "better_en": ["Cool applications"],
        "worse_de": ["Wasser und Waschen", "Berührung"],
        "worse_en": ["Water and washing", "Touch"],
        "diff": ["Rhus tox", "Graphites", "Petroleum"],
        "sphere": ["Haut", "Harnröhre", "Nervensystem"],
        "tier": 3
    },
    {
        "id": "anthracinum",
        "latin": "Anthracinum",
        "cat": "nosode",
        "de_name": "Milzbrand-Nosode",
        "en_name": "Anthracinum",
        "es_name": "Antracino",
        "fr_name": "Anthracinum",
        "it_name": "Antracino",
        "el_name": "Ανθρακίνη",
        "ru_name": "Антрацинум",
        "de_essence": "Schwerste septische Entzündungen, Karbunkel, Gangrän und Furunkel mit unerträglichen brennenden Schmerzen und Zersetzung.",
        "en_essence": "Malignant ulcerations, carbuncles, gangrene, and septic cellulitis with intolerable burning pains and prostration.",
        "indications_de": ["Maligne Karbunkel & Furunkel", "Septische Zellulitis", "Gangränöse Wundinfektionen"],
        "indications_en": ["Malignant carbuncles and boils", "Septic cellulitis", "Gangrenous infections"],
        "keynotes_de": ["Unerträgliches Brennen wie von glühenden Kohlen", "Dunkelblaue, eitrige Schwellungen mit üblem Geruch", "Tiefe Erschöpfung und septischer Kollaps"],
        "keynotes_en": ["Terrible burning pains as from red-hot coals", "Bluish indurated carbuncles with foul discharge", "Profound septic prostration"],
        "better_de": ["Heißeste Anwendungen"],
        "better_en": ["Very hot applications"],
        "worse_de": ["Kälte", "Berührung"],
        "worse_en": ["Cold", "Touch"],
        "diff": ["Arsenicum album", "Tarentula cubensis", "Echinacea"],
        "sphere": ["Blut", "Gewebe", "Haut", "Immunabwehr"],
        "tier": 2
    },
    {
        "id": "apocynum-cannabinum",
        "latin": "Apocynum cannabinum",
        "cat": "plant",
        "de_name": "Kanadischer Hanf",
        "en_name": "Indian Hemp",
        "es_name": "Cáñamo de Canadá",
        "fr_name": "Apocyn chanvrin",
        "it_name": "Apocino canapino",
        "el_name": "Απόκυνον το καννάβινον",
        "ru_name": "Кендырь коноплёвый",
        "de_essence": "Boerickes großes Wassersuchtmittel bei Herz-, Nieren- und Leberödemen mit unlöschbarem Durst und Erbrechen von Wasser.",
        "en_essence": "Boericke's pre-eminent dropsy remedy in cardiac, renal, and hepatic hydrops with unquenchable thirst and water intolerance.",
        "indications_de": ["Aszites & generalisierte Wassersucht", "Kardiale und renale Ödeme", "Hydrocephalus & Pleuraguss"],
        "indications_en": ["Ascites and general dropsy", "Cardiac and renal oedema", "Hydrothorax and pleurisy with effusion"],
        "keynotes_de": ["Großer Durst, doch Wasser wird sofort wieder erbrochen", "Massive Ödeme der Beine und des Abdomens", "Stumpfer Druck im Epigastrium mit Atemnot"],
        "keynotes_en": ["Great thirst, but cold water causes stomach distress and nausea", "Rapidly accumulating dropsical effusions", "Weak, irregular heart with oliguria"],
        "better_de": ["Reichliche Diurese", "Wärme"],
        "better_en": ["Profuse urination", "Warmth"],
        "worse_de": ["Kaltes Trinken", "Feuchtes Wetter"],
        "worse_en": ["Cold drinks", "Damp weather"],
        "diff": ["Arsenicum album", "Digitalis", "Helleborus"],
        "sphere": ["Seröse Häute", "Nieren", "Herz", "Gewebe"],
        "tier": 2
    },
    {
        "id": "aralia-racemosa",
        "latin": "Aralia racemosa",
        "cat": "plant",
        "de_name": "Amerikanische Narde",
        "en_name": "American Spikenard",
        "es_name": "Nardo americano",
        "fr_name": "Nard américain",
        "it_name": "Nardo americano",
        "el_name": "Αραλία η βοτρυώδης",
        "ru_name": "Аралия кистевидная",
        "de_essence": "Asthma und krampfhafter Husten, der den Patienten pünktlich um 23:00 oder 24:00 Uhr nach dem ersten Schlaf aus dem Bett treibt.",
        "en_essence": "Asthmatic and spasmodic cough awakening the patient abruptly around 11 p.m. or midnight after initial sleep.",
        "indications_de": ["Nächtliches Asthma bronchiale", "Spasmodischer Reizhusten", "Akuter Schnupfen mit Kitzeln"],
        "indications_en": ["Nocturnal bronchial asthma", "Spasmodic cough", "Hay fever and acute coryza"],
        "keynotes_de": ["Erwachen um 23 Uhr mit plötzlicher Erstickungsnot", "Pfeifendes Atmen mit zähem Schleim", "Husten schlimmer im Liegen, besser durch Vorbeugen"],
        "keynotes_en": ["Awakens at 11 p.m. gasping for breath", "Loud wheezing in chest with scanty mucus", "Must sit up and lean forward"],
        "better_de": ["Aufrechtes Sitzen und Vorbeugen"],
        "better_en": ["Sitting erect and bending forward"],
        "worse_de": ["Um 23:00 Uhr", "Flaches Hinlegen", "Zugluft"],
        "worse_en": ["Around 11 p.m.", "Lying down", "Draft of air"],
        "diff": ["Arsenicum album", "Grindelia", "Sambucus"],
        "sphere": ["Bronchien", "Kehlkopf", "Atmungsorgane"],
        "tier": 3
    },
    {
        "id": "aranea-diadema",
        "latin": "Aranea diadema",
        "cat": "animal",
        "de_name": "Kreuzspinne",
        "en_name": "Diadem Spider / Cross Spider",
        "es_name": "Araña diademada",
        "fr_name": "Araignée diadème",
        "it_name": "Ragno crociato",
        "el_name": "Αράχνη του σταυρού",
        "ru_name": "Крестовик обыкновенный",
        "de_essence": "Ständige, tiefe Kälte bis ins Knochenmark; Verschlimmerung durch jede feuchte Kälte oder Aufenthalt in feuchten Räumen.",
        "en_essence": "Deep bone-chilling coldness unaffected by warmth; extreme susceptibility to damp weather, rain, and cold rooms.",
        "indications_de": ["Malariaartige Kälteparoxysmen", "Periodische Neuralgien", "Knochenschmerzen bei Feuchtigkeit"],
        "indications_en": ["Malarial bone chill", "Periodical neuralgias", "Osteocopic pains in damp climates"],
        "keynotes_de": ["Fühlt sich durch und durch eisig kalt bis in die Knochen", "Symptome kehren täglich zur exakt gleichen Stunde wieder", "Schwellungsgefühl in den Fingern"],
        "keynotes_en": ["Sensation as if bones were made of ice", "Symptoms return at precisely the same hour daily", "Hands and arms feel swollen and huge"],
        "better_de": ["Rauchen", "Trockene Hitze"],
        "better_en": ["Smoking", "Dry external heat"],
        "worse_de": ["Feuchte Kälte", "Regenwetter", "Baden"],
        "worse_en": ["Damp cold", "Rainy weather", "Bathing"],
        "diff": ["Cedron", "Chinchona", "Dulcamara"],
        "sphere": ["Nervensystem", "Knochen", "Blut"],
        "tier": 3
    },
    {
        "id": "arbutus-andrachne",
        "latin": "Arbutus andrachne",
        "cat": "plant",
        "de_name": "Östlicher Erdbeerbaum",
        "en_name": "Strawberry Tree",
        "es_name": "Madroño oriental",
        "fr_name": "Arbousier de Chypre",
        "it_name": "Corbezzolo orientale",
        "el_name": "Ανδράχνη η κουμαριά",
        "ru_name": "Земляничник греческий",
        "de_essence": "Gichtrheumatismus mit nächtlichem Harndrang, Brennen in der Urethra und schmerzhafter Schwellung der Knie- und Fußgelenke.",
        "en_essence": "Gouty arthritis and eczema with vesical irritation, frequent urination, and aching in knees and small joints.",
        "indications_de": ["Gicht und Harnsäurediathese", "Zystitis mit Harndrang", "Arthritis der Knie und Zehen"],
        "indications_en": ["Gout and uric acid gravel", "Cystitis with urge", "Arthritic swelling of joints"],
        "keynotes_de": ["Gelenkschmerzen wechseln mit vermehrtem Harndrang ab", "Urin trüb mit reichlich Harnsäuresediment", "Brennendes Ziehen in Knien und Fersen"],
        "keynotes_en": ["Joint pain alternates with frequent urination", "Urine loaded with uric acid gravel", "Burning aches in knees and heels"],
        "better_de": ["Reichliche Miktion", "Ruhe"],
        "better_en": ["Copious urination", "Rest"],
        "worse_de": ["Wetterwechsel", "Fleischkost"],
        "worse_en": ["Weather changes", "Meat diet"],
        "diff": ["Uva ursi", "Colchicum", "Ledum"],
        "sphere": ["Harnwege", "Gelenke", "Stoffwechsel"],
        "tier": 3
    },
    {
        "id": "areca-catechu",
        "latin": "Areca catechu",
        "cat": "plant",
        "de_name": "Betelnusspalme",
        "en_name": "Betel Nut",
        "es_name": "Nuez de areca",
        "fr_name": "Noix d'arec",
        "it_name": "Noce di areca",
        "el_name": "Άρεκα η κατηχού",
        "ru_name": "Арека катеху",
        "de_essence": "Helminthiasis (Bandwurm) mit profusem Speichelfluss, Koliken und Pupillenverengung.",
        "en_essence": "Helminthiasis, tapeworm expeller, excessive salivation, and myosis.",
        "indications_de": ["Bandwurm- & Wurmbefall", "Chronischer Speichelfluss", "Spastische Darmkoliken"],
        "indications_en": ["Tapeworm infestation", "Ptyalism and salivation", "Intestinal colics"],
        "keynotes_de": ["Übermäßiger Speichelfluss im Mund", "Krampfartige Schmerzen um den Nabel", "Verengte Pupillen mit Schwindel"],
        "keynotes_en": ["Copious flow of saliva in mouth", "Griping colics around navel", "Contracted pupils with dizziness"],
        "better_de": ["Wärme am Bauch"],
        "better_en": ["Warmth to abdomen"],
        "worse_de": ["Nüchterner Magen"],
        "worse_en": ["Fasting"],
        "diff": ["Filix mas", "Granatum", "Santoninum"],
        "sphere": ["Darmtrakt", "Parasitenabwehr", "Speicheldrüsen"],
        "tier": 3
    },
    {
        "id": "argemone-mexicana",
        "latin": "Argemone mexicana",
        "cat": "plant",
        "de_name": "Mexikanischer Stachelmohn",
        "en_name": "Prickly Poppy",
        "es_name": "Cardo santo / Chicalote",
        "fr_name": "Chardon marbré",
        "it_name": "Cardo messicano",
        "el_name": "Αργεμόνη η μεξικανική",
        "ru_name": "Аргемона мексиканская",
        "de_essence": "Krampfartige Kolikschmerzen, Dysenterie, schmerzhafte Dysmenorrhoe und rheumatische Beschwerden.",
        "en_essence": "Spasmodic abdominal colic, dysentery, severe dysmenorrhea, and arthralgias.",
        "indications_de": ["Gallen- und Nierenkoliken", "Krampfhafte Menstruationsschmerzen", "Spasmodischer Husten"],
        "indications_en": ["Biliary and renal colic", "Spasmodic dysmenorrhea", "Spasmodic cough"],
        "keynotes_de": ["Krampfhafte Schmerzen, die den Patienten krümmen", "Gallenstau mit bitterem Geschmack", "Kopfschmerz mit Augendruck"],
        "keynotes_en": ["Violent colic compelling double bending", "Bilious vomiting with bitter taste", "Throbbing temple headache"],
        "better_de": ["Zusammenkrümmen", "Druck"],
        "better_en": ["Bending double", "Hard pressure"],
        "worse_de": ["Aufrechtes Stehen", "Kälte"],
        "worse_en": ["Standing erect", "Cold"],
        "diff": ["Colocynthis", "Magnesia phosphorica", "Dioscorea"],
        "sphere": ["Glatte Muskulatur", "Gallenblase", "Uterus"],
        "tier": 3
    },
    {
        "id": "aristolochia-clematitis",
        "latin": "Aristolochia clematitis",
        "cat": "plant",
        "de_name": "Osterluzei",
        "en_name": "Birthwort",
        "es_name": "Clemátide de Aristoloquia",
        "fr_name": "Aristoloche clématite",
        "it_name": "Aristolochia clematite",
        "el_name": "Αριστολοχία η κληματίτις",
        "ru_name": "Кирказон ломоносовидный",
        "de_essence": "Kongestionen der weiblichen Beckenorgane, Amenorrhoe, atonische Wundgeschwüre und Nierenbeschwerden.",
        "en_essence": "Pelvic venous stasis in females, delayed menses, indolent torpid ulcers, and urinary irritation.",
        "indications_de": ["Amenorrhoe & Zyklusstörungen", "Schlecht heilende Beingeschwüre", "Chronische Zystitis"],
        "indications_en": ["Delayed menses and amenorrhea", "Sluggish varicose ulcers", "Chronic cystitis"],
        "keynotes_de": ["Ausbleiben der Menses mit Schweregefühl im Becken", "Wunden heilen träge und nässen", "Häufiger Harndrang mit Brennen"],
        "keynotes_en": ["Suppressed or delayed menstruation", "Torpid ulcers refusing to granulate", "Burning urination with frequency"],
        "better_de": ["Frische Luft", "Mäßige Bewegung"],
        "better_en": ["Open air", "Gentle motion"],
        "worse_de": ["Vor der Menstruation", "Kälte"],
        "worse_en": ["Before menses", "Cold damp"],
        "diff": ["Pulsatilla", "Sepia", "Silicea"],
        "sphere": ["Uterus", "Venen", "Haut"],
        "tier": 3
    },
    {
        "id": "arundo-mauritanica",
        "latin": "Arundo mauritanica",
        "cat": "plant",
        "de_name": "Pfahlrohr",
        "en_name": "Italian Reed",
        "es_name": "Caña común",
        "fr_name": "Canne de Provence",
        "it_name": "Canna comune",
        "el_name": "Δόναξ ο καλαμοειδής",
        "ru_name": "Арундо тростниковый",
        "de_essence": "Boerickes Hauptmittel bei Heuschnupfen: unerträgliches Jucken am Gaumen, in den Gehörgängen und an den Augen.",
        "en_essence": "Boericke's premier hay fever remedy: intense burning itching of roof of mouth, nostrils, and auditory canals.",
        "indications_de": ["Allergischer Heuschnupfen", "Juckreiz an Gaumen und Gehörgang", "Akute Rhinitis mit Niesen"],
        "indications_en": ["Hay fever", "Itching of palate and ear canals", "Violent sneezing attacks"],
        "keynotes_de": ["Unerträgliches Jucken am weichen Gaumen und in den Ohren", "Ständige Niesanfälle mit wässrigem Brennschnupfen", "Verlust des Geruchssinns"],
        "keynotes_en": ["Maddening itching of palate and external auditory canals", "Paroxysms of sneezing with copious watery coryza", "Anosmia during coryza"],
        "better_de": ["Kaltes Wasser trinken", "Ruhe"],
        "better_en": ["Cold water drinks", "Rest"],
        "worse_de": ["Blütenstaub", "Wind", "Morgens"],
        "worse_en": ["Pollen season", "Windy days", "Morning"],
        "diff": ["Sabadilla", "Allium cepa", "Euphrasia"],
        "sphere": ["Schleimhäute", "Gaumen", "Gehörgang", "Nase"],
        "tier": 2
    },
    {
        "id": "asclepias-tuberosa",
        "latin": "Asclepias tuberosa",
        "cat": "plant",
        "de_name": "Knollige Seidenpflanze",
        "en_name": "Pleurisy Root",
        "es_name": "Raíz de la pleuresía",
        "fr_name": "Asclépiade tubéreuse",
        "it_name": "Asclepiade tuberosa",
        "el_name": "Ασκληπιάς η κονδυλώδης",
        "ru_name": "Ваточник клубневой",
        "de_essence": "Pleuritis, Interkostalneuralgie und Bronchitis mit stechenden Brustschmerzen und Schweißausbrüchen.",
        "en_essence": "Pleurisy, intercostal neuralgia, and catarrhal chest affections with sharp stitching pains and copious sweating.",
        "indications_de": ["Pleuritis & Pleurareizung", "Interkostalneuralgie", "Schmerzhafter Reizhusten"],
        "indications_en": ["Pleurisy and pleural friction", "Intercostal neuralgia", "Painful dry cough"],
        "keynotes_de": ["Stechende Schmerzen in der Brust beim Einatmen", "Warmes Schweißgefühl bei Fieber", "Gefühl als läge ein Gewicht auf der Brust"],
        "keynotes_en": ["Sharp stitching chest pains on inspiration", "Profuse warm perspiration with relief", "Sensation of weight on thoracic wall"],
        "better_de": ["Nach dem Schwitzen", "Vorbeugen"],
        "better_en": ["After sweating", "Bending forward"],
        "worse_de": ["Tiefe Inspiration", "Bewegung", "Kälte"],
        "worse_en": ["Deep breathing", "Motion", "Cold air"],
        "diff": ["Bryonia", "Ranunculus bulbosus", "Kalium carbonicum"],
        "sphere": ["Pleura", "Brustwand", "Bronchien"],
        "tier": 3
    },
    {
        "id": "asparagus-officinalis",
        "latin": "Asparagus officinalis",
        "cat": "plant",
        "de_name": "Gemüsespargel",
        "en_name": "Asparagus",
        "es_name": "Espárrago común",
        "fr_name": "Asperge",
        "it_name": "Asparago",
        "el_name": "Ασπάραγος ο φαρμακευτικός",
        "ru_name": "Спаржа лекарственная",
        "de_essence": "Starkes Harntreibemittel bei Herzklopfen, kardialen Ödemen, Nierenreizung und übelriechendem Urin.",
        "en_essence": "Diuretic cardiac remedy for palpitation, dropsy, hydrothorax, and offensive catarrhal urine.",
        "indications_de": ["Kardiale Ödeme", "Herzklopfen mit Angst", "Zystitis mit Harngeruch"],
        "indications_en": ["Cardiac dropsy", "Functional palpitations with anxiety", "Offensive catarrhal urine"],
        "keynotes_de": ["Starker, stechender Geruch des Harns", "Herzklopfen, das den Brustkorb erschüttert", "Stechen am Herz mit Atemnot beim Aufrichten"],
        "keynotes_en": ["Characteristic offensive odor of urine", "Violent palpitation jarring chest wall", "Stitches in heart and dyspnea on rising"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting erect"],
        "worse_de": ["Liegen auf linker Seite", "Bewegung"],
        "worse_en": ["Lying on left side", "Exertion"],
        "diff": ["Digitalis", "Crataegus", "Convallaria"],
        "sphere": ["Nieren", "Blase", "Herz"],
        "tier": 3
    },
    {
        "id": "astacus-fluviatilis",
        "latin": "Astacus fluviatilis",
        "cat": "animal",
        "de_name": "Flusskrebs",
        "en_name": "Crawfish",
        "es_name": "Cangrejo de río",
        "fr_name": "Écrevisse de rivière",
        "it_name": "Gambero di fiume",
        "el_name": "Αστακός του γλυκού νερού",
        "ru_name": "Рак речной",
        "de_essence": "Akute und chronische Urtikaria am ganzen Körper mit Leberüberlastung, Gelbsucht und Drüsenschwellungen.",
        "en_essence": "Acute and chronic generalized urticaria associated with hepatic congestion, jaundice, and lymphadenopathy.",
        "indications_de": ["Quälende Urtikaria (Nesselsucht)", "Leberschwellung mit Ikterus", "Vergrößerte Halsdrüsen"],
        "indications_en": ["Urticaria and nettle rash", "Hepatic congestion with jaundice", "Cervical lymphadenitis"],
        "keynotes_de": ["Urtikaria am ganzen Körper mit Brennen und Stechen", "Gelbfärbung von Skleren und Haut", "Schwellung und Druckschmerz der Leber"],
        "keynotes_en": ["Nettle-rash over entire body with crusts", "Jaundice with hepatic tenderness", "Itching stinging hives with fever"],
        "better_de": ["Aufdecken des Körpers"],
        "better_en": ["Uncovering"],
        "worse_de": ["Wärme des Bettes", "Nach dem Essen"],
        "worse_en": ["Warmth of bed", "After eating"],
        "diff": ["Apis mellifica", "Urtica urens", "Chelidonium"],
        "sphere": ["Haut", "Leber", "Lymphsystem"],
        "tier": 3
    },
    {
        "id": "asterias-rubens",
        "latin": "Asterias rubens",
        "cat": "animal",
        "de_name": "Seestern",
        "en_name": "Red Starfish",
        "es_name": "Estrella de mar roja",
        "fr_name": "Étoile de mer rouge",
        "it_name": "Stella marina rossa",
        "el_name": "Ερυθρός αστερίας",
        "ru_name": "Морская звезда красная",
        "de_essence": "Affektionen der Mammae, Mastitis, stechende Brustschmerzen und Kongestionen des Kopfes mit Schwindel.",
        "en_essence": "Mammary affections, neuralgic breast pains extending to arm, and cerebral congestions.",
        "indications_de": ["Mastodynie & Mammaverhärtung", "Stechende Schmerzen in der linken Brust", "Zerebrale Kongestionen"],
        "indications_en": ["Mastodynia and mammary induration", "Lancinating pains in left breast", "Cerebral congestions"],
        "keynotes_de": ["Stechende Schmerzen in der Brustwarze, die in den Rücken ziehen", "Brüste geschwollen, empfindlich vor den Menses", "Kongestiver Kopfschmerz wie zerspringend"],
        "keynotes_en": ["Drawing piercing pain in left breast pulling to back", "Breasts swollen and painful before menses", "Sensation as if head would burst"],
        "better_de": ["Kühles Zimmer", "Ausruhen"],
        "better_en": ["Cool room", "Rest"],
        "worse_de": ["Kaffee", "Kälte und Feuchtigkeit", "Nachts"],
        "worse_en": ["Coffee", "Cold dampness", "Night"],
        "diff": ["Conium", "Phytolacca", "Sepia"],
        "sphere": ["Mammae", "Weibliche Brust", "Gefäße"],
        "tier": 3
    },
    {
        "id": "atropinum-sulfuricum",
        "latin": "Atropinum sulfuricum",
        "cat": "mineral",
        "de_name": "Atropinsulfat",
        "en_name": "Atropine Sulfate",
        "es_name": "Sulfato de atropina",
        "fr_name": "Sulfate d'atropine",
        "it_name": "Solfato di atropina",
        "el_name": "Θειική ατροπίνη",
        "ru_name": "Атропина сульфат",
        "de_essence": "Blitzartige Neuralgien, Pupillenerweiterung, Trockenheit des Mundes und Magenkrämpfe mit Hyperazidität.",
        "en_essence": "Violent neuralgias, mydriasis, extreme dry mouth, gastric hyperacidity with severe gastralgia.",
        "indications_de": ["Heftige Trigeminusneuralgie", "Gastralgie & Magenkrämpfe", "Augenbeschwerden mit Mydriasis"],
        "indications_en": ["Trigeminal neuralgia", "Violent gastralgia and spasm", "Ocular ciliary neuralgia"],
        "keynotes_de": ["Plötzlich einschießende stechende Schmerzen", "Mund und Rachen trocken wie Pergament", "Erweiterte Pupillen mit Lichtscheu"],
        "keynotes_en": ["Sudden stabbing lightning neuralgias", "Mouth and throat dry as parchment", "Dilated pupils with photophobia"],
        "better_de": ["Vollkommene Ruhe", "Druck"],
        "better_en": ["Absolute quiet", "Firm pressure"],
        "worse_de": ["Geräusch", "Licht", "Erschütterung"],
        "worse_en": ["Noise", "Light", "Jarring"],
        "diff": ["Belladonna", "Magnesia phosphorica"],
        "sphere": ["Nervensystem", "Magen", "Augen"],
        "tier": 3
    },
    {
        "id": "avena-sativa",
        "latin": "Avena sativa",
        "cat": "plant",
        "de_name": "Echter Hafer",
        "en_name": "Oat",
        "es_name": "Avena",
        "fr_name": "Avoine cultivée",
        "it_name": "Avena",
        "el_name": "Βρώμη η κοινή",
        "ru_name": "Овёс посевной",
        "de_essence": "Großes Nerventonikum bei geistiger Erschöpfung, Neurasthenie, Schlaflosigkeit und Entzugssymptomen.",
        "en_essence": "Nutritive nerve tonic for brain fag, nervous exhaustion, debility from sexual excess or drug withdrawal.",
        "indications_de": ["Nervöse Erschöpfung & Burnout", "Schlaflosigkeit durch Gedankenandrang", "Rekonvaleszenz nach Überarbeitung"],
        "indications_en": ["Nervous exhaustion and brain fag", "Insomnia from nervous worry", "Debility after exhausting disease"],
        "keynotes_de": ["Kann nicht schlafen vor geistiger Überarbeitung", "Konzentrationsschwäche und nervöses Zittern", "Rasche Kräftigung bei Erschöpfungszuständen"],
        "keynotes_en": ["Sleeplessness in brain workers and alcoholics", "Nervous tremors and inability to concentrate", "Prompt tonic effect in convalescence"],
        "better_de": ["Guter Schlaf", "Warme Milch"],
        "better_en": ["Restful sleep", "Warm milk"],
        "worse_de": ["Sorgen", "Schlafmangel", "Exzesse"],
        "worse_en": ["Anxiety", "Lack of sleep", "Excesses"],
        "diff": ["Alfalfa", "Passiflora", "Scutellaria"],
        "sphere": ["Gehirn", "Zentralnervensystem", "Schlaf"],
        "tier": 2
    },
    {
        "id": "azadirachta-indica",
        "latin": "Azadirachta indica",
        "cat": "plant",
        "de_name": "Neembaum",
        "en_name": "Margosa / Neem",
        "es_name": "Árbol de nim",
        "fr_name": "Margousier / Neem",
        "it_name": "Albero di Neem",
        "el_name": "Αζαδιράχτα η ινδική (Νιμ)",
        "ru_name": "Азадирахта индийская (Ним)",
        "de_essence": "Periodische Wechselfieber am Nachmittag, Brennen der Augen und juckende Hautausschläge.",
        "en_essence": "Afternoon intermittent fevers, glowing burning eyes, and persistent itching skin eruptions.",
        "indications_de": ["Intermittierendes Fieber", "Konjunktivitis mit Brennen", "Juckende Hautausschläge"],
        "indications_en": ["Intermittent fever paroxysms", "Burning conjunctivitis", "Itching cutaneous eruptions"],
        "keynotes_de": ["Frostschauer um 16:30 Uhr beginnend", "Brennen in Handflächen und Fußsohlen", "Gefühl als stünden die Augen in Flammen"],
        "keynotes_en": ["Chill commences about 4:30 p.m.", "Burning in palms and soles", "Sensation of glowing coals in eyes"],
        "better_de": ["Frische Luft", "Ruhe"],
        "better_en": ["Open air", "Rest"],
        "worse_de": ["Spätnachmittags (16-17 Uhr)"],
        "worse_en": ["Late afternoon"],
        "diff": ["Cedron", "China", "Arsenicum album"],
        "sphere": ["Haut", "Augen", "Thermoregulation"],
        "tier": 3
    },
    {
        "id": "baccharis-cordifolia",
        "latin": "Baccharis cordifolia",
        "cat": "plant",
        "de_name": "Mio-Mio",
        "en_name": "Mio-Mio",
        "es_name": "Mio-Mio",
        "fr_name": "Mio-Mio",
        "it_name": "Mio-Mio",
        "el_name": "Βακχαρίς",
        "ru_name": "Бакхарис сердцелистный",
        "de_essence": "Schwere gastrointestinale Reizung mit brennenden Magenkrämpfen, Brechdurchfall und Schwäche.",
        "en_essence": "Intense gastro-intestinal poisoning, burning gastralgia, toxic vomiting, and prostration.",
        "indications_de": ["Gastroenteritis mit Erbrechen", "Toxische Koliken", "Nervöse Magenreizung"],
        "indications_en": ["Acute toxic gastroenteritis", "Violent abdominal cramps", "Irritable stomach"],
        "keynotes_de": ["Brennende Schmerzen in Ösophagus und Magen", "Schwächegefühl mit kaltem Schweiß", "Brechreiz bei geringster Nahrung"],
        "keynotes_en": ["Burning heat in gullet and stomach", "Faintness with cold sweat", "Incessant retching"],
        "better_de": ["Ruhelage", "Wärme"],
        "better_en": ["Rest", "Warmth"],
        "worse_de": ["Nahrungsaufnahme", "Bewegung"],
        "worse_en": ["Ingesting food", "Motion"],
        "diff": ["Arsenicum album", "Veratrum album"],
        "sphere": ["Magen-Darm-Trakt", "Vegetatives Nervensystem"],
        "tier": 3
    },
    {
        "id": "balsamum-peruvianum",
        "latin": "Balsamum peruvianum",
        "cat": "plant",
        "de_name": "Perubalsam",
        "en_name": "Balsam of Peru",
        "es_name": "Bálsamo del Perú",
        "fr_name": "Baume du Pérou",
        "it_name": "Balsamo del Perù",
        "el_name": "Βάλσαμο του Περού",
        "ru_name": "Перуанский бальзам",
        "de_essence": "Bronchialkatarrh mit eitrigem, reichlichem Auswurf, Heiserkeit und hartnäckigen Hautrhagaden.",
        "en_essence": "Bronchial catarrh with purulent copious expectoration, phthisis, and chronic indolent fissures.",
        "indications_de": ["Bronchitis mit eitrigem Sputum", "Rissige Hautrhagaden & Brustwarzen", "Chronischer Husten"],
        "indications_en": ["Purulent bronchitis and phthisis", "Cracked nipples and skin rhagades", "Debilitating chronic cough"],
        "keynotes_de": ["Dicker, eitriger, übelriechender Auswurf", "Husten reißt in der Luftröhre", "Schmerzhafte Fissuren an Händen und Mamillen"],
        "keynotes_en": ["Thick, yellowish-green purulent expectoration", "Raw burning in trachea on coughing", "Bleeding fissures of nipples and fingers"],
        "better_de": ["Warmes Einhüllen"],
        "better_en": ["Warm wraps"],
        "worse_de": ["Kälte", "Nachts"],
        "worse_en": ["Cold", "Night"],
        "diff": ["Stannum", "Silicea", "Graphites"],
        "sphere": ["Bronchien", "Schleimhäute", "Haut"],
        "tier": 3
    },
    {
        "id": "baryta-acetica",
        "latin": "Baryta acetica",
        "cat": "mineral",
        "de_name": "Bariumacetat",
        "en_name": "Barium Acetate",
        "es_name": "Acetato de bario",
        "fr_name": "Acétate de baryte",
        "it_name": "Acetato di bario",
        "el_name": "Οξικό βάριο",
        "ru_name": "Барита ацетика",
        "de_essence": "Zerebrale Arteriosklerose alter Menschen mit Gedächtnisverlust, Schwindel und Neigung zu Apoplexie.",
        "en_essence": "Cerebral arteriosclerosis of the aged with memory decay, confusion, and apoplectic threats.",
        "indications_de": ["Altersdemenz & Vergesslichkeit", "Arteriosklerotischer Schwindel", "Apoplex-Prophylaxe"],
        "indications_en": ["Senile dementia and loss of memory", "Arteriosclerotic vertigo", "Threatened apoplexy"],
        "keynotes_de": ["Vergessen von Eigennamen und Worten", "Unsicherer Gang alter Menschen", "Schweregefühl im Hinterkopf"],
        "keynotes_en": ["Total oblivion of familiar names", "Unsteady staggering gait in aged", "Heavy ache in occiput"],
        "better_de": ["Wärme", "Alleinsein"],
        "better_en": ["Warmth", "Being alone"],
        "worse_de": ["Kälte", "Gesellschaft", "Denken an Beschwerden"],
        "worse_en": ["Cold air", "Company", "Thinking of ailments"],
        "diff": ["Baryta carbonica", "Conium", "Anacardium"],
        "sphere": ["Gehirn", "Zerebrale Gefäße", "Geist"],
        "tier": 3
    },
    {
        "id": "baryta-iodata",
        "latin": "Baryta iodata",
        "cat": "mineral",
        "de_name": "Bariumiodid",
        "en_name": "Barium Iodide",
        "es_name": "Yoduro de bario",
        "fr_name": "Iodure de baryte",
        "it_name": "Ioduro di bario",
        "el_name": "Ιωδιούχο βάριο",
        "ru_name": "Барита иодата",
        "de_essence": "Chronisch vergrößerte, steinhart indurierte Mandeln und Halsdrüsen bei skrofulösen Kindern.",
        "en_essence": "Chronically hypertrophied, indurated tonsils and cervical glands in scrofulous, stunted children.",
        "indications_de": ["Tonsillenhypertrophie", "Chronische Lymphdrüsenschwellung", "Entwicklungsverzögerung"],
        "indications_en": ["Hypertrophy of tonsils", "Indurated lymph glands", "Stunted childhood development"],
        "keynotes_de": ["Mandeln füllen den ganzen Rachen aus", "Halsdrüsen steinhart geschwollen", "Ständige Erkältungsneigung"],
        "keynotes_en": ["Tonsils enlarged, impeding speech and swallowing", "Glands stony hard like knots", "Extreme susceptibility to colds"],
        "better_de": ["Warmes trockenes Wetter"],
        "better_en": ["Warm dry climate"],
        "worse_de": ["Feuchte Kälte", "Wetterwechsel"],
        "worse_en": ["Damp cold", "Weather changes"],
        "diff": ["Baryta carbonica", "Iodium", "Calcarea iodata"],
        "sphere": ["Tonsillen", "Lymphdrüsen", "Schilddrüse"],
        "tier": 2
    },
    {
        "id": "baryta-muriatica",
        "latin": "Baryta muriatica",
        "cat": "mineral",
        "de_name": "Bariumchlorid",
        "en_name": "Barium Chloride",
        "es_name": "Cloruro de bario",
        "fr_name": "Chlorure de baryte",
        "it_name": "Cloruro di bario",
        "el_name": "Χλωριούχο βάριο",
        "ru_name": "Барита муриатика",
        "de_essence": "Organische Gefäßerkrankungen, Bluthochdruck mit hohem diastolischem Druck, Aneurysmen und Arteriosklerose.",
        "en_essence": "Organic vascular disease, high blood pressure with high systolic/diastolic tension, and aneurysms.",
        "indications_de": ["Senile Hypertonie", "Aneurysma & Gefäßsklerose", "Chronische Mandelentzündung"],
        "indications_en": ["Senile hypertension", "Aneurysms and arterial degeneration", "Chronic tonsillitis"],
        "keynotes_de": ["Extrem hoher Blutdruck bei alten Patienten", "Pulsierendes Klopfen in den großen Arterien", "Schwäche der Beine mit Zittern"],
        "keynotes_en": ["Great arterial tension in old people", "Throbbing in abdominal aorta and neck", "Paresis of limbs with tremor"],
        "better_de": ["Aufrechtes Sitzen"],
        "better_en": ["Sitting quiet"],
        "worse_de": ["Kälte und Nässe", "Frühling"],
        "worse_en": ["Cold wet weather", "Springtime"],
        "diff": ["Plumbum", "Aurum", "Crataegus"],
        "sphere": ["Arterien", "Kreislaufsystem", "Lymphknoten"],
        "tier": 2
    },
    {
        "id": "bellis-perennis",
        "latin": "Bellis perennis",
        "cat": "plant",
        "de_name": "Gänseblümchen",
        "en_name": "Daisy",
        "es_name": "Margarita común",
        "fr_name": "Pâquerette",
        "it_name": "Pratolina / Margheritina",
        "el_name": "Μαργαρίτα η πολυετής",
        "ru_name": "Маргаритка многолетняя",
        "de_essence": "Boerickes großes Wund- und Gewebemittel: Trauma tiefer Organe, Muskelprellungen, Schmerzen nach Operationen und Kalttrinken bei Erhitzung.",
        "en_essence": "Boericke's premier traumatic remedy for deep tissue injury, pelvic surgery recovery, muscle soreness, and cold drinks when overheated.",
        "indications_de": ["Tiefe Gewebstraumata & Prellungen", "Rekonvaleszenz nach abdominalen Operationen", "Beschwerden durch Kalttrinken bei Hitze"],
        "indications_en": ["Deep muscle contusions and trauma", "Post-operative abdominal soreness", "Ill effects from cold drinks when overheated"],
        "keynotes_de": ["Gefühl von Zerschlagenheit in den Beckenorganen", "Unfähigkeit nach Prellung oder OP aufzustehen", "Boericke: 'Das Arnika für tiefe Organe'"],
        "keynotes_en": ["Sore bruised feeling in pelvic organs", "Stiffness and aching after injuries", "Boericke: 'The Arnica of deeper tissues'"],
        "better_de": ["Fortgesetzte Bewegung", "Sanfte Massage"],
        "better_en": ["Continued gentle motion", "Warm rubbing"],
        "worse_de": ["Kaltes Bad", "Kalttrinken bei Schweiß", "Erstbewegung"],
        "worse_en": ["Cold bath", "Cold drinks when hot", "Beginning motion"],
        "diff": ["Arnica", "Rhus tox", "Hypericum"],
        "sphere": ["Muskeln", "Bindegewebe", "Beckenorgane", "Gefäße"],
        "tier": 2
    },
    {
        "id": "berberis-aquifolium",
        "latin": "Berberis aquifolium",
        "cat": "plant",
        "de_name": "Mahonie",
        "en_name": "Oregon Grape / Mountain Grape",
        "es_name": "Uva de Oregón",
        "fr_name": "Mahonier à feuilles de houx",
        "it_name": "Maonia",
        "el_name": "Βερβερίς η οξυάκανθος (Μαχόνια)",
        "ru_name": "Магония падуболистная",
        "de_essence": "Boerickes bewährtestes Hauttonikum: reinigt den Teint, heilt Akne, Psoriasis, Schuppenflechte und chronische Ekzeme.",
        "en_essence": "Boericke's celebrated skin restorative: cleanses the complexion, clears acne, psoriasis, scales, and hepatic eruptions.",
        "indications_de": ["Akne vulgaris & unreine Haut", "Psoriasis & Schuppenflechte", "Chronische Ekzeme mit Krusten"],
        "indications_en": ["Acne vulgaris and blotchy complexion", "Psoriasis and scaly skin diseases", "Chronic dry crusty eczema"],
        "keynotes_de": ["Pustulöse Ausschläge im Gesicht und am Rücken", "Brennende Schuppen auf der Kopfhaut", "Bessert das Hautbild und stimuliert die Leber"],
        "keynotes_en": ["Pimples and pustules on face and shoulders", "Scaly eruptions extending to scalp", "Clears muddiness of skin and cleanses blood"],
        "better_de": ["Frische Luft"],
        "better_en": ["Fresh air"],
        "worse_de": ["Fettige Speisen", "Kaffee"],
        "worse_en": ["Fatty rich foods", "Stimulants"],
        "diff": ["Sarsaparilla", "Sulfur", "Graphites"],
        "sphere": ["Haut", "Talgdrüsen", "Leber"],
        "tier": 2
    },
    {
        "id": "bismuthum-subnitricum",
        "latin": "Bismuthum subnitricum",
        "cat": "mineral",
        "de_name": "Wismutnitrat",
        "en_name": "Bismuth Subnitrate",
        "es_name": "Subnitrato de bismuto",
        "fr_name": "Sous-nitrate de bismuth",
        "it_name": "Sottonitrato di bismuto",
        "el_name": "Υπονιτρικό βισμούθιο",
        "ru_name": "Висмута субнитрат",
        "de_essence": "Akute Gastralgie mit krampfartigem Magenschmerz; Erbrechen von Wasser, sobald es den Magen berührt und erwärmt wird.",
        "en_essence": "Severe gastralgia with intense stomach pain; vomits water as soon as it reaches the stomach and gets warm.",
        "indications_de": ["Schwere Gastritis & Magengeschwür", "Sofortiges Erbrechen von Wasser", "Sommerdiarrhoe von Kindern"],
        "indications_en": ["Severe gastritis and ulcer pain", "Vomiting water immediately when warm", "Summer diarrhea of children"],
        "keynotes_de": ["Wasser wird im Magen behalten, bis es warm wird, dann in großen Schwallen erbrochen", "Brennender, schneidender Druck im Magen", "Verlangen nach Gesellschaft; Angst vor dem Alleinsein"],
        "keynotes_en": ["Vomits water in large quantities the moment it gets warm in stomach", "Intense burning gastralgia", "Solitude is intolerable; clings to company"],
        "better_de": ["Kaltes Trinken (vorübergehend)", "Vorbeugen"],
        "better_en": ["Cold drinks (temporarily)", "Bending backward"],
        "worse_de": ["Sobald der Magen warm wird", "Alleinsein"],
        "worse_en": ["When stomach warms up", "Being alone"],
        "diff": ["Arsenicum album", "Phosphorus", "Nux vomica"],
        "sphere": ["Magen", "Schleimhaut", "Nervensystem"],
        "tier": 2
    },
    {
        "id": "blatta-orientalis",
        "latin": "Blatta orientalis",
        "cat": "animal",
        "de_name": "Küchenschabe / Kakerlake",
        "en_name": "Indian Cockroach",
        "es_name": "Cucaracha oriental",
        "fr_name": "Blatte orientale",
        "it_name": "Blatta orientale",
        "el_name": "Ανατολική κατσαρίδα",
        "ru_name": "Черный таракан",
        "de_essence": "Boerickes bewährtes Asthmamittel: akute Asthmaanfälle mit reichlichem Schleimrasseln, schwerer Erstickungsnot und Verschlimmerung bei feuchtem Wetter.",
        "en_essence": "Boericke's celebrated asthma remedy: acute asthmatic paroxysms with heavy bronchial rattling, suffocation, and rainy weather aggravation.",
        "indications_de": ["Asthma bronchiale", "Akute Bronchitis mit Schleimstau", "Dyspnoe bei Korpulenten"],
        "indications_en": ["Bronchial asthma", "Severe bronchitis with dyspnea", "Asthma in stout, corpulent patients"],
        "keynotes_de": ["Erstickungsanfall mit lautem Rasseln im Brustkorb", "Patient muss sich aufsetzen und nach Luft ringen", "Besonders wirksam bei feuchtem, regnerischem Wetter"],
        "keynotes_en": ["Suffocative cough with loud rattling in lungs", "Compelled to sit up in bed to breathe", "Great aggravation from rainy and damp weather"],
        "better_de": ["Aufrechtes Sitzen", "Auswurf"],
        "better_en": ["Sitting upright", "Free expectoration"],
        "worse_de": ["Feuchtes Wetter", "Regen", "Flaches Liegen"],
        "worse_en": ["Damp rainy weather", "Lying flat"],
        "diff": ["Ipecacuanha", "Arsenicum album", "Grindelia"],
        "sphere": ["Bronchien", "Lunge", "Atmungszentrum"],
        "tier": 2
    }
]

print(f"Loaded {len(REMEDIES_DATA)} Boericke definitions.")
