import { RawRemedy } from './buildRemedyUtils';

export const REMEDIES_PART3_DEFG: RawRemedy[] = [
  {
    id: 'digitalis-purpurea',
    latinName: 'Digitalis purpurea',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Roter Fingerhut',
      origin: 'Getrocknete Blätter des Roten Fingerhuts (Plantaginaceae).',
      essence: 'Extrem langsame, unregelmäßige Herztätigkeit (Bradykardie) mit plötzlichem Gefühl, das Herz würde stehenbleiben, wenn man sich bewegt.',
      mainIndications: ['Herzinsuffizienz & Bradykardie mit Arrhythmie', 'Herzbeschwerden mit plötzlicher Todesangst bei Bewegung', 'Ödeme & Wassersucht infolge von Herzschwäche'],
      keynotes: ['Puls extrem langsam, setzt bei jedem 3. oder 5. Schlag aus', 'Gefühl: „Wenn ich mich bewege, bleibt mein Herz stehen“', 'Aschgrauer, lehmfarbener Stuhl bei Leberstauung'],
      mindEmotional: 'Ängstlich, traurig, fürchtet plötzlichen Herztod.',
      modalitiesBetter: ['Absolute Ruhe', 'Aufrechtes Sitzen'],
      modalitiesWorse: ['Jede Bewegung & Lagewechsel', 'Aufstehen aus dem Sitzen', 'Kälte'],
      potenciesAndDosage: 'D4 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Herz & Erregungsleitung', 'Kreislauf', 'Nieren & Leber'],
      differentialRemedies: ['Crataegus', 'Cactus', 'Spigelia', 'Gelsemium (muss sich bewegen, damit Herz schlägt)'],
      searchKeywords: ['fingerhut', 'digitalis', 'herz', 'bradykardie', 'puls', 'herzstillstand', 'ödem']
    },
    en: {
      commonName: 'Purple Foxglove',
      origin: 'Dried leaves of Digitalis purpurea (Plantaginaceae).',
      essence: 'Extremely slow, irregular, intermittent pulse (bradycardia) with the terrifying sensation that the heart will stop beating if she/he moves.',
      mainIndications: ['Cardiac failure & bradycardia with irregular pulse', 'Cardiac distress with dread of sudden cessation on moving', 'Dropsy & edema resulting from heart failure'],
      keynotes: ['Pulse extremely slow, intermits every third or fifth beat', 'Fear that the heart will cease beating if he moves (opposite Gelsemium)', 'Ashy white or chalky clay-colored stools in liver congestion'],
      mindEmotional: 'Anxious, melancholic, dreads sudden death from heart failure.',
      modalitiesBetter: ['Absolute quiet rest', 'Sitting upright with head high'],
      modalitiesWorse: ['Any physical movement', 'Rising from sitting', 'Cold air'],
      potenciesAndDosage: 'D4 to C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Heart & Conduction System', 'Circulation', 'Kidneys & Liver'],
      differentialRemedies: ['Crataegus', 'Cactus', 'Spigelia', 'Gelsemium (must move to keep heart going)'],
      searchKeywords: ['foxglove', 'digitalis', 'heart', 'slow pulse', 'bradycardia', 'dropsy']
    },
    es: { commonName: 'Digital / Dedalera' },
    fr: { commonName: 'Digitale pourpre' },
    el: { commonName: 'Δακτυλίτιδα' },
    it: { commonName: 'Digitale purpurea' },
    ru: { commonName: 'Наперстянка пурпурная' }
  },
  {
    id: 'dioscorea-villosa',
    latinName: 'Dioscorea villosa',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Wilde Yamswurzel',
      origin: 'Frische Wurzel der Wilden Yamswurzel (Dioscoreaceae).',
      essence: 'Gallen- und Bauchkoliken, die sich paradoxerweise durch Strecken und Weit-nach-hinten-Beugen des Körpers bessern (Gegenteil von Colocynthis).',
      mainIndications: ['Gallenkolik & Magen-Darm-Krämpfe', 'Nierenkolik & schmerzhafte Blähungen', 'Angina pectoris mit Ausstrahlung'],
      keynotes: ['Bauchschmerz bessert sich prompt durch Überstrecken nach hinten', 'Schmerzen strahlen vom Nabel in Brust, Arme und Beine aus', 'Ständiges schmerzhaftes Drehen und Winden im Bauch'],
      mindEmotional: 'Reizbar, nervös, stöhnt vor Schmerzen.',
      modalitiesBetter: ['Strecken & Rückwärtsbeugen', 'Aufrechtes Stehen', 'Im Freien'],
      modalitiesWorse: ['Zusammenkrümmen & Vornüberbeugen', 'Liegen', 'Nach dem Essen'],
      potenciesAndDosage: 'D4 bis C30. Bei Koliken D6 alle 15–30 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Bauchorgane & Gallenblase', 'Peripheres Nervensystem'],
      differentialRemedies: ['Colocynthis (besser durch Zusammenkrümmen)', 'Magnesia phosphorica', 'Chamomilla'],
      searchKeywords: ['yamswurzel', 'kolik', 'rückwärtsbeugen', 'krämpfe', 'galle', 'dioscorea']
    },
    en: {
      commonName: 'Wild Yam',
      origin: 'Fresh root of Dioscorea villosa (Dioscoreaceae).',
      essence: 'Violent abdominal and biliary colics relieved paradoxically by stretching out and bending backward (direct opposite of Colocynthis).',
      mainIndications: ['Biliary colic & spasmodic intestinal cramps', 'Renal colic & flatulent colic', 'Angina-like chest pains radiating from abdomen'],
      keynotes: ['Pains promptly relieved by stretching erect or bending backward', 'Pains radiate outward from navel into chest, arms, and legs', 'Continuous writhing and twisting agony in bowels'],
      mindEmotional: 'Irritable, nervous, groans aloud from colic.',
      modalitiesBetter: ['Stretching out & bending backward', 'Standing erect', 'Open air'],
      modalitiesWorse: ['Doubling up & bending forward', 'Lying down flat', 'After eating'],
      potenciesAndDosage: 'D4 to C30 / 6C, 30C. In colic D6 every 15–30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Abdominal Viscera & Biliary Ducts', 'Spinal Nerves'],
      differentialRemedies: ['Colocynthis (better bending double)', 'Magnesia phosphorica', 'Chamomilla'],
      searchKeywords: ['wild yam', 'colic', 'bending backward', 'cramps', 'gallbladder', 'dioscorea']
    },
    es: { commonName: 'Ñame silvestre' },
    fr: { commonName: 'Igname sauvage' },
    el: { commonName: 'Διοσκορέα' },
    it: { commonName: 'Dioscorea' },
    ru: { commonName: 'Диоскорея мохнатая / Дикий ямс' }
  },
  {
    id: 'drosera-rotundifolia',
    latinName: 'Drosera rotundifolia',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Rundblättriger Sonnentau',
      origin: 'Ganze frische Pflanze des Sonnentaus (Droseraceae).',
      essence: 'Das Hauptmittel für krampfhaften Keuchhusten: Bellende, anfallsartige Hustenstöße, die so schnell aufeinanderfolgen, dass der Patient kaum Luft holen kann; Erwachen sofort nach dem Hinlegen um Mitternacht.',
      mainIndications: ['Keuchhusten (Pertussis) & krampfhafter Reizhusten', 'Kitzelhusten mit Würgen und Erbrechen von Schleim', 'Heiserkeit bei Sängern und Rednern mit tiefer Stimme'],
      keynotes: ['Hustenanfälle folgen so rasch, dass der Patient fast erstickt', 'Husten beginnt sofort, sobald der Kopf das Kissen berührt', 'Muss beim Husten die Brust oder den Bauch mit beiden Händen festhalten', 'Verschlimmerung nach Mitternacht'],
      mindEmotional: 'Misstrauisch, eigensinnig, unruhig bei Hustenanfällen.',
      modalitiesBetter: ['Aufrechtes Sitzen', 'Frische kühle Luft'],
      modalitiesWorse: ['Sofort beim Hinlegen', 'Nach Mitternacht', 'Wärme des Bettes', 'Sprechen & Lachen'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Keuchhusten C30: 3–5 Globuli abends und bei Hustenanfall.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Kehlkopf, Trachea & Bronchien', 'Zwerchfell & Atemzentrum'],
      differentialRemedies: ['Ipecacuanha', 'Cuprum metallicum', 'Spongia tosta', 'Coccus cacti'],
      searchKeywords: ['sonnentau', 'drosera', 'keuchhusten', 'krampfhusten', 'hinlegen', 'mitternacht', 'ersticken']
    },
    en: {
      commonName: 'Round-Leaved Sundew',
      origin: 'Whole fresh flowering plant of Drosera rotundifolia (Droseraceae).',
      essence: 'The supreme whooping cough and spasmodic paroxysmal cough remedy: violent barking paroxysms following in such rapid succession that the patient can scarcely catch breath; cough begins the instant the head touches the pillow.',
      mainIndications: ['Whooping cough (pertussis) & severe paroxysmal cough', 'Tickling spasmodic cough with retching and vomiting of mucus', 'Chronic hoarseness with deep hollow voice in vocalists'],
      keynotes: ['Paroxysms follow in rapid succession, patient nearly suffocates', 'Cough begins immediately upon lying down and head touching pillow', 'Must hold the chest and abdomen firmly with both hands while coughing', 'Violent aggravation after midnight'],
      mindEmotional: 'Suspicious of friends, obstinate, fretful during suffocative coughing.',
      modalitiesBetter: ['Sitting erect in bed', 'Cool open air'],
      modalitiesWorse: ['Immediately upon lying down', 'After midnight', 'Warmth of bed', 'Speaking & laughing'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In whooping cough C30 at bedtime and after paroxysms.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Larynx, Trachea & Bronchial Tree', 'Diaphragm & Respiratory Reflex'],
      differentialRemedies: ['Ipecacuanha', 'Cuprum metallicum', 'Spongia tosta', 'Coccus cacti'],
      searchKeywords: ['sundew', 'drosera', 'whooping cough', 'spasmodic cough', 'lying down worse', 'midnight']
    },
    es: { commonName: 'Drosera / Rocío del sol' },
    fr: { commonName: 'Droséra à feuilles rondes' },
    el: { commonName: 'Δροσέρα' },
    it: { commonName: 'Drosera' },
    ru: { commonName: 'Росянка круглолистная' }
  },
  {
    id: 'dulcamara',
    latinName: 'Solanum dulcamara',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Bittersüß',
      origin: 'Frische, vor der Blüte gesammelte Stängel von Solanum dulcamara (Solanaceae).',
      essence: 'Beschwerden infolge von Kälte und Nässe (plötzlicher Temperaturabfall, nasses Sitzen auf kaltem Boden, Regenwetter im Spätsommer/Herbst); Blasenkatarrh, Gelenkschmerzen und Warzen.',
      mainIndications: ['Erkältungen & Durchfall nach Nässe und Kälte', 'Akute Zystitis nach Sitzen auf kaltem Boden', 'Rheumatische Gelenk- und Muskelschmerzen bei Wetterumschwung', 'Weiche, fleischige Warzen an den Händen'],
      keynotes: ['Alle Beschwerden ausgelöst durch Wechsel von warmem zu kalt-feuchtem Wetter', 'Schmerzen bessern sich durch fortgesetzte Bewegung und Wärme', 'Krustige Ekzeme im Gesicht und an den Händen, die bei Kälte jucken'],
      mindEmotional: 'Ungeduldig, herrschsüchtig, zänkisch.',
      modalitiesBetter: ['Trockene Wärme', 'Fortgesetzte Bewegung'],
      modalitiesWorse: ['Nasskaltes Wetter & Regen', 'Sitzen auf feuchtem Boden', 'Herbst & Temperatursturz'],
      potenciesAndDosage: 'D6, D12, C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Schleimhäute & Blase', 'Gelenke & Muskulatur', 'Haut'],
      differentialRemedies: ['Rhus toxicodendron', 'Natrium sulfuricum', 'Calcarea carbonica'],
      searchKeywords: ['bittersüß', 'dulcamara', 'nasskalt', 'wetterwechsel', 'blasenentzündung', 'rheuma', 'warzen']
    },
    en: {
      commonName: 'Bittersweet / Woody Nightshade',
      origin: 'Fresh young stems of Solanum dulcamara (Solanaceae).',
      essence: 'Ailments from exposure to damp cold (sudden drop in temperature, sitting on cold wet ground, rainy late summer days); acute cystitis, rheumatism, and fleshy warts.',
      mainIndications: ['Catarrhs & diarrhea provoked by damp cold weather', 'Acute cystitis after sitting on chilled stone/ground', 'Rheumatic joint and muscular stiffness aggravated by wet weather', 'Smooth fleshy warts on palms and hands'],
      keynotes: ['Every symptom brought on by change from warm to cold damp air', 'Pains and stiffness relieved by gentle continuous motion and dry heat', 'Crusted scabby eczema that itches violently in damp cold'],
      mindEmotional: 'Domineering, impatient, quarrelsome.',
      modalitiesBetter: ['Dry warm air', 'Continuous gentle motion'],
      modalitiesWorse: ['Cold wet weather & rain', 'Sitting on damp cold ground', 'Autumn season'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Mucous Membranes & Urinary Bladder', 'Joints & Muscles', 'Skin'],
      differentialRemedies: ['Rhus toxicodendron', 'Natrium sulfuricum', 'Calcarea carbonica'],
      searchKeywords: ['bittersweet', 'dulcamara', 'damp cold', 'wet weather', 'cystitis', 'rheumatism', 'warts']
    },
    es: { commonName: 'Dulcamara' },
    fr: { commonName: 'Douce-amère' },
    el: { commonName: 'Γλυκύπικρος' },
    it: { commonName: 'Dulcamara' },
    ru: { commonName: 'Паслен сладко-горький / Дулькамара' }
  },
  {
    id: 'echinacea-angustifolia',
    latinName: 'Echinacea angustifolia',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Schmalblättriger Sonnenhut',
      origin: 'Frische ganze blühende Pflanze und Wurzel von Echinacea angustifolia (Asteraceae).',
      essence: 'Das homöopathische Immun- und Blutschutzmittel bei septischen Prozessen, Abszessen, Furunkeln, Lymphangitis und Infektanfälligkeit.',
      mainIndications: ['Septische Infektionen & Wundinfektionen', 'Rezidivierende Furunkel, Karbunkel & Abszesse', 'Grippale Infekte zur Immunstimulation', 'Insektenbisse mit starker Entzündungsreaktion'],
      keynotes: ['Müdigkeit, Zerschlagenheit und Schüttelfrost bei bakteriellen Infekten', 'Übelriechende Wundabsonderungen', 'Taubheitsgefühl und Kribbeln auf Zunge und Lippen nach Einnahme'],
      mindEmotional: 'Müde, apathisch, verlangsamt bei fieberhafter Infektion.',
      modalitiesBetter: ['Ruhe', 'Wärme'],
      modalitiesWorse: ['Körperliche Anstrengung', 'Kälte'],
      potenciesAndDosage: 'Urtinktur (Ø) oder D1 bis D6. Bei akuten Infekten 3x täglich 10 Tropfen oder 5 Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Immunsystem & Lymphatisches System', 'Blut', 'Haut & Weichteile'],
      differentialRemedies: ['Pyrogenium', 'Baptisia', 'Arnica', 'Hepar sulfuris'],
      searchKeywords: ['sonnenhut', 'echinacea', 'immunsystem', 'abszess', 'furunkel', 'infekt', 'blutreinigung']
    },
    en: {
      commonName: 'Narrow-Leaved Coneflower',
      origin: 'Fresh whole plant and root of Echinacea angustifolia (Asteraceae).',
      essence: 'Homeopathic blood cleanser and immune restorative for septic processes, abscesses, carbuncles, lymphangitis, and recurring infectious states.',
      mainIndications: ['Septic states, pyemia, and infected wounds', 'Recurrent boils, carbuncles, and lymphangitis', 'Immune stimulation in acute viral and bacterial fevers', 'Insect stings with rapid inflamed swelling'],
      keynotes: ['Profound aching exhaustion and chilliness in septic infections', 'Foul offensive discharges from infected ulcers', 'Characteristic tingling and numbness of tongue and lips upon taking'],
      mindEmotional: 'Tired, confused, depressed during toxic infection.',
      modalitiesBetter: ['Rest', 'Warmth'],
      modalitiesWorse: ['Physical exertion', 'Cold exposure'],
      potenciesAndDosage: 'Mother tincture (Q) or 1X to 6X / D1 to D6. In acute infections 3 times daily 10 drops or 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Immune & Reticuloendothelial System', 'Blood & Lymph', 'Skin & Soft Tissues'],
      differentialRemedies: ['Pyrogenium', 'Baptisia', 'Arnica', 'Hepar sulfuris'],
      searchKeywords: ['coneflower', 'echinacea', 'immune', 'abscess', 'boils', 'sepsis', 'infections']
    },
    es: { commonName: 'Equinácea de hoja estrecha' },
    fr: { commonName: 'Échinacée à feuilles étroites' },
    el: { commonName: 'Εχινάκεια' },
    it: { commonName: 'Echinacea angustifolia' },
    ru: { commonName: 'Эхинацея узколистная' }
  },
  {
    id: 'eupatorium-perfoliatum',
    latinName: 'Eupatorium perfoliatum',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Wasserhanf / Knochenheil',
      origin: 'Frische blühende oberirdische Teile des Wasserhanfs (Asteraceae).',
      essence: 'Das klassische Grippemittel mit tiefen, unerträglichen Knochenschmerzen, als wären die Knochen zerbrochen; Patient kann wegen der Schmerzen nicht still liegen; großer Durst auf kaltes Wasser vor dem Frost.',
      mainIndications: ['Echte Virusgrippe (Influenza) mit zerschlagenen Knochen', 'Fieberhafte Infekte mit tiefen Gliederschmerzen', 'Schmerzhafter Husten mit Wundheit in der Luftröhre'],
      keynotes: ['Knochen tun weh, als wären sie in Stücke geschlagen', 'Großer Durst auf eiskaltes Wasser schon vor dem Schüttelfrost', 'Große Ruhelosigkeit: Muss sich ständig bewegen, obwohl jede Bewegung schmerzt', 'Gelb belegte Zunge und bitteres Erbrechen von Galle'],
      mindEmotional: 'Stöhnt vor Knochenschmerzen, ängstlich, ruhelos.',
      modalitiesBetter: ['Auf Händen und Knien ruhen', 'Wärme', 'Nach dem Schwitzen'],
      modalitiesWorse: ['Kälte & Kaltluft', 'Um 07:00 bis 09:00 Uhr morgens', 'Bewegung'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Grippebeginn C30 alle 2–3 Stunden.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Knochen & Skelettsystem', 'Muskulatur', 'Atmungsorgane', 'Magen-Darm'],
      differentialRemedies: ['Gelsemium (müde, schläfrig, zittrig)', 'Bryonia (will absolut ruhig liegen)', 'Rhus tox'],
      searchKeywords: ['wasserhanf', 'grippe', 'knochenschmerz', 'knochenheil', 'schüttelfrost', 'durst', 'fieber']
    },
    en: {
      commonName: 'Boneset / Thoroughwort',
      origin: 'Fresh blooming herb of Eupatorium perfoliatum (Asteraceae).',
      essence: 'The supreme influenza remedy characterized by excruciating, bruised bone pains as if bones were broken into pieces; patient cannot lie still from agony; intense thirst for cold water before chills.',
      mainIndications: ['Epidemic influenza with agonizing aching in all bones', 'Febrile catarrhs with deep aching skeletal pain', 'Painful cough with raw soreness throughout trachea'],
      keynotes: ['Aching in bones so severe it feels as if they were broken', 'Intense thirst for ice-cold water before and during the chill', 'Great restlessness: constantly shifts position though motion hurts', 'Yellow-coated tongue and bilious vomiting after chill'],
      mindEmotional: 'Moans and groans aloud from bone agony, restless.',
      modalitiesBetter: ['Resting on hands and knees', 'Warmth', 'Onset of perspiration'],
      modalitiesWorse: ['Cold drafts', '7:00 to 9:00 AM', 'Motion'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In flu onset C30 every 2–3 hours.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Periosteum & Bones', 'Muscles & Fibrous Tissues', 'Respiratory Tract', 'Gastrointestinal'],
      differentialRemedies: ['Gelsemium (dull, heavy, drowsy)', 'Bryonia (desires absolute quiet)', 'Rhus tox'],
      searchKeywords: ['boneset', 'eupatorium', 'flu', 'influenza', 'broken bones', 'bone pain', 'thirst before chill']
    },
    es: { commonName: 'Eupatorio / Consuelda de pantano' },
    fr: { commonName: 'Eupatoire perfoliée' },
    el: { commonName: 'Ευπατόριο' },
    it: { commonName: 'Eupatorio' },
    ru: { commonName: 'Посконник пронзеннолистный' }
  },
  {
    id: 'euphrasia-officinalis',
    latinName: 'Euphrasia officinalis',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Augentrost',
      origin: 'Ganze frische blühende Pflanze des Augentrosts (Orobanchaceae).',
      essence: 'Das klassische Augenmittel: Scharfe, brennende, ätzende Tränenflüssigkeit mit starker Lichtscheu, gepaart mit mildem, nicht wundmachendem Nasenschnupfen (exaktes Gegenteil von Allium cepa).',
      mainIndications: ['Akute Konjunktivitis & Bindehautentzündung', 'Heuschnupfen mit brennenden roten Augen & Lichtempfindlichkeit', 'Lidrandentzündung (Blepharitis) & Tränenfluss'],
      keynotes: ['Tränen sind scharf, ätzend und röten die Wangen', 'Nasensekret ist mild und verursacht keine Wundheit', 'Augen brennen wie Feuer und vertragen kein Licht', 'Ständiges Blinzeln und Zukneifen der Augenlider'],
      mindEmotional: 'Schläfrig, reizbar durch das brennende Augenlicht.',
      modalitiesBetter: ['Dunkles Zimmer', 'Kaltes Auswaschen der Augen', 'Im Freien'],
      modalitiesWorse: ['Helles Licht & Sonnenlicht', 'Wind & Zugluft', 'Im warmen Zimmer'],
      potenciesAndDosage: 'D6, D12, C30. Akut: 3–5 Globuli alle 1–2 Stunden.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Augen & Konjunktiven', 'Tränenwege & Lider', 'Nasenschleimhaut'],
      differentialRemedies: ['Allium cepa (Tränen mild, Nase scharf)', 'Apis mellifica', 'Pulsatilla'],
      searchKeywords: ['augentrost', 'euphrasia', 'augen', 'konjunktivitis', 'tränen', 'bindehautentzündung', 'lichtscheu', 'heuschnupfen']
    },
    en: {
      commonName: 'Eyebright',
      origin: 'Whole fresh blooming plant of Euphrasia officinalis (Orobanchaceae).',
      essence: 'The supreme ocular remedy: acrid, scalding, corrosive lacrimation with marked photophobia, paired with bland, non-irritating nasal coryza (exact opposite of Allium cepa).',
      mainIndications: ['Acute conjunctivitis & allergic red eye', 'Hay fever with burning lacrimation & photophobia', 'Blepharitis & agglutinated eyelids in morning'],
      keynotes: ['Acrid burning tears excoriate the cheeks and eyelids', 'Nasal discharge is mild, bland, non-irritating', 'Eyes burn like hot coals; intolerable photophobia', 'Frequent compulsive winking and blinking of lids'],
      mindEmotional: 'Drowsy, irritable from light pain in eyes.',
      modalitiesBetter: ['Darkened room', 'Cold water eye baths', 'Open fresh air'],
      modalitiesWorse: ['Bright sunlight and glare', 'Wind and draft', 'Warm stuffy room'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. Acute: 3–5 pellets every 1–2 hours.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Eyes & Conjunctiva', 'Lacrimal Glands & Lids', 'Nasal Mucosa'],
      differentialRemedies: ['Allium cepa (bland tears, acrid nose)', 'Apis mellifica', 'Pulsatilla'],
      searchKeywords: ['eyebright', 'euphrasia', 'conjunctivitis', 'tears', 'photophobia', 'red eyes', 'hay fever']
    },
    es: { commonName: 'Eufrasia' },
    fr: { commonName: 'Euphraise officinale' },
    el: { commonName: 'Ευφρασία' },
    it: { commonName: 'Eufrasia' },
    ru: { commonName: 'Очанка лекарственная' }
  },
  {
    id: 'ferrum-metallicum',
    latinName: 'Ferrum metallicum',
    categoryKey: 'mineral',
    importanceTier: 1,
    de: {
      commonName: 'Metallisches Eisen',
      origin: 'Reines elementares Eisen (Fe).',
      essence: 'Pseudo-Plethora bei Anämie: Aschfahles, blasses Gesicht, das bei der geringsten Aufregung oder Anstrengung plötzlich feuerrot erglüht; schmerzlose Durchfälle während des Essens.',
      mainIndications: ['Eisenmangelanämie mit Schwäche & Herzklopfen', 'Schulter-Arm-Syndrom (besonders linke Schulter)', 'Schmerzlose Durchfälle unmittelbar während der Mahlzeit'],
      keynotes: ['Plötzliches feuerrotes Erröten des ansonsten blassen Gesichts bei Erregung', 'Schmerzloser wässriger Durchfall treibt vom Esstisch weg', 'Schmerzen bessern sich durch langsames, ruhiges Umhergehen'],
      mindEmotional: 'Reizbar bei Widerspruch, überempfindlich gegen das geringste Geräusch.',
      modalitiesBetter: ['Langsames, gleichmäßiges Gehen', 'Wärme'],
      modalitiesWorse: ['Ruhe & Stillstand', 'Geringste Anstrengung', 'Nachts im Bett'],
      potenciesAndDosage: 'D6, D12, C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Blut & Erythropoese', 'Blutgefäße & Kreislauf', 'Schultergelenke'],
      differentialRemedies: ['China', 'Ferrum phosphoricum', 'Pulsatilla', 'Natrium muriaticum'],
      searchKeywords: ['eisen', 'anämie', 'blässe', 'erröten', 'schulter', 'durchfall beim essen', 'ferrum']
    },
    en: {
      commonName: 'Metallic Iron',
      origin: 'Pure elemental iron.',
      essence: 'False plethora in profound anemia: ashen, deathly pale face that suddenly flushes fiery red upon slightest emotion or exertion; painless diarrhea while eating.',
      mainIndications: ['Iron deficiency anemia with weakness & palpitations', 'Left shoulder-arm periarthritis and joint pain', 'Painless lienteric diarrhea driving from dining table'],
      keynotes: ['Sudden fiery flushing of pale face upon least emotional excitement', 'Painless watery diarrhea occurring immediately while eating', 'Aching pains and stiffness markedly relieved by slow, gentle walking'],
      mindEmotional: 'Irritable at slightest contradiction, intolerant of slightest rustling noise.',
      modalitiesBetter: ['Slow, gentle, continuous walking', 'Warmth'],
      modalitiesWorse: ['Absolute quiet rest', 'Slightest exertion', 'Night in bed'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Blood & Hemoglobin', 'Vascular System & Flushing', 'Shoulder Joints'],
      differentialRemedies: ['China', 'Ferrum phosphoricum', 'Pulsatilla', 'Natrium muriaticum'],
      searchKeywords: ['iron', 'ferrum', 'anemia', 'flushing', 'pale', 'shoulder pain', 'diarrhea while eating']
    },
    es: { commonName: 'Hierro metálico' },
    fr: { commonName: 'Fer métallique' },
    el: { commonName: 'Σίδηρος' },
    it: { commonName: 'Ferro metallico' },
    ru: { commonName: 'Железо металлическое' }
  },
  {
    id: 'ferrum-phosphoricum',
    latinName: 'Ferrum phosphoricum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Eisenphosphat',
      origin: 'Reines Eisen(III)-phosphat (FePO4 · 4H2O).',
      essence: 'Das Erstmittel im 1. Stadium aller fieberhaften Entzündungen: Mäßiges Fieber (bis 38,8 °C), schleichender Beginn, rotes Gesicht bei Hitzegefühl, Neigung zu Nasenbluten und Otitis media.',
      mainIndications: ['1. Stadium von Erkältungen, Bronchitis & fieberhaften Infekten', 'Akute Otitis media (Mittelohrentzündung) im Anfangsstadium', 'Nasenbluten (Epistaxis) bei Kindern während Infekten', 'Schonendes Antiphlogistikum für Kinder und Senioren'],
      keynotes: ['Mäßiges Fieber mit weichem, vollem Puls', 'Rote Flecken auf den Wangen, die bei Anstrengung pulsieren', 'Kopfschmerzen bessern sich durch kalte Umschläge', 'Schonende Wirkung ohne die Heftigkeit von Aconitum oder Belladonna'],
      mindEmotional: 'Leicht erregbar, gesellig, gesprächig, aber schnell erschöpft.',
      modalitiesBetter: ['Kalte Umschläge auf den Kopf', 'Sanfte, langsame Bewegung'],
      modalitiesWorse: ['Wärme & warmes Zimmer', 'Zwischen 04:00 und 06:00 Uhr morgens', 'Rasche Bewegung'],
      potenciesAndDosage: 'Akut: D6, D12, C30 (Schüßler-Salz Nr. 3). Bei Infektbeginn alle 30–60 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Blutgefäße & Kapillaren', 'Mittelohr & Trommelfell', 'Atemwege & Lunge'],
      differentialRemedies: ['Aconitum (plötzlich, trocken, Angst)', 'Belladonna (glühend rot, pochend)', 'Gelsemium'],
      searchKeywords: ['eisenphosphat', 'ferrum phosphoricum', 'fieber', 'anfangsstadium', 'mittelohrentzündung', 'nasenbluten', 'erkältung']
    },
    en: {
      commonName: 'Phosphate of Iron',
      origin: 'Pure ferric phosphate.',
      essence: 'The premier remedy for the first stage of all febrile inflammations: moderate fever (under 39 °C / 102 °F), gradual onset, flushed cheeks, tendency to epistaxis, and early otitis media.',
      mainIndications: ['First stage of catarrhs, bronchitis & febrile colds', 'Early stage of acute otitis media in children', 'Epistaxis (nosebleeds) during acute fever', 'Gentle anti-inflammatory for children and the frail'],
      keynotes: ['Moderate fever with soft, full, compressible pulse', 'Circumscribed red flushes on cheeks pulsing with exertion', 'Congestive headache relieved by cold applications', 'Gentle onset lacking the explosive violence of Aconite or Belladonna'],
      mindEmotional: 'Sensitive, cheerful, talkative, but tires easily during fever.',
      modalitiesBetter: ['Cold local compresses on head', 'Gentle slow motion'],
      modalitiesWorse: ['Warmth & heated rooms', '4:00 to 6:00 AM', 'Rapid jarring motion'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6X, 12X. At cold onset every 30–60 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Blood Vessels & Capillary Circulation', 'Middle Ear & Tympanum', 'Respiratory Mucosa'],
      differentialRemedies: ['Aconitum (sudden, panic, dry)', 'Belladonna (hot throbbing sweat)', 'Gelsemium'],
      searchKeywords: ['iron phosphate', 'ferrum phosphoricum', 'fever', 'first stage', 'ear infection', 'nosebleed', 'colds']
    },
    es: { commonName: 'Fosfato de hierro' },
    fr: { commonName: 'Phosphate de fer' },
    el: { commonName: 'Φωσφορικός σίδηρος' },
    it: { commonName: 'Fosfato di ferro' },
    ru: { commonName: 'Фосфорнокислое железо' }
  },
  {
    id: 'galphimia-glauca',
    latinName: 'Galphimia glauca',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Kleiner Goldregen / Galphimia',
      origin: 'Getrocknete Blätter und Blüten von Galphimia glauca (Malpighiaceae).',
      essence: 'Das moderne homöopathische Antiallergikum: Heuschnupfen, allergisches Asthma, juckende Augen und Fließschnupfen durch Pollenbelastung.',
      mainIndications: ['Saisonaler Heuschnupfen (Pollinosis) & allergische Rhinitis', 'Allergische Konjunktivitis mit Juckreiz', 'Allergisches Asthma & Reizhusten'],
      keynotes: ['Brennender und juckender Tränen- und Nasenfluss', 'Häufige Niesanfälle bei Pollenflug', 'Schleimhautschwellung der Nase'],
      mindEmotional: 'Müde, nervös gereizt durch den ständigen Allergiezustand.',
      modalitiesBetter: ['In geschlossenen Räumen', 'Kühle Umschläge'],
      modalitiesWorse: ['Im Freien bei Pollenflug', 'Sonniges, windiges Wetter'],
      potenciesAndDosage: 'D4, D6, D12. In der Pollensaison 3x täglich 5 Globuli (prophylaktisch 4 Wochen vor Saisonbeginn).',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Nasenschleimhaut', 'Augen & Bindehaut', 'Bronchien'],
      differentialRemedies: ['Luffa operculata', 'Allium cepa', 'Euphrasia', 'Sabadilla'],
      searchKeywords: ['galphimia', 'heuschnupfen', 'allergie', 'pollen', 'niesen', 'augenjucken']
    },
    en: {
      commonName: 'Golden Thryallis',
      origin: 'Dried leaves and flowers of Galphimia glauca (Malpighiaceae).',
      essence: 'The modern homeopathic antiallergic: seasonal hay fever, allergic bronchial asthma, itching red eyes, and profuse sneezing from pollen.',
      mainIndications: ['Seasonal hay fever (pollinosis) & allergic rhinitis', 'Allergic conjunctivitis with intense ocular itching', 'Allergic asthma & spasmodic sneezing fits'],
      keynotes: ['Burning, itching watery discharge from eyes and nose', 'Paroxysmal violent sneezing fits on outdoor exposure', 'Edematous congestion of nasal turbinates'],
      mindEmotional: 'Fatigued, irritable from allergic exhaustion.',
      modalitiesBetter: ['Indoors with closed windows', 'Cold compresses'],
      modalitiesWorse: ['Outdoors during peak pollen count', 'Sunny breezy days'],
      potenciesAndDosage: 'D4, D6, D12 / 4X to 6X. 3 times daily 5 pellets during pollen season.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Nasal Mucosa', 'Conjunctiva', 'Bronchial Mucosa'],
      differentialRemedies: ['Luffa operculata', 'Allium cepa', 'Euphrasia', 'Sabadilla'],
      searchKeywords: ['galphimia', 'hay fever', 'allergy', 'pollen', 'sneezing', 'itching eyes']
    },
    es: { commonName: 'Galphimia / Flor de estrella' },
    fr: { commonName: 'Galphimia glauca' },
    el: { commonName: 'Γαλφίμια' },
    it: { commonName: 'Galphimia glauca' },
    ru: { commonName: 'Гальфимия сизая' }
  },
  {
    id: 'gelsemium-sempervirens',
    latinName: 'Gelsemium sempervirens',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Falscher Jasmin / Gelber Jasmin',
      origin: 'Frischer Wurzelstock des Gelben Jasmins (Gelsemiaceae).',
      essence: 'Die drei großen „D“: Dull, Drowsy, Dizzy (benommen, schläfrig, schwindlig). Lähmige Schwäche, zittrige Glieder, schwere Augenlider, Durstlosigkeit und Erwartungsangst mit Durchfall vor Prüfungen.',
      mainIndications: ['Echte Sommer- & Wintergrippe mit schwerer Erschöpfung', 'Prüfungsangst mit Zittrigkeit & Durchfall', 'Okzipitaler Kopfschmerz, der von Nacken über den Kopf zieht', 'Lähmungen & Muskelschwäche nach Virusinfekten'],
      keynotes: ['Schwere, herabfallende Augenlider (kann Augen kaum offen halten)', 'Zittern der Hände und Knie vor Schwäche oder Angst', 'Völlige Durstlosigkeit trotz hohem Fieber', 'Reichliches Wasserlassen bringt sofortige Linderung der Kopfschmerzen'],
      mindEmotional: 'Apathisch, will seine Ruhe haben, feige, zittert vor Prüfungen und öffentlichen Auftritten.',
      modalitiesBetter: ['Reichliches Urinieren', 'Frische Luft', 'Bücken'],
      modalitiesWorse: ['Erwartungsangst & Aufregung', 'Schwüles, feuchtes Wetter', 'Um 10:00 Uhr morgens'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Vor Prüfungen C30 am Vorabend und 1 Std. vorher.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Motorisches Nervensystem & Rückenmark', 'Gehirn & Augenlider', 'Kreislauf'],
      differentialRemedies: ['Argentum nitricum (hastig, klaustrophobisch)', 'Bryonia', 'Eupatorium perfoliatum', 'Baptisia'],
      searchKeywords: ['gelber jasmin', 'gelsemium', 'grippe', 'prüfungsangst', 'schwere augenlider', 'zittern', 'durstlos', 'nackenkopfschmerz']
    },
    en: {
      commonName: 'Yellow Jasmine',
      origin: 'Fresh rootstock of Gelsemium sempervirens (Gelsemiaceae).',
      essence: 'The classic "3 Ds": Dull, Drowsy, Dizzy. Paralytic heaviness, trembling limbs, drooping heavy eyelids, complete lack of thirst, and paralyzing stage fright with diarrhea before exams.',
      mainIndications: ['Summer & winter flu with deep muscular prostration', 'Paralyzing stage fright & test anxiety with bowel looseness', 'Occipital headache ascending from cervical spine over vertex', 'Post-viral paresis and muscular weakness'],
      keynotes: ['Heavy, drooping ptosis of eyelids; can scarcely keep eyes open', 'Trembling of hands, knees, and tongue from sheer weakness or fright', 'Complete absence of thirst despite high fever', 'Profuse clear urination brings immediate relief of headache'],
      mindEmotional: 'Dull, listless, desires quiet, lacks courage, trembles from anticipation.',
      modalitiesBetter: ['Profuse urination', 'Open air', 'Bending forward'],
      modalitiesWorse: ['Anticipation & emotional excitement', 'Humid muggy heat', '10:00 AM'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. For exam fright C30 prior to event.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Motor Nervous System & Spinal Axis', 'Brain & Ocular Muscles', 'Vascular System'],
      differentialRemedies: ['Argentum nitricum (hurried, agitated)', 'Bryonia', 'Eupatorium perfoliatum', 'Baptisia'],
      searchKeywords: ['yellow jasmine', 'gelsemium', 'flu', 'stage fright', 'heavy eyelids', 'trembling', 'thirstless', 'occipital headache']
    },
    es: { commonName: 'Jazmín amarillo' },
    fr: { commonName: 'Jasmin de Caroline' },
    el: { commonName: 'Γελσέμιο' },
    it: { commonName: 'Gelsomino della Carolina' },
    ru: { commonName: 'Гельземиум / Желтый жасмин' }
  },
  {
    id: 'glonoinum',
    latinName: 'Glonoinum / Nitroglycerinum',
    categoryKey: 'mineral',
    importanceTier: 1,
    de: {
      commonName: 'Nitroglycerin / Sprengöl',
      origin: 'Alkoholische Lösung von Nitroglycerin (C3H5(NO3)3).',
      essence: 'Gewaltige arterielle Blutwelle zum Kopf mit hämmerndem, pochendem Berstungskopfschmerz im Takt des Pulses; Sonnenstich, Hitzschlag und Orientierungsverlust.',
      mainIndications: ['Sonnenstich & akuter Hitzschlag', 'Pochende Hypertonie-Kopfschmerzen mit rotem Kopf', 'Orientierungsverlust in bekannten Straßen'],
      keynotes: ['Kopfschmerz pulsiert synchron mit jedem Herzschlag', 'Gefühl, der Kopf würde unter dem Druck explodieren', 'Patient verirrt sich in ihm wohlbekannten Straßen', 'Verträgt absolut keine Kopfbedeckung und keine Sonnenhitze'],
      mindEmotional: 'Verwirrt, erkennt bekannte Straßen nicht mehr, ängstlich.',
      modalitiesBetter: ['Kälte & Eisumschläge auf den Kopf', 'Aufrechtes Sitzen'],
      modalitiesWorse: ['Sonneneinstrahlung & Sommerhitze', 'Alkohol', 'Erschütterung & Hinlegen'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Sonnenstich D6 alle 15–30 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Gehirngefäße & Arterien', 'Herz-Kreislauf-System'],
      differentialRemedies: ['Belladonna (weitere Pupillen, feuchte Hitze)', 'Melilotus', 'Natrium carbonicum'],
      searchKeywords: ['nitroglycerin', 'glonoinum', 'sonnenstich', 'pochen', 'kopfschmerz', 'orientierung', 'hitzschlag']
    },
    en: {
      commonName: 'Nitroglycerine',
      origin: 'Alcoholic solution of nitroglycerine.',
      essence: 'Violent arterial surge of blood to head with bursting, throbbing headache synchronized with every pulse beat; sunstroke, heat apoplexy, and loss of orientation.',
      mainIndications: ['Sunstroke & acute heat exhaustion', 'Congestive throbbing hypertensive headache with scarlet face', 'Loss of orientation in well-known familiar streets'],
      keynotes: ['Headache pulsates and hammers synchronously with every heartbeat', 'Sensation as if skull would explode from internal arterial pressure', 'Loses way and becomes completely disoriented in familiar streets', 'Cannot bear the slightest hat pressure or sun rays on head'],
      mindEmotional: 'Confused, loses sense of locality and time, alarmed.',
      modalitiesBetter: ['Cold air and ice compresses on head', 'Sitting erect'],
      modalitiesWorse: ['Direct sun exposure & radiant heat', 'Alcohol', 'Jarring & lying flat'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In sunstroke D6 every 15–30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Cerebral Circulation & Arteries', 'Cardiovascular System'],
      differentialRemedies: ['Belladonna (dilated pupils, moist heat)', 'Melilotus', 'Natrium carbonicum'],
      searchKeywords: ['nitroglycerine', 'glonoinum', 'sunstroke', 'throbbing headache', 'disorientation', 'heatstroke']
    },
    es: { commonName: 'Nitroglicerina' },
    fr: { commonName: 'Nitroglycérine' },
    el: { commonName: 'Νιτρογλυκερίνη' },
    it: { commonName: 'Nitroglicerina' },
    ru: { commonName: 'Нитроглицерин / Глоноин' }
  },
  {
    id: 'graphites',
    latinName: 'Graphites naturalis',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Reißblei / Graphit',
      origin: 'Natürlicher kristallisierter Kohlenstoff / Graphit.',
      essence: 'Das große Haut- und Stoffwechselmittel: Dicke, klebrige, honigartige Krustenabsonderungen an Ohrläppchen, Augenlidern und Beugen; Kälteempfindlichkeit, Neigung zu Übergewicht und quälende Obstipation.',
      mainIndications: ['Ekzeme & Rhagaden mit honigartiger klebriger Flüssigkeit', 'Rissige Mundwinkel & Retroaurikulär-Ekzeme (hinter den Ohren)', 'Chronische atonische Obstipation mit Schleimüberzug', 'Brüchige, verformte Finger- und Zehennägel'],
      keynotes: ['Sekret aus Hautrissen ist zäh, klebrig und honiggelb', 'Neigung zu Fettleibigkeit, Frostigkeit und Verstopfung', 'Musik bringt zum Weinen', 'Extreme Berührungsempfindlichkeit der Narben'],
      mindEmotional: 'Träge, unentschlossen, ängstlich, weinerlich bei Musik.',
      modalitiesBetter: ['Im Dunkeln', 'An der frischen Luft', 'Nach dem Essen'],
      modalitiesWorse: ['Kälte & Zugluft', 'Nachts', 'Während und nach den Menses'],
      potenciesAndDosage: 'D6 bis C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Haut & Hautfalten (Ohren, Beugen)', 'Stoffwechsel & Magen-Darm', 'Nägel & Haare'],
      differentialRemedies: ['Petroleum', 'Mezereum', 'Calcarea carbonica', 'Pulsatilla'],
      searchKeywords: ['graphit', 'ekzem', 'honigsekret', 'ohrhinter', 'risse', 'rhagaden', 'verstopfung', 'nägel']
    },
    en: {
      commonName: 'Black Lead / Pure Graphite',
      origin: 'Natural crystallized mineral carbon.',
      essence: 'The supreme dermatological and metabolic polychrest: thick, sticky, honey-like exudations from cracks behind ears, eyelids, and flexures; chilly, sluggish, obese, and severely constipated.',
      mainIndications: ['Eczema & fissures oozing thick honey-like fluid', 'Cracked corners of mouth & retroauricular fissures', 'Chronic atonic constipation with mucus-coated stools', 'Deformed, thick, crumbling finger- and toenails'],
      keynotes: ['Exudation from cracks is sticky, glutinous, and honey-like', 'Triad of chilliness, obesity, and delayed menses/constipation', 'Listening to music provokes weeping and sadness', 'Sensitive hypertrophic scars and keloids'],
      mindEmotional: 'Hesitant, indecisive, apprehensive, weeps on hearing music.',
      modalitiesBetter: ['Dark quiet room', 'Open cool air', 'After eating'],
      modalitiesWorse: ['Cold drafts', 'Nighttime', 'During and after menses'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Skin & Folds (Behind Ears, Flexures)', 'Metabolism & Digestive Tract', 'Nails & Hair'],
      differentialRemedies: ['Petroleum', 'Mezereum', 'Calcarea carbonica', 'Pulsatilla'],
      searchKeywords: ['graphites', 'black lead', 'honey discharge', 'behind ears', 'fissures', 'constipation', 'brittle nails']
    },
    es: { commonName: 'Grafito' },
    fr: { commonName: 'Graphite' },
    el: { commonName: 'Γραφίτης' },
    it: { commonName: 'Grafite' },
    ru: { commonName: 'Графит' }
  }
];

console.log('REMEDIES_PART3_DEFG defined with count:', REMEDIES_PART3_DEFG.length);
