import { RawRemedy } from './buildRemedyUtils';

export const REMEDIES_PART4_HIJ: RawRemedy[] = [
  {
    id: 'hamamelis-virginiana',
    latinName: 'Hamamelis virginiana',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Virginische Zaubernuss',
      origin: 'Frische Rinde der Wurzeln und Zweige von Hamamelis virginiana (Hamamelidaceae).',
      essence: 'Venöse Stauung mit passiven, dunklen, schmerzlosen venösen Blutungen; schmerzhafte Krampfadern und blutende Hämorrhoiden mit Zerschlagenheitsgefühl.',
      mainIndications: ['Krampfadern (Varikose) mit Entzündung (Phlebitis)', 'Blutende, schmerzhafte Hämorrhoiden', 'Passive dunkle venöse Blutungen (z.B. Nasenbluten, Uterusblutung)'],
      keynotes: ['Dunkles, nicht geronnenes venöses Blut', 'Gefühl von Zerschlagenheit und Wundheit in den Venen', 'Starke Schmerzhaftigkeit bei geringster Berührung der Venen'],
      mindEmotional: 'Mürrisch, deprimiert, will in Ruhe gelassen werden.',
      modalitiesBetter: ['Ruhe', 'Hochlagern der Beine'],
      modalitiesWorse: ['Wärme & feuchte Luft', 'Berührung', 'Bewegung'],
      potenciesAndDosage: 'D3 bis D12. 3x täglich 5 Tropfen oder Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Venöses Blutgefäßsystem', 'Rektum & Hämorrhoiden', 'Uterus & Schleimhäute'],
      differentialRemedies: ['Aesculus', 'Collinsonia', 'Pulsatilla', 'Millefolium'],
      searchKeywords: ['zaubernuss', 'hamamelis', 'krampfadern', 'hämorrhoiden', 'venen', 'blutung', 'phlebitis']
    },
    en: {
      commonName: 'Witch Hazel',
      origin: 'Fresh bark of root and twigs of Hamamelis virginiana (Hamamelidaceae).',
      essence: 'Venous engorgement with passive, dark, non-coagulating venous hemorrhages; tender inflamed varicose veins and bleeding hemorrhoids with sore bruised feeling.',
      mainIndications: ['Varicose veins with phlebitis & heaviness', 'Bleeding, sore, aching hemorrhoids', 'Passive dark venous hemorrhages from nose or uterus'],
      keynotes: ['Dark, non-coagulable, passive venous bleeding', 'Bruised soreness and tension in affected veins', 'Exquisite tenderness of varicose vessels to light touch'],
      mindEmotional: 'Peevish, irritable, depressed by physical weakness.',
      modalitiesBetter: ['Rest with legs elevated', 'Cool open air'],
      modalitiesWorse: ['Warm humid air', 'Touch', 'Motion and jarring'],
      potenciesAndDosage: 'D3 to D12 / 3X to 12X. 3 times daily 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Venous Vascular System', 'Rectum & Hemorrhoidal Veins', 'Uterine Mucosa'],
      differentialRemedies: ['Aesculus', 'Collinsonia', 'Pulsatilla', 'Millefolium'],
      searchKeywords: ['witch hazel', 'hamamelis', 'varicose veins', 'hemorrhoids', 'venous bleed', 'phlebitis']
    },
    es: { commonName: 'Hamamelis' },
    fr: { commonName: 'Hamamélis de Virginie' },
    el: { commonName: 'Αμαμελίδα' },
    it: { commonName: 'Amamelide' },
    ru: { commonName: 'Гамамелис виргинский' }
  },
  {
    id: 'helleborus-niger',
    latinName: 'Helleborus niger',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Schwarze Nieswurz / Christrose',
      origin: 'Frischer Wurzelstock der Christrose (Ranunculaceae).',
      essence: 'Tiefe geistige Abstumpfung und Apathie bei Hirnhautentzündung (Meningismus) oder Hydrozephalus: starrt ins Leere, rollt den Kopf im Kissen hin und her.',
      mainIndications: ['Meningismus & Hirnödem nach Infekten', 'Akuter Hydrozephalus bei Kindern', 'Wassersucht (Anasarka) mit spärlichem schwarzem Urin'],
      keynotes: ['Rollen des Kopfes im Kissen von einer Seite zur anderen', 'Reaktionslosigkeit: Sieht nichts, hört nichts, versteht nichts', 'Dunkler Urin wie Kaffeesatz'],
      mindEmotional: 'Apathisch, stuporös, unansprechbar, starrt stumm vor sich hin.',
      modalitiesBetter: ['Ruhe', 'Wärme'],
      modalitiesWorse: ['Von 16:00 bis 20:00 Uhr', 'Entblößen', 'Anstrengung'],
      potenciesAndDosage: 'D6 bis C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Gehirn & Meningen', 'Nieren & Flüssigkeitshaushalt'],
      differentialRemedies: ['Apis mellifica', 'Zincum metallicum', 'Hyoscyamus', 'Opium'],
      searchKeywords: ['christrose', 'helleborus', 'meningitis', 'hirnödem', 'kopfrollen', 'stupor', 'apathie']
    },
    en: {
      commonName: 'Black Hellebore / Christmas Rose',
      origin: 'Fresh rootstock of Helleborus niger (Ranunculaceae).',
      essence: 'Profound sensorial apathy and stupor in meningitis or hydrocephalus: stares blankly into space, rolling head from side to side in pillow.',
      mainIndications: ['Meningeal irritation & post-infectious cerebral edema', 'Acute hydrocephalus in children', 'General anasarca with dark coffee-ground urine'],
      keynotes: ['Rolling head rhythmically from side to side in pillow', 'Complete sensorial torpor: sees, hears, and tastes nothing', 'Dark, scanty urine containing coffee-ground sediment'],
      mindEmotional: 'Apathetic, stuporous, silent, stares vacantly into space.',
      modalitiesBetter: ['Rest', 'Warmth'],
      modalitiesWorse: ['4:00 to 8:00 PM', 'Uncovering', 'Physical exertion'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Brain & Meninges', 'Kidneys & Serous Cavities'],
      differentialRemedies: ['Apis mellifica', 'Zincum metallicum', 'Hyoscyamus', 'Opium'],
      searchKeywords: ['black hellebore', 'helleborus', 'meningitis', 'head rolling', 'stupor', 'coffee ground urine']
    },
    es: { commonName: 'Heléboro negro' },
    fr: { commonName: 'Hellébore noir / Rose de Noël' },
    el: { commonName: 'Ελλέβορος' },
    it: { commonName: 'Elleboro nero' },
    ru: { commonName: 'Морозник черный' }
  },
  {
    id: 'hepar-sulfuris',
    latinName: 'Hepar sulphuris calcareum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Kalkschwefelleber',
      origin: 'Verbindung aus Austernschalenkalk und reinem Schwefelblumen nach Hahnemann.',
      essence: 'Das Hauptmittel für Eiterungen und Abszesse mit stechenden Splitterschmerzen; extreme Kälteüberempfindlichkeit (selbst das Herausstrecken einer Hand aus dem Bett verursacht Husten) und ungeduldig-cholerisches Gemüt.',
      mainIndications: ['Akute eitrige Tonsillitis & Pseudokrupp (bellender Husten nach Kälte)', 'Abszesse, Furunkel, Phlegmonen & eiternde Wunden', 'Schmerzhafte Otitis media mit stinkendem Eiterfluss', 'Sinusitis mit stechenden Schmerzen'],
      keynotes: ['Stechende Schmerzen wie von einem Holz- oder Glassplitter', 'Extremste Kälteempfindlichkeit: verträgt nicht die geringste Entblößung', 'Eiter riecht stechend nach altem Käse', 'Husten beginnt oder verschlimmert sich durch das geringste Frösteln'],
      mindEmotional: 'Cholerisch, aufbrausend, extrem gereizt, neigt zu Wutanfällen und Gewalttätigkeit.',
      modalitiesBetter: ['Feuchte Wärme & dicke Einhüllung (Kopf warm einpacken)', 'Nach dem Essen'],
      modalitiesWorse: ['Kalter, trockener Wind & Zugluft', 'Geringste Entblößung', 'Berührung der eiternden Stelle'],
      potenciesAndDosage: 'Zur Einschmelzung/Reifung: D6. Zur Rückbildung/Resorption: D12, C30.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Haut & Weichteile (Eiterung)', 'Atmungsorgane & Kehlkopf', 'Lymphknoten & Mandeln'],
      differentialRemedies: ['Silicea (chronischer Eiter)', 'Mercurius solubilis', 'Aconitum', 'Spongia tosta'],
      searchKeywords: ['kalkschwefelleber', 'hepar sulfuris', 'eiter', 'abszess', 'splittergefühl', 'krupp', 'mandeln', 'kälteempfindlich']
    },
    en: {
      commonName: 'Hahnemann’s Calcium Sulfide',
      origin: 'Calcined mixture of oyster shell calcium and sulfur flowers.',
      essence: 'The supreme suppurative remedy for abscesses with sharp splinter-like stitching pains; extreme hypersensitivity to cold drafts (uncovering a hand brings coughing fits); violent snappish anger.',
      mainIndications: ['Suppurative tonsillitis & croupy barking cough from cold dry air', 'Abscesses, furuncles, carbuncles, and suppurating wounds', 'Acute otitis media with foul cheese-smelling discharge', 'Painful acute maxillary sinusitis'],
      keynotes: ['Stitching pains like a sharp wood or glass splinter', 'Extreme sensitivity to cold air; uncovering the hand causes coughing', 'Discharges smell offensive like old decayed cheese', 'Cough aggravated by slightest chilly draft'],
      mindEmotional: 'Violently angry, snappish, impatient, impulsive, intolerant of contradiction.',
      modalitiesBetter: ['Moist heat & wrapping up warmly (especially head)', 'After eating'],
      modalitiesWorse: ['Cold dry winds & drafts', 'Slightest uncovering of body', 'Touch on inflamed spot'],
      potenciesAndDosage: 'To promote suppuration: D6. To abort and resorb: D12, C30 / 6C, 30C.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Skin & Cellular Tissue (Suppuration)', 'Respiratory Tract & Larynx', 'Lymph Glands & Tonsils'],
      differentialRemedies: ['Silicea (chronic pus)', 'Mercurius solubilis', 'Aconitum', 'Spongia tosta'],
      searchKeywords: ['calcium sulfide', 'hepar sulfuris', 'suppuration', 'abscess', 'splinter pain', 'croup', 'quinsy', 'chilly']
    },
    es: { commonName: 'Hépar sulfur' },
    fr: { commonName: 'Foie de soufre calcaire' },
    el: { commonName: 'Ήπαρ θείου' },
    it: { commonName: 'Hepar sulfur' },
    ru: { commonName: 'Гепар сульфур / Серная печень' }
  },
  {
    id: 'hydrastis-canadensis',
    latinName: 'Hydrastis canadensis',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Kanadische Gelbwurz / Goldsiegelwurzel',
      origin: 'Frischer Wurzelstock der Goldsiegelwurzel (Ranunculaceae).',
      essence: 'Dicke, zähe, gelbliche, fadenziehende Schleimabsonderungen an allen Schleimhäuten (Nase, Rachen, Magen, Zervix); chronische Obstipation ohne Drang.',
      mainIndications: ['Chronische Sinusitis mit fadenziehendem gelbem Schleim', 'Postnasal-Drip-Syndrom (Schleim läuft hinten in den Rachen)', 'Atonische Obstipation nach Laxanzien-Missbrauch', 'Gastritis mit Leeregefühl in der Magengrube'],
      keynotes: ['Schleim ist zäh wie Gummi und zieht lange Fäden', 'Großes Schwäche- und Leeregefühl im Epigastrium', 'Zunge groß, schlaff, gelb belegt mit Zahneindrücken'],
      mindEmotional: 'Depressiv, weinerlich, verliert die Hoffnung auf Genesung.',
      modalitiesBetter: ['Ruhe', 'Wärme'],
      modalitiesWorse: ['Einatmen kalter Luft', 'Missbrauch von Abführmitteln', 'Nacht'],
      potenciesAndDosage: 'D4 bis C30. 2-3x täglich 5 Globuli.',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Schleimhäute (Nase, Rachen, Uterus)', 'Magen-Darm-Trakt', 'Gallenwege'],
      differentialRemedies: ['Kalium bichromicum (Fadenziehend)', 'Pulsatilla', 'Nux vomica'],
      searchKeywords: ['gelbwurz', 'hydrastis', 'fadenziehend', 'sinusitis', 'schleim', 'postnasaldrip', 'verstopfung']
    },
    en: {
      commonName: 'Golden Seal',
      origin: 'Fresh rootstock of Hydrastis canadensis (Ranunculaceae).',
      essence: 'Thick, tenacious, yellowish, stringy, ropy mucous discharges from all mucous membranes (nasopharynx, stomach, cervix); atonic constipation without urge.',
      mainIndications: ['Chronic sinusitis with ropy stringy yellow mucus', 'Postnasal drip dropping down into posterior pharynx', 'Atonic constipation following laxative abuse', 'Chronic gastritis with sinking empty sensation at pit of stomach'],
      keynotes: ['Discharges are thick, tenacious, and can be pulled into long strings', 'Gone, faint, empty feeling at epigastrium', 'Tongue broad, flabby, yellow-coated, showing imprint of teeth'],
      mindEmotional: 'Depressed, despondent, sure of incurable disease.',
      modalitiesBetter: ['Rest', 'Warmth'],
      modalitiesWorse: ['Inhaling cold dry air', 'Laxative abuse', 'Nighttime'],
      potenciesAndDosage: 'D4 to C30 / 6C, 30C. 2-3 times daily 5 pellets.',
      defaultTagesdosis: '2-3 times daily 5 pellets',
      sphereOfAction: ['Mucous Membranes (Nasopharynx, Cervix)', 'Gastrointestinal Canal', 'Biliary Ducts'],
      differentialRemedies: ['Kalium bichromicum (ropy stringy)', 'Pulsatilla', 'Nux vomica'],
      searchKeywords: ['golden seal', 'hydrastis', 'stringy mucus', 'sinusitis', 'postnasal drip', 'constipation']
    },
    es: { commonName: 'Hidrastis / Sello de oro' },
    fr: { commonName: 'Hydraste du Canada' },
    el: { commonName: 'Υδραστίδα' },
    it: { commonName: 'Idraste' },
    ru: { commonName: 'Гидрастис / Желтокорень канадский' }
  },
  {
    id: 'hyoscyamus-niger',
    latinName: 'Hyoscyamus niger',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Schwarzes Bilsenkraut',
      origin: 'Ganze frische blühende Pflanze des Bilsenkrauts (Solanaceae).',
      essence: 'Eifersuchtswahn, Schamlosigkeit (entblößt den Körper), Misstrauen (fürchtet vergiftet zu werden) und trockener Kitzelhusten, der sofort beim Hinlegen beginnt und beim Aufsitzen aufhört.',
      mainIndications: ['Trockener nächtlicher Kitzelhusten (besser beim Aufsitzen)', 'Eifersuchtspsychosen, Delirium & Manie', 'Krämpfe, Muskelzuckungen & Tics bei Kindern', 'Schamlosigkeit bei Demenz'],
      keynotes: ['Trockener Husten zwingt zum Aufsitzen im Bett (hört beim Aufsitzen auf)', 'Neigung sich nackt auszuziehen und Genitalien zu entblößen', 'Weigert sich Nahrung oder Medizin einzunehmen aus Furcht vor Vergiftung', 'Zucken der Sehnen und Muskeln (Subsultus tendinum)'],
      mindEmotional: 'Verzehrt von Eifersucht, verdächtigt Partner, schamlos, lacht unpassend.',
      modalitiesBetter: ['Aufrechtes Sitzen im Bett', 'Wärme'],
      modalitiesWorse: ['Flaches Hinlegen', 'Nachts im Bett', 'Während der Menses', 'Eifersucht'],
      potenciesAndDosage: 'D6 bis C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Psyche', 'Atmungsorgane (Kehlkopf & Husten)', 'Muskeln & Motorik'],
      differentialRemedies: ['Belladonna (heiß, rot)', 'Stramonium (Lichtangst, Raserei)', 'Lachesis (Eifersucht)'],
      searchKeywords: ['bilsenkraut', 'hyoscyamus', 'husten', 'aufsitzen', 'eifersucht', 'schamlos', 'vergiftungsangst', 'zuckung']
    },
    en: {
      commonName: 'Black Henbane',
      origin: 'Whole fresh blooming plant of Hyoscyamus niger (Solanaceae).',
      essence: 'Jealous delusion, shameless exhibitionism (strips off clothing), suspicious fear of being poisoned, and dry tickling cough starting on lying flat and stopping on sitting up.',
      mainIndications: ['Nocturnal dry tickling cough relieved by sitting up', 'Jealous delirium, paranoia, and mania', 'Muscular twitchings, subsultus tendinum, and tics', 'Shameless nudity in senile dementia'],
      keynotes: ['Dry nocturnal cough relieved instantly upon sitting erect in bed', 'Inclination to strip off clothes and expose genitals', 'Refuses all food or medicine from fear of being poisoned', 'Twitching of muscles and tendons (subsultus tendinum)'],
      mindEmotional: 'Raving jealousy, suspicious of family, shameless, obscenely loquacious.',
      modalitiesBetter: ['Sitting erect in bed', 'Warmth'],
      modalitiesWorse: ['Lying down flat', 'Night in bed', 'During menses', 'Jealousy'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Cerebrospinal Axis & Mind', 'Respiratory Tract & Cough Reflex', 'Motor Nerves'],
      differentialRemedies: ['Belladonna (hot throbbing)', 'Stramonium (fears darkness, terrors)', 'Lachesis (jealousy)'],
      searchKeywords: ['henbane', 'hyoscyamus', 'cough sitting up', 'jealousy', 'shameless', 'poison fear', 'twitching']
    },
    es: { commonName: 'Beleño negro' },
    fr: { commonName: 'Jusquiame noire' },
    el: { commonName: 'Υοσκύαμος' },
    it: { commonName: 'Giusquiamo nero' },
    ru: { commonName: 'Белена черная' }
  },
  {
    id: 'hypericum-perforatum',
    latinName: 'Hypericum perforatum',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Echtes Johanniskraut',
      origin: 'Ganze frische blühende Pflanze des Johanniskrauts (Hypericaceae).',
      essence: 'Das „Arnika der Nerven“: Schießende, stechende Schmerzen nach Quetschung oder Verletzung nervenreicher Gewebe (Fingerkuppen, Zehen, Steißbein, Zähne); Phantomschmerzen und Tetanusprophylaxe.',
      mainIndications: ['Eingeklemmte Fingerkuppen & Zehenquetschungen', 'Steißbeinsturz & Kokzygodynie nach Sturz', 'Schießende Schmerzen nach Zahnextraktionen & Nervenverletzungen', 'Nervenschmerzen nach Operationen & Amputationen (Phantomschmerz)'],
      keynotes: ['Schmerz schießt wie ein Blitz entlang des Nervenverlaufs zentripetal nach oben', 'Verletzungen von extrem nervenreichen Zonen (Fingerspitzen, Nägel, Steißbein)', 'Extreme Berührungsempfindlichkeit der verletzten Stelle'],
      mindEmotional: 'Deprimiert nach Nervenverletzungen, Gedächtnisschwäche nach Schädel-Hirn-Trauma.',
      modalitiesBetter: ['Ruhiges Liegen', 'Kopf nach hinten beugen'],
      modalitiesWorse: ['Kälte & feuchtes Wetter', 'Berührung & Erschütterung', 'Nebel'],
      potenciesAndDosage: 'Akut: D6, D12, C30, C200. Sofort nach Nervenquetschung C30 wiederholt einnehmen.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Periphere Nerven & Rückenmark', 'Finger- & Zehenspitzen', 'Steißbein & Wirbelsäule'],
      differentialRemedies: ['Arnica (Muskel- und Weichteiltrauma)', 'Ledum (Stichwunden)', 'Ruta (Knochenhaut)'],
      searchKeywords: ['johanniskraut', 'hypericum', 'nervenverletzung', 'steißbein', 'fingerquetschung', 'phantomschmerz', 'zahnextraktion']
    },
    en: {
      commonName: 'St. John’s Wort',
      origin: 'Whole fresh blooming plant of Hypericum perforatum (Hypericaceae).',
      essence: 'The "Arnica of the Nerves": shooting, darting, excruciating pains following injury to nerve-rich areas (fingertips, toes, coccyx, dental sockets); phantom limb pain and prevention of lockjaw.',
      mainIndications: ['Crushed fingertips, toes, and matrix injuries', 'Coccygeal trauma & tailbone fall injury (coccydynia)', 'Shooting lancinating pains after dental surgery & nerve laceration', 'Post-amputation phantom nerve pains'],
      keynotes: ['Pains shoot upward like lightning along the nerve tract toward trunk', 'Injuries to nerve-abundant anatomical parts (fingertips, spinal cord, coccyx)', 'Intolerable sensitivity of the injured nerve terminal to slightest touch'],
      mindEmotional: 'Melancholic after severe nerve trauma, mental dullness following concussion.',
      modalitiesBetter: ['Lying quiet', 'Bending head backward'],
      modalitiesWorse: ['Cold damp air & fog', 'Touch & slightest jar', 'Weather changes'],
      potenciesAndDosage: 'Acute: D6, D12, C30, C200. Immediately after nerve injury C30 repeated as needed.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Peripheral Sensory Nerves', 'Spinal Cord & Coccyx', 'Fingertips & Nail Beds'],
      differentialRemedies: ['Arnica (blunt muscle bruise)', 'Ledum (puncture wounds)', 'Ruta (periosteum)'],
      searchKeywords: ['st johns wort', 'hypericum', 'nerve injury', 'coccyx', 'crushed fingers', 'phantom pain', 'shooting pain']
    },
    es: { commonName: 'Hipérico / Hierba de San Juan' },
    fr: { commonName: 'Millepertuis perforé' },
    el: { commonName: 'Βάλσαμο / Υπερικό' },
    it: { commonName: 'Iperico' },
    ru: { commonName: 'Зверобой продырявленный' }
  },
  {
    id: 'ignatia-amara',
    latinName: 'Strychnos ignatii',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Ignazbohne',
      origin: 'Getrocknete Samen der Ignazbohne (Loganiaceae).',
      essence: 'Das Hauptmittel für akuten Kummer, Liebeskummer, Schock, Enttäuschung und Hysterie: Paradoxe, widersprüchliche Symptome (z.B. Halsschmerz bessert sich beim Schlucken fester Nahrung), Globusgefühl (Kloß im Hals) und häufiges tiefes Seufzen.',
      mainIndications: ['Akuter Kummer & Trauer nach Verlust eines geliebten Menschen', 'Liebeskummer, Enttäuschung & hysterische Weinkrämpfe', 'Globusgefühl (Kloß im Hals beim Schlucken)', 'Paradoxe Beschwerden (Kopfschmerz bessert sich durch Bücken, Halsschmerz beim Kauen)'],
      keynotes: ['Häufiges, unwillkürliches tiefes Seufzen und Schluchzen', 'Kloßgefühl im Hals, das durch Leerschlucken nicht vergeht', 'Stimmungsschwankungen: schlägt blitzartig von Weinen in unpassendes Lachen um', 'Beschwerden bessern sich durch Ablenkung'],
      mindEmotional: 'Verschlossener stiller Kummer, weint heimlich, verträgt keinen Trost (Trost verschlimmert).',
      modalitiesBetter: ['Beim Essen fester Nahrung', 'Durch Ablenkung & Lagewechsel', 'Wärme'],
      modalitiesWorse: ['Kummer, Sorgen & Enttäuschung', 'Trost & Zuspruch', 'Kaffee & Tabakrauch', 'Morgens'],
      potenciesAndDosage: 'Akut: C30, C200. Bei akutem Kummer/Schock 3–5 Globuli C30.',
      defaultTagesdosis: '1–2 Gaben à 3–5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Emotionen', 'Hals & Ösophagus', 'Vegetatives Nervensystem'],
      differentialRemedies: ['Natrium muriaticum (chronischer Kummer)', 'Phosphoricum acidum (apathische Erschöpfung)', 'Pulsatilla (sucht Trost)'],
      searchKeywords: ['ignazbohne', 'ignatia', 'kummer', 'liebeskummer', 'trauer', 'seufzen', 'kloß im hals', 'globus', 'widersprüchlich']
    },
    en: {
      commonName: 'St. Ignatius Bean',
      origin: 'Dried seeds of Strychnos ignatii (Loganiaceae).',
      essence: 'The supreme remedy for acute grief, romantic heartbreak, emotional shock, and hysteria: paradoxical contradictory symptoms (e.g. sore throat relieved by swallowing solids), globus hystericus (lump in throat), and involuntary deep sighing.',
      mainIndications: ['Acute grief & bereavement after loss of loved one', 'Romantic heartbreak & emotional disappointment', 'Globus hystericus (sensation of lump in throat)', 'Paradoxical symptoms (headache relieved by stooping, throat pain relieved by eating solids)'],
      keynotes: ['Frequent involuntary deep sighing and sobbing', 'Persistent lump sensation in throat not relieved by empty swallowing', 'Rapid mood swings: weeping abruptly changes to inappropriate laughter', 'Marked improvement of complaints from mental distraction'],
      mindEmotional: 'Silent brooding grief, weeps in secret, aggravated by attempts at consolation.',
      modalitiesBetter: ['While swallowing solid food', 'Mental distraction', 'Warmth'],
      modalitiesWorse: ['Grief & emotional shock', 'Consolation', 'Coffee & tobacco smoke', 'Morning'],
      potenciesAndDosage: 'Acute: C30, C200. In acute bereavement C30: 3–5 pellets.',
      defaultTagesdosis: '1–2 doses of 3–5 pellets',
      sphereOfAction: ['Emotional Nervous System & Brain', 'Throat & Esophagus', 'Autonomic Reflexes'],
      differentialRemedies: ['Natrium muriaticum (chronic held grief)', 'Phosphoricum acidum (apathetic burnout)', 'Pulsatilla (craves consolation)'],
      searchKeywords: ['ignatia', 'st ignatius bean', 'grief', 'heartbreak', 'sighing', 'lump in throat', 'globus', 'consolation worse']
    },
    es: { commonName: 'Haba de San Ignacio' },
    fr: { commonName: 'Fève de Saint-Ignace' },
    el: { commonName: 'Ιγνάτιο' },
    it: { commonName: 'Fava di Sant’Ignazio' },
    ru: { commonName: 'Игнация / Боб святого Игнатия' }
  },
  {
    id: 'iodium',
    latinName: 'Iodium purum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Reines Iod',
      origin: 'Elementares reines Iod (I2).',
      essence: 'Heißhunger mit paradoxer Abmagerung: Der Patient isst riesige Mengen und verliert dennoch an Gewicht; extreme innere Hitze, Schilddrüsenüberfunktion und ständige Ruhelosigkeit.',
      mainIndications: ['Hyperthyreose & Morbus Basedow mit Gewichtsverlust', 'Heißhunger mit rapider Abmagerung', 'Harte Lymphdrüsen- und Schilddrüsenschwellungen (Struma)', 'Krupphusten bei warmblütigen Kindern'],
      keynotes: ['Isst pausenlos und magert dennoch zusehends ab', 'Muss ständig in Bewegung sein, um innere Unruhe zu bewältigen', 'Extreme Hitzeintoleranz (sucht ständig kalte Luft und kaltes Wasser)', 'Besserung aller Gemütssymptome während und nach dem Essen'],
      mindEmotional: 'Ängstlich, gehetzt, gewalttätige Impulse, muss ständig beschäftigt sein.',
      modalitiesBetter: ['Während und nach dem Essen', 'Kälte & kaltes Baden', 'Frische Luft'],
      modalitiesWorse: ['Wärme & warmes Zimmer', 'Auf nüchternen Magen', 'Ruhe'],
      potenciesAndDosage: 'D6 bis C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Schilddrüse & Hormonsystem', 'Stoffwechsel & Lymphdrüsen', 'Atmungsorgane'],
      differentialRemedies: ['Natrium muriaticum', 'Tuberculinum', 'Abrotanum', 'Lachesis'],
      searchKeywords: ['iod', 'schilddrüse', 'abmagerung', 'heißhunger', 'hitze', 'unruhe', 'struma', 'hyperthyreose']
    },
    en: {
      commonName: 'Pure Iodine',
      origin: 'Pure elemental iodine.',
      essence: 'Canine hunger with paradoxically progressive emaciation: eats enormous amounts yet wastes away; intense internal heat, hyperthyroidism, and frantic restlessness.',
      mainIndications: ['Hyperthyroidism & Graves’ disease with wasting', 'Ravenous appetite with progressive weight loss', 'Indurated thyroid and lymphatic glandular swellings (goiter)', 'Membranous croup in hot-blooded children'],
      keynotes: ['Eats constantly yet wastes to skin and bones', 'Must remain constantly in motion to relieve internal anxiety', 'Intolerant of heat; craves cold air and cold bathing', 'Mental anxiety dramatically relieved while and after eating'],
      mindEmotional: 'Anxious, hurried, sudden violent impulses, driven to keep busy.',
      modalitiesBetter: ['While and after eating', 'Cold air and cold bathing', 'Open fresh breeze'],
      modalitiesWorse: ['Heat & warm stuffy rooms', 'Fasting', 'Inactivity and quiet rest'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Thyroid Gland & Endocrine System', 'Metabolic Axis & Lymphatics', 'Larynx & Lungs'],
      differentialRemedies: ['Natrium muriaticum', 'Tuberculinum', 'Abrotanum', 'Lachesis'],
      searchKeywords: ['iodine', 'thyroid', 'emaciation', 'hunger', 'hyperthyroidism', 'goiter', 'heat intolerant']
    },
    es: { commonName: 'Yodo' },
    fr: { commonName: 'Iode' },
    el: { commonName: 'Ιώδιο' },
    it: { commonName: 'Iodio' },
    ru: { commonName: 'Йод' }
  },
  {
    id: 'ipecacuanha',
    latinName: 'Carapichea ipecacuanha',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Brechwurz',
      origin: 'Getrocknete Wurzel der Brechwurz (Rubiaceae).',
      essence: 'Ständige, quälende Dauerübelkeit, die sich selbst durch Erbrechen in keiner Weise bessert; saubere, völlig unbelegte Zunge und krampfhafter Keuchhusten mit Erstickungsgefühl.',
      mainIndications: ['Schwangerschaftsübelkeit & Magen-Darm-Infekte mit Dauerübelkeit', 'Krampfhafter Husten mit Ersticken, Erbrechen & Nasenbluten', 'Asthma bronchiale mit Rasselgeräuschen ohne Auswurf', 'Uterusblutungen von hellrotem Blut mit Übelkeit'],
      keynotes: ['Ständige Übelkeit, die durch Erbrechen nicht gelindert wird', 'Zunge ist auffallend sauber, rosarot und völlig unbelegt', 'Reichlicher Speichelfluss bei Übelkeit', 'Hustenanfälle enden mit Würgen und Schleimerbrechen'],
      mindEmotional: 'Mürrisch, verächtlich, ungeduldig, verlangt vieles, weiß aber nicht was.',
      modalitiesBetter: ['An der frischen Luft', 'Ruhe'],
      modalitiesWorse: ['Wärme & feuchte Hitze', 'Geringste Bewegung', 'Liegen'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei akuter Übelkeit D6 alle 15–30 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Magen & Brechzentrum', 'Bronchien & Lunge', 'Kapillaren (hellrote Blutungen)'],
      differentialRemedies: ['Antimonium tartaricum (belegte Zunge, Erbrechen bessert)', 'Tabacum', 'Nux vomica', 'Arsenicum album'],
      searchKeywords: ['brechwurz', 'ipecacuanha', 'übelkeit', 'erbrechen', 'saubere zunge', 'schwangerschaftsübelkeit', 'husten', 'blutung']
    },
    en: {
      commonName: 'Ipecac Root',
      origin: 'Dried root of Carapichea ipecacuanha (Rubiaceae).',
      essence: 'Persistent, agonizing, unrelenting nausea not relieved in the slightest by vomiting; remarkably clean, pink, uncoated tongue; spasmodic suffocative cough with retching.',
      mainIndications: ['Morning sickness & gastroenteritis with unrelenting nausea', 'Spasmodic cough with suffocation, gagging, and epistaxis', 'Bronchial asthma with loud rattling without expectoration', 'Active bright red uterine hemorrhages accompanied by nausea'],
      keynotes: ['Constant nausea that vomiting does not relieve in the least', 'Tongue is clean, pink, and completely free of coating', 'Profuse salivation accompanying nausea and gagging', 'Suffocative coughing paroxysms ending in retching of mucus'],
      mindEmotional: 'Peevish, scornful, impatient, desires many things without knowing what.',
      modalitiesBetter: ['Open fresh air', 'Quiet rest'],
      modalitiesWorse: ['Warm humid air', 'Slightest motion', 'Lying down'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In acute nausea D6 every 15–30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Gastric Reflex & Vomiting Center', 'Bronchi & Lungs', 'Capillary Vessels'],
      differentialRemedies: ['Antimonium tartaricum (coated tongue, vomiting relieves)', 'Tabacum', 'Nux vomica', 'Arsenicum album'],
      searchKeywords: ['ipecac', 'ipecacuanha', 'nausea', 'vomiting', 'clean tongue', 'morning sickness', 'cough', 'hemorrhage']
    },
    es: { commonName: 'Ipecacuana' },
    fr: { commonName: 'Ipécacuanha' },
    el: { commonName: 'Ιπεκακουάνα' },
    it: { commonName: 'Ipecacuana' },
    ru: { commonName: 'Ипекакуана / Рвотный корень' }
  },
  {
    id: 'iris-versicolor',
    latinName: 'Iris versicolor',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Verschiedenfarbige Schwertlilie',
      origin: 'Frischer Wurzelstock der Schwertlilie (Iridaceae).',
      essence: 'Periodische Wochenendmigräne mit Sehstörungen (Verschwommen- oder Halbbildsehen) vor dem Schmerz und extrem saurem, brennendem Erbrechen der gesamten Magensäure.',
      mainIndications: ['Klassische Migräne mit Aura & Sehstörungen', 'Saures Erbrechen & Sodbrennen, das die Speiseröhre verbrennt', 'Pankreaserkrankungen mit brennenden Durchfällen'],
      keynotes: ['Sehstörungen (Aura) kündigen den Migräneanfall an', 'Erbrochenes ist so sauer, dass es die Zähne stumpf macht und den Hals verbrennt', 'Wochenend-Periodizität (Migräne tritt sonntags nach der Arbeitswoche auf)'],
      mindEmotional: 'Müde, mutlos, niedergeschlagen vor und während des Kopfschmerzes.',
      modalitiesBetter: ['Fortgesetzte sanfte Bewegung'],
      modalitiesWorse: ['Ruhe', 'Am Wochenende', 'Süßigkeiten'],
      potenciesAndDosage: 'D4 bis C30. Bei Migränebeginn D6 alle 15–30 Min.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Magen & Ösophagus', 'Bauchspeicheldrüse', 'Gehirn & Sehnerv'],
      differentialRemedies: ['Robinia', 'Sanguinaria', 'Spigelia', 'Nux vomica'],
      searchKeywords: ['schwertlilie', 'iris versicolor', 'migräne', 'saures erbrechen', 'aura', 'wochenendkopfschmerz', 'sodbrennen']
    },
    en: {
      commonName: 'Blue Flag',
      origin: 'Fresh rhizome of Iris versicolor (Iridaceae).',
      essence: 'Periodic weekend sick headache preceded by visual aura (blurred or hemiopic vision) and accompanied by intensely sour, burning vomiting of gastric acid.',
      mainIndications: ['Classic migraine preceded by visual blurriness/aura', 'Acid vomiting & heartburn burning the entire esophagus', 'Pancreatic affections with burning diarrhea'],
      keynotes: ['Visual disturbances (blurriness, hemiopia) precede headache', 'Vomitus is so intensely sour that it sets teeth on edge and excoriates throat', 'Weekend periodicity (migraine attacks appear on Sunday after weekly strain)'],
      mindEmotional: 'Despondent, low-spirited, dejected during headache.',
      modalitiesBetter: ['Continuous gentle motion'],
      modalitiesWorse: ['Rest', 'On weekends (Sundays)', 'Sweets and pastries'],
      potenciesAndDosage: 'D4 to C30 / 6C, 30C. At migraine aura onset D6 every 15–30 min.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Gastric Mucosa & Esophagus', 'Pancreas & Liver', 'Cerebrospinal & Optic Axis'],
      differentialRemedies: ['Robinia', 'Sanguinaria', 'Spigelia', 'Nux vomica'],
      searchKeywords: ['blue flag', 'iris versicolor', 'migraine', 'sour vomiting', 'visual aura', 'weekend headache', 'heartburn']
    },
    es: { commonName: 'Lirio azul / Iris' },
    fr: { commonName: 'Iris versicolore' },
    el: { commonName: 'Ίριδα' },
    it: { commonName: 'Iride versicolore' },
    ru: { commonName: 'Ирис разноцветный / Касатик' }
  }
];

console.log('REMEDIES_PART4_HIJ defined with count:', REMEDIES_PART4_HIJ.length);
