# scripts/remedy_definitions.py
# Raw structured definitions of classical remedies from Kent, Hahnemann, and Hering

RAW_REMEDIES = [
    # --- KENT & HAHNEMANN & HERING A ---
    {
        "id": "ailanthus-glandulosa",
        "latin": "Ailanthus glandulosa",
        "cat": "plant",
        "authors": ["kent", "hering"],
        "poly": False,
        "tier": 2,
        "de_name": "Götterbaum",
        "en_name": "Tree of Heaven",
        "es_name": "Árbol del cielo",
        "fr_name": "Ailante glanduleux",
        "it_name": "Albero del paradiso",
        "el_name": "Αείλανθος",
        "ru_name": "Айлант высочайший",
        "origin_de": "Frische Rinde und Blüten des Götterbaums (Simaroubaceae).",
        "origin_en": "Fresh bark and flowers of Ailanthus glandulosa (Simaroubaceae).",
        "essence_de": "Schwere septische Zustände mit tiefem Stupor, dunkelrotem Ausschlag und zyanotischem Rachen.",
        "essence_en": "Severe septic conditions with profound stupor, dark livid rash, and malignant sore throat.",
        "indications_de": ["Malignes Scharlach", "Septische Diphtherie", "Zyanotische Angina", "Stuporöse Infekte"],
        "indications_en": ["Malignant scarlatina", "Septic diphtheria", "Cyanotic tonsillitis", "Stuporous fevers"],
        "keynotes_de": [
            "Tiefe Benommenheit und Apathie mit halboffenem Mund",
            "Maligner, dunkelroter oder livider Ausschlag, der nur mangelhaft herauskommt",
            "Übelriechender Speichel und geschwollene Zunge",
            "Extreme Erschöpfung bei Infektionskrankheiten"
        ],
        "keynotes_en": [
            "Profound stupor and apathy with half-open mouth",
            "Livid, dark rash that fails to come out properly",
            "Fetid saliva and swollen tongue",
            "Extreme prostration in infectious diseases"
        ],
        "mind_de": "Völlige Gleichgültigkeit, erkennt die Umgebung nicht, delirierend.",
        "mind_en": "Complete indifference, semi-conscious stupor, muttering delirium.",
        "better_de": ["Frische Luft", "Ruhelage"],
        "better_en": ["Fresh air", "Quiet rest"],
        "worse_de": ["Aufrichten", "Schlucken", "Wärme"],
        "worse_en": ["Sitting up", "Swallowing", "Warmth"],
        "dosage_de": "D4 bis D12. Bei akuter Toxizität D6 alle 2 Stunden.",
        "dosage_en": "6X to 12X. In acute toxicity 6X every 2 hours.",
        "sphere": ["Hals & Rachen", "Blut & Sepsis", "ZNS", "Haut"],
        "diffs": ["Baptisia", "Belladonna", "Lachesis", "Rhus tox"],
        "keywords": ["scharlach", "angina", "stupor", "dunkler ausschlag", "sepsis"]
    },
    {
        "id": "aletris-farinosa",
        "latin": "Aletris farinosa",
        "cat": "plant",
        "authors": ["kent", "hering"],
        "poly": False,
        "tier": 2,
        "de_name": "Mehlige Sternwurzel",
        "en_name": "Star Grass / Colic Root",
        "es_name": "Hierba estrella",
        "fr_name": "Alétris farineux",
        "it_name": "Erba stella",
        "el_name": "Άλετρις",
        "ru_name": "Алетрис мучнистый",
        "origin_de": "Getrockneter Wurzelstock von Aletris farinosa (Liliaceae).",
        "origin_en": "Dried rhizome of Aletris farinosa (Liliaceae).",
        "essence_de": "Müdigkeit, Uterusschwäche und Anämie bei erschöpften Frauen mit habitueller Abortneigung.",
        "essence_en": "Exhaustion, uterine atony, and anemia in worn-out women prone to habitual miscarriage.",
        "indications_de": ["Uterussenkung", "Habitueller Abort", "Postpartale Erschöpfung", "Dyspepsie bei Anämie"],
        "indications_en": ["Uterine prolapse", "Habitual abortion", "Postpartum exhaustion", "Dyspepsia in anemia"],
        "keynotes_de": [
            "Ständiges Gefühl von Uterusschwäche und Schwere im Becken",
            "Müde, ausgezehrte Konstitution mit Verdauungsschwäche",
            "Erbrechen und Übelkeit während der Schwangerschaft",
            "Verstopfung mit hartem Stuhl durch Darmatonie"
        ],
        "keynotes_en": [
            "Constant feeling of uterine weakness and pelvic heaviness",
            "Tired, chlorotic constitution with poor digestion",
            "Obstinate vomiting and morning sickness in pregnancy",
            "Constipation from rectal and bowel atony"
        ],
        "mind_de": "Niedergeschlagen, müde des Lebens, nervöse Erschöpfung.",
        "mind_en": "Depressed, tired of life, nervous fatigue.",
        "better_de": ["Ruhe", "Nach gutem Schlaf"],
        "better_en": ["Rest", "After restorative sleep"],
        "worse_de": ["Geringste Anstrengung", "Bücken", "Schwangerschaft"],
        "worse_en": ["Least exertion", "Bending over", "Pregnancy"],
        "dosage_de": "D3 bis D6. 3x täglich 5 Tropfen.",
        "dosage_en": "3X to 6X. 5 drops 3 times daily.",
        "sphere": ["Weibliche Geschlechtsorgane", "Verdauungstrakt", "Blutbildung"],
        "diffs": ["Helonias", "Sepia", "Fraxinus", "China"],
        "keywords": ["uterussenkung", "abortneigung", "schwäche", "anämie", "übelkeit"]
    },
    {
        "id": "allium-sativum",
        "latin": "Allium sativum",
        "cat": "plant",
        "authors": ["kent", "hering"],
        "poly": False,
        "tier": 2,
        "de_name": "Knoblauch",
        "en_name": "Garlic",
        "es_name": "Ajo",
        "fr_name": "Ail cultivé",
        "it_name": "Aglio",
        "el_name": "Σκόρδο",
        "ru_name": "Чеснок посевной",
        "origin_de": "Frische Zwiebelknolle von Allium sativum (Amaryllidaceae).",
        "origin_en": "Fresh bulb of Allium sativum (Amaryllidaceae).",
        "essence_de": "Dyspepsie bei Fleischessern mit zähem Bronchialsekret und brennendem Magendruck.",
        "essence_en": "Dyspepsia in excessive meat-eaters with tenacious bronchial mucus and burning stomach pressure.",
        "indications_de": ["Chronische Bronchitis", "Dyspepsie nach Diätfehlern", "Bluthochdruck & Arteriosklerose", "Meteorismus"],
        "indications_en": ["Chronic bronchitis", "Dyspepsia from dietary errors", "Hypertension & arteriosclerosis", "Flatulence"],
        "keynotes_de": [
            "Reichlicher, zäher, klebriger Schleim in den Atemwegen",
            "Magenbeschwerden durch Fleischkonsum und Überernährung",
            "Heißhunger, aber das Essen verursacht Unbehagen",
            "Besserung der Magenbeschwerden durch Bücken"
        ],
        "keynotes_en": [
            "Copious, tenacious, sticky mucus in respiratory tract",
            "Stomach disturbances from meat eating and overeating",
            "Canine hunger, but eating causes distress",
            "Relief of gastric pain by bending double"
        ],
        "mind_de": "Ungeduldig, ängstlich bezüglich Gesundheit, empfindlich gegen Gerüche.",
        "mind_en": "Impatient, anxious about health, sensitive to odors.",
        "better_de": ["Bücken nach vorne", "Sitzen"],
        "better_en": ["Bending forward", "Sitting"],
        "worse_de": ["Kälte & Feuchtigkeit", "Fleischgenuss", "Gehen"],
        "worse_en": ["Cold and damp", "Eating meat", "Walking"],
        "dosage_de": "D2 bis D6. 3x täglich 5 Tropfen.",
        "dosage_en": "2X to 6X. 5 drops 3 times daily.",
        "sphere": ["Magen-Darm-Trakt", "Bronchien", "Kreislauf"],
        "diffs": ["Nux vomica", "Antimonium crudum", "Bryonia", "Pulsatilla"],
        "keywords": ["knoblauch", "dyspepsie", "fleisch", "bronchitis", "zäher schleim"]
    }
]
