import { RawRemedy } from './buildRemedyUtils';

export const REMEDIES_PART8_RS: RawRemedy[] = [
  {
    id: 'rhododendron-chrysanthum',
    latinName: 'Rhododendron aureum / Rhododendron chrysanthum',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Gelbe Alpenrose / Sibirische Schnee-Rose',
      origin: 'Getrocknete Blätter der Sibirischen Schnee-Rose (Ericaceae).',
      essence: 'Extremste Wetterfühligkeit: Rheumatische Gelenk- und Nervenschmerzen sowie Hodenentzündungen verschlimmern sich dramatisch VOR einem herannahenden Gewitter oder Sturm und bessern sich, sobald das Gewitter losbricht.',
      mainIndications: ['Rheumatische Gelenkschmerzen & Neuralgien vor Gewittern', 'Akute & chronische Orchitis (Hodenentzündung) / Epididymitis', 'Interkostalneuralgie & Zahnschmerzen bei Wetterumschwung'],
      keynotes: ['Symptome verschlimmern sich stundenlang vor einem Sturm/Gewitter und bessern sich bei Ausbruch des Wetters', 'Schmerzen wandern von Gelenk zu Gelenk', 'Hodenschmerz zieht in die Oberschenkel und Leiste', 'Besserung durch Bewegung und Wärme'],
      mindEmotional: 'Ängstlich, panisch vor drohendem Unwetter und Donner.',
      modalitiesBetter: ['Nach Ausbruch des Gewitters', 'Fortgesetzte Bewegung', 'Wärme & trockenes Wetter'],
      modalitiesWorse: ['Vor dem Sturm/Gewitter (Barometerabfall)', 'Windiges, stürmisches, nasskaltes Wetter', 'Ruhe'],
      potenciesAndDosage: 'D6 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Faserige Gewebe & Gelenke', 'Hoden & Samenstränge', 'Sensible Nerven'],
      differentialRemedies: ['Rhus tox', 'Dulcamara', 'Spigelia', 'Clematis'],
      searchKeywords: ['alpenrose', 'rhododendron', 'gewitter', 'wetterfühlig', 'hodenentzündung', 'orchitis', 'sturm', 'gelenkschmerzen']
    },
    en: {
      commonName: 'Siberian Snow Rose / Yellow Rhododendron',
      origin: 'Dried leaves of Rhododendron chrysanthum (Ericaceae).',
      essence: 'Extreme barometric weather sensitivity: rheumatic joint and neuralgic pains and testicular inflammation violently aggravated BEFORE an approaching thunderstorm, relieved once storm breaks.',
      mainIndications: ['Rheumatic arthritis & neuralgias before thunderstorms', 'Acute & chronic orchitis & epididymitis with severe tenderness', 'Intercostal neuralgia & toothaches from storm fronts'],
      keynotes: ['Symptoms aggravated for hours preceding a storm/thunderstorm; relieved when rain begins', 'Pains wander rapidly between joints', 'Testicular swelling and drawing pain radiating into thighs and groin', 'Pains relieved by continuous walking and local warmth'],
      mindEmotional: 'Anxious, dreads approaching thunder and storms.',
      modalitiesBetter: ['Once thunderstorm breaks & rain falls', 'Continuous motion', 'Warmth and dry wrapping'],
      modalitiesWorse: ['Before a thunderstorm (falling barometer)', 'Rough windy stormy weather', 'Absolute rest'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Fibrous Tissues & Joint Capsules', 'Testes & Spermatic Cords', 'Sensory Nerves'],
      differentialRemedies: ['Rhus tox', 'Dulcamara', 'Spigelia', 'Clematis'],
      searchKeywords: ['rhododendron', 'snow rose', 'thunderstorm', 'weather sensitive', 'orchitis', 'joint pain', 'barometer']
    },
    es: { commonName: 'Rododendro / Rosa de nieve siberiana' },
    fr: { commonName: 'Rhododendron doré' },
    el: { commonName: 'Ροδόδεντρο' },
    it: { commonName: 'Rododendro' },
    ru: { commonName: 'Рододендрон золотистый' }
  },
  {
    id: 'rhus-toxicodendron',
    latinName: 'Toxicodendron pubescens / Rhus toxicodendron',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Giftsumach / Giftschlingstrauch',
      origin: 'Frische Blätter des Giftsumachs (Anacardiaceae).',
      essence: 'Das große Mittel für Sehnen, Bänder und Gelenke mit typischer Bewegungsmodalität: Schlimmer bei Beginn der Bewegung („Anlaufschmerz“), besser durch fortgesetzte Bewegung; Ruhelosigkeit (muss ständig die Lage wechseln); rote Zungenspitze (rotes Dreieck); Herpesbläschen und Folgen von Durchnässung bei Erhitzung.',
      mainIndications: ['Verstauchungen, Zerrungen & Sehnenüberlastung (z.B. Tennisarm)', 'Hexenschuss (Lumbago), Ischias & rheumatischer Gelenkschmerz', 'Lippenherpes & Bläschenausschläge (Herpes zoster, Windpocken)', 'Erkältungen nach Schwitzen und anschließender Durchnässung'],
      keynotes: ['Anlaufschmerz: Zu Beginn der Bewegung steif und schmerzhaft, bei fortgesetzter Bewegung deutlich besser', 'Ständige körperliche Ruhelosigkeit: muss die Lage im Bett unaufhörlich verändern', 'Rotes Dreieck an der Zungenspitze (rote Dreiecksspitze)', 'Besserung durch heiße Bäder, heiße Duschen und lokale Wärme'],
      mindEmotional: 'Unruhig, ängstlich, besonders nachts, kann nicht im Bett stillliegen.',
      modalitiesBetter: ['Fortgesetzte Bewegung', 'Hitze, heiße Bäder & heiße Umschläge', 'Trockenes warmes Wetter'],
      modalitiesWorse: ['Beginn der Bewegung (nach Ruhe)', 'Kälte, Nässe, Regen & Nebel', 'Nachts im Bett'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Nach Verstauchung oder bei Hexenschuss C30 alle 2–4 Stunden.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Sehnen, Bänder & Gelenkkapseln', 'Haut (Herpes, Bläschen)', 'Lendenwirbelsäule & Nerven'],
      differentialRemedies: ['Bryonia (Gegenteil: jede Bewegung verschlimmert)', 'Ruta (Knochenhaut)', 'Arnica', 'Dulcamara'],
      searchKeywords: ['giftsumach', 'rhus toxicodendron', 'rhus tox', 'anlaufschmerz', 'verstauchung', 'zerrung', 'ruhelosigkeit', 'herpes', 'rotes dreieck zunge', 'hexenschuss']
    },
    en: {
      commonName: 'Poison Ivy',
      origin: 'Fresh leaves of Toxicodendron pubescens (Anacardiaceae).',
      essence: 'The supreme ligament, tendon, and restless musculoskeletal polychrest: worse at beginning of motion ("initial stiffness"), better from continuous gentle motion; uncontrollable tossing restlessness; red triangular tip on tongue; vesicular herpes; ailments from getting drenched while overheated.',
      mainIndications: ['Sprains, strains & ligament injuries (e.g. tennis elbow, sprained ankle)', 'Lumbago, sciatica & rheumatic stiffness', 'Herpes labialis & vesicular eruptions (shingles, varicella)', 'Ailments from getting wet and chilled after being overheated'],
      keynotes: ['Initial motion painful, but continuous motion brings marked limbering and relief', 'Physical restlessness: constantly tosses and changes position in bed', 'Red triangular patch on tip of coated tongue', 'Marked relief from hot scalding baths, hot showers, and dry heat'],
      mindEmotional: 'Restless, apprehensive, anxious at twilight and night, cannot stay in bed.',
      modalitiesBetter: ['Continuous motion and walking', 'Intense dry heat & hot baths', 'Dry sunny weather'],
      modalitiesWorse: ['First motion after rest', 'Damp cold, rain & exposure to wet', 'Night in bed'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In sprains or lumbago C30 every 2–4 hours.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Ligaments, Tendons & Joint Capsules', 'Skin (Vesicles, Herpes)', 'Lumbar Spine & Sciatic Nerve'],
      differentialRemedies: ['Bryonia (opposite: absolute motion aggravation)', 'Ruta (periosteum)', 'Arnica', 'Dulcamara'],
      searchKeywords: ['poison ivy', 'rhus tox', 'rhus toxicodendron', 'initial stiffness', 'sprain', 'strain', 'restless', 'red triangle tongue', 'lumbago', 'hot bath']
    },
    es: { commonName: 'Hiedra venenosa / Zaqueque' },
    fr: { commonName: 'Sumac vénéneux / Toxicodendron' },
    el: { commonName: 'Ρους ο τοξικόδενδρος' },
    it: { commonName: 'Edera velenosa / Rhus tox' },
    ru: { commonName: 'Сумах ядовитый / Рус токсикодендрон' }
  },
  {
    id: 'ruta-graveolens',
    latinName: 'Ruta graveolens',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Gartenraute / Weinraute',
      origin: 'Frische oberirdische Teile der Weinraute vor der Blüte (Rutaceae).',
      essence: 'Das Hauptmittel für Knochenhaut (Periost), Sehnenansätze, Ganglien (Überbeine) und Augenüberanstrengung durch Bildschirmarbeit oder Feinarbeit; Zerschlagenheitsgefühl, als läge man auf hartem Holz.',
      mainIndications: ['Knochenhautprellungen (Schienbein, Rippen, Ellbogen)', 'Sehnenscheidenentzündung & Ganglien (Überbeine am Handgelenk)', 'Asthenopie (Augenüberanstrengung durch Bildschirm, Lesen, Nähen)', 'Achillessehnenreizung & Fersensporn'],
      keynotes: ['Verletzungen und Prellungen des Periosts (Knochenhaut)', 'Brennende, schmerzende, müde Augen nach stundenlanger Bildschirmarbeit', 'Überbeine (Ganglien) an Handgelenken und Fußrücken', 'Zerschlagenheitsgefühl in den Gliedern, als läge man auf harten Steinen'],
      mindEmotional: 'Mürrisch, unzufrieden mit sich und anderen, ängstlich.',
      modalitiesBetter: ['Bewegung', 'Wärme', 'Liegen auf dem Rücken'],
      modalitiesWorse: ['Kälte & Nässe', 'Ruhe', 'Überanstrengung der Augen (Bildschirm)'],
      potenciesAndDosage: 'D6 bis C30. Bei Sehnenscheidenentzündung D6 3x täglich.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Periost (Knochenhaut) & Knochen', 'Sehnenansätze & Sehnenscheiden', 'Augenmuskeln & Akkommodation'],
      differentialRemedies: ['Arnica (Muskeln)', 'Rhus tox (Bänder)', 'Symphytum (Knochenbruch)', 'Hypericum (Nerven)'],
      searchKeywords: ['weinraute', 'ruta', 'knochenhaut', 'periost', 'ganglion', 'überbein', 'bildschirmarbeit', 'augenüberanstrengung', 'sehnenscheide']
    },
    en: {
      commonName: 'Rue / Bitter Herb',
      origin: 'Fresh blooming herb of Ruta graveolens (Rutaceae).',
      essence: 'The supreme periosteal, tendon insertion, ganglion, and visual asthenopia remedy: eye-strain from screen work or fine stitching; bruised soreness as if lying on hard boards; wrist ganglia.',
      mainIndications: ['Periosteal contusions & bone bruises (tibia, ribs, elbows)', 'Tendonitis & ganglia of wrists and flexor tendons', 'Asthenopia (eye strain from computer monitors, reading, fine sewing)', 'Achilles tendinitis & calcaneal spur pain'],
      keynotes: ['Injuries directly bruising the sensitive periosteum of bones', 'Burning, aching, straining fatigue in eyes after prolonged near vision / screens', 'Cystic ganglia over wrist flexor or extensor tendons', 'Bruised soreness in all limbs as if beaten with a heavy stick'],
      mindEmotional: 'Morose, irritable, dissatisfied with self and others, anxious.',
      modalitiesBetter: ['Continuous movement', 'Warmth', 'Lying on back'],
      modalitiesWorse: ['Cold damp air', 'Resting', 'Ocular strain (computer screens)'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. In tendonitis D6 3 times daily.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Periosteum & Bone Surfaces', 'Tendon Insertions & Sheaths', 'Ciliary Eye Muscles & Accommodation'],
      differentialRemedies: ['Arnica (muscle contusion)', 'Rhus tox (ligaments)', 'Symphytum (fractures)', 'Hypericum (nerves)'],
      searchKeywords: ['rue', 'ruta', 'periosteum', 'bone bruise', 'ganglion cyst', 'eye strain', 'computer screens', 'tendonitis']
    },
    es: { commonName: 'Ruda / Hierba de gracia' },
    fr: { commonName: 'Rue officinale / Rue des jardins' },
    el: { commonName: 'Απήγανος' },
    it: { commonName: 'Ruta comune' },
    ru: { commonName: 'Рута душистая / Рута гравеоленс' }
  },
  {
    id: 'sabadilla',
    latinName: 'Schoenocaulon officinale / Sabadilla',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Läusekörner / Sabadill',
      origin: 'Getrocknete Samen von Schoenocaulon officinale (Melanthiaceae).',
      essence: 'Krampfhafte, unstillbare Niesanfälle bei Heuschnupfen: Reizendes Jucken in Nase und Gaumen, Tränenfluss und Überempfindlichkeit gegen den Geruch von Blumen und Knoblauch.',
      mainIndications: ['Saisonaler Heuschnupfen mit heftigsten Nieskaskaden', 'Kitzeln & Jucken am weichen Gaumen und in den Nasengängen', 'Pharyngitis (Halsschmerz wandert von links nach rechts)'],
      keynotes: ['Serien von 10 bis 20 heftigen Niesern hintereinander', 'Zwingender Drang, den Gaumen mit der Zunge zu reiben oder zu kratzen', 'Geruch von Blumen, Äpfeln oder Knoblauch löst sofort Niesanfall aus'],
      mindEmotional: 'Eingebildete Krankheitsvorstellungen (Wahnideen über den eigenen Körper).',
      modalitiesBetter: ['Warme Getränke & warme Speisen', 'Warme Raumluft'],
      modalitiesWorse: ['Kälte & Zugluft', 'Geruch von Blumen und Knoblauch', 'Pollenflug'],
      potenciesAndDosage: 'D4 bis C30. Bei Heuschnupfen D6 3x täglich.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Nasenschleimhaut & Niesreflex', 'Gaumen & Rachen', 'Tränendrüsen'],
      differentialRemedies: ['Allium cepa', 'Euphrasia', 'Galphimia glauca', 'Luffa operculata'],
      searchKeywords: ['sabadilla', 'läusekörner', 'niesen', 'niesanfall', 'heuschnupfen', 'gaumenjucken', 'blumenallergie']
    },
    en: {
      commonName: 'Cevadilla Seed',
      origin: 'Dried seeds of Schoenocaulon officinale (Melanthiaceae).',
      essence: 'Violent paroxysmal spasmodic sneezing fits in seasonal hay fever: severe itching of soft palate and nostrils, copious lacrimation, and intolerance of the odor of flowers and garlic.',
      mainIndications: ['Seasonal pollinosis with explosive cascading sneezing', 'Tickling itch of soft palate compelling tongue rubbing', 'Pharyngitis with pain shifting from left to right side'],
      keynotes: ['Cascades of 10 to 20 violent explosive sneezes in rapid succession', 'Compelling urge to rub or scratch soft palate with tongue', 'Odor of fresh flowers, garlic, or apples provokes violent sneezing'],
      mindEmotional: 'Erroneous somatic delusions (imagines parts shrunken or deformed).',
      modalitiesBetter: ['Hot drinks & warm food', 'Warm room'],
      modalitiesWorse: ['Cold drafts', 'Odor of flowers and garlic', 'Pollen counts'],
      potenciesAndDosage: 'D4 to C30 / 4X to 30C. In hay fever D6 3 times daily.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Nasal Mucosa & Sneezing Reflex', 'Soft Palate & Pharynx', 'Lacrimal Glands'],
      differentialRemedies: ['Allium cepa', 'Euphrasia', 'Galphimia glauca', 'Luffa operculata'],
      searchKeywords: ['sabadilla', 'sneezing paroxysms', 'hay fever', 'itching palate', 'flower odor', 'pollen allergy']
    },
    es: { commonName: 'Sabadilla / Cevadilla' },
    fr: { commonName: 'Sabadille' },
    el: { commonName: 'Σαβαδίλλα' },
    it: { commonName: 'Sabadilla' },
    ru: { commonName: 'Сабадилла / Вшивое семя' }
  },
  {
    id: 'sambucus-nigra',
    latinName: 'Sambucus nigra',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Schwarzer Holunder',
      origin: 'Frische Blätter und Blüten des Schwarzen Holunders (Adoxaceae).',
      essence: 'Das Hauptmittel für Säuglingsschnupfen (Säugling kann wegen verstopfter Nase nicht an der Brust trinken) und nächtliche Erstickungsanfälle bei Pseudokrupp: Erwachen um Mitternacht mit blaurotem Gesicht und Erstickungsnot; starkes Schwitzen beim Erwachen (schwitzt nicht im Schlaf).',
      mainIndications: ['Säuglingsschnupfen (Nase völlig verstopft beim Stillen)', 'Pseudokrupp & Laryngitis mit nächtlichem Erwachen und Atemnot', 'Asthmatische Atemnot mit trockenem Bellhusten'],
      keynotes: ['Säugling schnappt nach Luft und muss beim Trinken an der Brust absetzen', 'Plötzliches Erwachen um Mitternacht mit Ersticken und blaurotem Gesicht', 'Trockene Hitze während des Schlafs – Schweiß bricht erst beim Erwachen aus'],
      mindEmotional: 'Ängstlich, panisch durch Atemnot beim Erwachen.',
      modalitiesBetter: ['Aufrechtes Sitzen im Bett', 'Wärme'],
      modalitiesWorse: ['Um Mitternacht (24:00 Uhr)', 'Liegen mit tiefem Kopf', 'Kaltluft'],
      potenciesAndDosage: 'Akut: D3 bis D12. Bei Säuglingsschnupfen D6 vor dem Stillen.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Nasenschleimhaut (Säuglinge)', 'Kehlkopf & Trachea (Krupp)', 'Schweißregulation'],
      differentialRemedies: ['Spongia tosta', 'Aconitum', 'Drosera', 'Hepar sulfuris'],
      searchKeywords: ['holunder', 'sambucus', 'säuglingsschnupfen', 'pseudokrupp', 'stillen', 'mitternacht', 'ersticken', 'schweiß beim erwachen']
    },
    en: {
      commonName: 'Black Elder',
      origin: 'Fresh leaves and flowers of Sambucus nigra (Adoxaceae).',
      essence: 'The supreme remedy for infant snuffles (baby cannot nurse because nostrils are blocked) and suffocative midnight croup: waking at midnight suffocating with cyanotic face; profuse sweat on waking (dry in sleep).',
      mainIndications: ['Infant snuffles & nasal obstruction preventing nursing', 'Midnight suffocative croup & spasmodic laryngismus', 'Bronchial asthma with dry suffocative barking cough'],
      keynotes: ['Nursing infant gasps for breath and constantly lets go of breast to breathe', 'Sudden suffocative midnight awakening with dark cyanotic gasping face', 'Dry burning heat during sleep – profuse sweating begins only on waking'],
      mindEmotional: 'Terrified, frantic from suffocation upon sudden waking.',
      modalitiesBetter: ['Sitting upright in bed', 'Warmth'],
      modalitiesWorse: ['Midnight (12:00 AM)', 'Lying with head low', 'Cold drafts'],
      potenciesAndDosage: 'Acute: D3 to D12 / 3X to 12X. In infant snuffles D6 before nursing.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Nasal Passages in Infants', 'Larynx & Trachea (Croup)', 'Diaphoretic Axis'],
      differentialRemedies: ['Spongia tosta', 'Aconitum', 'Drosera', 'Hepar sulfuris'],
      searchKeywords: ['elder', 'sambucus', 'infant snuffles', 'nursing', 'croup', 'midnight suffocation', 'sweat on waking']
    },
    es: { commonName: 'Saúco negro' },
    fr: { commonName: 'Sureau noir' },
    el: { commonName: 'Σαμπούκος' },
    it: { commonName: 'Sambuco nero' },
    ru: { commonName: 'Бузина черная' }
  },
  {
    id: 'sanguinaria-canadensis',
    latinName: 'Sanguinaria canadensis',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Kanadische Blutwurz',
      origin: 'Frischer Wurzelstock der Kanadischen Blutwurz (Papaveraceae).',
      essence: 'Rechtsseitige Sonnen- und Klimakteriums-Migräne: Kopfschmerz beginnt morgens im Nacken, zieht über den Kopf und setzt sich im rechten Auge fest; steigt mit der Sonne auf und sinkt mit ihr; feuerrote rechte Wange.',
      mainIndications: ['Rechtsseitige Sonnen- und Wochenend-Migräne (über rechtem Auge)', 'Klimakterische Hitzewallungen mit roten Wangenflecken', 'Rechtseitige Schulter-Arm-Neuralgie'],
      keynotes: ['Kopfschmerz steigt morgens auf, erreicht mittags seinen Höhepunkt und sinkt abends mit der Sonne', 'Schmerz setzt sich über dem rechten Auge/rechter Schläfe fest', 'Umschriebene feuerrote Rötung der rechten Wange', 'Besserung durch festen Druck, Erbrechen von Galle und Schlaf im dunklen Zimmer'],
      mindEmotional: 'Reizbar, empfindlich gegen Geräusche und Licht, will absolute Stille.',
      modalitiesBetter: ['Dunkler Raum & Schlaf', 'Erbrechen von Galle', 'Fester Druck auf den Kopf'],
      modalitiesWorse: ['Sonnenaufgang bis Sonnenuntergang', 'Rechte Seite', 'Bewegung & Gerüche'],
      potenciesAndDosage: 'D6 bis C30. Bei Migränebeginn D6 alle 30 Min.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Gehirn & Vasomotorik (rechtsseitig)', 'Rechte Schulter & Gelenke', 'Schleimhäute & Magen'],
      differentialRemedies: ['Spigelia (linksseitig)', 'Iris versicolor', 'Belladonna', 'Sepia'],
      searchKeywords: ['blutwurz', 'sanguinaria', 'migräne', 'rechtsseitig', 'rechtes auge', 'sonnenkopfschmerz', 'hitzewallung', 'rote wange']
    },
    en: {
      commonName: 'Bloodroot',
      origin: 'Fresh rhizome of Sanguinaria canadensis (Papaveraceae).',
      essence: 'Right-sided American sun migraine and menopausal flushing: headache starts in morning occiput, spreads upward settling over right eye; rises and falls with the sun; circumscribed fiery red right cheek.',
      mainIndications: ['Right-sided sun migraine settling over right eye', 'Menopausal hot flushes with circumscribed burning cheeks', 'Right deltoid & shoulder-arm periarthritis'],
      keynotes: ['Headache begins at sunrise, peaks at midday, and declines at sunset', 'Pain settles fiercely in and above the right eye and temple', 'Circumscribed burning red flush on right cheek', 'Relief from firm pressure, vomiting bilious fluid, and dark sleep'],
      mindEmotional: 'Irritable, intolerant of noise and smells, wants quiet.',
      modalitiesBetter: ['Dark quiet room & sleep', 'Bilious vomiting', 'Firm pressure on head'],
      modalitiesWorse: ['Sun exposure (sunrise to sunset)', 'Right side', 'Motion and odors'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. At migraine onset D6 every 30 min.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Right Cerebral Vasomotor Axis', 'Right Shoulder & Deltoid', 'Respiratory & Gastric Mucosa'],
      differentialRemedies: ['Spigelia (left-sided)', 'Iris versicolor', 'Belladonna', 'Sepia'],
      searchKeywords: ['bloodroot', 'sanguinaria', 'migraine', 'right eye', 'sun headache', 'red cheek', 'menopause']
    },
    es: { commonName: 'Sanguinaria / Raíz de sangre' },
    fr: { commonName: 'Sanguinaire du Canada' },
    el: { commonName: 'Σανγκουινάρια' },
    it: { commonName: 'Sanguinaria' },
    ru: { commonName: 'Сангвинария канадская' }
  },
  {
    id: 'sepia-officinalis',
    latinName: 'Sepia officinalis',
    categoryKey: 'animal',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Echter Tintenfisch / Sepia',
      origin: 'Getrockneter Inhalt des Tintenbeutels des Tintenfischs (Sepiidae).',
      essence: 'Das große Mittel für hormonelle Erschöpfung und venöse Stauung: Völlige emotionale Gleichgültigkeit gegen die eigene Familie; Herabdrängungsgefühl im Unterleib (muss die Beine kreuzen); gelber Schmetterlingsfleck über der Nase; dramatische Besserung durch heftige körperliche Bewegung (Tanzen, Joggen, Aerobic).',
      mainIndications: ['Klimakterische Beschwerden mit Hitzewallungen, Schweiß & Erschöpfung', 'Uterusprolaps & Senkungsbeschwerden mit „Bearing-down-Gefühl“', 'Postpartale Depression & emotionale Kälte gegenüber Familie', 'Melasma (gelb-brauner Schmetterlingsfleck über Nase und Wangen)', 'Chronische Obstipation mit Gefühl einer Kugel im Rektum'],
      keynotes: ['Bearing-down: Starkes Herabdrängungsgefühl im Becken, kreuzt instinktiv die Beine', 'Dramatische Besserung von Gemüt und Körper durch anstrengende Bewegung (schnelles Tanzen/Laufen)', 'Gelb-brauner Sattel- oder Schmetterlingsfleck quer über Nasenrücken und Wangen', 'Abneigung gegen Fett, Fleisch und den Geruch von kochendem Essen', 'Völlige emotionale Kälte und Gleichgültigkeit gegen geliebte Menschen'],
      mindEmotional: 'Gleichgültig, erschöpft, weinerlich, will allein sein, reizbar bei Widerspruch.',
      modalitiesBetter: ['Heftige körperliche Anstrengung & schnelles Tanzen/Sport', 'Wärme des Bettes', 'Überkreuzen der Beine'],
      modalitiesWorse: ['Kälte, Nässe & Waschen mit kaltem Wasser', 'Vor und während der Menses', 'Geruch von Speisen', 'Ruhe'],
      potenciesAndDosage: 'C30 bis C200. Bei klimakterischen Beschwerden C30 1x wöchentlich.',
      defaultTagesdosis: '1 Gabe à 3–5 Globuli',
      sphereOfAction: ['Weibliche Geschlechtsorgane & Uterus', 'Venöses Gefäßsystem (Pfortader)', 'Psyche & Hormone'],
      differentialRemedies: ['Lachesis (redselig, hitzig)', 'Pulsatilla (sucht Trost, besser sanfte Bewegung)', 'Natrium muriaticum'],
      searchKeywords: ['tintenfisch', 'sepia', 'klimakterium', 'hitzewallung', 'senkung', 'bearing down', 'beine kreuzen', 'gleichgültig', 'schmetterlingsfleck', 'tanzen bessert']
    },
    en: {
      commonName: 'Cuttlefish Ink / Sepia',
      origin: 'Dried contents of the ink sac of Sepia officinalis (Sepiidae).',
      essence: 'The supreme hormonal exhaustion and venous stasis polychrest: profound emotional indifference to own loved ones; bearing-down sensation in pelvis compelling crossing of legs; yellow butterfly saddle across nose; dramatic relief from violent physical exertion (aerobics, fast dancing).',
      mainIndications: ['Menopausal syndrome with hot flashes, night drenching sweats & burnout', 'Uterine prolapse & pelvic relaxation with severe "bearing-down"', 'Postpartum depression with emotional detachment from baby/husband', 'Chloasma / melasma (yellowish-brown saddle across nose and cheeks)', 'Obstinate constipation with sensation of a hard ball in rectum'],
      keynotes: ['Bearing-down sensation in pelvis as if organs would escape; crosses legs firmly to prevent it', 'Remarkable relief of mind and body from vigorous, violent exercise and dancing', 'Yellow-brown saddle across bridge of nose and cheeks', 'Intolerance of the smell and sight of food cooking', 'Complete emotional coldness and indifference toward family'],
      mindEmotional: 'Apathetic, weeping, burnt-out, irritable, craves solitude, spiteful.',
      modalitiesBetter: ['Violent physical exercise, fast walking & aerobics', 'Warmth of bed', 'Crossing legs tightly'],
      modalitiesWorse: ['Cold air, dampness & laundry cold water', 'Before and during menses', 'Smell of cooking', 'Resting'],
      potenciesAndDosage: 'C30 to C200 / 30C, 200C. In menopausal flushes C30 once weekly.',
      defaultTagesdosis: '1 dose of 3–5 pellets',
      sphereOfAction: ['Female Reproductive Organs & Uterus', 'Portal & Pelvic Venous Circulation', 'Autonomic & Endocrine Axis'],
      differentialRemedies: ['Lachesis (loquacious, intolerant of collars)', 'Pulsatilla (craves consolation, gentle motion)', 'Natrium muriaticum'],
      searchKeywords: ['sepia', 'cuttlefish', 'menopause', 'hot flushes', 'bearing down', 'cross legs', 'indifference', 'butterfly saddle', 'exercise relieves']
    },
    es: { commonName: 'Sepia / Tinta de calamar' },
    fr: { commonName: 'Sépia / Encre de seiche' },
    el: { commonName: 'Σουπιά / Σέπια' },
    it: { commonName: 'Sepia / Inchiostro di seppia' },
    ru: { commonName: 'Сепия / Чернила каракатицы' }
  },
  {
    id: 'silicea',
    latinName: 'Silicea terra / Acidum silicicum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Kieselerde / Reines Siliciumdioxid',
      origin: 'Reines amorphes Siliciumdioxid (SiO2).',
      essence: 'Das große Mittel für Schwäche des Bindegewebes, chronische Eiterungen und mangelnde Selbstbehauptung: Extrem frostig (muss sich bis über die Ohren warm einpacken); treibt Fremdkörper (Splitter, Dornen) aus dem Gewebe; stinkender Fußschweiß und Schüchternheit mit innerem Perfektionismus.',
      mainIndications: ['Chronische Eiterungen, Fisteln, Abszesse & Furunkel', 'Austreibung von Fremdkörpern (Splitter, Dornen, Glassplitter)', 'Stinkender Fußschweiß & Kälteempfindlichkeit an Kopf und Füßen', 'Brüchige Nägel mit weißen Flecken & Haarausfall', 'Prüfungsangst mit Mangel an Selbstvertrauen ("Grit")'],
      keynotes: ['Fördert die Austreibung eingedrungener Fremdkörper aus der Haut', 'Extremste Frostigkeit: packt den Kopf selbst im Sommer warm ein', 'Übelriechender, ätzender Fußschweiß, der die Socken zerstört', 'Verstopfung: Stuhl schlüpft zurück, wenn er fast geboren ist („schüchterner Stuhl“)', 'Empfindlich gegen Nadeln und spitze Gegenstände (Nadelphobie)'],
      mindEmotional: 'Schüchtern, sanft, nachgiebig, aber im Kern unnachgiebig starr; Versagensangst trotz brillanter Fähigkeiten.',
      modalitiesBetter: ['Warmes Einhüllen (besonders des Kopfes)', 'Sommer & trockene Wärme'],
      modalitiesWorse: ['Kälte, Zugluft & Entblößen des Kopfes', 'Unterdrückter Fußschweiß', 'Neumond'],
      potenciesAndDosage: 'D6, D12, C30 (Schüßler-Salz Nr. 11). 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Bindegewebe, Knochen & Gelenke', 'Haut, Haare & Nägel', 'Lymphknoten & Eiterungsprozesse'],
      differentialRemedies: ['Hepar sulfuris (akuter Eiter, Splitterschmerz)', 'Calcarea carbonica', 'Pulsatilla', 'Fluoricum acidum'],
      searchKeywords: ['kieselerde', 'silicea', 'splitter', 'fremdkörper', 'frostig', 'kopf warm einpacken', 'stinkender fußschweiß', 'brüchige nägel', 'fistel']
    },
    en: {
      commonName: 'Pure Flint / Silica',
      origin: 'Pure precipitated silicon dioxide.',
      essence: 'The supreme connective tissue, chronic suppurative, and constitutional grit polychrest: extremely chilly (must wrap head up warmly); expels foreign bodies (splinters, thorns); offensive foot sweat and yielding perfectionism.',
      mainIndications: ['Chronic suppurations, fistulae, boils, and indurated abscesses', 'Expulsion of foreign bodies (splinters, needles, thorns, glass)', 'Offensive corrosive foot sweat & icy coldness of extremities', 'Brittle deformed nails with white spots & thinning hair', 'Performance anxiety with lack of self-confidence despite talent'],
      keynotes: ['Promotes mechanical expulsion of embedded foreign bodies from skin', 'Exquisite chilliness: wraps head up in heavy woolens even in summer', 'Offensive, acrid foot sweat destroying socks and shoes', 'Constipation: stool recedes back into rectum after partial emergence ("bashful stool")', 'Pin and needle phobia (dreads sharp objects)'],
      mindEmotional: 'Timid, yielding, gentle, but with unbending stubborn core; fears failure.',
      modalitiesBetter: ['Wrapping up head and body warmly', 'Summer and dry heat'],
      modalitiesWorse: ['Cold drafts & uncovering head', 'Suppression of foot sweat', 'New moon'],
      potenciesAndDosage: 'D6, D12, C30 / 6X, 12X, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Connective Tissue & Bone Matrix', 'Skin, Hair & Nails', 'Lymphatic Glands & Suppuration'],
      differentialRemedies: ['Hepar sulfuris (acute pus, splinter pain)', 'Calcarea carbonica', 'Pulsatilla', 'Fluoricum acidum'],
      searchKeywords: ['silica', 'silicea', 'splinters', 'foreign body expulsion', 'chilly', 'wrap up head', 'smelly foot sweat', 'bashful stool', 'brittle nails']
    },
    es: { commonName: 'Sílice / Tierra silícea' },
    fr: { commonName: 'Silice / Terre silicieuse' },
    el: { commonName: 'Πυρίτιο' },
    it: { commonName: 'Silice' },
    ru: { commonName: 'Кремнезем / Силицея' }
  },
  {
    id: 'spigelia-anthelmia',
    latinName: 'Spigelia anthelmia',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Wurmkraut',
      origin: 'Ganze getrocknete Pflanze des Wurmkrauts (Loganiaceae).',
      essence: 'Linksseitige Trigeminusneuralgie und heftiges, sichtbares Herzklopfen: Stechende Schmerzen im und über dem linken Auge, die mit dem Sonnenstand an- und abschwellen; Herzschläge erschüttern den gesamten Brustkorb.',
      mainIndications: ['Linksseitige Trigeminusneuralgie & Gesichtsschmerzen', 'Linksseitige Sonnenmigräne (über dem linken Auge)', 'Heftiges Herzklopfen & Perikarditis mit sichtbaren Pulsationen'],
      keynotes: ['Schmerz beginnt morgens, erreicht mittags seinen Höhepunkt und sinkt abends ab (wie Sanguinaria, aber LINKS)', 'Schmerz fühlt sich an wie eine glühende Nadel, die tief ins linke Auge sticht', 'Herzklopfen ist so heftig, dass man es von außen sehen und hören kann', 'Empfindlich gegen Erschütterung und Berührung'],
      mindEmotional: 'Ängstlich wegen des Herzklopfens, Angst vor spitzen Nadeln.',
      modalitiesBetter: ['Liegen auf der rechten Seite mit hochgelagertem Kopf', 'Ruhe'],
      modalitiesWorse: ['Geringste Erschütterung & Bewegung', 'Liegen auf der linken Seite', 'Berührung'],
      potenciesAndDosage: 'D6 bis C30. Bei akuter Neuralgie D6 alle 15–30 Min.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Nervus trigeminus (links)', 'Herz & Herzbeutel', 'Linkes Auge'],
      differentialRemedies: ['Sanguinaria (rechtsseitig)', 'Spongia tosta', 'Cactus grandiflorus', 'Magnesia phosphorica'],
      searchKeywords: ['wurmkraut', 'spigelia', 'trigeminus', 'linksseitig', 'linkes auge', 'herzklopfen', 'sonnenmigräne', 'erschütterung']
    },
    en: {
      commonName: 'Pinkroot / Wormgrass',
      origin: 'Whole dried plant of Spigelia anthelmia (Loganiaceae).',
      essence: 'Left-sided trigeminal neuralgia and violent, visible palpitations: darting piercing pains in and above left eye, tracking the sun’s course; heartbeats violently shaking the entire chest wall.',
      mainIndications: ['Left-sided trigeminal facial neuralgia', 'Left-sided sun migraine centering over left eye', 'Violent palpitations & pericarditis with visible cardiac thrust'],
      keynotes: ['Headache begins at sunrise, peaks at noon, and fades at sunset (like Sanguinaria, but strictly LEFT-sided)', 'Pain like a red-hot needle stabbing deeply into the left eye socket', 'Cardiac pulsations are visibly turbulent and shake the whole chest', 'Intolerant of slightest jar or light touch'],
      mindEmotional: 'Anxious from heart palpitations, acute needle phobia.',
      modalitiesBetter: ['Lying on right side with head elevated', 'Quiet rest'],
      modalitiesWorse: ['Slightest jarring, stepping & motion', 'Lying on left side', 'Light touch'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. In acute neuralgia D6 every 15–30 min.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Left Trigeminal Nerve', 'Heart & Pericardium', 'Left Eye & Orbit'],
      differentialRemedies: ['Sanguinaria (right-sided)', 'Spongia tosta', 'Cactus grandiflorus', 'Magnesia phosphorica'],
      searchKeywords: ['pinkroot', 'spigelia', 'trigeminal neuralgia', 'left eye', 'palpitations', 'sun headache', 'jarring worse']
    },
    es: { commonName: 'Espigelia / Hierba de las lombrices' },
    fr: { commonName: 'Spigélie vermifuge' },
    el: { commonName: 'Σπιγέλια' },
    it: { commonName: 'Spigelia' },
    ru: { commonName: 'Спигелия противоглистная' }
  },
  {
    id: 'spongia-tosta',
    latinName: 'Spongia officinalis tosta',
    categoryKey: 'animal',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Gerösteter Meerschwamm',
      origin: 'In Alkohol gerösteter echter Meerschwamm (Spongiidae).',
      essence: 'Das Hauptmittel für Pseudokrupp: Trockener, bellender, hohler Husten „wie eine Säge durch trockenes Tannenholz“; Erwachen vor Mitternacht mit Erstickungsangst; dramatische Besserung durch warme Getränke und warmen Wasserdampf.',
      mainIndications: ['Akuter Pseudokrupp bei Kindern mit bellendem Husten', 'Kehlkopfentzündung (Laryngitis) mit heiserer Stimme und Trockenheit', 'Hodenentzündung (Orchitis) mit schmerzhafter Schwellung', 'Schilddrüsenvergrößerung (Struma) mit Erstickungsgefühl'],
      keynotes: ['Husten klingt exakt wie das Sägen von Holz („Sägehusten“)', 'Kehlkopf fühlt sich staubtrocken an, zwingt zu ständigem Räuspern', 'Erwachen vor Mitternacht (gegen 23:00–24:00 Uhr) mit akuter Erstickungsnot', 'Trinken von warmem Wasser bringt augenblickliche Erleichterung'],
      mindEmotional: 'Panische Erstickungsangst, fürchtet zu sterben beim Hustenanfall.',
      modalitiesBetter: ['Warme Getränke & feuchtwarm inhalieren', 'Kopf tief lagern'],
      modalitiesWorse: ['Vor Mitternacht', 'Kalter, trockener Wind', 'Liegen mit flachem Kopf'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Kruppanfall C30 alle 15–30 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Larynx & Trachea (Pseudokrupp)', 'Schilddrüse & Kehlkopfknorpel', 'Hoden & Samenstränge'],
      differentialRemedies: ['Aconitum (vor Mitternacht, heiß, Panik)', 'Hepar sulfuris (nach Mitternacht, eitrig)', 'Sambucus', 'Drosera'],
      searchKeywords: ['meerschwamm', 'spongia', 'pseudokrupp', 'krupp', 'sägehusten', 'bellhusten', 'kehlkopf', 'warme getränke bessern']
    },
    en: {
      commonName: 'Roasted Sea Sponge',
      origin: 'Genuine roasted marine sponge.',
      essence: 'The supreme croup remedy: dry, barking, hollow, crowing cough "like a saw driven through dry pine wood"; awakening before midnight in suffocative panic; dramatic relief from warm drinks and warm steam.',
      mainIndications: ['Acute spasmodic croup in children with barking saw-like cough', 'Laryngitis with hoarseness, dryness, and suffocative spasms', 'Acute orchitis and epididymitis with hard swelling', 'Goiter with sensation of constriction and suffocation'],
      keynotes: ['Cough sounds like a wood saw driven through dry board', 'Larynx feels dry as a bone, provoking continuous cough', 'Awakens abruptly before midnight (11:00 PM to midnight) suffocating with fright', 'Drinking warm liquids affords immediate dramatic relief'],
      mindEmotional: 'Suffocative terror, fears sudden death during paroxysms.',
      modalitiesBetter: ['Warm drinks & warm moist steam inhalation', 'Lying with head low'],
      modalitiesWorse: ['Before midnight', 'Cold dry winds', 'Lying flat on back'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In croup attack C30 every 15–30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Larynx & Tracheal Mucosa (Croup)', 'Thyroid Gland', 'Testes & Spermatic Cords'],
      differentialRemedies: ['Aconitum (first stage before midnight, intense panic)', 'Hepar sulfuris (after midnight, loose)', 'Sambucus', 'Drosera'],
      searchKeywords: ['sponge', 'spongia', 'croup', 'barking cough', 'saw cough', 'warm drinks relieve', 'larynx', 'suffocation']
    },
    es: { commonName: 'Esponja tostada' },
    fr: { commonName: 'Éponge torréfiée' },
    el: { commonName: 'Ψημένος σπόγγος' },
    it: { commonName: 'Spugna tostata' },
    ru: { commonName: 'Губка жженая / Спонгия' }
  },
  {
    id: 'staphisagria',
    latinName: 'Delphinium staphisagria',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Stephanskörner / Stephanskraut',
      origin: 'Getrocknete reife Samen des Stephanskrauts (Ranunculaceae).',
      essence: 'Das Hauptmittel für unterdrückten Zorn, Entrüstung, Kränkung und Demütigung: Flitterwochen-Zystitis (Honeymoon-Cystitis) mit ständigem Brennen beim und nach dem Wasserlassen; Gerstenkörner (Hagelkörner) an den Augenlidern und Schmerzen nach Schnittwunden (z.B. nach Operationen/Kaiserschnitt).',
      mainIndications: ['Honeymoon-Zystitis (Blasenentzündung nach Geschlechtsverkehr)', 'Folgen von unterdrückter Wut, Kränkung, Demütigung & Beleidigung', 'Rezidivierende Hagelkörner (Chalazien) & Gerstenkörner an den Augenlidern', 'Schmerzen nach Schnittwunden, Skalpell-Schnitten & Kaiserschnitt', 'Schwarzer Kariesbefall der Zahnkronen bei Kindern'],
      keynotes: ['Brennen in der Harnröhre, wenn man NICHT uriniert (hört während des Urinierens auf)', 'Krankheiten entstehen nach unterdrücktem Zorn (hat die Wut hinuntergeschluckt)', 'Harte Hagelkörner an den Lidrändern, die Knötchen hinterlassen', 'Saubere Schnittwunden durch Messer oder Skalpell tun extrem weh'],
      mindEmotional: 'Überempfindlich gegen das geringste Wort, schluckt Wut hinunter, zittert vor Zorn, wirft Gegenstände weg.',
      modalitiesBetter: ['Wärme', 'Ruhe', 'Nach dem Frühstück'],
      modalitiesWorse: ['Unterdrückte Gefühle & Kränkung', 'Geschlechtsverkehr & Katheterisierung', 'Kälte & Berührung'],
      potenciesAndDosage: 'Akut: D6, D12, C30, C200. Nach Blasenkatheter oder Schnitt-OP C30.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Urogenitaltrakt (Harnröhre & Blase)', 'Lider & Meibom-Drüsen (Chalazion)', 'Gefühlsleben & Wutreflex'],
      differentialRemedies: ['Cantharis (Brennen WÄHREND Urinieren)', 'Colocynthis (Zornkolik)', 'Arnica', 'Ignatia'],
      searchKeywords: ['stephanskörner', 'staphisagria', 'honeymoon zystitis', 'blasenentzündung', 'unterdrückte wut', 'kränkung', 'chalazion', 'gerstenkorn', 'schnittwunde']
    },
    en: {
      commonName: 'Stavesacre',
      origin: 'Dried ripe seeds of Delphinium staphisagria (Ranunculaceae).',
      essence: 'The supreme suppressed anger, indignity, humiliation, and honeymoon cystitis polychrest: constant burning in urethra when not urinating; chalazia/styes on eyelids; agonizing pains after clean surgical incisions (scalpel/episiotomy).',
      mainIndications: ['Honeymoon cystitis after coitus or catheterization', 'Ailments from suppressed indignation, mortification, and wounded pride', 'Recurrent chalazia & styes leaving hard nodules on eyelids', 'Severe post-surgical incisional pains (laparotomy, episiotomy, C-section)', 'Premature carious blackening of infant teeth crowns'],
      keynotes: ['Burning in urethra ceases while urinating, returns instantly when finished', 'Illnesses triggered by swallowed anger and suppressed insults', 'Hard indurated chalazia on eyelid borders', 'Exquisite tenderness of clean incised wounds from sharp surgical instruments'],
      mindEmotional: 'Hypersensitive to slightest offense, trembles with suppressed rage, throws things.',
      modalitiesBetter: ['Warmth', 'Rest', 'After breakfast'],
      modalitiesWorse: ['Suppressed emotion & wounded pride', 'Sexual intercourse & catheterization', 'Cold drafts'],
      potenciesAndDosage: 'Acute: D6, D12, C30, C200 / 6C, 30C, 200C. After catheter or incision C30.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Urinary Tract & Urethral Sphincter', 'Eyelids & Meibomian Glands', 'Emotional Nervous System'],
      differentialRemedies: ['Cantharis (burning DURING urination)', 'Colocynthis (anger colic)', 'Arnica', 'Ignatia'],
      searchKeywords: ['stavesacre', 'staphisagria', 'honeymoon cystitis', 'suppressed anger', 'mortification', 'chalazion', 'stye', 'incision pain']
    },
    es: { commonName: 'Estafisagria / Hierba piojera' },
    fr: { commonName: 'Staphisaigre / Herbe aux poux' },
    el: { commonName: 'Σταφισάγρια' },
    it: { commonName: 'Stafisagria' },
    ru: { commonName: 'Стафизагрия / Стефаново семя' }
  },
  {
    id: 'stramonium',
    latinName: 'Datura stramonium',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Gemeiner Stechapfel',
      origin: 'Ganze frische blühende Pflanze des Stechapfels (Solanaceae).',
      essence: 'Panische Angst vor Dunkelheit und Alleinsein (braucht Licht und Gesellschaft): Nachtschreck (Pavor nocturnus) bei Kindern mit schreiendem Erwachen und wildem Umherstarren; Raserei, Halluzinationen von wilden Tieren und hydrophobische Krämpfe beim Anblick von Wasser oder glänzenden Gegenständen.',
      mainIndications: ['Pavor nocturnus (Nachtschreck) bei Kindern mit Schlafwandeln', 'Panische Furcht vor Dunkelheit & Verlassenheit', 'Fieberdelirium mit wilden Halluzinationen & Beißdrang', 'Stottern & Tics nach schwerem Schreckerlebnis'],
      keynotes: ['Kann absolut keine Dunkelheit ertragen: muss bei voller Beleuchtung schlafen', 'Schreckt nachts schreiend aus dem Schlaf auf und erkennt niemanden', 'Entsetzliche Visionen von Ungeheuern, Hunden und Fratzen', 'Hydrophobie: Krämpfe beim Sehen von Wasser, Spiegeln oder glänzenden Flächen'],
      mindEmotional: 'Panische Todesangst, flieht vor Halluzinationen, klammert sich an Bezugspersonen, beißt und schlägt im Wahn.',
      modalitiesBetter: ['Helles Licht im Zimmer', 'Anwesenheit vertrauter Menschen', 'Wärme'],
      modalitiesWorse: ['Dunkelheit & Alleinsein', 'Glänzende Gegenstände & Spiegel', 'Nach dem Schlaf'],
      potenciesAndDosage: 'C30 bis C200. Bei Nachtschreck C30 abends.',
      defaultTagesdosis: '1 Gabe à 3–5 Globuli',
      sphereOfAction: ['Gehirn & Psychomotorik', 'Schlaf- & Traumregulation', 'Kehlkopfkrämpfe'],
      differentialRemedies: ['Belladonna (Hitze, Rötung, Pochen)', 'Hyoscyamus (schamlos, eifersüchtig)', 'Aconitum'],
      searchKeywords: ['stechapfel', 'stramonium', 'nachtschreck', 'pavor nocturnus', 'dunkelangst', 'licht verlangen', 'halluzinationen', 'stottern']
    },
    en: {
      commonName: 'Thorn Apple / Jimsonweed',
      origin: 'Whole fresh flowering plant of Datura stramonium (Solanaceae).',
      essence: 'Terrified fear of darkness and solitude (must have bright light and company): night terrors (pavor nocturnus) in children with screaming awakening; wild hallucinations of monsters/dogs; hydrophobic throat spasms from glistening objects.',
      mainIndications: ['Pavor nocturnus (night terrors) in children waking in screams', 'Panic fear of darkness & being abandoned', 'Violent febrile delirium with visual hallucinations', 'Spasmodic stammering & tics after fright'],
      keynotes: ['Cannot tolerate darkness: must sleep with full room lights on', 'Awakens in terror screaming, not recognizing parents or surroundings', 'Terrifying hallucinations of ghosts, ferocious dogs, and devils', 'Hydrophobia: throat spasms provoked by water, mirrors, or shining surfaces'],
      mindEmotional: 'Frantic terror, flees delusions, clings desperately to bystander, bites and strikes in delirium.',
      modalitiesBetter: ['Bright light & sunshine', 'Company of trusted persons', 'Warmth'],
      modalitiesWorse: ['Darkness & solitude', 'Glistening objects & mirrors', 'Immediately on waking'],
      potenciesAndDosage: 'C30 to C200 / 30C, 200C. In night terrors C30 at bedtime.',
      defaultTagesdosis: '1 dose of 3–5 pellets',
      sphereOfAction: ['Cerebrospinal Axis & Sensorium', 'Sleep-Wake & Fear Circuits', 'Laryngeal Motor Reflexes'],
      differentialRemedies: ['Belladonna (heat, redness, throbbing)', 'Hyoscyamus (shameless, jealousy)', 'Aconitum'],
      searchKeywords: ['stramonium', 'thorn apple', 'night terrors', 'pavor nocturnus', 'fear of dark', 'light craving', 'hallucinations', 'stammering']
    },
    es: { commonName: 'Estramonio / Manzana espinosa' },
    fr: { commonName: 'Stramoine / Pomme épineuse' },
    el: { commonName: 'Στραμώνιο' },
    it: { commonName: 'Stramonio' },
    ru: { commonName: 'Дурман обыкновенный / Страмониум' }
  },
  {
    id: 'sulphur',
    latinName: 'Sulphur depuratum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Gereinigte Schwefelblume / Schwefel',
      origin: 'Reiner sublimierter Schwefel (S).',
      essence: 'Der „König der Polychreste“: Unordentlicher Philosoph, Hitzeintoleranz, brennende Schmerzen an allen Körperöffnungen (besonders brennende Fußsohlen, die nachts unter der Bettdecke hervorgestreckt werden), Verlangen nach Süßigkeiten, chronischer Heißhunger um 11:00 Uhr und Reaktivierung blockierter Heilungsverläufe.',
      mainIndications: ['Chronische Hauterkrankungen (Ekzeme, Psoriasis, Akne) mit unerträglichem Juckreiz', 'Chronische Reaktionslosigkeit (bringt blockierte Fälle wieder in Fluss)', 'Frühmorgendlicher Durchfall treibt um 05:00 Uhr aus dem Bett', 'Heißhunger & Leeregefühl im Magen um Punkt 11:00 Uhr vormittags', 'Brennende Fußsohlen im Bett nachts'],
      keynotes: ['Brennende Fußsohlen im Bett: streckt nachts instinktiv die Füße unter der Decke hervor', 'Unerträglicher Hautjuckreiz: Verschlimmerung durch warmes Wasser und Waschen', 'Heißhunger und flaues Magengefühl exakt um 11:00 Uhr', 'Alle Körperöffnungen sind feuerrot (rote Lippen, rote Lidränder, roter Anus)', 'Widerwillen gegen Baden und Waschen'],
      mindEmotional: 'Philosophisch, unordentlich, egoistisch, sammelt alten Krempel („Lumpen sind Seide“), intellektuell rege.',
      modalitiesBetter: ['Trockenes warmes Wetter', 'Im Freien', 'Bewegung'],
      modalitiesWorse: ['Bettwärme & Wärme', 'Waschen & Baden', 'Um 11:00 Uhr vormittags', 'Stehen (kann nicht stillstehen)'],
      potenciesAndDosage: 'D6 bis C200. Konstitutionell C30 1x wöchentlich.',
      defaultTagesdosis: '1 Gabe à 3–5 Globuli',
      sphereOfAction: ['Haut & Schleimhäute', 'Pfortadersystem & Magen-Darm', 'Gesamter Zellstoffwechsel'],
      differentialRemedies: ['Psorinum (extrem frostig, Schmutzgeruch)', 'Lycopodium', 'Nux vomica', 'Calcarea carbonica'],
      searchKeywords: ['schwefel', 'sulphur', 'juckreiz', 'brennende fußsohlen', '11uhr heißhunger', 'ekzem', 'philosoph', 'unordentlich', 'baden verschlimmert']
    },
    en: {
      commonName: 'Sublimed Flowers of Sulfur',
      origin: 'Pure sublimed sulfur.',
      essence: 'The supreme "King of Polychrests": ragged philosopher, heat intolerant, burning at all body orifices (especially burning soles of feet stuck out of bed covers at night), craving sweets, 11:00 AM ravenous hunger, and unlocking blocked vitality in chronic cases.',
      mainIndications: ['Chronic dermatoses (eczema, psoriasis, acne) with fierce itching', 'Lack of vital reaction in stalled, blocked chronic cases', 'Early morning painless diarrhea driving out of bed at 5:00 AM', 'Ravenous sinking hunger at pit of stomach punctually at 11:00 AM', 'Burning soles of feet sticking out of bedcovers at night'],
      keynotes: ['Burning heat in soles of feet compelling sticking feet out from under bedcovers', 'Intolerable voluptuous skin itching violently aggravated by warm bathing', 'Faint, empty ravenous hunger at exactly 11:00 AM', 'All body orifices are fiery bright red (lips, nostrils, eyelids, anus)', 'Aversion to washing and bathing'],
      mindEmotional: 'Philosophical, untidy, selfish, intellectual dreamer, values worthless items.',
      modalitiesBetter: ['Dry warm weather', 'Open cool air', 'Continuous motion'],
      modalitiesWorse: ['Warmth of bed', 'Washing & bathing with water', '11:00 AM', 'Standing still (cannot stand)'],
      potenciesAndDosage: 'D6 to C200 / 6C, 30C, 200C. Constitutionally C30 once weekly.',
      defaultTagesdosis: '1 dose of 3–5 pellets',
      sphereOfAction: ['Skin & Mucous Membranes', 'Portal Venous System & Digestion', 'Universal Cellular Metabolism'],
      differentialRemedies: ['Psorinum (extremely chilly, offensive odor)', 'Lycopodium', 'Nux vomica', 'Calcarea carbonica'],
      searchKeywords: ['sulfur', 'sulphur', 'itching', 'burning soles of feet', '11am hunger', 'eczema', 'philosopher', 'aversion to bathing']
    },
    es: { commonName: 'Azufre / Flor de azufre' },
    fr: { commonName: 'Soufre purifié / Fleur de soufre' },
    el: { commonName: 'Θείο' },
    it: { commonName: 'Zolfo' },
    ru: { commonName: 'Сера очищенная / Сульфур' }
  },
  {
    id: 'symphytum-officinale',
    latinName: 'Symphytum officinale',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Echter Beinwell / Knochenheil',
      origin: 'Frische Wurzel des Beinwells vor der Blüte (Boraginaceae).',
      essence: 'Das „Arnika der Knochen“: Beschleunigt die Kallusbildung bei Knochenbrüchen (Frakturen), heilt stumpfe Augenapfelverletzungen (z.B. Treffer durch Tennisball/Schneeball) und lindert Phantomschmerzen an Amputationsstümpfen.',
      mainIndications: ['Knochenbrüche (beschleunigt Heilung & Kallusbildung nach Reposition)', 'Stumpfe Traumata des Augapfels (Tennisball, Faustschlag, Schneeball)', 'Knochenschmerzen nach alten Frakturen bei Wetterwechsel', 'Reizung des Periosts & Schienbeinkanten-Syndrom'],
      keynotes: ['Fördert die Knochenneubildung nach erfolgter Frakturreposition', 'Spezifisches Mittel für stumpfe Verletzungen direkt am Bulbus (Augapfel)', 'Stechende Schmerzen im Knochen an der Bruchstelle'],
      mindEmotional: 'Geduldig, erträgt Schmerzen stoisch.',
      modalitiesBetter: ['Ruhigstellung & Schienung', 'Sanfte Wärme'],
      modalitiesWorse: ['Berührung & Bewegung des Knochens', 'Wetterwechsel'],
      potenciesAndDosage: 'D4 bis C30. Nach Knochenbruch D6 3x täglich über 3–4 Wochen.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Knochengewebe & Periost (Kallusbildung)', 'Bulbus oculi (Augapfeltrauma)', 'Amputationsstümpfe'],
      differentialRemedies: ['Arnica (Weichteiltrauma)', 'Ruta (Sehnen & Knochenhaut)', 'Ledum (blaues Auge)', 'Calcarea phosphorica'],
      searchKeywords: ['beinwell', 'symphytum', 'knochenbruch', 'fraktur', 'kallus', 'augapfelverletzung', 'tennisball auge', 'knochenheil']
    },
    en: {
      commonName: 'Comfrey / Knitbone',
      origin: 'Fresh root of Symphytum officinale (Boraginaceae).',
      essence: 'The "Arnica of the Bones": stimulates rapid callus formation in fractures (after proper setting); heals blunt mechanical eyeball trauma (blow from tennis ball/snowball); relieves bone stump pain.',
      mainIndications: ['Bone fractures (accelerates callus formation after orthopedic setting)', 'Blunt mechanical trauma to eyeball (tennis ball, snowball, blunt blow)', 'Aching pains at site of old fractures in damp weather', 'Periostitis & shin splints in athletes'],
      keynotes: ['Promotes rapid osseous union and bridging callus in fractures', 'Specific affinity for mechanical contusions directly to the ocular globe', 'Pricking sharp bone pains at fracture junction'],
      mindEmotional: 'Stoic, patient, endures skeletal recovery calmly.',
      modalitiesBetter: ['Splinting & immobility', 'Gentle warmth'],
      modalitiesWorse: ['Touch & motion of bone', 'Damp weather changes'],
      potenciesAndDosage: 'D4 to C30 / 4X to 30C. After fracture reduction D6 3 times daily for 3–4 weeks.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Bone Matrix & Periosteum (Callus)', 'Eyeball & Orbital Cavity', 'Amputation Stumps'],
      differentialRemedies: ['Arnica (soft tissue contusion)', 'Ruta (tendons & periosteum)', 'Ledum (black eye)', 'Calcarea phosphorica'],
      searchKeywords: ['comfrey', 'symphytum', 'fracture', 'bone healing', 'callus', 'eyeball injury', 'tennis ball eye', 'knitbone']
    },
    es: { commonName: 'Consuelda / Sinfito' },
    fr: { commonName: 'Grande consoude' },
    el: { commonName: 'Σύμφυτο' },
    it: { commonName: 'Consolida maggiore' },
    ru: { commonName: 'Окопник лекарственный / Симфитум' }
  }
];

console.log('REMEDIES_PART8_RS defined with count:', REMEDIES_PART8_RS.length);
