import { RawRemedy } from './buildRemedyUtils';

export const REMEDIES_PART7_OPQ: RawRemedy[] = [
  {
    id: 'opium',
    latinName: 'Papaver somniferum / Opium',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Schlafmohn / Opium',
      origin: 'Getrockneter Milchsaft der unreifen Samenkapseln des Schlafmohns (Papaveraceae).',
      essence: 'Völlige Schmerz- und Reaktionslosigkeit bei schwersten Krankheiten; tiefer komatöser Schlaf mit schnarchendem, rasselndem Atem (Stridor), rotes aufgedunsenes Gesicht und atonische Obstipation ohne jeglichen Stuhldrang.',
      mainIndications: ['Folgen von schwerem Schreck, Angst & Panik', 'Koma, Apoplex (Schlaganfall) & Schädel-Hirn-Trauma mit Stupor', 'Atonische Obstipation mit harten schwarzen Kotballen ohne Drang', 'Postoperativer Darmverschluss (paralytischer Ileus)'],
      keynotes: ['Völlige Schmerzlosigkeit bei Zuständen, die normalerweise extrem schmerzhaft sind', 'Tiefer, komatöser Schlaf mit lautem, schnarchendem Atem (Stertor)', 'Gesicht dunkelrot, heiß, geschwollen mit schweißiger Haut', 'Darm ist völlig gelähmt, kein Stuhldrang über Tage'],
      mindEmotional: 'Schläfrig, empfindet kein Leid, sagt, es fehle ihm gar nichts, Albträume nach Schreck.',
      modalitiesBetter: ['Kälte & kühle Luft', 'Fortgesetztes Umhergehen'],
      modalitiesWorse: ['Hitze & Wärme', 'Nach dem Schlaf', 'Alkohol & Beruhigungsmittel'],
      potenciesAndDosage: 'C30 bis C200. Nach Schreck oder Apoplex C30.',
      defaultTagesdosis: '1 Gabe à 3–5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Gehirn', 'Darmmotorik & vegetative Reflexe', 'Atmung'],
      differentialRemedies: ['Aconitum (Schreck mit Panik/Todesangst)', 'Gelsemium', 'Arnica', 'Helleborus'],
      searchKeywords: ['schlafmohn', 'opium', 'schmerzlos', 'reaktionslos', 'koma', 'schnarchen', 'schlaganfall', 'paralytischer ileus', 'schreck']
    },
    en: {
      commonName: 'Poppy / Opium',
      origin: 'Dried milky juice of Papaver somniferum (Papaveraceae).',
      essence: 'Complete painlessness and lack of reaction in severe acute pathology; deep comatose sleep with loud stertorous snoring breathing, bloated dusky face, and complete bowel paralysis without urge.',
      mainIndications: ['Ailments from severe fright, sudden shock & terror', 'Coma, apoplexy (stroke) & cerebral concussion with stupor', 'Atonic constipation with hard black round balls and zero urge', 'Post-operative paralytic ileus'],
      keynotes: ['Complete painlessness: complains of nothing in grave illness', 'Deep comatose sleep with loud rattling, stertorous breathing', 'Dark flushed dusky red bloated face bathed in hot sweat', 'Paralysis of intestines: no desire for stool for days'],
      mindEmotional: 'Drowsy, stuporous, denies illness ("nothing ails me"), terrors after fright.',
      modalitiesBetter: ['Cold air and cold applications', 'Constant walking'],
      modalitiesWorse: ['Heat & overheated rooms', 'During and after sleep', 'Stimulants and sedatives'],
      potenciesAndDosage: 'C30 to C200 / 30C, 200C. In fright or stroke aftermath C30.',
      defaultTagesdosis: '1 dose of 3–5 pellets',
      sphereOfAction: ['Cerebrospinal Axis & Brain', 'Gastrointestinal Motility', 'Respiratory Center'],
      differentialRemedies: ['Aconitum (fright with acute panic)', 'Gelsemium', 'Arnica', 'Helleborus'],
      searchKeywords: ['opium', 'poppy', 'painless', 'unresponsive', 'coma', 'snoring', 'stroke', 'paralytic ileus', 'fright']
    },
    es: { commonName: 'Opio / Adormidera' },
    fr: { commonName: 'Opium / Pavot somnifère' },
    el: { commonName: 'Όπιο' },
    it: { commonName: 'Oppio' },
    ru: { commonName: 'Опиум / Мак снотворный' }
  },
  {
    id: 'petroleum',
    latinName: 'Petroleum rectificatum',
    categoryKey: 'mineral',
    importanceTier: 1,
    de: {
      commonName: 'Steinöl / Bergöl',
      origin: 'Gereinigtes Steinöl / Erdöl.',
      essence: 'Tief eingerissene, blutende Hautrhagaden an den Fingerspitzen im Winter; schwere Reisekrankheit (Übelkeit beim Fahren im Auto, Schiff oder Flugzeug), die sich durch ständiges Essen bessert.',
      mainIndications: ['Reisekrankheit (Kinetose) im Auto, Boot oder Flugzeug', 'Schmerzhafte Rhagaden & Risse an Fingerspitzen und Fersen im Winter', 'Trockene, juckende Winterekzeme & Schuppenflechte'],
      keynotes: ['Übelkeit bei Reisekrankheit bessert sich vorübergehend durch Essen', 'Tiefe schmerzhafte Risse an den Händen, die im Winter aufspringen und bluten', 'Wahnidee, eine zweite Person liege mit im Bett oder ein Glied sei verdoppelt'],
      mindEmotional: 'Reizbar, streitsüchtig, verliert die Orientierung in Straßen.',
      modalitiesBetter: ['Essen (bessert Magenbeschwerden)', 'Trockene, warme Luft'],
      modalitiesWorse: ['Fahren in Fahrzeugen', 'Winter & kalte Luft', 'Feuchtigkeit'],
      potenciesAndDosage: 'D6 bis C30. Bei Reisekrankheit D6 vor und während der Fahrt.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Haut & Fingerkuppen', 'Gleichgewichtsorgan & Brechzentrum', 'Magen-Darm'],
      differentialRemedies: ['Cocculus (Reisekrankheit durch Schlafmangel)', 'Tabacum', 'Graphites', 'Sepia'],
      searchKeywords: ['steinöl', 'petroleum', 'reisekrankheit', 'kinetose', 'rhagaden', 'winterriss', 'fingerkuppen', 'essen bessert']
    },
    en: {
      commonName: 'Rectified Crude Rock Oil',
      origin: 'Purified petroleum.',
      essence: 'Deep bleeding fissures on fingertips aggravated in winter; severe motion sickness (nausea from riding in cars, boats, or airplanes) relieved by eating continuously.',
      mainIndications: ['Motion sickness (kinetosis) in vehicles, boats, and flights', 'Painful cracked fingertips and heel fissures in winter', 'Dry itchy winter eczema & palmar psoriasiform eruptions'],
      keynotes: ['Nausea from motion sickness is relieved temporarily by eating', 'Deep painful fissures of fingertips that crack and bleed in winter', 'Delusion that another person is lying in bed beside him or limbs are double'],
      mindEmotional: 'Irritable, easily offended, loses orientation in streets.',
      modalitiesBetter: ['Eating (relieves nausea)', 'Dry warm air'],
      modalitiesWorse: ['Riding in carriages/cars/boats', 'Winter & cold weather', 'Dampness'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. In motion sickness D6 before and during trip.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Skin (Palms, Fingers, Flexures)', 'Vestibular System & Nausea', 'Gastric Mucosa'],
      differentialRemedies: ['Cocculus (motion sickness from loss of sleep)', 'Tabacum', 'Graphites', 'Sepia'],
      searchKeywords: ['petroleum', 'motion sickness', 'car sickness', 'cracked fingertips', 'winter fissures', 'eating relieves']
    },
    es: { commonName: 'Petróleo rectificado' },
    fr: { commonName: 'Pétrole rectifié' },
    el: { commonName: 'Πετρέλαιο' },
    it: { commonName: 'Petrolio rettificato' },
    ru: { commonName: 'Нефть очищенная / Петролеум' }
  },
  {
    id: 'phosphoricum-acidum',
    latinName: 'Acidum phosphoricum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Phosphorsäure',
      origin: 'Reine konzentrierte Phosphorsäure (H3PO4).',
      essence: 'Apathische geistige und körperliche Erschöpfung nach akutem Kummer, Schock, Liebeskummer, Überarbeitung oder Verlust von Körpersäften; Patient sitzt stumm da, antwortet nur langsam und will seine Ruhe; schmerzlose, schwächende Durchfälle.',
      mainIndications: ['Totale Apathie & Burnout nach akutem Kummer oder Verlust', 'Chronisches Erschöpfungssyndrom nach schweren Infekten', 'Schmerzloser, chronischer, wässriger Durchfall (ohne Entkräftung)', 'Vorzeitiger Haarausfall nach Kummer und Schock'],
      keynotes: ['Völlige emotionale Gleichgültigkeit und Apathie gegen alles', 'Beantwortet Fragen nur langsam oder einsilbig nach langer Denkpause', 'Reichlicher milchig-trüber Urin', 'Schmerzlose wässrige Diarrhö, die den Patienten überraschenderweise kaum schwächt'],
      mindEmotional: 'Apathisch, gleichgültig gegen Angehörige, will nicht sprechen, stiller Kummer.',
      modalitiesBetter: ['Wärme', 'Nach kurzem Schlaf'],
      modalitiesWorse: ['Kummer & Sorgen', 'Geistige & körperliche Anstrengung', 'Verlust von Körpersäften'],
      potenciesAndDosage: 'D6 bis C200. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Psyche', 'Magen-Darm-Trakt', 'Haare & Vitalstoffe'],
      differentialRemedies: ['Ignatia (hysterischer, dramatischer Kummer)', 'Natrium muriaticum', 'China (Saftverlust)', 'Kalium phosphoricum'],
      searchKeywords: ['phosphorsäure', 'phosphoricum acidum', 'apathie', 'burnout', 'kummer', 'gleichgültigkeit', 'haarausfall', 'schmerzloser durchfall']
    },
    en: {
      commonName: 'Phosphoric Acid',
      origin: 'Pure concentrated phosphoric acid.',
      essence: 'Apathetic mental and physical burnout following grief, heartbreak, overstudy, or loss of vital fluids: patient sits silently, answers slowly, indifferent to everything; painless non-exhausting diarrhea.',
      mainIndications: ['Profound apathy & burnout from silent grief or loss', 'Chronic fatigue syndrome after debilitating infectious illness', 'Painless chronic watery diarrhea (remarkably non-debilitating)', 'Premature hair loss following intense sorrow and grief'],
      keynotes: ['Complete emotional apathy and indifference to all friends and activities', 'Answers questions slowly or in monosyllables after long hesitation', 'Profuse milky-turbid urine containing phosphates', 'Painless watery diarrhea that surprisingly does not exhaust the patient'],
      mindEmotional: 'Apathetic, listless, indifferent, desires silence, brooding over grief.',
      modalitiesBetter: ['Warmth', 'Short sleep'],
      modalitiesWorse: ['Grief & mental strain', 'Physical exertion', 'Loss of vital fluids'],
      potenciesAndDosage: 'D6 to C200 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Cerebrospinal Axis & Mind', 'Digestive Canal & Colon', 'Hair Follicles & Vital Fluids'],
      differentialRemedies: ['Ignatia (hysterical acute grief)', 'Natrium muriaticum', 'China (fluid loss)', 'Kalium phosphoricum'],
      searchKeywords: ['phosphoric acid', 'acid phos', 'apathy', 'burnout', 'grief', 'indifference', 'hair loss', 'painless diarrhea']
    },
    es: { commonName: 'Ácido fosfórico' },
    fr: { commonName: 'Acide phosphorique' },
    el: { commonName: 'Φωσφορικό οξύ' },
    it: { commonName: 'Acido fosforico' },
    ru: { commonName: 'Фосфорная кислота / Фосфорикум ацидум' }
  },
  {
    id: 'phosphorus',
    latinName: 'Phosphorus purus',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Gelber / Weißer Phosphor',
      origin: 'Reines elementares Phosphor.',
      essence: 'Das große Mittel für offene, mitfühlende Menschen mit Ängsten (Alleinsein, Dunkelheit, Gewitter): Brennende Schmerzen, Neigung zu Blutungen (hellrot, stillbar schwer), Heißhunger auf eiskalte Getränke und Speiseeis; Erbrechen von Flüssigkeiten, sobald sie im Magen warm werden.',
      mainIndications: ['Hämorrhagische Diathese & Blutungen (Nasenbluten, Zahnfleischbluten)', 'Akute Pneumonie, Bronchitis & Heiserkeit mit brennendem Schmerz', 'Gastritis & Erbrechen (bricht Wasser aus, sobald es im Magen warm wird)', 'Ängste vor Gewitter, Dunkelheit und Alleinsein'],
      keynotes: ['Unstillbares Verlangen nach eiskaltem Wasser und Speiseeis', 'Erbrechen von getrunkenem kaltem Wasser, sobald es im Magen warm geworden ist', 'Brennende Schmerzen in Handflächen, Wirbelsäule oder Magen', 'Hellrote, langanhaltende Blutungen selbst bei kleinen Wunden', 'Liegen auf der linken Seite ist unmöglich (Herzklopfen, Husten)'],
      mindEmotional: 'Offen, empathisch, feinfühlig, sucht Gesellschaft, panische Angst vor Gewitter und Dunkelheit.',
      modalitiesBetter: ['Eiskalte Getränke & Speisen', 'Schlaf & kurzes Nickerchen', 'Rechte Seite'],
      modalitiesWorse: ['Gewitter & Wetterwechsel', 'Alleinsein & Dunkelheit', 'Liegen auf der linken Seite', 'Dämmerung'],
      potenciesAndDosage: 'D6 bis C200. Bei Heiserkeit/Bronchitis C30 2x täglich.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Lunge & Atemwege (Pneumonie)', 'Blutgefäße & Gerinnung', 'Nervensystem & Magen'],
      differentialRemedies: ['Arsenicum album', 'Bryonia', 'Tuberculinum', 'Ferrum phosphoricum'],
      searchKeywords: ['phosphor', 'phosphorus', 'gewitterangst', 'blutung', 'eiskaltes wasser', 'heiserkeit', 'lunge', 'brennen', 'erbrechen']
    },
    en: {
      commonName: 'Yellow Phosphorus',
      origin: 'Pure elemental white/yellow phosphorus.',
      essence: 'The supreme open, sympathetic, anxious polychrest: fears solitude, darkness, and thunderstorms; burning pains, bleeding tendency (bright red, difficult to arrest), intense craving for ice-cold water and ice cream; vomiting water as soon as it warms in stomach.',
      mainIndications: ['Hemorrhagic diathesis & easy bleeding (epistaxis, gingival, wounds)', 'Acute pneumonia, bronchitis & hoarseness with raw burning chest', 'Gastritis & vomiting (vomits cold liquids as soon as they warm in stomach)', 'Terrors from thunderstorms, twilight, and being alone'],
      keynotes: ['Unquenchable craving for ice-cold drinks and ice cream', 'Vomiting of cold drinks the moment they become warm in stomach', 'Burning pains in palms, spine, stomach, or between scapulae', 'Bright red prolonged bleeding from even minor scratches', 'Cannot lie on left side (causes palpitations and cough)'],
      mindEmotional: 'Extroverted, affectionate, clairvoyant sensitivity, craves company, terrors during thunderstorms.',
      modalitiesBetter: ['Ice-cold drinks and food', 'Short refreshing sleep', 'Lying on right side'],
      modalitiesWorse: ['Thunderstorms & weather changes', 'Solitude & dark', 'Lying on left side', 'Twilight'],
      potenciesAndDosage: 'D6 to C200 / 6C, 30C, 200C. In bronchitis/hoarseness C30 twice daily.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Lungs & Respiratory Mucosa', 'Blood Vessels & Hemostasis', 'Cerebrospinal Axis & Stomach'],
      differentialRemedies: ['Arsenicum album', 'Bryonia', 'Tuberculinum', 'Ferrum phosphoricum'],
      searchKeywords: ['phosphorus', 'thunderstorm fear', 'bleeding', 'ice cold water', 'hoarseness', 'pneumonia', 'burning', 'sympathetic']
    },
    es: { commonName: 'Fósforo' },
    fr: { commonName: 'Phosphore' },
    el: { commonName: 'Φώσφορος' },
    it: { commonName: 'Fosforo' },
    ru: { commonName: 'Фосфор' }
  },
  {
    id: 'phytolacca-americana',
    latinName: 'Phytolacca decandra / Phytolacca americana',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Kermesbeere',
      origin: 'Frische Wurzel der Kermesbeere (Phytolaccaceae).',
      essence: 'Das Hauptmittel für schmerzhafte Brustdrüsenentzündung (Mastitis) und dunkle Tonsillitis: Brust steinhart, knotig und heiß; Schmerzen schießen beim Schlucken blitzartig in beide Ohren aus; unbezwingbarer Drang, die Zähne fest aufeinanderzubeißen.',
      mainIndications: ['Puerperale Mastitis (Brustentzündung) beim Stillen', 'Dunkelrote Follikulitis / Tonsillitis mit Ohrausstrahlung', 'Schmerzhafte schwere Lymphknotenschwellungen am Hals', 'Brustknoten & Mastopathie'],
      keynotes: ['Schmerzen beim Schlucken strahlen blitzartig direkt in die Ohren aus', 'Brustdrüse ist steinhart, heiß, extrem schmerzhaft beim Stillen', 'Unwiderstehlicher Drang, die Zähne oder den Kiefer fest zusammenzupressen', 'Rachen ist dunkelrot, livide oder bläulich geschwollen'],
      mindEmotional: 'Gleichgültig gegenüber dem eigenen Leben, mürrisch, stöhnt vor Schmerzen.',
      modalitiesBetter: ['Wärme & trockene Luft', 'Ruhe'],
      modalitiesWorse: ['Kaltes, nasses Wetter & Regen', 'Schlucken (besonders heißer Getränke)', 'Nachts'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Mastitis D6 alle 1–2 Stunden.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Mammae (Brustdrüsen)', 'Tonsillen & Rachen', 'Halslymphknoten'],
      differentialRemedies: ['Bryonia (Brust hart, jede Bewegung schmerzt)', 'Belladonna', 'Mercurius solubilis', 'Hepar sulfuris'],
      searchKeywords: ['kermesbeere', 'phytolacca', 'mastitis', 'brustentzündung', 'stillen', 'ohrausstrahlung', 'schlucken', 'zähne zusammenbeißen']
    },
    en: {
      commonName: 'Poke Root',
      origin: 'Fresh root of Phytolacca americana (Phytolaccaceae).',
      essence: 'The supreme remedy for painful breast mastitis and dusky tonsillitis: breasts stony hard, knotty, and inflamed; pains shoot like lightning into both ears upon swallowing; irresistible urge to bite teeth tightly together.',
      mainIndications: ['Puerperal mastitis in nursing mothers with stony breast', 'Follicular tonsillitis with pains radiating to ears on swallowing', 'Indurated painful cervical lymphadenopathy', 'Fibrocystic breast disease with tenderness'],
      keynotes: ['Pains shoot like an arrow into ears upon attempting to swallow', 'Mammary gland is stony hard, swollen, and excruciatingly painful when nursing', 'Irresistible impulse to bite or press teeth firmly together', 'Pharynx is dusky, dark red, or bluish swollen'],
      mindEmotional: 'Indifferent to life, morose, groans aloud with pain.',
      modalitiesBetter: ['Dry warm weather', 'Rest'],
      modalitiesWorse: ['Cold wet rainy weather', 'Swallowing (especially hot liquids)', 'Nighttime'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In acute mastitis D6 every 1–2 hours.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Mammary Glands (Mastitis)', 'Tonsils & Fauces', 'Cervical Lymph Nodes'],
      differentialRemedies: ['Bryonia (breast hard, motion agonizing)', 'Belladonna', 'Mercurius solubilis', 'Hepar sulfuris'],
      searchKeywords: ['poke root', 'phytolacca', 'mastitis', 'breast inflammation', 'pain to ears', 'swallowing', 'bite teeth']
    },
    es: { commonName: 'Fitolaca / Hierba carmín' },
    fr: { commonName: 'Phytolaque / Raisin d’Amérique' },
    el: { commonName: 'Φυτολάκκα' },
    it: { commonName: 'Fitolacca' },
    ru: { commonName: 'Лаконос американский / Фитолякка' }
  },
  {
    id: 'podophyllum-peltatum',
    latinName: 'Podophyllum peltatum',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Maiapfel / Entenfuß',
      origin: 'Frischer Wurzelstock des Maiapfels (Berberidaceae).',
      essence: 'Gewaltige, explosionsartige, schmerzlose Durchfälle: wässrig, übelriechend, schießen wie aus einer Spritzpistole hervor; treiben frühmorgens aus dem Bett und hinterlassen extremes Leeregefühl im Bauch.',
      mainIndications: ['Akute Sommerdiarrhö & Reisedurchfall', 'Zahnungsdurchfall bei Säuglingen mit Kopfrollen', 'Uterus- und Rektumprolaps bei chronischem Durchfall'],
      keynotes: ['Stuhl schießt explosionsartig in riesigen Mengen hervor („wie ein Brunnen“)', 'Extremes Schwäche- und Leeregefühl im Abdomen nach der Darmentleerung', 'Frühmorgendlicher Beginn ab 04:00 oder 05:00 Uhr morgens', 'Drückt während des Zahnens die Zähne oder Kiefer fest zusammen'],
      mindEmotional: 'Niedergeschlagen, stöhnt vor Erschöpfung nach Durchfall.',
      modalitiesBetter: ['Auf dem Bauch liegen', 'Wärme'],
      modalitiesWorse: ['Frühmorgens (04:00 bis 09:00 Uhr)', 'Sommerhitze', 'Während des Zahnens'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei akutem Durchfall nach jedem Stuhlgang 5 Globuli.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Dünn- & Dickdarm (Durchfall)', 'Leber & Gallenwege', 'Rektum (Prolaps)'],
      differentialRemedies: ['Aloe socotrina (unsicherer Schließmuskel)', 'Natrium sulfuricum', 'Veratrum album', 'Chamomilla'],
      searchKeywords: ['maiapfel', 'podophyllum', 'durchfall', 'explosionsartig', 'sommerdurchfall', 'zahnung', 'leeregefühl']
    },
    en: {
      commonName: 'Mayapple / Duck’s Foot',
      origin: 'Fresh rhizome of Podophyllum peltatum (Berberidaceae).',
      essence: 'Profuse, explosive, painless gushing diarrhea: watery, offensive, spurting out like a fire hose; drives out of bed in early morning and leaves a sensation of utter abdominal emptiness.',
      mainIndications: ['Acute summer diarrhea & traveler’s gastroenteritis', 'Dentition diarrhea in infants with head rolling', 'Prolapsus ani and uteri accompanying chronic diarrhea'],
      keynotes: ['Stool spurts out explosively in immense gushing quantities', 'Sensation of utter emptiness and exhaustion in abdomen after stool', 'Early morning onset from 4:00 to 9:00 AM', 'Clenches gums or grinds teeth during infant dentition'],
      mindEmotional: 'Depressed, exhausted, moans after watery evacuation.',
      modalitiesBetter: ['Lying on abdomen', 'Warmth'],
      modalitiesWorse: ['Early morning (4:00 to 9:00 AM)', 'Summer heat', 'During dentition'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In acute diarrhea 5 pellets after each stool.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Small & Large Intestine (Diarrhea)', 'Liver & Biliary Ducts', 'Rectum (Prolapse)'],
      differentialRemedies: ['Aloe socotrina (insecure sphincter)', 'Natrium sulfuricum', 'Veratrum album', 'Chamomilla'],
      searchKeywords: ['mayapple', 'podophyllum', 'explosive diarrhea', 'summer diarrhea', 'gushing stool', 'dentition', 'empty abdomen']
    },
    es: { commonName: 'Podófilo / Manzana de mayo' },
    fr: { commonName: 'Podophylle pelté / Pomme de mai' },
    el: { commonName: 'Ποδόφυλλο' },
    it: { commonName: 'Podofillo' },
    ru: { commonName: 'Подофилл щитовидный' }
  },
  {
    id: 'pulsatilla-pratensis',
    latinName: 'Pulsatilla pratensis',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Wiesen-Küchenschelle',
      origin: 'Ganze frische blühende Pflanze der Küchenschelle (Ranunculaceae).',
      essence: 'Das große Frauen- und Kindermittel: Sanftmütig, weinerlich, anhänglich, sucht Trost (Trost bessert sofort); ständige Wechselhaftigkeit aller Symptome (kein Stuhl wie der andere); milde, dicke, gelb-grüne Schleimabsonderungen; völlige Durstlosigkeit und dramatische Besserung an der frischen kühlen Luft.',
      mainIndications: ['Akute Otitis media (Mittelohrentzündung) bei weinerlichen Kindern', 'Katarrhe mit dickem, mildem, gelb-grünem Schleim', 'Menstruationsstörungen (verzögert, spärlich, wechselhaft)', 'Magenverstimmung nach fettem Essen (Schweinefleisch, Eis)', 'Stimmungsschwankungen & Weinerlichkeit'],
      keynotes: ['Tröstung bessert augenblicklich (sucht Zuwendung, Umarmung)', 'Völlige Durstlosigkeit bei allen Krankheitszuständen (selbst bei Fieber)', 'Symptome wechseln ständig (keine zwei Schmerzen oder Stühle sind gleich)', 'Muss an die frische Luft: verträgt absolut keine warmen, geschlossenen Räume', 'Sekrete sind dick, cremig, gelb-grün und völlig schmerzlos/mild'],
      mindEmotional: 'Sanft, anhänglich, weinerlich, schüchtern, gibt schnell nach, sucht Liebe und Trost.',
      modalitiesBetter: ['Frische kühle Luft & Spaziergang im Freien', 'Trost & Zuwendung', 'Kalte Umschläge', 'Aufrechtes Sitzen'],
      modalitiesWorse: ['Warme, stickige Zimmer & Bettwärme', 'Fettes Essen, Torten, Schweinefleisch & Eis', 'Abends & in der Ruhe'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Otitis media C30 alle 2 Stunden.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Schleimhäute (Ohren, Nase, Bronchien)', 'Weibliche Genitalorgane & Hormone', 'Magen-Darm-Trakt & Gemüt'],
      differentialRemedies: ['Silicea', 'Natrium muriaticum (Trost verschlimmert)', 'Sepia', 'Chamomilla (zornig, schlägt um sich)'],
      searchKeywords: ['küchenschelle', 'pulsatilla', 'trost bessert', 'weinerlich', 'mittelohrentzündung', 'gelbgrüner schleim', 'durstlos', 'frische luft', 'fettes essen']
    },
    en: {
      commonName: 'Windflower / Pasqueflower',
      origin: 'Whole fresh flowering plant of Pulsatilla pratensis (Ranunculaceae).',
      essence: 'The supreme pediatric and female polychrest: gentle, yielding, tearful, craves consolation (consolation brings instant relief); ever-changing shifting symptoms (no two stools alike); thick, bland, yellowish-green mucous discharges; complete absence of thirst; dramatic relief in cool open air.',
      mainIndications: ['Acute otitis media in weeping affectionate children', 'Catarrhs with thick, creamy, bland, yellow-green mucus', 'Delayed, scanty, shifting menstrual irregularities', 'Dyspepsia from rich fatty food, pork, pastries, or ice cream', 'Tearful mood swings & emotional neediness'],
      keynotes: ['Consolation and sympathy bring instant soothing and relief', 'Complete lack of thirst in all febrile and acute complaints', 'Ever-changing symptoms: pains shift rapidly from joint to joint', 'Craves open cool air; cannot tolerate warm stuffy rooms', 'Discharges are thick, bland, non-irritating, and yellow-green'],
      mindEmotional: 'Gentle, affectionate, weeping, timid, clingy, craves affection and hugs.',
      modalitiesBetter: ['Cool open air & gentle slow walking', 'Consolation & affection', 'Cold compresses', 'Sitting erect'],
      modalitiesWorse: ['Warm stuffy rooms & bed heat', 'Rich fatty food, pork, pastries & ice cream', 'Evening & at rest'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In earaches C30 every 2 hours.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Mucous Membranes (Ears, Nasopharynx, Lungs)', 'Female Reproductive Axis', 'Gastrointestinal Canal & Mind'],
      differentialRemedies: ['Silicea', 'Natrium muriaticum (consolation aggravates)', 'Sepia', 'Chamomilla (angry, snappish)'],
      searchKeywords: ['windflower', 'pulsatilla', 'consolation improves', 'weeping', 'earache', 'yellow green discharge', 'thirstless', 'open air', 'fatty food']
    },
    es: { commonName: 'Pulsatila / Flor del viento' },
    fr: { commonName: 'Pulsatille / Anémone des prés' },
    el: { commonName: 'Πουλσατίλλα' },
    it: { commonName: 'Pulsatilla' },
    ru: { commonName: 'Прострел луговой / Пульсатилла' }
  },
  {
    id: 'pyrogenium',
    latinName: 'Pyrogenium',
    categoryKey: 'nosode',
    importanceTier: 1,
    de: {
      commonName: 'Pyrogenium (Septisches Nosodenpräparat)',
      origin: 'Nosode aus zersetztem magerem Rindfleisch (Pyrogen).',
      essence: 'Das homöopathische Antiseptikum für schwere septische Zustände: Ausgeprägte Diskrepanz zwischen Puls und Temperatur (rasender Puls bei mäßigem Fieber oder umgekehrt); stinkende Ausscheidungen und das Gefühl, das Bett sei steinhart (muss sich ständig bewegen).',
      mainIndications: ['Septische Fieberzustände, Puerperalfieber & Blutvergiftung', 'Schwere fieberhafte Infekte mit eitrigen Herden', 'Zerschlagenheitsgefühl mit Ruhelosigkeit (Bett zu hart)'],
      keynotes: ['Diskrepanz: Extrem schneller Puls bei mäßigem Fieber (oder umgekehrt)', 'Alle Ausscheidungen (Schweiß, Eiter, Stuhl) riechen aasig-stinkend', 'Gefühl, das Bett sei so hart, dass alle Knochen wehtun (ständiges Hin- und Herwälzen)'],
      mindEmotional: 'Delirant, glaubt, sein Körper sei zerstreut oder bestehe aus zwei Personen.',
      modalitiesBetter: ['Fortgesetzte Bewegung', 'Wärme'],
      modalitiesWorse: ['Ruhe', 'Kälte'],
      potenciesAndDosage: 'C30 bis C200. Bei septischen Zuständen C30 alle 2–4 Stunden.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Blut & retikuloendotheliales System (Sepsis)', 'Herz-Kreislauf & Puls', 'Muskeln & Bindegewebe'],
      differentialRemedies: ['Arnica (Bett zu hart, aber apathisch)', 'Baptisia (stinkend, schlaftrunken)', 'Echinacea'],
      searchKeywords: ['pyrogenium', 'sepsis', 'blutvergiftung', 'stinkend', 'puls temperatur diskrepanz', 'bett zu hart', 'fieber']
    },
    en: {
      commonName: 'Pyrogen / Septic Nosode',
      origin: 'Nosode prepared from decomposed lean beef.',
      essence: 'The supreme homeopathic antiseptic for severe septic conditions: marked discrepancy between pulse and temperature (racing rapid pulse with moderate fever or vice versa); horribly offensive discharges; bed feels too hard (restless tossing).',
      mainIndications: ['Septic fevers, puerperal sepsis & toxemia', 'Severe infectious states with purulent foci', 'Bruised aching with restless tossing (bed feels too hard)'],
      keynotes: ['Discrepancy: extremely rapid pulse out of all proportion to temperature', 'All discharges (sweat, lochia, stool, pus) are putrid and horribly offensive', 'Bed feels stony hard, compelling constant restless shifting of position'],
      mindEmotional: 'Delirious in fever, imagines parts of body are scattered or double.',
      modalitiesBetter: ['Continuous motion', 'Warmth'],
      modalitiesWorse: ['Absolute rest', 'Cold drafts'],
      potenciesAndDosage: 'C30 to C200 / 30C, 200C. In septic fevers C30 every 2–4 hours.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Blood & Reticuloendothelial System (Sepsis)', 'Cardiac Conduction & Pulse', 'Muscles & Connective Tissue'],
      differentialRemedies: ['Arnica (bed hard, but motionless stupor)', 'Baptisia (foul, besotted)', 'Echinacea'],
      searchKeywords: ['pyrogenium', 'sepsis', 'blood poisoning', 'offensive discharge', 'pulse temperature discrepancy', 'bed too hard']
    },
    es: { commonName: 'Pirogenio' },
    fr: { commonName: 'Pyrogénium' },
    el: { commonName: 'Πυρογένιο' },
    it: { commonName: 'Pirogenio' },
    ru: { commonName: 'Пирогениум' }
  }
];

console.log('REMEDIES_PART7_OPQ defined with count:', REMEDIES_PART7_OPQ.length);
