import { RawRemedy } from './buildRemedyUtils';

export const REMEDIES_PART2_BC: RawRemedy[] = [
  {
    id: 'bacillinum',
    latinName: 'Bacillinum Burnett',
    categoryKey: 'nosode',
    importanceTier: 2,
    de: {
      commonName: 'Tuberkulose-Nosode',
      origin: 'Mazeriertes tuberkulöses Lungengewebe nach Dr. Burnett.',
      essence: 'Nosode für tuberkulöse Diathese, chronische Erkältungsneigung und quälenden Reizhusten bei Nacht.',
      mainIndications: ['Chronische Bronchitis & rezidivierende Infekte', 'Drüsenschwellungen bei Kindern', 'Ekzeme und Ringelflechte'],
      keynotes: ['Ständiges Sich-Erkälten ohne ersichtlichen Anlass', 'Husten nachts und beim Zubettgehen', 'Kopfschmerz wie ein eng anliegender eiserner Reifen'],
      mindEmotional: 'Reizbar, mürrisch, melancholisch, ruhelos.',
      modalitiesBetter: ['Wärme'],
      modalitiesWorse: ['Kälte & Nässe', 'Nacht'],
      potenciesAndDosage: 'C30 bis C200. Nur in seltenen Einzelgaben (1x monatlich).',
      defaultTagesdosis: '1 Gabe à 5 Globuli',
      sphereOfAction: ['Lunge & Atemwege', 'Lymphknoten', 'Haut'],
      differentialRemedies: ['Tuberculinum', 'Drosera', 'Phosphorus'],
      searchKeywords: ['nosode', 'bacillinum', 'husten', 'infektanfälligkeit', 'drüsen']
    },
    en: {
      commonName: 'Burnett’s Bacillinum',
      origin: 'Macerated tuberculous lung tissue according to Dr. Burnett.',
      essence: 'Nosode for tubercular diathesis, constant tendency to take cold, and suffocative nocturnal cough.',
      mainIndications: ['Chronic recurrent respiratory infections', 'Glandular swelling in children', 'Ringworm and stubborn eczema'],
      keynotes: ['Takes cold upon slightest exposure', 'Cough worse at night and on retiring', 'Headache as if bound by an iron hoop'],
      mindEmotional: 'Fretful, morose, restless, melancholic.',
      modalitiesBetter: ['Warmth'],
      modalitiesWorse: ['Cold and damp', 'Night'],
      potenciesAndDosage: 'C30 to C200. Single infrequent doses.',
      defaultTagesdosis: '1 dose of 5 pellets',
      sphereOfAction: ['Lungs & Respiratory Tract', 'Lymphatic Glands', 'Skin'],
      differentialRemedies: ['Tuberculinum', 'Drosera', 'Phosphorus'],
      searchKeywords: ['nosode', 'bacillinum', 'cough', 'colds', 'glands']
    },
    es: { commonName: 'Bacillinum' },
    fr: { commonName: 'Bacillinum' },
    el: { commonName: 'Βακιλλίνο' },
    it: { commonName: 'Bacillinum' },
    ru: { commonName: 'Бациллинум' }
  },
  {
    id: 'baptisia-tinctoria',
    latinName: 'Baptisia tinctoria',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Wilder Indigo',
      origin: 'Frische Wurzelrinde des Wilden Indigos (Fabaceae).',
      essence: 'Schwerste septische Zustände mit Benommenheit (wie betrunken), stinkenden Absonderungen und dem Wahn, der Körper sei in Teile zerfallen.',
      mainIndications: ['Septisches Fieber & Typhuszustände', 'Faule Angina & schwere Stomatitis', 'Extreme körperliche Zerschlagenheit bei Grippe'],
      keynotes: ['Fühlt sich in Teile zerstreut und versucht die Teile im Bett zusammenzuholen', 'Alle Absonderungen (Atem, Schweiß, Stuhl) riechen extrem übel', 'Dunkelrotes, schläfrig-stumpfes Gesicht'],
      mindEmotional: 'Schläft mitten im Satz beim Antworten ein, verwirrt, apathisch.',
      modalitiesBetter: ['Mäßige Bewegung'],
      modalitiesWorse: ['Druck', 'Aufwachen', 'Geschlossene Räume'],
      potenciesAndDosage: 'D4 bis C30. Im akuten septischen Zustand D6 stündlich.',
      defaultTagesdosis: '3–4 Gaben à 5 Globuli',
      sphereOfAction: ['Blut & Immunsystem', 'Schleimhäute & Rachen', 'Gehirn'],
      differentialRemedies: ['Pyrogenium', 'Arnica', 'Gelsemium', 'Rhus tox'],
      searchKeywords: ['septisch', 'indigo', 'baptisia', 'körperteile', 'gestank', 'typhus']
    },
    en: {
      commonName: 'Wild Indigo',
      origin: 'Fresh root bark of Baptisia tinctoria (Fabaceae).',
      essence: 'Profound septic state with stupor (looks intoxicated), highly offensive discharges, and delusion of body being scattered into pieces.',
      mainIndications: ['Septic fever & typhoid states', 'Putrid tonsillitis & gangrenous sore throat', 'Profound bruised soreness in toxic flu'],
      keynotes: ['Feels scattered in pieces and struggles to toss them together', 'All discharges (breath, sweat, stool) intensely fetid', 'Besotted, dusky red, intoxicated facial expression'],
      mindEmotional: 'Falls asleep while answering questions, stuporous, confused.',
      modalitiesBetter: ['Moderate movement'],
      modalitiesWorse: ['Pressure', 'On waking', 'Enclosed warm room'],
      potenciesAndDosage: 'D4 to C30 / 6C, 30C. Acute septic: D6 hourly.',
      defaultTagesdosis: '3–4 doses of 5 pellets',
      sphereOfAction: ['Blood & Reticuloendothelial System', 'Throat & Mucosa', 'Brain'],
      differentialRemedies: ['Pyrogenium', 'Arnica', 'Gelsemium', 'Rhus tox'],
      searchKeywords: ['septic', 'wild indigo', 'baptisia', 'scattered pieces', 'fetid', 'typhoid']
    },
    es: { commonName: 'Índigo salvaje' },
    fr: { commonName: 'Indigo sauvage' },
    el: { commonName: 'Βαπτίσια' },
    it: { commonName: 'Indaco selvatico' },
    ru: { commonName: 'Баптизия красильная' }
  },
  {
    id: 'baryta-carbonica',
    latinName: 'Baryta carbonica',
    categoryKey: 'mineral',
    importanceTier: 1,
    de: {
      commonName: 'Bariumcarbonat',
      origin: 'Reines Bariumcarbonat (BaCO3).',
      essence: 'Entwicklungsverzögerung bei Kindern und vorzeitiges Altern bei Senioren; chronisch vergrößerte Mandeln und extreme Schüchternheit gegenüber Fremden.',
      mainIndications: ['Rezidivierende Tonsillitis & chronische Mandelhypertrophie', 'Entwicklungsrückstand & Lernschwierigkeiten bei Kindern', 'Zerebrale Sklerose & Gedächtnisschwäche bei Senioren'],
      keynotes: ['Vergrößerte Lymphknoten und riesige Mandeln', 'Kind versteckt sich hinter der Mutter vor Fremden', 'Fußschweiß stinkt und unterdrückter Schweiß führt zu Halsentzündung'],
      mindEmotional: 'Mangelndes Selbstvertrauen, scheu, kindisches Verhalten bei Alten.',
      modalitiesBetter: ['Trockenes warmes Wetter'],
      modalitiesWorse: ['Kälte & feuchte Kälte', 'Nach dem Essen', 'In Gesellschaft Fremder'],
      potenciesAndDosage: 'D6, D12, C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Lymphatisches System & Mandeln', 'Gehirn & Blutgefäße'],
      differentialRemedies: ['Calcarea carbonica', 'Silicea', 'Lycopodium', 'Causticum'],
      searchKeywords: ['baryta', 'mandeln', 'tonsillitis', 'schüchtern', 'senioren', 'kinder']
    },
    en: {
      commonName: 'Carbonate of Barium',
      origin: 'Pure barium carbonate (BaCO3).',
      essence: 'Developmental delay in children and senile decay in the elderly; chronically enlarged tonsils and extreme timidity before strangers.',
      mainIndications: ['Recurrent tonsillitis & hypertrophic tonsils', 'Learning disabilities & developmental delay in children', 'Cerebral arteriosclerosis & memory loss in aged'],
      keynotes: ['Enlarged indurated glands and huge tonsils', 'Child hides behind mother when strangers enter', 'Offensive foot sweat; suppression causes quinsy'],
      mindEmotional: 'Lack of self-confidence, timid, childish behavior in the aged.',
      modalitiesBetter: ['Warm dry weather'],
      modalitiesWorse: ['Cold damp drafts', 'After eating', 'In presence of strangers'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Lymphatic System & Tonsils', 'Brain & Cerebral Arteries'],
      differentialRemedies: ['Calcarea carbonica', 'Silicea', 'Lycopodium', 'Causticum'],
      searchKeywords: ['barium', 'tonsils', 'quinsy', 'timidity', 'elderly', 'developmental delay']
    },
    es: { commonName: 'Carbonato de bario' },
    fr: { commonName: 'Carbonate de baryte' },
    el: { commonName: 'Ανθρακικό βάριο' },
    it: { commonName: 'Carbonato di bario' },
    ru: { commonName: 'Барита карбоника / Углекислый барий' }
  },
  {
    id: 'belladonna',
    latinName: 'Atropa belladonna',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Tollkirsche / Belladonna',
      origin: 'Ganze frische Pflanze der Tollkirsche (Solanaceae).',
      essence: 'Das große Mittel für plötzliche, hochakute, pochende Entzündungen mit glühender Hitze, feuerrotem Gesicht, weiten Pupillen und Delirium; dampfender Schweiß.',
      mainIndications: ['Hohes plötzliches Fieber mit Halluzinationen & Phantasieren', 'Pochende Kopfschmerzen & Migräne (schlimmer durch Erschütterung)', 'Akute feuerrote Angina tonsillaris & Scharlach', 'Akute Mastitis (brustrot, heiß, strahlend)', 'Sonnenstich & Hitzschlag'],
      keynotes: ['Plötzlicher Beginn, pochender hämmernder Schmerz', 'Glühend heißer Kopf bei kalten Händen und Füßen', 'Weite, glänzende Pupillen, Licht- und Geräuschempfindlichkeit', 'Dampfender Schweiß am Kopf', 'Verschlimmerung durch geringste Erschütterung'],
      mindEmotional: 'Fieberdelirium mit Beiß- und Schlagdrang, Halluzinationen von schwarzen Hunden und Gespenstern.',
      modalitiesBetter: ['Ruhe & dunkles Zimmer', 'Aufrechtes Sitzen', 'Wärme'],
      modalitiesWorse: ['Erschütterung & Berührung', 'Licht, Lärm & Zugluft', 'Liegen mit tiefem Kopf', 'Um 15:00 Uhr'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei hohem Fieber C30 alle 30–60 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Gehirn', 'Gefäßsystem & Kreislauf', 'Schleimhäute & Rachen', 'Haut'],
      differentialRemedies: ['Aconitum (trockene Haut, Durst, Angst)', 'Gelsemium (müde, schläfrig)', 'Apis (ödematös, kältebesserung)'],
      searchKeywords: ['tollkirsche', 'fieber', 'belladonna', 'pochen', 'rotes gesicht', 'scharlach', 'mandeln', 'delirium', 'sonnenstich']
    },
    en: {
      commonName: 'Deadly Nightshade',
      origin: 'Whole fresh flowering plant of Atropa belladonna (Solanaceae).',
      essence: 'The supreme remedy for sudden, intensely violent, throbbing inflammations with glowing heat, fiery red face, dilated pupils, and delirious stupor; steaming sweat.',
      mainIndications: ['Sudden high fever with delirium and hallucinations', 'Throbbing congestive headaches aggravated by jar', 'Acute fiery red tonsillitis & scarlet fever', 'Acute mastitis with radiating streaks', 'Sunstroke & heat exhaustion'],
      keynotes: ['Sudden explosive onset with throbbing hammering pain', 'Glowing hot head with icy cold hands and feet', 'Dilated glistening pupils, photophobia, sensitive to noise', 'Steaming sweat on head', 'Violent aggravation from slightest jar or bed shake'],
      mindEmotional: 'Feverish delirium, bites, strikes, hallucinates black dogs and specters.',
      modalitiesBetter: ['Rest in a quiet dark room', 'Sitting semi-erect', 'Warm wrapping'],
      modalitiesWorse: ['Jarring of bed & touch', 'Bright light, noise & draft', 'Lying flat', '3:00 PM'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In high fever C30 every 30–60 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Central Nervous System & Brain', 'Vascular System', 'Mucous Membranes & Throat', 'Skin'],
      differentialRemedies: ['Aconitum (dry skin, panic, thirst)', 'Gelsemium (dull, heavy, drowsy)', 'Apis (pink edema, cold better)'],
      searchKeywords: ['belladonna', 'deadly nightshade', 'fever', 'throbbing', 'red face', 'tonsillitis', 'delirium', 'sunstroke']
    },
    es: { commonName: 'Belladona' },
    fr: { commonName: 'Belladone' },
    el: { commonName: 'Μπελαντόνα' },
    it: { commonName: 'Belladonna' },
    ru: { commonName: 'Белладонна / Красавка' }
  },
  {
    id: 'bellis-perennis',
    latinName: 'Bellis perennis',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Gänseblümchen',
      origin: 'Ganze blühende Pflanze des Gänseblümchens (Asteraceae).',
      essence: 'Tiefes Weichteiltrauma („Gärtner-Arnika“), stumpfe Verletzungen von Brust, Bauch und Becken; Schmerzen nach kaltem Bad in erhitztem Zustand.',
      mainIndications: ['Tiefe Gewebs- & Muskelverletzungen', 'Hämatome im Bauch- und Beckenbereich (z.B. nach Geburt/OP)', 'Muskelkater und Überarbeitung'],
      keynotes: ['Verletzungen tief sitzender Organe (Brustdrüse, Uterus)', 'Schlimmer durch kaltes Trinken oder Baden, wenn überhitzt', 'Erwacht früh morgens und kann nicht mehr schlafen'],
      mindEmotional: 'Müde, erschöpft, möchte sich nicht bewegen.',
      modalitiesBetter: ['Fortgesetzte Bewegung', 'Wärme'],
      modalitiesWorse: ['Kaltes Bad nach Überhitzung', 'Berührung', 'Ruhe'],
      potenciesAndDosage: 'D4 bis C30. 2-3x täglich 5 Globuli.',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Tiefe Weichteile & Muskulatur', 'Beckenorgane', 'Blutgefäße'],
      differentialRemedies: ['Arnica', 'Ruta', 'Hypericum', 'Conium'],
      searchKeywords: ['gänseblümchen', 'trauma', 'becken', 'geburt', 'muskeln', 'prellung']
    },
    en: {
      commonName: 'English Daisy',
      origin: 'Whole fresh flowering plant of Bellis perennis (Asteraceae).',
      essence: 'Deep muscular and soft tissue trauma ("Gardener’s Arnica"), blunt injuries to pelvic and abdominal organs; ill effects of cold bathing when heated.',
      mainIndications: ['Deep pelvic and abdominal bruising (postpartum, surgery)', 'Trauma to breast tissue and deep tissues', 'Sore bruised feeling in pelvic viscera'],
      keynotes: ['Injuries to deep seated visceral structures', 'Worse from cold drinks or cold bathing when overheated', 'Wakes early in morning and cannot sleep again'],
      mindEmotional: 'Tired, depleted, disinclined to move.',
      modalitiesBetter: ['Continued gentle motion', 'Warmth'],
      modalitiesWorse: ['Cold bathing when overheated', 'Touch', 'Inactivity'],
      potenciesAndDosage: 'D4 to C30 / 6C, 30C. 2-3 times daily 5 pellets.',
      defaultTagesdosis: '2-3 times daily 5 pellets',
      sphereOfAction: ['Deep Soft Tissues & Muscles', 'Pelvic Viscera', 'Blood Vessels'],
      differentialRemedies: ['Arnica', 'Ruta', 'Hypericum', 'Conium'],
      searchKeywords: ['daisy', 'deep trauma', 'pelvic injury', 'postpartum', 'bruising']
    },
    es: { commonName: 'Margarita menor' },
    fr: { commonName: 'Pâquerette' },
    el: { commonName: 'Μαργαρίτα' },
    it: { commonName: 'Pratolina' },
    ru: { commonName: 'Маргаритка многолетняя' }
  },
  {
    id: 'berberis-vulgaris',
    latinName: 'Berberis vulgaris',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Sauerdorn / Berberitze',
      origin: 'Rinde der Wurzeln von Berberis vulgaris (Berberidaceae).',
      essence: 'Radiierende, stechende Schmerzen, die von einem Punkt in alle Richtungen ausstrahlen; Nierenkoliken, Gallengangskoliken und Harnsäurediathese.',
      mainIndications: ['Nierenkolik & Nephrolithiasis (Schmerz strahlt in Oberschenkel/Hoden aus)', 'Gallenkolik & Leberfunktionsstörungen', 'Rückenschmerzen & Hexenschuss mit Steifigkeit'],
      keynotes: ['Schmerzen strahlen kranzförmig in alle Richtungen aus', 'Blubberndes, gluckerndes Gefühl in der Nierengegend', 'Roter, ziegelmehlartiger Bodensatz im Urin'],
      mindEmotional: 'Apathisch, melancholisch, reizbar bei Schmerzen.',
      modalitiesBetter: ['Ruhe'],
      modalitiesWorse: ['Bewegung & Erschütterung', 'Stehen', 'Reiten oder Autofahren'],
      potenciesAndDosage: 'D4 bis C30. Bei Koliken D6 alle 15–30 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Nieren & Harnleiter', 'Gallenblase & Leber', 'Lendenwirbelsäule'],
      differentialRemedies: ['Lycopodium', 'Cantharis', 'Colocynthis', 'Pareira brava'],
      searchKeywords: ['berberitze', 'sauerdorn', 'nierenkolik', 'gallenkolik', 'ziegelmehlurin', 'strahlend']
    },
    en: {
      commonName: 'Barberry',
      origin: 'Bark of the root of Berberis vulgaris (Berberidaceae).',
      essence: 'Radiating, shooting, stitching pains darting outward from one point in all directions; renal calculi, biliary colic, and uric acid diathesis.',
      mainIndications: ['Renal colic & kidney stones (pain radiating down ureter into thighs/testes)', 'Biliary colic & hepatic congestion', 'Lumbago with intense bubbling stiffness'],
      keynotes: ['Pains radiate outward in all directions', 'Bubbling or gurgling sensation in lumbar/renal area', 'Red, brick-dust sediment in urine'],
      mindEmotional: 'Apathetic, gloomy, irritable during severe pain.',
      modalitiesBetter: ['Quiet rest'],
      modalitiesWorse: ['Motion, jar & stepping hard', 'Standing', 'Riding or jar in car'],
      potenciesAndDosage: 'D4 to C30 / 6C, 30C. In colic D6 every 15–30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Kidneys & Ureters', 'Gallbladder & Liver', 'Lumbar Spine'],
      differentialRemedies: ['Lycopodium', 'Cantharis', 'Colocynthis', 'Pareira brava'],
      searchKeywords: ['barberry', 'renal colic', 'kidney stone', 'biliary colic', 'radiating pain']
    },
    es: { commonName: 'Agracejo' },
    fr: { commonName: 'Épine-vinette' },
    el: { commonName: 'Βερβερίδα' },
    it: { commonName: 'Crespino' },
    ru: { commonName: 'Барбарис обыкновенный' }
  },
  {
    id: 'borax-veneta',
    latinName: 'Borax veneta',
    categoryKey: 'mineral',
    importanceTier: 2,
    de: {
      commonName: 'Borax / Natriumtetraborat',
      origin: 'Reines Natriumborat (Na2B4O7 · 10H2O).',
      essence: 'Panische Angst vor Abwärtsbewegung (Schaukel, Fahrstuhl, Herabtragen des Kindes) und schmerzhafte Aphthen in Mund und Zahnfleisch.',
      mainIndications: ['Angst vor Abwärtsbewegung bei Säuglingen & Reisekrankheit', 'Schmerzhafte Mundaphthen & Soor', 'Kinderlosigkeit & Leitsymptom Scheidenausfluss wie heißes Wasser'],
      keynotes: ['Kind schreit und klammert sich fest, sobald es ins Bettchen abgelegt wird', 'Empfindlich gegen plötzliche Geräusche (Türknallen, Schüsse)', 'Mundhöhle heiß mit leicht blutenden Aphthen'],
      mindEmotional: 'Ängstlich, schreckhaft bei jedem Knall.',
      modalitiesBetter: ['Druck', 'Nach Mitternacht'],
      modalitiesWorse: ['Abwärtsbewegung (Lift, Schaukel, Runtertragen)', 'Plötzlicher Lärm'],
      potenciesAndDosage: 'D6 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Nervensystem & Gleichgewichtssinn', 'Mundschleimhaut', 'Urogenitaltrakt'],
      differentialRemedies: ['Gelsemium', 'Mercurius', 'Natrium muriaticum'],
      searchKeywords: ['borax', 'abwärtsbewegung', 'aphthen', 'mundsoor', 'fahrstuhl', 'schaukel']
    },
    en: {
      commonName: 'Borate of Sodium',
      origin: 'Pure sodium borate.',
      essence: 'Dread of downward motion (swings, elevator, putting baby down in crib) and painful aphthous ulcers in mouth and gums.',
      mainIndications: ['Dread of downward motion in infants & motion sickness', 'Painful oral aphthae & thrush in nursing infants', 'Infertility & leucorrhea resembling hot water'],
      keynotes: ['Infant cries and grasps crib tightly when being laid down', 'Extreme hyperacusis to sudden sharp noises (distant shots, thunder)', 'Mouth is hot, sensitive with bleeding aphthous ulcers'],
      mindEmotional: 'Anxious, easily startled by unexpected sounds.',
      modalitiesBetter: ['Pressure', 'After midnight'],
      modalitiesWorse: ['Downward motion (elevators, downward rocking)', 'Sudden noise'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Vestibular & Nervous System', 'Oral Mucous Membranes', 'Urogenital Organs'],
      differentialRemedies: ['Gelsemium', 'Mercurius', 'Natrium muriaticum'],
      searchKeywords: ['borax', 'downward motion', 'aphthae', 'thrush', 'elevator fear']
    },
    es: { commonName: 'Bórax' },
    fr: { commonName: 'Borax' },
    el: { commonName: 'Βόρακας' },
    it: { commonName: 'Borace' },
    ru: { commonName: 'Бура / Боракс' }
  },
  {
    id: 'bryonia-alba',
    latinName: 'Bryonia alba',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Weiße Zaunrübe',
      origin: 'Frische Wurzel der Weißen Zaunrübe (Cucurbitaceae).',
      essence: 'Das große Mittel für Entzündungen der serösen Häute (Rippenfell, Gelenke). Stechende Schmerzen, die durch die geringste Bewegung unerträglich verschlimmert und durch absolutes Ruheliegen auf der schmerzhaften Seite sowie festen Druck gebessert werden; großer Durst.',
      mainIndications: ['Pleuritis & stechender trockener Husten (hält sich beim Husten die Brust)', 'Akute Arthritis & Gelenkschwellung (besser durch festen Druck)', 'Appendizitis & Bauchfellreizung (jede Erschütterung schmerzt)', 'Kopfschmerzen mit Berstungsgefühl (muss Kopf festhalten)', 'Obstipation mit trockenem, hartem Stuhl wie verbrannt'],
      keynotes: ['Schlimmer durch die geringste Bewegung (sogar Augenbewegung)', 'Besserung durch festen Druck und Liegen auf der schmerzhaften Seite', 'Extreme Trockenheit aller Schleimhäute', 'Großer Durst auf riesige Mengen eiskaltes Wasser in langen Abständen', 'Redet im Delirium über geschäftliche Angelegenheiten'],
      mindEmotional: 'Mürrisch, will in Ruhe gelassen werden, reizbar, redet im Fieber über seine Geschäfte.',
      modalitiesBetter: ['Absolute Ruhe', 'Liegen auf der schmerzhaften Seite', 'Fester Druck', 'Kalte Umschläge'],
      modalitiesWorse: ['Jede Bewegung & Erschütterung', 'Wärme & warmes Zimmer', 'Morgens um 9:00 Uhr'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei stechendem Husten/Gelenkschmerz C30: 3–5 Globuli alle 1–2 Std.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Seröse Häute (Pleura, Peritoneum, Synovia)', 'Atmungsorgane', 'Magen-Darm-Trakt'],
      differentialRemedies: ['Rhus tox (besser durch Bewegung)', 'Aconitum (plötzlich, unruhig)', 'Belladonna (pochend)'],
      searchKeywords: ['zaunrübe', 'bryonia', 'bewegungsschmerz', 'druckbesserung', 'pleuritis', 'trockenheit', 'durst', 'husten']
    },
    en: {
      commonName: 'White Bryony',
      origin: 'Fresh root of Bryonia alba (Cucurbitaceae).',
      essence: 'The supreme remedy for inflammation of serous membranes (pleura, joints, peritoneum). Stitching tearing pains aggravated by slightest motion and relieved by absolute rest and hard pressure on painful side; large thirst.',
      mainIndications: ['Pleurisy & stitching dry cough (holds chest with both hands)', 'Acute arthritis with hot swollen joints relieved by firm wrapping', 'Peritoneal irritation & appendicitis (every jar excruciating)', 'Splitting bursting headaches holding temples', 'Constipation with dry, hard stools as if burnt'],
      keynotes: ['Aggravation from the slightest motion (even moving eyes)', 'Relief from firm hard pressure and lying on painful side', 'Excessive dryness of all mucous membranes', 'Thirst for large quantities of cold water at long intervals', 'Delirious rambling about daily business'],
      mindEmotional: 'Irritable, wants to be left alone in quiet, worries about business affairs in fever.',
      modalitiesBetter: ['Absolute quiet rest', 'Lying on painful side', 'Hard pressure', 'Cold compresses'],
      modalitiesWorse: ['Any motion & jarring', 'Warmth & warm room', 'Morning around 9:00 AM'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In stitching pain C30 every 1–2 hours.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Serous Membranes (Pleura, Peritoneum, Synovia)', 'Respiratory Tract', 'Gastrointestinal Canal'],
      differentialRemedies: ['Rhus tox (better on motion)', 'Aconitum (sudden panic)', 'Belladonna (throbbing)'],
      searchKeywords: ['bryonia', 'white bryony', 'motion worse', 'pressure better', 'pleurisy', 'dry cough', 'thirst', 'joint pain']
    },
    es: { commonName: 'Brionia blanca' },
    fr: { commonName: 'Bryone blanche' },
    el: { commonName: 'Βρυωνία' },
    it: { commonName: 'Brionia bianca' },
    ru: { commonName: 'Бриония белая / Переступень' }
  },
  {
    id: 'cactus-grandiflorus',
    latinName: 'Cactus grandiflorus',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Königin der Nacht',
      origin: 'Frische junge Stängel und Blüten der Königin der Nacht (Cactaceae).',
      essence: 'Gefühl einer eisernen Faust oder eines Bandes, das das Herz oder andere Organe krampfhaft zusammenschnürt; Angina pectoris und Blutungen.',
      mainIndications: ['Angina pectoris mit Einschnürungsgefühl am Herzen', 'Herzklopfen & Arrhythmien mit Angst', 'Dysmenorrhö mit krampfhafter Einschnürung'],
      keynotes: ['Gefühl, als würde das Herz von einer eisernen Faust zusammengepresst', 'Schmerz strahlt in den linken Arm aus', 'Blutungen von schwarzem, geronnenem Blut'],
      mindEmotional: 'Traurig, furchtsam, weint über seine Herzkrankheit, Todesangst.',
      modalitiesBetter: ['Frische Luft', 'Ruhe'],
      modalitiesWorse: ['Liegen auf der linken Seite', 'Um 11:00 Uhr und 23:00 Uhr', 'Gehen'],
      potenciesAndDosage: 'D4 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Herz & Kreislauf', 'Gefäßsystem', 'Kreislauf'],
      differentialRemedies: ['Digitalis', 'Spigelia', 'Latrodectus mactans', 'Crataegus'],
      searchKeywords: ['kaktus', 'königin der nacht', 'herzenge', 'eiserne faust', 'angina pectoris']
    },
    en: {
      commonName: 'Night-Blooming Cereus',
      origin: 'Fresh young stems and flowers of Selenicereus grandiflorus (Cactaceae).',
      essence: 'Constriction sensation as if an iron hand or tight wire was squeezing the heart or other organs; angina pectoris and dark hemorrhages.',
      mainIndications: ['Angina pectoris with constriction of chest', 'Palpitations & cardiac arrhythmias with anxiety', 'Severe dysmenorrhea with clutch-like cramps'],
      keynotes: ['Sensation as if an iron fist were clutching the heart', 'Pain radiates down into left arm and hand', 'Hemorrhages of dark clotted blood from orifices'],
      mindEmotional: 'Fear of death, weeps over cardiac disease, despondent.',
      modalitiesBetter: ['Open fresh air', 'Quiet rest'],
      modalitiesWorse: ['Lying on left side', '11:00 AM and 11:00 PM', 'Walking or climbing stairs'],
      potenciesAndDosage: 'D4 to C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Heart & Coronary Circulation', 'Blood Vessels', 'Smooth Muscle'],
      differentialRemedies: ['Digitalis', 'Spigelia', 'Latrodectus mactans', 'Crataegus'],
      searchKeywords: ['cactus', 'night blooming cereus', 'iron fist', 'angina pectoris', 'heart constriction']
    },
    es: { commonName: 'Reina de la noche' },
    fr: { commonName: 'Cactus à grandes fleurs' },
    el: { commonName: 'Κάκτος' },
    it: { commonName: 'Cactus grandifloro' },
    ru: { commonName: 'Кактус грандифлорус / Царица ночи' }
  },
  {
    id: 'calcarea-carbonica',
    latinName: 'Calcarea carbonica',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Austernschalenkalk',
      origin: 'Mittlere Schicht der zerriebenen Austernschale (Ostrea edulis).',
      essence: 'Das große Stoffwechsel- und Konstitutionsmittel: Kälteempfindlich, feuchte Kopfschweiße im Schlaf, verlangsamte Knochen- und Zahnentwicklung, Verlangen nach weichgekochten Eiern; Überarbeitung führt zur Erschöpfung.',
      mainIndications: ['Gedeihstörungen, späte Zahnung & späte Fontanellenschließung bei Kindern', 'Rezidivierende Infekte mit Neigung zu Lymphdrüsenschwellungen', 'Chronische Erschöpfung bei pflichtbewussten Menschen nach Überarbeitung', 'Osteoporose, Rachitis & Knochenheilungsstörungen', 'Gewichtszunahme & träger Stoffwechsel'],
      keynotes: ['Saurer, reichlicher Kopfschweiß durchnässt das Kissen im Schlaf', 'Ständige Kälteempfindlichkeit und kalte, feuchte Füße (wie feuchte Socken)', 'Großes Verlangen nach Eiern (besonders weich gekocht) und Unverdaulichem', 'Schlimmer durch körperliche und geistige Anstrengung sowie Treppensteigen', 'Träge Verdauung mit Wohlbefinden bei Obstipation'],
      mindEmotional: 'Ängstlich, fürchtet den Verstand zu verlieren oder dass andere seine Schwäche bemerken. Pflichtbewusst, baut Burgen aus Arbeit.',
      modalitiesBetter: ['Trockenes warmes Wetter', 'Liegen auf der schmerzhaften Seite', 'Im Dunkeln'],
      modalitiesWorse: ['Kälte & Feuchtigkeit', 'Körperliche Anstrengung & Treppensteigen', 'Bei Vollmond'],
      potenciesAndDosage: 'Konstitutionell: C30, C200. 1x wöchentlich oder monatlich 5 Globuli.',
      defaultTagesdosis: '1 Gabe à 5 Globuli',
      sphereOfAction: ['Knochen, Zähne & Skelettsystem', 'Lymphsystem & Drüsen', 'Stoffwechsel & Verdauung'],
      differentialRemedies: ['Silicea (dünn, fröstelnd)', 'Calcarea phosphorica (groß, schlank)', 'Sulfur (warmblütig)'],
      searchKeywords: ['austernschalenkalk', 'kalk', 'knochen', 'zahnung', 'eier', 'kopfschweiß', 'fontanelle', 'stoffwechsel', 'müdigkeit']
    },
    en: {
      commonName: 'Carbonate of Lime / Oyster Shell Calcium',
      origin: 'Middle layer of the oyster shell (Ostrea edulis).',
      essence: 'The supreme metabolic and constitutional polychrest: chilly, head drenching in sweat during sleep, delayed dentition and bone closure, intense craving for boiled eggs; exhaustion from overwork.',
      mainIndications: ['Failure to thrive, delayed dentition & open fontanelles in children', 'Recurrent catarrhs with swollen lymphatic glands', 'Chronic burnout in conscientious overburdened individuals', 'Osteoporosis, rickets & delayed fracture healing', 'Sluggish metabolism & easy weight gain'],
      keynotes: ['Sour profuse head sweat wets pillow completely during sleep', 'Constant chilliness with cold damp feet (feels like damp socks)', 'Intense craving for eggs (especially soft-boiled) and indigestible items', 'Dyspnea and exhaustion from climbing stairs or physical exertion', 'Constipated with paradoxically better feeling when bowels are bound'],
      mindEmotional: 'Anxious, fears losing mind or that people will observe their confusion. Overwhelmed by responsibilities.',
      modalitiesBetter: ['Dry warm weather', 'Lying on painful side', 'Dark quiet room'],
      modalitiesWorse: ['Cold and damp weather', 'Physical exertion & ascending stairs', 'Full moon'],
      potenciesAndDosage: 'Constitutional: C30, C200. 1 dose weekly or monthly.',
      defaultTagesdosis: '1 dose of 5 pellets',
      sphereOfAction: ['Bones, Teeth & Skeletal System', 'Lymphatic System & Glands', 'Metabolism & Digestion'],
      differentialRemedies: ['Silicea (lean, chilly)', 'Calcarea phosphorica (tall, slender)', 'Sulfur (warm-blooded)'],
      searchKeywords: ['calcium', 'oyster shell', 'bones', 'teething', 'eggs craving', 'head sweat', 'fontanelle', 'exhaustion']
    },
    es: { commonName: 'Carbonato de calcio / Caliza de ostras' },
    fr: { commonName: 'Calcaire d’huîtres' },
    el: { commonName: 'Ασβέστιο στρειδιού' },
    it: { commonName: 'Carbonato di calcio d’ostrica' },
    ru: { commonName: 'Калькарея карбоника / Углекислая известь' }
  },
  {
    id: 'calcarea-fluorica',
    latinName: 'Calcarea fluorica',
    categoryKey: 'mineral',
    importanceTier: 1,
    de: {
      commonName: 'Flussspat / Calciumfluorid',
      origin: 'Reines Calciumfluorid (CaF2).',
      essence: 'Gewebe- und Gefäßelastizitätsverlust: steinharte Drüsenschwellungen, Knochenüberbeine (Exostosen), Bindegewebsschwäche und Krampfadern.',
      mainIndications: ['Überbeine (Ganglien, Exostosen) & Fersensporn', 'Ausgeprägte Bindegewebsschwäche & Krampfadern', 'Zahnkaries & Schmelzdefekte der Zähne'],
      keynotes: ['Steinharte Verhärtungen von Drüsen und Knochen', 'Risse und Rhagaden in Haut und Händen', 'Anlaufschmerz, der sich bei fortgesetzter Bewegung bessert'],
      mindEmotional: 'Ständige Angst vor finanzieller Not und Ruin.',
      modalitiesBetter: ['Wärme & heiße Umschläge', 'Fortgesetzte Bewegung'],
      modalitiesWorse: ['Kälte & Nässe', 'Ruhebeginn'],
      potenciesAndDosage: 'D6, D12 (auch Schüßler-Salz Nr. 1). 2-3x täglich 5 Globuli.',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Bindegewebe & Faszien', 'Knochen & Zahnschmelz', 'Venen'],
      differentialRemedies: ['Silicea', 'Ruta', 'Calcarea phosphorica', 'Fluoricum acidum'],
      searchKeywords: ['flussspat', 'überbein', 'ganglion', 'bindegewebe', 'fersensporn', 'krampfadern']
    },
    en: {
      commonName: 'Fluoride of Lime / Fluorite',
      origin: 'Pure calcium fluoride (CaF2).',
      essence: 'Loss of elasticity in fibers and vessels: stony-hard glandular indurations, bone exostoses, ligamentous relaxation, and varicose veins.',
      mainIndications: ['Bone spurs, ganglions, and calcaneal spurs', 'Severe ligamentous laxity & varicose veins', 'Deficient dental enamel & rapid tooth decay'],
      keynotes: ['Stony-hard induration of glands, ligaments, and bones', 'Cracks, fissures, and chaps in palms and soles', 'Initial stiffness relieved by continued gentle motion'],
      mindEmotional: 'Constant unwarranted dread of financial ruin and poverty.',
      modalitiesBetter: ['Heat and warm applications', 'Continued motion'],
      modalitiesWorse: ['Cold and damp weather', 'Beginning of motion'],
      potenciesAndDosage: 'D6, D12, C30 / 6X, 12X. 2-3 times daily 5 pellets.',
      defaultTagesdosis: '2-3 times daily 5 pellets',
      sphereOfAction: ['Connective Tissue & Elastic Fibers', 'Bones & Dental Enamel', 'Veins'],
      differentialRemedies: ['Silicea', 'Ruta', 'Calcarea phosphorica', 'Fluoricum acidum'],
      searchKeywords: ['fluoride of lime', 'bone spur', 'ganglion', 'elasticity', 'varicose', 'calcium fluoride']
    },
    es: { commonName: 'Fluoruro de calcio' },
    fr: { commonName: 'Fluorure de calcium' },
    el: { commonName: 'Φθοριούχο ασβέστιο' },
    it: { commonName: 'Fluoruro di calcio' },
    ru: { commonName: 'Калькарея флюорика / Фтористый кальций' }
  },
  {
    id: 'calcarea-phosphorica',
    latinName: 'Calcarea phosphorica',
    categoryKey: 'mineral',
    importanceTier: 1,
    de: {
      commonName: 'Calciumphosphat / Knochenkalk',
      origin: 'Reines Calciumhydrogenphosphat (CaHPO4 · 2H2O).',
      essence: 'Wachstumsschmerzen bei schnellem Längenwachstum Jugendlicher, verzögerte Knochenbruchheilung, Verlangen nach Geräuchertem/Salzigem und chronische Unzufriedenheit.',
      mainIndications: ['Wachstumsschmerzen & Haltungsschwäche bei Jugendlichen', 'Verzögerte Frakturheilung & Pseudarthrosen', 'Schulkopfschmerz bei überforderten Schülern'],
      keynotes: ['Großes Verlangen nach Schinken, Speck und geräuchertem Fleisch', 'Kopfschmerzen nach der Schule bei überlasteten Kindern', 'Fontanellen bleiben lange offen'],
      mindEmotional: 'Unzufrieden, will immer woanders hin (Fernweh), seufzt häufig.',
      modalitiesBetter: ['Im Sommer', 'Warmes trockenes Wetter'],
      modalitiesWorse: ['Kaltes feuchtes Wetter', 'Wetterwechsel & Schneeschmelze', 'Geistige Anstrengung'],
      potenciesAndDosage: 'D6, D12, C30 (Schüßler-Salz Nr. 2). 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Knochen & Knorpel', 'Blutbildung', 'Wachstum'],
      differentialRemedies: ['Calcarea carbonica', 'Phosphorus', 'Tuberculinum', 'Silicea'],
      searchKeywords: ['knochenkalk', 'wachstumsschmerzen', 'fraktur', 'schulkopfschmerz', 'geräuchertes']
    },
    en: {
      commonName: 'Phosphate of Lime',
      origin: 'Pure calcium phosphate.',
      essence: 'Growing pains in rapidly shooting adolescents, delayed union of fractures, craving for smoked salty bacon/ham, and restless discontent.',
      mainIndications: ['Growing pains & poor posture in slender teens', 'Delayed bone fracture healing & calluses', 'Schoolgirl headaches from study fatigue'],
      keynotes: ['Intense craving for smoked meat, bacon, and salty food', 'Headaches in school children from cognitive strain', 'Fontanelles remain widely open in infants'],
      mindEmotional: 'Discontented, restless wanderlust, constantly sighs.',
      modalitiesBetter: ['Summer season', 'Warm dry weather'],
      modalitiesWorse: ['Cold damp drafts', 'Melting snow & weather change', 'Mental exertion'],
      potenciesAndDosage: 'D6, D12, C30 / 6X, 12X. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Bones & Cartilage', 'Hematopoiesis', 'Adolescent Growth'],
      differentialRemedies: ['Calcarea carbonica', 'Phosphorus', 'Tuberculinum', 'Silicea'],
      searchKeywords: ['calcium phosphate', 'growing pains', 'fracture', 'school headache', 'smoked meat']
    },
    es: { commonName: 'Fosfato de calcio' },
    fr: { commonName: 'Phosphate de calcium' },
    el: { commonName: 'Φωσφορικό ασβέστιο' },
    it: { commonName: 'Fosfato di calcio' },
    ru: { commonName: 'Калькарея фосфорика / Фосфорнокислый кальций' }
  },
  {
    id: 'calendula-officinalis',
    latinName: 'Calendula officinalis',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Ringelblume',
      origin: 'Frische blühende oberirdische Teile der Ringelblume (Asteraceae).',
      essence: 'Das homöopathische Wundheilungsmittel für offene, zerrissene, klaffende Riss- und Schnittwunden: verhindert Eiterung und fördert Granulationsgewebe.',
      mainIndications: ['Klaffende Risswunden, Schnittwunden & Schürfwunden', 'Wundheilungsstörungen nach Operationen & Zahnextraktionen', 'Verbrennungen & oberflächliche Entzündungen'],
      keynotes: ['Wunden mit starkem Wundschmerz und Neigung zu Vereiterung', 'Hervorragende narbenfreie Granulation', 'Schmerz überproportional zur sichtbaren Verletzung'],
      mindEmotional: 'Ängstlich, reizbar bei Schmerzen, fürchtet Berührung der Wunde.',
      modalitiesBetter: ['Wärme', 'Vollkommene Ruhe'],
      modalitiesWorse: ['Feuchte Kälte', 'Bewegung der Wundregion'],
      potenciesAndDosage: 'Lokal: Urtinktur verdünnt (1:10) als Wundspülung; innerlich D4 bis C30 2–3x täglich 5 Globuli.',
      defaultTagesdosis: '2–3x täglich 5 Globuli',
      sphereOfAction: ['Haut & Wundränder', 'Schleimhäute', 'Weichteile'],
      differentialRemedies: ['Arnica (stumpfes Trauma)', 'Hypericum (Nervenverletzung)', 'Staphisagria (glatte Schnitte)'],
      searchKeywords: ['ringelblume', 'wundheilung', 'risswunde', 'schnittwunde', 'eiterung', 'operation', 'zahnextraktion']
    },
    en: {
      commonName: 'Marigold',
      origin: 'Fresh flowering aerial parts of Calendula officinalis (Asteraceae).',
      essence: 'The supreme homeopathic antiseptic and wound healer for lacerated, ragged, open wounds: prevents suppuration and promotes clean granulation.',
      mainIndications: ['Lacerated ragged wounds, cuts, and scrapes', 'Postoperative wound recovery & dental socket healing', 'Superficial burns and raw skin fissures'],
      keynotes: ['Excessive raw soreness out of proportion to injury', 'Promotes healthy clean scar-free granulation', 'Prevents septic suppuration in open wounds'],
      mindEmotional: 'Fretful, anxious during painful dressing changes.',
      modalitiesBetter: ['Warmth', 'Absolute rest of the wounded part'],
      modalitiesWorse: ['Damp cold', 'Motion of injured area'],
      potenciesAndDosage: 'Locally: Dilute mother tincture (1:10) wash; Internally: D4 to C30 / 6C. 2-3 times daily 5 pellets.',
      defaultTagesdosis: '2-3 times daily 5 pellets',
      sphereOfAction: ['Skin & Lacerated Edges', 'Mucosa', 'Soft Tissue Granulation'],
      differentialRemedies: ['Arnica (blunt trauma)', 'Hypericum (nerve rich parts)', 'Staphisagria (clean incised cuts)'],
      searchKeywords: ['marigold', 'wound healing', 'laceration', 'cuts', 'antiseptic', 'granulation']
    },
    es: { commonName: 'Caléndula' },
    fr: { commonName: 'Souci officinal' },
    el: { commonName: 'Καλέντουλα' },
    it: { commonName: 'Calendula' },
    ru: { commonName: 'Календула / Ноготки' }
  },
  {
    id: 'camphora',
    latinName: 'Cinnamomum camphora',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Kampferbaum / Kampfer',
      origin: 'Destilliertes ätherisches Öl aus dem Holz des Kampferbaums (Lauraceae).',
      essence: 'Eiskalter Kollapszustand: Der Körper ist eiskalt wie Marmor, aber der Patient will paradoxerweise absolut nicht zugedeckt werden.',
      mainIndications: ['Akuter Kreislaufkollaps & Schockzustand', 'Initiale Abkühlung bei beginnender schwerer Grippe', 'Plötzlicher wässriger Brechdurchfall mit Eiseskälte'],
      keynotes: ['Körper fühlt sich eiskalt an wie eine Leiche', 'Wehrt jede Zudecke energisch ab trotz extremer Kälte', 'Plötzlicher rapider Verfall der Lebenskräfte'],
      mindEmotional: 'Ängstlich, panisch, fürchtet im Dunkeln allein zu sein.',
      modalitiesBetter: ['Warmes Zimmer', 'Denken an die Beschwerden'],
      modalitiesWorse: ['Kälte & Zugluft', 'Zudecken'],
      potenciesAndDosage: 'D1 bis D6. Im Kollapszustand wiederholt wenige Tropfen/Globuli.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Herz-Kreislauf & Vasomotorik', 'Nervensystem', 'Magen-Darm-Trakt'],
      differentialRemedies: ['Carbo vegetabilis', 'Veratrum album', 'Arsenicum album'],
      searchKeywords: ['kampfer', 'kollaps', 'eiskalt', 'nicht zudecken', 'schock', 'kreislauf']
    },
    en: {
      commonName: 'Camphor',
      origin: 'Gum camphor distilled from the wood of Cinnamomum camphora (Lauraceae).',
      essence: 'Icy cold state of collapse: body feels deathly cold to touch like marble, yet the patient violently rejects being covered.',
      mainIndications: ['Acute circulatory collapse and shock', 'First chilly stage of malignant influenza', 'Sudden prostrating watery choleroid diarrhea with icy coldness'],
      keynotes: ['Body icy cold like a corpse yet cannot bear covers', 'Violently throws off blankets despite freezing skin', 'Sudden rapid sinking of vital forces'],
      mindEmotional: 'Anxious, terrified in the dark, afraid to be left alone.',
      modalitiesBetter: ['Warm room', 'Thinking of the complaint'],
      modalitiesWorse: ['Cold open air', 'Being covered up'],
      potenciesAndDosage: '1X to 6X / D1 to D6. In collapse repeated small doses.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Vasomotor Centers & Circulation', 'Autonomic Nervous System', 'Digestive Canal'],
      differentialRemedies: ['Carbo vegetabilis', 'Veratrum album', 'Arsenicum album'],
      searchKeywords: ['camphor', 'collapse', 'icy cold', 'uncovering', 'shock', 'circulatory failure']
    },
    es: { commonName: 'Alcanfor' },
    fr: { commonName: 'Camphre' },
    el: { commonName: 'Καμφορά' },
    it: { commonName: 'Canfora' },
    ru: { commonName: 'Камфора' }
  },
  {
    id: 'cantharis-vesicatoria',
    latinName: 'Cantharis vesicatoria',
    categoryKey: 'animal',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Spanische Fliege / Kantharide',
      origin: 'Getrocknete ganze Spanische Fliege (Blasenkäfer, Meloidae).',
      essence: 'Unerträgliche brennende, schneidende Schmerzen in Harnröhre und Blase; ständiger quälender Harndrang mit tropfenweisem, blutigem Wasserlassen; schwere Brandblasen.',
      mainIndications: ['Akute hämorrhagische Zystitis mit heftigem Brennen', 'Verbrennungen 2. Grades mit Blasenbildung', 'Extreme brennende Schmerzen in Schleimhäuten'],
      keynotes: ['Brennen wie Feuer vor, während und nach dem Urinieren', 'Ständiger Drang: Urin geht nur tropfenweise unter Schmerzkrämpfen ab', 'Blasenbildung auf Haut und Schleimhaut'],
      mindEmotional: 'Wütend vor Schmerz, sexuelle Erregbarkeit, ruhelos.',
      modalitiesBetter: ['Wärme & Ruhe', 'Reiben'],
      modalitiesWorse: ['Beim Wasserlassen', 'Trinken von kaltem Wasser', 'Berührung'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei akuter Blasenentzündung D6 alle 15–30 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Harnblase & Urogenitaltrakt', 'Haut (Blasenbildung)', 'Schleimhäute'],
      differentialRemedies: ['Apis mellifica', 'Berberis', 'Sarsaparilla', 'Staphisagria'],
      searchKeywords: ['spanische fliege', 'blasenentzündung', 'brennen', 'urin', 'harndrang', 'verbrennung', 'zystitis']
    },
    en: {
      commonName: 'Spanish Fly',
      origin: 'Dried whole beetle Cantharis vesicatoria (Meloidae).',
      essence: 'Intolerable burning, cutting, scalding pains in urethra and bladder; constant tenesmus with drop-by-drop bloody scalding urination; blistering burns.',
      mainIndications: ['Acute hemorrhagic cystitis with scalding burning', 'Second-degree blistering burns and scalds', 'Violent burning inflammation of mucous surfaces'],
      keynotes: ['Burning like fire before, during, and after urination', 'Constant intolerable urge, passing only drops of bloody urine', 'Vesication and blister formation on skin'],
      mindEmotional: 'Furious from intense agony, sexual frenzy, frenzied restlessness.',
      modalitiesBetter: ['Warm applications & rest', 'Gentle rubbing'],
      modalitiesWorse: ['Urination', 'Drinking cold water/coffee', 'Touch'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In acute cystitis D6 every 15–30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Urinary Bladder & Urethra', 'Skin (Vesication)', 'Mucous Membranes'],
      differentialRemedies: ['Apis mellifica', 'Berberis', 'Sarsaparilla', 'Staphisagria'],
      searchKeywords: ['spanish fly', 'cystitis', 'burning urine', 'tenesmus', 'blistering', 'burns']
    },
    es: { commonName: 'Cantárida / Mosca española' },
    fr: { commonName: 'Cantharide' },
    el: { commonName: 'Κανθαρίδα' },
    it: { commonName: 'Cantaride' },
    ru: { commonName: 'Шпанская мушка' }
  },
  {
    id: 'carbo-vegetabilis',
    latinName: 'Carbo vegetabilis',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Holzkohle / Vegetabilische Kohle',
      origin: 'Reine Holzkohle aus Birken- oder Buchenholz.',
      essence: 'Der „Wiederbeleber von Sterbenden“: Extremster Kollaps mit Eiseskälte, Lufthunger (verlangt energisch nach Zufächeln von Luft) und gewaltige Blähungsansammlung im Oberbauch.',
      mainIndications: ['Kreislaufkollaps & Schockzustand mit kaltem Schweiß', 'Massiver Meteorismus & Völlegefühl im Oberbauch', 'Chronische Heiserkeit am Abend', 'Altersasthma mit Lufthunger'],
      keynotes: ['Patient ist eiskalt, hat aber intensiven Lufthunger und will angefächelt werden', 'Oberbauch ist prall aufgebläht und bessert sich nur durch Aufstoßen', 'Kalter Atem, kalte Zunge, kalte Knie'],
      mindEmotional: 'Apathisch, träge, verlangsamt, gleichgültig gegen alles.',
      modalitiesBetter: ['Zufächeln von Luft', 'Aufstoßen', 'Kühle Luft'],
      modalitiesWorse: ['Wärme & warmes Zimmer', 'Fettes Essen & Butter', 'Liegen im Bett'],
      potenciesAndDosage: 'Akut: C30, C200. Im Kollapsfall C30 wiederholt verabreichen.',
      defaultTagesdosis: '1–2 Gaben à 3–5 Globuli',
      sphereOfAction: ['Venöser Kreislauf & Kapillaren', 'Magen-Darm-Trakt (Oberbauch)', 'Atmungsorgane'],
      differentialRemedies: ['Lycopodium (Unterbauchblähung)', 'Arsenicum album', 'China (Blähungen)', 'Camphora'],
      searchKeywords: ['holzkohle', 'kollaps', 'lufthunger', 'fächeln', 'oberbauch', 'blähungen', 'aufstoßen', 'wiederbelebung']
    },
    en: {
      commonName: 'Vegetable Charcoal',
      origin: 'Charcoal made from birch or beech wood.',
      essence: 'The "Reviver of the Dying": extreme collapse with icy coldness, air hunger (desires to be fanned vigorously), and massive flatulent distension of upper abdomen.',
      mainIndications: ['Circulatory collapse & shock with cold sweat', 'Massive flatulence & tympanites of upper abdomen', 'Chronic hoarseness worse in evening', 'Senile asthma with severe dyspnea and air hunger'],
      keynotes: ['Patient is icy cold yet gasps for air and demands to be fanned', 'Upper abdomen distended like a drum, relieved only by eructations', 'Breath is cold, tongue is cold, knees are icy'],
      mindEmotional: 'Apathetic, sluggish, stuporous, indifferent to everything.',
      modalitiesBetter: ['Being fanned vigorously', 'Eructations', 'Cool open air'],
      modalitiesWorse: ['Warmth & stuffy rooms', 'Fatty food & butter', 'Lying flat in bed'],
      potenciesAndDosage: 'Acute: C30, C200. In critical collapse C30 repeated frequently.',
      defaultTagesdosis: '1–2 doses of 3–5 pellets',
      sphereOfAction: ['Venous Circulation & Capillaries', 'Upper Gastrointestinal Tract', 'Respiratory System'],
      differentialRemedies: ['Lycopodium (lower abdomen gas)', 'Arsenicum album', 'China (flatulence)', 'Camphora'],
      searchKeywords: ['vegetable charcoal', 'collapse', 'air hunger', 'fanning', 'flatulence', 'eructations', 'cold breath']
    },
    es: { commonName: 'Carbón vegetal' },
    fr: { commonName: 'Charbon végétal' },
    el: { commonName: 'Φυτικός άνθρακας' },
    it: { commonName: 'Carbone vegetale' },
    ru: { commonName: 'Древесный уголь' }
  },
  {
    id: 'causticum',
    latinName: 'Causticum Hahnemanni',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Hahnemanns Ätzstoff',
      origin: 'Spezielle Zubereitung nach Hahnemann aus gelöschtem Kalk und Kaliumbisulfat.',
      essence: 'Rebellischer Gerechtigkeitssinn und Mitleid mit anderen; allmählich fortschreitende Lähmungen (Stimmbänder, Blase), Heiserkeit und Besserung bei feucht-warmem Wetter.',
      mainIndications: ['Heiserkeit & Stimmlosigkeit (besonders morgens)', 'Harninkontinenz beim Husten oder Niesen', 'Fazialisparese nach kaltem Wind', 'Gelenksteifigkeit & Sehnenverkürzungen', 'Alte schmerzhafte Verbrennungsnarben'],
      keynotes: ['Heiserkeit morgens mit brennender Wundheit im Kehlkopf', 'Urin geht unwillkürlich ab beim Husten oder Lachen', 'Besserung aller Symptome bei feuchtem Regenwetter (Gegenteil von Rhus tox)', 'Patient verträgt kein Unrecht an anderen'],
      mindEmotional: 'Tiefes Mitgefühl mit dem Leiden anderer, kämpft gegen Ungerechtigkeit.',
      modalitiesBetter: ['Feuchtes, regnerisches Wetter', 'Wärme des Bettes'],
      modalitiesWorse: ['Trockener, kalter Wind', 'Zugluft', 'Morgens beim Erwachen'],
      potenciesAndDosage: 'D6, D12, C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Motorische Nerven & ZNS', 'Kehlkopf & Stimmbänder', 'Harnblase', 'Gelenke & Sehnen'],
      differentialRemedies: ['Rhus toxicodendron', 'Gelsemium', 'Phosphorus', 'Arum triphyllum'],
      searchKeywords: ['ätzstoff', 'causticum', 'mitleid', 'ungerechtigkeit', 'lähmung', 'harninkontinenz', 'regenwetter', 'stimmverlust']
    },
    en: {
      commonName: 'Hahnemann’s Causticum',
      origin: 'Hahnemann’s preparation of slaked lime and potassium bisulfate.',
      essence: 'Intense sympathy for others and rebellion against injustice; gradual progressive paralyses (vocal cords, bladder), morning hoarseness, and amelioration in damp rainy weather.',
      mainIndications: ['Hoarseness & aphonia worse in the morning', 'Stress incontinence when coughing or sneezing', 'Bell’s palsy / facial paralysis after dry cold wind', 'Joint stiffness & shortening of flexor tendons', 'Painful burns and old contracted scars'],
      keynotes: ['Morning hoarseness with burning rawness in larynx', 'Involuntary spurting of urine when coughing or laughing', 'Marked amelioration in wet damp rainy weather (opposite of Rhus tox)', 'Intense empathy and intolerance of injustice'],
      mindEmotional: 'Deeply sympathetic toward the suffering of others, champions justice.',
      modalitiesBetter: ['Damp wet rainy weather', 'Warmth of bed'],
      modalitiesWorse: ['Dry cold winds & drafts', 'Clear cold days', 'Morning on waking'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Motor Nervous System', 'Larynx & Vocal Cords', 'Bladder & Sphincter', 'Tendons & Joints'],
      differentialRemedies: ['Rhus toxicodendron', 'Gelsemium', 'Phosphorus', 'Arum triphyllum'],
      searchKeywords: ['causticum', 'sympathy', 'injustice', 'paralysis', 'incontinence', 'rainy better', 'hoarseness']
    },
    es: { commonName: 'Cáustico de Hahnemann' },
    fr: { commonName: 'Causticum' },
    el: { commonName: 'Καυστικό' },
    it: { commonName: 'Caustico di Hahnemann' },
    ru: { commonName: 'Каустикум Ганемана' }
  },
  {
    id: 'chamomilla',
    latinName: 'Matricaria chamomilla',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Echte Kamille',
      origin: 'Ganze frische blühende Kamillenpflanze (Asteraceae).',
      essence: 'Extreme Überempfindlichkeit gegen Schmerzen mit zorniger Wut und Reizbarkeit; Zahnungsbeschwerden bei Kleinkindern mit einer roten und einer blassen Wange; Kind beruhigt sich nur beim Umhertragen.',
      mainIndications: ['Schmerzhafte Zahnung bei Säuglingen & Kleinkindern', 'Gereizte Schmerzzustände & Koliken mit Wutausbrüchen', 'Dysmenorrhö & wehenartige Krämpfe mit unerträglichem Schmerz', 'Schlaflosigkeit & Alpträume durch Überreizung'],
      keynotes: ['Schmerzen sind völlig unerträglich und machen rasend vor Wut', 'Eine Wange rot und heiß, die andere blass und kalt', 'Kind verlangt Gegenstände und wirft sie zornig weg', 'Beruhigung nur durch ständiges rasches Umhertragen', 'Grünlicher, nach faulen Eiern riechender Stuhl'],
      mindEmotional: 'Zornig, ungeduldig, wütend, schreit bei Schmerzen, verträgt kein freundliches Zureden.',
      modalitiesBetter: ['Umhertragen des Kindes', 'Warmes, feuchtes Wetter'],
      modalitiesWorse: ['Ärger & Zorn', 'Nachts um 21:00 Uhr', 'Kaffee & Schmerzmittel', 'Kälte'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Zahnungsnot C30: 3–5 Globuli alle 30–60 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Emotionen', 'Magen-Darm-Trakt', 'Zähne & Mundhöhle'],
      differentialRemedies: ['Aconitum (Angst)', 'Belladonna (Hitze, Schweiß)', 'Pulsatilla (weinerlich, will Trost)', 'Colocynthis (Krämpfe)'],
      searchKeywords: ['kamille', 'zahnung', 'wut', 'zorn', 'schmerzempfindlich', 'tragen', 'wange', 'kolik', 'kinder']
    },
    en: {
      commonName: 'German Chamomile',
      origin: 'Whole fresh blooming plant of Matricaria chamomilla (Asteraceae).',
      essence: 'Extreme hypersensitivity to pain with frantic anger and snappish irritability; infant teething troubles with one cheek red and hot, the other pale and cold; calmed only when carried.',
      mainIndications: ['Painful teething in infants & toddlers', 'Irritable pain states & colic with violent temper tantrums', 'Severe dysmenorrhea with unbearable labor-like pains', 'Insomnia from nervous irritability and coffee abuse'],
      keynotes: ['Pains are utterly unbearable, driving patient to frantic rage', 'One cheek flushed and hot, the other pale and cool', 'Child demands toys and tosses them away in anger', 'Amelioration only by being carried constantly', 'Greenish stool smelling like rotten eggs'],
      mindEmotional: 'Spiteful, snappish, furious from pain, uncivil, rejects consolation.',
      modalitiesBetter: ['Being carried about in arms', 'Warm wet weather'],
      modalitiesWorse: ['Anger & vexation', 'Night around 9:00 PM', 'Coffee and narcotics', 'Cold wind'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In teething crises C30 every 30–60 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Central Nervous System & Temperament', 'Gastrointestinal Canal', 'Teeth & Dental Nerves'],
      differentialRemedies: ['Aconitum (anxiety, fright)', 'Belladonna (hot throbbing)', 'Pulsatilla (mild, tearful)', 'Colocynthis (doubling up)'],
      searchKeywords: ['chamomile', 'teething', 'anger', 'irritability', 'carried better', 'one red cheek', 'colic', 'pain sensitivity']
    },
    es: { commonName: 'Manzanilla alemana' },
    fr: { commonName: 'Camomille vraie' },
    el: { commonName: 'Χαμομήλι' },
    it: { commonName: 'Camomilla comune' },
    ru: { commonName: 'Ромашка аптечная' }
  },
  {
    id: 'chelidonium-majus',
    latinName: 'Chelidonium majus',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Schöllkraut',
      origin: 'Frische Wurzel des Schöllkrauts (Papaveraceae).',
      essence: 'Das Leber- und Gallenmittel: Schmerz unter dem rechten Schulterblattwinkel, gelbe Skleren und Vorliebe für heiße Getränke.',
      mainIndications: ['Leber- und Gallenerkrankungen (Ikterus, Cholezystitis)', 'Schmerzen unter dem rechten Schulterblatt', 'Gallenkolik & Hepatitis'],
      keynotes: ['Konstanter bohrender Schmerz am unteren Winkel des rechten Schulterblatts', 'Verlangen nach sehr heißen Getränken (bringen Erleichterung)', 'Gelbliche Verfärbung von Haut und Augen'],
      mindEmotional: 'Reizbar, rechthaberisch, mürrisch bei Leberstörungen.',
      modalitiesBetter: ['Sehr heiße Getränke', 'Nach dem Essen', 'Druck'],
      modalitiesWorse: ['Bewegung', 'Um 04:00 Uhr morgens und 16:00 Uhr nachmittags', 'Rechte Seite'],
      potenciesAndDosage: 'D4 bis C30. 2-3x täglich 5 Globuli.',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Leber & Gallenwege', 'Magen-Darm-Trakt', 'Rechtes Schulterblatt'],
      differentialRemedies: ['Carduus marianus', 'Lycopodium', 'Berberis', 'Nux vomica'],
      searchKeywords: ['schöllkraut', 'leber', 'galle', 'schulterblatt', 'ikterus', 'heiße getränke']
    },
    en: {
      commonName: 'Greater Celandine',
      origin: 'Fresh root and flowering plant of Chelidonium majus (Papaveraceae).',
      essence: 'The supreme hepatic and biliary remedy: constant pain under the inferior angle of right scapula, yellow conjunctivae, and relief from hot drinks.',
      mainIndications: ['Liver & gallbladder disorders (jaundice, cholecystitis)', 'Pain under inferior angle of right scapula', 'Biliary colic & sluggish liver'],
      keynotes: ['Constant dull aching fixed beneath right scapular angle', 'Intense desire for very hot drinks which relieve stomach', 'Yellow tint of whites of eyes and palms'],
      mindEmotional: 'Domineering, irritable, melancholic liver temperament.',
      modalitiesBetter: ['Very hot drinks', 'After dinner', 'Pressure'],
      modalitiesWorse: ['Motion', '4:00 AM and 4:00 PM', 'Right side'],
      potenciesAndDosage: 'D4 to C30 / 6C, 30C. 2-3 times daily 5 pellets.',
      defaultTagesdosis: '2-3 times daily 5 pellets',
      sphereOfAction: ['Liver & Biliary Ducts', 'Right Scapular Region', 'Digestive Canal'],
      differentialRemedies: ['Carduus marianus', 'Lycopodium', 'Berberis', 'Nux vomica'],
      searchKeywords: ['greater celandine', 'liver', 'gallbladder', 'scapula pain', 'jaundice', 'hot drinks']
    },
    es: { commonName: 'Celidonia mayor' },
    fr: { commonName: 'Grande chélidoine' },
    el: { commonName: 'Χελιδόνιο' },
    it: { commonName: 'Chelidonia' },
    ru: { commonName: 'Чистотел большой' }
  },
  {
    id: 'china-officinalis',
    latinName: 'Cinchona pubescens / China',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Chinarinde',
      origin: 'Getrocknete Rinde des Chinarindenbaums (Rubiaceae).',
      essence: 'Hahnemanns erstes Prüfungsmittel: Schwäche und Erschöpfung nach Verlust von Körpersäften (Blut, Schweiß, Durchfall, Stillen); Meteorismus des gesamten Bauches und extreme Berührungsempfindlichkeit der Haut.',
      mainIndications: ['Erschöpfung nach Blutverlust, Durchfall & langem Stillen', 'Meteorismus & Blähungskoliken (der ganze Bauch wie eine Trommel gespannt)', 'Periodisches Wechselfieber mit Schüttelfrost und Schweiß', 'Tinnitus & Schwindel nach Blutarmut'],
      keynotes: ['Verlust von Körpersäften als Ursache aller Beschwerden', 'Leichte Berührung ist unerträglich, aber fester Druck bessert', 'Der gesamte Bauch ist trommelartig gebläht, Abgang von Winden bringt keine Erleichterung', 'Periodische Wiederkehr der Beschwerden (jeden 2. oder 3. Tag)'],
      mindEmotional: 'Gereizt, unzufrieden, schwelgt in heroischen Phantasien im Bett.',
      modalitiesBetter: ['Fester Druck', 'Wärme', 'Zusammenkrümmen'],
      modalitiesWorse: ['Leichte Berührung & Zugluft', 'Verlust von Flüssigkeiten', 'Nach dem Essen'],
      potenciesAndDosage: 'D6, D12, C30. Nach Blutverlust/Durchfall 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Blut & Kreislauf', 'Magen-Darm-Trakt', 'Milz & Leber', 'Nervensystem'],
      differentialRemedies: ['Carbo vegetabilis', 'Phosphoricum acidum', 'Ferrum metallicum'],
      searchKeywords: ['chinarinde', 'china', 'saftverlust', 'blutverlust', 'blähbauch', 'schwäche', 'tinnitus', 'periodisch']
    },
    en: {
      commonName: 'Peruvian Bark / Quinquina',
      origin: 'Dried bark of Cinchona pubescens (Rubiaceae).',
      essence: 'Hahnemann’s foundational proving remedy: debility and exhaustion following loss of vital fluids (blood, sweat, diarrhea, prolonged nursing); tympanitic bloating of entire abdomen and hypersensitivity of skin to light touch.',
      mainIndications: ['Exhaustion following hemorrhages, diarrhea & lactation', 'Tympanitic bloating of entire abdomen without relief from flatus', 'Periodic intermittent fevers with chills and profuse sweat', 'Tinnitus and vertigo from anemia and fluid loss'],
      keynotes: ['Ailments from loss of vital bodily fluids', 'Slightest touch is painful, yet hard firm pressure relieves', 'Entire abdomen bloated tight like a drum; no relief from passing gas', 'Strict periodicity of attacks (every alternate day)'],
      mindEmotional: 'Touchy, irritable, builds grand heroic castles in the air at night.',
      modalitiesBetter: ['Hard firm pressure', 'Warmth', 'Bending double'],
      modalitiesWorse: ['Slight touch & draft of air', 'Loss of vital fluids', 'After meals'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Blood & Circulation', 'Gastrointestinal Canal', 'Spleen & Liver', 'Nervous System'],
      differentialRemedies: ['Carbo vegetabilis', 'Phosphoricum acidum', 'Ferrum metallicum'],
      searchKeywords: ['cinchona', 'china', 'fluid loss', 'hemorrhage', 'bloating', 'debility', 'periodicity', 'tinnitus']
    },
    es: { commonName: 'Quina' },
    fr: { commonName: 'Quinquina rouge' },
    el: { commonName: 'Κίνα' },
    it: { commonName: 'China' },
    ru: { commonName: 'Хинное дерево / Хина' }
  },
  {
    id: 'cicuta-virosa',
    latinName: 'Cicuta virosa',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Wasserschierling',
      origin: 'Frische Wurzel des Wasserschierlings (Apiaceae).',
      essence: 'Schwere epileptiforme Krämpfe mit Opisthotonus (nach hinten überstreckter Körper) und Verkrustungen im Gesicht (Impetigo).',
      mainIndications: ['Epilepsie & schwere Krämpfe mit Rückwärtsbeugen', 'Impetigo contagiosa mit dicken zitronengelben Krusten', 'Kopfverletzung mit Krämpfen'],
      keynotes: ['Opisthotonus: Kopf und Wirbelsäule krampfhaft nach hinten gebogen', 'Verzerrte Gesichtszüge und starre Augen bei Anfällen', 'Dicke, honiggelbe Krusten um Mund und Kinn'],
      mindEmotional: 'Kindisches Verhalten, singt, tanzt, verwechselt Gegenwart und Vergangenheit.',
      modalitiesBetter: ['Wärme', 'Ruhe'],
      modalitiesWorse: ['Berührung & Erschütterung', 'Kälte'],
      potenciesAndDosage: 'D6 bis C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Gehirn & Rückenmark', 'Haut (Gesichtskrusten)'],
      differentialRemedies: ['Cuprum metallicum', 'Hyoscyamus', 'Stramonium', 'Arnica'],
      searchKeywords: ['wasserschierling', 'krampf', 'opisthotonus', 'epilepsie', 'impetigo', 'krusten']
    },
    en: {
      commonName: 'Water Hemlock',
      origin: 'Fresh root of Cicuta virosa (Apiaceae).',
      essence: 'Violent epileptiform convulsions with opisthotonos (head drawn violently backward) and thick crusted eruptions on face (impetigo).',
      mainIndications: ['Epilepsy & severe spasms with backward arching', 'Impetigo contagiosa with thick lemon-yellow crusts', 'Convulsions resulting from head injuries'],
      keynotes: ['Opisthotonos: spine bent backward like an arch', 'Distorted facial spasms with staring eyes during fit', 'Thick honey-colored crusts around mouth and chin'],
      mindEmotional: 'Childish behavior, sings, dances, confuses present with past.',
      modalitiesBetter: ['Warmth', 'Quiet rest'],
      modalitiesWorse: ['Touch & jarring', 'Cold'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Brain & Cerebrospinal Axis', 'Skin (Facial Crusts)'],
      differentialRemedies: ['Cuprum metallicum', 'Hyoscyamus', 'Stramonium', 'Arnica'],
      searchKeywords: ['water hemlock', 'convulsions', 'opisthotonos', 'epilepsy', 'impetigo', 'head injury']
    },
    es: { commonName: 'Cicuta acuática' },
    fr: { commonName: 'Ciguë aquatique' },
    el: { commonName: 'Κικούτα' },
    it: { commonName: 'Cicuta acquatica' },
    ru: { commonName: 'Вех ядовитый / Цикута' }
  },
  {
    id: 'cimicifuga-racemosa',
    latinName: 'Cimicifuga racemosa / Actaea racemosa',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Traubensilberkerze',
      origin: 'Frischer Wurzelstock der Traubensilberkerze (Ranunculaceae).',
      essence: 'Gynäkologische Schmerzen proportional zur Blutungsstärke, Nacken- und Rückenschmerzen; Gefühl einer schweren schwarzen Wolke über dem Gemüt.',
      mainIndications: ['Prämenstruelles Syndrom & Dysmenorrhö (je mehr Blutung, desto mehr Schmerz)', 'Klimakterische Beschwerden mit Hitzewallungen & Depression', 'Nacken- und Schultersteife mit schießenden Schmerzen'],
      keynotes: ['Schmerzintensität steigt exakt mit der Stärke des Menstruationsflusses', 'Gefühl, als hinge eine dunkle schwere Wolke über dem Kopf', 'Schießende Schmerzen wie Elektroschocks in Oberschenkel und Rücken'],
      mindEmotional: 'Schwatzhaft (springt von Thema zu Thema), melancholisch, Angst vor Wahnsinn.',
      modalitiesBetter: ['Wärme', 'Essen'],
      modalitiesWorse: ['Während der Menstruation', 'Kälte & Nässe', 'Nacht'],
      potenciesAndDosage: 'D4 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Weibliche Geschlechtsorgane', 'Nacken & Wirbelsäule', 'Zentralnervensystem'],
      differentialRemedies: ['Sepia', 'Lachesis', 'Caulophyllum', 'Pulsatilla'],
      searchKeywords: ['silberkerze', 'cimicifuga', 'wechseljahre', 'menstruation', 'nacken', 'depression', 'hitzewallung']
    },
    en: {
      commonName: 'Black Cohosh',
      origin: 'Fresh rootstock of Actaea racemosa (Ranunculaceae).',
      essence: 'Uterine and pelvic pains directly proportional to the flow of menses, shooting muscular neck/back pains, and sensation of a heavy dark cloud hanging over the mind.',
      mainIndications: ['PMS & dysmenorrhea (pain increases with menstrual flow)', 'Menopausal hot flushes & depressive moodiness', 'Cervical stiffness and shooting muscular spasms'],
      keynotes: ['Pain increases in direct ratio with menstrual flow', 'Sensation as if a heavy black cloud settled over the head', 'Electric shock-like shooting pains darting through thighs and hips'],
      mindEmotional: 'Incessant loquacity changing rapidly from subject to subject; fear of impending insanity.',
      modalitiesBetter: ['Warmth', 'Eating'],
      modalitiesWorse: ['During menses', 'Cold damp drafts', 'Night'],
      potenciesAndDosage: 'D4 to C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Female Reproductive Axis', 'Cervical Spine & Muscles', 'Mind & Nervous System'],
      differentialRemedies: ['Sepia', 'Lachesis', 'Caulophyllum', 'Pulsatilla'],
      searchKeywords: ['black cohosh', 'menopause', 'dysmenorrhea', 'neck pain', 'black cloud', 'loquacity']
    },
    es: { commonName: 'Cimicífuga / Hierba de San Cristóbal' },
    fr: { commonName: 'Actée à grappes' },
    el: { commonName: 'Τσιμισιφούγκα' },
    it: { commonName: 'Cimicifuga' },
    ru: { commonName: 'Цимицифуга / Клопогон кистевидный' }
  },
  {
    id: 'cina-maritima',
    latinName: 'Artemisia cina',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Zitwerwurmsamen',
      origin: 'Getrocknete Blütenköpfe des Wurmsamens (Asteraceae).',
      essence: 'Typisches Wurmmittel bei Kindern: Ständiges Reiben und Bohren in der Nase, extreme Reizbarkeit (will nicht berührt oder getragen werden) und Heißhunger.',
      mainIndications: ['Wurmbefall (Oxyuren, Askariden) & Reizblase', 'Zähneknirschen im Schlaf & unruhiger Nachtschlaf', 'Reizbare, unzufriedene Kinder mit dunklen Augenringen'],
      keynotes: ['Bohrt und reibt ständig an der Nase', 'Zähneknirschen nachts und Erwachen mit Schreien', 'Heißhunger kurz nach einer vollen Mahlzeit'],
      mindEmotional: 'Extrem mürrisch, schnippisch, will weder berührt noch angesehen oder getragen werden.',
      modalitiesBetter: ['Bauchlage'],
      modalitiesWorse: ['Berührung & Ansehen', 'Nachts', 'Beim Wurmbefall'],
      potenciesAndDosage: 'D6, D12, C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Magen-Darm-Trakt (Parasiten)', 'Nervensystem', 'Nase'],
      differentialRemedies: ['Chamomilla (will getragen werden)', 'Santoninum', 'Spigelia', 'Teucrium'],
      searchKeywords: ['wurmsamen', 'cina', 'würmer', 'zähneknirschen', 'nase bohren', 'augenringe', 'kinder']
    },
    en: {
      commonName: 'Wormseed',
      origin: 'Dried flower heads of Artemisia cina (Asteraceae).',
      essence: 'Classic anthelmintic and worm symptom picture: persistent picking and rubbing of nose, extreme snappish irritability (refuses to be touched or carried), and canine hunger.',
      mainIndications: ['Helminthiasis (pinworms, roundworms) & enuresis', 'Nocturnal teeth grinding & restless startings in sleep', 'Ill-humored children with dark circles under eyes'],
      keynotes: ['Constantly rubs, bores, and picks at the nose', 'Grinds teeth in sleep and wakes screaming in terror', 'Ravenous hunger shortly after a full meal'],
      mindEmotional: 'Extremely cross, snappish, refuses to be touched, looked at, or carried.',
      modalitiesBetter: ['Lying on abdomen'],
      modalitiesWorse: ['Touch & being looked at', 'Nighttime', 'From worms'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Gastrointestinal Tract (Parasites)', 'Nervous System', 'Nose'],
      differentialRemedies: ['Chamomilla (demands carrying)', 'Santoninum', 'Spigelia', 'Teucrium'],
      searchKeywords: ['wormseed', 'worms', 'pinworms', 'teeth grinding', 'picking nose', 'irritable child']
    },
    es: { commonName: 'Cina / Semen contra' },
    fr: { commonName: 'Semen-contra' },
    el: { commonName: 'Κίνα μαριτίμα' },
    it: { commonName: 'Semencina' },
    ru: { commonName: 'Цина / Полынь цитварная' }
  },
  {
    id: 'cocculus-indicus',
    latinName: 'Anamirta cocculus',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Kockelskörner / Scheinmyrte',
      origin: 'Getrocknete Früchte von Anamirta cocculus (Menispermaceae).',
      essence: 'Reisekrankheit, Schwindel und Erschöpfung durch Nachtwachen, Schlafmangel oder Krankenpflege; Übelkeit beim Fahren in Autos, Zügen oder Schiffen.',
      mainIndications: ['Reisekrankheit (Kinetose) in Auto, Schiff & Flugzeug', 'Schlafmangel & Erschöpfung nach nächtlicher Krankenpflege', 'Drehschwindel mit Übelkeit beim Aufrichten im Bett'],
      keynotes: ['Übelkeit schon beim bloßen Anblick oder Geruch von Speisen', 'Gefühl von Leere und Hohlheit im Kopf und Bauch', 'Schlimmer durch passive Bewegung (Fahren, Schaukeln)'],
      mindEmotional: 'Verlangsamt, besorgt um kranke Angehörige, traurig nach Schlafmangel.',
      modalitiesBetter: ['Liegen in ruhigem, warmem Zimmer'],
      modalitiesWorse: ['Reisen & passive Bewegung', 'Schlafmangel & Nachtwachen', 'Geruch von Essen'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Reiseübelkeit 30 Min. vor Abfahrt C30 nehmen.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Gleichgewicht', 'Magen-Darm-Trakt'],
      differentialRemedies: ['Tabacum', 'Petroleum', 'Nux vomica', 'Phosphoricum acidum'],
      searchKeywords: ['kockelskörner', 'reisekrankheit', 'kinetose', 'nachtwache', 'schlafmangel', 'schwindel', 'übelkeit']
    },
    en: {
      commonName: 'Indian Cockle / Fish Berry',
      origin: 'Dried berries of Anamirta cocculus (Menispermaceae).',
      essence: 'Motion sickness, vertigo, and profound prostration from loss of sleep, night watching, and nursing the sick; nausea from riding in cars, boats, or trains.',
      mainIndications: ['Motion sickness (kinetosis) in cars, boats, or airplanes', 'Exhaustion & insomnia from night-nursing sick relatives', 'Rotary vertigo with nausea upon rising in bed'],
      keynotes: ['Nausea from the mere sight or smell of food', 'Sensation of hollow emptiness in head and abdomen', 'Violent aggravation from passive motion (riding, swinging)'],
      mindEmotional: 'Slow in responding, deeply anxious regarding sick relatives, drained.',
      modalitiesBetter: ['Lying quiet in a warm room'],
      modalitiesWorse: ['Passive motion (cars, boats, planes)', 'Loss of sleep & night sitting', 'Smell of food'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. For motion sickness C30 before departure.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Vestibular & Cerebrospinal System', 'Digestive Canal'],
      differentialRemedies: ['Tabacum', 'Petroleum', 'Nux vomica', 'Phosphoricum acidum'],
      searchKeywords: ['cocculus', 'motion sickness', 'night watching', 'sleep loss', 'vertigo', 'car sick']
    },
    es: { commonName: 'Cóculo índico' },
    fr: { commonName: 'Coque du Levant' },
    el: { commonName: 'Κόκκουλος' },
    it: { commonName: 'Cocculo' },
    ru: { commonName: 'Кукольван / Коккулюс' }
  },
  {
    id: 'coffea-cruda',
    latinName: 'Coffea arabica',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Rohkaffee',
      origin: 'Ungeröstete getrocknete Samen des Kaffeestrauchs (Rubiaceae).',
      essence: 'Nervöse Schlaflosigkeit durch Gedankenflut, freudige Erregung oder plötzliche gute Nachrichten; extreme Sinnesschärfe und Schmerzunverträglichkeit.',
      mainIndications: ['Schlaflosigkeit vor Aufregung & Gedankenandrang', 'Zahnschmerzen, die durch Eiswasser im Mund gelindert werden', 'Hyperästhesie aller Sinne (Lärm, Geruch, Licht)'],
      keynotes: ['Geist ist hellwach, Ideen strömen pausenlos durch den Kopf', 'Zahnschmerz bessert sich nur, solange Eiswasser im Mund gehalten wird', 'Schlimmer durch freudige Überraschungen und Kaffee'],
      mindEmotional: 'Euphorisch, übererregbar, voller Pläne, weint vor Freude.',
      modalitiesBetter: ['Eiswasser im Mund (Zähne)', 'Wärme (Körper)', 'Ruhe'],
      modalitiesWorse: ['Freudige Aufregung & Überraschung', 'Lärm & Gerüche', 'Nachts'],
      potenciesAndDosage: 'D6, D12, C30. Bei Schlaflosigkeit C30 abends 5 Globuli.',
      defaultTagesdosis: '1–2 Gaben à 3–5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Psyche', 'Sinnesorgane', 'Zahnnerven'],
      differentialRemedies: ['Chamomilla', 'Nux vomica', 'Ignatia', 'Aconitum'],
      searchKeywords: ['kaffee', 'schlaflosigkeit', 'gedankenflut', 'freude', 'zahnschmerz', 'eiswasser', 'übererregt']
    },
    en: {
      commonName: 'Raw Coffee',
      origin: 'Unroasted dried seeds of Coffea arabica (Rubiaceae).',
      essence: 'Nervous insomnia from rush of thoughts, joyful excitement, or pleasant surprises; extraordinary sensory acuity and acute pain intolerance.',
      mainIndications: ['Insomnia from ideational hyperactivity & sudden joy', 'Toothache relieved strictly by holding ice-water in the mouth', 'Hyperesthesia of all special senses (hearing, smell, light)'],
      keynotes: ['Brain is excessively wide awake with endless stream of ideas', 'Toothache instantly relieved by ice water held in mouth (worse as it warms)', 'Aggravated by pleasant surprises and excessive coffee'],
      mindEmotional: 'Euphoric, hyper-responsive, full of animated schemes, weeps with joy.',
      modalitiesBetter: ['Holding ice water in mouth (dental pain)', 'Warmth of room', 'Rest'],
      modalitiesWorse: ['Joyful excitement & surprise', 'Sudden noises', 'Nighttime'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. For insomnia C30 at bedtime.',
      defaultTagesdosis: '1–2 doses of 3–5 pellets',
      sphereOfAction: ['Central Nervous System & Brain', 'Sensory Organs', 'Dental Nerves'],
      differentialRemedies: ['Chamomilla', 'Nux vomica', 'Ignatia', 'Aconitum'],
      searchKeywords: ['coffee', 'insomnia', 'racing thoughts', 'joy', 'toothache', 'ice water better', 'sensory overload']
    },
    es: { commonName: 'Café crudo' },
    fr: { commonName: 'Café vert' },
    el: { commonName: 'Καφές' },
    it: { commonName: 'Caffè crudo' },
    ru: { commonName: 'Кофе сырой' }
  },
  {
    id: 'colchicum-autumnale',
    latinName: 'Colchicum autumnale',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Herbstzeitlose',
      origin: 'Frische Knollen der Herbstzeitlosen (Colchicaceae).',
      essence: 'Akute Gichtanfälle (besonders Großzehengrundgelenk) und extreme Ekel-Übelkeit schon beim bloßen Geruch oder Anblick von gekochtem Essen.',
      mainIndications: ['Akute Gicht der Großzehe (Podagra) & Arthritis urica', 'Schwangerschaftsübelkeit durch Essensgerüche', 'Wassersucht & Herzbeutelentzündung'],
      keynotes: ['Übelkeit bis zum Erbrechen beim Geruch von kochendem Essen (besonders Fisch/Fleisch)', 'Großzehe rot, glänzend geschwollen und unerträglich berührungsempfindlich', 'Geringste Erschütterung des Bettes verursacht Schmerzensschreie'],
      mindEmotional: 'Mürrisch, überempfindlich gegen Gerüche, Lärm und Licht.',
      modalitiesBetter: ['Wärme', 'Vornüberbeugen', 'Schlaf'],
      modalitiesWorse: ['Geruch von Speisen', 'Geringste Bewegung oder Erschütterung', 'Herbst'],
      potenciesAndDosage: 'D6, D12, C30. Im Gichtanfall D6 stündlich.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Gelenke & Sehnen (Großzehe)', 'Magen-Darm-Trakt', 'Harnwege'],
      differentialRemedies: ['Benzoicum acidum', 'Ledum', 'Sepia', 'Arsenicum album'],
      searchKeywords: ['herbstzeitlose', 'gicht', 'großzehe', 'podagra', 'essensgeruch', 'übelkeit', 'harnsäure']
    },
    en: {
      commonName: 'Meadow Saffron',
      origin: 'Fresh corms of Colchicum autumnale (Colchicaceae).',
      essence: 'Acute gouty paroxysms (especially big toe podagra) and sickening nausea provoked by the mere sight or odor of cooking food.',
      mainIndications: ['Acute gout of big toe (podagra) & uric arthritis', 'Morning sickness triggered by cooking odors', 'Pericardial effusion & dropsical states'],
      keynotes: ['Nausea to fainting from odor of food cooking (especially fish/meat)', 'Big toe red, hot, shining, exquisitely sensitive to slightest touch', 'Jarring of the bed or floor causes screams of pain'],
      mindEmotional: 'Peevish, hypersensitive to smells, bright lights, and noise.',
      modalitiesBetter: ['Warmth', 'Bending forward', 'Sleep'],
      modalitiesWorse: ['Smell or sight of food', 'Slightest motion or jar', 'Autumn weather'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. In acute gout D6 hourly.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Joints & Synovial Membranes (Great Toe)', 'Digestive System', 'Urinary Tract'],
      differentialRemedies: ['Benzoicum acidum', 'Ledum', 'Sepia', 'Arsenicum album'],
      searchKeywords: ['meadow saffron', 'gout', 'big toe', 'podagra', 'food odors', 'nausea']
    },
    es: { commonName: 'Cólquico / Cólquico de otoño' },
    fr: { commonName: 'Colchique d’automne' },
    el: { commonName: 'Κολχικό' },
    it: { commonName: 'Colchico autunnale' },
    ru: { commonName: 'Безвременник осенний' }
  },
  {
    id: 'colocynthis',
    latinName: 'Citrullus colocynthis',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Koloquinte / Bitterapfel',
      origin: 'Getrocknetes Fruchtfleisch des Bitterapfels (Cucurbitaceae).',
      essence: 'Heftigste schneidende Bauch- und Ischiasschmerzen nach Ärger oder Demütigung; Patient krümmt sich doppelt zusammen und drückt sich Gegenstände fest in den Bauch.',
      mainIndications: ['Akute Bauchkoliken & Nabelkoliken bei Kindern', 'Ischialgie (besonders rechts) mit Besserung durch festen Druck', 'Krampfhafte Dysmenorrhö (krümmt sich zusammen)'],
      keynotes: ['Bauchschmerz zwingt zum Zusammenkrümmen', 'Fester, harter Druck auf den Bauch bringt deutliche Erleichterung', 'Schmerzen ausgelöst durch Ärger, Zorn oder Kränkung'],
      mindEmotional: 'Äußerst gereizt, ungeduldig, wirft Gegenstände weg bei Zorn.',
      modalitiesBetter: ['Zusammenkrümmen', 'Fester harter Druck', 'Wärme'],
      modalitiesWorse: ['Ärger, Zorn & Demütigung', 'Aufrechtes Stehen', 'Nach dem Essen'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Koliken D6 alle 15–30 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Magen-Darm-Trakt & Bauchorgane', 'Nervus ischiadicus', 'Uterus'],
      differentialRemedies: ['Magnesia phosphorica (Wärme & leichter Druck)', 'Chamomilla', 'Dioscorea (besser durch Rückwärtsbeugen)'],
      searchKeywords: ['koloquinte', 'kolik', 'krämpfe', 'zusammenkrümmen', 'druckbesserung', 'ärger', 'ischias']
    },
    en: {
      commonName: 'Bitter Apple',
      origin: 'Dried fruit pulp of Citrullus colocynthis (Cucurbitaceae).',
      essence: 'Violent cutting abdominal cramps and sciatica triggered by anger or indignation; patient doubles up tightly and presses hard objects into the belly for relief.',
      mainIndications: ['Acute abdominal colic & umbilical cramps in infants', 'Right-sided sciatica relieved by hard firm pressure', 'Severe spasmodic dysmenorrhea doubling up in agony'],
      keynotes: ['Agonizing abdominal cramps compel doubling up', 'Hard, firm pressure on abdomen brings marked relief', 'Ailments triggered by anger with indignation or humiliation'],
      mindEmotional: 'Extremely irritable, indignant, snappish from pain.',
      modalitiesBetter: ['Doubling up tightly', 'Hard pressure & firm wrapping', 'Heat'],
      modalitiesWorse: ['Anger & indignation', 'Standing upright', 'Immediately after eating'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In acute colic D6 every 15–30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Abdominal Viscera & Colon', 'Sciatic Nerve', 'Pelvic Organs'],
      differentialRemedies: ['Magnesia phosphorica (heat and light pressure)', 'Chamomilla', 'Dioscorea (bending backward better)'],
      searchKeywords: ['bitter apple', 'colic', 'cramps', 'doubling up', 'pressure relief', 'anger', 'sciatica']
    },
    es: { commonName: 'Coloquíntida' },
    fr: { commonName: 'Coloquinte' },
    el: { commonName: 'Κολοκυνθίδα' },
    it: { commonName: 'Colocintide' },
    ru: { commonName: 'Колоцинт / Горькое яблоко' }
  },
  {
    id: 'conium-maculatum',
    latinName: 'Conium maculatum',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Gefleckter Schierling',
      origin: 'Frische blühende Pflanze des Gefleckten Schierlings (Apiaceae).',
      essence: 'Sokrates-Gift: Steinharte Drüsenschwellungen nach Quetschung (besonders Brustdrüse); Drehschwindel beim Umdrehen des Kopfes oder im Bett; aufsteigende Lähmungen und Beschwerden durch unterdrückte Sexualität.',
      mainIndications: ['Steinharte Knoten in der Brust nach Trauma/Schlag', 'Prostatahyperplasie & verhärtete Lymphknoten', 'Lagerungsschwindel beim Drehen des Kopfes oder Umdrehen im Bett', 'Beschwerden von zölibatär lebenden Menschen / Enthaltsamkeit'],
      keynotes: ['Steinharte Verhärtungen von Brust, Hoden oder Lymphknoten', 'Schwindel beim Umdrehen im Bett oder Kopfbewegen', 'Harnstrahl unterbricht wiederholt während des Wasserlassens', 'Aufsteigende Schwäche von den Beinen zum Rumpf'],
      mindEmotional: 'Geistig träge, verlangsamt, gleichgültig, meidet Gesellschaft.',
      modalitiesBetter: ['Dunkelheit', 'Hängenlassen der Gliedmaßen', 'Wärme'],
      modalitiesWorse: ['Kopfdrehen & Umdrehen im Bett', 'Enthaltsamkeit', 'Kälte'],
      potenciesAndDosage: 'D6 bis C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Drüsensystem (Mamma, Prostata)', 'Gehirn & Gleichgewicht', 'Motorische Nerven'],
      differentialRemedies: ['Baryta carbonica', 'Phytolacca', 'Silicea', 'Gelsemium'],
      searchKeywords: ['schierling', 'conium', 'schwindel', 'brustknoten', 'drüsenhärte', 'prostata', 'enthaltsamkeit']
    },
    en: {
      commonName: 'Poison Hemlock',
      origin: 'Fresh flowering herb of Conium maculatum (Apiaceae).',
      essence: 'Socrates’ poison: stony-hard glandular indurations following trauma (especially breasts); rotary vertigo when turning the head or rolling over in bed; ascending paralysis and ailments from celibacy.',
      mainIndications: ['Stony-hard breast lumps after injury/blow', 'Benign prostatic hypertrophy & indurated lymph nodes', 'Positional vertigo when turning head or rolling in bed', 'Ill effects of suppressed sexual desire / celibacy'],
      keynotes: ['Stony-hard induration of mammary glands, testicles, and nodes', 'Vertigo provoked by turning the head sideways or rolling over in bed', 'Intermittent flow of urine (stops and starts repeatedly)', 'Ascending muscular weakness from legs upward'],
      mindEmotional: 'Mental sluggishness, impaired memory, indifferent, averse to company.',
      modalitiesBetter: ['Darkness', 'Letting limbs hang down', 'Warmth'],
      modalitiesWorse: ['Turning head or rolling in bed', 'Celibacy', 'Cold air'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Glandular System (Breasts, Prostate)', 'Vestibular System', 'Spinal Motor Nerves'],
      differentialRemedies: ['Baryta carbonica', 'Phytolacca', 'Silicea', 'Gelsemium'],
      searchKeywords: ['poison hemlock', 'vertigo', 'breast lump', 'stony hard', 'prostate', 'celibacy']
    },
    es: { commonName: 'Cicuta mayor' },
    fr: { commonName: 'Grande ciguë' },
    el: { commonName: 'Κώνειο' },
    it: { commonName: 'Cicuta maggiore' },
    ru: { commonName: 'Болиголов пятнистый' }
  },
  {
    id: 'cuprum-metallicum',
    latinName: 'Cuprum metallicum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Metallisches Kupfer',
      origin: 'Reines elementares Kupfer (Cu).',
      essence: 'Das Hauptmittel für krampfartige Spasmen: Wadenkrämpfe, Keuchhusten mit Atemnot und Daumeneinschlagen in die Faust vor Krämpfen; Besserung durch Trinken von kaltem Wasser.',
      mainIndications: ['Wadenkrämpfe & nächtliche Muskelkrämpfe', 'Keuchhusten mit Erstickungsanfällen & Zyanose', 'Epilepsie mit Daumenkrallung in die Handflächen', 'Bauchkrämpfe & Cholerakrämpfe'],
      keynotes: ['Daumen werden vor und während des Krampfs fest in die Faust gekrallt', 'Schluck kaltes Wasser bringt sofortige Linderung des Hustens/Krampfs', 'Plötzlicher Beginn und Ende der Krämpfe'],
      mindEmotional: 'Ängstlich, nervös, scheu, fürchtet sich vor jedem Kontakt vor Anfällen.',
      modalitiesBetter: ['Trinken von kaltem Wasser', 'Schwitzen'],
      modalitiesWorse: ['Berührung & Kälte', 'Vor Einsetzen der Menses', 'Nachts'],
      potenciesAndDosage: 'D6, D12, C30. Bei akuten Krämpfen D6 alle 15–30 Min.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Motorik', 'Muskulatur & Spasmen', 'Atmungsorgane'],
      differentialRemedies: ['Magnesia phosphorica', 'Drosera', 'Cicuta virosa', 'Zincum'],
      searchKeywords: ['kupfer', 'krämpfe', 'wadenkrampf', 'keuchhusten', 'daumen', 'kaltes wasser', 'spasmus']
    },
    en: {
      commonName: 'Metallic Copper',
      origin: 'Pure elemental copper.',
      essence: 'The supreme spasmodic cramp remedy: severe nocturnal calf cramps, whooping cough with suffocation, and thumbs clenched tightly into fists; relief from sipping cold water.',
      mainIndications: ['Nocturnal leg & calf cramps', 'Whooping cough with cyanosis and breathless paroxysms', 'Epileptoid spasms with thumbs clenched into palms', 'Spasmodic choleraic abdominal cramps'],
      keynotes: ['Thumbs clenched tightly into palms before and during spasm', 'A sip of cold water dramatically stops the cough or spasm', 'Sudden abrupt onset and violent termination of spasms'],
      mindEmotional: 'Anxious, malicious delirium, screams before convulsions.',
      modalitiesBetter: ['Drinking a sip of cold water', 'Sweating'],
      modalitiesWorse: ['Touch & cold air', 'Before menses', 'Nighttime'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. In acute cramps D6 every 15–30 min.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Motor Nervous System', 'Striated & Smooth Muscle', 'Respiratory Tract'],
      differentialRemedies: ['Magnesia phosphorica', 'Drosera', 'Cicuta virosa', 'Zincum'],
      searchKeywords: ['copper', 'cramps', 'calf cramps', 'whooping cough', 'clenched thumbs', 'cold water sip']
    },
    es: { commonName: 'Cobre metálico' },
    fr: { commonName: 'Cuivre métallique' },
    el: { commonName: 'Χαλκός' },
    it: { commonName: 'Rame metallico' },
    ru: { commonName: 'Медь металлическая' }
  }
];

console.log('REMEDIES_PART2_BC defined with count:', REMEDIES_PART2_BC.length);
