# scripts/remedies_batch_a_f.py
# Classical remedies from A to F not yet in the initial 126

REMEDIES_A_F = [
    {
        "id": "actaea-spicata", "latin": "Actaea spicata", "cat": "plant", "authors": ["kent", "hering"], "poly": False, "tier": 2,
        "name_de": "Christophskraut", "name_en": "Baneberry",
        "origin_de": "Frische Wurzel von Actaea spicata (Hahnenfußgewächse).", "origin_en": "Fresh root of Actaea spicata (Ranunculaceae).",
        "essence_de": "Rheumatoide Schwellung der kleinen Hand- und Fußgelenke, extrem empfindlich gegen Berührung und Kälte.",
        "essence_en": "Rheumatic inflammation of the small joints of hands and feet, acutely sensitive to touch and cold air.",
        "indications_de": ["Arthrose der Finger- und Zehengelenke", "Gicht der Handgelenke", "Neuralgien des Gesichts"],
        "indications_en": ["Arthritis of small finger and toe joints", "Wrist gout", "Facial neuralgia"],
        "keynotes_de": ["Schwellung der Fingergelenke nach geringer Anstrengung", "Gelenke schwellen nach Ermüdung an", "Schmerz reißend und stechend"],
        "keynotes_en": ["Swelling of finger joints after slight exertion", "Joints swell after fatigue", "Tearing stitching pain"],
        "mind_de": "Ängstlich, fürchtet den Tod, besonders nachts im Bett.", "mind_en": "Anxious, fears death, especially at night in bed.",
        "better_de": ["Wärme", "Ruhiges Liegen"], "better_en": ["Warmth", "Quiet lying"],
        "worse_de": ["Berührung", "Kälte", "Bewegung der Gelenke"], "worse_en": ["Touch", "Cold", "Motion of joints"],
        "dosage_de": "D3 bis D6. 3x täglich 5 Tropfen.", "dosage_en": "3X to 6X. 5 drops 3 times daily.",
        "sphere": ["Kleine Gelenke", "Sehnen", "Periost"], "diffs": ["Caulophyllum", "Ledum", "Ruta"], "keywords": ["fingergelenke", "rheuma", "gicht", "christophskraut"]
    },
    {
        "id": "adonis-vernalis", "latin": "Adonis vernalis", "cat": "plant", "authors": ["hering"], "poly": False, "tier": 2,
        "name_de": "Frühlings-Adonisröschen", "name_en": "Pheasant's Eye",
        "origin_de": "Ganze blühende Pflanze von Adonis vernalis.", "origin_en": "Whole flowering plant of Adonis vernalis.",
        "essence_de": "Herzmittel bei Myokardschwäche, unregelmäßigem Puls und kardialen Ödemen mit Beklemmung.",
        "essence_en": "Cardiac remedy for weak irregular heart action, low vitality, and dropsy.",
        "indications_de": ["Herzinsuffizienz mit Ödemen", "Kardiale Dyspnoe", "Herzklopfen bei Schilddrüsenüberfunktion"],
        "indications_en": ["Congestive heart failure with edema", "Cardiac dyspnea", "Palpitations in hyperthyroidism"],
        "keynotes_de": ["Präkordialer Druck mit Schweregefühl auf der Brust", "Puls schnell, schwach und unregelmäßig", "Wassersucht mit spärlichem Urin"],
        "keynotes_en": ["Precordial oppression with heaviness on chest", "Pulse rapid, feeble, irregular", "Dropsy with scanty urine"],
        "mind_de": "Ängstlich um das Herz, unruhig, furchtsam im Dunkeln.", "mind_en": "Anxious about heart, restless, fearful in dark.",
        "better_de": ["Ruhe im Sitzen", "Frische Luft"], "better_en": ["Rest in sitting posture", "Fresh air"],
        "worse_de": ["Körperliche Anstrengung", "Flaches Liegen"], "worse_en": ["Physical exertion", "Lying flat"],
        "dosage_de": "D2 bis D4. 3x täglich 5 Tropfen.", "dosage_en": "2X to 4X. 5 drops 3 times daily.",
        "sphere": ["Herzmuskel", "Gefäßtonus", "Nierenfunktion"], "diffs": ["Digitalis", "Crataegus", "Convallaria"], "keywords": ["herzinsuffizienz", "puls", "ödeme", "herzklopfen", "adonis"]
    },
    {
        "id": "alstonia-scholaris", "latin": "Alstonia scholaris", "cat": "plant", "authors": ["hering"], "poly": False, "tier": 3,
        "name_de": "Dita-Rinde", "name_en": "Dita Bark",
        "origin_de": "Rinde von Alstonia scholaris (Apocynaceae).", "origin_en": "Bark of Alstonia scholaris (Apocynaceae).",
        "essence_de": "Malariale Rekonvaleszenz mit chronischer Diarrhö, Schwäche und Verdauungsversagen.",
        "essence_en": "Malarial debility with chronic camp diarrhea, indigestion, and profound exhaustion.",
        "indications_de": ["Chronische Diarrhö nach Tropenreisen", "Postinfektiöse Erschöpfung", "Dyspepsie mit Zungenbelag"],
        "indications_en": ["Chronic tropical diarrhea", "Post-infectious exhaustion", "Dyspepsia with coated tongue"],
        "keynotes_de": ["Wässrige, unverdaut abfließende Stühle", "Leeregefühl in der Magengrube", "Ständiges Frösteln trotz Wärme"],
        "keynotes_en": ["Watery lienteric stools", "Empty sinking sensation in epigastrium", "Chilly even in warm room"],
        "mind_de": "Geistig erschöpft, apathisch, melancholisch.", "mind_en": "Brain fag, listless, melancholic.",
        "better_de": ["Wärme", "Nach Ruhe"], "better_en": ["Warmth", "After rest"],
        "worse_de": ["Nach dem Essen", "Geringe Kälte"], "worse_en": ["After eating", "Slight cold"],
        "dosage_de": "D2 bis D6. 3x täglich 5 Tropfen.", "dosage_en": "2X to 6X. 5 drops 3 times daily.",
        "sphere": ["Darmtrakt", "Blutbildung", "Milz"], "diffs": ["China", "Chininum ars", "Alstonia"], "keywords": ["ditarinde", "durchfall", "tropen", "schwäche"]
    },
    {
        "id": "alumina-phosphorica", "latin": "Alumina phosphorica", "cat": "mineral", "authors": ["kent"], "poly": False, "tier": 3,
        "name_de": "Aluminiumphosphat", "name_en": "Aluminium Phosphate",
        "origin_de": "Chemische Verbindung aus Tonerde und Phosphorsäure.", "origin_en": "Chemical compound of alumina and phosphoric acid.",
        "essence_de": "Tiefe Nervenschwäche mit Gedächtnisverlust, chronischer Obstipation und Kälteempfindlichkeit.",
        "essence_en": "Profound nervous exhaustion with loss of memory, atonic constipation, and chilliness.",
        "indications_de": ["Parästhesien & Taubheitsgefühl", "Atonische Obstipation", "Geistige Erschöpfung", "Wirbelsäulenschwäche"],
        "indications_en": ["Paresthesia & numbness", "Atonic constipation", "Mental exhaustion", "Spinal weakness"],
        "keynotes_de": ["Trägheit des Rektums, weicher Stuhl erfordert starkes Pressen", "Kältegefühl in Wirbelsäule und Knochen", "Verwirrung über die eigene Person"],
        "keynotes_en": ["Inactivity of rectum, soft stool expelled with difficulty", "Coldness in spine and bones", "Confusion of personal identity"],
        "mind_de": "Gedächtnisschwund, ängstlich am Morgen, verwirrt.", "mind_en": "Loss of memory, morning anxiety, confused identity.",
        "better_de": ["Wärme", "Ruhiges Sitzen"], "better_en": ["Warmth", "Quiet sitting"],
        "worse_de": ["Kälte", "Geistige Arbeit", "Morgens"], "worse_en": ["Cold", "Mental labor", "Morning"],
        "dosage_de": "C30 oder C200. Seltene Gabe.", "dosage_en": "30C or 200C. Infrequent dose.",
        "sphere": ["Rückenmark", "ZNS", "Rektum"], "diffs": ["Alumina", "Phosphorus", "Plumbum"], "keywords": ["aluminiumphosphat", "nervenschwäche", "obstipation", "gedächtnis"]
    },
    {
        "id": "alumina-silicata", "latin": "Alumina silicata", "cat": "mineral", "authors": ["kent"], "poly": False, "tier": 3,
        "name_de": "Aluminiumsilikat", "name_en": "Aluminium Silicate",
        "origin_de": "Natürliches Aluminiumsilikat (Kaolin).", "origin_en": "Natural aluminium silicate (kaolin).",
        "essence_de": "Chronische Schwächezustände mit Eiterungsneigung, trockenem Katarrh und Verstopfung.",
        "essence_en": "Chronic debilitated states with tendency to suppuration, dry crusty catarrh, and constipation.",
        "indications_de": ["Rhinitis mit dicken Krusten", "Chronische Kachexie", "Obstipation durch Trockenheit"],
        "indications_en": ["Crusty nasal catarrh", "Chronic cachexia", "Constipation from dryness"],
        "keynotes_de": ["Trockenheit aller Schleimhäute", "Kältegefühl im Rücken und den Knochen", "Magert trotz gutem Appetit ab"],
        "keynotes_en": ["Dryness of mucous membranes", "Coldness in back and bones", "Emaciation despite good appetite"],
        "mind_de": "Mürrisch, niedergeschlagen, abgeneigt gegen Gesellschaft.", "mind_en": "Sullen, despondent, averse to company.",
        "better_de": ["Wärme", "Trockene Luft"], "better_en": ["Warmth", "Dry atmosphere"],
        "worse_de": ["Kälte & Feuchtigkeit", "Geistige Anstrengung"], "worse_en": ["Cold and damp", "Mental exertion"],
        "dosage_de": "C30 bis C200. Einzeldosis.", "dosage_en": "30C to 200C. Single dose.",
        "sphere": ["Schleimhäute", "Nervensystem", "Knochen"], "diffs": ["Alumina", "Silicea"], "keywords": ["krusten", "silikat", "abmagerung", "trockenheit"]
    },
    {
        "id": "ambrosia-artemisiifolia", "latin": "Ambrosia artemisiifolia", "cat": "plant", "authors": ["hering"], "poly": False, "tier": 2,
        "name_de": "Beifußblättrige Ambrosie", "name_en": "Ragweed",
        "origin_de": "Frische blühende Zweige von Ambrosia artemisiifolia.", "origin_en": "Fresh flowering tops of Ambrosia artemisiifolia.",
        "essence_de": "Spezifisches Heuschnupfenmittel mit heftigem Juckreiz der Augenlider und wässrigem Fließschnupfen.",
        "essence_en": "Specific remedy for hay fever with intense itching of eyelids and profuse watery coryza.",
        "indications_de": ["Heuschnupfen & Pollenallergie", "Asthma bronchiale im Spätsommer", "Allergische Konjunktivitis"],
        "indications_en": ["Hay fever & pollinosis", "Late summer asthma", "Allergic conjunctivitis"],
        "keynotes_de": ["Unerträgliches Jucken in Augen und Nase", "Ständiges Niesen mit wässrigem Sekret", "Engegefühl in der Brust bei Allergenkontakt"],
        "keynotes_en": ["Intolerable itching of eyes and nose", "Constant sneezing with watery discharge", "Chest wheezing upon pollen exposure"],
        "mind_de": "Gereizt durch das ständige Niesen, schläfrig am Tag.", "mind_en": "Irritable from sneezing, drowsy during day.",
        "better_de": ["Geschlossene Räume", "Kühle Waschungen der Augen"], "better_en": ["Indoors", "Cool bathing of eyes"],
        "worse_de": ["Freie Luft", "Pollenflug", "Spätsommer"], "worse_en": ["Open air", "Pollen exposure", "Late summer"],
        "dosage_de": "D3 bis D6. Während der Pollensaison 3x täglich 5 Tropfen.", "dosage_en": "3X to 6X. 5 drops 3 times daily in season.",
        "sphere": ["Nasenschleimhaut", "Augenbindehaut", "Bronchien"], "diffs": ["Sabadilla", "Allium cepa", "Euphrasia"], "keywords": ["heuschnupfen", "ambrosia", "pollenallergie", "augenjucken", "niesen"]
    },
    {
        "id": "ammoniacum-gummi", "latin": "Ammoniacum gummi", "cat": "plant", "authors": ["hering"], "poly": False, "tier": 3,
        "name_de": "Ammoniakgummi", "name_en": "Gum Ammoniac",
        "origin_de": "Gummicharz von Dorema ammoniacum.", "origin_en": "Gum resin of Dorema ammoniacum.",
        "essence_de": "Chronischer Bronchialkatarrh bei älteren Menschen mit reichlichem zähem Schleim und Asthma.",
        "essence_en": "Chronic bronchial catarrh in elderly subjects with tenacious mucus and asthmatic wheezing.",
        "indications_de": ["Senile Bronchitis", "Lungenemphysem", "Asthma mit zähem Auswurf"],
        "indications_en": ["Senile bronchitis", "Emphysema", "Asthma with tough expectoration"],
        "keynotes_de": ["Zäher, fadenziehender Schleim, schwer aufzuhusten", "Rasselnde Atmung mit Kurzatmigkeit bei Bewegung", "Gefühl von Rauch in den Atemwegen"],
        "keynotes_en": ["Tenacious adherent mucus difficult to raise", "Rattling breathing with dyspnea on walking", "Sensation of smoke in larynx"],
        "mind_de": "Ängstlich bei Atemnot, unruhig in der Nacht.", "mind_en": "Anxious with dyspnea, restless at night.",
        "better_de": ["Warmes Einhüllen", "Aufrechtes Sitzen"], "better_en": ["Warm wrapping", "Sitting upright"],
        "worse_de": ["Kaltes feuchtes Wetter", "Gehen", "Liegen"], "worse_en": ["Cold damp weather", "Walking", "Lying down"],
        "dosage_de": "D3 bis D6. 3x täglich 5 Tropfen.", "dosage_en": "3X to 6X. 5 drops 3 times daily.",
        "sphere": ["Bronchialschleimhaut", "Lunge", "Kehlkopf"], "diffs": ["Senega", "Antimonium tart", "Kali bich"], "keywords": ["senile bronchitis", "zäher schleim", "ammoniakgummi", "emphysem"]
    },
    {
        "id": "ammonium-benzoicum", "latin": "Ammonium benzoicum", "cat": "mineral", "authors": ["hering"], "poly": False, "tier": 3,
        "name_de": "Ammoniumbenzoat", "name_en": "Ammonium Benzoate",
        "origin_de": "Salz aus Ammoniak und Benzoesäure.", "origin_en": "Salt of ammonia and benzoic acid.",
        "essence_de": "Harnsäure-Diathese mit gichtigen Ablagerungen, rauchigem Urin und stechendem Geruch.",
        "essence_en": "Uric acid diathesis with gouty concretions, smoky turbid urine, and pungent ammoniacal odor.",
        "indications_de": ["Gichtknoten & Arthritis urica", "Chronische Zystitis", "Albuminurie mit Ödemen"],
        "indications_en": ["Gouty deposits & arthritis", "Chronic cystitis", "Albuminuria with swelling"],
        "keynotes_de": ["Urin dunkel, rauchig mit stechendem Geruch nach Pferdeharn", "Gichtige Schwellung der Zehen- und Fingergelenke", "Ödeme der Lider"],
        "keynotes_en": ["Urine dark smoky with pungent horse-like odor", "Gouty swelling of small joints", "Edema of eyelids"],
        "mind_de": "Trübsinnig, mürrisch bei Schmerzen.", "mind_en": "Gloomy, irritable during pains.",
        "better_de": ["Wärme", "Viel Trinken"], "better_en": ["Warmth", "Copious fluids"],
        "worse_de": ["Kälte", "Fleischverzehr", "Nässe"], "worse_en": ["Cold", "Meat diet", "Wet weather"],
        "dosage_de": "D3 bis D6. 3x täglich 1 Tablette.", "dosage_en": "3X to 6X. 1 tablet 3 times daily.",
        "sphere": ["Nieren & Harnwege", "Gelenke", "Stoffwechsel"], "diffs": ["Benzoic acid", "Ammonium carb", "Berberis"], "keywords": ["ammoniumbenzoat", "gicht", "harnsäure", "rauchiger urin"]
    },
    {
        "id": "ammonium-bromatum", "latin": "Ammonium bromatum", "cat": "mineral", "authors": ["hering"], "poly": False, "tier": 3,
        "name_de": "Ammoniumbromid", "name_en": "Ammonium Bromide",
        "origin_de": "Synthetisches Salz aus Ammoniak und Bromwasserstoff.", "origin_en": "Salt of ammonia and hydrobromic acid.",
        "essence_de": "Krampfhusten mit Erstickungsgefühl, Larynxkitzeln und Rötung der Augenränder.",
        "essence_en": "Spasmodic suffocation cough with laryngeal tickling and redness of lid margins.",
        "indications_de": ["Keuchhusten & Spasmen", "Chronische Pharyngitis", "Reizhusten nachts"],
        "indications_en": ["Whooping cough spasms", "Chronic pharyngitis", "Dry nocturnal cough"],
        "keynotes_de": ["Plötzlicher Kitzelhusten beim Hinlegen", "Krampfartiger Husten bis zum Erbrechen", "Zungenwurzel fühlt sich wie geschwollen an"],
        "keynotes_en": ["Sudden tickling cough on lying down", "Suffocative paroxysms ending in vomiting", "Root of tongue feels swollen"],
        "mind_de": "Nervös, fahrig, schreckhaft bei Geräuschen.", "mind_en": "Nervous, easily startled by sounds.",
        "better_de": ["Aufrechtes Sitzen", "Warme Getränke"], "better_en": ["Sitting erect", "Warm drinks"],
        "worse_de": ["Hinlegen", "Nachts zwischen 2 und 4 Uhr"], "worse_en": ["Lying down", "Night 2-4 AM"],
        "dosage_de": "D3 bis D6. 3x täglich 5 Tropfen.", "dosage_en": "3X to 6X. 5 drops 3 times daily.",
        "sphere": ["Kehlkopf & Trachea", "Nervensystem", "Augenlider"], "diffs": ["Drosera", "Bromium", "Hyoscyamus"], "keywords": ["ammoniumbromid", "krampfhusten", "kitzelhusten", "erstickungsgefühl"]
    },
    {
        "id": "ammonium-causticum", "latin": "Ammonium causticum", "cat": "mineral", "authors": ["hering"], "poly": False, "tier": 3,
        "name_de": "Salmiakgeist", "name_en": "Ammonia Water",
        "origin_de": "Wässrige Lösung von gasförmigem Ammoniak.", "origin_en": "Aqueous solution of ammonia gas.",
        "essence_de": "Heftigste Kehlkopfentzündung mit Membranbildung, Erstickungsanfällen und brennendem Wundschmerz.",
        "essence_en": "Violent membranous croup with suffocative spasms and raw burning pain in larynx.",
        "indications_de": ["Akute Laryngitis membranosa", "Kruppartige Anfälle", "Verätzungen der Schleimhaut"],
        "indications_en": ["Membranous croup", "Suffocative laryngeal spasm", "Mucosal caustic burns"],
        "keynotes_de": ["Brennender Schmerz im Hals wie mit Säure verätzt", "Stridor mit Erstickungsangst", "Vollständige Aphonie mit Speichelfluss"],
        "keynotes_en": ["Burning rawness in throat as if scalded", "Loud stridor with terror of suffocation", "Complete aphonia with salivation"],
        "mind_de": "Todesangst durch Erstickungsnot, verzweifelt.", "mind_en": "Terror of death from suffocation, desperate.",
        "better_de": ["Frische feuchte Luft", "Aufrechtes Sitzen"], "better_en": ["Cool humid air", "Sitting erect"],
        "worse_de": ["Schlucken", "Liegen", "Sprechen"], "worse_en": ["Swallowing", "Lying down", "Speaking"],
        "dosage_de": "D6 bis D12. Im Anfall D6 alle 15 Minuten.", "dosage_en": "6X to 12X. 6X every 15 minutes during spasm.",
        "sphere": ["Kehlkopf & Trachea", "Rachenschleimhaut"], "diffs": ["Spongia", "Hepar sulph", "Bromium"], "keywords": ["salmiakgeist", "krupp", "kehlkopf", "erstickung", "aphonie"]
    },
    {
        "id": "ammonium-iodatum", "latin": "Ammonium iodatum", "cat": "mineral", "authors": ["hering"], "poly": False, "tier": 3,
        "name_de": "Ammoniumiodid", "name_en": "Ammonium Iodide",
        "origin_de": "Salz aus Ammoniak und Iodwasserstoff.", "origin_en": "Salt of ammonia and hydriodic acid.",
        "essence_de": "Katarrhe der oberen Atemwege mit Schwellung der Lymphe und Schilddrüse, schlimmer in warmer Stube.",
        "essence_en": "Catarrh of upper airways with glandular and thyroid enlargement, worse in warm rooms.",
        "indications_de": ["Chronische Laryngitis", "Struma & Lymphknotenschwellung", "Asthmatische Bronchitis"],
        "indications_en": ["Chronic laryngitis", "Goiter & lymphadenopathy", "Asthmatic bronchitis"],
        "keynotes_de": ["Schwellung der Halslymphknoten mit Heiserkeit", "Trockener, schmerzhafter Kehlkopfhusten", "Verlangen nach frischer Luft"],
        "keynotes_en": ["Cervical lymph node swelling with hoarseness", "Dry painful laryngeal cough", "Craving for fresh open air"],
        "mind_de": "Unruhig, ängstlich, leicht erregbar.", "mind_en": "Restless, anxious, easily excited.",
        "better_de": ["Kühle frische Luft", "Kaltes Trinken"], "better_en": ["Cool open air", "Cold drinks"],
        "worse_de": ["Warme geschlossene Räume", "Nachts"], "worse_en": ["Warm closed rooms", "Night"],
        "dosage_de": "D3 bis D6. 3x täglich 5 Tropfen.", "dosage_en": "3X to 6X. 5 drops 3 times daily.",
        "sphere": ["Schilddrüse & Lymphdrüsen", "Atemwege"], "diffs": ["Iodium", "Ammonium carb", "Spongia"], "keywords": ["ammoniumiodid", "lymphknoten", "schilddrüse", "struma", "heiserkeit"]
    },
    {
        "id": "ammonium-valerianicum", "latin": "Ammonium valerianicum", "cat": "mineral", "authors": ["hering"], "poly": False, "tier": 3,
        "name_de": "Ammoniumvalerianat", "name_en": "Ammonium Valerianate",
        "origin_de": "Salz aus Ammoniak und Baldriansäure.", "origin_en": "Salt of ammonia and valeric acid.",
        "essence_de": "Nervöse Herzbeschwerden, Schlaflosigkeit und Hysterie bei überreizten Personen.",
        "essence_en": "Nervous cardiac palpitations, insomnia, and hysteria in hypersensitive individuals.",
        "indications_de": ["Nervöses Herzklopfen", "Schlaflosigkeit durch Gedankenandrang", "Hysterische Globusbeschwerden"],
        "indications_en": ["Nervous palpitations", "Insomnia from racing thoughts", "Hysterical globus"],
        "keynotes_de": ["Herzrasen bei geringster emotionaler Erregung", "Hyperästhesie aller Sinne", "Neuralgischer Kopfschmerz"],
        "keynotes_en": ["Tachycardia from emotional excitement", "Hyperesthesia of all senses", "Neuralgic clavus headache"],
        "mind_de": "Hysterisch, wechselhafte Stimmung, kann nicht abschalten.", "mind_en": "Hysterical, variable moods, racing mind.",
        "better_de": ["Bewegung im Freien", "Ablenkung"], "better_en": ["Motion in open air", "Diversion"],
        "worse_de": ["Emotionale Aufregung", "Ruhe", "Koffein"], "worse_en": ["Emotional excitement", "Quiet rest", "Caffeine"],
        "dosage_de": "D3 bis D6. 3x täglich 5 Tropfen.", "dosage_en": "3X to 6X. 5 drops 3 times daily.",
        "sphere": ["Vegetatives Nervensystem", "Herz & Gefäße"], "diffs": ["Valeriana", "Coffea", "Ignatia"], "keywords": ["ammoniumvalerianat", "baldrian", "herzklopfen", "hysterie", "schlaflosigkeit"]
    },
    {
        "id": "amylenum-nitrosum", "latin": "Amylenum nitrosum", "cat": "mineral", "authors": ["hering"], "poly": False, "tier": 2,
        "name_de": "Amylnitrit", "name_en": "Amyl Nitrite",
        "origin_de": "Flüssiger Salpetrigsäure-Isoamylester.", "origin_en": "Liquid isoamyl nitrite.",
        "essence_de": "Plötzliche Hitzewallungen im Klimakterium mit scharlachrotem Gesicht, Pulsieren der Halsschlagadern und Angst.",
        "essence_en": "Sudden climacteric flushes of heat with crimson face, throbbing carotids, and profound anxiety.",
        "indications_de": ["Klimakterische Hitzewallungen", "Angina pectoris mit Beklemmung", "Gefäßkrämpfe & Erröten"],
        "indications_en": ["Climacteric hot flashes", "Angina pectoris", "Vasospasm & blushing"],
        "keynotes_de": ["Plötzliche Hitze steigt in den Kopf, Gesicht wird feuerrot", "Pulsieren der Karotiden und Schläfenarterien", "Gefühl von Enge um die Brust und den Hals"],
        "keynotes_en": ["Surge of heat ascending to head with scarlet face", "Visible throbbing of carotids and temples", "Constriction around chest and neck"],
        "mind_de": "Große Angst, Furcht vor Ohnmacht oder Schlaganfall.", "mind_en": "Intense anxiety, fear of fainting or apoplexy.",
        "better_de": ["Frische kühle Luft", "Kaltes Wasser ins Gesicht"], "better_en": ["Cool fresh air", "Cold water to face"],
        "worse_de": ["Klimakterium", "Wärme", "Geringste Aufregung"], "worse_en": ["Climacteric", "Warmth", "Slightest excitement"],
        "dosage_de": "D6 bis C30. Im akuten Flush D6.", "dosage_en": "6X to 30C. 6X during acute flush.",
        "sphere": ["Vasomotorische Nerven", "Herzkranzgefäße", "Gehirndurchblutung"], "diffs": ["Glonoinum", "Lachesis", "Belladonna"], "keywords": ["amylnitrit", "hitzewallungen", "klimakterium", "rotes gesicht", "pulsieren"]
    },
    {
        "id": "anagallis-arvensis", "latin": "Anagallis arvensis", "cat": "plant", "authors": ["hering"], "poly": False, "tier": 3,
        "name_de": "Ackergauchheil", "name_en": "Scarlet Pimpernel",
        "origin_de": "Ganze frische blühende Pflanze von Anagallis arvensis.", "origin_en": "Whole fresh flowering plant of Anagallis arvensis.",
        "essence_de": "Hautausschläge an den Handflächen mit Bläschen, Juckreiz und Reizung der Harnröhre.",
        "essence_en": "Vesicular eruptions on palms of hands with violent itching and urethral irritation.",
        "indications_de": ["Dyshidrotisches Handekzem", "Urethritis & Brennen beim Wasserlassen", "Warzen an den Händen"],
        "indications_en": ["Dyshidrotic hand eczema", "Urethritis with burning", "Warts on hands"],
        "keynotes_de": ["Kleine Bläschen an Händen und Fingern mit starkem Juckreiz", "Kitzeln und Kribbeln in der Harnröhre", "Trockene Schuppung der Handflächen"],
        "keynotes_en": ["Small itchy vesicles on palms and fingers", "Tickling in urethra before urination", "Dry scaling of palms"],
        "mind_de": "Fröhlich, redselig, wechselnd zu Missmut.", "mind_en": "Exhilarated, talkative, alternating with moodiness.",
        "better_de": ["Kaffee", "Kratzen bis es blutet"], "better_en": ["Coffee", "Scratching until it bleeds"],
        "worse_de": ["Wasserberührung", "Seife", "Kälte"], "worse_en": ["Contact with water", "Soap", "Cold"],
        "dosage_de": "D3 bis D6. 3x täglich 5 Tropfen.", "dosage_en": "3X to 6X. 5 drops 3 times daily.",
        "sphere": ["Haut der Handflächen", "Harnröhre"], "diffs": ["Graphites", "Mezereum", "Rhus tox"], "keywords": ["ackergauchheil", "handekzem", "bläschen", "juckreiz", "harnröhre"]
    },
    {
        "id": "anhalonium-lewinii", "latin": "Anhalonium lewinii", "cat": "plant", "authors": ["hering"], "poly": False, "tier": 3,
        "name_de": "Peyote-Kaktus", "name_en": "Peyote",
        "origin_de": "Getrocknete Spitzen des Kaktus Lophophora williamsii.", "origin_en": "Dried tops of cactus Lophophora williamsii.",
        "essence_de": "Farbenreiche visuelle Halluzinationen, Entfremdung der Sinne und Depersonalisation.",
        "essence_en": "Brilliant colored visual hallucinations, depersonalization, and heightened sensory awareness.",
        "indications_de": ["Migräne mit visuellen Auren", "Schlaflosigkeit mit lebhaften Bildern", "Neurasthenie"],
        "indications_en": ["Migraine with visual aura", "Insomnia with kaleidoscope imagery", "Neurasthenia"],
        "keynotes_de": ["Wunderbare Farbenpracht vor geschlossenen Augen", "Gefühl der Spaltung der Persönlichkeit", "Verändertes Zeitempfinden"],
        "keynotes_en": ["Gorgeous kaleidoscopic visual imagery", "Sensation of divided personality", "Loss of time sense"],
        "mind_de": "Gefühl von Weltentrücktheit, Apathie gegen Pflichten.", "mind_en": "Detached from surroundings, apathy towards duties.",
        "better_de": ["Dunkler ruhiger Raum", "Liegen"], "better_en": ["Dark quiet room", "Lying down"],
        "worse_de": ["Bewegung", "Helles Licht", "Lärm"], "worse_en": ["Motion", "Bright light", "Noise"],
        "dosage_de": "C30. Einzeldosis.", "dosage_en": "30C. Single dose.",
        "sphere": ["ZNS & Wahrnehmung", "Sehnerv"], "diffs": ["Cannabis indica", "Stramonium", "Belladonna"], "keywords": ["peyote", "visionen", "farben", "halluzination", "zeitempfinden"]
    }
]

print(f"Loaded {len(REMEDIES_A_F)} remedies in remedies_batch_a_f.py")
