import { RawRemedy } from './buildRemedyUtils';

export const REMEDIES_PART6_MN: RawRemedy[] = [
  {
    id: 'magnesia-phosphorica',
    latinName: 'Magnesium phosphoricum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Magnesiumphosphat',
      origin: 'Reines Magnesiumhydrogenphosphat (MgHPO4 · 3H2O).',
      essence: 'Das homöopathische Schmerz- und Krampflösungsmittel („Homöopathisches Aspirin / Heiße 7“): Blitzartige, schießende, krampfhafte Schmerzen, die sich durch heiße Anwendungen und festen Druck schlagartig bessern.',
      mainIndications: ['Menstruationskrämpfe (Dysmenorrhö) & Bauchkoliken', 'Gallenkolik & Magen-Darm-Krämpfe', 'Trigeminusneuralgie & blitzartige Nervenschmerzen', 'Wadenkrämpfe & Muskelspasmen'],
      keynotes: ['Schmerzen bessern sich prompt durch heiße Umschläge, heiße Bäder und festen Druck', 'Krämpfe zwingen zum Zusammenkrümmen', 'Schmerzen schießen wie ein Blitz oder Stromschlag durch den Nerv', 'Besonders wirksam als „Heiße 7“ (in heißem Wasser gelöst und schluckweise getrunken)'],
      mindEmotional: 'Ängstlich, weint vor Schmerzen, ungeduldig vor Krämpfen.',
      modalitiesBetter: ['Hitze & heiße Umschläge', 'Fester Druck & Zusammenkrümmen', 'Reiben der Stelle'],
      modalitiesWorse: ['Kälte & Kaltluft', 'Berührung ohne Druck', 'Rechte Seite'],
      potenciesAndDosage: 'Akut: D6, D12, C30 (Schüßler-Salz Nr. 7). Bei Koliken/Krämpfen 10 Tabletten D6 in heißem Wasser lösen („Heiße 7“).',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Glatte & quergestreifte Muskulatur (Spasmen)', 'Periphere sensible Nerven (Neuralgien)', 'Uterus & Bauchorgane'],
      differentialRemedies: ['Colocynthis (besser durch Druck, aber Zorn)', 'Chamomilla', 'Dioscorea (besser Rückbeugen)', 'Belladonna'],
      searchKeywords: ['magnesiumphosphat', 'magnesia phosphorica', 'heiße 7', 'krämpfe', 'kolik', 'regelschmerzen', 'trigeminus', 'wärme bessert']
    },
    en: {
      commonName: 'Phosphate of Magnesia',
      origin: 'Pure magnesium phosphate.',
      essence: 'The supreme homeopathic antispasmodic and analgesic: lightning-fast, darting, cramping pains relieved promptly by local heat and firm pressure.',
      mainIndications: ['Dysmenorrhea (menstrual cramps) & abdominal colics', 'Biliary colic & spasmodic intestinal cramps', 'Trigeminal neuralgia & shooting electric nerve pains', 'Calf cramps, muscular spasms, and writer’s cramp'],
      keynotes: ['Pains promptly and dramatically relieved by heat, hot water bottles, and firm pressure', 'Cramps compel patient to double up', 'Pains shoot like an electric shock along nerves', 'Famously effective taken in hot water sips ("Hot 7")'],
      mindEmotional: 'Anxious, groans aloud with cramps, sensitive to pain.',
      modalitiesBetter: ['Local heat & hot applications', 'Firm pressure & bending double', 'Friction/rubbing'],
      modalitiesWorse: ['Cold air and cold applications', 'Light touching without firm pressure', 'Right side'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6X, 12X. In acute spasms dissolve 10 tablets in hot water and sip.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Smooth & Striated Muscle (Spasms)', 'Sensory Nerve Trunks (Neuralgia)', 'Uterus & Abdominal Viscera'],
      differentialRemedies: ['Colocynthis (better pressure, anger causations)', 'Chamomilla', 'Dioscorea (better bending back)', 'Belladonna'],
      searchKeywords: ['magnesium phosphate', 'mag phos', 'hot 7', 'cramps', 'colic', 'dysmenorrhea', 'sciatica', 'heat relieves']
    },
    es: { commonName: 'Fosfato de magnesio' },
    fr: { commonName: 'Phosphate de magnésium' },
    el: { commonName: 'Φωσφορικό μαγνήσιο' },
    it: { commonName: 'Fosfato di magnesio' },
    ru: { commonName: 'Фосфорнокислая магнезия / Магнезия фосфорика' }
  },
  {
    id: 'mercurius-solubilis',
    latinName: 'Mercurius solubilis Hahnemanni',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Quecksilber nach Hahnemann',
      origin: 'Hahnemannsches lösliches Quecksilber (Gemisch aus Quecksilber(I)-nitrat, Quecksilber(II)-oxid und Ammoniak).',
      essence: 'Das „menschliche Thermometer“: Äußerst empfindlich sowohl gegen Kälte als auch gegen Wärme; stinkender Mundgeruch, schlaffe feuchte Zunge mit Zahneindrücken, reichlicher nächtlicher Schweiß ohne Erleichterung und Eiterungen mit Drüsennschwellungen.',
      mainIndications: ['Eitrige Tonsillitis & eitriger Halsschmerz mit Speichelfluss', 'Stomatitis, Aphthen, Parodontitis & Mundgeruch', 'Otitis media mit eitrigem, übelriechendem Ausfluss', 'Gastroenteritis & Colitis mit schmerzhaftem Stuhldrang (Tenesmen)'],
      keynotes: ['Zunge ist groß, schlaff, feucht, gelb belegt und zeigt seitliche Zahneindrücke', 'Starker, faulig-metallischer Mundgeruch (Foetor ex ore)', 'Reichlicher nächtlicher Schweiß bringt keinerlei Linderung', 'Extreme Verschlimmerung nachts im warmen Bett'],
      mindEmotional: 'Misstrauisch, gehetzt, innerlich unruhig, zänkisch, Zwangsimpulse.',
      modalitiesBetter: ['Mäßige, gleichbleibende Temperatur', 'Ruhe'],
      modalitiesWorse: ['Nachts', 'Wärme des Bettes UND Kälte (Thermometer)', 'Feuchtes Wetter', 'Schwitzen'],
      potenciesAndDosage: 'D6 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Schleimhäute & Mundhöhle (Speichel, Aphthen)', 'Lymphknoten & Mandeln', 'Gastrointestinaltrakt & Rektum'],
      differentialRemedies: ['Hepar sulfuris', 'Nitricum acidum', 'Phytolacca', 'Belladonna'],
      searchKeywords: ['quecksilber', 'mercurius solubilis', 'zahneindrücke', 'mundgeruch', 'speichelfluss', 'nachtschweiß', 'mandeln', 'thermometer']
    },
    en: {
      commonName: 'Hahnemann’s Soluble Mercury',
      origin: 'Hahnemannian soluble mercury preparation.',
      essence: 'The "human thermometer": exquisitely sensitive to both cold and heat; intensely offensive fetid breath, flabby wet tongue indented by teeth, profuse nocturnal sweats without relief, and glandular suppuration.',
      mainIndications: ['Suppurative tonsillitis & quinsy with salivation', 'Ulcerative stomatitis, aphthae, gingivitis & halitosis', 'Acute otitis media with foul purulent otorrhoea', 'Dysentery & colitis with painful tenesmus ("never-get-done" sensation)'],
      keynotes: ['Tongue is large, moist, flabby, yellow-coated, imprinted with teeth indentations', 'Foul, metallic, penetrating breath odor (fetor oris)', 'Profuse night sweats afford zero relief of symptoms', 'Violent nocturnal aggravation in the warmth of bed'],
      mindEmotional: 'Suspicious, hurried, restless, irritable, impulsive, memory weak.',
      modalitiesBetter: ['Moderate, uniform, even temperature', 'Rest'],
      modalitiesWorse: ['Nighttime', 'Warmth of bed AND cold drafts (mercury thermometer)', 'Damp wet air', 'Sweating'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Mucous Membranes & Oral Cavity', 'Lymphatic Glands & Tonsils', 'Gastrointestinal & Rectum'],
      differentialRemedies: ['Hepar sulfuris', 'Nitricum acidum', 'Phytolacca', 'Belladonna'],
      searchKeywords: ['mercury', 'mercurius solubilis', 'teeth marks', 'bad breath', 'salivation', 'night sweat', 'tonsillitis']
    },
    es: { commonName: 'Mercurio soluble' },
    fr: { commonName: 'Mercure soluble d’Hahnemann' },
    el: { commonName: 'Υδράργυρος' },
    it: { commonName: 'Mercurio solubile' },
    ru: { commonName: 'Меркуриус солюбилис / Ртуть растворимая' }
  },
  {
    id: 'mezereum',
    latinName: 'Daphne mezereum',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Gemeiner Seidelbast / Kellerhals',
      origin: 'Frische Rinde des Seidelbasts vor der Blüte (Thymelaeaceae).',
      essence: 'Dicke, lederartige Schuppen und Krusten auf der Kopfhaut, unter denen sich weißer, dicker Eiter ansammelt; quälende Knochenschmerzen (besonders Schienbeine) und Neuralgien nach Herpes zoster.',
      mainIndications: ['Herpes zoster (Gürtelrose) & postzosterische Neuralgie', 'Krusten- und Schuppenekzeme mit Eiter unter der Kruste', 'Periostitis & nächtliche Schienbeinschmerzen', 'Zahnschmerzen mit Zahnzerfall'],
      keynotes: ['Dicke lederartige Krusten mit Eitersee darunter', 'Brennender, unerträglicher Juckreiz der Haut, der beim Kratzen den Ort wechselt', 'Knochenschmerzen verschlimmern sich nachts in der Bettwärme'],
      mindEmotional: 'Gereizt, mürrisch, weinerlich, klagt über ständige Schmerzen.',
      modalitiesBetter: ['Im Freien', 'Kühle Umschläge'],
      modalitiesWorse: ['Bettwärme & warme Umschläge', 'Nachts', 'Berührung & Kälte'],
      potenciesAndDosage: 'D6 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Haut (Herpes zoster, Krusten)', 'Sensible Nerven (Neuralgien)', 'Periost & Knochen (Tibia)'],
      differentialRemedies: ['Rhus tox', 'Ranunculus bulbosus', 'Graphites', 'Arsenicum album'],
      searchKeywords: ['seidelbast', 'mezereum', 'gürtelrose', 'herpes zoster', 'krusten', 'eiter', 'schienbein', 'neuralgie']
    },
    en: {
      commonName: 'Spurge Olive / Mezereon',
      origin: 'Fresh bark of Daphne mezereum (Thymelaeaceae).',
      essence: 'Thick, leathery crusts and scabs on scalp beneath which thick white pus collects; agonizing periosteal bone pains (especially tibiae) and post-herpetic neuralgia.',
      mainIndications: ['Herpes zoster (shingles) & post-herpetic neuralgias', 'Crusted scabby eczema with pus beneath the crust', 'Periostitis & nocturnal agonizing tibial pains', 'Carious decay of teeth roots with pain'],
      keynotes: ['Thick, tough leathery crusts concealing collection of pus underneath', 'Intolerable burning itching of skin shifting to another spot when scratched', 'Violent bone aching aggravated at night in the warmth of bed'],
      mindEmotional: 'Irritable, morose, fretful, constantly complaining of pains.',
      modalitiesBetter: ['Open cool air', 'Cold applications'],
      modalitiesWorse: ['Warmth of bed', 'Nighttime', 'Touch and cold damp air'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Skin (Herpes Zoster, Crusted Eruptions)', 'Sensory Nerves (Neuralgia)', 'Periosteum & Bones (Tibiae)'],
      differentialRemedies: ['Rhus tox', 'Ranunculus bulbosus', 'Graphites', 'Arsenicum album'],
      searchKeywords: ['mezereum', 'shingles', 'herpes zoster', 'post herpetic neuralgia', 'crusts', 'tibia', 'bone pain']
    },
    es: { commonName: 'Mecereón / Laureola hembra' },
    fr: { commonName: 'Bois-gentil / Mézéréon' },
    el: { commonName: 'Δάφνη mezereum' },
    it: { commonName: 'Mezereo / Fior di stecco' },
    ru: { commonName: 'Волчеягодник обыкновенный / Мезереум' }
  },
  {
    id: 'millefolium',
    latinName: 'Achillea millefolium',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Gemeine Schafgarbe',
      origin: 'Ganze frische blühende Pflanze der Schafgarbe (Asteraceae).',
      essence: 'Das Hämostatikum für schmerzlose, passive oder aktive hellrote Blutungen aus allen Körperöffnungen nach Überanstrengung oder Verletzungen.',
      mainIndications: ['Nasenbluten (Epistaxis) & Bluterbrechen', 'Hämorrhoidalblutungen & Uterusblutungen (schmerzlos)', 'Bluthusten (Hämoptoe) nach schwerem Heben oder Trauma'],
      keynotes: ['Blut ist hellrot, dünnflüssig und strömt ohne Schmerzen hervor', 'Blutungen nach Sturz, Verheben oder Überanstrengung'],
      mindEmotional: 'Ängstlich durch den plötzlichen Blutverlust.',
      modalitiesBetter: ['Ruhe', 'Kälte'],
      modalitiesWorse: ['Körperliche Anstrengung & Heben', 'Bücken'],
      potenciesAndDosage: 'D3 bis D12. Bei akuter Blutung alle 10–15 Min. 5 Tropfen oder Globuli.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Gefäßsystem & Kapillaren', 'Uterus', 'Atmungs- & Magen-Darm-Trakt'],
      differentialRemedies: ['Hamamelis (dunkles Blut)', 'Ipecacuanha', 'Arnica', 'Phosphorus'],
      searchKeywords: ['schafgarbe', 'millefolium', 'blutung', 'hellrot', 'nasenbluten', 'überanstrengung', 'schmerzlos']
    },
    en: {
      commonName: 'Yarrow',
      origin: 'Whole fresh flowering plant of Achillea millefolium (Asteraceae).',
      essence: 'The supreme mechanical hemostatic for painless, bright red, profuse hemorrhages from any body orifice following mechanical trauma or heavy physical strain.',
      mainIndications: ['Epistaxis (nosebleeds) & hematemesis', 'Painless bleeding hemorrhoids & menorrhagia', 'Hemoptysis after heavy lifting or blunt injury'],
      keynotes: ['Bright red, fluid blood flowing painlessly in torrents', 'Hemorrhages provoked by falling, heavy lifting, or overexertion'],
      mindEmotional: 'Anxious from sight and suddenness of bleeding.',
      modalitiesBetter: ['Rest', 'Cold'],
      modalitiesWorse: ['Physical exertion & heavy lifting', 'Stooping'],
      potenciesAndDosage: 'D3 to D12 / 3X to 12X. In acute hemorrhage every 10–15 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Capillary Blood Vessels', 'Uterine Vascular System', 'Respiratory & Gastrointestinal Mucosa'],
      differentialRemedies: ['Hamamelis (dark venous blood)', 'Ipecacuanha', 'Arnica', 'Phosphorus'],
      searchKeywords: ['yarrow', 'millefolium', 'bleeding', 'bright red blood', 'nosebleed', 'hemorrhage', 'lifting']
    },
    es: { commonName: 'Milenrama / Aquilea' },
    fr: { commonName: 'Millefeuille / Achillée' },
    el: { commonName: 'Αχίλλεια' },
    it: { commonName: 'Millefoglio' },
    ru: { commonName: 'Тысячелистник обыкновенный' }
  },
  {
    id: 'natrium-muriaticum',
    latinName: 'Natrium chloratum / Natrium muriaticum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Kochsalz / Natriumchlorid',
      origin: 'Reines Natriumchlorid (NaCl).',
      essence: 'Das große Mittel für chronischen Kummer, Einsamkeit und Wasserhaushaltsstörungen: Verschlossenes Gemüt, weint heimlich, verträgt keinerlei Trost (Trost macht wütend); rissige Unterlippe in der Mitte, Heißhunger auf Salz, Sonnenallergie und herpesartige Lippenbläschen.',
      mainIndications: ['Chronischer unterdrückter Kummer & Enttäuschung', 'Lippenherpes & Rhagade in der Mitte der Unterlippe', 'Pochende Hämmerkopfschmerzen wie von kleinen Hämmern (10 bis 15 Uhr)', 'Trockene Schleimhäute & Verstopfung mit trockenem, bröckeligem Stuhl'],
      keynotes: ['Trost verschlimmert massiv (macht zornig oder weinerlich)', 'Tiefer Riss genau in der Mitte der Unterlippe', 'Unstillbares Verlangen nach Salz und salzigen Speisen', 'Kopfschmerz verschlimmert sich durch geistige Anstrengung und Sonnenlicht von 10 bis 15 Uhr', 'Abmagerung besonders im Nacken- und Halsbereich trotz gutem Appetit'],
      mindEmotional: 'Verschlossen, nachtragend, brütet über vergangenen Kränkungen, introvertiert.',
      modalitiesBetter: ['Im Freien', 'Kaltes Waschen', 'Auslassen von Mahlzeiten', 'Dunkler Raum'],
      modalitiesWorse: ['Trost & Mitleid', 'Sonneneinstrahlung & Sommerhitze', 'Um 10:00 bis 11:00 Uhr morgens', 'Am Meer'],
      potenciesAndDosage: 'C30, C200. Bei chronischem Kummer C30 1x wöchentlich.',
      defaultTagesdosis: '1 Gabe à 3–5 Globuli',
      sphereOfAction: ['Wasser- & Elektrolythaushalt', 'Psyche & Emotionen', 'Haut & Lippen', 'Blut & Schleimhäute'],
      differentialRemedies: ['Ignatia (akuter Kummer)', 'Sepia', 'Phosphoricum acidum', 'Pulsatilla (sucht Trost)'],
      searchKeywords: ['kochsalz', 'natrium muriaticum', 'kummer', 'trost verschlimmert', 'salzhunger', 'lippenriss', 'herpes', 'sonnenallergie', 'hämmerkopfschmerz']
    },
    en: {
      commonName: 'Common Salt / Sodium Chloride',
      origin: 'Pure sodium chloride.',
      essence: 'The supreme grief, emotional reserve, and fluid balance polychrest: silent brooding grief, weeps in isolation, fiercely rejects consolation (consolation infuriates); deep crack in middle of lower lip, craving for salt, sun headache, and fever blisters.',
      mainIndications: ['Chronic suppressed grief, romantic heartbreak & resentment', 'Herpes labialis & vertical fissure in center of lower lip', 'Hammering throbbing morning headache (10 AM to 3 PM)', 'Dry mucous membranes & obstinate constipation with dry crumbly stools'],
      keynotes: ['Consolation violently aggravates (causes anger or renewed weeping)', 'Deep vertical fissure in exact midline of lower lip', 'Intense unquenchable craving for salt and salty snacks', 'Hammering headache aggravated by reading and bright sun from 10 AM to 3 PM', 'Emaciation marked around the neck and collarbones despite eating well'],
      mindEmotional: 'Introverted, holds grudges, dwells on past grievances, cannot weep before others.',
      modalitiesBetter: ['Open fresh air', 'Cold water bathing', 'Skipping meals', 'Lying in a dark quiet room'],
      modalitiesWorse: ['Consolation & sympathy', 'Direct sun glare & summer heat', '10:00 to 11:00 AM', 'At the seashore'],
      potenciesAndDosage: 'C30, C200 / 30C, 200C. In chronic held grief C30 once weekly.',
      defaultTagesdosis: '1 dose of 3–5 pellets',
      sphereOfAction: ['Fluid & Osmotic Balance', 'Emotional Nervous System', 'Skin & Mucocutaneous Junctions', 'Blood'],
      differentialRemedies: ['Ignatia (acute grief)', 'Sepia', 'Phosphoricum acidum', 'Pulsatilla (craves consolation)'],
      searchKeywords: ['table salt', 'natrum mur', 'nat mur', 'grief', 'consolation worse', 'salt craving', 'split lower lip', 'cold sores', 'hammering headache']
    },
    es: { commonName: 'Sal común / Cloruro de sodio' },
    fr: { commonName: 'Chlorure de sodium / Sel marin' },
    el: { commonName: 'Χλωριούχο νάτριο' },
    it: { commonName: 'Cloruro di sodio' },
    ru: { commonName: 'Натрия хлорид / Поваренная соль' }
  },
  {
    id: 'natrium-sulfuricum',
    latinName: 'Natrium sulfuricum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Natriumsulfat / Glaubersalz',
      origin: 'Reines Natriumsulfat (Na2SO4 · 10H2O).',
      essence: 'Das große Mittel für Beschwerden durch Feuchtigkeit und Nässe (Wasseradern, feuchte Keller, Regenwetter): Früh-morgendlicher Durchfall (treibt aus dem Bett), Asthma bei nasskaltem Wetter und Gemütsveränderungen nach Kopfverletzung.',
      mainIndications: ['Asthma bronchiale & chronischer Husten bei nasskaltem Wetter', 'Frühmorgendlicher wässriger Durchfall mit viel Gasabgang', 'Persönlichkeitsveränderungen & Kopfschmerz nach Schädel-Hirn-Trauma', 'Chronische Leberbeschwerden & Gelbsucht'],
      keynotes: ['Muss beim Husten die Brust mit beiden Händen festhalten', 'Durchfall treibt den Patienten sofort nach dem Aufstehen aus dem Bett', 'Verschlimmerung in feuchten Räumen, Kellern oder an Seen/Flüssen', 'Suizidale Gedanken bei feuchtem Wetter, muss sich beherrschen'],
      mindEmotional: 'Traurig, depressiv bei feuchtem Wetter, reizbar am Morgen.',
      modalitiesBetter: ['Trockenes, warmes Wetter', 'Im Freien', 'Nach Stuhlgang'],
      modalitiesWorse: ['Nasskaltes Wetter & feuchte Keller', 'Frühmorgens beim Aufstehen', 'Liegen auf der linken Seite'],
      potenciesAndDosage: 'D6, D12, C30 (Schüßler-Salz Nr. 10). 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Atemwege & Lunge (Asthma)', 'Leber, Galle & Darm', 'Gehirn (nach Trauma)'],
      differentialRemedies: ['Dulcamara', 'Thuja occidentalis', 'Rhus tox', 'Natrium muriaticum'],
      searchKeywords: ['glaubersalz', 'natrium sulfuricum', 'feuchtigkeit', 'feuchter keller', 'asthma', 'frühmorgendlicher durchfall', 'schädeltrauma']
    },
    en: {
      commonName: 'Sulfate of Sodium / Glauber’s Salt',
      origin: 'Pure sodium sulfate.',
      essence: 'The supreme hydrogenoid remedy for ailments provoked by dampness (living in basements, rainy damp weather, living near water): morning diarrhea driving out of bed, asthma in damp weather, and personality changes after head injury.',
      mainIndications: ['Bronchial asthma & humid rattling cough in cold wet weather', 'Early morning watery diarrhea with noisy flatus', 'Mental depression & headaches following head trauma/concussion', 'Chronic liver congestion & biliousness'],
      keynotes: ['Must hold chest firmly with both hands while coughing', 'Diarrhea drives patient out of bed immediately upon rising in morning', 'Violent aggravation in damp basements, damp houses, and rainy weather', 'Suicidal depression in damp weather, has to restrain himself'],
      mindEmotional: 'Melancholic, depressed in damp weather, irritable on waking.',
      modalitiesBetter: ['Dry warm weather', 'Open fresh air', 'After passing stool and flatus'],
      modalitiesWorse: ['Damp cold air, rain & wet basements', 'Early morning on rising', 'Lying on left side'],
      potenciesAndDosage: 'D6, D12, C30 / 6X, 12X. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Respiratory Mucosa (Asthma)', 'Liver, Biliary Ducts & Intestines', 'Brain (Post-Concussion)'],
      differentialRemedies: ['Dulcamara', 'Thuja occidentalis', 'Rhus tox', 'Natrium muriaticum'],
      searchKeywords: ['glauber salt', 'natrum sulf', 'dampness', 'wet basements', 'asthma in damp', 'morning diarrhea', 'head injury']
    },
    es: { commonName: 'Sulfato de sodio / Sal de Glauber' },
    fr: { commonName: 'Sulfate de sodium / Sel de Glauber' },
    el: { commonName: 'Θειικό νάτριο' },
    it: { commonName: 'Solfato di sodio' },
    ru: { commonName: 'Натрия сульфат / Глауберова соль' }
  },
  {
    id: 'nitricum-acidum',
    latinName: 'Acidum nitricum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Salpetersäure',
      origin: 'Reine Salpetersäure (HNO3).',
      essence: 'Stechende Splitterschmerzen an allen Schleimhautübergängen (Mund, Anus, Harnröhre); stinkender, ätzender Urin (wie Pferdeharn) und unversöhnlicher, rachsüchtiger Groll.',
      mainIndications: ['Schmerzhafte Analfissuren mit stundenlangen Nachwehen nach Stuhlgang', 'Splitterartige Halsschmerzen & Aphthen', 'Geschwüre & Warzen mit gezackten Rändern, die leicht bluten', 'Harnwegsinfekte mit stinkendem Urin wie Pferdeharn'],
      keynotes: ['Schmerzen fühlen sich an wie ein scharfer Glassplitter oder Holzspan', 'Analfissurschmerz hält noch stundenlang nach der Defäkation an', 'Urin riecht extrem stechend und intensiv wie Pferdemist/Pferdeharn', 'Besserung aller Symptome beim Fahren im Auto oder Zug'],
      mindEmotional: 'Unversöhnlich, hegt tiefen Groll, rachsüchtig, verzweifelt an Gesundheit.',
      modalitiesBetter: ['Fahren im Auto, Zug oder Wagen', 'Milde gleichmäßige Temperatur'],
      modalitiesWorse: ['Kälte & Wetterwechsel', 'Berührung', 'Nach dem Stuhlgang', 'Nachts'],
      potenciesAndDosage: 'D6 bis C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Haut-Schleimhaut-Grenzen (Anus, Mund, Meatus)', 'Harnwege & Blase', 'Haut & Warzen'],
      differentialRemedies: ['Hepar sulfuris (Splitter, Kälte)', 'Mercurius solubilis', 'Causticum', 'Thuja'],
      searchKeywords: ['salpetersäure', 'nitricum acidum', 'splittergefühl', 'analfissur', 'pferdeharn', 'warzen', 'unversöhnlich', 'auto fahren bessert']
    },
    en: {
      commonName: 'Nitric Acid',
      origin: 'Pure nitric acid.',
      essence: 'Sharp splinter-like stitching pains at all mucocutaneous junctions (mouth, anus, urethra); foul, offensive, horse-urine-smelling urine; unforgiving, resentful, and vindictive mind.',
      mainIndications: ['Painful anal fissures with agonizing pain lasting hours after stool', 'Splinter-like sore throat & ulcerated aphthae', 'Ulcers & bleeding jagged warts', 'Urinary tract infections with urine smelling like horse urine'],
      keynotes: ['Pains like a sharp splinter or shard of glass sticking in tissue', 'Anal fissure pain persists for hours after defecation', 'Urine smells intensely offensive like horse urine', 'Marked relief of all physical and mental symptoms while riding in a car or train'],
      mindEmotional: 'Unforgiving, holds deep vindictive grudges, anxious about disease.',
      modalitiesBetter: ['Riding in a vehicle/car/train', 'Mild even weather'],
      modalitiesWorse: ['Cold air & weather changes', 'Touch', 'After stool', 'Nighttime'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Mucocutaneous Outlets (Anus, Mouth, Urethra)', 'Urinary System', 'Skin & Warts'],
      differentialRemedies: ['Hepar sulfuris (splinter, chills)', 'Mercurius solubilis', 'Causticum', 'Thuja'],
      searchKeywords: ['nitric acid', 'splinter pain', 'anal fissure', 'horse urine', 'riding in car relieves', 'unforgiving', 'warts']
    },
    es: { commonName: 'Ácido nítrico' },
    fr: { commonName: 'Acide nitrique' },
    el: { commonName: 'Νιτρικό οξύ' },
    it: { commonName: 'Acido nitrico' },
    ru: { commonName: 'Азотная кислота / Нитрикум ацидум' }
  },
  {
    id: 'nux-vomica',
    latinName: 'Strychnos nux-vomica',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Brechnuss / Krähenaugen',
      origin: 'Getrocknete reife Samen der Brechnuss (Loganiaceae).',
      essence: 'Das große Manager- und Entgiftungsmittel für die moderne Zivilisation: Cholerisch, gereizt, ungeduldig; Überlastung durch Arbeit, Stress, Kaffee, Alkohol und Medikamente; erfolgloser Stuhldrang, morgendlicher Kater und extreme Kälteempfindlichkeit; Erwachen um 03:00 Uhr mit Gedanken an die Arbeit.',
      mainIndications: ['Kater nach Alkohol-, Kaffee- und Genussmittelübermaß', 'Magen-Darm-Krämpfe, Gastritis & Sodbrennen nach Stress', 'Obstipation mit vergeblichem, ständigem Stuhldrang', 'Schlaflosigkeit: Erwachen um 03:00 Uhr mit Arbeitsgedanken', 'Überempfindlichkeit gegen Lärm, Licht, Gerüche und Widerspruch'],
      keynotes: ['Ständiger, aber vergeblicher Drang zu Stuhl oder Harnlassen', 'Überempfindlich gegen alle Sinneseindrücke (Geräusche, Licht, Gerüche)', 'Erwacht pünktlich um 03:00 oder 04:00 Uhr, grübelt über Probleme, schläft morgens schwer ein und fühlt sich wie gerädert', 'Extreme Frostigkeit: schon das geringste Anheben der Bettdecke verursacht Frösteln'],
      mindEmotional: 'Cholerisch, herrschsüchtig, arbeitswütig, ungeduldig, rastet bei kleinsten Verzögerungen aus.',
      modalitiesBetter: ['Wärme & warmes Einhüllen', 'Abendruhe', 'Kurzer Mittagsschlaf (Powernap)'],
      modalitiesWorse: ['Kälte & Zugluft', 'Morgens beim Erwachen & um 03:00 Uhr', 'Genussmittel (Kaffee, Alkohol, Nikotin)', 'Geistige Überarbeitung'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Nach Alkohol-/Essensübermaß C30 am Abend oder morgens.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Zentral- & Vegetatives Nervensystem', 'Magen, Leber & Darm', 'Schlaf-Wach-Rhythmus'],
      differentialRemedies: ['Lycopodium', 'Sulphur', 'Arsenicum album', 'Bryonia'],
      searchKeywords: ['brechnuss', 'nux vomica', 'manager', 'kater', 'alkohol', 'kaffee', 'stress', 'stuhldrang', 'cholerisch', 'frostig', '03uhr']
    },
    en: {
      commonName: 'Poison Nut / Nux Vomica',
      origin: 'Dried ripe seeds of Strychnos nux-vomica (Loganiaceae).',
      essence: 'The supreme modern executive and detox polychrest: irritable, impatient, workaholic; toxicity from stress, coffee, alcohol, drugs; ineffectual urging for stool, morning hangover, chilly, waking at 3:00 AM thinking of work.',
      mainIndications: ['Hangover after alcohol, coffee, rich food, or medication', 'Gastric spasms, heartburn, dyspepsia & acid reflux from stress', 'Obstinate constipation with constant ineffectual urging to stool', 'Insomnia: waking at 3:00 AM with racing business thoughts', 'Extreme hypersensitivity to noise, light, odors, and opposition'],
      keynotes: ['Constant ineffectual urging for stool ("never done" sensation)', 'Extreme intolerance of external impressions (sound, light, odors)', 'Wakes punctually at 3:00 or 4:00 AM thinking of business, falls into heavy stupor at dawn', 'Exquisite chilliness: slightest lifting of bedcovers causes shivering'],
      mindEmotional: 'Fiery, irritable, aggressive, competitive workaholic, furious at slightest obstacle.',
      modalitiesBetter: ['Warmth & wrapping up', 'Evening rest', 'Short uninterrupted power nap'],
      modalitiesWorse: ['Cold drafts', 'Morning on waking & 3:00 AM', 'Stimulants (coffee, liquor, spices)', 'Mental overwork'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. After dietary or alcohol excess C30 at bedtime.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Cerebrospinal Axis & Autonomic Nerves', 'Digestive Tract, Liver & Bowels', 'Sleep Cycle'],
      differentialRemedies: ['Lycopodium', 'Sulphur', 'Arsenicum album', 'Bryonia'],
      searchKeywords: ['nux vomica', 'poison nut', 'hangover', 'executive', 'workaholic', 'coffee', 'ineffectual urging', 'chilly', '3am']
    },
    es: { commonName: 'Nuez vómica' },
    fr: { commonName: 'Noix vomique' },
    el: { commonName: 'Εμετική καρυδιά / Νουξ βόμικα' },
    it: { commonName: 'Noce vomica' },
    ru: { commonName: 'Рвотный орех / Нукс вомика / Чилибуха' }
  }
];

console.log('REMEDIES_PART6_MN defined with count:', REMEDIES_PART6_MN.length);
