import { RawRemedy } from './buildRemedyUtils';

export const REMEDIES_PART5_KL: RawRemedy[] = [
  {
    id: 'kalium-bichromicum',
    latinName: 'Kalium bichromicum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Kaliumdichromat',
      origin: 'Reines Kaliumdichromat (K2Cr2O7).',
      essence: 'Extrem zähe, fadenziehende, gelb-grüne Schleimabsonderungen, die sich wie lange Fäden ziehen lassen; punktförmige Schmerzen, die man mit der Fingerspitze abdecken kann, und tiefe, wie ausgestanzte Geschwüre.',
      mainIndications: ['Chronische eitrige Sinusitis mit Borken & Druck an der Nasenwurzel', 'Punktförmige Schmerzen, die plötzlich den Ort wechseln', 'Fadenziehender Husten mit Schleimpfröpfen (Pseudokrupp)', 'Magengeschwüre wie ausgestanzt mit brennendem Schmerz'],
      keynotes: ['Schleimabsonderungen lassen sich meterlang in elastischen Fäden ziehen', 'Schmerzpunkte sind winzig klein und lassen sich mit einer Fingerspitze bedecken', 'Harte, elastische Borken („Nasensteine“) in der Nase mit Blutungen beim Lösen', 'Morgendliche Verschlimmerung zwischen 02:00 und 03:00 Uhr'],
      mindEmotional: 'Pflichtbewusst, ordnungsliebend, engstirnig, pedantisch.',
      modalitiesBetter: ['Wärme & warmes Einhüllen', 'Im Sommer'],
      modalitiesWorse: ['Kälte & feuchtes Wetter', 'Biergenuss', 'Zwischen 02:00 und 03:00 Uhr morgens'],
      potenciesAndDosage: 'D6 bis C30. 2-3x täglich 5 Globuli.',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Schleimhäute (Nasennebenhöhlen, Pharynx, Magen)', 'Haut & Schleimhautgeschwüre', 'Gelenke'],
      differentialRemedies: ['Hydrastis', 'Pulsatilla', 'Mercurius', 'Silicea'],
      searchKeywords: ['kalium bichromicum', 'dichromat', 'fadenziehend', 'sinusitis', 'borken', 'punktförmiger schmerz', 'ausgestanzt']
    },
    en: {
      commonName: 'Potassium Bichromate',
      origin: 'Pure potassium dichromate.',
      essence: 'Extremely tough, stringy, ropy, viscous discharges that can be drawn into long elastic threads; circumscribed point-like pains that can be covered with the tip of a finger; round punched-out ulcers.',
      mainIndications: ['Chronic purulent sinusitis with tough plugs & root-of-nose ache', 'Pains in small spots that shift rapidly from joint to joint', 'Spasmodic cough with stringy sticky sputum (croup)', 'Punched-out round peptic ulcers with burning pain'],
      keynotes: ['Discharges are stringy, ropy, tough, and elastic', 'Pains confined to small circumscribed spots coverable by a fingertip', 'Hard elastic clinkers and plugs in nose, bleeding when dislodged', 'Aggravation at 2:00 to 3:00 AM'],
      mindEmotional: 'Punctual, orderly, rigid, narrow-minded, pedantic.',
      modalitiesBetter: ['Warmth & warm wraps', 'Summer weather'],
      modalitiesWorse: ['Cold damp air', 'Drinking beer', '2:00 to 3:00 AM'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 2-3 times daily 5 pellets.',
      defaultTagesdosis: '2-3 times daily 5 pellets',
      sphereOfAction: ['Mucous Membranes (Sinuses, Pharynx, Gastric)', 'Skin & Round Ulcers', 'Fibrous Tissues & Joints'],
      differentialRemedies: ['Hydrastis', 'Pulsatilla', 'Mercurius', 'Silicea'],
      searchKeywords: ['potassium bichromate', 'kali bich', 'stringy discharge', 'sinusitis', 'punched out ulcer', 'point pains']
    },
    es: { commonName: 'Bicromato de potasio' },
    fr: { commonName: 'Bichromate de potassium' },
    el: { commonName: 'Διχρωμικό κάλιο' },
    it: { commonName: 'Bicromato di potassio' },
    ru: { commonName: 'Калия бихромат / Двухромовокислый калий' }
  },
  {
    id: 'kalium-carbonicum',
    latinName: 'Kalium carbonicum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Kaliumcarbonat / Pottasche',
      origin: 'Reines Kaliumcarbonat (K2CO3).',
      essence: 'Das große Mittel für Herz-, Lungen- und Rückenschwäche: Sackartige Schwellungen am oberen inneren Augenlid; stechende Schmerzen, die zwingen, sich mit auf die Knie gestützten Ellbogen nach vorn zu beugen; Panik beim Erwachen zwischen 02:00 und 04:00 Uhr.',
      mainIndications: ['Asthma bronchiale & chronische Bronchitis mit Erwachen um 03:00 Uhr', 'Sackartige Ödeme der oberen Augenlider', 'Chronische Lumbalgie & Rückenschwäche („Kreuz lahmt")', 'Herzinsuffizienz mit Ödemneigung'],
      keynotes: ['Sackartige Ödemtaschen zwischen Oberlid und Augenbraue', 'Stechende Schmerzen unabhängig von der Bewegung', 'Muss sich im Bett aufsetzen und nach vorn beugen, um atmen zu können', 'Extreme Schreckhaftigkeit bei unerwarteter Berührung (an den Fußsohlen)'],
      mindEmotional: 'Pflichtbewusst, überkorrekt, starr, mag kein Alleinsein, fürchtet die Dunkelheit.',
      modalitiesBetter: ['Aufrechtes Sitzen & Vornüberbeugen mit Ellbogen auf Knien', 'Wärme'],
      modalitiesWorse: ['Kälte & Zugluft', 'Zwischen 02:00 und 04:00 Uhr morgens', 'Liegen auf der schmerzhaften Seite'],
      potenciesAndDosage: 'D6 bis C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Lunge & Bronchien', 'Herz & Kreislauf', 'Lendenwirbelsäule & Nieren'],
      differentialRemedies: ['Bryonia', 'Natrium sulfuricum', 'Arsenicum album', 'Phosphorus'],
      searchKeywords: ['kalium carbonicum', 'pottasche', 'oberlidödem', 'asthma', 'vornüberbeugen', 'rückenschmerz', 'erschrecken']
    },
    en: {
      commonName: 'Potassium Carbonate',
      origin: 'Pure potassium carbonate (potash).',
      essence: 'The great remedy for cardiac, pulmonary, and lumbar back exhaustion: bag-like puffy swellings of upper inner eyelids; sharp stitching pains; sitting up leaning forward with elbows on knees; waking in terror at 2:00 to 4:00 AM.',
      mainIndications: ['Bronchial asthma & chronic cough waking patient at 3:00 AM', 'Bag-like swelling of upper eyelids between lid and brow', 'Chronic low back weakness and sacral pain ("back gives out")', 'Congestive heart failure with dependent edema'],
      keynotes: ['Bag-like puffiness of upper inner angle of upper eyelids', 'Sharp stitching pains independent of motion', 'Asthma forces patient to sit up leaning forward with elbows on knees', 'Startles violently from lightest touch especially on soles of feet'],
      mindEmotional: 'Rigid, duty-bound, moralistic, fears solitude, fears the dark.',
      modalitiesBetter: ['Sitting up & leaning forward with elbows on knees', 'Warmth'],
      modalitiesWorse: ['Cold drafts', '2:00 to 4:00 AM', 'Lying on painful side'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Lungs & Bronchi', 'Heart & Circulation', 'Lumbar Spine & Kidneys'],
      differentialRemedies: ['Bryonia', 'Natrium sulfuricum', 'Arsenicum album', 'Phosphorus'],
      searchKeywords: ['potassium carbonate', 'kali carb', 'upper eyelid swelling', 'asthma 3am', 'leaning forward', 'backache']
    },
    es: { commonName: 'Carbonato de potasio' },
    fr: { commonName: 'Carbonate de potassium' },
    el: { commonName: 'Ανθρακικό κάλιο' },
    it: { commonName: 'Carbonato di potassio' },
    ru: { commonName: 'Калия карбонат / Поташ' }
  },
  {
    id: 'kalium-phosphoricum',
    latinName: 'Kalium phosphoricum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Kaliumphosphat',
      origin: 'Reines Kaliumhydrogenphosphat (K2HPO4).',
      essence: 'Das biochemische und homöopathische Nervennährsalz bei totaler geistiger und körperlicher Erschöpfung (Burnout), Überarbeitung, Prüfungsstress, Nervosität und Konzentrationsschwäche.',
      mainIndications: ['Burnout-Syndrom, geistige Überarbeitung & chronische Erschöpfung', 'Prüfungsstress & Nervosität bei Studenten und Schülern', 'Gedächtnisschwäche & Brain-Fog nach akuten Krankheiten', 'Nervöse Schlaflosigkeit mit Gedankenkreisen'],
      keynotes: ['Gefühl völliger geistiger Leere und Erschöpfung bei geringster Denkanstrengung', 'Schreckhaft, nervös, ängstlich beim geringsten Geräusch', 'Aasiger Mundgeruch und dunkler übelriechender Urin'],
      mindEmotional: 'Reizbare Schwäche, Angst vor der Zukunft, verzagend, weint vor Erschöpfung.',
      modalitiesBetter: ['Wärme', 'Ruhe', 'Essen'],
      modalitiesWorse: ['Geistige Anstrengung', 'Kälte', 'Alleinsein'],
      potenciesAndDosage: 'D6, D12, C30 (Schüßler-Salz Nr. 5). 2-3x täglich 5 Globuli.',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Nervensystem & Gehirn', 'Psyche & Emotionen', 'Muskulatur'],
      differentialRemedies: ['Phosphoricum acidum', 'Gelsemium', 'Anacardium', 'Picricum acidum'],
      searchKeywords: ['kalium phosphoricum', 'nervensalz', 'burnout', 'erschöpfung', 'überarbeitung', 'gedächtnis', 'gehirnschwäche']
    },
    en: {
      commonName: 'Phosphate of Potassium',
      origin: 'Pure potassium phosphate.',
      essence: 'The supreme brain and nerve nutrient for profound mental and physical burnout, brain-fag from overwork, examination fatigue, nervous prostration, and inability to concentrate.',
      mainIndications: ['Burnout syndrome, mental overwork & neurasthenia', 'Examination exhaustion & study fatigue in students', 'Memory loss & brain fog following acute illness', 'Nervous insomnia with racing exhausted thoughts'],
      keynotes: ['Profound mental exhaustion from least intellectual effort', 'Hypersensitive, jumpy, startled by lightest rustling sound', 'Offensive breath and dark putrid-smelling urine'],
      mindEmotional: 'Irritable weakness, dreads society, despairs of recovery, weeps from fatigue.',
      modalitiesBetter: ['Warmth', 'Rest', 'Nourishing food'],
      modalitiesWorse: ['Mental exertion & studying', 'Cold air', 'Being alone'],
      potenciesAndDosage: 'D6, D12, C30 / 6X, 12X. 2-3 times daily 5 pellets.',
      defaultTagesdosis: '2-3 times daily 5 pellets',
      sphereOfAction: ['Cerebrospinal Axis & Nerves', 'Mental Sphere', 'Muscles'],
      differentialRemedies: ['Phosphoricum acidum', 'Gelsemium', 'Anacardium', 'Picricum acidum'],
      searchKeywords: ['potassium phosphate', 'kali phos', 'burnout', 'brain fag', 'nerve exhaustion', 'memory', 'fatigue']
    },
    es: { commonName: 'Fosfato de potasio' },
    fr: { commonName: 'Phosphate de potassium' },
    el: { commonName: 'Φωσφορικό κάλιο' },
    it: { commonName: 'Fosfato di potassio' },
    ru: { commonName: 'Фосфорнокислый калий / Калия фосфат' }
  },
  {
    id: 'lachesis-muta',
    latinName: 'Lachesis muta',
    categoryKey: 'animal',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Buschmeister-Schlange',
      origin: 'Frisches Gift der südamerikanischen Buschmeisterschlange Lachesis muta (Viperidae).',
      essence: 'Das große Schlangengiftmittel: Linksseitigkeit, ausgeprägte Eifersucht, ungebremste Redseligkeit (Loquazität), extreme Engeintoleranz (verträgt keinen engen Kragen/Gürtel) und Verschlimmerung nach dem Schlaf („schläft sich in die Verschlimmerung hinein“); Linderung durch das Auftreten einer Blutung oder Ausscheidung.',
      mainIndications: ['Klimakterische Beschwerden mit Hitzewallungen & Engegefühl', 'Akute linksseitige Tonsillitis mit bläulich-roter Verfärbung', 'Schwere Eifersucht, Misstrauen & unaufhörlicher Redefluss', 'Purpurfarbene Hautinfektionen, Phlegmonen & Thrombophlebitis'],
      keynotes: ['Verträgt absolut keine beengende Kleidung am Hals oder Bund', 'Beschwerden beginnen links und wandern nach rechts', 'Verschlimmerung sofort nach dem Schlaf oder beim Aufwachen', 'Dramatische Besserung aller Symptome, sobald eine Blutung (z.B. Menses) einsetzt'],
      mindEmotional: 'Extrem eifersüchtig, misstrauisch, sprunghaft redselig, Sarkasmus.',
      modalitiesBetter: ['Einsetzen von Blutungen/Absonderungen', 'Frische kühle Luft', 'Kälte'],
      modalitiesWorse: ['Nach dem Schlaf', 'Enge Kleidung am Hals', 'Wärme & heißes Baden', 'Unterdrückte Ausscheidungen'],
      potenciesAndDosage: 'C30 bis C200. Bei klimakterischen Hitzewallungen 1x wöchentlich C30.',
      defaultTagesdosis: '1 Gabe à 3–5 Globuli',
      sphereOfAction: ['Blut & Blutgefäße (Purpura, Zyanose)', 'Zentralnervensystem & Psyche', 'Kehle & Ovarien (links)'],
      differentialRemedies: ['Sepia (Klimakterium)', 'Hyoscyamus (Eifersucht)', 'Crotalus horridus', 'Naja'],
      searchKeywords: ['buschmeister', 'lachesis', 'schlange', 'eifersucht', 'hitzewallung', 'engegefühl', 'kragen', 'linksseitig', 'schlaf']
    },
    en: {
      commonName: 'Bushmaster Snake Venom',
      origin: 'Fresh venom of the South American bushmaster viper Lachesis muta (Viperidae).',
      essence: 'The supreme snake venom polychrest: left-sidedness, intense jealousy, compulsive loquacity, extreme intolerance of tight collars/waistbands, and severe aggravation after sleep ("sleeps into aggravation"); prompt relief from onset of flow/discharge.',
      mainIndications: ['Menopausal hot flushes with suffocation & tightness', 'Left-sided purplish-cyanotic tonsillitis and pharyngitis', 'Pathological jealousy, suspicion, and incessant rapid talking', 'Purplish cellulitis, boils, and septic thrombophlebitis'],
      keynotes: ['Cannot bear slightest constriction around neck or waist', 'Left-sided or moves from left to right side', 'Symptoms violently aggravated after sleep or upon waking', 'Dramatic relief of all complaints upon appearance of a bodily discharge'],
      mindEmotional: 'Intensely jealous, suspicious of betrayal, erratic loquacity, sarcastic.',
      modalitiesBetter: ['Appearance of discharges & menses', 'Cool open air', 'Cold bathing'],
      modalitiesWorse: ['After sleep', 'Tight clothing around neck', 'Heat & hot baths', 'Suppressed discharges'],
      potenciesAndDosage: 'C30 to C200 / 30C, 200C. In menopause C30 once weekly.',
      defaultTagesdosis: '1 dose of 3–5 pellets',
      sphereOfAction: ['Blood & Vascular Tone (Cyanosis, Purpura)', 'Cerebral & Emotional Axis', 'Throat & Left Ovary'],
      differentialRemedies: ['Sepia (menopause)', 'Hyoscyamus (jealousy)', 'Crotalus horridus', 'Naja'],
      searchKeywords: ['bushmaster', 'lachesis', 'snake venom', 'jealousy', 'hot flushes', 'tight collar', 'left sided', 'worse after sleep']
    },
    es: { commonName: 'Láquesis / Veneno de cascabel muda' },
    fr: { commonName: 'Venin de serpent Lachesis' },
    el: { commonName: 'Λάχεσις' },
    it: { commonName: 'Lachesis' },
    ru: { commonName: 'Лахезис / Яд змеи сурукуку' }
  },
  {
    id: 'ledum-palustre',
    latinName: 'Rhododendron tomentosum / Ledum palustre',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Sumpfporst',
      origin: 'Getrocknete blühende Zweige des Sumpfporsts (Ericaceae).',
      essence: 'Das Hauptmittel für Stichwunden (Nägel, Nadeln, Insektenstiche, Zeckenbisse): Die Wunde fühlt sich eiskalt an, wird aber paradoxerweise durch eiskalte Umschläge gebessert; Gichtschmerzen steigen von den Füßen nach oben.',
      mainIndications: ['Stichwunden durch Nägel, Dornen, Nadeln & Spritzen', 'Insektenstiche & Zeckenbisse mit bläulicher Schwellung', 'Schwarzes Auge (Hämatom am Auge nach Faustschlag)', 'Aufsteigende Gicht & Rheuma der Zehen- und Fußgelenke'],
      keynotes: ['Verletzte Stelle ist eiskalt bei Berührung, verlangt aber eiskaltes Wasser', 'Aufsteigende Schmerzen: Gicht beginnt in den Großzehen und wandert aufwärts', 'Bläulich-marmorierte, kalte Hautverfärbung um die Einstichstelle'],
      mindEmotional: 'Mürrisch, ungesellig, meidet Gesellschaft.',
      modalitiesBetter: ['Eiskalte Umschläge & Eisbäder', 'Ruhiges Liegen'],
      modalitiesWorse: ['Bettwärme & warme Umschläge', 'Nachts', 'Bewegung'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Stichen und Bissen C30 sofort 3–5 Globuli.',
      defaultTagesdosis: '2–3 Gaben à 3–5 Globuli',
      sphereOfAction: ['Kapillaren & Haut (Stichwunden)', 'Gelenke & Sehnen (Gicht)', 'Augenregion (Monokelhämatom)'],
      differentialRemedies: ['Hypericum (Nervenquetschung)', 'Arnica (stumpfes Trauma)', 'Apis mellifica (heißer Stich)'],
      searchKeywords: ['sumpfporst', 'ledum', 'stichwunde', 'insektenstich', 'zeckenbiss', 'blaues auge', 'eiskalt', 'gicht']
    },
    en: {
      commonName: 'Marsh Tea / Wild Rosemary',
      origin: 'Dried leafy twigs of Ledum palustre (Ericaceae).',
      essence: 'The supreme remedy for puncture wounds (nails, needles, insect stings, tick bites): wounded part feels icy cold to touch yet is relieved paradoxically by ice-cold water; gout ascends from feet upward.',
      mainIndications: ['Puncture wounds from nails, splinters, thorns, and needles', 'Insect stings & tick bites with purplish cold swelling', 'Black eye (ecchymosis of orbits after blunt blow)', 'Ascending gout & rheumatism starting in big toes'],
      keynotes: ['Affected part feels icy cold to touch yet craves ice-cold water compresses', 'Ascending direction of pains: gout starts in feet and travels upward', 'Purplish mottled discoloration around puncture wound'],
      mindEmotional: 'Morose, irritable, avoids company, discontented.',
      modalitiesBetter: ['Ice-cold water compresses & ice baths', 'Lying quiet'],
      modalitiesWorse: ['Warmth of bed & hot covers', 'Nighttime', 'Motion'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In puncture wounds C30 immediately.',
      defaultTagesdosis: '2–3 doses of 3–5 pellets',
      sphereOfAction: ['Skin Capillaries (Punctures)', 'Fibrous Tissues & Small Joints', 'Periorbital Tissues'],
      differentialRemedies: ['Hypericum (crushed nerve)', 'Arnica (blunt contusion)', 'Apis mellifica (hot sting)'],
      searchKeywords: ['marsh tea', 'ledum', 'puncture wound', 'insect sting', 'tick bite', 'black eye', 'cold compresses', 'gout']
    },
    es: { commonName: 'Ledo / Romero silvestre' },
    fr: { commonName: 'Lédon des marais' },
    el: { commonName: 'Λήδο' },
    it: { commonName: 'Rosmarino selvatico' },
    ru: { commonName: 'Багульник болотный / Ледум' }
  },
  {
    id: 'luffa-operculata',
    latinName: 'Luffa operculata',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Schwammgurke / Luffa',
      origin: 'Getrocknete Früchte von Luffa operculata (Cucurbitaceae).',
      essence: 'Das Hauptmittel für verstopfte Nasennebenhöhlen, Heuschnupfen und trockene Borken in der Nase; befreit die Nasenatmung bei Sinusitis und chronischem Stockschnupfen.',
      mainIndications: ['Akute & chronische Sinusitis (Stirnhöhlen-, Kieferhöhlenentzündung)', 'Saisonaler Heuschnupfen mit Stockschnupfen', 'Borkige trockene Nasenschleimhaut (Rhinitis sicca)'],
      keynotes: ['Nase ist völlig verstopft mit brennendem Trockenheitsgefühl', 'Zähe, gelbliche Borken in der Nase, die die Atmung behindern', 'Kopfschmerz über den Augen bei Sinusitis'],
      mindEmotional: 'Erschöpft und gereizt durch die behinderte Nasenatmung.',
      modalitiesBetter: ['Im Freien', 'Kühle Luft'],
      modalitiesWorse: ['Trockene warme Zimmerluft', 'Pollenflug'],
      potenciesAndDosage: 'D4 bis D12. 3x täglich 5 Tropfen oder Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Nasenschleimhaut & Nasennebenhöhlen'],
      differentialRemedies: ['Galphimia glauca', 'Kalium bichromicum', 'Hydrastis', 'Euphrasia'],
      searchKeywords: ['luffa', 'schwammgurke', 'sinusitis', 'stockschnupfen', 'heuschnupfen', 'nasenverstopfung', 'borken']
    },
    en: {
      commonName: 'Sponge Cucumber / Luffa',
      origin: 'Dried fruits of Luffa operculata (Cucurbitaceae).',
      essence: 'The leading remedy for blocked nasal sinuses, allergic rhinitis, and dry crusts in the nasal cavity; clears airway in sinusitis and chronic stuffy head colds.',
      mainIndications: ['Acute & chronic sinusitis (frontal and maxillary sinuses)', 'Seasonal hay fever with severe nasal blockage', 'Dry crusty nasal mucosa (rhinitis sicca)'],
      keynotes: ['Complete nasal obstruction with burning dryness', 'Tenacious crusts adhering tightly to turbinates', 'Frontal congestive headache over root of nose'],
      mindEmotional: 'Weary and irritable from impaired nasal breathing.',
      modalitiesBetter: ['Cool fresh outdoor air'],
      modalitiesWorse: ['Dry overheated rooms', 'Peak pollen exposure'],
      potenciesAndDosage: 'D4 to D12 / 4X to 12X. 3 times daily 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Nasal Mucosa & Paranasal Sinuses'],
      differentialRemedies: ['Galphimia glauca', 'Kalium bichromicum', 'Hydrastis', 'Euphrasia'],
      searchKeywords: ['luffa', 'sponge cucumber', 'sinusitis', 'stuffy nose', 'hay fever', 'rhinitis sicca']
    },
    es: { commonName: 'Lufa / Esponjilla' },
    fr: { commonName: 'Luffa operculata' },
    el: { commonName: 'Λούφα' },
    it: { commonName: 'Luffa' },
    ru: { commonName: 'Люффа прикрепленная' }
  },
  {
    id: 'lycopodium-clavatum',
    latinName: 'Lycopodium clavatum',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Bärlapp / Hexenmehl',
      origin: 'Sporen des Bärlapps (Lycopodiaceae).',
      essence: 'Das große Mittel für Leber, Verdauung und mangelndes Selbstvertrauen: Rechtsseitigkeit (oder von rechts nach links wandernd), gewaltige Blähungen (schon nach wenigen Bissen satt und aufgebläht), Verlangen nach warmen Speisen und Getränken; Verschlimmerung zwischen 16:00 und 20:00 Uhr.',
      mainIndications: ['Meteorismus, Blähbauch & chronische Verdauungsschwäche', 'Leber- und Gallestörungen mit Völlegefühl', 'Rechtsseitige Nierensteinkoliken & roter Ziegelsand im Urin', 'Versagensangst trotz exzellenter Leistung'],
      keynotes: ['Schon nach wenigen Bissen ist der Magen zum Bersten voll', 'Blähungen treiben den Hosenbund auf, muss Gürtel lockern', 'Heißhunger auf warme Speisen und Getränke sowie Süßigkeiten', 'Rechtsseitige Beschwerden oder wandern von rechts nach links', 'Verschlimmerungszeit von 16:00 bis 20:00 Uhr'],
      mindEmotional: 'Minderwertigkeitskomplexe mit kompensatorischem Dünkel; feige vor Vorgesetzten, tyrannisch zu Hause.',
      modalitiesBetter: ['Warme Getränke & warme Speisen', 'Lockerung der Kleidung', 'Frische kühle Luft'],
      modalitiesWorse: ['Zwischen 16:00 und 20:00 Uhr', 'Enge Kleidung am Bauch', 'Kalte Speisen', 'Bohnen & Kohl'],
      potenciesAndDosage: 'D6 bis C200. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Leber & Gallenblase', 'Magen-Darm-Trakt (Blähungen)', 'Urogenitaltrakt (Nieren)', 'Psyche'],
      differentialRemedies: ['Nux vomica', 'Carbo vegetabilis', 'Chelidonium', 'Sulphur'],
      searchKeywords: ['bärlapp', 'lycopodium', 'blähungen', 'blähbauch', 'leber', '16bis20uhr', 'rechtsseitig', 'versagensangst', 'warme getränke']
    },
    en: {
      commonName: 'Club Moss',
      origin: 'Sporen of Lycopodium clavatum (Lycopodiaceae).',
      essence: 'The supreme gastrointestinal, hepatic, and confidence polychrest: right-sidedness (or moving right to left), enormous flatulent distension (full after a few mouthfuls), craving for hot food and drinks; strict 4:00 to 8:00 PM aggravation.',
      mainIndications: ['Flatulent dyspepsia, abdominal bloating & gas', 'Hepatic & biliary sluggishness with postprandial distress', 'Right-sided renal colic with red sand in urine', 'Anticipatory performance anxiety masked by intellectual competence'],
      keynotes: ['Eating a few mouthfuls produces unbearable abdominal distension', 'Bloating forces loosening of waistband and tight clothes', 'Craves warm food, hot drinks, and sweets', 'Right-sided symptoms or moves from right to left', 'Characteristic aggravation from 4:00 to 8:00 PM'],
      mindEmotional: 'Inner lack of self-confidence; timid before superiors, irritable and dictatorial at home.',
      modalitiesBetter: ['Hot drinks & warm food', 'Loosening clothes', 'Cool open breeze'],
      modalitiesWorse: ['4:00 to 8:00 PM', 'Tight waistbands', 'Cold food', 'Cabbage and beans'],
      potenciesAndDosage: 'D6 to C200 / 6C, 30C, 200C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Liver & Biliary System', 'Gastrointestinal Tract (Gas)', 'Kidneys & Urinary Tract', 'Intellectual Sphere'],
      differentialRemedies: ['Nux vomica', 'Carbo vegetabilis', 'Chelidonium', 'Sulphur'],
      searchKeywords: ['club moss', 'lycopodium', 'bloating', 'gas', 'liver', '4 to 8 pm', 'right sided', 'hot drinks', 'anticipation']
    },
    es: { commonName: 'Licopodio / Licopodio clavado' },
    fr: { commonName: 'Lycopode en massue' },
    el: { commonName: 'Λυκοπόδιο' },
    it: { commonName: 'Licopodio' },
    ru: { commonName: 'Плаун булавовидный / Ликоподиум' }
  }
];

console.log('REMEDIES_PART5_KL defined with count:', REMEDIES_PART5_KL.length);
