import { RawRemedy } from './buildRemedyUtils';

export const REMEDIES_PART9_TUVWXYZ: RawRemedy[] = [
  {
    id: 'tabacum',
    latinName: 'Nicotiana tabacum',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Echter Tabak',
      origin: 'Frische Blätter des Tabaks vor der Blüte (Solanaceae).',
      essence: 'Extremste Übelkeit mit eiskaltem Schweiß auf der Stirn, Todesübelkeit und Schwindel; Patient muss den Bauch entblößen und verlangt frische kalte Luft; Seekrankheit und Kollapszustände.',
      mainIndications: ['Schwere Reisekrankheit (Seekrankheit, Kinetose) mit kaltem Schweiß', 'Schwangerschaftserbrechen mit Kollapsneigung', 'Morbus Menière mit Drehschwindel und Erbrechen'],
      keynotes: ['Eiseskalter, klebriger Schweiß besonders auf Stirn und Gesicht', 'Übelkeit geht einher mit dem Zwang, den Bauch vollständig zu entblößen', 'Dramatische Besserung durch das Einatmen von frischer, eiskalter Seeluft und Schließen der Augen'],
      mindEmotional: 'Todesangst bei Übelkeit, apathisch vor Schwindel.',
      modalitiesBetter: ['Frische, kühle Luft & Seeluft', 'Entblößen des Bauches', 'Augen schließen'],
      modalitiesWorse: ['Geringste Bewegung & Fahren im Schiff/Auto', 'Wärme & stickige Räume', 'Tabakrauch'],
      potenciesAndDosage: 'D6 bis C30. Bei akuter Reisekrankheit D6 alle 15–30 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Gleichgewichtsorgan & Brechzentrum', 'Vagusnerv & Kreislauf', 'Magen-Darm-Trakt'],
      differentialRemedies: ['Cocculus (Reisekrankheit durch Schlafmangel)', 'Petroleum', 'Ipecacuanha', 'Veratrum album'],
      searchKeywords: ['tabak', 'tabacum', 'seekrankheit', 'reisekrankheit', 'kalter schweiß', 'todesübelkeit', 'bauch entblößen', 'schwindel']
    },
    en: {
      commonName: 'Tobacco',
      origin: 'Fresh leaves of Nicotiana tabacum (Solanaceae).',
      essence: 'Deadly nausea with icy cold sweat on forehead, sinking prostration, and vertigo; patient must uncover the abdomen and craves fresh cold breeze; seasickness and collapse.',
      mainIndications: ['Severe seasickness & motion sickness with cold sweat', 'Hyperemesis gravidarum with fainting collapse', 'Ménière’s vertigo with projectile vomiting'],
      keynotes: ['Icy cold, clammy perspiration especially bathing forehead and face', 'Nausea forces patient to uncover abdomen completely to cold air', 'Dramatic relief from inhaling fresh, brisk, cold outdoor/sea air and closing eyes'],
      mindEmotional: 'Deathly terror during vomiting, apathetic from vertigo.',
      modalitiesBetter: ['Fresh cold breeze & sea air', 'Uncovering abdomen', 'Closing eyes'],
      modalitiesWorse: ['Slightest motion & riding on boats/cars', 'Warm stuffy air', 'Tobacco smoke'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. In motion sickness D6 every 15–30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Vestibular Apparatus & Vomiting Reflex', 'Vagus Nerve & Vasomotor System', 'Gastric Mucosa'],
      differentialRemedies: ['Cocculus (motion sickness from sleeplessness)', 'Petroleum', 'Ipecacuanha', 'Veratrum album'],
      searchKeywords: ['tobacco', 'tabacum', 'seasickness', 'motion sickness', 'cold sweat', 'deathly nausea', 'uncover abdomen']
    },
    es: { commonName: 'Tabaco' },
    fr: { commonName: 'Tabac' },
    el: { commonName: 'Καπνός' },
    it: { commonName: 'Tabacco' },
    ru: { commonName: 'Табак настоящий' }
  },
  {
    id: 'thuja-occidentalis',
    latinName: 'Thuja occidentalis',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Abendländischer Lebensbaum',
      origin: 'Frische beblätterte Zweige des Lebensbaums (Cupressaceae).',
      essence: 'Das Hauptmittel für Sykose, Warzen und Impffolgen: Blumenkohlartige, feuchte Feigwarzen und Warzen; Wahnidee, die Glieder bestünden aus Glas oder etwas Lebendiges bewege sich im Bauch; chronischer Katarrh nach Impfung.',
      mainIndications: ['Warzen aller Art (Dornwarzen, Feigwarzen, weiche Warzen)', 'Beschwerden nach Schutzimpfungen (Impfschäden/Post-Vaccination-Syndrom)', 'Chronische Polyposis (Nasenpolypen, Darmpolypen)', 'Fettige, glänzende Gesichtshaut & brüchige, gerillte Nägel'],
      keynotes: ['Warzen sind gestielt, blumenkohlartig, weich und bluten leicht', 'Wahnidee: Körper oder Beine seien aus Glas und würden leicht zerbrechen', 'Wahnidee: Etwas Lebendiges bewege sich im Abdomen', 'Schweiß nur an unbedeckten Körperteilen, riecht süßlich nach gekochtem Lauch'],
      mindEmotional: 'Fixe Ideen, fühlt sich innerlich beschmutzt, geringes Selbstwertgefühl.',
      modalitiesBetter: ['Trockenes warmes Wetter', 'Fortgesetzte Bewegung'],
      modalitiesWorse: ['Nasskaltes Wetter & Feuchtigkeit', 'Nach Impfungen', 'Um 03:00 und 15:00 Uhr', 'Tee- und Kaffeegenuss'],
      potenciesAndDosage: 'D6 bis C200. Bei Warzen C30 2x wöchentlich.',
      defaultTagesdosis: '1-2x wöchentlich 5 Globuli',
      sphereOfAction: ['Haut & Warzen (sykotisches Miasma)', 'Urogenitaltrakt & Schleimhäute', 'Immunsystem (Impffolgen)'],
      differentialRemedies: ['Silicea (Impffolgen)', 'Nitricum acidum (spitze Warzen)', 'Causticum', 'Staphisagria'],
      searchKeywords: ['lebensbaum', 'thuja', 'warzen', 'feigwarzen', 'impffolgen', 'impfschaden', 'beine aus glas', 'nasenpolypen', 'sykose']
    },
    en: {
      commonName: 'Arbor Vitae / Northern White Cedar',
      origin: 'Fresh leafy twigs of Thuja occidentalis (Cupressaceae).',
      essence: 'The supreme sycotic, condylomata, and post-vaccinial polychrest: cauliflower-like, moist, bleeding warts and excrescences; fixed delusions that limbs are made of fragile glass or something alive is moving in abdomen; ailments from vaccination.',
      mainIndications: ['Warts of all types (verrucae, condylomata, soft pedigree warts)', 'Ailments from vaccination (post-vaccinial syndrome, vaccinosis)', 'Chronic mucous polypi (nasal, vocal cord, rectal)', 'Greasy oily facial skin & ridged, crumbling nails'],
      keynotes: ['Warts are pedunculated, cauliflower-like, moist, bleeding easily', 'Fixed delusion: limbs are made of brittle glass and will break', 'Fixed delusion: sensation of something alive bounding in abdomen', 'Sweat occurs only on uncovered parts; smells sweetish like boiled leeks'],
      mindEmotional: 'Fixed obsessive ideas, feels internally tainted, fragile self-esteem.',
      modalitiesBetter: ['Warm dry weather', 'Continuous motion'],
      modalitiesWorse: ['Cold damp rainy weather', 'After vaccination', '3:00 AM and 3:00 PM', 'Tea and onions'],
      potenciesAndDosage: 'D6 to C200 / 6C, 30C, 200C. In warts C30 twice weekly.',
      defaultTagesdosis: '1-2 times weekly 5 pellets',
      sphereOfAction: ['Skin & Warty Excrescences (Sycotic Miasm)', 'Genitourinary Mucosa & Polypi', 'Immune System (Post-Vaccinal)'],
      differentialRemedies: ['Silicea (vaccinosis)', 'Nitricum acidum (jagged bleeding warts)', 'Causticum', 'Staphisagria'],
      searchKeywords: ['arbor vitae', 'thuja', 'warts', 'condyloma', 'vaccinosis', 'post vaccination', 'glass limbs', 'nasal polyp', 'sycotic']
    },
    es: { commonName: 'Tuya / Árbol de la vida' },
    fr: { commonName: 'Thuya d’Occident / Arbre de vie' },
    el: { commonName: 'Θούγια' },
    it: { commonName: 'Tuia / Albero della vita' },
    ru: { commonName: 'Туя западная / Дерево жизни' }
  },
  {
    id: 'tuberculinum-bovinum',
    latinName: 'Tuberculinum bovinum',
    categoryKey: 'nosode',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Tuberkulose-Nosode',
      origin: 'Nosode aus tuberkulösem Gewebe (Mycobacterium bovis / tuberculosis).',
      essence: 'Unstillbare Reiselust (Cosmopolitan), ständiges Verlangen nach Veränderung; ständige Infektanfälligkeit der Atemwege („holt sich bei jedem Luftzug eine Erkältung“); Abmagerung trotz Heißhunger und Verlangen nach frischer Bergluft.',
      mainIndications: ['Chronische Infektanfälligkeit der Atemwege bei Kindern', 'Rezidivierende Bronchitis, Pneumonie & chronischer Husten', 'Verhaltensauffälligkeiten bei Kindern (Zerstörungswut, Trotzanfälle)', 'Chronische Müdigkeit mit ständigem Bedürfnis zu reisen'],
      keynotes: ['Patient fängt sich bei jedem geringsten Luftzug sofort eine Erkältung ein', 'Unstillbare Reiselust: will ständig den Ort, die Arbeit oder die Möbel wechseln', 'Magert rapide ab trotz gewaltigem Appetit', 'Schlaf: schläft mit dem Kopf tief in die Kissen vergraben (Knie-Ellbogen-Lage)'],
      mindEmotional: 'Unruhig, reizbar, unberechenbar, zerstörungswütig bei Kindern, verlangt ständig Neues.',
      modalitiesBetter: ['Frische, kühle Bergluft & Wind', 'Fortgesetztes Reisen & Bewegung'],
      modalitiesWorse: ['Vor Gewitter & Wetterumschwung', 'Feuchtkalte Luft', 'In geschlossenen warmen Räumen'],
      potenciesAndDosage: 'C30, C200, 1M. 1x monatlich 5 Globuli.',
      defaultTagesdosis: '1 Gabe pro Monat / Intervall',
      sphereOfAction: ['Atmungsorgane & Lunge', 'Lymphatisches System', 'Psyche & Konstitution'],
      differentialRemedies: ['Phosphorus', 'Calcarea phosphorica', 'Bacillinum', 'Drosera'],
      searchKeywords: ['tuberkulose nosode', 'tuberculinum', 'reiselust', 'infektanfällig', 'erkältung', 'abmagerung', 'bergluft', 'knie ellbogen lage']
    },
    en: {
      commonName: 'Tuberculin Nosode',
      origin: 'Nosode from bovine/human tuberculous tissues.',
      essence: 'Cosmopolitan wanderlust, insatiable craving for travel and change; catches cold from slightest draft of air; rapid wasting despite voracious appetite; craves cold bracing mountain air.',
      mainIndications: ['Recurrent respiratory catarrhs and susceptibility to colds', 'Chronic bronchitis, childhood asthma & lingering coughs', 'Behavioral defiance & destructive temper tantrums in children', 'Chronic fatigue combined with restless wanderlust'],
      keynotes: ['Takes cold from the slightest change of temperature or draft of air', 'Insatiable wanderlust: constantly wants to travel, relocate, or rearrange furniture', 'Rapid emaciation despite ravenous appetite', 'Sleeps in knee-chest position or with head buried deep in pillow'],
      mindEmotional: 'Restless, discontented, destructive temper, compulsive desire to travel.',
      modalitiesBetter: ['Cool bracing mountain air & open breeze', 'Continuous rapid motion and travel'],
      modalitiesWorse: ['Before thunderstorms & damp weather', 'Drafts of cold air', 'Warm closed rooms'],
      potenciesAndDosage: 'C30, C200, 1M / 30C, 200C, 1M. Once monthly 5 pellets.',
      defaultTagesdosis: '1 dose per month / interval',
      sphereOfAction: ['Lungs & Respiratory Epithelium', 'Lymphatic Glands & Metabolism', 'Constitutional Vital Axis'],
      differentialRemedies: ['Phosphorus', 'Calcarea phosphorica', 'Bacillinum', 'Drosera'],
      searchKeywords: ['tuberculinum', 'wanderlust', 'catching cold easily', 'mountain air', 'emaciation', 'knee chest sleep', 'recurrent bronchitis']
    },
    es: { commonName: 'Tuberculina' },
    fr: { commonName: 'Tuberculinum' },
    el: { commonName: 'Τουμπερκουλίνουμ' },
    it: { commonName: 'Tuberculinum' },
    ru: { commonName: 'Туберкулинум / Нозод туберкулеза' }
  },
  {
    id: 'urtica-urens',
    latinName: 'Urtica urens',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Kleine Brennnessel',
      origin: 'Ganze frische blühende Pflanze der Kleinen Brennnessel (Urticaceae).',
      essence: 'Das Hauptmittel für Nesselsucht (Urtikaria), Quaddeln mit brennendem und stechendem Schmerz (wie Brennnessel-Kontakt), Verbrennungen 1. Grades, Mangel an Muttermilch (Agalaktie) und Gichtkrisen mit Harnsäureschub.',
      mainIndications: ['Akute Nesselsucht (Urtikaria) mit brennenden roten Quaddeln', 'Leichte Verbrennungen & Verbrühungen 1. Grades (Erythem & Brennen)', 'Mangelnde Milchbildung (Agalaktie) bei stillenden Müttern', 'Akute Gichtanfälle mit Harnsäureablagerungen'],
      keynotes: ['Haut brennt und sticht wie nach Berührung von frischen Brennnesseln', 'Quaddeln treten besonders nach Genuss von Meeresfrüchten/Muscheln auf', 'Fördert prompt den Milchfluss bei stillenden Frauen'],
      mindEmotional: 'Ungeduldig, gereizt durch den brennenden Juckreiz.',
      modalitiesBetter: ['Liegen', 'Reiben der Haut'],
      modalitiesWorse: ['Kaltes Wasser & Waschen', 'Kühler feuchter Wind', 'Genuss von Muscheln'],
      potenciesAndDosage: 'D3 bis D12. Bei akuter Urtikaria D6 alle 30 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Haut & Kapillaren (Urtikaria)', 'Mammae (Milchsekretion)', 'Nieren & Harnsäure'],
      differentialRemedies: ['Apis mellifica (besser Kälte, schlimmer Wärme)', 'Cantharis', 'Rhus tox', 'Ledum'],
      searchKeywords: ['brennnessel', 'urtica urens', 'nesselsucht', 'urtikaria', 'quaddeln', 'brennen', 'milchbildung', 'stillen', 'gicht', 'verbrennung']
    },
    en: {
      commonName: 'Dwarf Stinging Nettle',
      origin: 'Whole fresh flowering plant of Urtica urens (Urticaceae).',
      essence: 'The supreme remedy for hives (urticaria), raised stinging burning wheals (identical to nettle stings), first-degree thermal burns, deficient breast milk (agalactia), and acute gouty uric acid crises.',
      mainIndications: ['Acute urticaria & red hives with intense burning sting', 'First-degree burns & scalds with redness and stinging', 'Suppressed or deficient lactation (agalactia) in nursing mothers', 'Acute gouty attacks with elevated uric acid excretion'],
      keynotes: ['Skin stings and burns violently like contact with fresh stinging nettles', 'Urticaria provoked especially after eating shellfish or crustaceans', 'Promotes abundant lactation in postpartum nursing mothers'],
      mindEmotional: 'Impatient, restless from severe stinging itch.',
      modalitiesBetter: ['Lying down', 'Frictional rubbing'],
      modalitiesWorse: ['Cold water washing', 'Cool damp winds', 'Eating shellfish'],
      potenciesAndDosage: 'D3 to D12 / 3X to 12X. In acute hives D6 every 30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Skin Capillaries (Wheals & Erythema)', 'Mammary Glands (Lactation)', 'Renal Uric Acid Axis'],
      differentialRemedies: ['Apis mellifica (better cold, worse heat)', 'Cantharis', 'Rhus tox', 'Ledum'],
      searchKeywords: ['stinging nettle', 'urtica urens', 'hives', 'urticaria', 'wheals', 'stinging pain', 'breast milk', 'lactation', 'burns', 'gout']
    },
    es: { commonName: 'Ortiga menor' },
    fr: { commonName: 'Ortie brûlante / Petite ortie' },
    el: { commonName: 'Τσουκνίδα' },
    it: { commonName: 'Ortica minore' },
    ru: { commonName: 'Крапива жгучая / Уртика уренс' }
  },
  {
    id: 'uva-ursi',
    latinName: 'Arctostaphylos uva-ursi',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Echte Bärentraube',
      origin: 'Getrocknete Blätter der Bärentraube (Ericaceae).',
      essence: 'Das klassische Harnwegsdesinfiziens: Akute Zystitis mit heftigem Brennen beim Wasserlassen, schleimig-blutigem Urin und unerträglichem Harndrang.',
      mainIndications: ['Akute & rezidivierende Zystitis (Blasenentzündung)', 'Pyelonephritis & schmerzhafter Harnwegsinfekt', 'Blut- und Schleimbeimengungen im Urin'],
      keynotes: ['Brennende Schmerzen in Harnröhre und Blase während der Miktion', 'Ständiger, krampfhafter Harndrang mit zähem Schleimauswurf', 'Urin riecht stechend ammoniakalisch'],
      mindEmotional: 'Unruhig vor Schmerzen bei Miktion.',
      modalitiesBetter: ['Ruhe', 'Reichliches Trinken'],
      modalitiesWorse: ['Kälte & Nässe', 'Zurückhalten des Urins'],
      potenciesAndDosage: 'Urtinktur (Ø) oder D1 bis D6. Bei Zystitis 3x täglich 10 Tropfen oder 5 Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Harnblase & Urethra', 'Nierenbecken'],
      differentialRemedies: ['Cantharis', 'Equisetum', 'Sarsaparilla', 'Staphisagria'],
      searchKeywords: ['bärentraube', 'uva ursi', 'blasenentzündung', 'zystitis', 'brennen', 'harndrang', 'harnwege']
    },
    en: {
      commonName: 'Bearberry',
      origin: 'Dried leaves of Arctostaphylos uva-ursi (Ericaceae).',
      essence: 'The classic urinary antiseptic: acute cystitis with scalding burning on micturition, bloody ropy mucous sediment, and intolerable vesical tenesmus.',
      mainIndications: ['Acute & recurrent bacterial cystitis', 'Pyelonephritis & painful urethral burning', 'Mucopurulent and blood-tinged urine sediment'],
      keynotes: ['Scalding, burning pain throughout urethra while voiding', 'Constant ineffectual strangury with thick ropy mucous clots', 'Urine smells intensely ammoniacal and pungent'],
      mindEmotional: 'Restless, groans with micturition pain.',
      modalitiesBetter: ['Rest', 'Copious water intake'],
      modalitiesWorse: ['Cold damp exposure', 'Retaining urine'],
      potenciesAndDosage: 'Mother tincture (Q) or 1X to 6X / D1 to D6. In cystitis 3 times daily 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Urinary Bladder & Urethra', 'Renal Pelvis'],
      differentialRemedies: ['Cantharis', 'Equisetum', 'Sarsaparilla', 'Staphisagria'],
      searchKeywords: ['bearberry', 'uva ursi', 'cystitis', 'bladder infection', 'burning urination', 'strangury']
    },
    es: { commonName: 'Gayuba / Uva de oso' },
    fr: { commonName: 'Busserole / Raisin d’ours' },
    el: { commonName: 'Αρκτοστάφυλος' },
    it: { commonName: 'Uva ursina' },
    ru: { commonName: 'Толокнянка обыкновенная / Медвежье ушко' }
  },
  {
    id: 'veratrum-album',
    latinName: 'Veratrum album',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Weißer Germer / Weiße Nieswurz',
      origin: 'Frischer Wurzelstock des Weißen Germers vor der Blüte (Melanthiaceae).',
      essence: 'Gewaltiges gleichzeitiges Erbrechen und explosionsartiger Durchfall mit eiskaltem Schweiß auf der Stirn und tiefem Kreislaufkollaps; Eiseskälte des gesamten Körpers mit unstillbarem Verlangen nach eiskaltem Wasser.',
      mainIndications: ['Akute schwere Gastroenteritis mit gleichzeitigem Erbrechen und Durchfall', 'Kreislaufkollaps mit kaltem Stirnschweiß und Fadenpuls', 'Schwere Menstruationskrämpfe mit Ohnmacht und Durchfall', 'Manie mit Größenwahn und religiösem Eifer'],
      keynotes: ['Perlen aus eiskaltem Schweiß auf der Stirn während der Darmentleerung/des Erbrechens', 'Gleichzeitiges massives Erbrechen und wässriger Durchfall', 'Eiseskälte des Körpers (blaue Lippen, eiskalte Hände und Nasenspitze)', 'Unstillbarer Durst auf riesige Mengen eiskaltes Wasser'],
      mindEmotional: 'Größenwahn, rastet aus, reißt Kleider in Stücke, betet fanatisch oder schimpft unflätig.',
      modalitiesBetter: ['Wärme & Liegen', 'Gehen'],
      modalitiesWorse: ['Geringste Bewegung', 'Nach dem Trinken', 'Kälte'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Brechdurchfall C30 alle 15–30 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Magen-Darm-Trakt (Cholera-ähnlicher Brechdurchfall)', 'Kreislauf & Vasomotorik (Kollaps)', 'Gehirn & Manie'],
      differentialRemedies: ['Arsenicum album (heißes Brennen)', 'Camphora (eiskalt, will Decken wegwerfen)', 'Podophyllum', 'Carbo veg'],
      searchKeywords: ['weißer germer', 'veratrum album', 'brechdurchfall', 'kalter stirnschweiß', 'kollaps', 'eiseskälte', 'durst auf eiswasser', 'gastroenteritis']
    },
    en: {
      commonName: 'White Hellebore',
      origin: 'Fresh rhizome of Veratrum album (Melanthiaceae).',
      essence: 'Violent simultaneous vomiting and explosive purging diarrhea with icy cold sweat on the forehead and profound cardiovascular collapse; icy coldness of entire body with unquenchable craving for ice water.',
      mainIndications: ['Severe acute gastroenteritis with simultaneous vomiting and purging', 'Cardiovascular collapse with cold forehead sweat & thready pulse', 'Dysmenorrhea with fainting, vomiting, and cold prostration', 'Religious mania and grandiose delirium'],
      keynotes: ['Beads of icy cold sweat standing out upon forehead during stool and vomiting', 'Simultaneous projectile vomiting and copious rice-water diarrhea', 'Icy coldness of body (cyanotic lips, freezing nose tip, cold breath)', 'Unquenchable thirst for huge quantities of ice-cold water'],
      mindEmotional: 'Grandiose mania, tears clothing, screams, preaches fanatically or curses loudly.',
      modalitiesBetter: ['Warmth & lying flat', 'Continuous walking'],
      modalitiesWorse: ['Slightest motion', 'Immediately after drinking', 'Cold air'],
      potenciesAndDosage: 'Acute: D6, D12, C30 / 6C, 30C. In severe gastroenteritis C30 every 15–30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Gastrointestinal Tract (Choleraic Vomiting & Purging)', 'Cardiovascular Vasomotor Tone (Collapse)', 'Cerebral Axis & Mania'],
      differentialRemedies: ['Arsenicum album (hot burning pains)', 'Camphora (icy cold yet throws off covers)', 'Podophyllum', 'Carbo veg'],
      searchKeywords: ['white hellebore', 'veratrum album', 'vomiting and diarrhea', 'cold forehead sweat', 'collapse', 'icy cold', 'ice water thirst']
    },
    es: { commonName: 'Heléboro blanco / Veratro' },
    fr: { commonName: 'Vératre blanc / Hellébore blanc' },
    el: { commonName: 'Λευκός ελλέβορος' },
    it: { commonName: 'Veratro bianco' },
    ru: { commonName: 'Чемерица белая / Вератрум альбум' }
  },
  {
    id: 'zincum-metallicum',
    latinName: 'Zincum metallicum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Metallisches Zink',
      origin: 'Reines metallisches Zink (Zn).',
      essence: 'Extremste nervöse Unruhe der Beine und Füße (Restless-Legs-Syndrom): Ständiges Zappeln und Hin- und Herbewegen der Füße; nervöse Erschöpfung des Gehirns (Brain-Fog, Gehirn zu schwach, um einen Hautausschlag herauszubringen); Verschlimmerung durch Wein/Alkohol.',
      mainIndications: ['Restless-Legs-Syndrom (RLS) & nächtliche Beinzuckungen', 'Nervöse Erschöpfung nach Unterdrückung von Hautausschlägen', 'Muskelzuckungen, Tic-Störungen & Zähneknirschen im Schlaf', 'Kopfschmerzen nach Weingenuss (selbst kleinste Mengen)'],
      keynotes: ['Unwillkürliche, ständige Bewegung der Füße und Unterschenkel (kann Beine nicht stillhalten)', 'Weinunverträglichkeit: Schon ein kleiner Schluck Wein löst sofort Herzklopfen oder Kopfschmerz aus', 'Zucken und Aufschrecken der Muskeln im Schlaf', 'Dramatische Linderung der Nervensymptome, sobald eine Absonderung (z.B. Menstruation) einsetzt'],
      mindEmotional: 'Geistig verlangsamt, wiederholt Fragen vor dem Antworten, weint vor nervöser Schwäche.',
      modalitiesBetter: ['Auftreten von Ausscheidungen & Menstruation', 'Im Freien', 'Essen'],
      modalitiesWorse: ['Alkohol & Wein', 'Geistige Anstrengung', 'Nachts im Bett', 'Unterdrückte Ausschläge'],
      potenciesAndDosage: 'D6 bis C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Motorik', 'Beine & Füße (Restless Legs)', 'Haut & Exantheme'],
      differentialRemedies: ['Causticum', 'Tarentula hispana', 'Ignatia', 'Gelsemium'],
      searchKeywords: ['zink', 'zincum metallicum', 'restless legs', 'unruhige beine', 'fußzappeln', 'weinunverträglichkeit', 'zuckungen', 'brainfog']
    },
    en: {
      commonName: 'Metallic Zinc',
      origin: 'Pure elemental zinc.',
      essence: 'Extreme fidgety nervous restlessness of legs and feet (Restless Legs Syndrome): continuous compulsive fidgeting of feet; profound nervous brain exhaustion (brain too weak to develop an exanthem); violent intolerance of wine.',
      mainIndications: ['Restless Legs Syndrome (RLS) & nocturnal leg jerking', 'Nervous exhaustion after suppressed skin eruptions', 'Muscular twitchings, chorea, tics & teeth grinding in sleep', 'Severe headache and palpitations from a single sip of wine'],
      keynotes: ['Continuous, involuntary restless fidgeting and moving of feet and legs', 'Violent intolerance of wine: slightest sip triggers palpitations or headache', 'Sudden muscular jerking and startings in sleep', 'Dramatic relief of mental/nervous symptoms as soon as a bodily discharge appears'],
      mindEmotional: 'Mental torpor, repeats question before answering, weeps from nervous exhaustion.',
      modalitiesBetter: ['Appearance of bodily discharges & menses', 'Open air', 'Eating'],
      modalitiesWorse: ['Alcohol & wine', 'Mental exertion', 'Night in bed', 'Suppressed eruptions'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Cerebrospinal Axis & Motor Tracts', 'Lower Limbs & Feet (Restless Legs)', 'Neurodermal Axis'],
      differentialRemedies: ['Causticum', 'Tarentula hispana', 'Ignatia', 'Gelsemium'],
      searchKeywords: ['zinc', 'zincum metallicum', 'restless legs', 'fidgety feet', 'wine intolerance', 'twitching', 'brain fag']
    },
    es: { commonName: 'Zinc metálico' },
    fr: { commonName: 'Zinc métallique' },
    el: { commonName: 'Ψευδάργυρος' },
    it: { commonName: 'Zinco metallico' },
    ru: { commonName: 'Цинк металлический' }
  }
];

console.log('REMEDIES_PART9_TUVWXYZ defined with count:', REMEDIES_PART9_TUVWXYZ.length);
