import fs from 'fs';
import { RawRemedy, buildEntry } from './buildRemedyUtils';

// Let's define the comprehensive database of remedies A to Z according to hallo-homoeopathie.de and classical materia medica
// Grouped into Part 1 (A), Part 2 (B, C), Part 3 (D, E, F, G), Part 4 (H, I, J), Part 5 (K, L), Part 6 (M, N), Part 7 (O, P, Q), Part 8 (R, S), Part 9 (T - Z)

export const REMEDIES_PART1_A: RawRemedy[] = [
  {
    id: 'abies-canadensis',
    latinName: 'Abies canadensis',
    categoryKey: 'plant',
    importanceTier: 3,
    de: {
      commonName: 'Kanadische Hemlocktanne',
      origin: 'Frische Rinde und Knospen der Kanadischen Hemlocktanne (Pinaceae).',
      essence: 'Magenmittel bei Heißhunger mit Magenschwäche, Kältegefühl im Magen wie aus Eis und Neigung zu Uterusprolaps.',
      mainIndications: ['Magenschleimhautentzündung & Heißhunger', 'Kältegefühl im Bauch', 'Gebärmuttersenkung mit Schwächegefühl'],
      keynotes: ['Heißhunger mit Ohnmachtsneigung', 'Kältegefühl wie eiskaltes Wasser im Magen', 'Großes Verlangen nach Fleisch und Gurken'],
      mindEmotional: 'Reizbar, weinerlich bei Magendrücken, fühlt sich kraftlos.',
      modalitiesBetter: ['Nach dem Essen', 'Durch Wärmeanwendung'],
      modalitiesWorse: ['Auf nüchternen Magen', 'Kälte'],
      potenciesAndDosage: 'D4 bis D12. 3x täglich 5 Tropfen/Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Magen-Darm-Trakt', 'Weibliche Genitalorgane'],
      differentialRemedies: ['Abies nigra', 'Anacardium', 'Ignatia'],
      searchKeywords: ['magen', 'heißhunger', 'kältegefühl', 'tanne', 'schleimhaut']
    },
    en: {
      commonName: 'Hemlock Spruce',
      origin: 'Fresh bark and buds of the Hemlock Spruce (Pinaceae).',
      essence: 'Gastric remedy for canine hunger with stomach weakness, sensation of coldness in stomach like ice, and tendency to uterine prolapse.',
      mainIndications: ['Gastric catarrh & craving for food', 'Sensation of icy water in stomach', 'Uterine displacement with sinking sensation'],
      keynotes: ['Canine hunger with fainting feeling', 'Coldness in stomach as if ice-water', 'Craving for meat, pickles and coarse food'],
      mindEmotional: 'Irritable, weeping during gastric distress, feels worn out.',
      modalitiesBetter: ['After eating', 'Warm applications'],
      modalitiesWorse: ['Fasting', 'Cold weather'],
      potenciesAndDosage: 'D4 to D12 / 6X to 12X. 3 times daily 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Gastrointestinal Tract', 'Female Pelvic Organs'],
      differentialRemedies: ['Abies nigra', 'Anacardium', 'Ignatia'],
      searchKeywords: ['stomach', 'hunger', 'coldness', 'spruce', 'prolapse']
    },
    es: { commonName: 'Abeto del Canadá' },
    fr: { commonName: 'Pruche du Canada' },
    el: { commonName: 'Καναδικό έλατο' },
    it: { commonName: 'Abete del Canada' },
    ru: { commonName: 'Пихта канадская' }
  },
  {
    id: 'abies-nigra',
    latinName: 'Abies nigra',
    categoryKey: 'plant',
    importanceTier: 3,
    de: {
      commonName: 'Schwarzfichte / Schwarztanne',
      origin: 'Harz der Schwarzfichte (Pinaceae).',
      essence: 'Leitsymptom: Gefühl eines hartgekochten Eies oder Steins in der Magengrube / am Mageneingang, besonders nach dem Essen.',
      mainIndications: ['Dyspepsie & Magenbeschwerden älterer Menschen', 'Gefühl eines Steins im Magen', 'Schlaflosigkeit durch Magenbeschwerden'],
      keynotes: ['Gefühl, als läge ein hartes Ei im Magen', 'Schmerzhafter Druck sofort nach dem Essen', 'Völlige Appetitlosigkeit morgens, Heißhunger mittags'],
      mindEmotional: 'Trübsinnig, hypochondrisch, kann nachts nicht schlafen wegen Herzklopfen und Magenbrennen.',
      modalitiesBetter: ['Aufrechtes Stehen', 'Mäßige Bewegung'],
      modalitiesWorse: ['Nach dem Essen', 'Nachts beim Liegen'],
      potenciesAndDosage: 'D6, D12, C30. 3x täglich 5 Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Magen', 'Ösophagus', 'Herz-Kreislauf'],
      differentialRemedies: ['Nux vomica', 'Bryonia', 'Carbo vegetabilis'],
      searchKeywords: ['magen', 'stein im magen', 'hartes ei', 'dyspepsie', 'schwarzfichte']
    },
    en: {
      commonName: 'Black Spruce',
      origin: 'Gum / resin of Black Spruce (Pinaceae).',
      essence: 'Keynote sensation of a hard-boiled egg or heavy stone lodged in the cardiac orifice of the stomach, especially after meals.',
      mainIndications: ['Dyspepsia of the elderly', 'Sensation of a lump or stone in epigastrium', 'Insomnia from indigestion'],
      keynotes: ['Sensation of a hard-boiled egg in stomach', 'Painful distress immediately after meals', 'Total lack of appetite in morning, hunger at noon'],
      mindEmotional: 'Melancholic, hypochondriacal, wakeful at night with gastric distress and palpitations.',
      modalitiesBetter: ['Standing upright', 'Moderate motion'],
      modalitiesWorse: ['Immediately after eating', 'At night lying down'],
      potenciesAndDosage: 'D6, D12, C30 / 6X, 12X. 3 times daily 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Stomach', 'Esophagus', 'Cardiovascular'],
      differentialRemedies: ['Nux vomica', 'Bryonia', 'Carbo vegetabilis'],
      searchKeywords: ['stomach', 'egg sensation', 'spruce', 'dyspepsia', 'indigestion']
    },
    es: { commonName: 'Abeto negro' },
    fr: { commonName: 'Épicéa noir' },
    el: { commonName: 'Μαύρη ελάτη' },
    it: { commonName: 'Abete nero' },
    ru: { commonName: 'Ель черная' }
  },
  {
    id: 'abrotanum',
    latinName: 'Abrotanum',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Eberraute / Artemisia abrotanum',
      origin: 'Frische Blätter der Eberraute (Asteraceae).',
      essence: 'Abmagerung trotz gutem Appetit (besonders von den Beinen aufwärts), Marasmus und Symptomenmetastasierung (z.B. Rheuma nach unterdrücktem Durchfall).',
      mainIndications: ['Abmagerung & Gedeihstörungen bei Kindern', 'Metastasierende Schmerzen & Wechselfieber', 'Furunkel und Hauterkrankungen'],
      keynotes: ['Abmagerung beginnt an den Beinen und wandert aufwärts', 'Heißhunger, nimmt dennoch kontinuierlich ab', 'Beschwerden wechseln nach unterdrückten Absonderungen'],
      mindEmotional: 'Mürrisch, boshaft, reizbar, grausam bei Kindern, depressiv.',
      modalitiesBetter: ['Wärme', 'Lockere Kleidung'],
      modalitiesWorse: ['Kälte', 'Unterdrückung von Durchfällen oder Hautausschlägen'],
      potenciesAndDosage: 'D4 bis D12. 3x täglich 5 Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Stoffwechsel & Ernährung', 'Lymphsystem', 'Bewegungsapparat'],
      differentialRemedies: ['Iodium', 'Natrium muriaticum', 'Tuberculinum'],
      searchKeywords: ['abmagerung', 'marasmus', 'kinder', 'eberraute', 'beine']
    },
    en: {
      commonName: 'Southernwood',
      origin: 'Fresh leaves of Artemisia abrotanum (Asteraceae).',
      essence: 'Emaciation progressing from below upward despite good appetite; marasmus and alternating metastasis of symptoms (e.g. rheumatism after checked diarrhea).',
      mainIndications: ['Emaciation & failure to thrive in children', 'Metastasis of symptoms after suppression', 'Rheumatism alternating with gut issues'],
      keynotes: ['Emaciation starts in lower extremities', 'Ravenous appetite yet loses flesh', 'Ill effects of checked secretions or eruptions'],
      mindEmotional: 'Cross, irritable, cruel, depressed, peevish children.',
      modalitiesBetter: ['Warmth', 'Loose clothing'],
      modalitiesWorse: ['Cold air', 'Suppression of discharges'],
      potenciesAndDosage: 'D4 to D12 / 6C. 3 times daily 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Nutrition & Metabolism', 'Lymphatics', 'Locomotor System'],
      differentialRemedies: ['Iodium', 'Natrium muriaticum', 'Tuberculinum'],
      searchKeywords: ['emaciation', 'marasmus', 'southernwood', 'children', 'metastasis']
    },
    es: { commonName: 'Abrótano macho' },
    fr: { commonName: 'Aurone' },
    el: { commonName: 'Αβρότονον' },
    it: { commonName: 'Abrotano' },
    ru: { commonName: 'Абротанум / Полынь лечебная' }
  },
  {
    id: 'absinthium',
    latinName: 'Absinthium',
    categoryKey: 'plant',
    importanceTier: 3,
    de: {
      commonName: 'Wermutkraut',
      origin: 'Frische Blätter und Blüten von Artemisia absinthium (Asteraceae).',
      essence: 'Nervöse Übererregbarkeit, epileptiforme Krämpfe mit Schwindel, Halluzinationen und Zittern.',
      mainIndications: ['Epileptiforme Konvulsionen & Krämpfe', 'Nervöse Schlaflosigkeit & Alpträume', 'Schwindel mit Fallneigung nach hinten'],
      keynotes: ['Plötzlicher Beginn mit Zuckungen von Gesicht und Gliedern', 'Zittern der Zunge und Lähmungsgefühl', 'Gedächtnislücken nach Anfällen'],
      mindEmotional: 'Halluzinationen, Fluchtneigung, unruhig, vergisst eigene Handlungen.',
      modalitiesBetter: ['Frische Luft', 'Ruhe'],
      modalitiesWorse: ['Kaffee', 'Aufregung', 'Nachts'],
      potenciesAndDosage: 'D6, D12, C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Zentralnervensystem', 'Gehirn', 'Magen-Darm'],
      differentialRemedies: ['Artemisia vulgaris', 'Cicuta virosa', 'Hyoscyamus'],
      searchKeywords: ['krampf', 'epilepsie', 'wermut', 'zittern', 'halluzination']
    },
    en: {
      commonName: 'Wormwood',
      origin: 'Fresh leaves and tops of Artemisia absinthium (Asteraceae).',
      essence: 'Nervous excitability, epileptiform convulsions with vertigo, hallucinations, and generalized tremor.',
      mainIndications: ['Epileptoid spasms & convulsions', 'Nervous insomnia & scary dreams', 'Vertigo with tendency to fall backward'],
      keynotes: ['Sudden convulsive jerking of facial muscles and limbs', 'Tremor of tongue with paralytic sensation', 'Loss of memory after seizures'],
      mindEmotional: 'Hallucinatory delirium, inclination to escape, forgets past actions.',
      modalitiesBetter: ['Open fresh air', 'Quiet rest'],
      modalitiesWorse: ['Coffee', 'Excitement', 'Nighttime'],
      potenciesAndDosage: 'D6, D12, C30. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Central Nervous System', 'Brain', 'Gastrointestinal'],
      differentialRemedies: ['Artemisia vulgaris', 'Cicuta virosa', 'Hyoscyamus'],
      searchKeywords: ['convulsion', 'epilepsy', 'wormwood', 'tremor', 'vertigo']
    },
    es: { commonName: 'Ajenjo' },
    fr: { commonName: 'Absinthe' },
    el: { commonName: 'Αψιθιά' },
    it: { commonName: 'Assenzio' },
    ru: { commonName: 'Полынь горькая' }
  },
  {
    id: 'acidum-aceticum',
    latinName: 'Acidum aceticum',
    categoryKey: 'acid',
    importanceTier: 3,
    de: {
      commonName: 'Essigsäure',
      origin: 'Verdünnte reine Essigsäure (CH3COOH).',
      essence: 'Extremer unstillbarer Durst, reichliche Urinausscheidung, kachektische Schwäche und Nachtschweiße; liegt am besten auf dem Bauch.',
      mainIndications: ['Kachexie & chronische Auszehrung', 'Großer Durst bei Diabetes & Wassersucht', 'Reichliche Nachtschweiße'],
      keynotes: ['Unstillbarer Durst auf große Mengen kaltes Wasser', 'Besserung aller Symptome beim Liegen auf dem Bauch', 'Große Blässe und wachsartiges Gesicht'],
      mindEmotional: 'Ängstlich um Familie und Gesundheit, nervös und schwach.',
      modalitiesBetter: ['Liegen auf dem Bauch', 'Ruhe'],
      modalitiesWorse: ['Kälte', 'Aufrechtes Liegen auf dem Rücken'],
      potenciesAndDosage: 'D6 bis D12. 3x täglich 5 Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Nieren & Flüssigkeitshaushalt', 'Magen-Darm', 'Atmungsorgane'],
      differentialRemedies: ['Arsenicum album', 'Phosphoricum acidum', 'China'],
      searchKeywords: ['essigsäure', 'durst', 'wassersucht', 'bauchlage', 'kachexie']
    },
    en: {
      commonName: 'Acetic Acid',
      origin: 'Dilute pure acetic acid.',
      essence: 'Extreme unquenchable thirst, profuse pale urination, profound debility, cachexia, and night sweats; sleeps best resting on abdomen.',
      mainIndications: ['Cachectic wasting states & anemia', 'Intense thirst in dropsy and diabetes', 'Drenching night sweats'],
      keynotes: ['Unquenchable burning thirst for large drinks', 'Cannot sleep on back, must lie flat on abdomen', 'Waxen, deathly pale skin'],
      mindEmotional: 'Anxious concerning family and health, nervous and prostrated.',
      modalitiesBetter: ['Lying flat on the belly', 'Rest'],
      modalitiesWorse: ['Cold', 'Lying on back'],
      potenciesAndDosage: '6X to 12X / D6 to D12. 3 times daily 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Kidneys & Fluid Balance', 'Gastrointestinal', 'Lungs'],
      differentialRemedies: ['Arsenicum album', 'Phosphoricum acidum', 'China'],
      searchKeywords: ['acetic acid', 'thirst', 'dropsy', 'abdomen', 'sweat']
    },
    es: { commonName: 'Ácido acético' },
    fr: { commonName: 'Acide acétique' },
    el: { commonName: 'Οξικό οξύ' },
    it: { commonName: 'Acido acetico' },
    ru: { commonName: 'Уксусная кислота' }
  },
  {
    id: 'acidum-benzoicum',
    latinName: 'Acidum benzoicum',
    categoryKey: 'acid',
    importanceTier: 2,
    de: {
      commonName: 'Benzoesäure',
      origin: 'Reine kristallisierte Benzoesäure.',
      essence: 'Harnsäure-Diathese und Gelenkgicht mit extrem intensiv stechend nach Pferdeharn riechendem, braunem Urin.',
      mainIndications: ['Gichtknoten & Arthritis urica', 'Enuresis nocturna mit stark riechendem Urin', 'Achillessehnen- und Großzehenschmerzen'],
      keynotes: ['Urin riecht extrem penetrant stechend wie Pferdeharn', 'Knacken in den Gelenken bei jeder Bewegung', 'Gelenkbeschwerden wechseln mit Urinausscheidung'],
      mindEmotional: 'Neigt zum Grübeln über unangenehme Dinge, niedergeschlagen.',
      modalitiesBetter: ['Reichlicher Urinfluss', 'Wärme'],
      modalitiesWorse: ['Kaltes feuchtes Wetter', 'Entblößen'],
      potenciesAndDosage: 'D4 bis D12. 3x täglich 5 Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Harnwege & Blase', 'Gelenke & Sehnen', 'Bindegewebe'],
      differentialRemedies: ['Berberis', 'Colchicum', 'Ledum', 'Lithium carb'],
      searchKeywords: ['gicht', 'benzoesäure', 'urinstank', 'harnsäure', 'gelenke']
    },
    en: {
      commonName: 'Benzoic Acid',
      origin: 'Pure crystalline benzoic acid.',
      essence: 'Uric acid diathesis and gouty joints characterized by dark brown urine smelling intensely pungent and offensive like horse urine.',
      mainIndications: ['Gouty nodes & acute arthritic flares', 'Nocturnal enuresis with strong-smelling urine', 'Achilles tendon and big toe pain'],
      keynotes: ['Urine highly colored with pungent horse-urine odor', 'Cracking in joints upon motion', 'Joint pains alternate with urinary flow'],
      mindEmotional: 'Dwells on unpleasant past events, depressed, melancholic.',
      modalitiesBetter: ['Free profuse flow of urine', 'Warmth'],
      modalitiesWorse: ['Cold wet drafts', 'Uncovering'],
      potenciesAndDosage: 'D4 to D12 / 6C. 3 times daily 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Urinary Tract', 'Joints & Tendons', 'Connective Tissue'],
      differentialRemedies: ['Berberis', 'Colchicum', 'Ledum', 'Lithium carb'],
      searchKeywords: ['gout', 'benzoic acid', 'urine odor', 'uric acid', 'joints']
    },
    es: { commonName: 'Ácido benzoico' },
    fr: { commonName: 'Acide benzoïque' },
    el: { commonName: 'Βενζοϊκό οξύ' },
    it: { commonName: 'Acido benzoico' },
    ru: { commonName: 'Бензойная кислота' }
  },
  {
    id: 'acidum-fluoricum',
    latinName: 'Acidum fluoricum',
    categoryKey: 'acid',
    importanceTier: 2,
    de: {
      commonName: 'Flusssäure / Fluoricum acidum',
      origin: 'Wässrige Lösung von Fluorwasserstoff (HF).',
      essence: 'Tiefgreifende Gewebsdestruktion, Knochennekrosen, Fisteln und Krampfadern bei extrem heißen, hitzeintoleranten Patienten mit übermäßiger Vitalität.',
      mainIndications: ['Knochen- & Zahnfisteln', 'Ausgeprägte Varikose & Krampfadergeschwüre', 'Vorzeitiges Altern & Karies'],
      keynotes: ['Patient hat ständig zu heiß und sucht Kälte', 'Kaltes Baden bringt sofortige Linderung', 'Brennende Schmerzen in alten Narben'],
      mindEmotional: 'Überaktiver Geist, gleichgültig gegenüber geliebten Menschen, impulsiv.',
      modalitiesBetter: ['Kälte & kaltes Baden', 'Schnelle Bewegung'],
      modalitiesWorse: ['Wärme & warme Zimmer', 'Morgens'],
      potenciesAndDosage: 'D6 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Knochen & Zähne', 'Venen & Bindegewebe', 'Haut'],
      differentialRemedies: ['Silicea (Silicea fröstelt, Fluoricum schwitzt)', 'Calcarea fluorica'],
      searchKeywords: ['flusssäure', 'fistel', 'knochen', 'krampfadern', 'kältebesserung']
    },
    en: {
      commonName: 'Hydrofluoric Acid',
      origin: 'Aqueous solution of hydrofluoric acid.',
      essence: 'Destructive tissue breakdown, bone necrosis, fistulae, and varicose ulcers in abnormally warm, heat-intolerant patients with buoyant energy.',
      mainIndications: ['Dental & bone fistulae', 'Varicose veins & indolent ulcers', 'Premature aging & tooth decay'],
      keynotes: ['Intolerant of heat, desires cool air and cold bathing', 'Cold bathing gives instant amelioration', 'Burning and itching in old scars'],
      mindEmotional: 'Buoyant spirit, indifferent toward beloved family members, hurried.',
      modalitiesBetter: ['Cold air and cold washing', 'Rapid vigorous motion'],
      modalitiesWorse: ['Warmth & heated rooms', 'Morning on waking'],
      potenciesAndDosage: 'D6 to C30 / 6C to 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Bones & Teeth', 'Venous Circulation', 'Skin'],
      differentialRemedies: ['Silicea (Silicea chilly, Fluoricum hot)', 'Calcarea fluorica'],
      searchKeywords: ['hydrofluoric', 'fistula', 'varicose', 'bone', 'heat intolerant']
    },
    es: { commonName: 'Ácido fluorhídrico' },
    fr: { commonName: 'Acide fluorhydrique' },
    el: { commonName: 'Υδροφθορικό οξύ' },
    it: { commonName: 'Acido fluoridrico' },
    ru: { commonName: 'Плавиковая кислота' }
  },
  {
    id: 'acidum-nitricum',
    latinName: 'Acidum nitricum',
    categoryKey: 'acid',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Salpetersäure / Nitricum acidum',
      origin: 'Reine Salpetersäure (HNO3).',
      essence: 'Splitterschmerzende Ulzera an allen Haut-Schleimhaut-Übergängen (Mund, After), Warzen, stinkender Urin und unversöhnliches Gemüt.',
      mainIndications: ['Afterfissuren & Hämorrhoiden mit stechendem Splitterschmerz', 'Aphthen, Mundgeschwüre & Rhagaden', 'Warzen & feuchte Kondylome'],
      keynotes: ['Schmerz wie von einem eingestochenen Glassplitter', 'Starker, stechend riechender Urin (wie Pferdeharn)', 'Besserung aller Symptome beim Fahren im Wagen / Zug'],
      mindEmotional: 'Unversöhnlich, nachtragend, verzweifelt, ängstlich um eigene Gesundheit.',
      modalitiesBetter: ['Fahren in Fahrzeugen / Erschütterung', 'Mäßige Wärme'],
      modalitiesWorse: ['Kälte & Wetterwechsel', 'Berührung', 'Nach dem Stuhlgang'],
      potenciesAndDosage: 'D6, D12, C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Haut-Schleimhaut-Grenzen', 'Enddarm & After', 'Harnblase'],
      differentialRemedies: ['Hepar sulfuris', 'Thuja', 'Mercurius', 'Silicea'],
      searchKeywords: ['salpetersäure', 'splitterschmerz', 'afterfissur', 'warzen', 'aphthen']
    },
    en: {
      commonName: 'Nitric Acid',
      origin: 'Pure nitric acid.',
      essence: 'Splinter-like stitching pains at mucocutaneous junctions (mouth, anus), jagged bleeding warts, offensive pungent urine, and unforgiving mental state.',
      mainIndications: ['Anal fissures & ulcerated piles with splinter pains', 'Aphthous ulcers & cracks at angle of mouth', 'Cauliflower warts & condylomata'],
      keynotes: ['Sticking pains like a sharp splinter or needle', 'Strong offensive urine smelling like horse urine', 'Riding in a carriage or train ameliorates'],
      mindEmotional: 'Unforgiving, holds grudges, anxious regarding health, discontented.',
      modalitiesBetter: ['Riding in cars or trains', 'Mild gentle warmth'],
      modalitiesWorse: ['Cold & damp weather changes', 'Touch', 'After bowel movement'],
      potenciesAndDosage: 'D6, D12, C30. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Mucocutaneous Junctions', 'Rectum & Anus', 'Bladder & Skin'],
      differentialRemedies: ['Hepar sulfuris', 'Thuja', 'Mercurius', 'Silicea'],
      searchKeywords: ['nitric acid', 'splinter pain', 'anal fissure', 'warts', 'riding better']
    },
    es: { commonName: 'Ácido nítrico' },
    fr: { commonName: 'Acide nitrique' },
    el: { commonName: 'Νιτρικό οξύ' },
    it: { commonName: 'Acido nitrico' },
    ru: { commonName: 'Азотная кислота' }
  },
  {
    id: 'acidum-phosphoricum',
    latinName: 'Acidum phosphoricum',
    categoryKey: 'acid',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Phosphorsäure / Phosphoricum acidum',
      origin: 'Reine verdünnte Phosphorsäure (H3PO4).',
      essence: 'Tiefe geistige und körperliche Erschöpfung nach Kummer, Trauer, Schlafmangel oder Verlust von Körpersäften; apathisch und reaktionsarm.',
      mainIndications: ['Chronische Erschöpfung & Burnout nach Trauer', 'Haarausfall nach Schock oder Kummer', 'Schmerzlose, nicht schwächende Durchfälle'],
      keynotes: ['Vollständige Apathie und emotionale Abstumpfung', 'Schmerzloser wässriger Durchfall, der nicht entkräftet', 'Milchig-trüber Urin bei nervöser Erschöpfung'],
      mindEmotional: 'Spricht kaum, apathisch, antwortet langsam, gleichgültig gegenüber allem.',
      modalitiesBetter: ['Kurzer Schlaf', 'Wärme'],
      modalitiesWorse: ['Geistige Anstrengung', 'Kummer', 'Verlust von Flüssigkeiten'],
      potenciesAndDosage: 'D6, D12, C30. Im Erschöpfungszustand 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Nervensystem & Gehirn', 'Haare & Haut', 'Verdauungstrakt'],
      differentialRemedies: ['Ignatia (akuter Kummer)', 'Natrium muriaticum', 'China (Saftverlust)'],
      searchKeywords: ['phosphorsäure', 'kummer', 'erschöpfung', 'burnout', 'apathie', 'haarausfall']
    },
    en: {
      commonName: 'Phosphoric Acid',
      origin: 'Pure diluted phosphoric acid.',
      essence: 'Profound mental and physical prostration following grief, sorrow, sleeplessness, or loss of vital fluids; indifferent, listless, and burned-out.',
      mainIndications: ['Chronic fatigue & burnout after grief', 'Hair loss after severe emotional shock', 'Painless copious diarrhea without exhaustion'],
      keynotes: ['Complete emotional apathy and indifference', 'Painless watery diarrhea that leaves patient untired', 'Milky, phosphatic urine under mental strain'],
      mindEmotional: 'Apathetic, speaks little, slow in answering, completely indifferent.',
      modalitiesBetter: ['Short restorative sleep', 'Warmth'],
      modalitiesWorse: ['Mental exertion', 'Grief & sorrow', 'Fluid loss'],
      potenciesAndDosage: 'D6, D12, C30. In burnout 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Nervous System & Brain', 'Hair & Skin', 'Digestive Canal'],
      differentialRemedies: ['Ignatia (acute grief)', 'Natrium muriaticum', 'China (fluid loss)'],
      searchKeywords: ['phosphoric acid', 'grief', 'exhaustion', 'burnout', 'apathy', 'hair loss']
    },
    es: { commonName: 'Ácido fosfórico' },
    fr: { commonName: 'Acide phosphorique' },
    el: { commonName: 'Φωσφορικό οξύ' },
    it: { commonName: 'Acido fosforico' },
    ru: { commonName: 'Фосфорная кислота' }
  },
  {
    id: 'acidum-sulfuricum',
    latinName: 'Acidum sulfuricum',
    categoryKey: 'acid',
    importanceTier: 2,
    de: {
      commonName: 'Schwefelsäure / Sulphuricum acidum',
      origin: 'Verdünnte Schwefelsäure (H2SO4).',
      essence: 'Innere Eile und Hast, Neigung zu blauen Flecken (Ekchymosen) bei geringstem Anstoß, saures Aufstoßen und Sodbrennen.',
      mainIndications: ['Sodbrennen & extrem saures Aufstoßen', 'Hämatome & Petechien nach kleinstem Trauma', 'Magenkatarrh bei Alkoholikern'],
      keynotes: ['Gefühl ständiger innerer Hetze und Eile', 'Zähne fühlen sich wie stumpf an durch Magensäure', 'Große Schwäche mit innerem Zittern ohne sichtbares Zittern'],
      mindEmotional: 'Ungeduldig, alles muss sofort und schnell erledigt werden, gereizt.',
      modalitiesBetter: ['Wärme', 'Liegen auf der schmerzhaften Seite'],
      modalitiesWorse: ['Kaltes Wasser', 'Erschütterung', 'Geruch von Kaffee'],
      potenciesAndDosage: 'D6 bis C30. 2-3x täglich 5 Globuli.',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Magen-Darm-Kanal', 'Gefäßwände & Kapillaren', 'Blut'],
      differentialRemedies: ['Arnica', 'Sulfur', 'Phosphorus', 'Carbo vegetabilis'],
      searchKeywords: ['schwefelsäure', 'sodbrennen', 'eile', 'blaue flecken', 'saures erbrechen']
    },
    en: {
      commonName: 'Sulfuric Acid',
      origin: 'Diluted sulfuric acid.',
      essence: 'Internal hurriedness and haste, ecchymoses and black-and-blue bruises from slightest trauma, intensely sour vomiting and pyrosis.',
      mainIndications: ['Heartburn & intensely sour eructations', 'Bruises & petechiae upon trivial touch', 'Alcoholic gastritis and tremor'],
      keynotes: ['Constant internal hurry, feels everything must be done fast', 'Teeth feel set on edge by extreme gastric acidity', 'Profound weakness with internal trembling without visible tremor'],
      mindEmotional: 'Impatient, restless, easily irritated if work is delayed.',
      modalitiesBetter: ['Warmth', 'Lying on painful side'],
      modalitiesWorse: ['Cold open air', 'Odor of coffee', 'Smell of cold drinks'],
      potenciesAndDosage: 'D6 to C30 / 6C to 30C. 2-3 times daily 5 pellets.',
      defaultTagesdosis: '2-3 times daily 5 pellets',
      sphereOfAction: ['Digestive Canal', 'Capillary Vessels', 'Blood'],
      differentialRemedies: ['Arnica', 'Sulfur', 'Phosphorus', 'Carbo vegetabilis'],
      searchKeywords: ['sulfuric acid', 'heartburn', 'haste', 'bruises', 'sour eructations']
    },
    es: { commonName: 'Ácido sulfúrico' },
    fr: { commonName: 'Acide sulfurique' },
    el: { commonName: 'Θειικό οξύ' },
    it: { commonName: 'Acido solforico' },
    ru: { commonName: 'Серная кислота' }
  },
  {
    id: 'aconitum-napellus',
    latinName: 'Aconitum napellus',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Blauer Eisenhut',
      origin: 'Frische, zur Blütezeit gesammelte ganze Pflanze und Wurzel des Blauen Eisenhuts (Ranunculaceae).',
      essence: 'Das Sturm- und Schockmittel. Plötzlicher, heftiger Beginn fieberhafter Entzündungen nach Kälteeinwirkung (kalter Ost-/Nordwind) oder plötzlichem Schreck mit panischer Todesangst und unbändiger Ruhelosigkeit.',
      mainIndications: ['Plötzliches hohes Fieber & Grippeinitialstadium', 'Akuter Krupp-Husten & Pseudokrupp (erwacht um Mitternacht)', 'Panikattacken, Schockzustand & Todesangst', 'Gesichtsneuralgien & Trigeminusneuralgie nach Kaltwind', 'Tachykardie mit Herzklopfen und Angst'],
      keynotes: ['Plötzlicher, stürmischer Beginn der Symptome', 'Große Angst, Unruhe, Vorhersage der Todesstunde', 'Trockene, heiße Haut ohne jegliche Schweißbildung', 'Unstillbarer Durst auf große Mengen kaltes Wasser', 'Rotes Gesicht im Liegen, wird beim Aufrichten leichenblass'],
      mindEmotional: 'Todesangst, panische Unruhe, Vorahnung des Todes. Wirft sich im Bett ruhelos hin und her. Ängstlich, schreckhaft, verträgt keine Musik.',
      modalitiesBetter: ['An der frischen Luft', 'Nach Einsetzen des Schweißes', 'Durch Ruhe'],
      modalitiesWorse: ['Kalter, trockener Wind & Zugluft', 'Um Mitternacht (23:00 - 01:00 Uhr)', 'Beim Aufrichten aus dem Liegen', 'In warmen Räumen'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Im Akutfall C30: 3–5 Globuli alle 15–30 Minuten bis zur Besserung / Schweißausbruch.',
      defaultTagesdosis: '1–2 Gaben à 3–5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Psyche', 'Herz-Kreislauf-System', 'Atmungsorgane', 'Schleimhäute'],
      differentialRemedies: ['Belladonna (Schwitzen, pochend)', 'Arsenicum album (brennend, 1-3 Uhr nachts)', 'Chamomilla (reizbar)'],
      searchKeywords: ['fieber', 'angst', 'panik', 'todesangst', 'plötzlich', 'krupp', 'kaltwind', 'schock', 'herzklopfen', 'eisenhut']
    },
    en: {
      commonName: 'Monkshood / Blue Rocket',
      origin: 'Fresh blooming plant and root of Monkshood (Ranunculaceae).',
      essence: 'The primary acute shock and storm remedy. Sudden, intense onset of high fever and inflammation after exposure to dry cold wind or sudden emotional shock with panic, fear of death, and intense restlessness.',
      mainIndications: ['Sudden high fever & initial stage of flu', 'Acute croup and pseudo-croup (waking around midnight)', 'Panic attacks, shock states & fear of death', 'Facial neuralgias & trigeminal neuralgia after cold wind', 'Tachycardia with palpitations and anxiety'],
      keynotes: ['Sudden, violent onset of symptoms', 'Great fear, agony, predicts the hour of death', 'Dry, burning hot skin without perspiration', 'Unquenchable thirst for large quantities of cold water', 'Red face when lying down, turns deathly pale on rising'],
      mindEmotional: 'Intense fear of death, panic, restlessness, tosses about in bed. Anxious, easily startled, intolerant of music.',
      modalitiesBetter: ['Open fresh air', 'Onset of perspiration', 'Quiet rest'],
      modalitiesWorse: ['Cold dry wind & drafts', 'Midnight (23:00 - 01:00)', 'Rising from lying down', 'Warm rooms'],
      potenciesAndDosage: 'Acute: D6, D12, C30. In acute crisis C30: 3–5 pellets every 15–30 min until perspiration starts.',
      defaultTagesdosis: '1–2 doses of 3–5 pellets',
      sphereOfAction: ['Central Nervous System & Mind', 'Cardiovascular System', 'Respiratory Organs', 'Mucous Membranes'],
      differentialRemedies: ['Belladonna (sweating, throbbing)', 'Arsenicum album (burning, 1-3 AM)', 'Chamomilla (irritable)'],
      searchKeywords: ['fever', 'fear', 'panic', 'death', 'sudden', 'croup', 'cold wind', 'shock', 'palpitations', 'monkshood']
    },
    es: { commonName: 'Acónito azul' },
    fr: { commonName: 'Aconit Napel' },
    el: { commonName: 'Ακόνιτο' },
    it: { commonName: 'Aconito Napello' },
    ru: { commonName: 'Борец синий / Аконит' }
  },
  {
    id: 'aesculus-hippocastanum',
    latinName: 'Aesculus hippocastanum',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Rosskastanie',
      origin: 'Reife Früchte der Gemeinen Rosskastanie (Sapindaceae).',
      essence: 'Venöse Stauung (besonders Portalvenensystem) mit schmerzhaften Hämorrhoiden, Völlegefühl im Rektum wie voller kleiner Holzsplitter und dumpfen Kreuzbeinschmerzen.',
      mainIndications: ['Hämorrhoiden (blaurot, schmerzhaft, selten blutend)', 'Kreuzschmerzen & Iliosakralgelenkblockade', 'Krampfadern mit Stauungsschwere in den Beinen'],
      keynotes: ['Gefühl von kleinen Holzsplittern oder Nadeln im Rektum', 'Trockenheit und Brennen in Schleimhäuten', 'Dumpfer Rückenschmerz beim Gehen oder Bücken'],
      mindEmotional: 'Deprimiert, reizbar, verstimmt nach dem Erwachen.',
      modalitiesBetter: ['Kühle Luft', 'Mäßige Bewegung'],
      modalitiesWorse: ['Langes Stehen', 'Gehen', 'Nach dem Stuhlgang'],
      potenciesAndDosage: 'D4 bis D12. 3x täglich 5 Tropfen oder Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Venen & Pfortadersystem', 'Rektum & Anus', 'Lumbosakralbereich'],
      differentialRemedies: ['Hamamelis', 'Collinsonia', 'Aloe', 'Nux vomica'],
      searchKeywords: ['hämorrhoiden', 'rosskastanie', 'kreuzschmerzen', 'splittergefühl', 'venenstauung']
    },
    en: {
      commonName: 'Horse Chestnut',
      origin: 'Ripe seeds of the Horse Chestnut (Sapindaceae).',
      essence: 'Venous engorgement (portal system) resulting in painful purple hemorrhoids, sensation of splinter sticks in rectum, and aching sacral lumbago.',
      mainIndications: ['Hemorrhoids (purple, painful, rarely bleeding)', 'Low backache & sacroiliac joint pain', 'Varicose veins with heavy legs'],
      keynotes: ['Sensation as if rectum were full of small wooden sticks', 'Dryness and burning in mucous membranes', 'Dull heavy aching in lumbosacral region on walking'],
      mindEmotional: 'Gloomy, irritable, disinclined to work upon waking.',
      modalitiesBetter: ['Cool open air', 'Gentle moderate exercise'],
      modalitiesWorse: ['Standing for long periods', 'Walking', 'After stool'],
      potenciesAndDosage: 'D4 to D12 / 6C. 3 times daily 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Venous System & Portal Vein', 'Rectum & Anus', 'Lumbosacral Spine'],
      differentialRemedies: ['Hamamelis', 'Collinsonia', 'Aloe', 'Nux vomica'],
      searchKeywords: ['hemorrhoids', 'horse chestnut', 'backache', 'splinters in rectum', 'veins']
    },
    es: { commonName: 'Castaño de Indias' },
    fr: { commonName: 'Marronnier d’Inde' },
    el: { commonName: 'Ιπποκαστανιά' },
    it: { commonName: 'Ippocastano' },
    ru: { commonName: 'Каштан конский' }
  },
  {
    id: 'aethusa-cynapium',
    latinName: 'Aethusa cynapium',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Hundspetersilie',
      origin: 'Ganze blühende Pflanze der Hundspetersilie (Apiaceae).',
      essence: 'Milchunverträglichkeit bei Säuglingen und Kindern: schwallartiges Erbrechen geronnener Milchbrocken, gefolgt von schlaffer Erschöpfung und Schlaf.',
      mainIndications: ['Milchunverträglichkeit & Säuglingsdyspepsie', 'Schwallartiges Erbrechen von Milchklumpen', 'Prüfungsangst & geistige Erschöpfung von Studenten'],
      keynotes: ['Erbrechen von großen sauren Milchklumpen', 'Schläft sofort nach dem Erbrechen tief erschöpft ein', 'Völlige Unfähigkeit zu denken bei Prüfungen'],
      mindEmotional: 'Unruhig, ängstlich, kann vor Prüfungen keinen klaren Gedanken fassen.',
      modalitiesBetter: ['Frische Luft', 'Nach dem Schlaf'],
      modalitiesWorse: ['Milch', 'Nach dem Erbrechen oder Stuhlgang', 'Wärme'],
      potenciesAndDosage: 'D6, D12, C30. 2-3x täglich 5 Globuli.',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Magen-Darm-Trakt', 'Gehirn & Nerven'],
      differentialRemedies: ['Calcarea carbonica', 'Magnesia muriatica', 'Antimonium crudum'],
      searchKeywords: ['milch', 'erbrechen', 'säugling', 'hundspetersilie', 'prüfung']
    },
    en: {
      commonName: "Fool's Parsley",
      origin: "Whole flowering plant of Fool's Parsley (Apiaceae).",
      essence: 'Intolerance of milk in infants and children: projectile vomiting of curdled milk chunks followed by deep prostration and sleep.',
      mainIndications: ['Milk intolerance & infantile gastroenteritis', 'Projectile vomiting of curds', 'Examination brain fag and mental exhaustion'],
      keynotes: ['Vomiting of milk in thick curds immediately after nursing', 'Falls into deep exhausted sleep right after vomiting', 'Inability to fix attention or study before exams'],
      mindEmotional: 'Anxious, restless, complete incapacity to think before exams.',
      modalitiesBetter: ['Open fresh air', 'After refreshing sleep'],
      modalitiesWorse: ['Milk', 'After stool or vomiting', 'Warm room'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. 2-3 times daily 5 pellets.',
      defaultTagesdosis: '2-3 times daily 5 pellets',
      sphereOfAction: ['Gastrointestinal Tract', 'Brain & Mind'],
      differentialRemedies: ['Calcarea carbonica', 'Magnesia muriatica', 'Antimonium crudum'],
      searchKeywords: ['milk intolerance', 'vomiting curds', 'fools parsley', 'infant', 'brain fag']
    },
    es: { commonName: 'Cicuta menor' },
    fr: { commonName: 'Petite ciguë' },
    el: { commonName: 'Αίθουσα' },
    it: { commonName: 'Cicuta minore' },
    ru: { commonName: 'Этуза / Собачья петрушка' }
  },
  {
    id: 'agaricus-muscarius',
    latinName: 'Agaricus muscarius',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Fliegenpilz / Amanita muscaria',
      origin: 'Frischer Pilzfruchtkörper des Fliegenpilzes (Amanitaceae).',
      essence: 'Zuckungen, Tics, Chorea, unwillkürliche Muskelkrämpfe und Frostbeulen (Chilblains) mit brennendem, stechendem Juckreiz wie von Eissplittern.',
      mainIndications: ['Tics, Augenlidzucken & Chorea minor', 'Frostbeulen mit Brennen und Stechen', 'Zittern der Hände & Gangunsicherheit'],
      keynotes: ['Zuckungen der Augenlider und Gesichtsmuskeln', 'Gefühl, als berührten eiskalte Nadeln die Haut', 'Schmerzen verlaufen diagonal (z.B. linker Arm und rechtes Bein)'],
      mindEmotional: 'Singt, dichtet, redet hastig, deliriumartige Zustände.',
      modalitiesBetter: ['Sanfte langsame Bewegung'],
      modalitiesWorse: ['Kälte & Kaltluft', 'Nach Geschlechtsverkehr', 'Vor Gewitter'],
      potenciesAndDosage: 'D6, D12, C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Motorik', 'Haut & Peripherie'],
      differentialRemedies: ['Tarentula hispana', 'Mygale', 'Zincum', 'Causticum'],
      searchKeywords: ['fliegenpilz', 'tics', 'zucken', 'frostbeulen', 'chorea', 'zittern']
    },
    en: {
      commonName: 'Fly Agaric',
      origin: 'Fresh fungus of Amanita muscaria (Amanitaceae).',
      essence: 'Twitchings, tics, chorea, involuntary motor jerks, and chilblains burning and itching as if pierced by ice-cold needles.',
      mainIndications: ['Tics, eyelid twitching & chorea minor', 'Chilblains with burning and stinging', 'Tremors of hands and ataxia'],
      keynotes: ['Twitching of eyelids and facial musculature', 'Sensation as if cold needles were piercing skin', 'Diagonal symptoms (left arm and right leg)'],
      mindEmotional: 'Delirium with loquacity, poetic singing, disinclined to answer.',
      modalitiesBetter: ['Gentle slow motion'],
      modalitiesWorse: ['Cold open air', 'After coitus', 'Before a thunderstorm'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Motor Nervous System', 'Skin & Circulation'],
      differentialRemedies: ['Tarentula hispana', 'Mygale', 'Zincum', 'Causticum'],
      searchKeywords: ['fly agaric', 'tics', 'twitching', 'chilblains', 'chorea', 'tremor']
    },
    es: { commonName: 'Matamoscas' },
    fr: { commonName: 'Amanite tue-mouches' },
    el: { commonName: 'Αγαρικό' },
    it: { commonName: 'Amanita muscaria' },
    ru: { commonName: 'Мухомор красный' }
  },
  {
    id: 'agnus-castus',
    latinName: 'Agnus castus',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Mönchspfeffer / Keuschlamm',
      origin: 'Reife, getrocknete Früchte des Mönchspfeffers (Lamiaceae).',
      essence: 'Völliger Verlust des sexuellen Verlangens und Potenzverlust nach Ausschweifungen; depressive Verstimmungen und fehlende Muttermilch (Agalaktie).',
      mainIndications: ['Impotenz mit kalten, schlaffen Genitalien', 'Mangelnde Milchbildung bei Wöchnerinnen', 'Depression mit Selbstvorwürfen'],
      keynotes: ['Völliger Mangel an sexueller Lust', 'Vorzeitiges Altern der Geschlechtsorgane', 'Häufiges Wiederholen von Fragen wegen Gedächtnisschwäche'],
      mindEmotional: 'Tiefe Niedergeschlagenheit, Angst vor baldigem Tod, traurig.',
      modalitiesBetter: ['Ruhe'],
      modalitiesWorse: ['Sexuelle Exzesse', 'Aufregung'],
      potenciesAndDosage: 'D4 bis D12. 2-3x täglich 5 Globuli.',
      defaultTagesdosis: '2-3x täglich 5 Globuli',
      sphereOfAction: ['Geschlechtsorgane', 'Hormonsystem & Hypophyse'],
      differentialRemedies: ['Selenium', 'Caladium', 'Conium', 'Sepia'],
      searchKeywords: ['mönchspfeffer', 'impotenz', 'milchmangel', 'libidoverlust', 'depression']
    },
    en: {
      commonName: 'Chaste Tree',
      origin: 'Ripe dried berries of Vitex agnus-castus (Lamiaceae).',
      essence: 'Complete loss of sexual desire and premature impotence after excesses; melancholic depression and lack of breast milk (agalactia).',
      mainIndications: ['Erectile dysfunction with cold relaxed genitals', 'Deficient lactation in nursing mothers', 'Depressive hypochondria'],
      keynotes: ['Complete absence of sexual desire', 'Premature old age of genital organs', 'Repeats questions due to weak memory'],
      mindEmotional: 'Profound melancholy, predicts impending death, despairing.',
      modalitiesBetter: ['Rest'],
      modalitiesWorse: ['Sexual excesses', 'Exertion'],
      potenciesAndDosage: 'D4 to D12 / 6C. 2-3 times daily 5 pellets.',
      defaultTagesdosis: '2-3 times daily 5 pellets',
      sphereOfAction: ['Reproductive System', 'Hormonal Axis & Lactation'],
      differentialRemedies: ['Selenium', 'Caladium', 'Conium', 'Sepia'],
      searchKeywords: ['chaste tree', 'impotence', 'lactation', 'low libido', 'depression']
    },
    es: { commonName: 'Sauzgatillo' },
    fr: { commonName: 'Gattilier' },
    el: { commonName: 'Λυγαριά' },
    it: { commonName: 'Agnocasto' },
    ru: { commonName: 'Агнус кастус / Прутняк' }
  },
  {
    id: 'allium-cepa',
    latinName: 'Allium cepa',
    categoryKey: 'plant',
    importanceTier: 1,
    de: {
      commonName: 'Küchenzwiebel',
      origin: 'Frische rote Küchenzwiebel (Amaryllidaceae).',
      essence: 'Fließschnupfen mit scharfem, wundmachendem Nasensekret und milder, brennfreier Tränenflüssigkeit; besser an kühler frischer Luft.',
      mainIndications: ['Akuter Fließschnupfen & Erkältungsstadium', 'Heuschnupfen & allergische Rhinitis', 'Kitzelnder Husten mit Schmerz im Kehlkopf'],
      keynotes: ['Scharfer Nasenfluss macht Oberlippe und Nasenflügel wund', 'Milde reichliche Tränenflüssigkeit (Gegenteil von Euphrasia)', 'Starke Besserung im Freien und in kalter Luft'],
      mindEmotional: 'Ängstlich bei Schmerzen im Kehlkopf, schläfrig bei Schnupfen.',
      modalitiesBetter: ['An der frischen, kühlen Luft', 'In kalten Räumen'],
      modalitiesWorse: ['Im warmen Zimmer', 'Gegen Abend', 'Durch Nässe'],
      potenciesAndDosage: 'D6, D12, C30. Akut: 3–5 Globuli alle 1–2 Stunden.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Obere Atemwege & Nase', 'Augen', 'Kehlkopf'],
      differentialRemedies: ['Euphrasia (Auge scharf, Nase mild)', 'Arsenicum album', 'Sabadilla'],
      searchKeywords: ['zwiebel', 'schnupfen', 'fließschnupfen', 'heuschnupfen', 'tränen', 'nase']
    },
    en: {
      commonName: 'Red Onion',
      origin: 'Fresh red onion bulb (Amaryllidaceae).',
      essence: 'Profuse watery coryza with acrid excoriating nasal discharge and bland lacrimation; marked relief in open cool air.',
      mainIndications: ['Acute catarrhal rhinitis & initial cold', 'Hay fever & allergic rhinorrhea', 'Laryngeal tickling cough holding throat'],
      keynotes: ['Acrid nasal discharge excoriates upper lip and nostrils', 'Bland profuse lacrimation (opposite of Euphrasia)', 'Marked relief in open fresh air and cold rooms'],
      mindEmotional: 'Anxious from painful laryngeal cough, drowsy with coryza.',
      modalitiesBetter: ['Open cool fresh air', 'Cold unheated rooms'],
      modalitiesWorse: ['Warm stuffy room', 'Toward evening', 'Damp weather'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. Acute: 3–5 pellets every 1–2 hours.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Upper Respiratory Tract & Nose', 'Eyes', 'Larynx'],
      differentialRemedies: ['Euphrasia (acrid tears, bland coryza)', 'Arsenicum album', 'Sabadilla'],
      searchKeywords: ['onion', 'coryza', 'runny nose', 'hay fever', 'sneezing', 'lacrimation']
    },
    es: { commonName: 'Cebolla común' },
    fr: { commonName: 'Oignon' },
    el: { commonName: 'Κρεμμύδι' },
    it: { commonName: 'Cipolla rossa' },
    ru: { commonName: 'Лук репчатый' }
  },
  {
    id: 'aloe-socotrina',
    latinName: 'Aloe socotrina',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Echte Aloe',
      origin: 'Eingedickter Saft der Blätter von Aloe socotrina (Asphodelaceae).',
      essence: 'Unsicherheit des Afterschließmuskels: stürmischer morgendlicher Drang zum Stuhlgang, treibt um 5 Uhr aus dem Bett mit Furcht vor unwillkürlichem Stuhlabgang bei Blähungen.',
      mainIndications: ['Stuhlzwang & Durchfall morgens (5:00 Uhr)', 'Hämorrhoiden wie Weintrauben, heiß und blutend', 'Pfortaderstauung mit Völlegefühl im Bauch'],
      keynotes: ['Plötzlicher, unhaltbarer Stuhldrang frühmorgens', 'Gefühl von Unsicherheit im Schließmuskel beim Windeabgang', 'Hämorrhoiden bessern sich durch kaltes Wasser'],
      mindEmotional: 'Unlustig, mürrisch bei feuchtem Wetter, unzufrieden.',
      modalitiesBetter: ['Kaltes Wasser & kühle Waschungen', 'Kühles Wetter'],
      modalitiesWorse: ['Frühmorgens (5:00 Uhr)', 'Nach dem Essen/Trinken', 'Hitze'],
      potenciesAndDosage: 'D6 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Dickdarm & Rektum', 'Pfortaderkreislauf', 'Hämorrhoidalvenen'],
      differentialRemedies: ['Sulphur (5 Uhr Durchfall)', 'Podophyllum', 'Nux vomica'],
      searchKeywords: ['aloe', 'durchfall', 'hämorrhoiden', 'schließmuskel', 'morgens']
    },
    en: {
      commonName: 'Socotrine Aloe',
      origin: 'Gum / inspissated juice of Aloe socotrina (Asphodelaceae).',
      essence: 'Insecurity of the anal sphincter: urgent morning diarrhea driving out of bed at 5:00 AM with fear of stool escaping while passing flatus.',
      mainIndications: ['Urgent morning diarrhea at 5:00 AM', 'Hemorrhoids protruding like bunches of grapes', 'Portal congestion & heavy abdominal fullness'],
      keynotes: ['Sudden irresistible urge to stool upon waking', 'Sensation of complete weakness in anal sphincter', 'Hemorrhoids relieved by cold water bathing'],
      mindEmotional: 'Ill-humored, disinclined to mental labor, peevish.',
      modalitiesBetter: ['Cold water applications', 'Cool open weather'],
      modalitiesWorse: ['Early morning (5 AM)', 'Immediately after eating or drinking', 'Heat'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Colon & Rectum', 'Portal Venous System', 'Hemorrhoidal Plexus'],
      differentialRemedies: ['Sulphur (5 AM diarrhea)', 'Podophyllum', 'Nux vomica'],
      searchKeywords: ['aloe', 'morning diarrhea', 'hemorrhoids', 'sphincter', 'flatus']
    },
    es: { commonName: 'Áloe socotrino' },
    fr: { commonName: 'Aloès' },
    el: { commonName: 'Αλόη' },
    it: { commonName: 'Aloe del Socotra' },
    ru: { commonName: 'Алоэ сокотринское' }
  },
  {
    id: 'alumina',
    latinName: 'Alumina',
    categoryKey: 'mineral',
    importanceTier: 2,
    de: {
      commonName: 'Tonerde / Aluminiumoxid',
      origin: 'Reines Aluminiumoxid (Al2O3).',
      essence: 'Extreme Schleimhauttrockenheit und motorische Trägheit: selbst weicher Stuhl erfordert gewaltiges Pressen; Verwirrung der Identität.',
      mainIndications: ['Atonische Obstipation (selbst weicher Stuhl geht schwer ab)', 'Trockene juckende Haut & Ekzeme im Winter', 'Geistige Verlangsamung & Identitätsverwirrung'],
      keynotes: ['Kein Stuhldrang bis riesige Ansammlung vorliegt', 'Völliger Mangel an Schleimhautabsonderung (trockene Nase, trockener Rachen)', 'Verlangen nach unverdaulichen Dingen (Kreide, Holzkohle, roher Reis)'],
      mindEmotional: 'Zeit vergeht unerträglich langsam, Verwirrung über die eigene Identität.',
      modalitiesBetter: ['Im Freien', 'Nach mäßigem Essen'],
      modalitiesWorse: ['Kälte & Winterwetter', 'Kartoffeln', 'Am Morgen nach dem Aufwachen'],
      potenciesAndDosage: 'D6, D12, C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Nervensystem', 'Schleimhäute & Rektum', 'Haut'],
      differentialRemedies: ['Bryonia', 'Plumbum', 'Graphites', 'Silicea'],
      searchKeywords: ['tonerde', 'verstopfung', 'trockenheit', 'pressen', 'kartoffeln', 'zeit']
    },
    en: {
      commonName: 'Pure Clay / Aluminum Oxide',
      origin: 'Pure aluminum oxide.',
      essence: 'Severe mucous membrane dryness and motor paresis: even soft stool requires violent straining; time passes too slowly; identity confusion.',
      mainIndications: ['Atonic constipation (straining even for soft stool)', 'Dry itching skin & winter eczemas', 'Mental slowness and alienated identity'],
      keynotes: ['No desire for stool until large accumulation', 'Extreme dryness of mucous surfaces (throat, rectum, skin)', 'Craving for inedible items (chalk, dry rice, coal)'],
      mindEmotional: 'Time passes too slowly, confused sense of personal identity.',
      modalitiesBetter: ['Open air', 'After mild eating'],
      modalitiesWorse: ['Cold winter days', 'Potatoes', 'Morning upon waking'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Nervous System & Spinal Cord', 'Mucous Membranes & Rectum', 'Skin'],
      differentialRemedies: ['Bryonia', 'Plumbum', 'Graphites', 'Silicea'],
      searchKeywords: ['alumina', 'constipation', 'dryness', 'straining', 'potatoes', 'time slow']
    },
    es: { commonName: 'Alúmina / Óxido de aluminio' },
    fr: { commonName: 'Alumine' },
    el: { commonName: 'Αλουμίνα' },
    it: { commonName: 'Allumina' },
    ru: { commonName: 'Алюмина / Окись алюминия' }
  },
  {
    id: 'ambra-grisea',
    latinName: 'Ambra grisea',
    categoryKey: 'animal',
    importanceTier: 2,
    de: {
      commonName: 'Grauer Amber',
      origin: 'Darmsekret des Pottwals (Physeter macrocephalus).',
      essence: 'Extreme Schüchternheit und Verlegenheit in Gegenwart anderer Menschen: kann in Anwesenheit Dritter weder urinieren noch Stuhlgang verrichten.',
      mainIndications: ['Nervöse Schlaflosigkeit durch Grübeln & Überarbeitung', 'Hemmung von Blasen- und Darmentleerung in Gesellschaft', 'Krampfhafter Husten bei Anwesenheit von Fremden'],
      keynotes: ['Kann keinen Stuhlgang haben, wenn jemand im Zimmer oder in der Nähe ist', 'Musik verschlimmert und treibt zu Tränen', 'Vorzeitiges Altern und Gedächtnisschwäche bei Senioren'],
      mindEmotional: 'Scheu, zieht sich zurück, errötet leicht, verzweifelt.',
      modalitiesBetter: ['An der frischen Luft', 'Nach Aufstehen und Gehen'],
      modalitiesWorse: ['Anwesenheit fremder Personen', 'Musik', 'Morgens im Bett'],
      potenciesAndDosage: 'D6 bis C30. 1-2x täglich 5 Globuli.',
      defaultTagesdosis: '1-2x täglich 5 Globuli',
      sphereOfAction: ['Nervensystem & Psyche', 'Kreislauf & Herz'],
      differentialRemedies: ['Natrium muriaticum', 'Ignatia', 'Baryta carbonica'],
      searchKeywords: ['amber', 'schüchternheit', 'husten', 'fremde', 'musik', 'senioren']
    },
    en: {
      commonName: 'Ambergris',
      origin: 'Intestinal concretion of the Sperm Whale (Physeter macrocephalus).',
      essence: 'Extreme bashfulness and embarrassment in the presence of others: cannot pass stool or urinate if anyone is nearby; music brings weeping.',
      mainIndications: ['Nervous insomnia from business worry & grief', 'Inability to evacuate bowel or bladder in company', 'Spasmodic cough triggered by presence of strangers'],
      keynotes: ['Cannot urinate or defecate if others are present', 'Music aggravates and brings tears', 'Premature senility and forgetfulness in the elderly'],
      mindEmotional: 'Extremely bashful, shrinks from conversation, blushful.',
      modalitiesBetter: ['Open air', 'Rising and walking in the room'],
      modalitiesWorse: ['Presence of strangers', 'Music', 'Morning in bed'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 1-2 times daily 5 pellets.',
      defaultTagesdosis: '1-2 times daily 5 pellets',
      sphereOfAction: ['Central Nervous System & Mind', 'Cardiovascular System'],
      differentialRemedies: ['Natrium muriaticum', 'Ignatia', 'Baryta carbonica'],
      searchKeywords: ['ambergris', 'bashfulness', 'cough', 'strangers', 'music', 'elderly']
    },
    es: { commonName: 'Ámbar gris' },
    fr: { commonName: 'Ambre gris' },
    el: { commonName: 'Άμβρα' },
    it: { commonName: 'Ambra grigia' },
    ru: { commonName: 'Амбра гризеа' }
  },
  {
    id: 'ammonium-carbonicum',
    latinName: 'Ammonium carbonicum',
    categoryKey: 'mineral',
    importanceTier: 2,
    de: {
      commonName: 'Hirschhornsalz / Ammoniumcarbonat',
      origin: 'Reines Ammoniumcarbonat.',
      essence: 'Nachtverstopfte Nase bei Kindern (erwachen nach Luft schnappend), hämorrhagische Diathese und Neigung zu Ohnmacht; Abneigung gegen Waschen.',
      mainIndications: ['Nase nachts völlig verstopft (atmet durch den Mund)', 'Herzschwäche mit Lungenödem & Zyanose', 'Nasenbluten beim Waschen des Gesichts'],
      keynotes: ['Nase nachts so verstopft, dass das Kind erstickend aufwacht', 'Blut ist dunkel, flüssig und gerinnt kaum', 'Große Abneigung gegen Wasser und Waschen'],
      mindEmotional: 'Verstimmt, mürrisch bei feuchtem Wetter, unkonzentriert.',
      modalitiesBetter: ['Trockenes warmes Wetter', 'Liegen auf der schmerzhaften Seite'],
      modalitiesWorse: ['Kaltes feuchtes Wetter', 'Waschen', 'Zwischen 3 und 4 Uhr morgens'],
      potenciesAndDosage: 'D6 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Atmungsorgane & Nase', 'Herz & Kreislauf', 'Blut'],
      differentialRemedies: ['Sambucus nigra', 'Carbo vegetabilis', 'Antimonium tartaricum'],
      searchKeywords: ['hirschhornsalz', 'nase verstopft', 'atmen', 'ohnmacht', 'waschen']
    },
    en: {
      commonName: "Carbonate of Ammonia / Baker's Salt",
      origin: 'Pure ammonium carbonate.',
      essence: 'Nocturnal nasal blockage in children (waking gasping for air), hemorrhagic diathesis, and syncope; strong aversion to washing.',
      mainIndications: ['Stoppage of nose at night (must breathe through mouth)', 'Cardiac weakness with pulmonary congestion', 'Epistaxis when washing the face'],
      keynotes: ['Nose stopped up at night, starts up gasping for breath', 'Blood is dark, fluid, non-coagulating', 'Great dread of water and washing'],
      mindEmotional: 'Gloomy, ill-humored in stormy wet weather, uncollected.',
      modalitiesBetter: ['Dry warm weather', 'Lying on painful side'],
      modalitiesWorse: ['Cold wet weather', 'Washing with water', '3:00 to 4:00 AM'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Respiratory System & Nasal Passages', 'Heart & Circulation', 'Blood'],
      differentialRemedies: ['Sambucus nigra', 'Carbo vegetabilis', 'Antimonium tartaricum'],
      searchKeywords: ['ammonium carbonate', 'blocked nose', 'breathing', 'fainting', 'washing aversion']
    },
    es: { commonName: 'Carbonato de amonio' },
    fr: { commonName: 'Carbonate d’ammonium' },
    el: { commonName: 'Ανθρακικό αμμώνιο' },
    it: { commonName: 'Carbonato di ammonio' },
    ru: { commonName: 'Углекислый аммоний' }
  },
  {
    id: 'anacardium-orientale',
    latinName: 'Anacardium orientale',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Elefantenlaus / Semecarpus anacardium',
      origin: 'Getrocknete Früchte der Elefantenlaus (Anacardiaceae).',
      essence: 'Gefühl einer inneren Spaltung (Engel und Teufel auf der Schulter), Fluchdrang und Magenbeschwerden, die sich vorübergehend durch Essen bessern.',
      mainIndications: ['Magenschmerzen, die durch Essen gebessert werden', 'Prüfungsangst & plötzlicher Gedächtnisverlust', 'Zwanghafte Gedanken & Impuls zu fluchen'],
      keynotes: ['Alle Beschwerden (Magen, Kopf) bessern sich prompt beim Essen', 'Gefühl wie ein Pfropfen oder Band um Körperteile', 'Spaltung des Willens: Streit zweier innerer Stimmen'],
      mindEmotional: 'Neigung zu fluchen und zu schimpfen, misstrauisch, grausam, mangelndes Selbstvertrauen.',
      modalitiesBetter: ['Beim und nach dem Essen', 'Durch Wärmeanwendung'],
      modalitiesWorse: ['Auf nüchternen Magen', 'Geistige Anstrengung', 'Wut'],
      potenciesAndDosage: 'D6, D12, C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Gehirn & Psyche', 'Magen-Darm-Trakt', 'Haut'],
      differentialRemedies: ['Nux vomica', 'Ignatia', 'Lycopodium', 'Medorrhinum'],
      searchKeywords: ['elefantenlaus', 'fluchen', 'spaltung', 'magen', 'besser durch essen', 'gedächtnis']
    },
    en: {
      commonName: 'Marking Nut',
      origin: 'Dried fruit of Semecarpus anacardium (Anacardiaceae).',
      essence: 'Inner duality (conflict between good and evil angel), impulse to curse, and gastric distress temporarily relieved by eating.',
      mainIndications: ['Gastric ulcers & pain promptly relieved by food', 'Sudden memory loss before examinations', 'Obsessive impulses and profanity'],
      keynotes: ['All symptoms (gastric, cephalic) relieved during eating', 'Plug-like or hoop-like constriction sensations', 'Illusion of having two conflicting wills'],
      mindEmotional: 'Irresistible impulse to curse and swear, suspicious, cruel, lack of self-confidence.',
      modalitiesBetter: ['While eating & after meals', 'Warmth'],
      modalitiesWorse: ['Fasting / empty stomach', 'Mental exertion', 'Anger'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Mind & Brain', 'Gastrointestinal Tract', 'Skin'],
      differentialRemedies: ['Nux vomica', 'Ignatia', 'Lycopodium', 'Medorrhinum'],
      searchKeywords: ['marking nut', 'swearing', 'duality', 'stomach', 'eating better', 'memory']
    },
    es: { commonName: 'Anacardo oriental' },
    fr: { commonName: 'Anacardier oriental' },
    el: { commonName: 'Ανακάρδιο' },
    it: { commonName: 'Anacardio orientale' },
    ru: { commonName: 'Анакардиум / Болотный орех' }
  },
  {
    id: 'antimonium-crudum',
    latinName: 'Antimonium crudum',
    categoryKey: 'mineral',
    importanceTier: 2,
    de: {
      commonName: 'Schwarzer Spießglanz / Grauspießglanz',
      origin: 'Natürliches Antimontrisulfid (Sb2S3).',
      essence: 'Dick milchweiß belegte Zunge wie eine Schneedecke, Magenverstimmung nach Überessen und große Reizbarkeit: verträgt kein Berühren oder Angesehenwerden.',
      mainIndications: ['Magenverstimmung & Dyspepsie nach Diätfehlern', 'Verhornte Warzen & Fußsohlenschwielen', 'Reizbare Kinder (wollen nicht berührt werden)'],
      keynotes: ['Zunge schneeweiß belegt', 'Magenschmerzen nach zu vielem Essen oder sauren Speisen', 'Kinder schreien und weinen, sobald man sie nur ansieht'],
      mindEmotional: 'Sentimental im Mondschein, schmollend, mürrisch, reizbar.',
      modalitiesBetter: ['An der frischen Luft', 'Nach Ruhe'],
      modalitiesWorse: ['Hitze & Strahlungshitze des Ofens', 'Kaltes Baden', 'Überessen'],
      potenciesAndDosage: 'D6 bis C30. 2x täglich 5 Globuli.',
      defaultTagesdosis: '2x täglich 5 Globuli',
      sphereOfAction: ['Magen-Darm-Kanal', 'Zunge & Schleimhäute', 'Haut & Nägel'],
      differentialRemedies: ['Antimonium tartaricum', 'Bryonia', 'Pulsatilla', 'Ipecacuanha'],
      searchKeywords: ['spießglanz', 'weiße zunge', 'überessen', 'schwielen', 'berührung', 'magen']
    },
    en: {
      commonName: 'Black Antimony',
      origin: 'Native antimony trisulfide (Sb2S3).',
      essence: 'Thick milky-white coated tongue like fresh snow, gastric distress after overeating, and intense irritability: cannot bear being touched or looked at.',
      mainIndications: ['Indigestion & gastric catarrh after dietary overload', 'Thick horny warts & painful callosities on soles', 'Irritable fretful children intolerant of being looked at'],
      keynotes: ['Thick, milky-white coating on tongue', 'Gastric distress after pastry, sour wine or sweets', 'Children scream and cry if touched or even looked at'],
      mindEmotional: 'Sentimental mood in moonlight, peevish, sullen, sulky.',
      modalitiesBetter: ['Open fresh air', 'Rest'],
      modalitiesWorse: ['Heat of sun or radiant furnace', 'Cold bathing', 'Overeating'],
      potenciesAndDosage: 'D6 to C30 / 6C, 30C. 2 times daily 5 pellets.',
      defaultTagesdosis: '2 times daily 5 pellets',
      sphereOfAction: ['Gastrointestinal Canal', 'Tongue & Mucosa', 'Skin & Nails'],
      differentialRemedies: ['Antimonium tartaricum', 'Bryonia', 'Pulsatilla', 'Ipecacuanha'],
      searchKeywords: ['black antimony', 'white tongue', 'indigestion', 'warts', 'touch aversion']
    },
    es: { commonName: 'Sulfuro negro de antimonio' },
    fr: { commonName: 'Antimoine brut' },
    el: { commonName: 'Αντιμόνιο' },
    it: { commonName: 'Antimonio crudo' },
    ru: { commonName: 'Антимониум крудум / Трехсернистая сурьма' }
  },
  {
    id: 'antimonium-tartaricum',
    latinName: 'Antimonium tartaricum',
    categoryKey: 'mineral',
    importanceTier: 1,
    de: {
      commonName: 'Brechweinstein / Tartarus emeticus',
      origin: 'Kaliumantimonyltartrat.',
      essence: 'Rasselnder Schleimhusten mit viel Schleim in den Bronchien, der aus Kraftlosigkeit nicht abgehustet werden kann; Zyanose, Atemnot und Erstickungsgefahr.',
      mainIndications: ['Bronchitis & Bronchiolitis bei Säuglingen und Senioren', 'Lungenemphysem & Lungenödem mit feuchtem Rasseln', 'Übelkeit mit kühlem Schweiß und Erleichterung durch Erbrechen'],
      keynotes: ['Lautes, grobblasiges Rasseln in den Lungen ohne Auswurf', 'Zu schwach, um den Schleim heraufzubringen', 'Erstickungsgefühl: muss sich im Bett aufsetzen'],
      mindEmotional: 'Mürrisch, weinerlich, schläfrig, will in Ruhe gelassen werden.',
      modalitiesBetter: ['Aufrechtes Sitzen', 'Nach dem Auswerfen'],
      modalitiesWorse: ['Liegen', 'Warme Zimmer', 'Nachts und am frühen Morgen'],
      potenciesAndDosage: 'D6, D12, C30. Im Akutfall D6 alle 30–60 Min.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Lunge & Bronchien', 'Herz & Kreislauf', 'Magen'],
      differentialRemedies: ['Ipecacuanha', 'Carbo vegetabilis', 'Hepar sulfuris'],
      searchKeywords: ['brechweinstein', 'rasseln', 'schleim', 'bronchitis', 'erstickungsnot', 'husten']
    },
    en: {
      commonName: 'Tartar Emetic',
      origin: 'Potassium antimony tartrate.',
      essence: 'Loud rattling cough with chest filled with mucous which patient lacks the physical strength to expectorate; cyanosis, dyspnea, and drowsiness.',
      mainIndications: ['Bronchitis & capillary bronchiolitis in infants & aged', 'Pulmonary edema & asthma with wet coarse rattling', 'Nausea with cold sweat relieved by vomiting'],
      keynotes: ['Loud rattling of mucus in bronchial tubes without expectoration', 'Profound weakness: cannot raise the mucus', 'Suffocation compels patient to sit erect in bed'],
      mindEmotional: 'Peevish, whining, drowsy, does not want to be disturbed.',
      modalitiesBetter: ['Sitting upright', 'After vomiting or expectorating'],
      modalitiesWorse: ['Lying down', 'Warm rooms', 'Night & early morning'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. Acute: 3–5 pellets every 30–60 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Lungs & Bronchi', 'Heart & Circulation', 'Stomach'],
      differentialRemedies: ['Ipecacuanha', 'Carbo vegetabilis', 'Hepar sulfuris'],
      searchKeywords: ['tartar emetic', 'rattling', 'mucus', 'bronchitis', 'suffocation', 'cough']
    },
    es: { commonName: 'Tártaro emético' },
    fr: { commonName: 'Tartre émétique' },
    el: { commonName: 'Εμετικός τρυγικός' },
    it: { commonName: 'Tartaro emetico' },
    ru: { commonName: 'Рвотный камень' }
  },
  {
    id: 'apis-mellifica',
    latinName: 'Apis mellifica',
    categoryKey: 'animal',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Honigbiene',
      origin: 'Ganze weibliche Honigbiene mit Giftblase (Apidae).',
      essence: 'Plötzliche, heiße, rosarote Ödeme und Schwellungen mit brennenden und stechenden Schmerzen (wie Bienenstiche), durstlos und extreme Besserung durch Kälte.',
      mainIndications: ['Insektenstiche & akute allergische Schwellungen (Urtikaria, Quincke-Ödem)', 'Gelenkentzündungen mit heißer Schwellung (Hydrops)', 'Mandelentzündung mit ödematösem Zäpfchen (wie ein Wassersack)', 'Eierstockzysten & Zystitis mit Stechen beim Urinieren'],
      keynotes: ['Brennende, stechende Schmerzen wie glühende Nadeln', 'Völlige Durstlosigkeit trotz Fieber und Hitze', 'Ausgeprägte Besserung durch eiskalte Umschläge', 'Große Berührungsempfindlichkeit der Schwellung'],
      mindEmotional: 'Reizbar, weinerlich, eifersüchtig, lässt Gegenstände aus ungeschickten Händen fallen.',
      modalitiesBetter: ['Eiskalte Umschläge & Kaltwasseranwendungen', 'An der kühlen frischen Luft', 'Entblößen'],
      modalitiesWorse: ['Wärme in jeder Form (warmes Zimmer, warme Bäder)', 'Berührung & Druck', 'Am Nachmittag (16:00 - 18:00 Uhr)'],
      potenciesAndDosage: 'Akut: D6, D12, C30. Bei Insektenstichen/Ödemen C30: 3–5 Globuli alle 15–30 Minuten.',
      defaultTagesdosis: '3–4 Gaben à 3–5 Globuli',
      sphereOfAction: ['Haut & Bindegewebe', 'Schleimhäute & Urogenitaltrakt', 'Gelenke & seröse Häute'],
      differentialRemedies: ['Arnica (Trauma, Muskeln)', 'Belladonna (heiß, rot, schwitzend)', 'Cantharis (Brennen beim Wasserlassen)', 'Urtica urens (Brennen/Jucken)'],
      searchKeywords: ['insektenstich', 'biene', 'schwellung', 'ödem', 'brennen', 'stechen', 'durstlos', 'kältebesserung', 'allergie', 'nesselsucht']
    },
    en: {
      commonName: 'Honeybee',
      origin: 'Whole female honeybee with poison sac (Apidae).',
      essence: 'Rapidly developing rosy-pink edematous swellings with stinging, burning pains like bee stings; absolute lack of thirst and marked relief from icy cold applications.',
      mainIndications: ['Insect stings, hives, and acute angioedema (Quincke edema)', 'Inflammatory joint effusion with hot swelling', 'Tonsillitis with bag-like edematous uvula', 'Ovarian cysts & acute cystitis with stinging urination'],
      keynotes: ['Stinging, burning pains like red-hot needles', 'Complete thirstlessness despite high fever & heat', 'Dramatic relief from ice-cold compresses', 'Extreme sensitivity to slightest touch on swelling'],
      mindEmotional: 'Jealous, irritable, tearful, drops things from clumsy awkward hands.',
      modalitiesBetter: ['Ice-cold compresses & cold washing', 'Open cool fresh air', 'Uncovering'],
      modalitiesWorse: ['Heat in any form (warm rooms, warm baths)', 'Touch & pressure', 'Afternoon (4:00 - 6:00 PM)'],
      potenciesAndDosage: 'Acute: D6, D12, C30. For stings C30: 3–5 pellets every 15–30 min.',
      defaultTagesdosis: '3–4 doses of 3–5 pellets',
      sphereOfAction: ['Skin & Subcutaneous Tissue', 'Mucous Membranes & Urinary Tract', 'Joints & Serous Membranes'],
      differentialRemedies: ['Arnica (bruise, trauma)', 'Belladonna (red, hot, sweating)', 'Cantharis (burning urination)', 'Urtica urens (burning/stinging)'],
      searchKeywords: ['honeybee', 'bee sting', 'edema', 'swelling', 'stinging', 'thirstless', 'cold better', 'urticaria', 'allergy']
    },
    es: { commonName: 'Abeja melífera' },
    fr: { commonName: 'Abeille' },
    el: { commonName: 'Μέλισσα' },
    it: { commonName: 'Ape mellifica' },
    ru: { commonName: 'Пчела медоносная' }
  },
  {
    id: 'argentum-nitricum',
    latinName: 'Argentum nitricum',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Höllenstein / Silbernitrat',
      origin: 'Reines Silbernitrat (AgNO3).',
      essence: 'Erwartungsangst, Lampenfieber und Panik vor Terminen mit nervösem Durchfall; Verlangen nach Zucker, der die Beschwerden verschlimmert; Splitterschmerzen im Hals.',
      mainIndications: ['Lampenfieber, Prüfungsangst & Erwartungsneurose', 'Nervöser Reizmagen & Durchfall vor Terminen', 'Pharyngitis & Laryngitis mit Splittergefühl im Hals', 'Klaustrophobie & Höhenangst'],
      keynotes: ['Große Eile und Unruhe, fürchtet zu spät zu kommen', 'Dranghafter Durchfall unmittelbar vor wichtigen Ereignissen', 'Gefühl eines Holzsplitters im Hals beim Schlucken', 'Heißhunger auf Süßigkeiten, verträgt sie aber nicht'],
      mindEmotional: 'Ängstlich, hastig, klaustrophobisch (Angst vor geschlossenen Räumen und Menschenmengen).',
      modalitiesBetter: ['Kühle frische Luft', 'Kaltes Baden', 'Fester Druck'],
      modalitiesWorse: ['Wärme in jeder Form', 'Zucker & Süßigkeiten', 'Vor Ereignissen / Erwartung'],
      potenciesAndDosage: 'D6, D12, C30. Vor Prüfungen C30: 3–5 Globuli am Vorabend und 1 Std. vorher.',
      defaultTagesdosis: '1–2 Gaben à 3–5 Globuli',
      sphereOfAction: ['Zentralnervensystem & Psyche', 'Magen-Darm-Trakt', 'Hals & Kehlkopf'],
      differentialRemedies: ['Gelsemium (Lähmige Prüfungsangst)', 'Ignatia', 'Lycopodium'],
      searchKeywords: ['lampenfieber', 'prüfungsangst', 'durchfall', 'silbernitrat', 'zucker', 'splittergefühl', 'klaustrophobie']
    },
    en: {
      commonName: 'Silver Nitrate',
      origin: 'Pure silver nitrate (AgNO3).',
      essence: 'Anticipatory anxiety, stage fright, and emotional diarrhea before appointments; intense craving for sugar which aggravates; splinter sensation in throat.',
      mainIndications: ['Stage fright & test anxiety with bowel distress', 'Nervous dyspepsia & anticipatory diarrhea', 'Pharyngitis & vocal strain with splinter sensation', 'Claustrophobia & fear of heights'],
      keynotes: ['Great hurry and restlessness, fears being late', 'Urgent watery diarrhea right before critical events', 'Sensation of a wooden splinter lodged in throat', 'Cravings for sweets and sugar which cause flatulence'],
      mindEmotional: 'Impulsive, hurried, fearful of high buildings and enclosed spaces.',
      modalitiesBetter: ['Cool fresh open air', 'Cold bathing', 'Firm pressure'],
      modalitiesWorse: ['Heat & warm rooms', 'Sugar & sweets', 'Anticipation & emotional stress'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. For stage fright C30: 3–5 pellets 1 hour before event.',
      defaultTagesdosis: '1–2 doses of 3–5 pellets',
      sphereOfAction: ['Nervous System & Mind', 'Gastrointestinal Canal', 'Throat & Larynx'],
      differentialRemedies: ['Gelsemium (paralyzing stage fright)', 'Ignatia', 'Lycopodium'],
      searchKeywords: ['silver nitrate', 'stage fright', 'anticipation', 'diarrhea', 'sugar craving', 'splinter throat', 'claustrophobia']
    },
    es: { commonName: 'Nitrato de plata' },
    fr: { commonName: 'Nitrate d’argent' },
    el: { commonName: 'Νιτρικός άργυρος' },
    it: { commonName: 'Nitrato d’argento' },
    ru: { commonName: 'Азотнокислое серебро / Ляпис' }
  },
  {
    id: 'arnica-montana',
    latinName: 'Arnica montana',
    categoryKey: 'plant',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Bergwohlverleih / Echte Arnika',
      origin: 'Getrockneter Wurzelstock der echten Arnika (Asteraceae).',
      essence: 'Das Hauptmittel für alle Traumen, stumpfe Verletzungen, Muskelkater und Schock. Der Patient behauptet trotz schwerer Verletzung, es fehle ihm nichts, und empfindet das Bett als zu hart.',
      mainIndications: ['Prellungen, Quetschungen, Hämatome & Blutergüsse', 'Postoperative Wundbehandlung & Zahnextraktionen', 'Muskelkater nach extremer körperlicher Anstrengung', 'Schlaganfall & Gehirnerschütterung (zur Resorption von Extravasaten)', 'Überlastung des Herzens bei Sportlern'],
      keynotes: ['Zerschlagenheitsgefühl am ganzen Körper', 'Das Bett fühlt sich überall zu hart an (sucht ständig neue Position)', 'Patient weist den Arzt ab: „Mir fehlt nichts, ich bin gesund“', 'Heißer Kopf bei kaltem Körper'],
      mindEmotional: 'Mürrisch, will in Ruhe gelassen werden, fürchtet Berührung und Annäherung.',
      modalitiesBetter: ['Liegen mit tief gelagertem Kopf', 'Ruhe'],
      modalitiesWorse: ['Jede Berührung & Erschütterung', 'Bewegung', 'Feuchte Kälte'],
      potenciesAndDosage: 'Akut: D6, D12, C30, C200. Nach Verletzung sofort C30: 3–5 Globuli, bei Bedarf wiederholen.',
      defaultTagesdosis: '1–2 Gaben à 3–5 Globuli',
      sphereOfAction: ['Blutgefäße & Kapillaren', 'Muskulatur & Weichteile', 'Zentralnervensystem'],
      differentialRemedies: ['Hypericum (Nervenverletzung)', 'Rhus tox (Sehnen/Bänder)', 'Ruta (Knochenhaut)', 'Bellis perennis (tiefe Gewebstraumen)'],
      searchKeywords: ['unfall', 'trauma', 'bluterguss', 'hämatom', 'prellung', 'muskelkater', 'verletzung', 'operation', 'zerschlagen']
    },
    en: {
      commonName: 'Mountain Daisy / Leopard’s Bane',
      origin: 'Dried rhizome and whole blooming plant of Arnica montana (Asteraceae).',
      essence: 'The supreme trauma, blunt injury, and muscle soreness remedy. The patient insists they are perfectly well despite severe injury, and complains the bed is too hard.',
      mainIndications: ['Contusions, blunt trauma, hematomas, and bruising', 'Postoperative care and dental extractions', 'Muscle strain & soreness from extreme overexertion', 'Concussion and cerebral trauma to promote extravasate resorption', 'Cardiac strain in athletes'],
      keynotes: ['Bruised, sore, aching feeling throughout the body', 'Bed feels too hard everywhere, tosses to find a softer spot', 'Sends the physician away: "I am fine, there is nothing wrong with me"', 'Hot head with cold body and limbs'],
      mindEmotional: 'Irritable, wants to be left alone, fears being touched or approached.',
      modalitiesBetter: ['Lying down with head low', 'Absolute rest'],
      modalitiesWorse: ['Slightest touch & jar', 'Motion', 'Damp cold'],
      potenciesAndDosage: 'Acute: D6, D12, C30, C200. Immediately after trauma C30: 3–5 pellets.',
      defaultTagesdosis: '1–2 doses of 3–5 pellets',
      sphereOfAction: ['Blood Vessels & Capillaries', 'Muscles & Soft Tissues', 'Central Nervous System'],
      differentialRemedies: ['Hypericum (nerve trauma)', 'Rhus tox (strains)', 'Ruta (periosteum)', 'Bellis perennis (deep pelvic trauma)'],
      searchKeywords: ['arnica', 'injury', 'trauma', 'bruise', 'hematoma', 'soreness', 'sprain', 'postoperative', 'concussion']
    },
    es: { commonName: 'Árnica montañesa' },
    fr: { commonName: 'Arnica des montagnes' },
    el: { commonName: 'Άρνικα' },
    it: { commonName: 'Arnica montana' },
    ru: { commonName: 'Арника горная' }
  },
  {
    id: 'arsenicum-album',
    latinName: 'Arsenicum album',
    categoryKey: 'mineral',
    isPolychrest: true,
    importanceTier: 1,
    de: {
      commonName: 'Weißer Arsenik / Arsentrioxid',
      origin: 'Reines Arsentrioxid (As2O3).',
      essence: 'Brennende Schmerzen wie glühende Kohlen, die paradoxerweise durch Hitze und heiße Umschläge gebessert werden; panische Todesangst, akute Ruhelosigkeit, Verschlimmerung zwischen 01:00 und 03:00 Uhr nachts und Durst auf häufige kleine Schlucke.',
      mainIndications: ['Gastroenteritis & Lebensmittelvergiftung (Erbrechen & Durchfall)', 'Asthma bronchiale (Erwachen zwischen 1 und 3 Uhr nachts)', 'Brennende Ekzeme & Psoriasis mit feiner Schuppung', 'Panikattacken mit Todesangst & Ruhelosigkeit', 'Akute Erschöpfung nach Infekten'],
      keynotes: ['Brennende Schmerzen werden durch Wärme gebessert', 'Verschlimmerungszeit: 01:00 bis 03:00 Uhr nachts', 'Große körperliche Schwäche bei extremer motorischer Unruhe', 'Durst auf kleine Mengen kaltes Wasser in kurzen Abständen', 'Pedantische Ordentlichkeit und Reinlichkeit'],
      mindEmotional: 'Große Todesangst, glaubt Rettung sei unmöglich. Äußerst ruhelos, wandert von Bett zu Bett. Perfektionistisch, anspruchsvoll.',
      modalitiesBetter: ['Hitze in jeder Form (heiße Bäder, Wärmflasche)', 'Warme Getränke', 'Hochgelagerter Kopf'],
      modalitiesWorse: ['Kälte & feuchte Luft', 'Zwischen 01:00 und 03:00 Uhr nachts', 'Kaltes Essen & Eis'],
      potenciesAndDosage: 'D6, D12, C30. Bei Lebensmittelvergiftung C30: 3–5 Globuli alle 30–60 Min.',
      defaultTagesdosis: '1–2 Gaben à 3–5 Globuli',
      sphereOfAction: ['Magen-Darm-Trakt', 'Atmungsorgane', 'Haut', 'Zentralnervensystem & Psyche'],
      differentialRemedies: ['Aconitum (Angst um Mitternacht)', 'Phosphorus (brennend, will kaltes Wasser)', 'Carbo vegetabilis (Kollaps)'],
      searchKeywords: ['lebensmittelvergiftung', 'brennen', 'angst', 'panik', 'durchfall', 'erbrechen', 'wärmebesserung', 'nachtunruhe', 'arsen']
    },
    en: {
      commonName: 'White Arsenic / Arsenic Trioxide',
      origin: 'Pure arsenic trioxide (As2O3).',
      essence: 'Burning pains like red-hot coals paradoxically relieved by heat; intense fear of death, extreme restlessness, aggravation between 1:00 and 3:00 AM, and sipping small amounts of water frequently.',
      mainIndications: ['Gastroenteritis & food poisoning with simultaneous vomiting and diarrhea', 'Asthma attacks waking between 1:00 and 3:00 AM', 'Burning eczema and dry scaly skin eruptions', 'Panic disorders with anguish and fear of death', 'Rapid prostration out of proportion to illness'],
      keynotes: ['Burning pains ameliorated by hot applications', 'Key aggravation time: 1:00 to 3:00 AM', 'Profound prostration coupled with anguish and pacing restlessness', 'Thirst for frequent small sips of water', 'Fastidious cleanliness and need for order'],
      mindEmotional: 'Despairs of recovery, fears death and being left alone. Restlessly moves from bed to chair. Demanding, fastidious.',
      modalitiesBetter: ['Heat in all forms (hot drinks, warm wraps)', 'Elevating head in bed'],
      modalitiesWorse: ['Cold air and cold dampness', 'Midnight to 3:00 AM', 'Cold food and ice cream'],
      potenciesAndDosage: 'D6, D12, C30 / 6C, 30C. For acute food poisoning C30: 3–5 pellets hourly.',
      defaultTagesdosis: '1–2 doses of 3–5 pellets',
      sphereOfAction: ['Gastrointestinal Tract', 'Respiratory Organs', 'Skin', 'Mind & Nervous System'],
      differentialRemedies: ['Aconitum (anxiety around midnight)', 'Phosphorus (craves cold drinks)', 'Carbo vegetabilis (collapse)'],
      searchKeywords: ['arsenic', 'food poisoning', 'burning', 'anxiety', 'panic', 'restlessness', 'heat better', 'vomiting', 'diarrhea']
    },
    es: { commonName: 'Arsénico blanco' },
    fr: { commonName: 'Arsenic blanc' },
    el: { commonName: 'Λευκό αρσενικό' },
    it: { commonName: 'Arsenico bianco' },
    ru: { commonName: 'Мышьяк белый' }
  },
  {
    id: 'arum-triphyllum',
    latinName: 'Arum triphyllum',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Dreiblättriger Zehrwurz / Jack-in-the-Pulpit',
      origin: 'Frische Knolle des Dreiblättrigen Zehrwurzes (Araceae).',
      essence: 'Scharfer, wundmachender Scharlach- und Erkältungsschnupfen; unstillbarer Zwang zum Bohren in der Nase und Abreißen von Lippenhaut bis zum Bluten.',
      mainIndications: ['Sänger- und Rednerheiserkeit', 'Scharlach & Diphtherie mit wundmachendem Ausfluss', 'Zwanghaftes Bohren in Lippen und Nase'],
      keynotes: ['Bohrt ständig in der Nase, bis sie blutet', 'Reißt an den brennenden Lippen, bis sie wund und blutig sind', 'Stimmbruch bei Sängern und Rednern'],
      mindEmotional: 'Unruhig, reizbar, eigensinnig, schreit bei Schmerzen.',
      modalitiesBetter: ['Nach Einsetzen von Schleimfluss'],
      modalitiesWorse: ['Überanstrengung der Stimme', 'Nordwestwind', 'Liegen'],
      potenciesAndDosage: 'D4 bis D12. 3x täglich 5 Globuli.',
      defaultTagesdosis: '3x täglich 5 Globuli',
      sphereOfAction: ['Kehlkopf & Stimmbänder', 'Nase & Lippen', 'Schleimhäute'],
      differentialRemedies: ['Allium cepa', 'Causticum', 'Argentum nitricum'],
      searchKeywords: ['zehrwurz', 'heiserkeit', 'stimme', 'bohren', 'blutige lippen', 'scharlach']
    },
    en: {
      commonName: 'Indian Turnip / Jack-in-the-Pulpit',
      origin: 'Fresh tuber of Arisaema triphyllum (Araceae).',
      essence: 'Acrid excoriating coryza in scarlatina; persistent picking and boring into the nose and lips until they bleed; loss of voice in public speakers.',
      mainIndications: ['Clergyman’s sore throat & vocal fatigue', 'Scarlatina with acrid nasal discharge', 'Compulsive picking at lips and nostrils'],
      keynotes: ['Bores fingers deep into nose until it bleeds', 'Picks at dry cracked lips until raw and bleeding', 'Voice suddenly breaks when trying to sing or speak'],
      mindEmotional: 'Fretful, obstinate, restless, screams with raw pain.',
      modalitiesBetter: ['After establishment of discharge'],
      modalitiesWorse: ['Vocal strain', 'Northwest winds', 'Lying down'],
      potenciesAndDosage: 'D4 to D12 / 6C. 3 times daily 5 pellets.',
      defaultTagesdosis: '3 times daily 5 pellets',
      sphereOfAction: ['Larynx & Vocal Cords', 'Nose & Lips', 'Mucous Membranes'],
      differentialRemedies: ['Allium cepa', 'Causticum', 'Argentum nitricum'],
      searchKeywords: ['indian turnip', 'hoarseness', 'picking lips', 'bleeding nose', 'voice loss']
    },
    es: { commonName: 'Aro tripartito' },
    fr: { commonName: 'Arum d’Amérique' },
    el: { commonName: 'Άρο τρίφυλλο' },
    it: { commonName: 'Aro trifillo' },
    ru: { commonName: 'Арум трифиллум' }
  },
  {
    id: 'aurum-metallicum',
    latinName: 'Aurum metallicum',
    categoryKey: 'mineral',
    importanceTier: 1,
    de: {
      commonName: 'Metallisches Gold',
      origin: 'Reines elementares Blattgold (Au).',
      essence: 'Schwerste suizidale Melancholie, Selbstvorwürfe und Gefühl des Pflichtversagens; nächtliche Knochenschmerzen und Bluthochdruck; Besserung durch klassische Musik.',
      mainIndications: ['Schwere endogene Depressionen & Suizidgefahr', 'Nächtliche Knochenschmerzen (Nekrosen & Karies)', 'Arterielle Hypertonie & Angina pectoris', 'Chronische Sinusitis mit Knochenbeteiligung'],
      keynotes: ['Tiefste Verzweiflung und Sehnsucht nach dem Tod', 'Schmerzen verschlimmern sich dramatisch nachts von Sonnenuntergang bis Sonnenaufgang', 'Musik bessert das seelische Befinden spürbar', 'Gefühl, als stünde das Herz für einen Schlag still'],
      mindEmotional: 'Extreme Selbstvorwürfe, glaubt Pflichten verletzt zu haben, reizbar bei Widerspruch.',
      modalitiesBetter: ['Klassische Musik', 'Im Freien', 'Wärme'],
      modalitiesWorse: ['Nachts (Sonnenuntergang bis Aufgang)', 'Kälte & Winter', 'Geistige Anstrengung'],
      potenciesAndDosage: 'C30, C200, 1M (nur unter fachlicher Aufsicht). 1x wöchentlich 5 Globuli.',
      defaultTagesdosis: '1 Gabe à 5 Globuli',
      sphereOfAction: ['Psyche & Zentralnervensystem', 'Herz-Kreislauf-System', 'Knochen & Periost'],
      differentialRemedies: ['Natrium muriaticum', 'Ignatia', 'Lachesis', 'Platina'],
      searchKeywords: ['gold', 'depression', 'suizid', 'knochenschmerz', 'musik', 'pflichtgefühl', 'bluthochdruck']
    },
    en: {
      commonName: 'Metallic Gold',
      origin: 'Pure elemental gold leaf.',
      essence: 'Profound suicidal melancholia with feelings of worthlessness and failure of duty; boring nocturnal bone pains; hypertension; distinct solace from music.',
      mainIndications: ['Severe suicidal depression & despair', 'Nocturnal boring bone pains & necrosis', 'Hypertension & angina pectoris', 'Chronic destructive sinusitis'],
      keynotes: ['Deepest despair with longing for death by jumping', 'Pains violently aggravate from sunset to sunrise', 'Solace and emotional relief from listening to classical music', 'Sensation as if heart suddenly ceased beating'],
      mindEmotional: 'Self-condemnation, feels neglected duty, explosive anger from slightest contradiction.',
      modalitiesBetter: ['Listening to music', 'Open fresh air', 'Warmth'],
      modalitiesWorse: ['Night (sunset to sunrise)', 'Cold winter months', 'Mental exertion'],
      potenciesAndDosage: 'C30, C200, 1M. 1 dose weekly under professional care.',
      defaultTagesdosis: '1 dose of 5 pellets',
      sphereOfAction: ['Mind & Emotions', 'Heart & Arteries', 'Bones & Periosteum'],
      differentialRemedies: ['Natrium muriaticum', 'Ignatia', 'Lachesis', 'Platina'],
      searchKeywords: ['gold', 'depression', 'suicide', 'bone pain', 'music relief', 'hypertension', 'duty']
    },
    es: { commonName: 'Oro metálico' },
    fr: { commonName: 'Or métallique' },
    el: { commonName: 'Χρυσός' },
    it: { commonName: 'Oro metallico' },
    ru: { commonName: 'Золото металлическое' }
  },
  {
    id: 'avena-sativa',
    latinName: 'Avena sativa',
    categoryKey: 'plant',
    importanceTier: 2,
    de: {
      commonName: 'Echter Hafer',
      origin: 'Frische, zur Blütezeit geerntete oberirdische Teile des Saat-Hafers (Poaceae).',
      essence: 'Nervenstärkungsmittel bei Neurasthenie, nervöser Schlaflosigkeit nach geistiger Überarbeitung und Entwöhnung von Suchtmitteln (Alkohol, Tabak, Morphin).',
      mainIndications: ['Nervöse Erschöpfung nach geistiger Überarbeitung', 'Schlaflosigkeit & nächtliche Unruhe', 'Unterstützung beim Entzug von Beruhigungsmitteln/Nikotin'],
      keynotes: ['Nervöse Schwäche mit Konzentrationsunfähigkeit', 'Schlaflosigkeit bei Geistesarbeitern', 'Zittern der Hände bei Senioren'],
      mindEmotional: 'Müde, apathisch, nervös erschöpft.',
      modalitiesBetter: ['Schlaf', 'Ruhe'],
      modalitiesWorse: ['Geistige Anstrengung', 'Nachtarbeit'],
      potenciesAndDosage: 'Urtinktur (Ø) oder D1 bis D6. 2–3x täglich 10 Tropfen in warmem Wasser.',
      defaultTagesdosis: '2–3x täglich 10 Tropfen',
      sphereOfAction: ['Nervensystem', 'Gehirn', 'Schlafzentrum'],
      differentialRemedies: ['Passiflora', 'Coffea', 'Zincum valerianicum', 'Phosphoricum acidum'],
      searchKeywords: ['hafer', 'nerven', 'schlaf', 'überarbeitung', 'entzug', 'neurasthenie']
    },
    en: {
      commonName: 'Oat',
      origin: 'Fresh blooming aerial parts of the common oat (Poaceae).',
      essence: 'Nerve tonic for neurasthenia, insomnia following mental exhaustion and worry, and withdrawal support from sedatives, alcohol, or tobacco.',
      mainIndications: ['Nervous exhaustion after intellectual strain', 'Insomnia in brain workers', 'Addiction & sedative withdrawal support'],
      keynotes: ['Nervous debility with inability to concentrate', 'Sleeplessness from overworked brain', 'Tremulous weakness in the elderly'],
      mindEmotional: 'Fatigued, listless, depleted brain power.',
      modalitiesBetter: ['Restful sleep', 'Quiet rest'],
      modalitiesWorse: ['Mental exertion', 'Night work'],
      potenciesAndDosage: 'Mother tincture (Q) or 1X to 6X. 10 drops in warm water at bedtime.',
      defaultTagesdosis: '2–3 times daily 10 drops',
      sphereOfAction: ['Central Nervous System', 'Brain', 'Sleep Centers'],
      differentialRemedies: ['Passiflora', 'Coffea', 'Zincum valerianicum', 'Phosphoricum acidum'],
      searchKeywords: ['oat', 'nervous exhaustion', 'insomnia', 'brain fag', 'addiction withdrawal']
    },
    es: { commonName: 'Avena' },
    fr: { commonName: 'Avoine cultivée' },
    el: { commonName: 'Βρώμη' },
    it: { commonName: 'Avena comune' },
    ru: { commonName: 'Овес посевной' }
  }
];

console.log('REMEDIES_PART1_A defined with count:', REMEDIES_PART1_A.length);
