import fs from 'fs';
import path from 'path';

const dbPath = path.resolve('data/medications_db.json');
let existingDb = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
const existingNames = new Set(existingDb.map(m => m.name.toLowerCase().trim()));

function med(name, activeSubstance, category, dosages, packageSizes, intake, sideEffects, interactions, warnings) {
  return {
    name,
    activeSubstance: activeSubstance || name,
    category,
    dosages: dosages || ['Standard'],
    packageSizes: packageSizes || ['N1 (10-20 Stk.)', 'N2 (50 Stk.)', 'N3 (100 Stk.)'],
    commonForms: ['Filmtablette', 'Kapsel'],
    recommendedIntake: intake || '1x täglich unzerkaut mit ausreichend Wasser einnehmen',
    sideEffectsByFrequency: {
      common: sideEffects ? [sideEffects[0], sideEffects[1]].filter(Boolean) : ['Gastrointestinale Beschwerden', 'Müdigkeit'],
      uncommon: sideEffects && sideEffects.length > 2 ? sideEffects.slice(2) : ['Hautreaktionen', 'Kopfschmerzen']
    },
    sideEffects: sideEffects || ['Gastrointestinale Beschwerden', 'Kopfschmerzen', 'Müdigkeit', 'Schwindel'],
    interactions: interactions || ['Alkohol meiden', 'Vorsicht bei Kombination mit anderen dämpfenden oder blutdrucksenkenden Mitteln'],
    warnings: warnings || 'Regelmäßige ärztliche Kontrollen empfohlen.',
    authoritySource: 'BfArM / EMA / Rote Liste Fachinformation',
    fromDatabase: true
  };
}

const catalog = [];

// 6. Pneumologie, Allergie & HNO
const lungs = [
  med('Salbutamol Spray', 'Salbutamol', 'Kurzwirksames Beta-2-Sympathomimetikum (SABA)', ['100 µg/Hub'], ['N1', 'N2'], 'Bei Atemnot 1-2 Hübe inhalieren', ['Tachykardie / Herzklopfen', 'Feinschlägiger Tremor (Zittern der Hände)', 'Kopfschmerzen', 'Hypokaliämie bei Überdosierung'], ['Unselektive Betablocker (antagonisieren Wirkung)', 'Digitalis']),
  med('Berotec (Fenoterol)', 'Fenoterol-Hydrochlorid', 'SABA / Bronchospasmolytikum', ['100 µg/Hub'], ['N1', 'N2'], 'Bei akutem Asthmaanfall 1-2 Hübe', ['Tremor', 'Tachykardie', 'Nervosität'], ['Betablocker']),
  med('Formoterol (Foradil)', 'Formoterol', 'Langwirksames Beta-2-Sympathomimetikum (LABA)', ['12 µg Kapseln / Inhalator'], ['N1', 'N2', 'N3'], '1-2x täglich inhalieren', ['Tremor', 'Palpitationen'], ['Betablocker', 'Theophyllin']),
  med('Salmeterol (Serevent)', 'Salmeterol', 'LABA (12 Stunden Wirkdauer)', ['25 µg/Hub', '50 µg Diskus'], ['N1', 'N2', 'N3'], '2x täglich morgens und abends', ['Kopfschmerzen', 'Tremor'], ['Betablocker']),
  med('Pulmicort (Budesonid Inhalator)', 'Budesonid', 'Inhalatives Kortikoid (ICS)', ['100 µg', '200 µg', '400 µg Turbohaler'], ['N1', 'N2', 'N3'], '1-2x täglich inhalieren, DANACH Mund mit Wasser ausspülen!', ['Oropharyngeale Candidose (Mundsoor)', 'Heiserkeit', 'Hustenreiz'], ['CYP3A4-Hemmer'], 'WICHTIG: Nach jeder Inhalation Mund gründlich ausspülen oder etwas essen!'),
  med('Flutide (Fluticason Inhalator)', 'Fluticasonpropionat', 'ICS (sehr potent)', ['50 µg', '125 µg', '250 µg'], ['N1', 'N2', 'N3'], '2x täglich morgens und abends', ['Mundsoor', 'Heiserkeit'], ['Ritonavir', 'Ketoconazol'], 'Mund nach Inhalation immer ausspülen.'),
  med('Foster (Formoterol / Beclometason)', 'Formoterol/Beclometason', 'Fixkombination LABA + ICS (SMART-Konzept)', ['100/6 µg', '200/6 µg'], ['N1', 'N2', 'N3'], '1-2 Hübe 2x täglich (und bei Bedarf als Reliever)', ['Heiserkeit', 'Tremor', 'Mundsoor'], ['Betablocker']),
  med('Symbicort (Budesonid / Formoterol)', 'Budesonid/Formoterol', 'Kombination ICS + LABA', ['160/4.5 µg', '320/9 µg'], ['N1', 'N2', 'N3'], '1-2x täglich morgens und abends', ['Mundsoor', 'Kopfschmerzen', 'Herzklopfen'], ['Betablocker']),
  med('Viani / Seretide (Fluticason / Salmeterol)', 'Fluticason/Salmeterol', 'Kombination ICS + LABA Diskus', ['100/50 µg', '250/50 µg', '500/50 µg'], ['N1', 'N2', 'N3'], '2x täglich alle 12 Stunden', ['Heiserkeit', 'Kandidose', 'Kopfschmerz'], ['CYP3A4-Inhibitoren']),
  med('Spiriva (Tiotropiumbromid)', 'Tiotropiumbromid', 'Langwirksames Anticholinergikum (LAMA)', ['2.5 µg Respimat', '18 µg HandiHaler'], ['N1', 'N2', 'N3'], '1x täglich zur gleichen Uhrzeit inhalieren', ['Mundtrockenheit (sehr häufig)', 'Harnverhalt (Vorsicht bei Prostatahyperplasie)', 'Obstipation'], ['Andere Anticholinergika']),
  med('Atrovent (Ipratropiumbromid)', 'Ipratropiumbromid', 'Kurzwirksames Anticholinergikum (SAMA)', ['20 µg/Hub'], ['N1', 'N2'], '3-4x täglich 1-2 Hübe', ['Mundtrockenheit', 'Schwindel'], ['Anticholinergika']),
  med('Anoro Ellipta (Umeclidinium / Vilanterol)', 'Umeclidinium/Vilanterol', 'LAMA + LABA (COPD)', ['55/22 µg'], ['N1', 'N2', 'N3'], '1x täglich inhalieren', ['Nasopharyngitis', 'Harnwegsinfektionen', 'Mundtrockenheit'], ['Betablocker']),
  med('Trelegy Ellipta (Fluticason / Umeclidinium / Vilanterol)', 'Fluticason/Umeclidinium/Vilanterol', 'Tripeltherapie ICS + LAMA + LABA', ['92/55/22 µg'], ['N1', 'N2', 'N3'], '1x täglich morgens inhalieren', ['Pneumonie-Risiko bei COPD', 'Mundsoor', 'Dysphonie'], ['CYP3A4-Hemmer']),
  med('Trimbow (Beclometason / Formoterol / Glycopyrronium)', 'Beclometason/Formoterol/Glycopyrronium', 'Tripeltherapie Dosieraerosol', ['87/5/9 µg'], ['N1', 'N2', 'N3'], '2x täglich je 2 Hübe morgens und abends', ['Heiserkeit', 'Mundtrockenheit', 'Pneumonie'], ['Betablocker']),
  med('Singulair (Montelukast)', 'Montelukast', 'Leukotrien-Rezeptorantagonist (LTRA)', ['4 mg', '5 mg', '10 mg'], ['N1', 'N2', 'N3'], '1x täglich abends vor dem Schlafen', ['Neuropsychiatrische Störungen (Alpträume, Schlafstörungen, Depression)', 'Kopfschmerz', 'Bauchschmerz'], ['Phenobarbital', 'Rifampicin'], 'Warnung der FDA/BfArM zu neuropsychiatrischen Ereignissen beachten.'),
  med('Theophyllin', 'Theophyllin retard', 'Methylxanthin / Phosphodiesterase-Hemmer', ['200 mg', '300 mg', '400 mg'], ['N1', 'N2', 'N3'], '1-2x täglich nach den Mahlzeiten', ['Schlafstörungen', 'Tachykardie', 'Tremor', 'Übelkeit/Erbrechen', 'Krampfanfälle bei Überdosierung'], ['Ciprofloxacin (drastischer Theophyllin-Anstieg!)', 'Rauchen (beschleunigt Abbau)'], 'Sehr enge therapeutische Breite (Serumspiegel 8-20 µg/ml überwachen).'),
  med('ACC akut (Acetylcystein)', 'Acetylcystein (NAC)', 'Mukolytikum / Hustenlöser', ['200 mg', '600 mg Brausetabletten'], ['N1', 'N2', 'N3'], '1x täglich morgens in Wasser aufgelöst trinken', ['Magenbeschwerden', 'Sodbrennen', 'Geruch nach Schwefel'], ['Nicht gleichzeitig mit Antitussiva (Sekretstau!)', 'Antibiotika (2h Abstand)'], 'Nicht spätabends einnehmen, um nächtlichen Abhustreiz zu vermeiden.'),
  med('Mucosolvan (Ambroxol)', 'Ambroxol-Hydrochlorid', 'Mukolytikum / Sekretolytikum', ['30 mg', '75 mg retard', 'Saft'], ['N1', 'N2', 'N3'], 'Morgens und mittags nach den Mahlzeiten', ['Magenbeschwerden', 'Übelkeit', 'Geschmacksstörungen'], ['Antitussiva (Sekretstaugefahr)']),
  med('Silomat (Dextromethorphan)', 'Dextromethorphan', 'Zentraler Hustenstiller (Antitussivum)', ['30 mg Kapseln / Saft'], ['N1', 'N2'], 'Bei trockenem Reizhusten zur Nacht', ['Schläfrigkeit', 'Schwindel', 'Gastrointestinale Beschwerden'], ['SSRI / Antidepressiva (Gefahr eines lebensbedrohlichen Serotoninsyndroms!)', 'MAO-Hemmer'], 'Nur bei trockenem, unproduktivem Reizhusten.'),
  med('Capval (Noscapin)', 'Noscapin', 'Nicht-Opioid-Antitussivum', ['Tropfen / Dragees'], ['N1', 'N2'], 'Vor dem Schlafengehen', ['Kopfschmerzen', 'Benommenheit'], ['Warfarin']),
  med('Cetirizin', 'Cetirizindihydrochlorid', 'H1-Antihistaminikum der 2. Generation', ['10 mg Filmtabletten'], ['N1', 'N2', 'N3'], '1x täglich abends mit Flüssigkeit', ['Müdigkeit / Schläfrigkeit (bei ca. 10%)', 'Mundtrockenheit', 'Kopfschmerzen'], ['Alkohol (verstärkte Sedierung)', 'ZNS-Dämpfer']),
  med('Levocetirizin (Xusal)', 'Levocetirizin', 'Reines R-Enantiomer von Cetirizin', ['5 mg'], ['N1', 'N2', 'N3'], '1x täglich abends', ['Geringere Sedierung', 'Kopfschmerz'], ['Alkohol']),
  med('Loratadin', 'Loratadin', 'Nicht-sedierendes H1-Antihistaminikum', ['10 mg'], ['N1', 'N2', 'N3'], '1x täglich morgens oder abends', ['Kopfschmerzen', 'Müdigkeit (selten)', 'Gesteigerter Appetit'], ['CYP3A4-Hemmer']),
  med('Desloratadin (Aerius)', 'Desloratadin', 'Aktiver Metabolit von Loratadin', ['5 mg'], ['N1', 'N2', 'N3'], '1x täglich unabhängig von Mahlzeiten', ['Praktisch keine Sedierung', 'Mundtrockenheit', 'Müdigkeit'], ['Alkohol']),
  med('Bilastin (Bitosen)', 'Bilastin', 'Modernes H1-Antihistaminikum', ['20 mg'], ['N1', 'N2', 'N3'], '1x täglich STRENG NÜCHTERN (1h vor oder 2h nach Essen/Fruchtsaft!)', ['Kopfschmerzen', 'Schläfrigkeit (sehr selten)'], ['Grapefruit- und Fruchtsäfte vermindern Resorption drastisch um 30-50%'], 'Nüchterneinnahme zwingend beachten!'),
  med('Fexofenadin (Telfast)', 'Fexofenadin', 'Nicht-sedierendes Antihistaminikum', ['120 mg', '180 mg'], ['N1', 'N2', 'N3'], '1x täglich vor einer Mahlzeit mit Wasser', ['Kopfschmerzen', 'Schwindel'], ['Aluminium- und magnesiumhaltige Antazida (mind. 2h Abstand)']),
  med('Rupatadin (Urtimed)', 'Rupatadin', 'Antihistaminikum + PAF-Antagonist', ['10 mg'], ['N1', 'N2', 'N3'], '1x täglich', ['Schläfrigkeit', 'Müdigkeit'], ['Grapefruitsaft', 'Ketoconazol']),
  med('Dimetinden (Fenistil)', 'Dimetindenmaleat', 'Klassisches H1-Antihistaminikum (1. Generation)', ['1 mg Dragees', 'Tropfen', 'Gel'], ['N1', 'N2', 'N3'], 'Abends bei allergischem Juckreiz', ['Ausgeprägte Sedierung / Müdigkeit', 'Mundtrockenheit'], ['Alkohol', 'Schlafmittel', 'Anticholinergika']),
  med('Xylometazolin Nasenspray (Otriven)', 'Xylometazolinhydrochlorid', 'Alpha-Sympathomimetikum / Schleimhautabschweller', ['0.05%', '0.1% Nasenspray'], ['N1', 'N2'], '2-3x täglich 1 Sprühstoß pro Nasenloch (MAXIMAL 7 TAGE!)', ['Austrocknung der Nasenschleimhaut', 'Rebound-Schwellung (Privinismus / Rhinitis medicamentosa)', 'Gewöhnungseffekt'], ['MAO-Hemmer', 'Trizyklika (Blutdruckkrisen möglich)'], 'STRENG MAXIMAL 7 TAGE anwenden wegen Gefahr chronischer Abhängigkeit!'),
  med('Nasivin (Oxymetazolin)', 'Oxymetazolinhydrochlorid', 'Abschwellendes Nasenspray', ['0.05% Dosierspray'], ['N1', 'N2'], 'Bis zu 3x täglich 1 Sprühstoß (max. 7 Tage)', ['Rebound-Effekt bei Dauergebrauch'], ['Antidepressiva']),
  med('Nasonex (Mometason Nasenspray)', 'Mometasonfuroat', 'Topisches Glukokortikoid Nasenspray (Heuschnupfen)', ['50 µg/Sprühstoß'], ['N1', 'N2', 'N3'], '1x täglich morgens je 1-2 Sprühstöße pro Nasenloch', ['Nasenbluten (Epistaxis)', 'Kopfschmerzen', 'Nasenreizung'], ['Keine systemischen Interaktionen'], 'Dauertherapie bei allergischer Rhinitis gut verträglich, kein Gewöhnungseffekt.')
];
catalog.push(...lungs);

// 7. ZNS, Neurologie & Psychiatrie
const neuro = [
  med('Citalopram', 'Citalopram-Hydrochlorid', 'SSRI (Antidepressivum)', ['10 mg', '20 mg', '40 mg'], ['N1', 'N2', 'N3'], '1x täglich morgens mit Wasser', ['Übelkeit zu Beginn', 'Schlafstörungen oder Schläfrigkeit', 'Sexuelle Dysfunktion', 'QT-Zeit-Verlängerung (Dosismax. 40mg, bei Älteren 20mg)'], ['Andere QT-verlängernde Arzneien', 'Serotonerge Substanzen (Serotoninsyndrom)', 'NSAR (Blutungsrisiko)'], 'Nicht abrupt absetzen (Absetzsymptome). EKG-Kontrolle wegen QT-Zeit.'),
  med('Escitalopram (Cipralex)', 'Escitalopram', 'S-Enantiomer von Citalopram (SSRI)', ['5 mg', '10 mg', '20 mg'], ['N1', 'N2', 'N3'], '1x täglich morgens', ['Übelkeit', 'Libidoverlust', 'Schlaflosigkeit', 'Geringere QT-Verlängerung als Citalopram'], ['MAO-Hemmer (mind. 14 Tage Abstand!)', 'Tramadol', 'Triptane']),
  med('Sertralin (Zoloft)', 'Sertralinhydrochlorid', 'SSRI', ['25 mg', '50 mg', '100 mg'], ['N1', 'N2', 'N3'], '1x täglich morgens oder abends zum Essen', ['Gastrointestinale Beschwerden (Durchfall/Übelkeit)', 'Schlaflosigkeit', 'Tremor', 'Sexuelle Dysfunktion'], ['Pimozid (kontraindiziert)', 'MAO-Hemmer', 'Blutverdünner']),
  med('Fluoxetin', 'Fluoxetinhydrochlorid', 'SSRI mit sehr langer Halbwertszeit', ['10 mg', '20 mg', '40 mg'], ['N1', 'N2', 'N3'], '1x täglich morgens', ['Agitiertheit', 'Gewichtsabnahme', 'Schlafstörungen'], ['Starker CYP2D6-Inhibitor (Tamoxifen-Wirkung blockiert!)', 'MAO-Hemmer'], 'Wegen langer HWZ (mehrere Wochen) langes Auswaschintervall beachten.'),
  med('Paroxetin (Seroxat)', 'Paroxetin', 'SSRI (stark anticholinerg & sedierend)', ['10 mg', '20 mg', '40 mg'], ['N1', 'N2', 'N3'], '1x täglich morgens zum Frühstück', ['Gewichtszunahme', 'Mundtrockenheit', 'Ausgeprägte Absetzsymptome'], ['CYP2D6-Substrate', 'Pravastatin']),
  med('Venlafaxin (Trevilor)', 'Venlafaxinhydrochlorid', 'SNRI (Serotonin- und Noradrenalin-Wiederaufnahmehemmer)', ['37.5 mg', '75 mg', '150 mg', '225 mg retard'], ['N1', 'N2', 'N3'], '1x täglich morgens mit den Mahlzeiten', ['Hypertonie (Blutdruckanstieg dosisabhängig)', 'Schwitzen (sehr häufig)', 'Übelkeit', 'Schlafstörungen', 'Schwere Absetzphänomene'], ['MAO-Hemmer (lebensbedrohlich)', 'Triptane', 'Tramadol'], 'Regelmäßige Blutdruckkontrollen. Sehr langsam ausschleichen!'),
  med('Mirtazapin (Remergil)', 'Mirtazapin', 'Noradrenerges & spezifisch serotonerges Antidepressivum (NaSSA)', ['15 mg', '30 mg', '45 mg Schmelztabletten'], ['N1', 'N2', 'N3'], '1x täglich ABENDS vor dem Schlafengehen', ['Ausgeprägte Sedierung / Schlafanstoßend', 'Starke Appetitsteigerung und deutliche Gewichtszunahme', 'Mundtrockenheit', 'Ödeme'], ['Alkohol', 'Benzodiazepine (verstärkte Sedierung)', 'MAO-Hemmer'], 'Ideal bei Depressionen mit Schlafstörungen und Gewichtsverlust.'),
  med('Bupropion (Elontril)', 'Bupropionhydrochlorid', 'NDRI (Noradrenalin- und Dopamin-Wiederaufnahmehemmer)', ['150 mg', '300 mg retard'], ['N1', 'N2', 'N3'], '1x täglich morgens (niemals abends wegen Schlaflosigkeit!)', ['Schlaflosigkeit', 'Kopfschmerzen', 'Gewichtsverlust (keine Gewichtszunahme!)', 'Krampfanfälle (dosisabhängig)'], ['Kombination mit anderen krampfschwellensenkenden Mitteln', 'MAO-Hemmer'], 'Kontraindiziert bei Epilepsie und Essstörungen (Bulimie/Anorexie). Keine sexuelle Dysfunktion.'),
  med('Amitriptylin (Saroten)', 'Amitriptylinhydrochlorid', 'Trizyklisches Antidepressivum (TCA) / Schmerzdistanzierung', ['10 mg', '25 mg', '50 mg', '75 mg retard'], ['N1', 'N2', 'N3'], '1x täglich abends 1-2 Stunden vor dem Schlafen', ['Mundtrockenheit', 'Obstipation', 'Harnverhalt', 'Tachykardie / QT-Verlängerung', 'Gewichtszunahme', 'Sedierung'], ['QT-Verlängerer', 'Anticholinergika', 'MAO-Hemmer', 'Alkohol'], 'Sehr häufig niedrigdosiert (10-25 mg) bei chronischen Schmerzen und Schlafstörungen.'),
  med('Doxepin', 'Doxepin', 'Trizyklisches Antidepressivum (sedierend)', ['10 mg', '25 mg', '50 mg', '100 mg'], ['N1', 'N2', 'N3'], '1x täglich zur Nacht', ['Starke Sedierung', 'Anticholinerge Effekte', 'Gewichtszunahme'], ['Alkohol', 'ZNS-Depressiva']),
  med('Opipramol (Insidon)', 'Opipramoldihydrochlorid', 'Sigma-Rezeptor-Ligand / Anxiolytikum & Beruhigungsmittel', ['50 mg', '100 mg'], ['N1', 'N2', 'N3'], '1-2x täglich, Schwerpunkt abends', ['Müdigkeit', 'Schwindel', 'Mundtrockenheit', 'Verstopfte Nase'], ['Alkohol', 'Sedativa'], 'Kein Abhängigkeitspotenzial, wirkt dämpfend und angstlösend.'),
  med('Trimipramin (Stangyl)', 'Trimipramin', 'Trizyklisches Antidepressivum (stark sedierend, nicht antriebssteigernd)', ['25 mg', '50 mg', '100 mg', 'Tropfen'], ['N1', 'N2', 'N3'], 'Abends vor dem Schlafen', ['Ausgeprägte Müdigkeit', 'Gewichtszunahme', 'Kreislaufbeschwerden'], ['Alkohol', 'QT-Verlängerer']),
  med('Trazodon (Thombran)', 'Trazodon', 'SARI (Serotonin-Wiederaufnahmehemmer & 5-HT2-Antagonist)', ['50 mg', '100 mg', '150 mg'], ['N1', 'N2', 'N3'], 'Abends vor dem Schlafen', ['Schlaffördernd', 'Hypotonie', 'Priapismus (seltene Dauererektion, Notfall!)'], ['Alkohol', 'Antihypertensiva']),
  med('Agomelatin (Valdoxan)', 'Agomelatin', 'Melatonerger Agonist (MT1/MT2) & 5-HT2c-Antagonist', ['25 mg'], ['N1', 'N2', 'N3'], '1x täglich vor dem Schlafengehen', ['Transaminasenanstieg (Lebertoxizität!)', 'Kopfschmerzen', 'Übelkeit'], ['Starke CYP1A2-Hemmer (Fluvoxamin, Ciprofloxacin streng kontraindiziert!)'], 'Leberwerte VOR Therapiebeginn und nach 3, 6, 12 und 24 Wochen zwingend kontrollieren!'),
  med('Quetiapin (Seroquel)', 'Quetiapinfumarat', 'Atypisches Antipsychotikum (Neuroleptikum)', ['25 mg', '50 mg', '100 mg', '200 mg', '300 mg retard'], ['N1', 'N2', 'N3'], 'Niedrigdosiert (25-50mg) abends zur Schlafförderung, höher bei Psychose/Bipolar', ['Starke Sedierung / Schläfrigkeit', 'Gewichtszunahme', 'Hypotonie', 'Mundtrockenheit', 'Metabolisches Syndrom'], ['CYP3A4-Hemmer/Induktoren', 'Alkohol', 'QT-Verlängerer'], 'In niedriger Dosis häufig Off-Label als Schlafmittel.'),
  med('Olanzapin (Zyprexa)', 'Olanzapin', 'Atypisches Neuroleptikum', ['2.5 mg', '5 mg', '10 mg', '15 mg', '20 mg'], ['N1', 'N2', 'N3'], '1x täglich abends', ['Massive Gewichtszunahme und Appetitsteigerung', 'Diabetes-Risiko', 'Sedierung', 'Periphere Ödeme'], ['Rauchen (beschleunigt Abbau)', 'Fluvoxamin', 'Carbamazepin'], 'Regelmäßige Kontrolle von Gewicht, Blutzucker und Lipiden.'),
  med('Risperidon (Risperdal)', 'Risperidon', 'Atypisches Antipsychotikum', ['0.5 mg', '1 mg', '2 mg', '3 mg', '4 mg'], ['N1', 'N2', 'N3'], '1-2x täglich', ['Extrapyramidale Bewegungsstörungen (EPMS dosisabhängig)', 'Prolaktinerhöhung (Gynäkomastie, Galaktorrhö)', 'Gewichtszunahme'], ['Levodopa (Wirkungsantagonismus)', 'Carbamazepin']),
  med('Aripiprazol (Abilify)', 'Aripiprazol', 'Partieller Dopamin-D2- und 5-HT1a-Agonist', ['5 mg', '10 mg', '15 mg', '30 mg'], ['N1', 'N2', 'N3'], '1x täglich morgens', ['Akathisie (motorische Unruhe)', 'Schlaflosigkeit', 'Übelkeit', 'Geringe Gewichtszunahme'], ['CYP2D6- und CYP3A4-Hemmer']),
  med('Haloperidol (Haldol)', 'Haloperidol', 'Klassisches hochpotentes Neuroleptikum', ['1 mg', '2 mg', '5 mg', '10 mg', 'Tropfen 2mg/ml'], ['N1', 'N2', 'N3'], 'Bei akuten psychotischen Erregungszuständen und Delir', ['Früh- und Spätdyskinesien (Blickkrämpfe, Zungen-Schlund-Krämpfe)', 'Parkinsonoid', 'Malignes neuroleptisches Syndrom'], ['QT-Verlängerer', 'Levodopa'], 'Frühdyskinesien mit Biperiden (Akineton) behandeln.'),
  med('Pipamperon (Dipiperon)', 'Pipamperon', 'Schwachpotentes Neuroleptikum / Schlaf & Unruhe im Alter', ['40 mg', 'Saft'], ['N1', 'N2', 'N3'], 'Abends bei seniler Unruhe und Schlafstörungen', ['Müdigkeit', 'Hypotonie', 'Kaum extrapyramidale Nebenwirkungen'], ['Alkohol', 'ZNS-Depressiva'], 'Häufig in der Geriatrie bei Demenz mit Unruhe.'),
  med('Melperon', 'Melperonhydrochlorid', 'Schwachpotentes Sedo-Neuroleptikum', ['25 mg', '50 mg', '100 mg'], ['N1', 'N2', 'N3'], 'Abends zur Nacht', ['Sedierung', 'Kreislaufdysregulation'], ['Alkohol', 'Antihypertensiva']),
  med('Promethazin (Atosil)', 'Promethazinhydrochlorid', 'Phenothiazin / Beruhigungsmittel & Antihistaminikum', ['25 mg', '50 mg', 'Tropfen'], ['N1', 'N2', 'N3'], 'Bei Unruhe oder Schlafstörungen abends', ['Starke Sedierung', 'Anticholinerge Wirkungen', 'Blutdruckabfall'], ['Alkohol', 'QT-Verlängernde Medikamente']),
  med('Lorazepam (Tavor)', 'Lorazepam', 'Benzodiazepin (Anxiolytikum / Beruhigungsmittel)', ['0.5 mg', '1 mg', '2 mg', '2.5 mg', 'Tavor Expidet'], ['N1', 'N2'], 'Bei akuten Panikattacken, Angstzuständen oder Erregung', ['Abhängigkeit und Toleranzentwicklung (bereits nach 2-4 Wochen!)', 'Sedierung', 'Muskelrelaxation (Sturzgefahr!)', 'Atemdepression bei Überdosierung', 'Paradoxe Reaktionen'], ['Alkohol (potenziert Wirkung dramatisch)', 'Opioide (tödliche Atemdepression möglich)'], 'STRENG KURZZEITIGE ANWENDUNG! Hohes Suchtrisiko.'),
  med('Diazepam (Valium)', 'Diazepam', 'Langwirksames Benzodiazepin (HWZ bis 100h)', ['2 mg', '5 mg', '10 mg', 'Tropfen', 'Rektaltuben'], ['N1', 'N2'], 'Bei akuten Krampfanfällen oder Angst', ['Kumulationsgefahr durch aktive Metaboliten', 'Hangover', 'Sturzrisiko'], ['Alkohol', 'Opioide']),
  med('Oxazepam (Adumbran)', 'Oxazepam', 'Kurzwirksames Benzodiazepin (keine aktiven Metaboliten)', ['10 mg', '50 mg'], ['N1', 'N2'], '1-3x täglich', ['Sedierung', 'Suchtpotenzial'], ['Alkohol'], 'Günstig bei Leberinsuffizienz, da direkte Glukuronidierung.'),
  med('Alprazolam (Xanax)', 'Alprazolam', 'Hochpotentes Anxiolytikum (Benzodiazepin)', ['0.5 mg', '1 mg'], ['N1', 'N2'], 'Bei Panikstörung', ['Sehr schnelles Abhängigkeitspotenzial', 'Entzugssymptome'], ['CYP3A4-Hemmer']),
  med('Zolpidem', 'Zolpidemtartrat', 'Z-Substanz / Nicht-Benzodiazepin-Hypnotikum', ['5 mg', '10 mg'], ['N1', 'N2'], 'Unmittelbar vor dem Zubettgehen einnehmen', ['Schlafwandeln / Amnesie (Somnambulismus)', 'Müdigkeit am Folgetag', 'Abhängigkeitspotenzial'], ['Alkohol', 'ZNS-Depressiva'], 'Nur zur Kurzzeitbehandlung (max. 4 Wochen).'),
  med('Zopiclon', 'Zopiclon', 'Z-Substanz (Einschlaf- und Durchschlafmittel)', ['3.75 mg', '7.5 mg'], ['N1', 'N2'], 'Direkt vor dem Einschlafen', ['Bitterer oder metallischer Geschmack am Morgen', 'Mundtrockenheit', 'Gewöhnung'], ['Alkohol', 'Sedativa']),
  med('Levetiracetam (Keppra)', 'Levetiracetam', 'Antiepileptikum (SV2A-Ligand)', ['250 mg', '500 mg', '750 mg', '1000 mg'], ['N1', 'N2', 'N3'], '2x täglich morgens und abends', ['Somnolenz', 'Aggression / Verhaltensänderungen', 'Schwindel', 'Müdigkeit'], ['Kaum hepatische Interaktionen (renale Elimination!)'], 'Häufiges Mittel der 1. Wahl bei fokalen und generalisierten Anfällen.'),
  med('Lamotrigin (Lamictal)', 'Lamotrigin', 'Antiepileptikum & Phasenprophylaxe Bipolar', ['25 mg', '50 mg', '100 mg', '200 mg'], ['N1', 'N2', 'N3'], '1-2x täglich, SEHR LANGSAM ÜBER WOCHEN EINSCHLEICHEN!', ['Schwere Hautreaktionen (Stevens-Johnson-Syndrom bei zu schneller Aufdosierung!)', 'Kopfschmerzen', 'Schwindel'], ['Valproinsäure (verdoppelt Lamotrigin-Spiegel -> Dosis halbieren!)', 'Orale Kontrazeptiva (senken Lamotrigin-Spiegel)'], 'STRENGES SCHLEICHSCHEMA einhalten zur Vermeidung tödlicher Hautreaktionen!'),
  med('Valproinsäure (Ergenyl / Orfiril)', 'Natriumvalproat / Valproinsäure', 'Breitband-Antiepileptikum', ['300 mg', '500 mg retard'], ['N1', 'N2', 'N3'], '2x täglich zu den Mahlzeiten', ['Hepatotoxizität', 'Pankreatitis', 'Tremor', 'Gewichtszunahme', 'Haarausfall', 'Teratogenität (Spina bifida)'], ['Carbapeneme (senken Valproat drastisch -> Anfallsgefahr!)', 'Lamotrigin'], 'STRENG KONTRAINDIZIERT bei Frauen im gebärfähigen Alter (Schwangerschaftsverhütungsprogramm!).'),
  med('Carbamazepin (Tegretal)', 'Carbamazepin', 'Natriumkanalblocker (Epilepsie & Trigeminusneuralgie)', ['200 mg', '400 mg retard'], ['N1', 'N2', 'N3'], '2-3x täglich zu den Mahlzeiten', ['Hyponatriämie (SIADH)', 'Schwindel', 'Ataxie', 'Agranulozytose', 'Starker CYP-Induktor'], ['Enorme Interaktionsvielfalt (Pille, DOAKs, Statine verlieren Wirkung!)'], 'Mittel der Wahl bei Trigeminusneuralgie.'),
  med('Madopar (Levodopa / Benserazid)', 'Levodopa/Benserazid', 'Dopamin-Vorstufe + DDC-Hemmer (Parkinson)', ['62.5 mg', '125 mg', '250 mg', 'LT'], ['N1', 'N2', 'N3'], 'Mindestens 30 min vor oder 90 min nach proteinreichen Mahlzeiten', ['Dyskinesien / Fluktuationen (On-Off)', 'Übelkeit zu Beginn', 'Orthostase', 'Visuelle Halluzinationen'], ['Eiweißreiche Nahrung (blockiert Resorption)', 'Neuroleptika (heben Wirkung auf)'], 'Niemals zusammen mit eiweißreicher Mahlzeit einnehmen!'),
  med('Sifrol (Pramipexol)', 'Pramipexol', 'Dopaminagonist (Parkinson & Restless Legs)', ['0.18 mg', '0.35 mg', '0.7 mg', 'retard'], ['N1', 'N2', 'N3'], 'Zu den Mahlzeiten', ['Plötzliche Schlafattacken am Tag', 'Impulskontrollstörungen (Spielsucht, Hypersexualität, Kaufsucht)', 'Ödeme'], ['Dopamin-Antagonisten'], 'Aufklärung über Impulskontrollstörungen obligatorisch.'),
  med('Donepezil (Aricept)', 'Donepezilhydrochlorid', 'Acetylcholinesterase-Hemmer (Alzheimer-Demenz)', ['5 mg', '10 mg'], ['N1', 'N2', 'N3'], '1x täglich abends vor dem Schlafen', ['Übelkeit/Erbrechen', 'Diarrhoe', 'Bradykardie / Synkopen', 'Schlaflosigkeit / Alpträume', 'Muskelkrämpfe'], ['Betablocker (erhöhtes Bradykardierisiko)', 'Anticholinergika (heben Wirkung auf)'], 'Vor Beginn EKG ableiten (Ausschluss Bradykardie / Sick-Sinus).'),
  med('Memantin (Axura / Ebixa)', 'Memantinhydrochlorid', 'NMDA-Rezeptor-Antagonist (moderate bis schwere Alzheimer-Demenz)', ['10 mg', '20 mg'], ['N1', 'N2', 'N3'], '1x täglich zur gleichen Zeit', ['Schwindel', 'Kopfschmerzen', 'Obstipation', 'Hypertonie'], ['Amantadin', 'Ketamin', 'L-Dopa']),
  med('Sumatriptan (Imigran)', 'Sumatriptansuccinat', '5-HT1B/1D-Rezeptoragonist (Akute Migräne & Clusterkopfschmerz)', ['50 mg', '100 mg', 'Nasenspray 20mg', 'Pen s.c. 6mg'], ['N1', 'N2'], 'Bei Beginn der Kopfschmerzphase (nicht in der Aura!)', ['Engegefühl in der Brust (Präkordialdruck)', 'Flush / Hitzegefühl', 'Schwindel', 'Kribbeln/Parästhesien'], ['Ergotamine (mind. 24h Abstand!)', 'SSRI/SNRI (Serotoninsyndrom-Risiko)', 'MAO-Hemmer'], 'Kontraindiziert bei KHK, Zustand nach Myokardinfarkt, Schlaganfall oder unkontrolliertem Bluthochdruck.'),
  med('Zolmitriptan (Ascotop)', 'Zolmitriptan', 'Triptan (auch als Schmelztablette)', ['2.5 mg', '5 mg'], ['N1', 'N2'], 'Bei Migräneattacke', ['Engegefühl im Hals/Brustkorb', 'Müdigkeit'], ['Cimetidin', 'MAO-Hemmer']),
  med('Rizatriptan (Maxalt)', 'Rizatriptan', 'Schnell wirkendes Triptan', ['5 mg', '10 mg Schmelztabletten'], ['N1', 'N2'], 'Bei Migränebeginn auf der Zunge zergehen lassen', ['Schwindel', 'Somnolenz'], ['Propranolol (verdoppelt Rizatriptan-Spiegel -> Dosis auf 5mg reduzieren!)']),
  med('Naratriptan (Formigran)', 'Naratriptan', 'Langwirksames Triptan (rezeptfrei 2 Tabl.)', ['2.5 mg'], ['N1'], 'Bei Migränekopfschmerz', ['Geringere Nebenwirkungen als Sumatriptan', 'Längere Wirkdauer (weniger Recurrence)'], ['Ergotamine'])
];
catalog.push(...neuro);

// 8. Infektiologie & Antibiotika
const infect = [
  med('Amoxicillin', 'Amoxicillin-Trihydrat', 'Aminopenicillin (Breitband)', ['500 mg', '750 mg', '1000 mg'], ['N1', 'N2', 'N3'], 'Alle 8 Stunden (3x täglich) mit reichlich Wasser', ['Gastrointestinale Beschwerden', 'Arzneimittelexanthem (Ampicillin-Exanthem bei EBV/Pfeiffer-Drüsenfieber!)', 'Diarrhoe'], ['Allopurinol (vermehrt Hautausschläge)', 'Methotrexat', 'Orale Kontrazeptiva'], 'Kontraindiziert bei Penicillinallergie. Nicht bei V.a. Mononukleose (Pfeiffer)!'),
  med('Amoxicillin / Clavulansäure (Augmentan)', 'Amoxicillin / Clavulansäure', 'Aminopenicillin + Beta-Laktamase-Inhibitor', ['500/125 mg', '875/125 mg'], ['N1', 'N2', 'N3'], '2-3x täglich zu Beginn einer Mahlzeit einnehmen (bessere Verträglichkeit)', ['Häufig Diarrhoe (durch Clavulansäure)', 'Cholestatischer Ikterus / Leberschaden', 'Pilzinfektionen (Candida)'], ['Cumarine', 'Methotrexat'], 'Zur Mahlzeit einnehmen mindert Magen-Darm-Nebenwirkungen deutlich.'),
  med('Cefuroxim axetil', 'Cefuroximaxetil', 'Oralcephalosporin der 2. Generation', ['250 mg', '500 mg'], ['N1', 'N2', 'N3'], '2x täglich ca. 15 Minuten NACH einer Mahlzeit (erhöht Bioverfügbarkeit)', ['Diarrhoe', 'Übelkeit', 'Eosinophilie', 'Kreuzallergie bei Penicillinallergie (ca. 5-10%)'], ['Antazida und PPI (senken Bioverfügbarkeit)', 'Schleifendiuretika'], 'Immer nach dem Essen einnehmen.'),
  med('Cefpodoxim proxetil', 'Cefpodoxim', 'Oralcephalosporin der 3. Generation', ['100 mg', '200 mg'], ['N1', 'N2', 'N3'], '2x täglich zu den Mahlzeiten', ['Diarrhoe', 'Kopfschmerz'], ['PPI']),
  med('Ciprofloxacin (Ciprobay)', 'Ciprofloxacin', 'Fluorchinolon / Gyrasehemmer', ['250 mg', '500 mg', '750 mg'], ['N1', 'N2', 'N3'], '2x täglich unabhängig von Mahlzeiten (NICHT mit Milchprodukten!)', ['Tendinitis und Achillessehnenruptur (auch noch Monate nach Einnahme!)', 'Aortendissektion', 'QT-Zeit-Verlängerung', 'ZNS-Toxizität (Psychose, Verwirrung, Krampfanfälle)', 'Photosensibilität'], ['Kationen (Milch, Calcium, Eisen, Magnesium blockieren Resorption komplett!)', 'Theophyllin (Toxizität!)', 'Tizanidin (kontraindiziert)'], 'Rote-Hand-Brief: Strenge Indikationsstellung! Bei Sehnenschmerzen sofort stoppen.'),
  med('Levofloxacin (Tavanic)', 'Levofloxacin', 'Fluorchinolon (Respiratorisch)', ['250 mg', '500 mg'], ['N1', 'N2', 'N3'], '1-2x täglich nüchtern oder zum Essen (ohne Milch!)', ['Sehnenschäden', 'QT-Verlängerung', 'Neuropathie'], ['Multivalente Kationen', 'Vitaminpräparate']),
  med('Moxifloxacin (Avalox)', 'Moxifloxacin', 'Gyrasehemmer der 4. Generation', ['400 mg'], ['N1', 'N2'], '1x täglich', ['QT-Verlängerung (Torsade de Pointes)', 'Lebertoxizität'], ['Klasse-IA- und III-Antiarrhythmika']),
  med('Azithromycin (Zithromax)', 'Azithromycin', 'Makrolid-Antibiotikum (Azalid)', ['250 mg', '500 mg (meist 3-Tages-Therapie)'], ['N1', 'N2'], '1x täglich für 3 Tage (lange Gewebshalbwertszeit von ca. 70h)', ['Gastrointestinale Krämpfe', 'QT-Intervall-Verlängerung', 'Hörstörungen bei hoher Dosis'], ['QT-verlängernde Substanzen', 'Antazida zeitversetzt einnehmen'], 'Wirkt durch hohe Gewebekonzentration noch Tage nach Einnahmeende nach.'),
  med('Clarithromycin (Klacid)', 'Clarithromycin', 'Makrolid-Antibiotikum (starker CYP3A4-Hemmer)', ['250 mg', '500 mg'], ['N1', 'N2', 'N3'], '2x täglich morgens und abends', ['Geschmacksstörung (metallischer Geschmack)', 'Übelkeit', 'QT-Verlängerung'], ['STATINE (strikte Kontraindikation wegen Rhabdomyolyse-Gefahr!)', 'Colchicin', 'Carbamazepin'], 'Statine (Simvastatin, Atorvastatin) während der Einnahme zwingend pausieren!'),
  med('Doxycyclin', 'Doxycyclin-Hyclat', 'Tetracyklin-Antibiotikum (Borreliose, Atemwege, Chlamydien)', ['100 mg', '200 mg'], ['N1', 'N2', 'N3'], 'Mit VIEL WASSER in AUFRECHTER HALTUNG zu einer Mahlzeit (keine Milch!)', ['Ösophagitis und schwere Speiseröhrenulzera bei Feststecken der Tablette', 'Photosensibilisierung (Sonnenbrandgefahr!)', 'Zahnverfärbungen'], ['Milchprodukte, Calcium, Eisen, Magnesium (mind. 2-3h Abstand!)', 'Isotretinoin (Pseudotumor cerebri)'], 'Niemals im Liegen einnehmen! Sonne und Solarium meiden.'),
  med('Cotrimoxazol (Sulfamethoxazol / Trimethoprim)', 'Cotrimoxazol', 'Folsäureantagonisten-Kombination', ['400/80 mg', '800/160 mg (Cotrim forte)'], ['N1', 'N2', 'N3'], '2x täglich morgens und abends mit reichlich Flüssigkeit', ['Hyperkaliämie (durch Trimethoprim)', 'Allergische Hautreaktionen (Stevens-Johnson)', 'Knochenmarksuppression', 'Nierenfunktionseinschränkung'], ['Methotrexat (erhöhte Zytotoxizität)', 'ACE-Hemmer/Sartane (schwere Hyperkaliämien)', 'Cumarine'], 'Viel trinken zur Vermeidung von Kristallurie.'),
  med('Fosfomycin (Monuril)', 'Fosfomycin-Trometamol', 'Einmaldosis-Antibiotikum (unkomplizierter HWI)', ['3000 mg Granulatbeutel'], ['N1'], 'EINMALIGE Einnahme abends vor dem Schlafen nach Entleerung der Blase', ['Diarrhoe', 'Kopfschmerzen', 'Übelkeit'], ['Metoclopramid senkt Serumspiegel'], 'Vor der Einnahme Blase entleeren; Granulat in Wasser auflösen.'),
  med('Nitrofurantoin', 'Nitrofurantoin retard', 'Harnwegstherapeutikum', ['50 mg', '100 mg'], ['N1', 'N2', 'N3'], '2-4x täglich zu den Mahlzeiten', ['Dunkelgelbe bis braune Urinverfärbung (harmlos)', 'Lungenfibrose bei Langzeiteinnahme', 'Polyneuropathie'], ['Magnesiumantazida'], 'Kontraindiziert bei GFR < 45 ml/min.'),
  med('Metronidazol (Clont)', 'Metronidazol', 'Nitroimidazol (Anaerobier & Protozoen)', ['250 mg', '400 mg', '500 mg'], ['N1', 'N2', 'N3'], '2-3x täglich während oder nach den Mahlzeiten', ['Metallischer Geschmack', 'Dunkelfärbung des Urins', 'Neurotoxizität (Kribbeln, Taubheit)'], ['ALKOHOL ABSOLUT VERBOTEN (schweres Antabus-Syndrom: Flush, Erbrechen, Kollaps!)', 'Warfarin'], 'Strengstes Alkoholverbot während und 48h nach der Therapie!'),
  med('Clindamycin (Sobelin)', 'Clindamycinhydrochlorid', 'Lincosamid (Knochen, Zähne, Staphylokokken)', ['150 mg', '300 mg', '600 mg'], ['N1', 'N2', 'N3'], '3-4x täglich mit einem großen Glas Wasser', ['Pseudomembranöse Kolitis durch Clostridioides difficile (sehr hohes Risiko!)', 'Diarrhoe'], ['Erythromycin (Wirkungsverlust)', 'Muskelrelaxanzien'], 'Bei wässrigen Durchfällen sofort Arzt informieren und absetzen.'),
  med('Fluconazol (Diflucan)', 'Fluconazol', 'Triazol-Antimykotikum (Candida)', ['50 mg', '100 mg', '150 mg (Einmaldosis bei Vaginalsoor)', '200 mg'], ['N1', 'N2'], 'Unabhängig von den Mahlzeiten', ['Leberwerterhöhung', 'Kopfschmerz', 'GI-Beschwerden'], ['Starker CYP2C9- und CYP3A4-Hemmer (verstärkt Cumarine, DOAKs, Phenytoin, Statine)']),
  med('Terbinafin (Lamisil)', 'Terbinafin', 'Antimykotikum (Nagel- und Fußpilz)', ['250 mg'], ['N1', 'N2', 'N3'], '1x täglich über mehrere Wochen/Monate', ['Geschmacksverlust (über Wochen anhaltend)', 'Hepatotoxizität (Leberwerte kontrollieren!)', 'Magen-Darm-Störungen'], ['CYP2D6-Substrate (Metoprolol, Antidepressiva)']),
  med('Aciclovir (Zovirax)', 'Aciclovir', 'Virustatikum (Herpes simplex, Herpes zoster)', ['200 mg', '400 mg', '800 mg', 'Creme'], ['N1', 'N2', 'N3'], '5x täglich alle 4 Stunden tagsüber mit viel Wasser', ['Nephrotoxizität (Kristallausfällung in Nierentubuli bei zu wenig Trinken)', 'Kopfschmerzen', 'Schwindel'], ['Nephrotoxische Substanzen', 'Probenecid'], 'Während der Therapie auf reichliche Flüssigkeitszufuhr achten!'),
  med('Valaciclovir (Valtrex)', 'Valaciclovir', 'Prodrug von Aciclovir (höhere Bioverfügbarkeit)', ['500 mg', '1000 mg'], ['N1', 'N2', 'N3'], 'Bei Zoster 3x täglich 1000 mg über 7 Tage', ['Kopfschmerzen', 'Übelkeit', 'Schwindel'], ['Nephrotoxische Arzneien'], 'Viel trinken.'),
  med('Brivudin (Zostex)', 'Brivudin', 'Nukleosid-Analogon (Herpes zoster)', ['125 mg'], ['N1'], '1x TÄGLICH für genau 7 Tage zur gleichen Uhrzeit', ['Übelkeit', 'Kopfschmerzen'], ['5-FLUOROURACIL / CAPECITABIN (ABSOLUTE TÖDLICHE KONTRAINDIKATION!)'], 'TÖDLICHE WECHSELWIRKUNG mit 5-FU/Capecitabin (mind. 4 Wochen Abstand zwingend!).')
];
catalog.push(...infect);

// 9. Urologie, Gynäkologie & Hormone
const uroGyn = [
  med('Tamsulosin (Alna)', 'Tamsulosinhydrochlorid', 'Selektiver Alpha-1A-Adrenorezeptorantagonist (BPH)', ['0.4 mg Retardkapseln'], ['N1', 'N2', 'N3'], '1x täglich nach dem Frühstück', ['Retrograde Ejakulation (trockener Samenerguss)', 'Schwindel / Orthostase', 'Intraoperative Floppy Iris Syndrome (IFIS bei Katarakt-OP!)'], ['Andere Antihypertensiva', 'PDE-5-Hemmer'], 'Augenarzt vor Star-OP unbedingt über Tamsulosin informieren!'),
  med('Silodosin (Urorec)', 'Silodosin', 'Hochselektiver Alpha-1A-Blocker', ['4 mg', '8 mg'], ['N1', 'N2', 'N3'], '1x täglich zum Essen', ['Retrograde Ejakulation (sehr häufig)', 'Schwindel'], ['Starke CYP3A4-Hemmer']),
  med('Finasterid (Proscar / Propecia)', 'Finasterid', '5-Alpha-Reduktase-Inhibitor (Typ II)', ['1 mg (Alopezie)', '5 mg (BPH)'], ['N1', 'N2', 'N3'], '1x täglich unabhängig von Mahlzeiten', ['Erektile Dysfunktion', 'Libidoverlust', 'Gynäkomastie', 'Depressive Verstimmungen (Post-Finasterid-Syndrom)', 'Halbiert den PSA-Wert!'], ['Keine relevanten Wechselwirkungen'], 'WICHTIG: Halbiert den PSA-Wert! Bei Prostatakrebsvorsorge gemessenen PSA verdoppeln.'),
  med('Dutasterid (Avodart)', 'Dutasterid', 'Dualer 5-Alpha-Reduktasehemmer (Typ I und II)', ['0.5 mg Weichkapseln'], ['N1', 'N2', 'N3'], '1x täglich ganz schlucken', ['Sexuelle Dysfunktion', 'Brustschwellung', 'PSA-Senkung um 50%'], ['CYP3A4-Hemmer']),
  med('Solifenacin (Vesikur)', 'Solifenacinsuccinat', 'Urologisches Spasmolytikum / Anticholinergikum (Dranginkontinenz)', ['5 mg', '10 mg'], ['N1', 'N2', 'N3'], '1x täglich als ganze Tablette mit Wasser', ['Mundtrockenheit (sehr häufig)', 'Obstipation', 'Verschwommenes Sehen', 'Harnverhalt'], ['Ketoconazol', 'Andere Anticholinergika'], 'Kontraindiziert bei Harnretention, schwerer Kolitis und Myasthenia gravis.'),
  med('Tolterodin (Detrusitol)', 'Tolterodin', 'Anticholinergikum bei überaktiver Blase', ['2 mg', '4 mg retard'], ['N1', 'N2', 'N3'], '1x täglich', ['Mundtrockenheit', 'Obstipation', 'Trockene Augen'], ['CYP3A4-Hemmer']),
  med('Trospiumchlorid (Spasmex)', 'Trospiumchlorid', 'Quartäres Anticholinergikum (überwindet Blut-Hirn-Schranke kaum)', ['20 mg', '30 mg', '45 mg'], ['N1', 'N2', 'N3'], 'Morgens und abends nüchtern vor dem Essen', ['Mundtrockenheit', 'Kaum ZNS-Nebenwirkungen (ideal bei Demenz)'], ['Nahrungsaufnahme vermindert Resorption']),
  med('Mirabegron (Betmiga)', 'Mirabegron', 'Beta-3-Adrenozeptor-Agonist (Dranginkontinenz)', ['25 mg', '50 mg'], ['N1', 'N2', 'N3'], '1x täglich', ['Blutdruckanstieg (Hypertonie)', 'Harnwegsinfekte', 'Tachykardie'], ['CYP2D6-Inhibitor (erhöht Metoprolol)'], 'Kontraindiziert bei schwerer unkontrollierter Hypertonie (≥180/110 mmHg).'),
  med('Sildenafil (Viagra)', 'Sildenafilcitrat', 'PDE-5-Inhibitor (Erektile Dysfunktion)', ['25 mg', '50 mg', '100 mg'], ['N1', 'N2'], 'Ca. 30-60 Minuten vor sexueller Aktivität auf nüchternen Magen', ['Kopfschmerzen', 'Gesichtsrötung (Flush)', 'Dyspepsie', 'Blausehen (Cyanopsie)', 'Nasale Kongestion'], ['NITRATE UND NO-DONATOREN STRENG KONTRAINDIZIERT (Gefahr tödlichen Blutdruckabfalls!)', 'Alpha-Blocker'], 'Niemals zusammen mit Nitrosprays oder Molsidomin einnehmen!'),
  med('Tadalafil (Cialis)', 'Tadalafil', 'PDE-5-Inhibitor (Lange Wirkdauer bis 36 Stunden)', ['5 mg (Täglich)', '10 mg', '20 mg'], ['N1', 'N2'], 'Bei Bedarf mind. 30 min vorher oder 5 mg täglich (auch bei BPH)', ['Myalgie / Rückenschmerzen', 'Kopfschmerzen', 'Dyspepsie', 'Flush'], ['Nitrate streng verboten', 'Antihypertensiva'], 'Keine Nitrate innerhalb von 48 Stunden!'),
  med('Vardenafil (Levitra)', 'Vardenafil', 'PDE-5-Hemmer', ['10 mg', '20 mg', 'Schmelztabletten'], ['N1', 'N2'], '25-60 min vor Aktivität', ['Kopfschmerzen', 'Flush'], ['Nitrate']),
  med('Desogestrel (Cerazette / Minipille)', 'Desogestrel', 'Reines Gestagen-Monopräparat (Östrogenfreie Pille)', ['75 µg'], ['N1', 'N2', 'N3'], 'Täglich zur EXAKT GLEICHEN UHRZEIT ohne Einnahmepause', ['Zwischenblutungen / Spotting', 'Akne', 'Stimmungsschwankungen'], ['Johanniskraut, Carbamazepin, Rifampicin (Verhütungsschutz aufgehoben!)'], 'Zeitfenster von max. 12 Stunden darf nicht überschritten werden.'),
  med('Dienogest (Visanne)', 'Dienogest', 'Gestagen (Endometriose-Therapie)', ['2 mg'], ['N1', 'N2', 'N3'], 'Täglich ohne Pause', ['Kopfschmerzen', 'Depressive Verstimmung', 'Brustspannen'], ['CYP3A4-Induktoren']),
  med('Levonorgestrel (Pille danach / Unofem)', 'Levonorgestrel', 'Notfallkontrazeptivum', ['1.5 mg Einzeldosis'], ['N1'], 'So schnell wie möglich nach ungeschütztem Verkehr (innerhalb max 72h)', ['Übelkeit (bei Erbrechen <3h Tablette wiederholen!)', 'Zyklusverschiebung', 'Unterleibsschmerzen'], ['Enzyminduktoren (doppelte Dosis 3mg nötig)']),
  med('EllaOne (Ulipristalacetat)', 'Ulipristalacetat', 'Selektiver Progesteron-Rezeptor-Modulator (Notfallkontrazeption)', ['30 mg'], ['N1'], 'Innerhalb von maximal 120 Stunden (5 Tagen)', ['Kopfschmerzen', 'Übelkeit', 'Dysmenorrhoe'], ['CYP3A4-Induktoren']),
  med('Estradiol Gel (Gynokadin)', 'Estradiol-0.06%', 'Transdermales Östrogen (Hormonersatztherapie HRT)', ['Dosiergel 0.6 mg/Hub'], ['N1', 'N2', 'N3'], '1x täglich morgens dünn auf Oberarm oder Oberschenkel einreiben', ['Brustspannen', 'Zwischenblutungen', 'Kopfschmerzen', 'Thromboserisiko (transdermal geringer als oral)'], ['Rauchen erhöht kardiovaskuläres Risiko'], 'Bei vorhandenem Uterus zwingend mit Gestagen kombinieren!'),
  med('Famenita / Utrogest (Progesteron)', 'Mikronisiertes natürliches Progesteron', 'Gestagen (Endometriumschutz bei HRT)', ['100 mg', '200 mg Weichkapseln'], ['N1', 'N2', 'N3'], 'Abends vor dem Schlafen oral oder vaginal', ['Müdigkeit / Schläfrigkeit (sedierende Wirkung)', 'Schwindel'], ['Sedativa']),
  med('Letrozol (Femara)', 'Letrozol', 'Aromatasehemmer (Mammakarzinom)', ['2.5 mg'], ['N1', 'N2', 'N3'], '1x täglich', ['Hitzewallungen', 'Arthralgien / Gelenkschmerzen', 'Osteoporose', 'Müdigkeit'], ['Östrogene heben Wirkung auf']),
  med('Anastrozol (Arimidex)', 'Anastrozol', 'Aromatasehemmer', ['1 mg'], ['N1', 'N2', 'N3'], '1x täglich', ['Gelenkschmerzen', 'Hitzewallungen', 'Knochendichteminderung'], ['Tamoxifen']),
  med('Tamoxifen', 'Tamoxifencitrat', 'SERM (Selektiver Estrogenrezeptormodulator)', ['10 mg', '20 mg', '30 mg'], ['N1', 'N2', 'N3'], '1x täglich zum Essen', ['Thromboembolien', 'Endometriumhyperplasie / -karzinom', 'Hitzewallungen', 'Sehstörungen'], ['CYP2D6-Inhibitoren (Paroxetin, Fluoxetin blockieren Bildung des aktiven Endoxifens!)'], 'Keine starken CYP2D6-hemmenden Antidepressiva kombinieren!')
];
catalog.push(...uroGyn);

// 10. Vitamine, Mineralstoffe, Dermatologie & Augen
const misc = [
  med('Dekristol (Vitamin D3 20000 IE)', 'Colecalciferol', 'Vitamin D3 hochdosiert', ['20000 I.E. Weichkapseln'], ['N1', 'N2'], 'Nach ärztlicher Anweisung (z.B. 1x wöchentlich) mit einer fettreichen Mahlzeit', ['Hyperkalzämie (bei toxischer Überdosierung)', 'Nierensteine', 'Übelkeit'], ['Thiaziddiuretika (erhöhtes Hyperkalzämierisiko)', 'Herzglykoside'], 'Fettlösliches Vitamin; immer mit fettreicher Nahrung einnehmen.'),
  med('Vigantolvit / Vigantol (Vitamin D3 1000/2000 IE)', 'Colecalciferol', 'Vitamin D3 täglich', ['1000 IE', '2000 IE'], ['N1', 'N2', 'N3'], '1x täglich zu einer Mahlzeit', ['Sehr gut verträglich'], ['Thiazide']),
  med('Ferro sanol duodenal (Eisen-II-glycin-sulfat)', 'Eisen(II)-glycin-sulfat-Komplex', 'Eisensupplement (Eisenmangelanämie)', ['50 mg', '100 mg magensaftresistente Kapseln'], ['N1', 'N2', 'N3'], 'Morgens nüchtern 1h vor dem Frühstück mit Orangensaft (Vitamin C fördert Resorption)', ['Schwarzer Stuhl (völlig harmlos)', 'Obstipation oder Diarrhoe', 'Übelkeit / Magenschmerzen'], ['Kaffee, schwarzer Tee, Milchprodukte, Antazida, PPI (blockieren Resorption drastisch!)', 'Thyroxin, Doxycyclin (2-3h Abstand zwingend)'], 'Schwarzer Stuhl ist normal. Nicht mit Kaffee oder Milch einnehmen!'),
  med('Vitamin B12 (Cyanocobalamin / Hydroxocobalamin)', 'Cyanocobalamin', 'Vitamin B12 hochdosiert', ['1000 µg Tabletten', 'Ampullen i.m./s.c.'], ['N1', 'N2', 'N3'], '1x täglich oder intramuskulär bei Malabsorption', ['Sehr selten Akne oder allergische Reaktionen'], ['PPI und Metformin vermindern B12-Resorption']),
  med('Folsäure', 'Folsäure (Vitamin B9)', 'Schwangerschaftsprophylaxe & Anämie', ['0.4 mg', '0.8 mg', '5 mg'], ['N1', 'N2', 'N3'], '1x täglich', ['Sehr gut verträglich'], ['Antiepileptika']),
  med('Magnesium Verla (Magnesium)', 'Magnesiumcitrat / Magnesiumaspartat', 'Mineralstoff / Muskelkrampf-Therapie', ['Granulatbeutel', 'Kautabletten', 'Dragees'], ['N1', 'N2', 'N3'], '1-2x täglich in Wasser aufgelöst trinken', ['Weicher Stuhl / Diarrhoe bei höherer Dosierung'], ['Fluorchinolone, Tetrazykline, Eisen (mind. 2h Abstand einhalten!)'], 'Bei Niereninsuffizienz Gefahr von Hypermagnesiämie.'),
  med('Kalinor (Kaliumchlorid / Citrat)', 'Kaliumchlorid / Kaliumhydrogencarbonat', 'Kaliumsubstitution', ['Brausetabletten 40 mmol'], ['N1', 'N2', 'N3'], 'In einem Glas Wasser aufgelöst zu einer Mahlzeit trinken', ['Magenreizung', 'Hyperkaliämie (lebensgefährliche Herzrhythmusstörungen!)'], ['Kaliumsparende Diuretika (Spironolacton)', 'ACE-Hemmer', 'Sartane'], 'Streng kontraindiziert bei Niereninsuffizienz und Hyperkaliämie.'),
  med('Zinkorotat / Zink Verla', 'Zinkorotat', 'Spurenelement (Immunsystem & Haut)', ['10 mg', '25 mg'], ['N1', 'N2', 'N3'], 'Mit Abstand zu den Mahlzeiten', ['Übelkeit bei Nüchtern-Einnahme'], ['Kupfermangel bei Langzeiteinnahme', 'Eisen verringert Zinkaufnahme']),
  med('Xalatan (Latanoprost)', 'Latanoprost', 'Prostaglandin-Analogon (Glaukom / Grüner Star)', ['0.005% Augentropfen'], ['N1', 'N2', 'N3'], '1x TÄGLICH ABENDS 1 Tropfen in das betroffene Auge', ['Dauerhafte Dunkelfärbung der Iris (braune Pigmentierung)', 'Verlängerung und Verdichtung der Wimpern', 'Augenrötung / Brennen'], ['Andere Augentropfen mit 5 min Abstand'], 'Nur 1x täglich abends anwenden.'),
  med('Cosopt (Dorzolamid / Timolol)', 'Dorzolamid / Timolol', 'Kombinations-Augentropfen gegen Glaukom', ['20 mg/5 mg/ml'], ['N1', 'N2', 'N3'], '2x täglich morgens und abends', ['Bitterer Geschmack im Mund', 'Brennen im Auge', 'Systemische Betablocker-Wirkung (Bradykardie, Asthmaanfall!)'], ['Systemische Betablocker'], 'Tränenpünktchen nach Tropfen 1 min zudrücken zur Senkung systemischer Resorption.'),
  med('Bepanthen Wund- und Heilsalbe', 'Dexpanthenol', 'Dermatikum / Wundheilungsfördernd', ['5% Salbe'], ['N1', 'N2', 'N3'], 'Mehrmals täglich dünn auf die betroffene Hautstelle auftragen', ['Sehr selten Überempfindlichkeit'], ['Keine relevanten Wechselwirkungen']),
  med('Advantan (Methylprednisolonaceponat)', 'Methylprednisolonaceponat', 'Topisches Kortikosteroid (Klasse III)', ['0.1% Creme / Salbe'], ['N1', 'N2'], '1x täglich dünn auftragen (max. 4-12 Wochen)', ['Hautatrophie (Dünnerwerden der Haut bei Übergebrauch)', 'Striae', 'Teleangiektasien'], ['Nicht im Gesicht über längere Zeit anwenden']),
  med('Dermoxin (Clobetasolpropionat)', 'Clobetasolpropionat', 'Sehr stark wirksames topisches Kortikoid (Klasse IV)', ['0.05% Salbe/Creme'], ['N1', 'N2'], '1-2x täglich sehr dünn (max. 2 Wochen)', ['Hautatrophie', 'Steroidakne', 'Nebennierenrinden-Suppression'], ['Großflächige Anwendung vermeiden'])
];
catalog.push(...misc);

console.log(`Part 2 generated ${catalog.length} additional medications.`);

// Save to data/medications_db.json
let addedCount = 0;
for (const item of catalog) {
  const key = item.name.toLowerCase().trim();
  if (!existingNames.has(key)) {
    existingDb.push(item);
    existingNames.add(key);
    addedCount++;
  }
}

fs.writeFileSync(dbPath, JSON.stringify(existingDb, null, 2), 'utf8');
console.log(`Saved to ${dbPath}: ${addedCount} items added in Part 2. Total now in DB: ${existingDb.length}`);

// Update src/data/topMedicationsCatalog.ts
const catalogTsContent = `// Auto-generated curated Top Medications Catalog
// Contains ${existingDb.length} verified medications for instant offline & client-side lookup.

import { MedicationSuggestion } from '../services/medicationDatabase';

export const TOP_MEDICATIONS_CATALOG: MedicationSuggestion[] = ${JSON.stringify(existingDb, null, 2)};
`;

fs.writeFileSync(path.resolve('src/data/topMedicationsCatalog.ts'), catalogTsContent, 'utf8');
console.log(`Updated src/data/topMedicationsCatalog.ts successfully with ${existingDb.length} medications.`);
