// Autogenerated Classical Authors Registry
// Mappings for Samuel Hahnemann, James Tyler Kent, and Constantine Hering

export interface ClassicalAuthorInfo {
  hahnemann: boolean;
  kent: boolean;
  hering: boolean;
  boericke?: boolean;
  boger?: boolean;
  allen?: boolean;
}

export type ClassicalAuthorFilterKey = 'all' | 'hahnemann' | 'kent' | 'hering' | 'boericke' | 'boger' | 'allen';

export const CLASSICAL_AUTHORS_MAP: Record<string, ClassicalAuthorInfo> = {
  "abies-canadensis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "abies-nigra": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "abrotanum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "absinthium": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "acidum-aceticum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "acidum-benzoicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "acidum-fluoricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "acidum-nitricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "acidum-phosphoricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "acidum-sulfuricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "aconitum-napellus": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "aesculus-hippocastanum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "aethusa-cynapium": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "agaricus-muscarius": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "agnus-castus": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "allium-cepa": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "aloe-socotrina": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "alumina": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "ambra-grisea": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "ammonium-carbonicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "anacardium-orientale": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "antimonium-crudum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "antimonium-tartaricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "apis-mellifica": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "argentum-nitricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "arnica-montana": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "arsenicum-album": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "arum-triphyllum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "aurum-metallicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "avena-sativa": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "bacillinum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "baptisia-tinctoria": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "baryta-carbonica": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "belladonna": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "bellis-perennis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "berberis-vulgaris": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "borax-veneta": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "bryonia-alba": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "cactus-grandiflorus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "calcarea-carbonica": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "calcarea-fluorica": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "calcarea-phosphorica": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "calendula-officinalis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "camphora": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "cantharis-vesicatoria": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "carbo-vegetabilis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "causticum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "chamomilla": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "chelidonium-majus": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "china-officinalis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "cicuta-virosa": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "cimicifuga-racemosa": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "cina-maritima": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "cocculus-indicus": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "coffea-cruda": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "colchicum-autumnale": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "colocynthis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "conium-maculatum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "cuprum-metallicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "digitalis-purpurea": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "dioscorea-villosa": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "drosera-rotundifolia": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "dulcamara": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "echinacea-angustifolia": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "eupatorium-perfoliatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "euphrasia-officinalis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "ferrum-metallicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "ferrum-phosphoricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "galphimia-glauca": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "gelsemium-sempervirens": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "glonoinum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "graphites": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "hamamelis-virginiana": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "helleborus-niger": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "hepar-sulfuris": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "hydrastis-canadensis": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "hyoscyamus-niger": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "hypericum-perforatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "ignatia-amara": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "iodium": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "ipecacuanha": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "iris-versicolor": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "kalium-bichromicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "kalium-carbonicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "kalium-phosphoricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "lachesis-muta": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "ledum-palustre": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "luffa-operculata": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "lycopodium-clavatum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "magnesia-phosphorica": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "mercurius-solubilis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "mezereum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "millefolium": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "natrium-muriaticum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "natrium-sulfuricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "nitricum-acidum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "nux-vomica": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "opium": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "petroleum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "phosphoricum-acidum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "phosphorus": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "phytolacca-americana": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "podophyllum-peltatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "pulsatilla-pratensis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "pyrogenium": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "rhododendron-chrysanthum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "rhus-toxicodendron": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "ruta-graveolens": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "sabadilla": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "sambucus-nigra": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "sanguinaria-canadensis": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "sepia-officinalis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "silicea": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "spigelia-anthelmia": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "spongia-tosta": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "staphisagria": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "stramonium": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "sulphur": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "symphytum-officinale": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "tabacum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "thuja-occidentalis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "tuberculinum-bovinum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "urtica-urens": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "uva-ursi": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "veratrum-album": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "zincum-metallicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "actaea-spicata": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "adonis-vernalis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "alstonia-scholaris": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "alumina-phosphorica": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "alumina-silicata": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "ambrosia-artemisiifolia": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ammoniacum-gummi": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ammonium-benzoicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ammonium-bromatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ammonium-causticum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ammonium-iodatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ammonium-muriaticum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "ammonium-phosphoricum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "ammonium-valerianicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "amylenum-nitrosum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "anagallis-arvensis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "angustura-vera": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "anhalonium-lewinii": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "anisum-stellatum": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "anthemis-nobilis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "anthracinum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "antimonium-arsenicosum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "antimonium-iodatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "antimonium-sulfuratum-aurantiacum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "apium-graveolens": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "apocynum-androsaemifolium": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "apocynum-cannabinum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "apomorphinum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "aralia-racemosa": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "aranea-diadema": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "argentum-cyanatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "argentum-iodatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "argentum-metallicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "aristolochia-clematitis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "arsenicum-bromatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "arsenicum-hydrogenisatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "arsenicum-iodatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "arsenicum-metallicum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "arsenicum-sulfuratum-flavum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "arsenicum-sulfuratum-rubrum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "artemisia-vulgaris": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "arum-dracontium": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "arum-maculatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "arundo-mauritanica": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "asa-foetida": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "asarum-europaeum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "asclepias-cornuti": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "asclepias-tuberosa": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "asparagus-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "astacus-fluviatilis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "asterias-rubens": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "atropinum-sulfuricum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "aurum-arsenicosum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "aurum-bromatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "aurum-iodatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "aurum-muriaticum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "aurum-muriaticum-kalinatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "aurum-muriaticum-natronatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "aurum-sulfuratum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "badiaga": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "balsamum-peruvianum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "baryta-acetica": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "baryta-iodata": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "baryta-muriatica": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "benzinum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "benzinum-dinitricum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "berberis-aquifolium": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "bismuthum-subnitricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "blatta-americana": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "blatta-orientalis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "boldo": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "bothrops-lanceolatus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "bovista-lycoperdon": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "brachyglottis-repens": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "bromium": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "bufo-rana": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "cadmium-metallicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "cadmium-sulfuratum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "cainca": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "caladium-seguinum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "calcarea-arsenicosa": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "calcarea-hypophosphorosa": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "calcarea-iodata": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "calcarea-silicata": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "calcarea-sulfurica": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "calotropis-gigantea": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "cannabis-indica": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "cannabis-sativa": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "capsicum-annuum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "carbo-animalis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "carbolicum-acidum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "carboneum-sulfuratum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "carduus-marianus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "castanea-vesca": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "castor-equi": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "castoreum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "caulophyllum-thalictroides": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "ceanothus-americanus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "cedron": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "cenchris-contortrix": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "centranthus-ruber": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "chenopodium-anthelminticum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "chimaphila-umbellata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "chininum-arsenicosum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "chininum-sulfuricum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "chionanthus-virginica": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "chlorum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "cinnabaris": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "cinnamomum-ceylanicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "cistus-canadensis": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "clematis-erecta": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "cobaltum-metallicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "coca": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "coccus-cacti": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "collinsonia-canadensis": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "comocladia-dentata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "convallaria-majalis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "copaiva-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "corallium-rubrum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "cornus-circinata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "cornus-florida": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "crocus-sativus": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "crotalus-horridus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "croton-tiglium": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "cubeba-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "cuprum-aceticum": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "cuprum-arsenicosum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "curare": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "cyclamen-europaeum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "damiana": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "daphne-indica": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "dirca-palustris": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "dolichos-pruriens": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "doryphora-decemlineata": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "elaps-corallinus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "elaterium": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "epilobium-palustre": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "epiphegus-virginiana": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "equisetum-hyemale": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "erigeron-canadense": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "eriodictyon-californicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "eryngium-aquaticum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "eucalyptus-globulus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "eugenia-jambos": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "euonymus-atropurpureus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "eupatorium-purpureum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "euphorbia-corollata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "euphorbium-officinarum": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "eupion": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ferrum-aceticum": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "ferrum-arsenicosum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "ferrum-iodatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "ferrum-magneticum": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "ferrum-muriaticum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ferrum-picricum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ferrum-sulfuricum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "formica-rufa": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "fragaria-vesca": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "fraxinus-americana": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "gambogia": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "gentiana-lutea": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "geranium-maculatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "geum-rivale": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "gnaphalium-polycephalum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "gossypium-herbaceum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "granatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "gratiola-officinalis": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "grindelia-robusta": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "guaco": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "guaiacum-officinale": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "guarea-trichilioides": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "gymnocladus-canadensis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "haematoxylon-campechianum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "hedeoma-pulegioides": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "hekla-lava": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "helianthus-annuus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "helonias-dioica": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "hydrangea-arborescens": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "hydrocotyle-asiatica": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "hydrocyanicum-acidum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "iberis-amara": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "illicium-anisatum": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "indigo-tinctoria": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "indium-metallicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "inula-helenium": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "iridium-metallicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "jaborandi": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "jacaranda-caroba": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "jalapa": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "jatropha-curcas": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "juglans-cinerea": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "juglans-regia": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "kalium-arsenicosum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "kalium-bromatum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "kalium-chloricum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "kalium-cyanatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "kalium-ferrocyanatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "kalium-hypophosphorosum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "kalium-iodatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "kalium-muriaticum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "kalium-nitricum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "kalium-oxalicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "kalium-permanganicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "kalium-silicatum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "kalium-sulfuricum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "kalmia-latifolia": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "kreosotum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "lac-caninum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "lac-defloratum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "lachnanthes-tinctoria": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "lactuca-virosa": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "lapis-albus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "lappa-arctium": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "latrodectus-mactans": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "laurocerasus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "leptandra-virginica": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "lilium-tigrinum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "linum-usitatissimum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "lithium-carbonicum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "lobelia-cardinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "lobelia-inflata": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "lycopus-virginicus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "lyssinum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "magnesia-carbonica": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "magnesia-muriatica": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "magnesia-sulfurica": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "magnolia-grandiflora": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "mancinella": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "mandragora-officinarum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "manganum-aceticum": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "manganum-metallicum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "marum-verum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "medorrhinum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "melilotus-alba": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "menyanthes-trifoliata": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "mephitis-mephitica": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "mercurialis-perennis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "mercurius-auratus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "mercurius-biniodatus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "mercurius-corrosivus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "mercurius-cyanatus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "mercurius-dulcis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "mercurius-iodatus-flavus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "mercurius-iodatus-ruber": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "mercurius-sulfuricus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "mercurius-vivus": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "mitchella-repens": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "moschus": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "murex-purpurea": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "muriaticum-acidum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "mygale-lasiodora": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "myrica-cerifera": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "myristica-sebifera": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "myrtus-communis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "naja-tripudians": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "naphthalinum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "narcissus-pseudonarcissus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "nasturtium-aquaticum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "natrum-arsenicosum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "natrum-bicarbonicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "natrum-carbonicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "natrum-hypochlorosum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "natrum-iodatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "natrum-nitricum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "natrum-phosphoricum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "natrum-salicylicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "natrum-silicofluoricum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "niccolum-metallicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "niccolum-sulfuricum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "nuphar-luteum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "nux-moschata": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "ocimum-canum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "oenanthe-crocata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "oleander": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "oleum-animale": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "oleum-jecoris-aselli": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "onosmodium-virginianum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "origanum-majorana": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "osmium-metallicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ostrya-virginica": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ova-gallina-pellicula": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "oxalicum-acidum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "oxytropis-lamberti": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "paeonia-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "palladium-metallicum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "pareira-brava": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "paris-quadrifolia": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "passiflora-incarnata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "petroselinum-sativum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "phellandrium-aquaticum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "physostigma-venenosum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "picricum-acidum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "pimpinella-saxifraga": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "pinus-sylvestris": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "piper-methysticum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "piper-nigrum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "plantago-major": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "platinum-metallicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "platinum-muriaticum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "plumbum-aceticum": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "plumbum-carbonicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "plumbum-iodatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "plumbum-metallicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "polygonum-hydropiperoides": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "polyporus-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "populus-tremuloides": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "pothos-foetidus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "prunus-spinosa": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "psorinum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "ptelea-trifoliata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "quassia-amara": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "quebracho": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "quercus-robur": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "radix-angelicae": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "radium-bromatum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "ranunculus-acris": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ranunculus-bulbosus": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "ranunculus-sceleratus": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "raphanus-sativus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ratanhia-peruviana": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "rheum-palmatum": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "rhus-aromatica": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "rhus-glabra": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "rhus-venenata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ricinus-communis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "robinia-pseudoacacia": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "rosa-damascena": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "rumex-crispus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "sabina": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "saccharum-album": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "saccharum-lactis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "salicylicum-acidum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "salix-nigra": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "sanicula-aqua": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "santoninum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "saponaria-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "sarsaparilla": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "secale-cornutum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "selenium-metallicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "sempervivum-tectorum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "senecio-aureus": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "senega": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "sinapis-alba": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "sinapis-nigra": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "solanum-carolinense": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "solanum-nigrum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "solidago-virgaurea": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "spiraea-ulmaria": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "squilla-maritima": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "stachys-betonica": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "stannum-iodatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "stannum-metallicum": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "sticta-pulmonaria": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "stillingia-sylvatica": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "strontium-carbonicum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "strontium-iodatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "strophanthus-hispidus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "strychninum-metallicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "strychninum-phosphoricum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "sulfurosum-acidum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "sulphur-iodatum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "syphilinum": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "tanacetum-vulgare": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "taraxacum-officinale": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "tarentula-cubensis": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "tarentula-hispana": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "taxus-baccata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "tellurium-metallicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "terebinthina": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "theridion-curassavicum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "thlaspi-bursa-pastoris": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "thyroidinum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "tilia-europaea": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "trillium-pendulum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "trombidium-muscae": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ulmus-campestris": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "uranium-nitricum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "usnea-barbata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "ustilago-maidis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "vaccininum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "valeriana-officinalis": {
    "hahnemann": true,
    "kent": true,
    "hering": true
  },
  "variolinum": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "veratrum-viride": {
    "hahnemann": false,
    "kent": true,
    "hering": true
  },
  "verbascum-thapsus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "verbena-hastata": {
    "hahnemann": true,
    "kent": false,
    "hering": true
  },
  "vesicaria-communis": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "viburnum-opulus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "viburnum-prunifolium": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "vinca-minor": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "viola-odorata": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "viola-tricolor": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "vipera-berus": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "viscum-album": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "wyethia-helenioides": {
    "hahnemann": false,
    "kent": true,
    "hering": false
  },
  "xanthoxylum-fraxineum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "yucca-filamentosa": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "zincum-aceticum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "zincum-arsenicosum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "zincum-bromatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "zincum-carbonicum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "zincum-cyanatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "zincum-iodatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "zincum-muriaticum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "zincum-oxydatum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "zincum-sulfuricum": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "zingiber-officinale": {
    "hahnemann": false,
    "kent": false,
    "hering": true
  },
  "acalypha-indica": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "aletris-farinosa": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "alfalfa": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "alstonia-constricta": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "ammoniacum-dorema": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "amyl-nitrosum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "arbutus-andrachne": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "areca-catechu": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "argemone-mexicana": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "azadirachta-indica": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "baccharis-cordifolia": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "boletus-laricis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "bovista-gigantea": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cahinca": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "canna-angustifolia": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "capsella-bursa-pastoris": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "condurango": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "corydalis-formosa": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cotyledon-umbilicus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "crataegus-oxyacantha": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cynodon-dactylon": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cypripedium-pubescens": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "ephedra-vulgaris": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "epigea-repens": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "euonymus-europaeus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "fagopyrum-esculentum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "ficus-religiosa": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "galium-aparine": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "guatteria-gaumeri": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "hecla-lava": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "heliotropium-peruvianum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "hyoscyaminum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "ichthyolum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "ilicium-anisatum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "jonosia-asoca": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "lathyrus-sativus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "lemna-minor": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "linaria-vulgaris": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "medusa": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "melilotus-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "myosotis-arvensis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "oxydendrum-arboreum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "psoralea-corylifolia": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "scutellaria-lateriflora": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "abroma-augusta": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "adoxa-moschatellina": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "agave-americana": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "ailanthus-glandulosa": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "alchemilla-vulgaris": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "alnus-serrulata": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "althaea-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "ambrosia-artemisiaefolia": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "ampelopsis-quinquefolia": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "anthoxanthum-odoratum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "aralia-hispida": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "arbutus-unedo": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "arctium-lappa": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "aristolochia-milhomens": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "asclepias-incarnata": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "asperula-odorata": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "aspidium-filix-mas": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "aspidosperma-quebracho": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "balsamum-tolutanum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "barosma-crenata": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "beta-vulgaris": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "betonica-aquatica": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "borago-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "botulinum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "buxus-sempervirens": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cajuputum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "calluna-vulgaris": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "caltha-palustris": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "canchalagua": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "carica-papaya": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cascara-sagrada": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cascarilla": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cassia-sophera": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "centaurea-cyanus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "centaurium-erythraea": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cephalandra-indica": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cetraria-islandica": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "chaparro-amargoso": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cheiranthus-cheiri": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "chelone-glabra": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "chloralum-hydratum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cholesterinum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cineraria-maritima": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "cochlearia-armoracia": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "codeinum-purum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "commelina-communis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "dictamnus-albus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "duboisia-myoporoides": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "echinacea-purpurea": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "erodios-cicutarium": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "eschscholtzia-californica": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "eugenia-jambosa": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "galega-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "gentiana-quinqueflora": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "ginkgo-biloba": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "humulus-lupulus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "justicia-adhatoda": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "lecithinum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "leonurus-cardiaca": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "liatris-spicata": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "lycopus-europaeus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "marrubium-vulgare": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "melissa-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "mentha-piperita": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "mentha-pulegium": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "myrrha": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "nasturtium-officinale": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "nyctanthes-arbor-tristis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "oenothera-biennis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "olea-europaea": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "ornithogalum-umbellatum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "orthosiphon-stamineus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "paullinia-cupana": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "phaseolus-nanus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "pichi-pichi": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "piscidia-erythrina": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "populus-candicans": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "primula-obconica": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "prunus-virginiana": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "quercus-glandium-spiritus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "rhamnus-californica": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "sabal-serrulata": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "salvia-officinalis": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "sarcolacticum-acidum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "scilla-maritima": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "scrophularia-nodosa": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "sedum-acre": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "silphium-laciniatum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "spartium-scoparium": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "allium-sativum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "aquilegia-vulgaris": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "amygdalus-persica": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "abelmoschus": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "aconitum-lycoctonum": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "adlumia-fungosa": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  },
  "agrostemma-githago": {
    "hahnemann": false,
    "kent": false,
    "hering": false,
    "boericke": true
  }
};

import { getBogerSynopticEntry } from './bogerSynopticData';
import { getAllenKeynoteEntry } from './allenKeynotesData';

export function getRemedyClassicalAuthors(remedyId: string): { hahnemann: boolean; kent: boolean; hering: boolean; boericke: boolean; boger: boolean; allen: boolean } {
  const info = CLASSICAL_AUTHORS_MAP[remedyId];
  const hasBoger = getBogerSynopticEntry(remedyId) !== null;
  const hasAllen = getAllenKeynoteEntry(remedyId) !== null;
  if (!info) {
    return { hahnemann: false, kent: false, hering: false, boericke: true, boger: hasBoger, allen: hasAllen };
  }
  return {
    hahnemann: Boolean(info.hahnemann),
    kent: Boolean(info.kent),
    hering: Boolean(info.hering),
    boericke: info.boericke !== undefined ? Boolean(info.boericke) : true,
    boger: info.boger !== undefined ? Boolean(info.boger) : hasBoger,
    allen: info.allen !== undefined ? Boolean(info.allen) : hasAllen,
  };
}

export function matchesAuthorFilter(remedyId: string, filter: ClassicalAuthorFilterKey): boolean {
  if (filter === 'all') return true;
  const authors = getRemedyClassicalAuthors(remedyId);
  return Boolean(authors[filter]);
}
